 
GO
/****** Object:  UserDefinedFunction [dbo].[fn_FaturaTutarBul]    Script Date: 05/14/2010 15:24:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE   FUNCTION [dbo].[fn_FaturaTutarBul] ( @DOSYANO  VARCHAR (15), @GELISNO VARCHAR(15), @KARTNO VARCHAR(15),@KDV INT )
RETURNS FLOAT
AS 
BEGIN
DECLARE  @TUTAR FLOAT
 SELECT @TUTAR=SUM(TUTAR) FROM FATURA F 
		WHERE F.DOSYANO=@DOSYANO 
		AND F.GELISNO=@GELISNO 
		AND F.KARTNO=@KARTNO 
		AND F.KDV=@KDV
RETURN @TUTAR
           

END




