
/****** Object:  StoredProcedure [dbo].[p_G2LKS_FaturaHizmetBilgisi]    Script Date: 05/14/2010 15:18:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Date	: 2008-10-30 13:45
Author	: Emre Baytar
Desc.	: Parametreleri verilen faturanýn hizmet bilgilerini getiren sorgudur.

p_G2LKS_FaturaHizmetBilgisi '01-51989',4,1,'Erog'
p_G2LKS_FaturaOdemeBilgisi '01-51989',4,1,'KOÇ AL'
*/
CREATE PROC [dbo].[p_G2LKS_FaturaHizmetBilgisi] @DOSYANO VARCHAR(15) , @GELISNO INT, @KARTNO INT, @KIME VARCHAR(100)
AS BEGIN

IF @KIME <> 'Katký'
BEGIN
SELECT
	FT.DOSYANO, FT.GELISNO, FT.KARTNO, ADSOYAD = K.AD+' '+K.SOYAD,
	G.KURUM,
	ACIKLAMA = 'HÝZMETLER',
	MUHKODU = I.MUHKODU , 
	FB.FATURANO,
	FB.MUHAKTAR,
	TUTAR = CASE WHEN FB.KDVDURUM = 'Dahil' THEN CONVERT(MONEY,SUM(FT.TUTAR / ( 1+ (FT.KDV/100.0 )) ) )
				ELSE
			CONVERT(MONEY,SUM(FT.TUTAR))
	END

FROM FATURA FT  INNER JOIN FATBASLIK FB ON FT.DOSYANO = FB.DOSYANO AND FT.GELISNO = FB.GELISNO AND FT.KARTNO = FB.KARTNO
				INNER JOIN GELISLER G ON FB.DOSYANO = G.DOSYANO AND FB.GELISNO = G.GELISNO
				INNER JOIN KIMLIK K ON G.DOSYANO = K.DOSYANO
				INNER JOIN KURUM KUR ON G.KURUM = KUR.KURUM
				INNER JOIN ISLEMLER I ON I.KOD = FT.KOD
WHERE
	G.DOSYANO = @DOSYANO AND
	G.GELISNO = @GELISNO AND
	FB.KARTNO = @KARTNO
GROUP BY I.MUHKODU, FT.DOSYANO, FT.GELISNO, FT.KARTNO, K.AD+' '+K.SOYAD, FB.KDVDURUM, FB.FATURANO, G.KURUM, 	FB.MUHAKTAR
END
ELSE IF @KIME ='Katký'
BEGIN

SELECT
	FT.DOSYANO, FT.GELISNO, FT.KARTNO, ADSOYAD = K.AD+' '+K.SOYAD,
	G.KURUM,
	ACIKLAMA = 'HÝZMETLER',
	MUHKODU = CASE WHEN FT.ACIKLAMA ='Hasta Katký Payý' THEN '600.01.0004' ELSE '' END , 
	FB.FATURANO,
	FB.MUHAKTAR,
	TUTAR = CASE WHEN FB.KDVDURUM = 'Dahil' THEN CONVERT(MONEY,SUM(FT.TUTAR / ( 1+FT.KDV/100.0 ) ) )
				ELSE
			CONVERT(MONEY,SUM(FT.TUTAR))
	END

FROM FATURA FT  INNER JOIN FATBASLIK FB ON FT.DOSYANO = FB.DOSYANO AND FT.GELISNO = FB.GELISNO AND FT.KARTNO = FB.KARTNO
				INNER JOIN GELISLER G ON FB.DOSYANO = G.DOSYANO AND FB.GELISNO = G.GELISNO
				INNER JOIN KIMLIK K ON G.DOSYANO = K.DOSYANO
				INNER JOIN KURUM KUR ON G.KURUM = KUR.KURUM

WHERE
	G.DOSYANO = @DOSYANO AND
	G.GELISNO = @GELISNO AND
	FB.KARTNO = @KARTNO
GROUP BY   FT.DOSYANO, FT.GELISNO, FT.KARTNO, K.AD+' '+K.SOYAD, FB.KDVDURUM, FB.FATURANO, G.KURUM , FT.ACIKLAMA, 	FB.MUHAKTAR


END

END






