

/****** Object:  StoredProcedure [dbo].[p_G2LKS_FaturalariListele]    Script Date: 05/14/2010 15:22:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



/*
2007-06-07 17:30 DEÐÝÞTÝRME
-- Rehberdeki anakuruma göre filtreleme eklendi.
-- Kullanýcýya göre filtreleme eklendi
---------------------------
2006-11-17 15:00 OLUÞTURMA 
EMRE BAYTAR
Verilen tarih aralýðýnda kesilmiþ faturalarý listeler

2008-10-30 Emre Baytar

p_G2LKS_FaturalariListele '','','','','2005-01-01','2007-12-05',0,0,0,999999,'False'

BELGETURU = 0: Hepsi, 1: Fatura , 2: Fiþ
 exec p_G2LKS_FaturalariListele '','','','','2010-04-22 00:00:00','2010-04-23 23:59:00',1,0,0,0,'False',4
*/
ALTER       PROC [dbo].[p_G2LKS_FaturalariListele] 
	@KURUM VARCHAR(100),
	@REFERANS VARCHAR(100),
	@ANAKURUM VARCHAR(100),
	@KULLANICI VARCHAR(40),
	@BASLA SMALLDATETIME,
	@BITIS SMALLDATETIME,
	@BELGETURU SMALLINT,
	@AKTARILMIS INT ,
	@ILKFATNO INT,
	@SONFATNO INT,
	@TUMUSECILI VARCHAR(5),
	@SUBEID INT
AS 
BEGIN
DECLARE @BELGE VARCHAR(10)
SELECT @BELGE= CASE WHEN @BELGETURU = 0 THEN '%'
	            WHEN @BELGETURU = 1 THEN 'Fatura'
                    WHEN @BELGETURU = 2 THEN 'Fiþ'
	ELSE '%'
	END


	  SET @KURUM=@KURUM+'%'
	  SET @REFERANS=@REFERANS+'%'
	  SET @KULLANICI = @KULLANICI+'%'
	  SET @ANAKURUM = @ANAKURUM+'%'

	PRINT('KURUM:'+@KURUM)
	PRINT('REF:'+@KURUM)
	PRINT('KULL:'+@KURUM)
	PRINT('ANAKURM:'+@KURUM)
	PRINT('BELGE:'+@KURUM)

	IF @ILKFATNO = 0 SET @ILKFATNO = 0
	IF @SONFATNO = 0 SET @SONFATNO = 99999999

	
	SELECT DISTINCT
		SEC=@TUMUSECILI,
		K.DOSYANO,
		ADSOYAD = K.AD+' '+K.SOYAD ,
	        FB.GELISNO,
		G.KURUM,
		FB.FATURANO, 
		FB.FATURATARIH,
		FB.KARTNO,
		FATURA_TUTARI= ROUND(FB.FATURA_TUTARI,2),
		FB.LOTNO,
	    FB.KIME,
		MUHASEBEKODU = CASE WHEN FB.KIME = 'Katký' AND G.SUBE_ID=4 THEN '120.03.01.004' -- kartal katký fat
							WHEN FB.KIME = 'Katký' AND G.SUBE_ID=2 THEN '120.03.02.004' -- pendik katký fat
							WHEN FB.KIME = 'Katký' AND G.SUBE_ID=3 THEN '120.03.03.004' -- fethiye katký fat							
			ELSE KM.MUHASEBEKODU
			END,
		MUHAKTAR = ISNULL(MUHAKTAR,0) ,
		G.REFERANS,
		AKTARMANOTU,
		AKTARMATARIHI,
		BELGE, 
		TURU,
		KULLANICIADI = ISNULL(KL.KULLANICIADI,''),
		ANAKURUM = ISNULL(R.ANAFIRMA,''),
-----------------------------------------------------------------------------------------
-- TOPLAM FATURA TUTARI
		TOPLAMFATURA = 
			(
			  SELECT SUM(FATURA_TUTARI) FROM 
						FATBASLIK FB INNER JOIN GELISLER G ON 
					FB.DOSYANO = G.DOSYANO AND
					FB.GELISNO = G.GELISNO
			     INNER JOIN KIMLIK K ON
					G.DOSYANO = K.DOSYANO
			     INNER JOIN KURUM KR ON 
					G.KURUM = KR.KURUM
	WHERE
		KIME NOT IN ('Sanal','Ýptal') AND
		ISNULL(G.KURUM,'') LIKE @KURUM AND
		ISNULL(G.REFERANS,'') LIKE @REFERANS AND
		FB.FATURATARIH BETWEEN @BASLA AND @BITIS AND
		ISNULL(MUHAKTAR,0) <= @AKTARILMIS AND
		ISNULL(BELGE,'') LIKE @BELGE AND
		CONVERT(INT,ISNULL(FB.FATURANO,'0')) >= @ILKFATNO AND
		CONVERT(INT,ISNULL(FB.FATURANO,'0')) <= @SONFATNO AND
		ISNULL(KL.KULLANICIADI,'') LIKE @KULLANICI AND
		ISNULL(R.ANAFIRMA,'') LIKE @ANAKURUM
		AND G.SUBE_ID = @SUBEID
		
			)
-- TOPLAM FATURA TUTARI
-------------------------------------------------------------------------------------------			    
	INTO #FaturalarTemp
	FROM
		FATBASLIK FB INNER JOIN GELISLER G ON 
					FB.DOSYANO = G.DOSYANO AND
					FB.GELISNO = G.GELISNO
			     INNER JOIN KIMLIK K ON
					G.DOSYANO = K.DOSYANO
			     INNER JOIN KURUM KR ON 
					G.KURUM = KR.KURUM
				 LEFT OUTER JOIN KURUMMUHASEBEKODLARI KM ON G.KURUM = KM.KURUM AND 
				                                            G.SUBE_ID = KM.SUBEID	
			     LEFT OUTER JOIN REHBER R ON
					G.REFERANSKOD = R.KOD
			     LEFT OUTER JOIN KULLAN KL ON
					KL.KULLANICI = FB.KULLANICI
	WHERE
		    ISNULL(KIME,'') NOT IN ('Sanal','Ýptal') 
		AND ISNULL(G.KURUM,'') LIKE @KURUM 
		AND ISNULL(G.REFERANS,'') LIKE @REFERANS 
		AND FB.FATURATARIH BETWEEN @BASLA AND @BITIS 
		AND ISNULL(MUHAKTAR,0) <= @AKTARILMIS 
		AND ISNULL(BELGE,'') LIKE @BELGE 
		AND CONVERT(INT,ISNULL(FB.FATURANO,'0')) >= @ILKFATNO 
		AND CONVERT(INT,ISNULL(FB.FATURANO,'0')) <= @SONFATNO 
		AND ISNULL(KL.KULLANICIADI,'') LIKE @KULLANICI 
		AND ISNULL(R.ANAFIRMA,'') LIKE @ANAKURUM
		AND G.SUBE_ID = @SUBEID
		

	ORDER BY FB.FATURANO
	
	  SELECT * FROM #FaturalarTemp
	
END


