 
GO
/****** Object:  StoredProcedure [dbo].[p_G2LKS_FaturaKDVBilgisi]    Script Date: 05/14/2010 15:20:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Date	: 2008-10-30 13:45
Author	: Emre Baytar
Desc.	: Parametreleri verilen faturanýn kdv bilgilerini getiren sorgudur.

p_G2LKS_FaturaKDVBilgisi 'O-00359',2,1
*/
CREATE proc [dbo].[p_G2LKS_FaturaKDVBilgisi] @DOSYANO VARCHAR(15), @GELISNO INT, @KARTNO INT
AS BEGIN

SELECT
	FB.DOSYANO, FB.GELISNO, FB.KARTNO, ADSOYAD = K.AD+' '+K.SOYAD, G.KURUM,
	ACIKLAMA = 'KDV',
	MUHKODU = GT.DEGER, 
	FB.FATURANO,
	TUTAR = CASE WHEN FB.KDVDURUM = 'Dahil' THEN CONVERT(MONEY,SUM(FT.TUTAR)) - CONVERT(MONEY,SUM(FT.TUTAR / ( 1+FT.KDV/100.0 ) ) )
				ELSE
			CONVERT(MONEY,SUM(FT.TUTAR * ( 1+FT.KDV/100.0 ) ) ) - CONVERT(MONEY,SUM(FT.TUTAR))
	END

FROM FATURA FT  INNER JOIN FATBASLIK FB ON FT.DOSYANO = FB.DOSYANO AND FT.GELISNO = FB.GELISNO AND FT.KARTNO = FB.KARTNO
				INNER JOIN GELISLER G ON FB.DOSYANO = G.DOSYANO AND FB.GELISNO = G.GELISNO
				INNER JOIN KIMLIK K ON G.DOSYANO = K.DOSYANO
				INNER JOIN KURUM KUR ON G.KURUM = KUR.KURUM
				INNER JOIN GENOTIPINI GT ON GT.ANAHTAR = FT.KDV AND GT.BOLUM='G2LKS_KDV_ESLE' 
WHERE
	G.DOSYANO = @DOSYANO AND
	G.GELISNO = @GELISNO AND
	FB.KARTNO = @KARTNO
GROUP BY  FB.DOSYANO, FB.GELISNO, FB.KARTNO, K.AD+' '+K.SOYAD, FB.KDVDURUM, FT.KDV, GT.DEGER, FB.FATURANO, G.KURUM

END

