SELECT DK.ID KLASORID, DK.USTID KLASORUSTID 
  , KLASORAD = CAST ( DK.AD AS NVARCHAR ( 260 ) ) 
   -- , AD = CAST ( DK.AD AS NVARCHAR ( 260 ) ) 
   --, (SELECT AD FROM DOKUMANKLASOR WHERE USTID = DK.USTID) AS KLASORAD 
   , D.ID, D.BELGENO, D.DURUM, D.AD, D.KONU, D.TUR, D.KLASOR,D.ESKIKLASOR
   , D.EKLEYEN, D.EKLEMETARIHI, D.GIZLILIKDERECESI, D.TARIH, D.GELEN_EVRAK_NUMARASI
   , D.EVRAK_DOSYA_KODU,D.EVRAK_ICERIGI, D.ACIKLAMA

  , IMAJ.ID IMAJ_ID, IMAJ.VARSAYILAN, IMAJ.REHBERID	IMAJ_REHBERID, IMAJ.ICDIS, IMAJ.YERI IMAJ_YERI, IMAJ.YER_ID	
IMAJ_YER_ID
  , IMAJ.DURUM IMAJ_DURUM, IMAJ.BELGENO IMAJ_BELGENO, IMAJ.SURUM	IMAJ_SURUM, IMAJ.TUR IMAJ_TUR, 
IMAJ.BELGEADI IMAJ_BELGEADI
  , IMAJ.BELGE IMAJ_BELGE, IMAJ.ACIKLAMA IMAJ_ACIKLAMA, IMAJ.EKLEYEN IMAJ_EKLEYEN, IMAJ.EKLEMETARIHI 
IMAJ_EKLEMETARIHI
  , IMAJ.DEGISTIREN IMAJ_DEGISTIREN, IMAJ.DEGISTIRMETARIHI IMAJ_DEGISTIRMETARIHI, IMAJ.SUBEID	IMAJ_SUBEID, 
IMAJ.ONAY IMAJ_ONAY
  , IMAJ.BELGETURU IMAJ_BELGETURU, IMAJ.BOYUT IMAJ_BOYUT, IMAJ.ONAYLAYACAK IMAJ_ONAYLAYACAK
	FROM DOKUMANKLASOR DK
	  INNER JOIN DOKUMAN  D ON D.KLASOR = DK.ID
	   LEFT JOIN IMAJ  ON IMAJ.YER_ID = D.ID 
	   --INNER JOIN DOKUMANYETKI DY ON DY.YERI= 321 AND DY.YERID=D.ID AND DY.REHBERID>0
