
SELECT DK.ID, DK.USTID, AD = CAST ( DK.AD AS NVARCHAR ( 260 ) ) 
    , D.ID, D.BELGENO, D.DURUM, D.AD, D.KONU, D.TUR, D.KLASOR,D.ESKIKLASOR, D.EKLEMETARIHI, D.GIZLILIKDERECESI, D.TARIH, D.GELEN_EVRAK_NUMARASI,D.EVRAK_DOSYA_KODU,D.EVRAK_ICERIGI, D.ACIKLAMA
	, IMAJ.*
	FROM DOKUMANKLASOR DK
	  INNER JOIN DOKUMAN  D ON D.KLASOR = DK.ID
	   LEFT JOIN IMAJ  ON IMAJ.YER_ID = D.ID 
	WHERE DK.USTID  < -999 and DK.USTID> -5000
		

order by DK.USTID DESC, DK.ID DESC, 
D.ID
