WITH Dizin AS (
	SELECT ID, USTID, AD = CAST ( AD AS NVARCHAR ( 260 ) ) 
	FROM DOKUMANKLASOR 
	WHERE USTID  < -999 and USTID> -5000
		UNION ALL
		
	SELECT A.ID , A.USTID, AD = CAST ( V.AD+ '\' + A.AD AS NVARCHAR ( 260 ) ) 
	FROM DOKUMANKLASOR A
		INNER JOIN Dizin V ON V.ID = A.USTID 
	) SELECT 
	 DISTINCT Dizin.*, D.* 
	 from Dizin
	   INNER JOIN DOKUMAN  D ON D.KLASOR = Dizin.ID

order by Dizin.USTID DESC, Dizin.ID DESC, 
D.ID
