object Siramatik: TSiramatik
  Left = 100
  Top = 85
  BorderStyle = bsNone
  Caption = 'GenS'#305'ramatik'
  ClientHeight = 704
  ClientWidth = 1158
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poDefault
  WindowState = wsMaximized
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object PanelUstBilgi: TJvNavPanelHeader
    Left = 0
    Top = 0
    Width = 1158
    Height = 113
    Align = alTop
    Alignment = taCenter
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -40
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
    WordWrap = True
    ColorFrom = clBlack
    ColorTo = 14408667
    ImageIndex = 0
    object ImageLogo: TImage
      Left = 1030
      Top = 0
      Width = 128
      Height = 113
      Align = alRight
      Stretch = True
      Transparent = True
      ExplicitLeft = 1003
    end
    object ImageDoktor: TImage
      Left = 0
      Top = 0
      Width = 137
      Height = 113
      Align = alLeft
      Stretch = True
      Transparent = True
    end
    object LblDoktor: TLabel
      Left = 143
      Top = 61
      Width = 286
      Height = 46
      Caption = 'DR.AL'#304' K'#220#199#220'K'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlue
      Font.Height = -40
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
    end
    object LblPol: TLabel
      Left = 141
      Top = 10
      Width = 182
      Height = 46
      Caption = 'DAHILIYE'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -40
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
    end
  end
  object PanelAna: TJvNavPanelHeader
    Left = 0
    Top = 113
    Width = 1158
    Height = 474
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindow
    Font.Height = -16
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    ColorFrom = 4605510
    ColorTo = 4605510
    ImageIndex = 0
    ParentStyleManager = False
    DesignSize = (
      1158
      474)
    object Image1: TImage
      Left = 0
      Top = 0
      Width = 1158
      Height = 474
      Align = alClient
      ExplicitLeft = -1
      ExplicitTop = 4
    end
    object Label6: TLabel
      Left = 1079
      Top = 456
      Width = 77
      Height = 13
      Anchors = [akRight, akBottom]
      Caption = 'GenS'#305'ramatik'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsItalic]
      ParentFont = False
      Transparent = True
    end
    object LblSirano: TGenYanipSonenPanel
      Left = 1000
      Top = 19
      Width = 105
      Height = 94
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'Tahoma'
      HotTrackFont.Style = []
      Anchors = [akTop, akRight]
      Caption = '-'
      Color = clRed
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentBackGround = False
      ParentFont = False
      TabOrder = 0
      YanipSonmeSayisi = 5
      ArtimSayisi = 20
      YanipSonmeTimer = 50
      SabitArkaPlan = True
      CerceveVar = True
      PanelModu = pmYanipSon
    end
    object LblHastaAdiSoyadi: TGenYanipSonenPanel
      Left = 0
      Top = 413
      Width = 1155
      Height = 75
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'Tahoma'
      HotTrackFont.Style = []
      Caption = '-'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -96
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      YanipSonmeSayisi = 5
      ArtimSayisi = 20
      YanipSonmeTimer = 50
      SabitArkaPlan = True
      CerceveVar = True
      PanelModu = pmMetinKaydir
    end
    object LblHastaDosyaNo: TGenYanipSonenPanel
      Left = 0
      Top = 350
      Width = 1155
      Height = 57
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'Tahoma'
      HotTrackFont.Style = []
      Caption = '-'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlue
      Font.Height = -73
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      YanipSonmeSayisi = 5
      ArtimSayisi = 20
      YanipSonmeTimer = 50
      SabitArkaPlan = True
      CerceveVar = True
      PanelModu = pmMetinKaydir
    end
  end
  object PanelKayanyazi: TJvPanel
    Left = 0
    Top = 638
    Width = 1158
    Height = 66
    HotTrackFont.Charset = DEFAULT_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -11
    HotTrackFont.Name = 'MS Sans Serif'
    HotTrackFont.Style = []
    Align = alBottom
    Caption = 'Deneme'
    Font.Charset = TURKISH_CHARSET
    Font.Color = clMenuBar
    Font.Height = -27
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
  end
  object PanelSiradaki: TJvNavPanelHeader
    Left = 0
    Top = 587
    Width = 1158
    Height = 51
    Align = alBottom
    Caption = 'Sonraki Hasta : '
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -27
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
    ColorFrom = 4605510
    ColorTo = clBlack
    ImageIndex = 0
    object LblSiradakiHasta: TLabel
      Left = 241
      Top = 10
      Width = 13
      Height = 32
      Caption = '-'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -27
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
      Transparent = True
    end
  end
  object JvNavPaneStyleManager1: TJvNavPaneStyleManager
    Colors.ButtonColorFrom = clWhite
    Colors.ButtonColorTo = 12435133
    Colors.ButtonHotColorFrom = 13009540
    Colors.ButtonHotColorTo = 13009540
    Colors.ButtonSelectedColorFrom = 14602190
    Colors.ButtonSelectedColorTo = 14602190
    Colors.SplitterColorFrom = 13026246
    Colors.SplitterColorTo = 9211532
    Colors.DividerColorFrom = 15725551
    Colors.DividerColorTo = 13026246
    Colors.HeaderColorFrom = 8684164
    Colors.HeaderColorTo = 8684164
    Colors.FrameColor = 8684676
    Colors.ToolPanelHeaderColorFrom = clWhite
    Colors.ToolPanelHeaderColorTo = 12435133
    Fonts.NavPanelFont.Charset = DEFAULT_CHARSET
    Fonts.NavPanelFont.Color = clWindowText
    Fonts.NavPanelFont.Height = -11
    Fonts.NavPanelFont.Name = 'Tahoma'
    Fonts.NavPanelFont.Style = [fsBold]
    Fonts.NavPanelHotTrackFont.Charset = DEFAULT_CHARSET
    Fonts.NavPanelHotTrackFont.Color = clWindow
    Fonts.NavPanelHotTrackFont.Height = -11
    Fonts.NavPanelHotTrackFont.Name = 'Tahoma'
    Fonts.NavPanelHotTrackFont.Style = [fsBold]
    Fonts.DividerFont.Charset = DEFAULT_CHARSET
    Fonts.DividerFont.Color = clWindowText
    Fonts.DividerFont.Height = -11
    Fonts.DividerFont.Name = 'Tahoma'
    Fonts.DividerFont.Style = []
    Fonts.HeaderFont.Charset = TURKISH_CHARSET
    Fonts.HeaderFont.Color = clWhite
    Fonts.HeaderFont.Height = -27
    Fonts.HeaderFont.Name = 'Verdana'
    Fonts.HeaderFont.Style = [fsBold]
    Theme = nptCustom
    Left = 216
    Top = 80
  end
  object Timer1: TTimer
    Interval = 100
    OnTimer = Timer1Timer
    Left = 688
    Top = 224
  end
end
