<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gentegre.Cekirdek\Gentegre.Cekirdek.csproj" />
    <ProjectReference Include="..\Gentegre.Veri\Gentegre.Veri.csproj" />
  </ItemGroup>

</Project>
