-- ============================================================
-- GenDepoUpdate1 : 06.07.2026 16:22 tarihli GenDepoKur SONRASI tum guncellemeler.
-- MEVCUT musterilere uygulanir (GenDepoKur1-9 daha once uygulanmis olmali).
-- ANA DB baglantisindan calistir (GenDepoKur gibi). IDEMPOTENT (tekrar guvenli).
-- Kapsam:
--   1) GENDEPO LOG tablolari: ALTISLEMTIPI kolonu + TARIH datetime2(0) + ISLEMLOG view
--   2) TABLOLAR (ana DB): rol(80)/yetki(484)/opsiyon(485)
--   3) LOGCOZUM (GENDEPO synonym): yetki(80) + ayar(485) cozum kurallari
--   4) AYARADI (ana DB): opsiyon BOLUM -> caption/ad + bolum (LOGCOZUM 'Ayar No' bunu okur)
-- NOT: TARIH datetime2(0) donusumu buyuk LOG tablosunda tek seferlik yavas olabilir.
-- ============================================================
SET NOCOUNT ON;
SET XACT_ABORT ON;

-- ---- 1) GENDEPO LOG tablolari: ALTISLEMTIPI + TARIH datetime2(0) + view ----
EXEC('USE GENDEPO;
DECLARE @t sysname;
DECLARE cur CURSOR LOCAL FAST_FORWARD FOR SELECT name FROM sys.tables WHERE name LIKE ''LOG[0-9][0-9][0-9][0-9]'';
OPEN cur; FETCH NEXT FROM cur INTO @t;
WHILE @@FETCH_STATUS=0
BEGIN
  IF COL_LENGTH(''dbo.''+@t,''ALTISLEMTIPI'') IS NULL
    EXEC(''ALTER TABLE dbo.''+@t+'' ADD ALTISLEMTIPI tinyint NULL'');
  IF EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(''dbo.''+@t) AND name=''TARIH'' AND scale<>0)
  BEGIN
    IF EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_''+@t+''_TARIH'' AND object_id=OBJECT_ID(''dbo.''+@t))
      EXEC(''DROP INDEX IX_''+@t+''_TARIH ON dbo.''+@t);
    EXEC(''ALTER TABLE dbo.''+@t+'' ALTER COLUMN TARIH datetime2(0) NOT NULL'');
    EXEC(''CREATE INDEX IX_''+@t+''_TARIH ON dbo.''+@t+''(TARIH)'');
  END
  FETCH NEXT FROM cur INTO @t;
END
CLOSE cur; DEALLOCATE cur;
DECLARE @u nvarchar(max)=N'''';
SELECT @u=@u+CASE WHEN @u=N'''' THEN N'''' ELSE N'' UNION ALL '' END+
 N''SELECT ID,TARIH,IP,ISTASYON,KULLANICIID,SUBEID,ISLEMTIPI,ALTISLEMTIPI,USTTABLOID,USTKAYITID,TABLOID,KAYITID,REHBERID,STOKID,BILGI FROM dbo.''+name
FROM sys.tables WHERE name LIKE ''LOG[0-9][0-9][0-9][0-9]'' ORDER BY name;
IF @u<>N'''' EXEC(N''CREATE OR ALTER VIEW dbo.ISLEMLOG AS ''+@u);
');

-- ---- 2) TABLOLAR (ana DB): rol/yetki/opsiyon ----
MERGE dbo.TABLOLAR AS h USING (VALUES
  (80,  'ROLLER', N'Rol',   N'Yetki'),
  (484, 'YETKI',  N'Yetki', N'Yetki'),
  (485, 'GENINI', N'Ayar',  N'Seçenekler')
) AS k(TABLOID,TABLOADI,GORUNUM,MODUL)
ON h.TABLOID=k.TABLOID
WHEN MATCHED THEN UPDATE SET TABLOADI=k.TABLOADI,GORUNUM=k.GORUNUM,MODUL=k.MODUL
WHEN NOT MATCHED THEN INSERT(TABLOID,TABLOADI,GORUNUM,MODUL) VALUES(k.TABLOID,k.TABLOADI,k.GORUNUM,k.MODUL);

-- ---- 3) LOGCOZUM (GENDEPO synonym): yetki(80) + ayar(485) ----
MERGE dbo.LOGCOZUM AS h USING (VALUES
  (80,  N'DEPARTMAN', N'GENINI',  N'DEGER', N'ANAHTAR', N'BOLUM=-2251'),
  (80,  N'GOREVID',   N'GENINI',  N'DEGER', N'ANAHTAR', N'BOLUM=-2252'),
  (80,  N'SUBEID',    N'REHBER',  N'ID',    N'FIRMA',   NULL),
  (485, N'Ayar No',   N'AYARADI', N'BOLUM', N'AD',      NULL)
) AS k(TABLOID,ALAN,KAYNAKTABLO,IDKOLON,ADKOLON,FILTRE)
ON ISNULL(h.TABLOID,-1)=ISNULL(k.TABLOID,-1) AND h.ALAN=k.ALAN COLLATE SQL_Latin1_General_CP1254_CI_AS
WHEN MATCHED THEN UPDATE SET KAYNAKTABLO=k.KAYNAKTABLO,IDKOLON=k.IDKOLON,ADKOLON=k.ADKOLON,FILTRE=k.FILTRE,AKTIF=1
WHEN NOT MATCHED THEN INSERT(TABLOID,ALAN,KAYNAKTABLO,IDKOLON,ADKOLON,FILTRE) VALUES(k.TABLOID,k.ALAN,k.KAYNAKTABLO,k.IDKOLON,k.ADKOLON,k.FILTRE);

-- ---- 4) AYARADI (ana DB): opsiyon adlari/caption'lari (Ops_ sabitlerinden uretildi) ----
IF OBJECT_ID('dbo.AYARADI','U') IS NOT NULL DROP TABLE dbo.AYARADI;
CREATE TABLE dbo.AYARADI(BOLUM int NOT NULL CONSTRAINT PK_AYARADI PRIMARY KEY, AD nvarchar(200) NULL, SEKSIYON nvarchar(60) NULL);
INSERT INTO dbo.AYARADI(BOLUM,AD,SEKSIYON) VALUES
  (-27990001, N'Stok Kategori Turleri', N'StokKategoriTurleri'),
  (-238801, N'Kasiyer / Cafe / Hesap / Sablon', N'Kasiyer'),
  (-238701, N'Kasiyer / Cafe / Sip / Sablon', N'Kasiyer'),
  (-100051, N'G2 LKS / ORKAExport Path', N'G2/LKS'),
  (-100050, N'G2 LKS / Varsayilan Muhasebe Prog', N'G2/LKS'),
  (-100049, N'G2 LKS / Muh Aktar Durum', N'G2/LKS'),
  (-100048, N'G2 LKS / Muhasebe Prog', N'G2/LKS'),
  (-100047, N'G2 LKS / Donem No', N'G2/LKS'),
  (-100046, N'G2 LKS / Firma No', N'G2/LKS'),
  (-100045, N'G2 LKS / Veri Tabani', N'G2/LKS'),
  (-100044, N'G2 LKS / Sifre', N'G2/LKS'),
  (-100043, N'G2 LKS / Kullanici', N'G2/LKS'),
  (-100042, N'G2 LKS / Server', N'G2/LKS'),
  (-100041, N'G2 LKS / LOGOExport Path', N'G2/LKS'),
  (-100040, N'G2 LKS / Registry', N'G2/LKS'),
  (-48006, N'Social Media / Meta Guncelleme', N'SocialMedia'),
  (-48005, N'Social Media / IMAP', N'SocialMedia'),
  (-48004, N'Social Media / Xtwitter', N'SocialMedia'),
  (-48003, N'Social Media / Linked In', N'SocialMedia'),
  (-48002, N'Social Media / Meta', N'SocialMedia'),
  (-48001, N'Social Media', N'SocialMedia'),
  (-45678, N'Fatura / Excel Eslesme', N'Fatura'),
  (-33114, N'Lotno Kaynağı', N'RadioGroupLotKaynak'),
  (-33112, N'Edit Is Emri Sekme2', N'EditIsEmriSekme2'),
  (-33111, N'Edit Is Emri Sekme1', N'EditIsEmriSekme1'),
  (-33107, N'UEmri Edit Sekme3', N'UEmriEditSekme3'),
  (-33106, N'UEmri Edit Sekme2', N'UEmriEditSekme2'),
  (-33105, N'UEmri Edit Sekme1', N'UEmriEditSekme1'),
  (-33103, N'Edit Uret Lot No Onek', N'EditUretLotNoOnek'),
  (-33102, N'Üretim Emrinde Yeni İşlemde Cari Sor', N'CheckCariSor'),
  (-33101, N'Uretim / Senaryo', N'Uretim'),
  (-33100, N'Uretim / Recete / KDV / Durum', N'Uretim'),
  (-33055, N'Stok Kartında Ürün No Tek Olmalı', N'CheckUrunNoTek'),
  (-33054, N'Test Kullanımında', N'CheckTest'),
  (-33053, N'Edit UTSFirma No', N'EditUTSFirmaNo'),
  (-33052, N'Edit UTSToken', N'EditUTSToken'),
  (-33051, N'ÜTS Kullanımda', N'CheckUTSKullanimda'),
  (-33003, N'ITSOpsiyon / Etiket', N'ITS'),
  (-33002, N'ITSOpsiyon / Depocu', N'ITS'),
  (-33001, N'ITSOpsiyon / Imalatci', N'ITS'),
  (-32101, N'KYSapma Olay Durum', N'KYSapmaOlayDurum'),
  (-32100, N'KYSapma Olay Kategori', N'KYSapmaOlayKategori'),
  (-32053, N'Kalite Testleri', N'KaliteTestleri'),
  (-32052, N'Kalite Olcu Aletleri', N'KaliteOlcuAletleri'),
  (-32030, N'Dini Tatil Gunleri2030', N'DiniTatilGunleri2030'),
  (-32029, N'Dini Tatil Gunleri2029', N'DiniTatilGunleri2029'),
  (-32028, N'Dini Tatil Gunleri2028', N'DiniTatilGunleri2028'),
  (-32027, N'Dini Tatil Gunleri2027', N'DiniTatilGunleri2027'),
  (-32026, N'Dini Tatil Gunleri2026', N'DiniTatilGunleri2026'),
  (-32025, N'Dini Tatil Gunleri2025', N'DiniTatilGunleri2025'),
  (-32024, N'Dini Tatil Gunleri2024', N'DiniTatilGunleri2024'),
  (-32023, N'Dini Tatil Gunleri2023', N'DiniTatilGunleri2023'),
  (-32022, N'Dini Tatil Gunleri2022', N'DiniTatilGunleri2022'),
  (-32021, N'Dini Tatil Gunleri2021', N'DiniTatilGunleri2021'),
  (-32020, N'Dini Tatil Gunleri2020', N'DiniTatilGunleri2020'),
  (-32019, N'Dini Tatil Gunleri2019', N'DiniTatilGunleri2019'),
  (-32018, N'Dini Tatil Gunleri2018', N'DiniTatilGunleri2018'),
  (-32017, N'Dini Tatil Gunleri2017', N'DiniTatilGunleri2017'),
  (-32016, N'Dini Tatil Gunleri2016', N'DiniTatilGunleri2016'),
  (-32015, N'Dini Tatil Gunleri2015', N'DiniTatilGunleri2015'),
  (-32014, N'Dini Tatil Gunleri2014', N'DiniTatilGunleri2014'),
  (-32009, N'KYDenetim Kategori', N'KYDenetimKategori'),
  (-32008, N'KYDenetim Durum', N'KYDenetimDurum'),
  (-32007, N'KYDenetim Tipi', N'KYDenetimTipi'),
  (-32002, N'Kalite Dof Kategori', N'KaliteDofKategori'),
  (-32001, N'Opsiyon Kalite / Bilgilendirme Mailrapor', N'Kalite'),
  (-32000, N'Kalite Kontrol Kullanımdadır', N'CheckKaliteKontrol'),
  (-31010, N'Dokuman / Revize Miktar', N'Dokuman'),
  (-31009, N'Dokuman / Bildirim Turleri', N'Dokuman'),
  (-31004, N'Tarayıcı Kullanımdadır', N'Dokuman'),
  (-31003, N'Dokuman / Giden Kutusu', N'Dokuman'),
  (-31002, N'Dokuman / Gelen Kutusu', N'Dokuman'),
  (-31001, N'Dokuman / Google Wsdl', N'Dokuman'),
  (-30033, N'Durumlar türe göre ayarlansın', N'Servis'),
  (-30032, N'Özellik Sekmesi', N'Servis'),
  (-30031, N'Servis Hareketler Sekmesi', N'ServisHareketlerSekmesi'),
  (-30030, N'Yorum Sekmesi', N'Servis'),
  (-30029, N'Genel Sekmesi', N'Servis'),
  (-30028, N'Belgeler Sekmesi', N'Servis'),
  (-30027, N'Birden fazla personel tek bir servisin sorumlusu olabilir.', N'ServisBirdenFazlaSorumluPers'),
  (-30026, N'Ek Alanlar Sekmesi', N'Servis'),
  (-30025, N'Teslim Sekmesi', N'Servis'),
  (-30024, N'Lokasyon', N'Servis'),
  (-30023, N'Servis / Proje', N'Servis'),
  (-30022, N'Seri No', N'Servis'),
  (-30021, N'Servis / Proje Firsat Sec', N'Servis'),
  (-30020, N'Opsiyon Servis / Genel', N'Servis'),
  (-30016, N'Opsiyon Servis / Cevapsiz Durum', N'Servis'),
  (-30015, N'Opsiyon Servis / Cevap Sure', N'Servis'),
  (-30014, N'Opsiyon Servis / Onay Hayir Durum', N'Servis'),
  (-30013, N'Opsiyon Servis / Varsayilan Klasor', N'Servis'),
  (-30012, N'Opsiyon Servis / Onay Evet Durum', N'Servis'),
  (-30011, N'Opsiyon Servis / Varsayilan Servis Turu', N'Servis'),
  (-30010, N'Opsiyon Servis / Senaryo', N'Servis'),
  (-30000, N'Opsiyon Servis / Kapsam', N'Servis'),
  (-28016, N'Demirbas Opsiyon / Gorev Turu', N'Demirbas'),
  (-28015, N'Demirbas Opsiyon / Mail Sablon', N'Demirbas'),
  (-28014, N'Demirbas Opsiyon / Aksiyon Tetik', N'Demirbas'),
  (-28013, N'Opsiyon Demirbas / Olusacak Aksiyon', N'Demirbas'),
  (-28011, N'Opsiyon Demirbas / Servis Durumu', N'Demirbas'),
  (-28004, N'Opsiyon Demirbas / Takip Tur', N'Demirbas'),
  (-27016, N'Stok Kartında Muhasebe Kodları Görünsün', N'Stok'),
  (-27015, N'Stok Maliyet Hesap Yöntemi', N'Stok'),
  (-27012, N'Stok Opsiyon / Hareket Basla', N'Stok'),
  (-27011, N'Varolmayan Stok Boyutlarını Oto. Oluştur', N'Stok'),
  (-27010, N'Stok seviyeleri yeni kart''da sorulsun', N'Stok'),
  (-27009, N'Stok hareketleri lokasyonlara göre yapılsın', N'Stok'),
  (-27006, N'Sayım Tutanakları Onaydan sonra tekrar değiştirilebilsin', N'Stok'),
  (-27005, N'Stok Opsiyon / Stok Kalmayanlar', N'Stok'),
  (-27004, N'Stok Opsiyon / Stok Kod Girisi', N'Stok'),
  (-27003, N'Stok Opsiyon / Stok Ara Focus Kurali', N'Stok'),
  (-27002, N'Stok Durum Kontrol Kuralı', N'Stok'),
  (-27001, N'Stok Opsiyon / Stok Varsayilan Birim', N'Stok'),
  (-25019, N'Excel Maas Esles / Ode Kasa', N'ExcelMaasEsles'),
  (-25018, N'Excel Maas Esles / Ode Banka', N'ExcelMaasEsles'),
  (-25017, N'Excel Maas Esles / Av Kasa', N'ExcelMaasEsles'),
  (-25016, N'Excel Maas Esles / Av Banka', N'ExcelMaasEsles'),
  (-25015, N'Excel Maas Esles / Kasa', N'ExcelMaasEsles'),
  (-25014, N'Excel Maas Esles / Diger', N'ExcelMaasEsles'),
  (-25013, N'Excel Maas Esles / Agi', N'ExcelMaasEsles'),
  (-25012, N'Excel Maas Esles / Banka', N'ExcelMaasEsles'),
  (-25011, N'Excel Maas Esles / Maas', N'ExcelMaasEsles'),
  (-25010, N'Excel Maas Esles / Tc Kim No', N'ExcelMaasEsles'),
  (-25002, N'Fatura Opsiyon / Referans', N'Fatura'),
  (-25000, N'Fatura Opsiyon / Poliklinik', N'Fatura'),
  (-24120, N'Fatura Opsiyon / Depo DBAdi', N'Fatura'),
  (-24119, N'Fatura Opsiyon / UBL / ZIP', N'Fatura'),
  (-24118, N'Fatura Opsiyon / EArsiv Gelen URL', N'Fatura'),
  (-24117, N'Gelen E-İrsaliyeyi Al', N'Fatura'),
  (-24116, N'Kurum XSLT / EIrsaliye', N'KurumXSLT'),
  (-24115, N'Kurum XSLT / EArsiv', N'KurumXSLT'),
  (-24114, N'Kurum XSLT / EFatura', N'KurumXSLT'),
  (-24113, N'Fatura Opsiyon / Son Sevk Bilgileri', N'Fatura'),
  (-24112, N'Gelen Faturayı Al', N'Fatura'),
  (-24111, N'Fatura Opsiyon / Cari Kod', N'Fatura'),
  (-24110, N'Fatura Opsiyon / EIrsaliye Gelen XSLT', N'Fatura'),
  (-24109, N'Fatura Opsiyon / ESMMGelen XSLT', N'Fatura'),
  (-24108, N'Fatura Opsiyon / EArsiv Fatura Gelen XSLT', N'Fatura'),
  (-24107, N'Fatura Opsiyon / EFatura Gelen XSLT', N'Fatura'),
  (-24105, N'Fatura Opsiyon / EIrsaliye GIBAlias', N'Fatura'),
  (-24104, N'Fatura Opsiyon / EBelge SOAPUretim URL', N'Fatura'),
  (-24103, N'Fatura Opsiyon / EBelge SOAPTest URL', N'Fatura'),
  (-24102, N'Fatura Opsiyon / EBelge Sifre', N'Fatura'),
  (-24101, N'Fatura Opsiyon / EBelge Kullanici', N'Fatura'),
  (-24100, N'Fatura Opsiyon / EIrsaliye Sabit Notlar', N'Fatura'),
  (-24099, N'Fatura Opsiyon / ESMMSabit Notlar', N'Fatura'),
  (-24098, N'Fatura Opsiyon / EArsiv Fatura Sabit Notlar', N'Fatura'),
  (-24097, N'Fatura Opsiyon / EFatura Sabit Notlar', N'Fatura'),
  (-24096, N'Fatura Opsiyon / EIrsaliye Seriler', N'Fatura'),
  (-24095, N'Fatura Opsiyon / ESMMSeriler', N'Fatura'),
  (-24094, N'Fatura Opsiyon / EArsiv Fatura Seriler', N'Fatura'),
  (-24093, N'Fatura Opsiyon / EFatura Seriler', N'Fatura'),
  (-24092, N'Fatura Opsiyon / EIrsaliye Uretim URL', N'Fatura'),
  (-24091, N'Fatura Opsiyon / EIrsaliye Test URL', N'Fatura'),
  (-24090, N'Fatura Opsiyon / ESMMUretim URL', N'Fatura'),
  (-24089, N'Fatura Opsiyon / ESMMTest URL', N'Fatura'),
  (-24088, N'Fatura Opsiyon / EArsiv Fatura Uretim URL', N'Fatura'),
  (-24087, N'Fatura Opsiyon / EArsiv Fatura Test URL', N'Fatura'),
  (-24086, N'Fatura Opsiyon / EFatura Test URL', N'Fatura'),
  (-24085, N'Aktif', N'Fatura'),
  (-24084, N'Gelen E-Arşivi Al', N'Fatura'),
  (-24083, N'Fatura Opsiyon / EFatura Aktif', N'Fatura'),
  (-24082, N'Fatura Opsiyon / EBelge Vergi No', N'Fatura'),
  (-24081, N'Test', N'Fatura'),
  (-24080, N'Fatura Opsiyon / EBelge Aktif', N'Fatura'),
  (-24079, N'Fatura Opsiyon / EIrsaliye XSLT', N'Fatura'),
  (-24078, N'Fatura Opsiyon / ESMMXSLT', N'Fatura'),
  (-24077, N'Fatura Opsiyon / EArsiv Fatura XSLT', N'Fatura'),
  (-24076, N'Fatura Opsiyon / EFatura XSLT', N'Fatura'),
  (-24075, N'Başlıkta Hasta Bilgisi Sekmesi', N'Fatura'),
  (-24074, N'Başlıkta Hasta Bilgisi Sekmesi', N'Fatura'),
  (-24072, N'Fatura Opsiyon / Poz No Aralik', N'Fatura'),
  (-24071, N'Poz No otomatik versin. Aralık', N'Fatura'),
  (-24070, N'En x Boy yüzey bilgileri girilebilsin', N'Fatura'),
  (-24069, N'Fatura Opsiyon / Proje Firsat Sec', N'Fatura'),
  (-24068, N'Vade', N'Fatura'),
  (-24067, N'Fiyat Adı', N'Fatura'),
  (-24066, N'Depo', N'Fatura'),
  (-24065, N'Vergi No', N'Fatura'),
  (-24064, N'Vergi Dairesi', N'Fatura'),
  (-24063, N'İl', N'Fatura'),
  (-24062, N'İlçe', N'Fatura'),
  (-24061, N'Adres', N'Fatura'),
  (-24060, N'Başlık', N'Fatura'),
  (-24050, N'Fatura Opsiyon / EFatura DB', N'Fatura'),
  (-24047, N'Fatura Opsiyon / Gider Pusulasi', N'Fatura'),
  (-24046, N'Fatura Opsiyon / Kira', N'Fatura'),
  (-24045, N'Fatura Opsiyon / Serbest Meslek', N'Fatura'),
  (-24040, N'Eksi iskontoya izin ver', N'Fatura'),
  (-24039, N'Fatura Opsiyon / Maliyet / Hesap', N'Fatura'),
  (-24038, N'Fatura Opsiyon / Maliyet / Kod', N'Fatura'),
  (-24037, N'Fatura Opsiyon / Maliyet / Trh', N'Fatura'),
  (-24036, N'Fatura Opsiyon / Bedelsiz', N'Fatura'),
  (-24035, N'Fatura Opsiyon / Senaryo', N'Fatura'),
  (-24034, N'Fatura Opsiyon / Ent / Sifre', N'Fatura'),
  (-24033, N'Fatura Opsiyon / Ent / Kullanici', N'Fatura'),
  (-24032, N'Fatura Opsiyon / Ent / Adres', N'Fatura'),
  (-24031, N'Fatura Opsiyon / Entegrator', N'Fatura'),
  (-24030, N'Fatura Opsiyon / E / Fatura Kullanimda', N'Fatura'),
  (-24028, N'Fatura Opsiyon / Ozelkod2 / Liste', N'Fatura'),
  (-24027, N'Fatura Opsiyon / Ozelkod1 / Liste', N'Fatura'),
  (-24026, N'Fatura Opsiyon / Ozelkod2', N'Fatura'),
  (-24025, N'Fatura Opsiyon / Ozelkod1', N'Fatura'),
  (-24024, N'İhracat Faturaları da Gönderilsin', N'IhracatGonder'),
  (-24023, N'E-İrsaliyeyi Aktif', N'EIrsaliye'),
  (-24021, N'Opsiyon Siparis / Verilen Durum', N'Siparis'),
  (-24020, N'Opsiyon Siparis / Alinan Durum', N'Siparis'),
  (-24019, N'Demirbaş Bilgileri Fatura ve Tahakkukda Gözüksün', N'Fatura'),
  (-24018, N'Proje Bilgileri Fatura ve Tahakkukda Gözüksün', N'Fatura'),
  (-24014, N'Fatura Opsiyon / Ondalik Dijit Say Miktar', N'Fatura'),
  (-24013, N'Dönüşüm bilgileri listelerde gözüksün', N'Fatura'),
  (-24012, N'Dönüşüm bilgileri listelerde gözüksün', N'Fatura'),
  (-24011, N'Alış/Satış Belgelerinde Dövizli Fiyat Bilgisi Bulunsun', N'Fatura'),
  (-24010, N'Fatura Opsiyon / Belge Olusturma', N'Fatura'),
  (-24009, N'Stok eklerken varsayılan olarak kalmayanları da göster.', N'Fatura'),
  (-24008, N'Opsiyon Siparis / Varsayilan Klasor', N'Siparis'),
  (-24007, N'Opsiyon Fatura / Varsayilan Klasor', N'Fatura'),
  (-24006, N'Fatura Opsiyon / Ondalik Dijit Say Doviz', N'Fatura'),
  (-24005, N'Başlıkta kullan', N'Fatura'),
  (-24004, N'Her satırda kullan', N'Fatura'),
  (-24003, N'Fatura Opsiyon / Ondalik Dijit Say Tut', N'Fatura'),
  (-24002, N'Fatura Opsiyon / Ondalik Dijit Say Br', N'Fatura'),
  (-24001, N'Tüm Faturalara Ödeme Planı Oluşturmayı Zorunlu Tut.', N'Fatura'),
  (-23506, N'Adisyon / Siparis Tahsil', N'Adisyon'),
  (-23505, N'Adisyon / Combo Siparis Iptal', N'Adisyon'),
  (-23504, N'Adisyon / Siparis Kurye', N'Adisyon'),
  (-23503, N'Adisyon / Siparis Yaz', N'Adisyon'),
  (-23502, N'Adisyon / Siparis Yeni', N'Adisyon'),
  (-23501, N'Adisyon / Durumlar', N'Adisyon'),
  (-23402, N'Kasa Ekle Gun', N'KasaEkleGun'),
  (-23401, N'Kasa Bit Zamani', N'KasaBitZamani'),
  (-23400, N'Kasa Bas Zamani', N'KasaBasZamani'),
  (-23355, N'IK / Cinsiyet', N'İK'),
  (-23330, N'IK / Maas Masraf Kalemi', N'İK'),
  (-23325, N'Maaş listesine varsa önceki aylardan devirler gelsin', N'İK'),
  (-23324, N'IK / Check Mola Suresi', N'İK'),
  (-23322, N'Pazar günleri izne dahil', N'İK'),
  (-23321, N'Cumartesi günleri izne dahil', N'İK'),
  (-23313, N'IK / Edit Izin Sure3', N'İK'),
  (-23312, N'IK / Edit Izin Sure2', N'İK'),
  (-23311, N'IK / Edit Izin Sure1', N'İK'),
  (-23303, N'IK / Edit Izin Yil3', N'İK'),
  (-23302, N'IK / Edit Izin Yil2', N'İK'),
  (-23301, N'IK / Edit Izin Yil1', N'İK'),
  (-23238, N'Masa Tutarı', N'Kafe'),
  (-23237, N'Geçen Zaman', N'Kafe'),
  (-23236, N'Açılış Zamanı', N'Kafe'),
  (-23235, N'Kişi sayısı', N'Kafe'),
  (-23234, N'Garson Adı', N'Kafe'),
  (-23230, N'Kasiyer / Perakendeye Satis', N'Kasiyer'),
  (-23229, N'Hesap yazınca ekran kapansın', N'Kasiyer'),
  (-23228, N'Siparişi yazınca ekran kapansın', N'Kasiyer'),
  (-23224, N'Hizli Giris / Color Combo Birles', N'Hızlı Giriş'),
  (-23223, N'Hizli Giris / Color Combo Hesap', N'Hızlı Giriş'),
  (-23222, N'Hizli Giris / Color Combo Rezerve', N'Hızlı Giriş'),
  (-23221, N'Hizli Giris / Color Combo Dolu', N'Hızlı Giriş'),
  (-23220, N'Hizli Giris / Color Combo Bos', N'Hızlı Giriş'),
  (-23217, N'Hizli Giris / Edit Servis Id', N'Hızlı Giriş'),
  (-23216, N'Hizli Giris / Edit Servis Oran', N'Hızlı Giriş'),
  (-23215, N'Servis eklensin', N'Hızlı Giriş'),
  (-23205, N'Rezervasyon Kullanılsın', N'Kafe'),
  (-23204, N'Cafe / Check Garson Adi Sor Mobil', N'Kafe'),
  (-23203, N'Şifre sıfırlansın', N'Kafe'),
  (-23202, N'Kişi sayısını sorsun', N'Kafe'),
  (-23201, N'Cafe / Check Garson Adi Sor PC', N'Kafe'),
  (-23198, N'"Perakende" müşterisi "Açık Hesap" a atılamasın', N'Kasiyer'),
  (-23197, N'Kalanı "İskonto" Butonu Görünsün', N'Kasiyer'),
  (-23196, N'Kalanı "Açık Hesap" Butonu Görünsün', N'Kasiyer'),
  (-23195, N'Kasiyer / Tah Turleri', N'Kasiyer'),
  (-23191, N'Kasiyer / Urun Birimlerini Toplama ID', N'Kasiyer'),
  (-23190, N'Ürünlerin Birimleri Dönüştürülerek Toplansın', N'Kasiyer'),
  (-23184, N'Kasa Opsiyon / Tahsilat Gider SRM', N'Kasa'),
  (-23183, N'Kasa Opsiyon / Odeme Gider SRM', N'Kasa'),
  (-23182, N'Kasa Opsiyon / Belge Gelir SRM', N'Kasa'),
  (-23181, N'Kasa Opsiyon / Belge Gider SRM', N'Kasa'),
  (-23180, N'Kasiyer / Nakliye ID', N'Kasiyer'),
  (-23179, N'Nakliye butonu görünsün', N'Kasiyer'),
  (-23177, N'Ürün Listelerinde Özel Kodu Göster.', N'Kasiyer'),
  (-23104, N'Kod dahil', N'Kasiyer'),
  (-23103, N'Kod dahil', N'Kasiyer'),
  (-23102, N'Kod dahil', N'Kasiyer'),
  (-23101, N'Kod dahil', N'Kasiyer'),
  (-23092, N'Hizli Giris / Fiyat Basamak', N'Hızlı Giriş'),
  (-23090, N'Hizli Giris / Cafe', N'Hızlı Giriş'),
  (-23088, N'Hizli Giris / Gratis Bas Gun', N'Hızlı Giriş'),
  (-23087, N'Günlük', N'Hızlı Giriş'),
  (-23079, N'Transferde "Kaydet" basınca yazsın', N'CheckTransferKaydetYaz'),
  (-23078, N'Açık Hesap', N'Stok Hızlı Giriş'),
  (-23077, N'İrsaliye Baskı', N'Hızlı Giriş'),
  (-23076, N'İrsaliye Kayıt', N'Hızlı Giriş'),
  (-23075, N'Resim altında barkod görünsün', N'Hızlı Giriş'),
  (-23074, N'Okunan Gr miktarını Kg''a çevirsin', N'Hızlı Giriş'),
  (-23073, N'Hizli Giris / Terazi Flow Control', N'Hızlı Giriş'),
  (-23072, N'Hizli Giris / Terazi Parity', N'Hızlı Giriş'),
  (-23071, N'Hizli Giris / Terazi Stop Bits', N'Hızlı Giriş'),
  (-23070, N'Hizli Giris / Terazi Data Bits', N'Hızlı Giriş'),
  (-23069, N'Hizli Giris / Terazi Boud Rare', N'Hızlı Giriş'),
  (-23068, N'Hizli Giris / Terazi Port', N'Hızlı Giriş'),
  (-23067, N'Sipariş sadece merkeze yapılsın', N'Hızlı Giriş'),
  (-23065, N'Fatura Baskı', N'Hızlı Giriş'),
  (-23064, N'Fiş Baskı', N'Hızlı Giriş'),
  (-23063, N'Stok Hizli Giris / Sadece Fat Kaydet', N'Stok Hızlı Giriş'),
  (-23062, N'Belgesiz', N'Hızlı Giriş'),
  (-23061, N'Gider Pusulası', N'Hızlı Giriş'),
  (-23060, N'Fatura Kayıt', N'Hızlı Giriş'),
  (-23059, N'Fiş Kayıt', N'Hızlı Giriş'),
  (-23056, N'Opsiyon Kasa / Gorunecek Subeler Kasa', N'Kasa'),
  (-23055, N'Opsiyon Kasa / Gorunecek Subeler MM', N'Kasa'),
  (-23045, N'Kasa Ekran / Plan', N'KasaEkran'),
  (-23044, N'Kasa Ekran / Kasa', N'KasaEkran'),
  (-23043, N'Kasa Ekran / Tahakkuk', N'KasaEkran'),
  (-23042, N'Kasa Ekran / Cekve Senet', N'KasaEkran'),
  (-23041, N'Kasa Ekran / Banka', N'KasaEkran'),
  (-23040, N'Yeni Fatura/Fiş ler için fatura bilgilerini sor.', N'Hızlı Giriş'),
  (-23039, N'Hizli Giris / Fazla Iskonto Yapabilir', N'Hızlı Giriş'),
  (-23038, N'Satış Belgesi yazdırırken belge numarası ekrana gelsin', N'Hızlı Giriş'),
  (-23037, N'Alış-Satış Belgelerinden Derle', N'Kasa'),
  (-23036, N'Stok Hizli Giris / Varsayilan KDVDurum', N'Stok Hızlı Giriş'),
  (-23030, N'Opsiyon Kasa / Aciklama Satir', N'Kasa'),
  (-23029, N'Çerçeveye boyutlandırma', N'Kasa'),
  (-23028, N'Opsiyon Kasa / Resim Pixel', N'Kasa'),
  (-23027, N'Opsiyon Kasa / Urun Kart Boy', N'Kasa'),
  (-23026, N'Opsiyon Kasa / Urun Kart En', N'Kasa'),
  (-23025, N'Opsiyon Kasa / Kategori Boy', N'Kasa'),
  (-23024, N'Opsiyon Kasa / Kategori En', N'Kasa'),
  (-23023, N'Kasa Opsiyon / Tahsilat Gider Merkezi', N'Kasa'),
  (-23022, N'Kasa Opsiyon / Odeme Gider Merkezi', N'Kasa'),
  (-23021, N'Kasa Opsiyon / Belge Gelir Merkezi', N'Kasa'),
  (-23020, N'Kasa Opsiyon / Belge Gider Merkezi', N'Kasa'),
  (-23019, N'Kasa Bakiye Kuralı', N'Kasa'),
  (-23018, N'Kupon', N'Stok Hızlı Giriş'),
  (-23017, N'İade Çeki', N'Stok Hızlı Giriş'),
  (-23016, N'POS', N'Stok Hızlı Giriş'),
  (-23015, N'Hediye Çeki', N'Stok Hızlı Giriş'),
  (-23014, N'Nakit', N'Stok Hızlı Giriş'),
  (-23013, N'Kupon', N'Stok Hızlı Giriş'),
  (-23012, N'İade Çeki', N'Stok Hızlı Giriş'),
  (-23011, N'Hediye Çeki', N'Stok Hızlı Giriş'),
  (-23010, N'POS', N'Stok Hızlı Giriş'),
  (-23009, N'Nakit', N'Stok Hızlı Giriş'),
  (-23004, N'İskonto İşlemlerinde Açıklama İste.', N'Hızlı Giriş'),
  (-23003, N'Her Yeni Girişte Kullanıcı Doğrulama Aktif.', N'Stok Hızlı Giriş'),
  (-23002, N'Kasa Açılış/Kapanış İşlemleri Aktif.', N'Stok Hızlı Giriş'),
  (-23001, N'Kasa Opsiyon / KDVOrani', N'Kasa'),
  (-22036, N'VNo ile bilgileri otomatik doldur', N'Cari'),
  (-22035, N'Opsiyon Cari / Not Turu', N'Cari'),
  (-22028, N'Opsiyon Cari / Caller IDCalistir', N'Cari'),
  (-22024, N'Çarşaf Listede Maaş Ödemesi Eksi olamaz', N'İK'),
  (-22023, N'Dini bayramlarda mesai eklenecek', N'Cari'),
  (-22022, N'Resmi bayramlarda mesai eklenecek', N'Cari'),
  (-22021, N'Dini bayramlarda çalışma var', N'Cari'),
  (-22020, N'Resmi bayramlarda çalışma var', N'Cari'),
  (-22015, N'Opsiyon Cari / Pers Kod Girisi', N'Cari'),
  (-22014, N'Alt Bölge Zorunlu Olacak', N'Cari'),
  (-22013, N'Bölge Zorunlu Olacak', N'Cari'),
  (-22012, N'Opsiyon Cari / Check Kurumsal Zorunlu', N'Cari'),
  (-22010, N'SAP / DBAd', N'SAP'),
  (-22009, N'Kart No Sorgula', N'Cari'),
  (-22008, N'Opsiyon Cari / Giris Turleri', N'Cari'),
  (-22007, N'Opsiyon Cari / Personel Hareket Tur', N'Cari'),
  (-22006, N'Opsiyon Cari / PDKSBilgi Girisi', N'Cari'),
  (-22005, N'Opsiyon Cari / Vardiya Cikis', N'Cari'),
  (-22004, N'Opsiyon Cari / Vardiya Giris', N'Cari'),
  (-22003, N'Opsiyon Cari / Gorunecek Subeler', N'Cari'),
  (-22002, N'Opsiyon Cari / Varsayilan Klasor', N'Cari'),
  (-22001, N'Opsiyon Cari / Cari Kod Girisi', N'Cari'),
  (-22000, N'Kaynak DB', N'KaynakDB'),
  (-21224, N'İş Listesi sekmesi görünsün', N'Firsat'),
  (-21221, N'Aşama sekmesi görünsün', N'Firsat'),
  (-21220, N'Lojistik sekmesi görünsün', N'Proje'),
  (-21219, N'Firsat Opsiyon / Proje Kodu Uretme', N'Firsat'),
  (-21218, N'Group Otomatik Kod', N'GroupOtomatikKod'),
  (-21119, N'Proje kapanınca bağlı tekliflerin durumunu  sorsun', N'Proje'),
  (-21080, N'İş listesi Google Takvimde görünsün', N'CheckGoogleTakvim'),
  (-21079, N'İş listesinde "Toplantı" görünsün', N'CheckToplantiGor'),
  (-21078, N'İş listesinde "Servis" görünsün', N'CheckServisGor'),
  (-21077, N'İş listesinde "Demirbaş" görünsün', N'CheckDemirbasGor'),
  (-21076, N'İş ekranında fırsat/proje bilgisi görünsün', N'CheckProjeGor'),
  (-21075, N'İş ekranında ekipman bilgisi görünsün', N'CheckEkipmanGor'),
  (-21074, N'Opsiyon Is Listesi / Varsayilan / Durum / Son', N'İş'),
  (-21073, N'Opsiyon Is Listesi / Varsayilan / Durum / Son Red', N'İş'),
  (-21072, N'Opsiyon Is Listesi / Varsayilan / Durum / Son Onay', N'İş'),
  (-21071, N'Opsiyon Is Listesi / Varsayilan / Durum / Yeni', N'İş'),
  (-21070, N'Tamamlanan İşler Onaya Gelsin', N'İş'),
  (-21050, N'CRM / Aktivite', N'CRM'),
  (-21045, N'Gorev / Turu / Demirbas', N'Gorev'),
  (-21044, N'Gorev / Turu', N'Gorev'),
  (-21043, N'Gorev / Son / Kac', N'Gorev'),
  (-21042, N'Gorev / Durum', N'Gorev'),
  (-21041, N'Gorev / Animsat Sonra', N'Gorev'),
  (-21040, N'Gorev / Animsat Once', N'Gorev'),
  (-21035, N'Proje Opsiyon / Proje Maliyet Eflow Kullan', N'Proje'),
  (-21032, N'Opsiyon Is / Varsayilan Klasor', N'İş'),
  (-21031, N'Proje Opsiyon / Panel Alan', N'Proje'),
  (-21030, N'Opsiyon AKtivite / Bilgilendirme Mailrapor', N'AKtivite'),
  (-21029, N'Opsiyon Aktivite / Bilgilendirme Sms', N'Aktivite'),
  (-21028, N'Opsiyon Aktivite / Bilgilendirme Mail', N'Aktivite'),
  (-21027, N'Opsiyon Proje / Gorunecek Subeler', N'Proje'),
  (-21026, N'Opsiyon Aktivite / Varsayilan Klasor', N'Aktivite'),
  (-21025, N'Opsiyon Proje / Varsayilan Klasor', N'Proje'),
  (-21024, N'Proje Opsiyon / Proj Trhc Asama Sorumlu', N'Proje'),
  (-21023, N'Projeler / Kod Grubu', N'Projeler'),
  (-21022, N'E-Posta Gönderim Şekli', N'Aktivite'),
  (-21021, N'Aktiviteler İçin SMS Bildirimini Kullan', N'Aktivite'),
  (-21020, N'Aktiviteler İçin Eposta Bildirimini Kullan', N'Aktivite'),
  (-21019, N'Proje Opsiyon / Proje Kodu Uretme', N'Proje'),
  (-21018, N'Müşteri İlgili', N'Proje'),
  (-21017, N'Sonuç', N'Proje'),
  (-21016, N'Durum', N'Proje'),
  (-21015, N'Proje Opsiyon / Proj Trhc Asama', N'Proje'),
  (-21014, N'Sorumlu', N'Proje'),
  (-21013, N'Aktivite Opsiyon / Amiri Bilgilendirilecek Getir', N'Aktivite'),
  (-21012, N'Aktivite Opsiyon / Amiri Takipci Getir', N'Aktivite'),
  (-21010, N'Aktivite Opsiyon / Bagli Aktivite Kullan', N'Aktivite'),
  (-21009, N'Aktivite Opsiyon / Tarihce Ekle Turu', N'Aktivite'),
  (-21008, N'Aktivite Opsiyon / Tarihce Ekle TO', N'Aktivite'),
  (-21007, N'Aktivite Opsiyon / Tarihce Ekle Durum', N'Aktivite'),
  (-21006, N'Aktivite Opsiyon / Tarihce Ekle Musteri', N'Aktivite'),
  (-21005, N'Aktivite Opsiyon / Tarihce Ekle Takipci', N'Aktivite'),
  (-21004, N'Aktivite Opsiyon / Tarihce Ekle Sorumlu', N'Aktivite'),
  (-21003, N'Aktivite Opsiyon / Personel Yetki Kontrol', N'Aktivite'),
  (-21002, N'Gorev Xgungoster', N'GorevXgungoster'),
  (-21001, N'Durum Değişikliğinde açıklama bilgisi al', N'Gorev'),
  (-21000, N'Gorev / Peryot', N'Gorev'),
  (-17777, N'Sonraki Sifre Sure Ctrl Tarihi', N'SonrakiSifreSureCtrlTarihi'),
  (-11111, N'Dokum / Degis', N'Dokum'),
  (-11110, N'Tablo No', N'TabloNo'),
  (-10154, N'Genel Opsiyon / Sifre Suresi', N'Genel'),
  (-10140, N'Uyari Opsiyon / Gorunmesin', N'Uyari'),
  (-10138, N'Genel Opsiyon / Tarih Farki Formati', N'Genel'),
  (-10136, N'Genel Opsiyon / Varsay Yabanci Birim', N'Genel'),
  (-10135, N'Genel Opsiyon / Varsay Doviz', N'Genel'),
  (-10130, N'Genel Opsiyon / Rapor Gun', N'Genel'),
  (-10129, N'Genel Opsiyon / Rapor Upd', N'Genel'),
  (-10100, N'Sektor / Liste', N'Sektor'),
  (-10099, N'Genel Opsiyon / Eski Tarih Kayit', N'Genel'),
  (-10098, N'Deneme Login Kalan', N'DenemeLoginKalan'),
  (-10097, N'Lsns Kurum Kodu', N'LsnsKurumKodu'),
  (-10096, N'Lsns Gnclleme', N'LsnsGnclleme'),
  (-10095, N'Lsns SKT', N'LsnsSKT'),
  (-10094, N'Lsns Kul Say', N'LsnsKulSay'),
  (-10093, N'Deneme Login Say', N'DenemeLoginSay'),
  (-10092, N'Server / Sid / Number', N'Server'),
  (-10091, N'Sonraki Lsns Ctrl Tarihi', N'SonrakiLsnsCtrlTarihi'),
  (-10090, N'Son Lsns Ctrl Tarihi', N'SonLsnsCtrlTarihi'),
  (-10089, N'Son Duyuru Ctrl Tarihi', N'SonDuyuruCtrlTarihi'),
  (-10088, N'Genel Opsiyon / Ileri Tarih Kayit', N'Genel'),
  (-10087, N'Proxy Port', N'ProxyPort'),
  (-10086, N'Proxy Adres', N'ProxyAdres'),
  (-10085, N'Yedekleme / Terminalede Yedekle', N'Yedekleme'),
  (-10084, N'Genel Opsiyon / Gorunur Durumu', N'Genel'),
  (-10083, N'Genel Opsiyon / Sifre Yontemi', N'Genel'),
  (-10082, N'Son Kilit Update Tarihi', N'SonKilitUpdateTarihi'),
  (-10081, N'Yedekleme / Son Yedek / Dokuman Tarih', N'Yedekleme'),
  (-10080, N'Yedekleme / Aylik', N'Yedekleme'),
  (-10079, N'Yedekleme / Haftalik', N'Yedekleme'),
  (-10078, N'Yedekleme / Gunluk', N'Yedekleme'),
  (-10077, N'Genel Opsiyon / GSMTel Kod', N'Genel'),
  (-10076, N'Opsiyon Duyuru / Bilgilendirme Sms', N'Duyuru'),
  (-10075, N'Opsiyon Duyuru / Bilgilendirme Mail', N'Duyuru'),
  (-10074, N'Hava Durumu / Il', N'HavaDurumu'),
  (-10073, N'Chat Opsiyon / Port', N'Chat'),
  (-10072, N'Chat Opsiyon / Adres', N'Chat'),
  (-10071, N'Yedekleme / Her Kapanista Yedek', N'Yedekleme'),
  (-10070, N'Genel Opsiyon / Sifre', N'Genel'),
  (-10069, N'Yedekleme / Son Yedek / Cikis', N'Yedekleme'),
  (-10068, N'Yedekleme / Son Yedek / Giris', N'Yedekleme'),
  (-10067, N'Yedekleme / Backup', N'Yedekleme'),
  (-10066, N'Yedekleme / Zip', N'Yedekleme'),
  (-10065, N'Yedekleme / Rar', N'Yedekleme'),
  (-10064, N'Yedekleme / Sifre', N'Yedekleme'),
  (-10063, N'Yedekleme / Kullanici Adi', N'Yedekleme'),
  (-10062, N'Yedekleme / Gecici Surucu', N'Yedekleme'),
  (-10061, N'Yedekleme / Paylasim Yolu', N'Yedekleme'),
  (-10060, N'Yedekleme / Paylasim Adi', N'Yedekleme'),
  (-10059, N'Yedekleme / Tutulacak Gun', N'Yedekleme'),
  (-10058, N'Yedekleme / Tutulacak Check', N'Yedekleme'),
  (-10057, N'Yedekleme / Kapanirken', N'Yedekleme'),
  (-10056, N'Yedekleme / Winrar', N'Yedekleme'),
  (-10055, N'Yedekleme / Yedekleme Adi', N'Yedekleme'),
  (-10054, N'Yedekleme / Yedekleme Dizin', N'Yedekleme'),
  (-10053, N'Genel Opsiyon / Aktarim Kurum Faturalari', N'Genel'),
  (-10052, N'Genel Opsiyon / Aktarim Gun Sonu', N'Genel'),
  (-10051, N'Genel Opsiyon / Aktarim Stok Giris', N'Genel'),
  (-10050, N'Genel Opsiyon / Aktarim Stok Kart', N'Genel'),
  (-10049, N'Genel Opsiyon / Aktarim Rehber Kayitlari', N'Genel'),
  (-10028, N'Genel Opsiyon / KURUMADI', N'Genel'),
  (-10027, N'Genel Opsiyon / BSMV', N'Genel'),
  (-10026, N'Entegrasyon / Ent / DB', N'Entegrasyon'),
  (-10025, N'Entegrasyon / Ent / Server', N'Entegrasyon'),
  (-10024, N'Genel Opsiyon / Rep GSTahsilat', N'Genel'),
  (-10023, N'Genel Opsiyon / Rep GSCari Har', N'Genel'),
  (-10022, N'Genel Opsiyon / Versiyon No', N'Genel'),
  (-10021, N'Genel Opsiyon / SMSHesap Id', N'Genel'),
  (-10020, N'Genel Opsiyon / Eposta Hesap Id', N'Genel'),
  (-10019, N'Genel Opsiyon / ITSHesap Id', N'Genel'),
  (-10018, N'Dokuman / Max Boyut', N'Dokuman'),
  (-10017, N'Dokuman / Kayit / Yeri', N'Dokuman'),
  (-10016, N'İş Listesine Yazılan Uyarılar Aktif', N'Uyari'),
  (-10015, N'Program açılışında döviz kurlarını otomatik olarak güncelle', N'Genel'),
  (-10014, N'Günlük döviz kurları kasa ekranında görünsün', N'Genel'),
  (-10013, N'Değiştirme', N'Genel'),
  (-10012, N'Silme', N'Genel'),
  (-10011, N'Ekleme', N'Genel'),
  (-10009, N'Genel Opsiyon / Gen Yazilim Adres', N'Genel'),
  (-10007, N'Veri Tabani Adi', N'VeriTabaniAdi'),
  (-10006, N'Dokuman / Dizin', N'Dokuman'),
  (-10005, N'Genel Opsiyon / Varsayilan Doviz', N'Genel'),
  (-10004, N'Uyari Opsiyon / Yeni Kayit Suresi', N'Uyari'),
  (-10003, N'Uyari Opsiyon / Yenileme Suresi', N'Uyari'),
  (-10002, N'Genel Opsiyon / Gen Yazilim IPAdress', N'Genel'),
  (-10001, N'Genel Opsiyon / Log', N'Genel'),
  (-10000, N'Sektor', N'Sektor'),
  (-5001, N'Bildirim / Adres', N'Bildirim'),
  (-3540, N'Resmi Tatil Gunleri', N'ResmiTatilGunleri'),
  (-3503, N'ISTEN / CIKIS / SEBEBI', N'ISTEN'),
  (-3502, N'Izin Turleri / Birim', N'IzinTurleri'),
  (-3501, N'Izin Turleri', N'IzinTurleri'),
  (-3402, N'Duyuru Kategori', N'DuyuruKategori'),
  (-3401, N'Seviye', N'Seviye'),
  (-3301, N'Devir Islemleri', N'DevirIslemleri'),
  (-3225, N'Sozlesme / Sure', N'Sozlesme'),
  (-3207, N'Dokuman / Tipi', N'Dokuman'),
  (-3206, N'Dokuman / Gizlilik', N'Dokuman'),
  (-3205, N'Dokuman / Yonu', N'Dokuman'),
  (-3204, N'Dokuman / Kategori', N'Dokuman'),
  (-3203, N'Dokuman / Konusu', N'Dokuman'),
  (-3202, N'Dokuman / Bolumu', N'Dokuman'),
  (-3201, N'Dokuman / Modul', N'Dokuman'),
  (-3027, N'Servis Asama / Durum', N'ServisAsama'),
  (-3015, N'Servis / Genel / Icerik', N'Servis'),
  (-3013, N'Servis / Kapsam', N'Servis'),
  (-3012, N'Servis / Sorunlar', N'Servis'),
  (-3011, N'Servis / Teslim Al', N'Servis'),
  (-3010, N'Servis Detay Guruplari', N'ServisDetayGuruplari'),
  (-3009, N'Servis / Konusu', N'Servis'),
  (-3008, N'Servis / Ucreti', N'Servis'),
  (-3007, N'Servis / Durum', N'Servis'),
  (-3006, N'Servis / Turu', N'Servis'),
  (-3005, N'Servis / Onay Sekli', N'Servis'),
  (-3004, N'Servis / Bildirim / Yazisi', N'Servis'),
  (-3002, N'Servis / Kabul / Sekli', N'Servis'),
  (-3001, N'Servis / Teslim / Sekli', N'Servis'),
  (-2912, N'Teklif / Sebebi', N'Teklif'),
  (-2911, N'Teklif / Sonuc', N'Teklif'),
  (-2909, N'Satin Alma / Asama', N'SatinAlma'),
  (-2908, N'Teklif / Bilgi Sablonu', N'Teklif'),
  (-2907, N'Teklif / Konusu', N'Teklif'),
  (-2905, N'Teklif / Bilgi', N'Teklif'),
  (-2904, N'Teklif / Odeme', N'Teklif'),
  (-2903, N'Teklif / Teslim / Sekli', N'Teklif'),
  (-2902, N'Teklif / Durum', N'Teklif'),
  (-2901, N'Teklif / Turu', N'Teklif'),
  (-2804, N'Demirbas / Marka', N'Demirbas'),
  (-2803, N'Demirbas / Durum', N'Demirbas'),
  (-2802, N'Demirbas / Alim Sekli', N'Demirbas'),
  (-2801, N'Demirbas / Aksiyon', N'Demirbas'),
  (-2799, N'Rep Fason Tipi', N'RepFasonTipi'),
  (-2798, N'Stok Kart / Ekstra Tur', N'Stok'),
  (-2791, N'Stok Kart / Kaynak Uretim Yeri', N'Stok'),
  (-2790, N'Stok Kart / KDV', N'Stok'),
  (-2787, N'Is Emri / Oncelik', N'IsEmri'),
  (-2786, N'Is Emri / Tur', N'IsEmri'),
  (-2785, N'Is Emri / Durum', N'IsEmri'),
  (-2757, N'Stok Kart / Medikal Sinif', N'Stok'),
  (-2756, N'Stok Kart / OTV', N'Stok'),
  (-2755, N'Stok Kart / Muhasebe Kodlari', N'Stok'),
  (-2727, N'Stok Kart / Marka Rakip', N'Stok'),
  (-2726, N'Stok Kart / Kullanim', N'Stok'),
  (-2725, N'Stok Kart / Esdeger Tur', N'Stok'),
  (-2721, N'Stok Kart / Kategori', N'Stok'),
  (-2720, N'Stok Kart / Fis Tipi', N'Stok'),
  (-2718, N'Stok Kart / Icerik', N'Stok'),
  (-2716, N'Stok Kart / Analiz', N'Stok'),
  (-2714, N'Stok Kart / Barkod Tipi', N'Stok'),
  (-2713, N'Stok Kart / Agirlik Birimi', N'Stok'),
  (-2712, N'Stok Kart / Hacim Birimi', N'Stok'),
  (-2711, N'Stok Kart / Alan Birimi', N'Stok'),
  (-2710, N'Stok Kart / Uzunluk Birimi', N'Stok'),
  (-2709, N'Stok Kart / Is Ortagiiliski Turu', N'Stok'),
  (-2708, N'Stok Kart / Durum', N'Stok'),
  (-2707, N'Stok Kart / Zaman Birimi', N'Stok'),
  (-2706, N'Stok Kart / Izleme', N'Stok'),
  (-2705, N'Stok Kart / Ozellik', N'Stok'),
  (-2704, N'Stok Kart / Grubu', N'Stok'),
  (-2703, N'Stok Kart / Tipi', N'Stok'),
  (-2702, N'Stok Kart / Anabirim', N'Stok'),
  (-2701, N'Stok Kart / Marka', N'Stok'),
  (-2651, N'Senet / Durum', N'Senet'),
  (-2602, N'Cek / Durum / Verilen', N'Cek'),
  (-2601, N'Cek / Durum / Alinan', N'Cek'),
  (-2503, N'Talimat / Durum', N'Talimat'),
  (-2488, N'Uretim Emir Turu', N'UretimEmirTuru'),
  (-2411, N'Uretim Turu', N'UretimTuru'),
  (-2407, N'Fatura Tipi', N'FaturaTipi'),
  (-2401, N'Fat Detay Tur', N'FatDetayTur'),
  (-2333, N'KDVIstisna Nedeni', N'KDVIstisnaNedeni'),
  (-2332, N'Tevkifat Nedeni', N'TevkifatNedeni'),
  (-2331, N'Tevkifat Oranlari', N'TevkifatOranlari'),
  (-2329, N'Hizli Satis Kuponlar', N'HizliSatisKuponlar'),
  (-2325, N'Hizli Satis Cafe Kod', N'HizliSatisCafeKod'),
  (-2324, N'Hizli Satis Terazi', N'HizliSatisTerazi'),
  (-2323, N'Hizli Satis Dara Kod', N'HizliSatisDaraKod'),
  (-2322, N'Hizli Satis Transfer Kod', N'HizliSatisTransferKod'),
  (-2321, N'Hizli Satis Siparis Kod', N'HizliSatisSiparisKod'),
  (-2320, N'Hizli Satis Satis Kod', N'HizliSatisSatisKod'),
  (-2319, N'Hizli Satis Cok Satilan Kod', N'HizliSatisCokSatilanKod'),
  (-2318, N'Rest Cok Satilan Kod', N'RestCokSatilanKod'),
  (-2309, N'Excel Maas Esles', N'ExcelMaasEsles'),
  (-2308, N'Odeme Aciklama', N'OdemeAciklama'),
  (-2307, N'Tahsilat Aciklama', N'TahsilatAciklama'),
  (-2306, N'MASRAFAD', N'MASRAFAD'),
  (-2305, N'GELIRAD', N'GELIRAD'),
  (-2303, N'Masraf / Sozlesme Tipi', N'Masraf'),
  (-2302, N'Masraf / Grubu', N'Masraf'),
  (-2301, N'Masraf / Turu', N'Masraf'),
  (-2256, N'IK / YDil', N'İK'),
  (-2255, N'IK / Ogrenim', N'İK'),
  (-2252, N'Bizim / Gorev', N'Bizim'),
  (-2251, N'Bizim / Departman', N'Bizim'),
  (-2250, N'IK / Listeler', N'İK'),
  (-2230, N'IK / Statu', N'İK'),
  (-2221, N'Cari Kart / Isk Turleri', N'Cari'),
  (-2211, N'Cari Kart / PDKSDurum', N'Cari'),
  (-2210, N'Cari Kart / Bolge', N'Cari'),
  (-2209, N'Cari Kart / Statu', N'Cari'),
  (-2208, N'Cari Kart / Kategori', N'Cari'),
  (-2207, N'Cari Kart / Temas', N'Cari'),
  (-2206, N'Cari Kart / Bolum', N'Cari'),
  (-2205, N'Cari Kart / Gorev', N'Cari'),
  (-2204, N'Cari Kart / Sektor', N'Cari'),
  (-2203, N'Cari Kart / Sinif', N'Cari'),
  (-2201, N'Cari Kart / Durum', N'Cari'),
  (-2200, N'Cari Kart / Grup', N'Cari'),
  (-2137, N'Proje / Konusu', N'Proje'),
  (-2134, N'Proje / Durum', N'Proje'),
  (-2133, N'Proje / Asama', N'Proje'),
  (-2132, N'Proje / Turu', N'Proje'),
  (-2131, N'Proje / Aplikasyon', N'Proje'),
  (-2124, N'Firsat / Asama2', N'Firsat'),
  (-2122, N'Gorev / Konusu', N'Gorev'),
  (-2121, N'Firsat / Lojistik / Tipi', N'Firsat'),
  (-2120, N'Ana Kaynak', N'AnaKaynak'),
  (-2119, N'Firsat / Olasilik', N'Firsat'),
  (-2117, N'Firsat / Konusu', N'Firsat'),
  (-2116, N'Firsat / Sebebi', N'Firsat'),
  (-2114, N'Firsat / Durum', N'Firsat'),
  (-2113, N'Firsat / Asama', N'Firsat'),
  (-2112, N'Firsat / Turu', N'Firsat'),
  (-2111, N'Firsat / Aplikasyon', N'Firsat'),
  (-2108, N'Aktivite / Tarihce Durumu', N'Aktivite'),
  (-2107, N'Aktivite / Konu', N'Aktivite'),
  (-2105, N'Aktivite / Durum', N'Aktivite'),
  (-2104, N'Aktivite / Puan', N'Aktivite'),
  (-2103, N'Aktivite / Oncelik', N'Aktivite'),
  (-2102, N'Aktivite / Konum', N'Aktivite'),
  (-2101, N'Aktivite / Tipi', N'Aktivite'),
  (-1016, N'Rep Imha Gerekce', N'RepImhaGerekce'),
  (-1013, N'Desteklenen / Diller', N'Desteklenen'),
  (-1012, N'Tablo Id', N'TabloId'),
  (-1011, N'Belge / Turu', N'Belge'),
  (-1010, N'Belge / Durum S', N'Belge'),
  (-1009, N'Doviz Eslestir', N'DovizEslestir'),
  (-1008, N'Fiyat Liste Adi Alis', N'FiyatListeAdiAlis'),
  (-1007, N'Fiyat Liste Adi', N'FiyatListeAdi'),
  (-1006, N'Depo Varsayilan', N'DepoVarsayilan'),
  (-1005, N'Kasa Turleri', N'KasaTurleri'),
  (-1004, N'KURLAR', N'KURLAR'),
  (-1001, N'Aktif Pasif', N'AktifPasif'),
  (-1000, N'YDil / Aktif', N'YDil'),
  (23057, N'Opsiyon Kasa / Bilgilendirme Mail', N'Kasa'),
  (23058, N'Opsiyon Kasa / Bilgilendirme Sms', N'Kasa'),
  (23066, N'Opsiyon Kasa / Masraflari Odemelerden Derle', N'Kasa'),
  (25001, N'Opsiyon Banka / Masraf Tutar', N'Banka'),
  (25002, N'Opsiyon Banka / Masraf Merkezi', N'Banka'),
  (25003, N'Opsiyon Banka / Gorunecek Subeler', N'Banka'),
  (25004, N'Opsiyon Kredi / Bilgilendirme Mail', N'Kredi'),
  (25005, N'Opsiyon Kredi / Bilgilendirme Sms', N'Kredi'),
  (25006, N'Opsiyon Kredi Karti / Bilgilendirme Mail', N'KrediKarti'),
  (25007, N'Opsiyon Kredi Karti / Bilgilendirme Sms', N'KrediKarti'),
  (25008, N'Opsiyon Banka / Kredi Tipi', N'Banka'),
  (25010, N'Banka / Excelden / Sat Sut', N'Banka'),
  (25011, N'Banka / Excelden / Islemler', N'Banka'),
  (25015, N'Banka / Excel / Atilacak', N'Banka'),
  (25018, N'Opsiyon Banka / Kredi Teminat', N'Banka'),
  (25019, N'Opsiyon Banka / Kredi Limit Sure Tipi', N'Banka'),
  (26001, N'Çek Seri No kontrolü yapsın', N'Çek/Senet'),
  (26002, N'Çek Risk Payı kontrolü yapsın', N'Çek/Senet'),
  (26003, N'Çek Ödemelerinde Masraf Merkezini Ödemeye Aktarsın', N'Çek/Senet'),
  (26004, N'Senet Ödemelerinde Masraf Merkezini Ödemeye Aktarsın', N'Senetler'),
  (26005, N'Cekler / Cek Odemede MMSil', N'Çek/Senet'),
  (26006, N'Opsiyon Senetler / Varsayilan Klasor', N'Senetler'),
  (26007, N'Opsiyon Cekler / Varsayilan Klasor', N'Çek/Senet'),
  (26008, N'Opsiyon Cekler / Bilgilendirme Mail', N'Çek/Senet'),
  (26009, N'Opsiyon Cekler / Bilgilendirme Sms', N'Çek/Senet'),
  (26010, N'Opsiyon Senetler / Bilgilendirme Mail', N'Senetler'),
  (26011, N'Opsiyon Senetler / Bilgilendirme Sms', N'Senetler'),
  (26013, N'Çek girişlerinde kur bilgilisi her bir işlem için sorsun', N'Çek/Senet'),
  (26015, N'Cekler / Birim Risk Tutari', N'Çek/Senet'),
  (27007, N'Opsiyon Stok / Varsayilan Klasor', N'Stok'),
  (27008, N'Stok Opsiyon / Gorunecek Subeler', N'Stok'),
  (28001, N'Opsiyon Demirbas / Varsayilan Klasor', N'Demirbas'),
  (28003, N'Demirbaş ekleme ''Stoktan'' olsun', N'Demirbas'),
  (28008, N'Demirbas Opsiyon / Demirbas Kod Girisi', N'Demirbas'),
  (29001, N'Teklif Opsiyon / No Dijit Say', N'Teklif'),
  (29002, N'Yıllık sıfırla', N'Teklif'),
  (29003, N'Opsiyon Teklif / Varsayilan Klasor', N'Teklif'),
  (29004, N'Opsiyon Teklif / Varsayilan Kur', N'Teklif'),
  (29005, N'Opsiyon Teklif / Onay Bekleme', N'Teklif'),
  (29006, N'Opsiyon Teklif / Onaylandi', N'Teklif');

-- ---- DOGRULAMA ----
SELECT TABLOLAR_yeni=(SELECT COUNT(*) FROM dbo.TABLOLAR WHERE TABLOID IN (80,484,485)),
       LOGCOZUM_yeni=(SELECT COUNT(*) FROM dbo.LOGCOZUM WHERE TABLOID IN (80,485)),
       AYARADI=(SELECT COUNT(*) FROM dbo.AYARADI),
       ISLEMLOG_ALTISLEMTIPI=CASE WHEN COL_LENGTH('GENDEPO.dbo.ISLEMLOG','ALTISLEMTIPI') IS NOT NULL THEN 'VAR' ELSE 'YOK' END;
