IF COL_LENGTH('dbo.SERVIS', 'SERVISNO') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.SERVIS') AND name = 'IX_SERVIS_SERVISNO')
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERVIS_SERVISNO ON dbo.SERVIS(SERVISNO) INCLUDE (ID);
END;
GO

IF COL_LENGTH('dbo.SERVIS', 'SERINO') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.SERVIS') AND name = 'IX_SERVIS_SERINO')
BEGIN
    CREATE NONCLUSTERED INDEX IX_SERVIS_SERINO ON dbo.SERVIS(SERINO) INCLUDE (ID);
END;
GO

