-- ============================================================
-- GenDepoKur4 : EBELGEKUYRUK tablosu (GENDEPO) + ana DB synonym
--   e-Belge gonderim kuyrugu (asenkron gonderim/tekrar deneme). FK -> EBELGE.
--   GenDepoKur2'den (EBELGE) SONRA. Idempotent.
-- ============================================================
-- FILTRELI/UNIQUE INDEKS var: bu SET secenekleri ZORUNLU. sqlcmd varsayilani
-- QUOTED_IDENTIFIER OFF'tur (-I bayragi verilmezse) -> 'CREATE INDEX failed because
-- the following SET options have incorrect settings' hatasi ve KURULUM YARIM kalir.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET NOCOUNT ON;
IF DB_ID('GENDEPO') IS NULL EXEC('CREATE DATABASE [GENDEPO] COLLATE SQL_Latin1_General_CP1254_CI_AS');

IF OBJECT_ID('GENDEPO.dbo.EBELGEKUYRUK','U') IS NULL
EXEC('USE GENDEPO;
CREATE TABLE dbo.EBELGEKUYRUK(
  ID                    int IDENTITY(1,1) NOT NULL,
  EBELGEID              bigint NOT NULL,
  FATBASLIKID           int NULL,
  BELGETURU             tinyint NOT NULL,
  YON                   tinyint NOT NULL,
  ISLEMTURU             tinyint NOT NULL,
  DURUM                 tinyint NOT NULL CONSTRAINT DF_EBELGEKUYRUK_DURUM DEFAULT(0),
  ONCELIK               tinyint NOT NULL CONSTRAINT DF_EBELGEKUYRUK_ONCELIK DEFAULT(5),
  SON_DENEME_TARIHI     datetime NULL,
  SONRAKI_DENEME_TARIHI datetime NULL,
  DENEME_SAYISI         int NOT NULL CONSTRAINT DF_EBELGEKUYRUK_DENEME DEFAULT(0),
  SON_HATA              nvarchar(1000) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  EKLEYEN               int NULL,
  EKLEMETARIHI          datetime NOT NULL CONSTRAINT DF_EBELGEKUYRUK_EKLEMETARIHI DEFAULT(GETDATE()),
  DEGISTIREN            int NULL,
  DEGISTIRMETARIHI      datetime NULL,
  CONSTRAINT PK_BELGEKUYRUK PRIMARY KEY CLUSTERED (ID)
);
CREATE INDEX IX_EBELGEKUYRUK_AKTIF ON dbo.EBELGEKUYRUK(DURUM,SONRAKI_DENEME_TARIHI,ONCELIK,ID)
  INCLUDE(EBELGEID,FATBASLIKID,ISLEMTURU,BELGETURU,YON);
CREATE UNIQUE INDEX UX_EBELGEKUYRUK_AKTIF_IS ON dbo.EBELGEKUYRUK(EBELGEID,ISLEMTURU) WHERE DURUM IN (0,1,9);
IF OBJECT_ID(''dbo.EBELGE'',''U'') IS NOT NULL AND OBJECT_ID(''dbo.FK_BELGEKUYRUK_EBELGE'') IS NULL
  ALTER TABLE dbo.EBELGEKUYRUK WITH CHECK ADD CONSTRAINT FK_BELGEKUYRUK_EBELGE
    FOREIGN KEY(EBELGEID) REFERENCES dbo.EBELGE(ID);
');

IF OBJECT_ID('dbo.EBELGEKUYRUK','U') IS NULL AND OBJECT_ID('dbo.EBELGEKUYRUK','SN') IS NULL
   CREATE SYNONYM dbo.EBELGEKUYRUK FOR GENDEPO.dbo.EBELGEKUYRUK;

SELECT EBELGEKUYRUK = CASE WHEN OBJECT_ID('GENDEPO.dbo.EBELGEKUYRUK','U') IS NOT NULL THEN 'VAR' ELSE 'YOK!' END,
       SYNONYM_DURUM = CASE WHEN OBJECT_ID('dbo.EBELGEKUYRUK','SN') IS NOT NULL THEN 'VAR' ELSE 'YOK/TABLO' END;
