SET NOCOUNT ON;

IF NOT EXISTS (
  SELECT 1
  FROM GENINI
  WHERE BOLUM = -2333
    AND DIL = -1
    AND DEGER = 351
)
BEGIN
  INSERT INTO GENINI (BOLUM, DIL, DEGER, ANAHTAR, SIRA)
  VALUES (-2333, -1, 351, N'351 - İstisna olmayan diğer', 351);
END;
