CREATE OR ALTER TRIGGER [dbo].[trg_SERVIS_SERVISNO_KONTROL]
ON [dbo].[SERVIS]
AFTER INSERT,UPDATE
AS
BEGIN
    SET NOCOUNT ON;

	IF EXISTS (
		SELECT 1
		FROM inserted i
		LEFT JOIN SERVIS S ON S.ID = i.ID
		WHERE ISNULL(S.SERVISNO,'') = '' OR S.SERVISNO IN (' ','0')
	)
	BEGIN
		THROW 50001, 'Servis numarasını giriniz!', 1;
		RETURN;
	END
END
GO

