-- ============================================================
-- trg_Siparis_Aktarim_duzelt.sql   (MUSTERIYE OZEL - BILIM/ALP aktarimi)
--
-- SORUN: SIPARIS uzerindeki trg_Siparis_Aktarim tetikleyicisi nitelenmemis
--   'ALPAPKAKTAR' kolonunu okuyordu. O kolon SIPARIS'te DEGIL, SIPARIS_USER'da
--   (AlpApkAktar). Sonuc: HER "UPDATE/INSERT SIPARIS" ifadesi
--     Msg 207: Invalid column name 'ALPAPKAKTAR'
--   ile patliyordu. Etkilenenler: siparis kaydetme, siparis durumu guncelleme
--   (TM_SiparisDurumGuncelle ve sp_Api_Belge_DurumHesapla_Json), siparisten
--   belgeye donusum.
--
-- IKINCI SORUN: aktarimin hedefi olan AlpAlk veritabani bu sunucuda YOK; yalniz
--   kolon referansi duzeltilseydi bayragi isaretli 170 siparis icin bu kez
--   'Invalid object name AlpAlk..REHBER' hatasi alinacakti.
--
-- DUZELTME (iki nokta):
--   1) LEFT OUTER JOIN SIPARIS_USER SU ON SU.ID = I.ID  ->  SU.AlpApkAktar
--   2) Aktarim blogu 'AND DB_ID(''AlpAlk'') IS NOT NULL' ile korundu; hedef DB
--      yoksa tetikleyici sessizce gecer, siparis islemleri kirilmaz.
--
-- Tetikleyicinin geri kalani AYNEN korunmustur (AlpAlk'e rehber/stok/siparis
--   aktarimi, tutar guncellemesi, DURUM=6 ve satir temizleme mantigi).
--
-- Uygulandi: BILIM, 08.08.2026. Diger musterilerde bu tetikleyici olmayabilir.
-- ============================================================
ALTER TRIGGER [dbo].[trg_Siparis_Aktarim]
ON dbo.SIPARIS
AFTER INSERT,UPDATE
AS
BEGIN
	DECLARE
		@SIPARISID INT,
		@BILIMSIPARISID INT,
		@AKTARIM BIT,
		@OZELKOD NVARCHAR(100),
		@KOD NVARCHAR(100),
		@FIRMA NVARCHAR(100),
		@GRUP INT,
		@REHBERID INT,
		@REHBERILETISIMID INT,
		@SATIRSAY INT,
		@SATIRSAY_ICERIKALP INT,
		@TUR INT

	SET NOCOUNT ON;

	-- 08.08.2026 DUZELTME: AlpApkAktar kolonu SIPARIS'te DEGIL, SIPARIS_USER'da.
	--   Nitelenmemis 'ALPAPKAKTAR' referansi her SIPARIS INSERT/UPDATE'ini
	--   "Invalid column name 'ALPAPKAKTAR'" ile patlatiyordu (siparis kaydetme,
	--   durum guncelleme, siparisten belge donusumu dahil).
	SELECT
		@AKTARIM = CASE WHEN ISNULL(SU.AlpApkAktar,'False') = 'False' THEN 0 ELSE 1 END,
		@BILIMSIPARISID = I.ID,
		@OZELKOD = I.OZELKOD,
		@KOD = R.KOD,
		@FIRMA = R.FIRMA,
		@GRUP = R.GRUP,
		@TUR = I.TUR
	FROM
		inserted I INNER JOIN REHBER R ON R.ID = I.REHBERID
		           LEFT OUTER JOIN SIPARIS_USER SU ON SU.ID = I.ID

	-- Hedef veritabani (AlpAlk) bu sunucuda yoksa aktarim yapilamaz; tetikleyici
	--   sessizce gecer. Aksi halde 'Invalid object name AlpAlk..REHBER' ile
	--   TUM siparis islemleri kirilir.
	IF(@AKTARIM = 1 AND ISNULL(@OZELKOD,'') <> '' AND @TUR = 19 AND DB_ID('AlpAlk') IS NOT NULL) --Aktarım seçili ve özel kod alanı dolu ise
	BEGIN
		IF (EXISTS(SELECT * FROM inserted I INNER JOIN SIPARISDETAY SD ON SD.SIPARISID = I.ID INNER JOIN STOKLAR S ON S.ID = SD.URUNID AND S.ICERIK = 2)) --Sipariş içerisinde stoklarda içerik bayi_alp varsa sipariş oluşacak
		BEGIN
			IF(NOT EXISTS(SELECT * FROM AlpAlk..REHBER R WHERE R.FIRMA = @FIRMA AND R.GRUP = @GRUP))
			BEGIN
				INSERT INTO AlpAlk..REHBER (KOD, FIRMA, GRUP, SINIF, DURUM, EKLEYEN, EKLEMETARIHI, SUBEID,KATEGORI)
				SELECT R.KOD, R.FIRMA, R.GRUP, R.SINIF, R.DURUM, 2 AS EKLEYEN, GETDATE() AS EKLEMETARIHI, R.SUBEID,R.KATEGORI FROM inserted I INNER JOIN REHBER R ON R.ID = I.REHBERID

				SET @REHBERID = (SELECT SCOPE_IDENTITY())

				INSERT INTO AlpAlk..REHBERILETISIM (REHBERID, AD, VARSAYILAN, AKTIF, EKLEYEN, EKLEMETARIHI, SUBEID)
				SELECT @REHBERID, 'Merkez', 1, 1, 2, GETDATE(), -1

				SET @REHBERILETISIMID = (SELECT SCOPE_IDENTITY())

				INSERT INTO AlpAlk..REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN,SUBEID)
				SELECT 
					1,@REHBERILETISIMID,RB.SIRA,RB.ETIKET,RB.BILGI,2,-1
				FROM 
					inserted I 
						INNER JOIN REHBER R ON R.ID = I.REHBERID
						INNER JOIN REHBERILETISIM RI ON RI.REHBERID = R.ID AND RI.VARSAYILAN = 1
						INNER JOIN REHBERBILGI RB ON RB.YERI = 1 AND RB.YER_ID = RI.ID
				UNION ALL
				SELECT 
					2,@REHBERID,RB.SIRA,RB.ETIKET,RB.BILGI,2,-1
				FROM 
					inserted I 
						INNER JOIN REHBER R ON R.ID = I.REHBERID
						INNER JOIN REHBERILETISIM RI ON RI.REHBERID = R.ID AND RI.VARSAYILAN = 1
						INNER JOIN REHBERBILGI RB ON RB.YERI = 1 AND RB.YER_ID = RI.ID
			END

			SET @REHBERID = (SELECT ID FROM AlpAlk..REHBER R WHERE R.FIRMA = @FIRMA AND R.GRUP = @GRUP)
			SET @REHBERILETISIMID =  (SELECT ID FROM AlpAlk..REHBERILETISIM WHERE REHBERID = @REHBERID AND VARSAYILAN = 1)

			IF (NOT EXISTS(SELECT * FROM AlpAlk..SIPARIS WHERE BILIMSIPARISID = @BILIMSIPARISID))
			BEGIN
				INSERT INTO AlpAlk..SIPARIS(TIPI,TARIH, TUR, DURUM, CIKISDEPO,SIPARISTARIH, SIPARISNO, OZELKOD, REHBERID, SIPARIS_MATRAHI, SIPARIS_TUTARI, DOVIZ_TUTARI, FIYAT_LISTESI,BASLIK, ADRES, ILCE, IL, VD, VNO, REHBERILETID, ACIKLAMA, EKLEYEN, EKLEMETARIHI, SUBEID, KUR, RAPORDOVIZ ,DOVIZ_CINSI, DOVIZKUR,KOCANNO,KDVDURUM,BILIMSIPARISID)
				SELECT
					TIPI,TARIH, TUR, DURUM, CIKISDEPO,SIPARISTARIH, SIPARISNO, OZELKOD, @REHBERID, SIPARIS_MATRAHI, SIPARIS_TUTARI, DOVIZ_TUTARI, FIYAT_LISTESI,BASLIK, ADRES, ILCE, IL, VD, VNO, @REHBERILETISIMID, ACIKLAMA, EKLEYEN, EKLEMETARIHI, SUBEID, KUR, RAPORDOVIZ ,DOVIZ_CINSI, DOVIZKUR,KOCANNO,KDVDURUM,ID
				FROM
					inserted

				SET @SIPARISID = (SELECT SCOPE_IDENTITY())
			END

			SET @SIPARISID = (SELECT ID FROM AlpAlk..SIPARIS WHERE BILIMSIPARISID = @BILIMSIPARISID)

			IF (EXISTS(SELECT * FROM inserted I INNER JOIN SIPARISDETAY SD ON SD.SIPARISID = I.ID INNER JOIN STOKLAR S ON S.ID = SD.URUNID AND S.ICERIK = 2 WHERE NOT EXISTS(SELECT * FROM AlpAlk..STOKLAR S1 WHERE S1.KOD = S.KOD)))
			BEGIN
				INSERT INTO AlpAlk..STOKLAR (KOD,STOKADI,KATEGORI,GRUBU,OZELLIK,OZELKOD,MUHKODU,ANABIRIM,BIRIM2,BIRIM2MIKTAR,KDV,DURUM,EKLEYEN,EKLEMETARIHI,SUBEID)	
				SELECT DISTINCT S.KOD,S.STOKADI,S.KATEGORI,S.GRUBU,S.OZELLIK,S.OZELKOD,S.MUHKODU,S.ANABIRIM, S.BIRIM2, S.BIRIM2MIKTAR, S.KDV, S.DURUM,2,GETDATE(),S.SUBEID FROM inserted I INNER JOIN SIPARISDETAY SD ON SD.SIPARISID = I.ID INNER JOIN STOKLAR S ON S.ID = SD.URUNID AND S.ICERIK = 2 WHERE NOT EXISTS(SELECT * FROM AlpAlk..STOKLAR S1 WHERE S1.KOD = S.KOD)
			END

			INSERT INTO AlpAlk..SIPARISDETAY( SIPARISID ,REHBERID, TUR, URUNID, ACIKLAMA, ADET, BIRIM, MIKTAR, BIRIMFIYAT, TUTAR, ISKONTO, KDV, MASRAFID, OZELKOD, KUR, DOVIZ_TUTARI, DOVIZ_KURU, ISKONTO2, DOVIZ_BIRIMFIYAT, DOVIZKURDEGERI, EKLEYEN,  SUBEID, GIRISKAYNAK,BILIMSIPARISDETAYID,TESLIMTARIHI,IZLEME)
			SELECT
				@SIPARISID,@REHBERID,SD.TUR,S1.ID,SD.ACIKLAMA,SD.ADET, SD.BIRIM, SD.MIKTAR, SD.BIRIMFIYAT, SD.TUTAR, SD.ISKONTO, SD.KDV, SD.MASRAFID, SD.OZELKOD, SD.KUR, SD.DOVIZ_TUTARI, SD.DOVIZ_KURU, SD.ISKONTO2, SD.DOVIZ_BIRIMFIYAT, SD.DOVIZKURDEGERI, SD.EKLEYEN,  SD.SUBEID, SD.GIRISKAYNAK,SD.ID,SD.TESLIMTARIHI,SD.IZLEME
			FROM
				inserted I 
					INNER JOIN SIPARISDETAY SD ON SD.SIPARISID = I.ID
					INNER JOIN STOKLAR S ON S.ID = SD.URUNID AND S.ICERIK = 2
					INNER JOIN AlpAlk..STOKLAR S1 ON S1.KOD = S.KOD
			WHERE
				NOT EXISTS(SELECT * FROM AlpAlk..SIPARISDETAY SD1 WHERE SD1.BILIMSIPARISDETAYID = SD.ID)

			UPDATE S SET 
				S.SIPARIS_TUTARI=(select SUM(SD.KDVDAHILFIYAT) from AlpAlk..SIPARISDETAY SD where S.ID=SD.SIPARISID),
				S.SIPARIS_MATRAHI=(select SUM(TUTAR) from AlpAlk..SIPARISDETAY SD where S.ID=SD.SIPARISID),
				S.DOVIZ_TUTARI=(select SUM(SD.DOVIZ_TUTARI*(1 + (SD.KDV / 100.0))) from AlpAlk..SIPARISDETAY SD where S.ID=SD.SIPARISID),
				S.KDV_TUTARI=(select SUM(SD.KDVDAHILFIYAT-SD.TUTAR) from AlpAlk..SIPARISDETAY SD where S.ID=SD.SIPARISID)  
			FROM 
				AlpAlk..SIPARIS S 
			WHERE 
				S.ID = @SIPARISID

		    SET @SATIRSAY = (SELECT COUNT(ID) FROM SIPARISDETAY SD WHERE SD.SIPARISID = @BILIMSIPARISID)
			SET @SATIRSAY_ICERIKALP = (SELECT COUNT(SD.ID) FROM SIPARISDETAY SD INNER JOIN STOKLAR S ON S.ID = SD.URUNID WHERE SD.SIPARISID = @BILIMSIPARISID AND S.ICERIK = 2)
			IF(@SATIRSAY = @SATIRSAY_ICERIKALP)
			BEGIN
				UPDATE SIPARIS SET DURUM = 6 WHERE ID = @BILIMSIPARISID
				UPDATE SIPARISDETAY SET ADET = 0, MIKTAR = 0, BIRIMFIYAT = 0, TUTAR = 0, DOVIZ_BIRIMFIYAT = 0, DOVIZ_TUTARI = 0, ISKONTO = 0 WHERE SIPARISID = @BILIMSIPARISID
			END

			IF(@SATIRSAY <> @SATIRSAY_ICERIKALP)
			BEGIN
				DELETE SD FROM SIPARISDETAY SD WHERE SD.SIPARISID = @BILIMSIPARISID AND EXISTS(SELECT * FROM AlpAlk..SIPARISDETAY SD1 WHERE SD1.BILIMSIPARISDETAYID = SD.ID)
			END

		END
			
	END

END
