-- ============================================================
-- Update_SQL_178.sql   (MSSQL)
-- SGK e-Fatura alanlari
--
-- SGK faturalari icin FATBASLIK.TIPI=25 kullanilir.
-- Senaryo TEMEL kalir; RepSenaryo'ya yeni kayit gerekmez.
-- ============================================================

IF COL_LENGTH('dbo.FATBASLIK_USER', 'SGK_ILAVE_TIPI') IS NULL
    ALTER TABLE dbo.FATBASLIK_USER ADD SGK_ILAVE_TIPI nvarchar(20) NULL;
IF COL_LENGTH('dbo.FATBASLIK_USER', 'SGK_MUKELLEF_KODU') IS NULL
    ALTER TABLE dbo.FATBASLIK_USER ADD SGK_MUKELLEF_KODU nvarchar(50) NULL;
IF COL_LENGTH('dbo.FATBASLIK_USER', 'SGK_MUKELLEF_ADI') IS NULL
    ALTER TABLE dbo.FATBASLIK_USER ADD SGK_MUKELLEF_ADI nvarchar(150) NULL;
IF COL_LENGTH('dbo.FATBASLIK_USER', 'SGK_DOSYA_NO') IS NULL
    ALTER TABLE dbo.FATBASLIK_USER ADD SGK_DOSYA_NO nvarchar(50) NULL;
IF COL_LENGTH('dbo.FATBASLIK_USER', 'SGK_DONEM_BAS') IS NULL
    ALTER TABLE dbo.FATBASLIK_USER ADD SGK_DONEM_BAS date NULL;
IF COL_LENGTH('dbo.FATBASLIK_USER', 'SGK_DONEM_BIT') IS NULL
    ALTER TABLE dbo.FATBASLIK_USER ADD SGK_DONEM_BIT date NULL;

IF NOT EXISTS (SELECT 1 FROM dbo.GENINI WHERE BOLUM=-2407 AND ANAHTAR=N'SGK' AND DIL=-1)
    INSERT INTO dbo.GENINI (BOLUM, ANAHTAR, DEGER, SIRA, DIL)
    VALUES (-2407, N'SGK', N'25', 25, -1);
ELSE
    UPDATE dbo.GENINI
       SET DEGER=N'25', SIRA=COALESCE(SIRA, 25)
     WHERE BOLUM=-2407 AND ANAHTAR=N'SGK' AND DIL=-1;

DECLARE @Ekran varchar(50) = 'FaturaWizardDlg';
DECLARE @Tablo nvarchar(60) = N'FATBASLIK_USER';
DECLARE @Konum varchar(20) = 'PanelEkAlanlar';

UPDATE dbo.ALANLAR SET TUR=1, CAPTION='SGK Ilave Tipi', SQL=NULL, [TOP]=20
 WHERE EKRANADI=@Ekran AND ALANADI='SGK_ILAVE_TIPI';
UPDATE dbo.ALANLAR SET TUR=1, CAPTION='SGK Mukellef Kodu', [TOP]=20
 WHERE EKRANADI=@Ekran AND ALANADI='SGK_MUKELLEF_KODU';
UPDATE dbo.ALANLAR SET TUR=1, CAPTION='SGK Mukellef Adi', [TOP]=20
 WHERE EKRANADI=@Ekran AND ALANADI='SGK_MUKELLEF_ADI';
UPDATE dbo.ALANLAR SET TUR=1, CAPTION='SGK Dosya No', [TOP]=70
 WHERE EKRANADI=@Ekran AND ALANADI='SGK_DOSYA_NO';
UPDATE dbo.ALANLAR SET TUR=3, CAPTION='SGK Donem Bas.', [TOP]=70
 WHERE EKRANADI=@Ekran AND ALANADI='SGK_DONEM_BAS';
UPDATE dbo.ALANLAR SET TUR=3, CAPTION='SGK Donem Bit.', [TOP]=70
 WHERE EKRANADI=@Ekran AND ALANADI='SGK_DONEM_BIT';

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='LBL_SGK_ILAVE')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,11,@Tablo,'LBL_SGK_ILAVE','SGK Ilave Tipi',NULL,@Konum,25,20,2,0,0,0,'Tahoma','clWindowText',8,'16777215',18,180,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='LBL_SGK_MKOD')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,11,@Tablo,'LBL_SGK_MKOD','SGK Mukellef Kodu',NULL,@Konum,25,220,2,0,0,0,'Tahoma','clWindowText',8,'16777215',18,130,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='LBL_SGK_MADI')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,11,@Tablo,'LBL_SGK_MADI','SGK Mukellef Adi',NULL,@Konum,25,370,2,0,0,0,'Tahoma','clWindowText',8,'16777215',18,220,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='LBL_SGK_DOSYA')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,11,@Tablo,'LBL_SGK_DOSYA','SGK Dosya No',NULL,@Konum,25,20,52,0,0,0,'Tahoma','clWindowText',8,'16777215',18,180,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='LBL_SGK_DBAS')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,11,@Tablo,'LBL_SGK_DBAS','SGK Donem Bas.',NULL,@Konum,25,220,52,0,0,0,'Tahoma','clWindowText',8,'16777215',18,130,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='LBL_SGK_DBIT')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,11,@Tablo,'LBL_SGK_DBIT','SGK Donem Bit.',NULL,@Konum,25,370,52,0,0,0,'Tahoma','clWindowText',8,'16777215',18,130,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='SGK_ILAVE_TIPI')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,1,@Tablo,'SGK_ILAVE_TIPI','SGK Ilave Tipi',
       NULL,@Konum,25,20,20,0,0,0,'Tahoma','clWindowText',8,'16777215',21,180,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='SGK_MUKELLEF_KODU')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,1,@Tablo,'SGK_MUKELLEF_KODU','SGK Mukellef Kodu',NULL,@Konum,25,220,20,0,0,0,'Tahoma','clWindowText',8,'16777215',21,130,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='SGK_MUKELLEF_ADI')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,1,@Tablo,'SGK_MUKELLEF_ADI','SGK Mukellef Adi',NULL,@Konum,25,370,20,0,0,0,'Tahoma','clWindowText',8,'16777215',21,220,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='SGK_DOSYA_NO')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,1,@Tablo,'SGK_DOSYA_NO','SGK Dosya No',NULL,@Konum,25,20,70,0,0,0,'Tahoma','clWindowText',8,'16777215',21,180,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='SGK_DONEM_BAS')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,3,@Tablo,'SGK_DONEM_BAS','SGK Donem Bas.',NULL,@Konum,25,220,70,0,0,0,'Tahoma','clWindowText',8,'16777215',21,130,1,GETDATE(),1);

IF NOT EXISTS (SELECT 1 FROM dbo.ALANLAR WHERE EKRANADI=@Ekran AND ALANADI='SGK_DONEM_BIT')
    INSERT INTO dbo.ALANLAR
      (EKRANADI,TUR,TABLO,ALANADI,CAPTION,SQL,KONUM,TAG,[LEFT],[TOP],BOLD,ITALIK,ALTCIZGI,FONT,FONTCOLOR,FONTSIZE,ARKARENK,HEIGHT,WIDTH,EKLEYEN,EKLEMETARIHI,SUBEID)
    VALUES
      (@Ekran,3,@Tablo,'SGK_DONEM_BIT','SGK Donem Bit.',NULL,@Konum,25,370,70,0,0,0,'Tahoma','clWindowText',8,'16777215',21,130,1,GETDATE(),1);


