USE BILIM;
GO

CREATE OR ALTER PROC [dbo].[sp_Grnt_AlisFaturaIslem](@jsonData NVARCHAR(MAX), @TIP INT, @SONUC_ID INT OUTPUT,@SONUC_MESAJ VARCHAR(5000) OUTPUT)
AS
BEGIN
    DECLARE
        @GNTP_FATBASLIKID INT,
        @FATBASID INT,
        @REHBERID INT,
        @FATURATARIHI DATETIME,
        @TUR VARCHAR(50),
        @ACIKLAMA VARCHAR(250),
        @FATURA_MATRAHI MONEY,
        @KDV_TUTARI MONEY,
        @FATURA_TUTARI MONEY,
        @KUR NVARCHAR(50),
        @DOVIZ_CINSI NVARCHAR(50),
        @DOVIZKUR MONEY,
        @DOVIZ_TUTARI MONEY,
        @RAPORDOVIZ NVARCHAR(50),
        @EKLEYEN INT,
        @PROJEID INT,
        @SUBE NVARCHAR(100),
        @SUBEID INT,
        @EKLEMETARIHI DATETIME,
        @DURUM INT,
        @DEPO NVARCHAR(100),
        @DEPOID INT,
        @FATURANO NVARCHAR(100),
        @KDVDURUM NVARCHAR(100),
        @BASLIK NVARCHAR(100),
        @ADRES NVARCHAR(200),
        @ILCE NVARCHAR(200),
        @IL NVARCHAR(200),
        @VD NVARCHAR(200),
        @VNO NVARCHAR(200),
        @REHBERILETID INT,
        @FIRMA NVARCHAR(200),
        @FIYATLISTEID INT,
        @GNTP_KULLANID INT,
        @REHBERID_SATICI INT,
        -- YENI: JSON'dan opsiyonel olarak gelen GIRISDEPO, ACIK_KAPALI ve SUBEID
        @GIRISDEPO_PARAM SMALLINT,
        @ACIKKAPALI_PARAM BIT,
        @SUBEID_PARAM INT,
        @GIRISDEPO_FINAL SMALLINT,
        @ACIKKAPALI_FINAL BIT,
        @SUBEID_FINAL INT

    SELECT
        @GNTP_FATBASLIKID = JSON_VALUE(@jsonData, '$.FATBASLIKID'),
        @FATBASID = JSON_VALUE(@jsonData, '$.FATBASID'),
        @FATURATARIHI = JSON_VALUE(@jsonData, '$.FATURATARIHI'),
        @FATURANO = JSON_VALUE(@jsonData, '$.FATURANO'),
        @REHBERID = JSON_VALUE(@jsonData, '$.REHBERID'),
        @FATURA_MATRAHI = JSON_VALUE(@jsonData, '$.FATURA_MATRAHI'),
        @KDV_TUTARI = JSON_VALUE(@jsonData, '$.KDV_TUTARI'),
        @FATURA_TUTARI = JSON_VALUE(@jsonData, '$.FATURA_TUTARI'),
        @KUR = JSON_VALUE(@jsonData, '$.KUR'),
        @DOVIZ_CINSI = JSON_VALUE(@jsonData, '$.DOVIZ_CINSI'),
        @DOVIZKUR = JSON_VALUE(@jsonData, '$.DOVIZKUR'),
        @DOVIZ_TUTARI = JSON_VALUE(@jsonData, '$.DOVIZ_TUTARI'),
        @EKLEYEN = JSON_VALUE(@jsonData, '$.EKLEYEN'),
        @SUBE = JSON_VALUE(@jsonData, '$.SUBE'),
        @ACIKLAMA = JSON_VALUE(@jsonData, '$.ACIKLAMA'),
        @KDVDURUM = JSON_VALUE(@jsonData, '$.KDVDURUM'),
        @GNTP_KULLANID = JSON_VALUE(@jsonData, '$.GNTP_KULLANID'),
        @DEPO = JSON_VALUE(@jsonData, '$.DEPO'),
        @GIRISDEPO_PARAM = JSON_VALUE(@jsonData, '$.GIRISDEPO'),
        @ACIKKAPALI_PARAM = JSON_VALUE(@jsonData, '$.ACIK_KAPALI'),
        @SUBEID_PARAM = JSON_VALUE(@jsonData, '$.SUBEID')

    SET @DURUM = 0
    SET @SUBEID = CASE WHEN @SUBE = 0 THEN 0 ELSE (SELECT ID FROM REHBER WHERE FIRMA = @SUBE AND ID < 0) END
    SET @EKLEYEN = 2
    SET @EKLEMETARIHI = GETDATE()
    SET @TUR = 11
    SET @SONUC_ID = 0
    SET @SONUC_MESAJ = N'İşlem başarısız.'

    SET @REHBERID = ISNULL(@REHBERID,4)
    -- Lookup'lar kaldirildi. BASLIK/ADRES/ILCE/IL/VD/VNO/REHBERILETID JSON'dan gelir;
    -- gelmiyorsa NULL olur. Caller ihtiyaca gore doldurur.
    SET @BASLIK = JSON_VALUE(@jsonData, '$.BASLIK')
    SET @ADRES = JSON_VALUE(@jsonData, '$.ADRES')
    SET @ILCE = JSON_VALUE(@jsonData, '$.ILCE')
    SET @IL = JSON_VALUE(@jsonData, '$.IL')
    SET @VD = JSON_VALUE(@jsonData, '$.VD')
    SET @VNO = JSON_VALUE(@jsonData, '$.VNO')
    SET @REHBERILETID = JSON_VALUE(@jsonData, '$.REHBERILETID')
    SET @FIRMA = NULL

    SET @REHBERID_SATICI = (SELECT ID FROM REHBER WHERE GRUP = 335 AND GNTPID = @GNTP_KULLANID)

    IF(NOT EXISTS(SELECT ID FROM DEPOLAR D WHERE D.DEPOADI = @DEPO))
    BEGIN
        INSERT INTO DEPOLAR (DEPOADI,DURUM,SUBEID)
        SELECT @DEPO,1,@SUBEID
        SET @DEPOID = (SELECT SCOPE_IDENTITY())
    END
    SET @DEPOID = (SELECT TOP 1 ID FROM DEPOLAR D WHERE D.DEPOADI = @DEPO ORDER BY ID)

    SET @KDVDURUM = N'Hariç'

    -- YENI: GIRISDEPO, ACIK_KAPALI ve SUBEID varsayilanlari
    --   GIRISDEPO: JSON'dan gelmiyorsa 1
    --   ACIK_KAPALI: JSON'dan gelmiyorsa 0
    --   SUBEID    : JSON'dan gelmiyorsa, var olan @SUBEID NULL ise -1
    SET @GIRISDEPO_FINAL = ISNULL(@GIRISDEPO_PARAM, 1)
    SET @ACIKKAPALI_FINAL = ISNULL(@ACIKKAPALI_PARAM, 0)
    SET @SUBEID_FINAL = ISNULL(@SUBEID_PARAM, -1)

    DECLARE @FaturaDipToplam AS TABLE (
           [FATBASID] int,
           [TUR] float NULL,
           [ACIKLAMA] VARCHAR(255) NULL,
           [DEGER] FLOAT NULL,
           [DOVIZTUTARI] FLOAT NULL,
           [KUR] VARCHAR(5) NULL,
           [DOVIZ_KURU] VARCHAR(5) NULL,
           [DOVIZKUR] FLOAT NULL,
           [KDVMUHAFIYETI] SMALLINT NULL,
           [FATURADOVIZI] VARCHAR(5) NULL
    )

    SET @FIYATLISTEID = (SELECT TOP 1 DEGER FROM GENINI WHERE BOLUM = -1008 AND ANAHTAR = N'Alış')

    BEGIN TRY
        IF @TIP = 1
        BEGIN
            IF (ISNULL(@GNTP_FATBASLIKID,0) <> 0 AND NOT EXISTS (SELECT ID FROM FATBASLIK WHERE GNTPID = @GNTP_FATBASLIKID AND TUR = @TUR AND REHBERID = @REHBERID) AND EXISTS(SELECT ID FROM REHBER WHERE ID = @REHBERID))
            BEGIN
                SET @FIRMA = (SELECT FIRMA FROM REHBER WHERE ID = @REHBERID)


                INSERT INTO FATBASLIK(TIPI,TARIH, TUR, DURUM, GIRISDEPO,FATURATARIH, FATURANO ,REHBERID, FATURA_MATRAHI, FATURA_TUTARI, DOVIZ_TUTARI, FIYAT_LISTESI,BASLIK, ADRES, ILCE, IL, VD, VNO, REHBERILETID, ACIKLAMA, EKLEYEN, EKLEMETARIHI, SUBEID, KUR, FATURADOVIZI,RAPORDOVIZ ,DOVIZ_CINSI, DOVIZKUR,KOCANNO,GNTP_FATBASID,
                KDVDURUM,SATICIKODU, ACIK_KAPALI)
                SELECT  1,@FATURATARIHI,@TUR, @DURUM, @GIRISDEPO_FINAL ,@FATURATARIHI, @FATURANO, @REHBERID, @FATURA_MATRAHI,@FATURA_TUTARI,@DOVIZ_TUTARI,@FIYATLISTEID ,ISNULL(@BASLIK,@FIRMA), @ADRES, @ILCE, @IL, @VD, @VNO, @REHBERILETID, @ACIKLAMA,  @EKLEYEN, @EKLEMETARIHI, @SUBEID_FINAL, @KUR,FATURADOVIZI = N'TL',CASE WHEN @DOVIZ_CINSI <> N'TL' THEN @DOVIZ_CINSI ELSE N'TL' END ,ISNULL(@DOVIZ_CINSI,N'TL'), ISNULL(@DOVIZKUR,1), 0 ,@GNTP_FATBASLIKID, @KDVDURUM,@REHBERID_SATICI, @ACIKKAPALI_FINAL

                SET @FATBASID = (SELECT SCOPE_IDENTITY())
                SET @SONUC_ID = 1
                SET @SONUC_MESAJ = N'İşlem başarılı.'
            END

        END
        ELSE
        BEGIN
            SET @SONUC_ID = 12
            SET @SONUC_MESAJ = N'Bu kayıt daha önce eklenmiş.X'
        END


    IF @TIP = 0
    BEGIN

        DELETE FROM FATURA WHERE FATBASID = @FATBASID
        DELETE FROM FATBASLIK WHERE ID = @FATBASID

        SET @SONUC_ID = 1
        SET @SONUC_MESAJ = N'İşlem başarılı.'
    END

    IF @TIP = 2
    BEGIN

        IF (ISNULL(@FATBASID,0) <> 0)
        BEGIN

            UPDATE FATBASLIK SET FATURATARIH = @FATURATARIHI, TARIH = @FATURATARIHI, GIRISDEPO = @GIRISDEPO_FINAL, ACIKLAMA = @ACIKLAMA,DEGISTIRMETARIHI = GETDATE(),BASLIK = @BASLIK, ADRES = @ADRES, ILCE = @ILCE, IL = @IL, VD = @VD, VNO = @VNO, REHBERILETID = @REHBERILETID, SATICIKODU = @REHBERID_SATICI, FATURANO = @FATURANO, FIYAT_LISTESI = @FIYATLISTEID WHERE ID = @FATBASID

            INSERT INTO @FaturaDipToplam (TUR,ACIKLAMA,DEGER,DOVIZTUTARI,KUR,DOVIZ_KURU,DOVIZKUR,KDVMUHAFIYETI,FATURADOVIZI)
            EXEC SP_PRG_FaturaDipToplami @FATBASID

            UPDATE @FaturaDipToplam SET FATBASID = @FATBASID

            UPDATE FB SET
                FB.FATURA_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = N'Genel Toplam'),
                FB.FATURA_MATRAHI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = N'Ara Toplam'),
                FB.DOVIZ_TUTARI=(SELECT FB1.DOVIZTUTARI FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = N'Genel Toplam'),
                FB.KDV_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = N'KDV Toplam')
            FROM
                FATBASLIK FB INNER JOIN @FaturaDipToplam FB1 ON FB1.FATBASID = FB.ID
            WHERE
                FB.ID = @FATBASID

            SET @SONUC_ID = 1
            SET @SONUC_MESAJ = N'İşlem başarılı.'
        END

    END
    END TRY
    BEGIN CATCH
        SET @SONUC_ID = -2;
        SET @SONUC_MESAJ = ERROR_MESSAGE();
    END CATCH
END
GO
