 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 1 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 1 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',1,'SAYFA','BOYUT','A4 21x29.7cm',null,null,null,null,null,NULL,null,NULL,NULL,'YAN',NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 11 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 11 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',11,'BAND','DETAY','VADEISLEM',null,null,null,null,0.5,NULL,null,NULL,NULL,NULL,NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 20 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 20 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',20,'SABÝT',NULL,'GEN YAZILIM',9,0,0,null,null,'Tahoma',10,NULL,'BOLD',NULL,NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 30 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 30 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',30,'SABÝT',NULL,'Cari Kod',9,0,2,null,null,'Tahoma',8,NULL,'BOLD',NULL,NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 31 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 31 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',31,'SABÝT','','Cari Ad',9,3,2,null,null,'Tahoma',8,'','BOLD','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 32 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 32 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',32,'SABÝT','','Açýklama',9,9,2,null,null,'Tahoma',8,'','BOLD','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 33 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 33 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',33,'SABÝT','','Giren',9,15,2,null,null,'Tahoma',8,'','BOLD','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 34 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 34 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',34,'SABÝT','','Çýkan',9,18,2,null,null,'Tahoma',8,'','BOLD','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 35 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 35 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',35,'SABÝT','','Hesap Kodu',9,21,2,null,null,'Tahoma',8,'','BOLD','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 36 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 36 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',36,'SABÝT','','Hesap Adý',9,24,2,null,null,'Tahoma',8,'','BOLD','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 38 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 38 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',38,'ÇÝZÝM','YATAYÇÝZGÝ','DÜZ',9,0,2.5,29,null,NULL,null,NULL,NULL,NULL,NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 5 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 5 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',5,'SAYFA','TABLO','VADEISLEM',null,null,null,null,null,NULL,null,NULL,NULL,NULL,NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 60 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 60 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',60,'ALAN','VADEISLEM','CARIKOD',11,0,0,null,null,'Tahoma',8,NULL,NULL,NULL,NULL)

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 61 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 61 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',61,'ALAN','VADEISLEM','CARIAD',11,3,0,null,null,'Tahoma',8,'','','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 62 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 62 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',62,'ALAN','VADEISLEM','ACIKLAMA',11,9,0,null,null,'Tahoma',8,'','','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 63 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 63 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',63,'ALAN','VADEISLEM','GIREN',11,15,0,null,null,'Tahoma',8,'','','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 64 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 64 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',64,'ALAN','VADEISLEM','CIKAN',11,18,0,null,null,'Tahoma',8,'','','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 65 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 65 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',65,'ALAN','VADEISLEM','HESAPKODU',11,21,0,null,null,'Tahoma',8,'','','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 66 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 66 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',66,'ALAN','VADEISLEM','HESAPADI',11,24,0,null,null,'Tahoma',8,'','','','')

 
IF EXISTS( SELECT * FROM AYARLAR WHERE	RAPORADI = 'VadeListe_' AND SIRANO = 9 ) DELETE FROM AYARLAR WHERE RAPORADI = 'VadeListe_' 
AND SIRANO = 9 INSERT INTO AYARLAR (RAPORADI, SIRANO, ALANTURU, TABLO, 
ALANADI, BANDNO, SOL, UST, EN, BOY, FONT, PUNTO, RENK, OZELLIK, YANASIK, 
[FORMAT]) VALUES('VadeListe_',9,'BAND','RAPORBAÞI',NULL,null,null,null,null,3,NULL,null,NULL,NULL,NULL,NULL)

 IF EXISTS( SELECT * FROM KOSULLAR WHERE	RAPORADI = 
'VadeListe_' ) DELETE FROM KOSULLAR WHERE RAPORADI = 'VadeListe_' 

