/* Gentegre — ortak ekran/modul veri modeli (tum kabuk surumleri bunu kullanir) */
var MODULLER = [
  {id:'iletisim', ad:'İletişim & AI', ad_en:'Communication & AI', ic:'💬', bolumler:[
    {id:'umesajlar', ad:'Mesajlar', ad_en:'Messages', ic:'💬', dosya:'umesajlar.html', tur:'liste', sade:1,
      kart:null, yol:'Sosyal\\UMesajlarFrame · UMESAJ · UMESAJUYE',
      arac:['Yeni Sohbet','Yeni Grup','Kayıt İliştir','Görev Oluştur','Arşivle'],
      arama:[{l:'Kişi / Grup',t:'text'},{l:'Mesaj içinde',t:'text'},{l:'Departman',t:'combo',v:'(tümü)'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.08.2026','15.08.2026']}]},
    {id:'ai_asistan', ad:'Gentegre Yapay Zeka', ad_en:'Gentegre AI', ic:'✨', dosya:'ai_asistan.html', tur:'islem', sade:1,
      yol:'AI\\UAsistanFrame · AISOHBET · AIARAC · AILOG'},
    {id:'proje_dosyasi', ad:'Proje Dosyası', ad_en:'Project Dossier', ic:'📘', dosya:'gentegre_ai_proje_dosyasi.html', tur:'ayar',
      yol:'Doküman · Gentegre AI mimari ve teknoloji kararları (sürüm 1.0)'},
    {id:'uygulama_plani', ad:'Uygulama Planı', ad_en:'Implementation Plan', ic:'🗺', dosya:'gentegre_ai_uygulama_plani.html', tur:'ayar',
      yol:'Doküman · Faz 0 sözleşmeleri, Faz 1 dikey dilim, SP göçü (plan modu)'},
    {id:'degerlendirme', ad:'Değerlendirme', ad_en:'Assessment', ic:'🧭', dosya:'gentegre_ai_projesi_degerlendirme.html', tur:'ayar',
      yol:'Doküman · Bağımsız proje değerlendirmesi (15.08.2026)'}
  ]},

  {id:'giris', ad:'Gen', ad_en:'Gen', ic:'🏠', bolumler:[
    {id:'home',            ad:'Ana Sayfa', ad_en:'Home',        ic:'🏠', dosya:null,                  tur:'panel', yol:'GirisSayfaFrame\\UGenelGirisFrame'},
    {id:'giris_sayfasi',   ad:'Giriş Sayfası', ad_en:'Landing Page',    ic:'📊', dosya:'giris_sayfasi.html',  tur:'panel', yol:'GirisSayfaFrame\\UGirisSayfaFrame'}
  ]},

  {id:'crm', ad:'CRM', ad_en:'CRM', ic:'🧭', bolumler:[
    {id:'cari_liste_ekrani', ad:'Potansiyel Müşteriler', ad_en:'Leads', ic:'🤝', dosya:'cari_liste_ekrani.html', tur:'liste',
      kart:'cari_karti', yol:'ListeFrame\\UCariListeDlg (potansiyel)',
      arac:['Cariye Dönüştür','Fırsat Aç'], arama:[{l:'Ünvan',t:'text'},{l:'Sektör',t:'combo',v:'(tümü)'},{l:'Kaynak',t:'combo',v:'(tümü)'},{l:'Temsilci',t:'combo',v:'(tümü)'},{l:'Şehir',t:'text'}]},
    {id:'firsat_listesi',    ad:'Satış Fırsatları', ad_en:'Opportunities',      ic:'🎯', dosya:'firsat_listesi.html',    tur:'liste',
      kart:'firsat_karti', yol:'ListeFrame\\UFirsatListeDlg · FIRSAT',
      arac:['Aşama Değiştir','Teklif Oluştur','Aktivite Ekle','Kazanıldı','Kaybedildi'],
      arama:[{l:'Fırsat Kodu',t:'text'},{l:'Müşteri',t:'text'},{l:'Türü',t:'combo',v:'(tümü)'},{l:'Aşama',t:'combo',v:'(tümü)'},{l:'Sorumlu',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'proje_listesi',     ad:'Projeler', ad_en:'Projects',              ic:'📐', dosya:'proje_listesi.html',     tur:'liste',
      kart:'proje_karti',  yol:'ListeFrame\\UProjeListeDlg · PROJELER · PROJEKULLANICI · PROJEASAMA · PROJEBUTCE',
      arac:['İş Emri Aç','Maliyet Analizi','Görev Ekle','Aşama İlerlet','Ekip Ata','Hakediş / Faturala'],
      arama:[{l:'Proje Kodu',t:'text'},{l:'Proje Adı',t:'text'},{l:'Müşteri',t:'text'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Devam Ediyor'},{l:'Proje Müdürü',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'is_listesi',        ad:'İş Listesi', ad_en:'Task List',            ic:'✅', dosya:'is_listesi.html',        tur:'liste',
      kart:'gorev_karti',  yol:'ListeFrame\\UIsListeDlg · GOREVLER',
      arac:['Tamamla','Ata','Ertele'], arama:[{l:'Konusu',t:'text'},{l:'Atanan',t:'combo',v:'(tümü)'},{l:'Liste',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Açık'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'crm_dokum',         ad:'Dökümler', ad_en:'Reports',              ic:'🖨️', dosya:'dokumler.html', ek:'&mod=crm', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'cari', ad:'Cari', ad_en:'Accounts', ic:'👥', bolumler:[
    {id:'musteriler', ad:'Müşteriler', ad_en:'Customers', ic:'🙋', dosya:'cari_liste_ekrani_Ver2.html', ek:'&tur=m', tur:'liste',
      kart:'musteri_karti', yol:'ListeFrame\\UCariListeDlg · CARI (hesap kodu 120.x — alıcılar + bayi)',
      arac:['Ekstre','Risk / Limit','İş Listesi','Sipariş Geçmişi','Aksiyon'],
      arama:[{l:'Ünvan',t:'text'},{l:'Kod',t:'text'},{l:'Grup',t:'combo',v:'Tümü'},{l:'Kategori',t:'combo',v:'Tümü'},{l:'Sektör',t:'combo',v:'Tümü'},{l:'Temsilci',t:'combo',v:'Tümü'},{l:'Özel Kod',t:'text'}]},
    {id:'tedarikciler', ad:'Tedarikçiler', ad_en:'Suppliers', ic:'🚚', dosya:'cari_liste_ekrani_Ver2.html', ek:'&tur=t', tur:'liste',
      kart:'tedarikci_karti', yol:'ListeFrame\\UCariListeDlg · CARI (hesap kodu 320.x — satıcılar)',
      arac:['Ekstre','Risk / Limit','Alım Geçmişi','Tedarikçi Değerlendirme','Aksiyon'],
      arama:[{l:'Ünvan',t:'text'},{l:'Kod',t:'text'},{l:'Grup',t:'combo',v:'Tümü'},{l:'Kategori',t:'combo',v:'Tümü'},{l:'Sektör',t:'combo',v:'Tümü'},{l:'Vade / Ödeme Planı',t:'combo',v:'Tümü'},{l:'Özel Kod',t:'text'}]},
    {id:'kisi_listesi', ad:'Kişiler', ad_en:'Contacts', ic:'🧑', dosya:'kisi_listesi.html', tur:'liste',
      kart:'kisi_karti', yol:'ListeFrame\\UKisiListeDlg · KISI · KISIAKTIVITE · KISIIZIN',
      arac:['Cariye Bağla','Aktivite Ekle','Toplu E-posta','vCard Aktar','Etiketle'],
      arama:[{l:'Ad Soyad',t:'text'},{l:'Cari',t:'text'},{l:'Görev / Ünvan',t:'text'},{l:'Rol',t:'combo',v:'(tümü)'},{l:'Şehir',t:'text'},{l:'E-posta / Telefon',t:'text'}]},
    {id:'rehber_arama', ad:'Rehber Arama', ad_en:'Directory Search', ic:'🔎', dosya:'rehber_arama.html', tur:'islem',
      yol:'URehberAramaEkrani (modal) · CARI + KISI birleşik arama · vw_Rehber'},
    {id:'cari_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=cari', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'kasa', ad:'Kasa', ad_en:'Cash', ic:'💵', bolumler:[
    {id:'kasa_listesi', ad:'Kasalar', ad_en:'Cash Accounts', ic:'💰', dosya:'kasa_listesi.html', tur:'liste',
      kart:'banka_hesabi', yol:'ListeFrame\\UKasaListeDlg · KASA',
      arac:['Tahsilat','Ödeme','Virman','Gün Sonu Sayım'],
      arama:[{l:'Kasa Adı',t:'text'},{l:'Kasa Kodu',t:'text'},{l:'Para Birimi',t:'combo',v:'(tümü)'},{l:'Sorumlu',t:'combo',v:'(tümü)'},{l:'Şube',t:'combo',v:'Merkez'}]},
    {id:'pos_ekrani', ad:'Hızlı Satış (POS)', ad_en:'Quick Sale (POS)', ic:'🧮', dosya:'pos_ekrani.html', tur:'islem', yol:'Rest\\UPosEkrani'},
    {id:'kasa_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=kasa', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'satislar', ad:'Satış', ad_en:'Sales', ic:'🧾', bolumler:[
    {id:'satis_siparis_listesi', ad:'Alınan Siparişler', ad_en:'Sales Orders', ic:'📥', dosya:'satis_siparis_listesi.html', tur:'liste',
      kart:'satis_siparis_karti', yol:'ListeFrame\\USiparisListeDlg · SIPBASLIK/SIPSATIR (Satış)',
      arac:['İrsaliyeye Dönüştür','Faturaya Dönüştür','Üretime Aktar','Rezerve Et'],
      arama:[{l:'Sipariş No',t:'text'},{l:'Müşteri',t:'text'},{l:'Temsilci',t:'combo',v:'(tümü)'},{l:'Sevk Durumu',t:'combo',v:'(tümü)'},{l:'Termin',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'satis_irsaliye_listesi', ad:'Satış İrsaliyeleri', ad_en:'Sales Delivery Notes', ic:'🚛', dosya:'satis_irsaliye_listesi.html', tur:'liste',
      kart:'satis_irsaliye_karti', yol:'ListeFrame\\UIrsaliyeListeDlg · IRSBASLIK/IRSSATIR (Satış)',
      arac:['Faturaya Dönüştür','e-İrsaliye Gönder','Sevk Fişi Yazdır'],
      arama:[{l:'İrsaliye No',t:'text'},{l:'Müşteri',t:'text'},{l:'Çıkış Deposu',t:'combo',v:'(tümü)'},{l:'e-İrsaliye Durumu',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'fatura_satis_listesi', ad:'Satış Faturaları', ad_en:'Sales Invoices', ic:'📄', dosya:'fatura_satis_listesi.html', tur:'liste',
      kart:'satis_faturasi', yol:'ListeFrame\\UFaturaListeDlg · FATBASLIK/FATSATIR (Satış)',
      arac:['e-Fatura Gönder','İrsaliyeye Dönüştür','Tahsilat','İade Faturası'],
      arama:[{l:'Belge No',t:'text'},{l:'Cari',t:'text'},{l:'Belge Türü',t:'combo',v:'(tümü)'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'satis_fis_listesi', ad:'Satış Fişleri', ad_en:'Sales Vouchers', ic:'🧾', dosya:'satis_fis_listesi.html', tur:'liste',
      kart:'satis_fis_karti', yol:'ListeFrame\\UFisListeDlg · FISBASLIK/FISSATIR (Satış)',
      arac:['Faturaya Dönüştür','İade Fişi','Z Raporu','Yeniden Yazdır'],
      arama:[{l:'Fiş No',t:'text'},{l:'Fiş Türü',t:'combo',v:'(tümü)'},{l:'Kasa / Şube',t:'combo',v:'(tümü)'},{l:'Ödeme Şekli',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'satis_tahakkuk_listesi', ad:'Satış Tahakkukları', ad_en:'Sales Accruals', ic:'📆', dosya:'satis_tahakkuk_listesi.html', tur:'liste',
      kart:'satis_tahakkuk_karti', yol:'ListeFrame\\UTahakkukListeDlg · TAHAKKUK (Gelir)',
      arac:['Toplu Faturala','Dönem Kapat','Muhasebeleştir'],
      arama:[{l:'Tahakkuk No',t:'text'},{l:'Gelir Türü',t:'combo',v:'(tümü)'},{l:'Müşteri',t:'text'},{l:'Dönem',t:'combo',v:'Ağustos 2026'},{l:'Faturalama',t:'combo',v:'(tümü)'}]},
    {id:'satis_konsinye_listesi', ad:'Satış Konsinyeleri', ad_en:'Sales Consignments', ic:'🏷️', dosya:'satis_konsinye_listesi.html', tur:'liste',
      kart:'satis_konsinye_karti', yol:'ListeFrame\\UKonsinyeListeDlg · KONSINYE/KONSINYESATIR (Satış)',
      arac:['Satılanı Faturala','İade Kabul','Bayi Sayımı Gir'],
      arama:[{l:'Konsinye No',t:'text'},{l:'Bayi / Müşteri',t:'text'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'İade Son Tarihi',t:'ikili',v:['01.01.2026','31.12.2026']}]},

    /* ---- DÖKÜM ---- */
    {id:'fiyat_sor', ad:'Fiyat Sor', ad_en:'Price Inquiry', ic:'🏷', dosya:'fiyat_sor.html', tur:'islem',
      yol:'UFiyatSor · TFiyatSorDlg · belge satırı girilirken açılan fiyat/bilgi ekranı'},
    {id:'satis_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=satis', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'alislar', ad:'Alış', ad_en:'Purchasing', ic:'🛒', bolumler:[
    {id:'alis_talep_listesi', ad:'Satınalma Talepleri', ad_en:'Purchase Requisitions', ic:'📝', dosya:'alis_talep_listesi.html', tur:'liste',
      kart:'alis_talep_karti', yol:'ListeFrame\\UTalepListeDlg · TALEPBASLIK/TALEPSATIR',
      arac:['Onaya Gönder','Siparişe Dönüştür','Teklif İste','Onayla','Reddet'],
      arama:[{l:'Talep No',t:'text'},{l:'Talep Eden',t:'text'},{l:'Departman',t:'combo',v:'(tümü)'},{l:'Onay Durumu',t:'combo',v:'(tümü)'},{l:'İhtiyaç Tarihi',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'alis_siparis_listesi', ad:'Verilen Siparişler', ad_en:'Purchase Orders', ic:'📤', dosya:'alis_siparis_listesi.html', tur:'liste',
      kart:'alis_siparis_karti', yol:'ListeFrame\\USiparisListeDlg · SIPBASLIK/SIPSATIR (Alış)',
      arac:['Teyitle','İrsaliyeye Dönüştür','Faturaya Dönüştür','Termin Güncelle','İptal'],
      arama:[{l:'Sipariş No',t:'text'},{l:'Tedarikçi',t:'text'},{l:'Sevk Durumu',t:'combo',v:'(tümü)'},{l:'Termin',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'alis_irsaliye_listesi', ad:'Alış İrsaliyeleri', ad_en:'Purchase Delivery Notes', ic:'🚚', dosya:'alis_irsaliye_listesi.html', tur:'liste',
      kart:'alis_irsaliye_karti', yol:'ListeFrame\\UIrsaliyeListeDlg · IRSBASLIK/IRSSATIR (Alış)',
      arac:['Faturaya Dönüştür','e-İrsaliye Yanıtı','Depo Girişi'],
      arama:[{l:'İrsaliye No',t:'text'},{l:'Tedarikçi',t:'text'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Fatura Durumu',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'fatura_alis_listesi', ad:'Alış Faturaları', ad_en:'Purchase Invoices', ic:'📥', dosya:'fatura_alis_listesi.html', tur:'liste',
      kart:'alis_faturasi', yol:'ListeFrame\\UFaturaListeDlg · FATBASLIK/FATSATIR (Alış)',
      arac:['e-Fatura Yanıtı','Ödeme Yap','Muhasebeleştir','İade Faturası'],
      arama:[{l:'Fatura No',t:'text'},{l:'Tedarikçi',t:'text'},{l:'VKN',t:'text'},{l:'Ödeme Durumu',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'alis_fis_listesi', ad:'Alış Fişleri', ad_en:'Purchase Vouchers', ic:'🧾', dosya:'alis_fis_listesi.html', tur:'liste',
      kart:'alis_fis_karti', yol:'ListeFrame\\UFisListeDlg · FISBASLIK/FISSATIR (Alış)',
      arac:['Faturaya Dönüştür','Kasaya İşle','Muhasebeleştir'],
      arama:[{l:'Fiş No',t:'text'},{l:'Fiş Türü',t:'combo',v:'(tümü)'},{l:'Cari',t:'text'},{l:'Ödeme Şekli',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'alis_tahakkuk_listesi', ad:'Alış Tahakkukları', ad_en:'Purchase Accruals', ic:'📑', dosya:'alis_tahakkuk_listesi.html', tur:'liste',
      kart:'alis_tahakkuk_karti', yol:'ListeFrame\\UTahakkukListeDlg · TAHAKKUK (Gider)',
      arac:['Faturayla Eşle','Dönem Kapat','Muhasebeleştir'],
      arama:[{l:'Tahakkuk No',t:'text'},{l:'Gider Türü',t:'combo',v:'(tümü)'},{l:'Cari',t:'text'},{l:'Dönem',t:'combo',v:'Ağustos 2026'},{l:'Durum',t:'combo',v:'(tümü)'}]},
    {id:'gider_pusulasi_listesi', ad:'Gider Pusulaları', ad_en:'Expense Vouchers', ic:'🧮', dosya:'gider_pusulasi_listesi.html', tur:'liste',
      kart:'gider_pusulasi_karti', yol:'ListeFrame\\UGiderPusulaListeDlg · GIDERPUSULA',
      arac:['e-Pusula Gönder','Ödeme Yap','Muhasebeleştir','Yazdır'],
      arama:[{l:'Pusula No',t:'text'},{l:'Ad Soyad',t:'text'},{l:'TC Kimlik',t:'text'},{l:'Stopaj Oranı',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'alis_konsinye_listesi', ad:'Alış Konsinyeleri', ad_en:'Purchase Consignments', ic:'📦', dosya:'alis_konsinye_listesi.html', tur:'liste',
      kart:'alis_konsinye_karti', yol:'ListeFrame\\UKonsinyeListeDlg · KONSINYE/KONSINYESATIR (Alış)',
      arac:['Satılanı Faturala','İade İrsaliyesi','Sayım Karşılaştır'],
      arama:[{l:'Konsinye No',t:'text'},{l:'Tedarikçi',t:'text'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'İade Son Tarihi',t:'ikili',v:['01.01.2026','31.12.2026']}]},

    /* ---- SATIŞ BELGELERİ ---- */
    {id:'alis_izlem', grup:'İzlem', grup_en:'Tracking', gic:'🔗', ad:'İzlem Girişi (Lot/SKT)', ad_en:'Tracking Entry (Lot / Expiry)', ic:'🏷', dosya:'alis_izlem_girisi.html', tur:'islem',
      yol:'IcerikFrame\\UIzlemGirisFrame · FATSATIR → STOKIZLEME'},
    {id:'izlem_gen', grup:'İzlem', grup_en:'Tracking', ad:'İzlem · GenGrid', ad_en:'Tracking · GenGrid', ic:'🅐', dosya:'alis_izlem_gen.html', tur:'islem',
      yol:'Karşılaştırma A · kendi grid sarmalayıcımız (GenGrid)'},
    {id:'izlem_ag', grup:'İzlem', grup_en:'Tracking', ad:'İzlem · AG Grid', ad_en:'Tracking · AG Grid', ic:'🅑', dosya:'alis_izlem_ag.html', tur:'islem',
      yol:'Karşılaştırma B · AG Grid Enterprise 36.1 (deneme lisansı)'},
    {id:'grid_krs', grup:'İzlem', grup_en:'Tracking', ad:'Grid Karşılaştırma', ad_en:'Grid Comparison', ic:'⚖', dosya:'grid_karsilastirma.html', tur:'ayar',
      yol:'Doküman · GenGrid ↔ AG Grid ölçümlü karşılaştırma (K5)'},
    {id:'alis_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=alis', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'banka', ad:'Banka', ad_en:'Bank', ic:'🏦', bolumler:[
    {id:'banka_hesabi', ad:'Banka Hesapları', ad_en:'Bank Accounts', ic:'🏛', dosya:'banka_hesaplari_listesi.html', tur:'liste',
      kart:'banka_hesabi', yol:'ListeFrame\\UBankaHesapListeDlg · BANKAHESAP · BANKAHAREKET · BANKA',
      arama:[{l:'Banka',t:'combo',v:'(tümü)'},{l:'Hesap No / IBAN',t:'text'},{l:'Para Birimi',t:'combo',v:'(tümü)'},{l:'Şube',t:'combo',v:'Merkez'}]},
    {id:'krediler_listesi', ad:'Krediler', ad_en:'Loans', ic:'📉', dosya:'krediler_listesi.html', tur:'liste',
      kart:null, yol:'ListeFrame\\UKrediListeDlg · KREDI',
      arac:['Ödeme Planı Oluştur','Taksit Öde','Erken Kapama','Yeniden Yapılandır','Teminat Ekle'],
      arama:[{l:'Kredi Adı',t:'text'},{l:'Kredi / Sözleşme No',t:'text'},{l:'Banka',t:'combo',v:'(tümü)'},{l:'Kredi Tipi',t:'combo',v:'(tümü)'},{l:'Para Birimi',t:'combo',v:'(tümü)'},{l:'Vade',t:'ikili',v:['01.08.2026','31.12.2027']}]},
    {id:'kredi_karti_listesi', ad:'Kredi Kartları', ad_en:'Credit Cards', ic:'💳', dosya:'kredi_karti_listesi.html', tur:'liste',
      kart:'kredi_karti', yol:'ListeFrame\\UKrediKartiListeDlg · KREDIKARTI',
      arac:['Ekstre Aktar','Ödeme Yap','Taksitlendir','Limit Güncelle'],
      arama:[{l:'Kart Adı',t:'text'},{l:'Banka',t:'combo',v:'(tümü)'},{l:'Kart No (son 4)',t:'text'},{l:'Zimmetli',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Aktif'}]},
    {id:'pos_listesi', ad:'POS Listesi', ad_en:'POS List', ic:'🖲', dosya:'pos_listesi.html', tur:'liste',
      kart:'pos_ekrani', yol:'ListeFrame\\UPosListeDlg · POS',
      arama:[{l:'POS Adı',t:'text'},{l:'Banka',t:'combo',v:'(tümü)'},{l:'Tip',t:'combo',v:'(tümü)'},{l:'Terminal No',t:'text'},{l:'Tarih',t:'ikili',v:['01.08.2026','14.08.2026']}]},
    {id:'cekler', ad:'Çekler', ad_en:'Cheques', ic:'🧾', dosya:'cek_senet_listesi.html', ek:'&tur=c', tur:'liste',
      kart:'cek_senet', yol:'ListeFrame\\UCekSenetListeDlg · CEKSENET (TUR=Ç) · Alınan/Verilen ekran içinde',
      arac:['Ciro Et','Tahsile Ver','Teminata Ver','Tahsil Et','Karşılıksız İşle','İade Et','Karşılık Ayır'],
      arama:[{l:'Çek No',t:'text'},{l:'Keşideci',t:'text'},{l:'Cari',t:'text'},{l:'Banka',t:'combo',v:'(tümü)'},{l:'Alınan/Verilen',t:'combo',v:'(tümü)'},{l:'Portföy Durumu',t:'combo',v:'(tümü)'},{l:'Vade',t:'ikili',v:['01.08.2026','31.12.2026']}]},
    {id:'senetler', ad:'Senetler', ad_en:'Promissory Notes', ic:'📜', dosya:'cek_senet_listesi.html', ek:'&tur=s', tur:'liste',
      kart:'cek_senet', yol:'ListeFrame\\UCekSenetListeDlg · CEKSENET (TUR=S) · Alınan/Verilen ekran içinde',
      arac:['Ciro Et','Tahsile Ver','Teminata Ver','Tahsil Et','Protesto İşle','Ödendi İşle'],
      arama:[{l:'Senet No',t:'text'},{l:'Borçlu / Lehtar',t:'text'},{l:'Cari',t:'text'},{l:'Alınan/Verilen',t:'combo',v:'(tümü)'},{l:'Portföy Durumu',t:'combo',v:'(tümü)'},{l:'Vade',t:'ikili',v:['01.08.2026','31.12.2026']}]},
    {id:'cekler_ver2', ad:'Çekler (Ver2 · deneme)', ad_en:'Cheques (v2 · trial)', ic:'🧪', dosya:'cek_senet_listesi_ver2.html', ek:'&tur=c', tur:'liste',
      kart:'cek_senet', yol:'Karşılaştırma tasarımı — Fluent komut şeridi · aynı veri, aynı aksiyon kataloğu',
      arac:['Aksiyon arama (Ctrl+K)','Bağlamsal seçim şeridi','Sağdan grid ayar paneli','Yoğunluk'],
      arama:[{l:'Çek No',t:'text'},{l:'Keşideci',t:'text'},{l:'Cari',t:'text'}]},
    {id:'cekler_ver3', ad:'Çekler (Ver3 · deneme)', ad_en:'Cheques (v3 · trial)', ic:'🧭', dosya:'cek_senet_listesi_ver3.html', ek:'&tur=c', tur:'liste',
      kart:'cek_senet', yol:'Karşılaştırma tasarımı — 4 satırlı sade yerleşim · komut butonu yalnızca 2. satırda',
      arac:['Yeni / Düzenle / Yazdır','Aksiyon combo + Uygula','Liste/Grup/Analiz/Grid','Durum ve yön süzgeçleri'],
      arama:[{l:'Çek No',t:'text'},{l:'Keşideci',t:'text'},{l:'Cari',t:'text'}]},
    {id:'banka_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=banka', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'stok', ad:'Stok', ad_en:'Inventory', ic:'📦', bolumler:[
    {id:'stok_listesi', ad:'Stok Listesi', ad_en:'Stock List', ic:'📦', dosya:'stok_listesi.html', tur:'liste',
      kart:'stok_karti', yol:'ListeFrame\\UStokListeDlg · STOKLAR',
      arac:['Barkod Yazdır','ÜTS','Reçete','Stok Durumu Güncelle','Excelden Veri Al'],
      arama:[{l:'Stok Adı',t:'text'},{l:'Kod / Ürün No',t:'text'},{l:'Barkod',t:'text'},{l:'Kategori',t:'combo',v:'(tümü)'},{l:'Marka',t:'combo',v:'(tümü)'},{l:'Depo',t:'combo',v:'(tümü)'}]},
    {id:'stok_talep', ad:'Stoktan Talepler', ad_en:'Stock Requests', ic:'📝', dosya:'stok_talep_listesi.html', tur:'liste',
      kart:'stok_talep_wizard', yol:'ListeFrame\\UTalepListeDlg · TALEP · TALEPDETAY',
      arac:['Onayla','Reddet','Karşıla (Çıkış Fişi)','Satın Almaya Aktar'],
      arama:[{l:'Talep No',t:'text'},{l:'Talep Eden',t:'combo',v:'(tümü)'},{l:'Departman',t:'combo',v:'(tümü)'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Bekleyen'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'stok_transfer', ad:'Transferler', ad_en:'Transfers', ic:'🔁', dosya:'stok_transfer_listesi.html', tur:'liste',
      kart:'stok_transfer_wizard', yol:'ListeFrame\\UTransferListeDlg · STOKFIS (TUR=Transfer)',
      arac:['Sevk Et','Teslim Al','İptal Et','İrsaliye Yazdır'],
      arama:[{l:'Fiş No',t:'text'},{l:'Çıkış Deposu',t:'combo',v:'(tümü)'},{l:'Giriş Deposu',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'stok_giris', ad:'Giriş Fişleri', ad_en:'Goods Receipts', ic:'📥', dosya:'stok_giris_listesi.html', tur:'liste',
      kart:'stok_giris_wizard', yol:'ListeFrame\\UStokFisListeDlg · STOKFIS (Giriş)',
      arac:['Faturaya Bağla','Seri / Lot Gir','Maliyet Güncelle','Yazdır'],
      arama:[{l:'Fiş No',t:'text'},{l:'Fiş Türü',t:'combo',v:'(tümü)'},{l:'Cari',t:'text'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'stok_cikis', ad:'Çıkış Fişleri', ad_en:'Goods Issues', ic:'📤', dosya:'stok_cikis_listesi.html', tur:'liste',
      kart:'stok_cikis_wizard', yol:'ListeFrame\\UStokFisListeDlg · STOKFIS (Çıkış)',
      arac:['Faturaya Bağla','Seri / Lot Seç','Sarf / Fire İşle','Yazdır'],
      arama:[{l:'Fiş No',t:'text'},{l:'Fiş Türü',t:'combo',v:'(tümü)'},{l:'Cari / Talep Eden',t:'text'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'uts_bildirim', ad:'ÜTS Bildirim', ad_en:'UTS Notification', ic:'📡', dosya:'uts_bildirim.html', tur:'liste',
      /* Ekranin kendi is akisi var: kayit "yeni/duzenle" ile degil belgeden uretilir,
         cikti ÜTS servisine gider. Yeni / Duzenle / Yazdir seridi anlamsiz — gizlenir.
         Butun islemler Aksiyon combosunda.                                             */
      komut:'yok',
      yol:'UTS\\UUTSDlg · TUTSDlg · UTSBILDIRIMMESAJ',
      arama:[{l:'Ürün No',t:'text'},{l:'Lot No',t:'text'},{l:'Seri No',t:'text'},
             {l:'Bildirim',t:'combo',v:'Alma Bildirimi'},{l:'Kurum No',t:'text'},
             {l:'Belge No',t:'text'},{l:'Durum',t:'combo',v:'(tümü)'},
             {l:'Tarih',t:'ikili',v:['01.08.2026','14.08.2026']}]},
    {id:'stok_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=stok', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'uretim', ad:'Üretim', ad_en:'Production', ic:'⚙️', bolumler:[
    {id:'recete_u', ad:'Reçete / Ürün Ağacı', ad_en:'Bill of Materials', ic:'⚗', dosya:'recete.html', tur:'liste',
      kart:null, yol:'IcerikFrame\\UReceteFrame', arac:['Maliyet Hesapla','Revizyon']},
    {id:'is_listesi_u', ad:'İş Emirleri', ad_en:'Work Orders', ic:'🏭', dosya:'is_listesi.html', tur:'liste',
      kart:'gorev_karti', yol:'ListeFrame\\UIsListeDlg (üretim)', arac:['Başlat','Tamamla','Fire Gir']},
    {id:'uretim_fisleri', ad:'Üretim Fişleri', ad_en:'Production Vouchers', ic:'🧾', dosya:null, tur:'liste',
      kart:null, yol:'ListeFrame\\UUretimFisListeDlg · URETIMFIS · URETIMFISDETAY',
      arac:['Sarf Çıkışı Yap','Mamul Girişi Yap','Fire / Zayi Gir','Maliyet Dağıt','İş Emrine Bağla'],
      arama:[{l:'Fiş No',t:'text'},{l:'İş Emri No',t:'text'},{l:'Mamul / Reçete',t:'text'},{l:'Depo',t:'combo',v:'(tümü)'},{l:'Vardiya',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'uretim_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=uretim', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'ik', ad:'İK', ad_en:'HR', ic:'🧑‍💼', bolumler:[
    {id:'ik_listesi', ad:'Personel Listesi', ad_en:'Employee List', ic:'🧑‍💼', dosya:'ik_listesi.html', tur:'liste',
      kart:'ik_karti', yol:'ListeFrame\\UPersonelListeDlg · PERSONEL · PERSONELIZIN · PUANTAJ · ZIMMET',
      arama:[{l:'Ad Soyad',t:'text'},{l:'Sicil No',t:'text'},{l:'T.C. Kimlik',t:'text'},
             {l:'Görev',t:'text'},{l:'Departman',t:'combo',v:'(tümü)'},{l:'Kadro',t:'combo',v:'(tümü)'},
             {l:'Şube',t:'combo',v:'Merkez'},{l:'Yönetici',t:'combo',v:'(tümü)'},
             {l:'Durum',t:'combo',v:'Çalışıyor'}]},
    {id:'ik_karti', ad:'Personel Kartları', ad_en:'Employee Records', ic:'🗂', dosya:'ik_karti.html', tur:'liste',
      kart:'ik_karti', yol:'IcerikFrame\\UPersonelFrame · PERSONEL',
      arac:['İzin Gir','Puantaj','Zimmet'],
      arama:[{l:'Ad Soyad',t:'text'},{l:'Departman',t:'combo',v:'(tümü)'},{l:'Görev',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Çalışıyor'}]},
    {id:'gorev_karti', ad:'Görev / Aktivite', ad_en:'Task / Activity', ic:'🗓', dosya:'gorev_karti.html', tur:'islem', yol:'GorevFrame\\UGorevFrame'},
    {id:'ik_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=ik', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'demirbas', ad:'Demirbaş', ad_en:'Fixed Assets', ic:'🖥️', bolumler:[
    {id:'demirbas_listesi', ad:'Demirbaş Listesi', ad_en:'Fixed Asset List', ic:'🖥', dosya:'demirbas_listesi.html', tur:'liste',
      kart:'demirbas_karti', yol:'ListeFrame\\UDemirbasListeDlg · DEMIRBAS',
      arac:['Zimmet Ver','Zimmet İade','Bakım Kaydı','Amortisman Hesapla','Etiket / Barkod'],
      arama:[{l:'Demirbaş Adı',t:'text'},{l:'Demirbaş No',t:'text'},{l:'Grup',t:'combo',v:'(tümü)'},{l:'Lokasyon',t:'combo',v:'(tümü)'},{l:'Zimmetli',t:'combo',v:'(tümü)'}]},
    {id:'dmb_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=demirbas', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'teklif', ad:'Teklif', ad_en:'Quotations', ic:'📄', bolumler:[
    {id:'teklif_listesi', ad:'Teklif Listesi', ad_en:'Quotation List', ic:'📑', dosya:'teklif_listesi.html', tur:'liste',
      kart:'teklif_karti', yol:'ListeFrame\\UTeklifListeDlg · TEKLIF',
      arac:['Revizyon Oluştur','Onaya Gönder','Siparişe Dönüştür','Faturaya Dönüştür','PDF Gönder'],
      arama:[{l:'Teklif No',t:'text'},{l:'Cari / Müşteri',t:'text'},{l:'Temsilci',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'teklif_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=teklif', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'servis', ad:'Servis', ad_en:'Service', ic:'🔧', bolumler:[
    {id:'servis_listesi', ad:'Servis Fişleri', ad_en:'Service Tickets', ic:'🔧', dosya:'servis_listesi.html', tur:'liste',
      kart:'servis_karti', yol:'ListeFrame\\UServisListeDlg · SERVIS',
      arac:['Teknisyen Ata','Parça Ekle','Teslim Et','Faturalandır','SLA Takibi'],
      arama:[{l:'Fiş No',t:'text'},{l:'Cari / Müşteri',t:'text'},{l:'Cihaz / Seri No',t:'text'},{l:'Teknisyen',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Açık'}]},
    {id:'servis_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=servis', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'dokuman', ad:'Doküman', ad_en:'Documents', ic:'🗂️', bolumler:[
    {id:'dokuman_listesi', ad:'Doküman Listesi', ad_en:'Document List', ic:'🗂', dosya:'dokuman_listesi.html', tur:'liste',
      kart:'dokuman_karti', yol:'EvrakTakip\\UDokumanListeDlg · DOKUMAN',
      arac:['Tarayıcıdan Al','Klasörden Ekle','Sürüm Ekle','Paylaş'],
      arama:[{l:'Doküman Adı',t:'text'},{l:'Klasör',t:'combo',v:'(tümü)'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Ekleyen',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'dok_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=dokuman', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'kalite', ad:'Kalite', ad_en:'Quality', ic:'✅', bolumler:[
    {id:'kalite_sapma', ad:'Sapma / Olay', ad_en:'Deviation / Incident', ic:'⚠', dosya:'kalite_sapma_listesi.html', tur:'liste',
      kart:'kalite_sapma_karti', yol:'Kalite\\USapmaListeDlg · KALSAPMA · KALSAPMADETAY',
      arac:['Kök Neden Analizi','DÖF Aç','Sınıflandır','Kapat'],
      arama:[{l:'Sapma No',t:'text'},{l:'Kaynak',t:'combo',v:'(tümü)'},{l:'Süreç',t:'combo',v:'(tümü)'},{l:'Önem',t:'combo',v:'(tümü)'},{l:'Sorumlu',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Açık'},{l:'Tarih',t:'ikili',v:['01.01.2026','14.08.2026']}]},
    {id:'kalite_dof', ad:'DÖF', ad_en:'CAPA', ic:'🛠', dosya:'kalite_dof_listesi.html', tur:'liste',
      kart:'kalite_dof_karti', yol:'Kalite\\UDofListeDlg · KALDOF (Düzeltici/Önleyici Faaliyet)',
      arac:['Aksiyon Ekle','Sorumlu Ata','Termin Ver','Etkinlik Kontrolü','Kapat'],
      arama:[{l:'DÖF No',t:'text'},{l:'Tür',t:'combo',v:'Düzeltici'},{l:'Kaynak Sapma',t:'text'},{l:'Sorumlu',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'Açık'},{l:'Termin',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'kalite_denetim', ad:'Denetim', ad_en:'Audits', ic:'🔍', dosya:'kalite_denetim_listesi.html', tur:'liste',
      kart:'kalite_denetim_karti', yol:'Kalite\\UDenetimListeDlg · KALDENETIM · KALDENETIMBULGU',
      arac:['Denetim Planla','Soru Listesi','Bulgu Gir','Rapor Üret','Kapat'],
      arama:[{l:'Denetim No',t:'text'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Standart',t:'combo',v:'ISO 9001'},{l:'Denetçi',t:'combo',v:'(tümü)'},{l:'Bölüm',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'kalite_egitim', ad:'Eğitim', ad_en:'Training', ic:'🎓', dosya:'kalite_egitim_listesi.html', tur:'liste',
      kart:'kalite_egitim_karti', yol:'Kalite\\UEgitimListeDlg · KALEGITIM · KALEGITIMKATILIMCI',
      arac:['Katılımcı Ekle','Yoklama Al','Etkinlik Değerlendir','Sertifika Yazdır'],
      arama:[{l:'Eğitim Adı',t:'text'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Eğitmen',t:'text'},{l:'Departman',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'kalite_toplanti', ad:'Toplantı', ad_en:'Meetings', ic:'🗓', dosya:'kalite_toplanti_listesi.html', tur:'liste',
      kart:'kalite_toplanti_karti', yol:'Kalite\\UToplantiListeDlg · KALTOPLANTI · KALTOPLANTIKARAR',
      arac:['Gündem Oluştur','Katılımcı Çağır','Karar Ekle','Göreve Dönüştür','Tutanak Yazdır'],
      arama:[{l:'Toplantı Konusu',t:'text'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Başkan',t:'combo',v:'(tümü)'},{l:'Bölüm',t:'combo',v:'(tümü)'},{l:'Durum',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['01.01.2026','31.12.2026']}]},
    {id:'kalite_dokum', ad:'Dökümler', ad_en:'Reports', ic:'🖨️', dosya:'dokumler.html', ek:'&mod=dokuman', tur:'dokum', yol:'DokumFrame\\UDokumListeFrame · GENDOKUM'}
  ]},

  {id:'yonetim', ad:'Yönetim', ad_en:'Administration', ic:'🛠', bolumler:[
    {id:'firma_bilgileri', grup:'Tanımlar', grup_en:'Definitions', gic:'📚', ad:'Firma Bilgileri', ad_en:'Company Details', ic:'🏢', dosya:'firma_bilgileri.html', tur:'ayar',
      yol:'Ortak\\UFirmaBilgileriFrame · FIRMA · SUBE'},
    {id:'kullanici_ayarlari', grup:'Tanımlar', grup_en:'Definitions', ad:'Kullanıcı Ayarları', ad_en:'User Settings', ic:'👤', dosya:'kullanici_yetki.html', tur:'ayar',
      yol:'UKullaniciYetki · TKullaniciYetkiDlg · ROLLER · YETKI · YETKIEK · REHBER'},
    {id:'hesap_plani', grup:'Tanımlar', grup_en:'Definitions', ad:'Hesap Planı', ad_en:'Chart of Accounts', ic:'📊', dosya:'hesap_plani.html', tur:'liste',
      kart:null, yol:'Muhasebe\\UHesapPlaniFrame · HESAPPLANI',
      arac:['Yeni Hesap','Alt Hesap Ekle','Kopyala','e-Defter Kontrol','Plan Yazdır'],
      arama:[{l:'Hesap Kodu',t:'text'},{l:'Hesap Adı',t:'text'},{l:'Seviye',t:'combo',v:'(tümü)'},{l:'Tip',t:'combo',v:'(tümü)'}]},
    {id:'banka_bilgileri', grup:'Tanımlar', grup_en:'Definitions', ad:'Banka Bilgileri', ad_en:'Bank Details', ic:'🏦', dosya:'banka_bilgileri.html', tur:'liste',
      kart:null, yol:'Ortak\\UBankaTanimFrame · BANKA · BANKASUBE · BANKAHESAP',
      arac:['Yeni Banka','Şube Ekle','Hesap Ekle','IBAN Doğrula','Muhasebe Eşle'],
      arama:[{l:'Banka Adı',t:'text'},{l:'Banka Kodu',t:'text'},{l:'IBAN',t:'text'},{l:'Hesap Türü',t:'combo',v:'(tümü)'}]},

    {id:'doviz_bilgileri', grup:'Tanımlar', grup_en:'Definitions', ad:'Döviz Değerleri', ad_en:'Exchange Rates', ic:'💱', dosya:'doviz_bilgileri.html', tur:'liste',
      kart:null, yol:'Ortak\\UDovizFrame · DOVIZ · DOVIZKUR',
      arac:['Yeni Döviz','Kur Gir','TCMB’den Çek','Toplu Kur Aktar'],
      arama:[{l:'Döviz Kodu',t:'text'},{l:'Kaynak',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['05.08.2026','14.08.2026']}]},
    {id:'ops_genel', grup:'Opsiyonlar', grup_en:'Options', gic:'🎛', ad:'Genel', ad_en:'General', ic:'⚙', dosya:'genel_opsiyonlar.html', tur:'ayar',
      yol:'Ortak\\UGenelOpsiyon · GENINI (MODUL=GENEL)'},
    {id:'ops_crm', grup:'Opsiyonlar', grup_en:'Options', ad:'CRM', ad_en:'CRM', ic:'🤝', dosya:'modul_opsiyonlari.html', ek:'&mod=crm', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=CRM)'},
    {id:'ops_cari', grup:'Opsiyonlar', grup_en:'Options', ad:'Cari', ad_en:'Accounts', ic:'🧾', dosya:'modul_opsiyonlari.html', ek:'&mod=cari', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=CARI)'},
    {id:'ops_kasa', grup:'Opsiyonlar', grup_en:'Options', ad:'Kasa', ad_en:'Cash', ic:'💰', dosya:'modul_opsiyonlari.html', ek:'&mod=kasa', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=KASA)'},
    {id:'ops_alissatis', grup:'Opsiyonlar', grup_en:'Options', ad:'Alış/Satış', ad_en:'Purchasing / Sales', ic:'🛒', dosya:'modul_opsiyonlari.html', ek:'&mod=alissatis', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=ALISSATIS)'},
    {id:'ops_banka', grup:'Opsiyonlar', grup_en:'Options', ad:'Banka', ad_en:'Bank', ic:'🏦', dosya:'modul_opsiyonlari.html', ek:'&mod=banka', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=BANKA)'},
    {id:'ops_stok', grup:'Opsiyonlar', grup_en:'Options', ad:'Stok', ad_en:'Inventory', ic:'📦', dosya:'modul_opsiyonlari.html', ek:'&mod=stok', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=STOK)'},
    {id:'ops_uretim', grup:'Opsiyonlar', grup_en:'Options', ad:'Üretim', ad_en:'Production', ic:'🏭', dosya:'modul_opsiyonlari.html', ek:'&mod=uretim', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=URETIM)'},
    {id:'ops_ik', grup:'Opsiyonlar', grup_en:'Options', ad:'İK', ad_en:'HR', ic:'👥', dosya:'modul_opsiyonlari.html', ek:'&mod=ik', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=IK)'},
    {id:'ops_demirbas', grup:'Opsiyonlar', grup_en:'Options', ad:'Demirbaş', ad_en:'Fixed Assets', ic:'🖥', dosya:'modul_opsiyonlari.html', ek:'&mod=demirbas', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=DEMIRBAS)'},
    {id:'ops_servis', grup:'Opsiyonlar', grup_en:'Options', ad:'Servis', ad_en:'Service', ic:'🔧', dosya:'modul_opsiyonlari.html', ek:'&mod=servis', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=SERVIS)'},
    {id:'ops_dokuman', grup:'Opsiyonlar', grup_en:'Options', ad:'Doküman', ad_en:'Documents', ic:'📁', dosya:'belge_opsiyonlari.html', tur:'ayar',
      yol:'Ortak\\UOpsiyonFatura · GENINI (MODUL=DOKUMAN/BELGE)'},
    {id:'ops_kalite', grup:'Opsiyonlar', grup_en:'Options', ad:'Kalite', ad_en:'Quality', ic:'✅', dosya:'modul_opsiyonlari.html', ek:'&mod=kalite', tur:'ayar',
      yol:'Ortak\\UOpsiyonFrame · GENINI (MODUL=KALITE)'},
    {id:'yedekleme', grup:'Sistem', grup_en:'System', gic:'🖥', ad:'Yedekleme', ad_en:'Backup', ic:'💾', dosya:'yedekleme.html', tur:'liste',
      kart:null, yol:'Yedek\\UYedeklemeFrame · YEDEKPLAN · YEDEKLOG',
      arac:['Şimdi Yedekle','Geri Yükle','Doğrula','Plan Düzenle'],
      arama:[{l:'Dosya Adı',t:'text'},{l:'Tür',t:'combo',v:'(tümü)'},{l:'Konum',t:'combo',v:'(tümü)'},{l:'Tarih',t:'ikili',v:['08.08.2026','14.08.2026']}]},
    {id:'log_info', grup:'Sistem', grup_en:'System', ad:'Log Info', ad_en:'Log Info', ic:'📜', dosya:'log_info.html', tur:'liste',
      kart:null, yol:'Log\\ULogFrame · GENLOG · GENLOGDETAY · AILOG',
      arac:['Yenile','Excel’e Aktar','Filtre Kaydet','Canlı İzleme'],
      arama:[{l:'Kullanıcı',t:'combo',v:'(tümü)'},{l:'Modül',t:'combo',v:'(tümü)'},{l:'İşlem',t:'combo',v:'(tümü)'},{l:'Önem',t:'combo',v:'(tümü)'},{l:'Zaman',t:'ikili',v:['13.08.2026','14.08.2026']}]}

  ]}

];

/* kart ekranlari (Yeni ile modal olarak acilir) */
var KARTLAR = {
  cari_karti:     {ad:'Cari Kartı',        dosya:'cari_karti.html',     yol:'IcerikFrame\\UCariFrame · CARI'},
  musteri_karti:  {ad:'Müşteri Kartı',     dosya:'musteri_karti.html',  yol:'IcerikFrame\\UCariFrame · CARI (120.x) · İlgili kişiler KISI tablosundan'},
  tedarikci_karti:{ad:'Tedarikçi Kartı',   dosya:'tedarikci_karti.html',yol:'IcerikFrame\\UCariFrame · CARI (320.x) · İlgili kişiler KISI tablosundan'},
  kisi_karti:     {ad:'Kişi Kartı',         dosya:'kisi_karti.html',     yol:'IcerikFrame\\UKisiFrame · KISI (Contact)'},
  stok_karti:     {ad:'Stok Kartı',        dosya:'stok_karti.html',     yol:'IcerikFrame\\UStokFrame · STOKLAR'},
  demirbas_karti: {ad:'Demirbaş Kartı',    dosya:'demirbas_karti.html', yol:'IcerikFrame\\UDemirbasFrame'},
  servis_karti:   {ad:'Servis Kartı',      dosya:'servis_karti.html',   yol:'IcerikFrame\\UServisFrame'},
  teklif_karti:   {ad:'Teklif Kartı',      dosya:'teklif_karti.html',   yol:'IcerikFrame\\UTeklifFrame'},
  firsat_karti:   {ad:'Fırsat Kartı',      dosya:'firsat_karti.html',   yol:'Social\\UFirsatFrame · FIRSAT'},
  gorev_karti:    {ad:'Görev Kartı',       dosya:'gorev_karti.html',    yol:'GorevFrame\\UGorevFrame'},
  proje_karti:    {ad:'Proje Kartı',       dosya:'proje_karti.html',    yol:'IcerikFrame\\UProjeFrame'},
  ik_karti:       {ad:'Personel Kartı',    dosya:'ik_karti.html',       yol:'IcerikFrame\\UPersonelFrame'},
  dokuman_karti:  {ad:'Doküman Kartı',     dosya:'dokuman_karti.html',  yol:'EvrakTakip\\UDokumanFrame'},
  cek_senet:      {ad:'Çek / Senet Kartı', dosya:'cek_senet.html',      yol:'IcerikFrame\\UCekSenetFrame'},
  kredi_karti:    {ad:'Kredi Kartı',       dosya:'kredi_karti.html',    yol:'IcerikFrame\\UKrediKartiFrame'},
  banka_hesabi:   {ad:'Kasa / Banka Hesabı',dosya:'banka_hesabi.html',  yol:'IcerikFrame\\UBankaHesapFrame'},
  pos_ekrani:     {ad:'POS Satış Ekranı',  dosya:'pos_ekrani.html',     yol:'Rest\\UPosEkrani'},
  stok_talep_wizard:    {ad:'Stok Talep Sihirbazı',     dosya:'stok_talep_wizard.html',    yol:'Stok\\UTalepWizard (JvWizard)'},
  stok_transfer_wizard: {ad:'Transfer Sihirbazı',        dosya:'stok_transfer_wizard.html', yol:'Stok\\UTransferWizard (JvWizard)'},
  stok_giris_wizard:    {ad:'Giriş Fişi Sihirbazı',      dosya:'stok_giris_wizard.html',    yol:'Stok\\UStokGirisWizard (JvWizard)'},
  stok_cikis_wizard:    {ad:'Çıkış Fişi Sihirbazı',      dosya:'stok_cikis_wizard.html',    yol:'Stok\\UStokCikisWizard (JvWizard)'},
  kalite_sapma_karti:   {ad:'Sapma / Olay Kartı', dosya:'kalite_sapma_karti.html',   yol:'Kalite\\USapmaFrame · KALSAPMA'},
  kalite_dof_karti:     {ad:'DÖF Kartı',          dosya:'kalite_dof_karti.html',     yol:'Kalite\\UDofFrame · KALDOF'},
  kalite_denetim_karti: {ad:'Denetim Kartı',      dosya:'kalite_denetim_karti.html', yol:'Kalite\\UDenetimFrame · KALDENETIM'},
  kalite_egitim_karti:  {ad:'Eğitim Kartı',       dosya:'kalite_egitim_karti.html',  yol:'Kalite\\UEgitimFrame · KALEGITIM'},
  kalite_toplanti_karti:{ad:'Toplantı Kartı',     dosya:'kalite_toplanti_karti.html',yol:'Kalite\\UToplantiFrame · KALTOPLANTI'},
  satis_faturasi: {ad:'Satış Faturası',    dosya:'satis_faturasi.html', yol:'IcerikFrame\\UFaturaFrame'},
  alis_talep_karti:      {ad:'Satınalma Talebi',       dosya:'alis_talep_karti.html',      yol:'IcerikFrame\\UTalepFrame · TALEPBASLIK'},
  alis_siparis_karti:    {ad:'Verilen Sipariş',        dosya:'alis_siparis_karti.html',    yol:'IcerikFrame\\USiparisFrame (Alış)'},
  alis_irsaliye_karti:   {ad:'Alış İrsaliyesi',        dosya:'alis_irsaliye_karti.html',   yol:'IcerikFrame\\UIrsaliyeFrame (Alış)'},
  alis_fis_karti:        {ad:'Alış Fişi',              dosya:'alis_fis_karti.html',        yol:'IcerikFrame\\UFisFrame (Alış)'},
  alis_tahakkuk_karti:   {ad:'Alış Tahakkuku',         dosya:'alis_tahakkuk_karti.html',   yol:'IcerikFrame\\UTahakkukFrame (Gider)'},
  gider_pusulasi_karti:  {ad:'Gider Pusulası',         dosya:'gider_pusulasi_karti.html',  yol:'IcerikFrame\\UGiderPusulaFrame'},
  alis_konsinye_karti:   {ad:'Alış Konsinye Belgesi',  dosya:'alis_konsinye_karti.html',   yol:'IcerikFrame\\UKonsinyeFrame (Alış)'},
  satis_siparis_karti:   {ad:'Alınan Sipariş',         dosya:'satis_siparis_karti.html',   yol:'IcerikFrame\\USiparisFrame (Satış)'},
  satis_irsaliye_karti:  {ad:'Satış İrsaliyesi',       dosya:'satis_irsaliye_karti.html',  yol:'IcerikFrame\\UIrsaliyeFrame (Satış)'},
  satis_fis_karti:       {ad:'Satış Fişi',             dosya:'satis_fis_karti.html',       yol:'IcerikFrame\\UFisFrame (Satış)'},
  satis_tahakkuk_karti:  {ad:'Satış Tahakkuku',        dosya:'satis_tahakkuk_karti.html',  yol:'IcerikFrame\\UTahakkukFrame (Gelir)'},
  satis_konsinye_karti:  {ad:'Satış Konsinye Belgesi', dosya:'satis_konsinye_karti.html',  yol:'IcerikFrame\\UKonsinyeFrame (Satış)'},
  alis_faturasi:  {ad:'Alış Faturası',     dosya:'alis_faturasi.html',  yol:'IcerikFrame\\UFaturaFrame'}
};

var HIZLI = [['stok','stok_listesi'],['cari','musteriler'],['satislar','fatura_satis_listesi'],
             ['teklif','teklif_listesi'],['crm','firsat_listesi'],['servis','servis_listesi'],
             ['banka','cekler'],['kasa','kasa_listesi'],['banka','pos_listesi'],
             ['banka','kredi_karti_listesi'],['banka','krediler_listesi'],['demirbas','demirbas_listesi']];
