object BankaGorevFrame: TBankaGorevFrame
  Left = 0
  Top = 0
  Width = 568
  Height = 388
  Align = alClient
  Color = clWhite
  Font.Charset = TURKISH_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Trebuchet MS'
  Font.Style = []
  ParentBackground = False
  ParentColor = False
  ParentFont = False
  TabOrder = 0
  object btnBankaTanimlari: TcxButton
    Tag = 11
    Left = 0
    Top = 0
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'Banka Tan'#305'mlar'#305
    Colors.Default = 10252717
    Colors.Hot = 12158835
    Colors.Pressed = 7814707
    LookAndFeel.Kind = lfOffice11
    LookAndFeel.NativeStyle = False
    OptionsImage.ImageIndex = 0
    OptionsImage.Images = Tablo.PngImageListTicari
    OptionsImage.Margin = 8
    SpeedButtonOptions.GroupIndex = 1
    TabOrder = 3
    Font.Charset = TURKISH_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = btnBankaTanimlariClick
  end
  object btnBankaKredileri: TcxButton
    Tag = 11
    Left = 0
    Top = 208
    Width = 568
    Height = 53
    Align = alTop
    Caption = 'Banka Aksiyonlar'#305
    Colors.Default = 10252717
    Colors.Hot = 12158835
    Colors.Pressed = 7814707
    LookAndFeel.Kind = lfOffice11
    LookAndFeel.NativeStyle = False
    OptionsImage.ImageIndex = 2
    OptionsImage.Images = Tablo.PngImageListTicari
    OptionsImage.Margin = 8
    SpeedButtonOptions.GroupIndex = 1
    TabOrder = 4
    Font.Charset = TURKISH_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = btnBankaKredileriClick
  end
  object BtnKrediler: TcxButton
    Tag = 11
    Left = 0
    Top = 52
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'Krediler'
    Colors.Default = 10252717
    Colors.Hot = 12158835
    Colors.Pressed = 7814707
    LookAndFeel.Kind = lfOffice11
    LookAndFeel.NativeStyle = False
    OptionsImage.ImageIndex = 5
    OptionsImage.Images = Tablo.PngImageListTicari
    OptionsImage.Margin = 8
    SpeedButtonOptions.GroupIndex = 1
    TabOrder = 5
    Font.Charset = TURKISH_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = BtnKredilerClick
  end
  object PanelCek: TPanel
    Left = 0
    Top = 104
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'PanelCek'
    TabOrder = 0
    object btnVerilenCek: TcxButton
      Tag = 103
      Left = 99
      Top = 1
      Width = 468
      Height = 50
      Align = alClient
      Caption = 'Verilen '#199'ek'
      Colors.Default = 10252717
      Colors.Hot = 12158835
      Colors.Pressed = 7814707
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      OptionsImage.ImageIndex = 6
      OptionsImage.Images = Tablo.PngImageListTicari
      OptionsImage.Margin = 8
      SpeedButtonOptions.GroupIndex = 1
      TabOrder = 0
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      OnClick = btnAlinanCekClick
    end
    object btnAlinanCek: TcxButton
      Tag = 101
      Left = 1
      Top = 1
      Width = 98
      Height = 50
      Align = alLeft
      Caption = 'Al'#305'nan '#199'ek'
      Colors.Default = 10252717
      Colors.Hot = 12158835
      Colors.Pressed = 7814707
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      OptionsImage.ImageIndex = 6
      OptionsImage.Images = Tablo.PngImageListTicari
      OptionsImage.Margin = 8
      SpeedButtonOptions.GroupIndex = 1
      TabOrder = 1
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      OnClick = btnAlinanCekClick
    end
  end
  object PanelSenet: TPanel
    Left = 0
    Top = 156
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'Panel1'
    TabOrder = 1
    object btnVerilenSenet: TcxButton
      Tag = 321
      Left = 99
      Top = 1
      Width = 468
      Height = 50
      Align = alClient
      Caption = 'Verilen Senet'
      Colors.Default = 10252717
      Colors.Hot = 12158835
      Colors.Pressed = 7814707
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      OptionsImage.ImageIndex = 6
      OptionsImage.Images = Tablo.PngImageListTicari
      OptionsImage.Margin = 8
      SpeedButtonOptions.GroupIndex = 1
      TabOrder = 0
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      OnClick = btnAlinanCekClick
    end
    object btnAlinanSenet: TcxButton
      Tag = 121
      Left = 1
      Top = 1
      Width = 98
      Height = 50
      Align = alLeft
      Caption = 'Al'#305'nan Senet'
      Colors.Default = 10252717
      Colors.Hot = 12158835
      Colors.Pressed = 7814707
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      OptionsImage.ImageIndex = 6
      OptionsImage.Images = Tablo.PngImageListTicari
      OptionsImage.Margin = 8
      SpeedButtonOptions.GroupIndex = 1
      TabOrder = 1
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      OnClick = btnAlinanCekClick
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 261
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'Panel1'
    TabOrder = 2
    object JvNavPanelButton2: TcxButton
      Left = 517
      Top = 1
      Width = 50
      Height = 50
      Align = alRight
      Caption = #214'zel'
      Colors.Default = 10252717
      Colors.Hot = 12158835
      Colors.Pressed = 7814707
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      OptionsImage.Margin = 8
      SpeedButtonOptions.GroupIndex = 1
      TabOrder = 0
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      OnClick = btnUpAndDown
      OnMouseDown = btnDokumlerMouseDown
    end
    object btnDokumler: TcxButton
      Tag = 1
      Left = 1
      Top = 1
      Width = 516
      Height = 50
      Align = alClient
      Caption = 'D'#246'k'#252'mler'
      Colors.Default = 10252717
      Colors.Hot = 12158835
      Colors.Pressed = 7814707
      LookAndFeel.Kind = lfOffice11
      LookAndFeel.NativeStyle = False
      OptionsImage.ImageIndex = 4
      OptionsImage.Images = Tablo.PngImageListTicari
      OptionsImage.Margin = 8
      SpeedButtonOptions.GroupIndex = 1
      TabOrder = 1
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      OnClick = btnUpAndDown
      OnMouseDown = btnDokumlerMouseDown
    end
  end
end
