object BankaGorevFrame: TBankaGorevFrame
  Left = 0
  Top = 0
  Width = 568
  Height = 388
  Align = alClient
  Color = clWhite
  Font.Charset = TURKISH_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Trebuchet MS'
  Font.Style = []
  ParentBackground = False
  ParentColor = False
  ParentFont = False
  TabOrder = 0
  ExplicitWidth = 451
  ExplicitHeight = 304
  object btnBankaTanimlari: TJvNavPanelButton
    Tag = 11
    Left = 0
    Top = 0
    Width = 568
    Height = 52
    Align = alTop
    AllowAllUp = True
    Caption = 'Banka Tan'#305'mlar'#305
    Font.Charset = TURKISH_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    GroupIndex = 1
    HotTrack = False
    HotTrackFont.Charset = TURKISH_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -13
    HotTrackFont.Name = 'Trebuchet MS'
    HotTrackFont.Style = [fsBold]
    ParentFont = False
    Colors.ButtonColorFrom = 15395562
    Colors.ButtonColorTo = 12566463
    Colors.ButtonHotColorFrom = 11633796
    Colors.ButtonHotColorTo = 9530476
    Colors.ButtonSelectedColorFrom = 11633796
    Colors.ButtonSelectedColorTo = 9530476
    ParentStyleManager = False
    ImageIndex = 0
    Images = Tablo.PngImageListTicari
    OnClick = btnBankaTanimlariClick
    ExplicitTop = -6
    ExplicitWidth = 343
  end
  object btnBankaKredileri: TJvNavPanelButton
    Tag = 11
    Left = 0
    Top = 208
    Width = 568
    Height = 53
    Align = alTop
    AllowAllUp = True
    Caption = 'Banka Aksiyonlar'#305
    Font.Charset = TURKISH_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    GroupIndex = 1
    HotTrack = False
    HotTrackFont.Charset = TURKISH_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -13
    HotTrackFont.Name = 'Trebuchet MS'
    HotTrackFont.Style = [fsBold]
    ParentFont = False
    Colors.ButtonColorFrom = 15395562
    Colors.ButtonColorTo = 12566463
    Colors.ButtonHotColorFrom = 11633796
    Colors.ButtonHotColorTo = 9530476
    Colors.ButtonSelectedColorFrom = 11633796
    Colors.ButtonSelectedColorTo = 9530476
    ParentStyleManager = False
    ImageIndex = 2
    Images = Tablo.PngImageListTicari
    OnClick = btnBankaKredileriClick
    ExplicitWidth = 870
  end
  object BtnKrediler: TJvNavPanelButton
    Tag = 11
    Left = 0
    Top = 52
    Width = 568
    Height = 52
    Align = alTop
    AllowAllUp = True
    Caption = 'Krediler'
    Font.Charset = TURKISH_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    GroupIndex = 1
    HotTrack = False
    HotTrackFont.Charset = TURKISH_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -13
    HotTrackFont.Name = 'Trebuchet MS'
    HotTrackFont.Style = [fsBold]
    ParentFont = False
    Colors.ButtonColorFrom = 15395562
    Colors.ButtonColorTo = 12566463
    Colors.ButtonHotColorFrom = 11633796
    Colors.ButtonHotColorTo = 9530476
    Colors.ButtonSelectedColorFrom = 11633796
    Colors.ButtonSelectedColorTo = 9530476
    ParentStyleManager = False
    ImageIndex = 5
    Images = Tablo.PngImageListTicari
    OnClick = BtnKredilerClick
    ExplicitLeft = -6
    ExplicitTop = 150
    ExplicitWidth = 377
  end
  object PanelCek: TPanel
    Left = 0
    Top = 104
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'PanelCek'
    TabOrder = 0
    ExplicitWidth = 451
    object btnVerilenCek: TJvNavPanelButton
      Tag = 103
      Left = 99
      Top = 1
      Width = 468
      Height = 50
      Align = alClient
      AllowAllUp = True
      Caption = 'Verilen '#199'ek'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 11633796
      Colors.ButtonHotColorTo = 9530476
      Colors.ButtonSelectedColorFrom = 11633796
      Colors.ButtonSelectedColorTo = 9530476
      ParentStyleManager = False
      ImageIndex = 6
      Images = Tablo.PngImageListTicari
      OnClick = btnAlinanCekClick
      ExplicitLeft = 105
      ExplicitTop = -3
      ExplicitWidth = 351
    end
    object btnAlinanCek: TJvNavPanelButton
      Tag = 101
      Left = 1
      Top = 1
      Width = 98
      Height = 50
      Align = alLeft
      AllowAllUp = True
      Caption = 'Al'#305'nan '#199'ek'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 11633796
      Colors.ButtonHotColorTo = 9530476
      Colors.ButtonSelectedColorFrom = 11633796
      Colors.ButtonSelectedColorTo = 9530476
      ParentStyleManager = False
      ImageIndex = 6
      Images = Tablo.PngImageListTicari
      OnClick = btnAlinanCekClick
      ExplicitLeft = -5
      ExplicitTop = -3
    end
  end
  object PanelSenet: TPanel
    Left = 0
    Top = 156
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'Panel1'
    TabOrder = 1
    ExplicitWidth = 451
    object btnVerilenSenet: TJvNavPanelButton
      Tag = 321
      Left = 99
      Top = 1
      Width = 468
      Height = 50
      Align = alClient
      AllowAllUp = True
      Caption = 'Verilen Senet'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 11633796
      Colors.ButtonHotColorTo = 9530476
      Colors.ButtonSelectedColorFrom = 11633796
      Colors.ButtonSelectedColorTo = 9530476
      ParentStyleManager = False
      ImageIndex = 6
      Images = Tablo.PngImageListTicari
      OnClick = btnAlinanCekClick
      ExplicitLeft = 111
      ExplicitWidth = 419
    end
    object btnAlinanSenet: TJvNavPanelButton
      Tag = 121
      Left = 1
      Top = 1
      Width = 98
      Height = 50
      Align = alLeft
      AllowAllUp = True
      Caption = 'Al'#305'nan Senet'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 11633796
      Colors.ButtonHotColorTo = 9530476
      Colors.ButtonSelectedColorFrom = 11633796
      Colors.ButtonSelectedColorTo = 9530476
      ParentStyleManager = False
      ImageIndex = 6
      Images = Tablo.PngImageListTicari
      OnClick = btnAlinanCekClick
      ExplicitLeft = -5
      ExplicitTop = 5
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 261
    Width = 568
    Height = 52
    Align = alTop
    Caption = 'Panel1'
    TabOrder = 2
    ExplicitWidth = 451
    object JvNavPanelButton2: TJvNavPanelButton
      Left = 517
      Top = 1
      Width = 50
      Height = 50
      Align = alRight
      AllowAllUp = True
      Caption = #214'zel'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 11633796
      Colors.ButtonHotColorTo = 9530476
      Colors.ButtonSelectedColorFrom = 11633796
      Colors.ButtonSelectedColorTo = 9530476
      ParentStyleManager = False
      ImageIndex = -1
      OnClick = btnUpAndDown
      OnMouseDown = btnDokumlerMouseDown
      ExplicitLeft = 298
      ExplicitTop = 6
    end
    object btnDokumler: TJvNavPanelButton
      Tag = 1
      Left = 1
      Top = 1
      Width = 516
      Height = 50
      Align = alClient
      AllowAllUp = True
      Caption = 'D'#246'k'#252'mler'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 11633796
      Colors.ButtonHotColorTo = 9530476
      Colors.ButtonSelectedColorFrom = 11633796
      Colors.ButtonSelectedColorTo = 9530476
      ParentStyleManager = False
      ImageIndex = 4
      Images = Tablo.PngImageListTicari
      OnClick = btnUpAndDown
      OnMouseDown = btnDokumlerMouseDown
      ExplicitTop = 6
      ExplicitWidth = 291
    end
  end
end


