object CariFrame: TCariFrame
  Left = 0
  Top = 0
  Width = 945
  Height = 535
  Align = alClient
  Color = clWhite
  ParentBackground = False
  ParentColor = False
  TabOrder = 0
  ExplicitWidth = 451
  ExplicitHeight = 304
  object pnl2: TPanel
    Left = 0
    Top = 0
    Width = 185
    Height = 535
    Align = alLeft
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    ExplicitHeight = 304
    object pnl1: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 3
      Width = 179
      Height = 139
      Align = alTop
      BevelOuter = bvNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      object btnDokumler: TcxButton
        AlignWithMargins = True
        Left = 3
        Top = 49
        Width = 173
        Height = 40
        Align = alTop
        Caption = 'D'#246'k'#252'mler'
        Font.Charset = TURKISH_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        OnClick = btnDokumlerClick
        LookAndFeel.SkinName = 'LondonLiquidSky'
        SpeedButtonOptions.GroupIndex = 5
      end
      object btnHesapKarti: TcxButton
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 173
        Height = 40
        Align = alTop
        Caption = 'Hesap Kart'#305
        Font.Charset = TURKISH_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
        OnClick = btnHesapKartiClick
        LookAndFeel.SkinName = 'LondonLiquidSky'
        SpeedButtonOptions.GroupIndex = 5
      end
    end
    object cxGroupBox1: TcxGroupBox
      Left = 0
      Top = 145
      Align = alClient
      Caption = 'Arama'
      Style.LookAndFeel.SkinName = 'LondonLiquidSky'
      StyleDisabled.LookAndFeel.SkinName = 'LondonLiquidSky'
      StyleFocused.LookAndFeel.SkinName = 'LondonLiquidSky'
      StyleHot.LookAndFeel.SkinName = 'LondonLiquidSky'
      TabOrder = 1
      ExplicitHeight = 159
      Height = 390
      Width = 185
      object ScrollBox2: TScrollBox
        Left = 2
        Top = 18
        Width = 181
        Height = 365
        Align = alClient
        BevelInner = bvNone
        BevelOuter = bvNone
        BorderStyle = bsNone
        Color = clWhite
        Ctl3D = False
        ParentColor = False
        ParentCtl3D = False
        TabOrder = 0
        ExplicitLeft = 1
        ExplicitTop = 17
        ExplicitWidth = 183
        ExplicitHeight = 141
        object pcArama: TcxPageControl
          Left = 0
          Top = 0
          Width = 181
          Height = 365
          Align = alClient
          HideTabs = True
          TabOrder = 0
          ExplicitWidth = 183
          ExplicitHeight = 141
          ClientRectBottom = 364
          ClientRectLeft = 1
          ClientRectRight = 180
          ClientRectTop = 1
        end
      end
    end
  end
  object JvPanel1: TJvPanel
    Left = 185
    Top = 0
    Width = 760
    Height = 535
    HotTrackFont.Charset = DEFAULT_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -11
    HotTrackFont.Name = 'Tahoma'
    HotTrackFont.Style = []
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    ExplicitWidth = 266
    ExplicitHeight = 304
    object AnaSayfaDenetimi: TcxPageControl
      Left = 0
      Top = 28
      Width = 760
      Height = 507
      Align = alClient
      HideTabs = True
      TabOrder = 0
      ExplicitWidth = 266
      ExplicitHeight = 276
      ClientRectBottom = 506
      ClientRectLeft = 1
      ClientRectRight = 759
      ClientRectTop = 1
    end
    object pnlBaslik: TJvPanel
      Left = 0
      Top = 0
      Width = 760
      Height = 28
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'Tahoma'
      HotTrackFont.Style = []
      FlatBorderColor = clBlue
      OnPaint = pnlBaslikPaint
      Align = alTop
      BevelOuter = bvNone
      BorderWidth = 1
      Color = clSilver
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -16
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
      ExplicitWidth = 266
    end
  end
  object cxPropertiesStore1: TcxPropertiesStore
    Components = <>
    StorageName = 'cxPropertiesStore1'
    Left = 64
    Top = 24
  end
end
