object CekSenetFrame: TCekSenetFrame
  Left = 0
  Top = 0
  Width = 451
  Height = 304
  Align = alClient
  TabOrder = 0
  object pnl2: TPanel
    Left = 0
    Top = 0
    Width = 185
    Height = 304
    Align = alLeft
    BevelOuter = bvNone
    Caption = 'object cxGroupBox1: TcxGroupBox'
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    object pnl1: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 3
      Width = 179
      Height = 94
      Align = alTop
      BevelOuter = bvNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      object btnCekSenet: TcxButton
        Tag = 11
        Left = 0
        Top = 0
        Width = 179
        Height = 40
        Margins.Left = 0
        Margins.Top = 0
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        Caption = #199'ek/Senet Tan'#305'mlar'#305
        Font.Charset = TURKISH_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        OnClick = btnCekSenetClick
        LookAndFeel.SkinName = 'UserSkin'
        SpeedButtonOptions.GroupIndex = 5
        ExplicitLeft = 3
        ExplicitTop = -7
        ExplicitWidth = 173
      end
      object btnDokumler: TcxButton
        Left = 0
        Top = 40
        Width = 179
        Height = 40
        Margins.Left = 0
        Margins.Top = 0
        Margins.Right = 0
        Margins.Bottom = 0
        Align = alTop
        Caption = 'D'#246'k'#252'mler'
        Font.Charset = TURKISH_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 1
        LookAndFeel.SkinName = 'LondonLiquidSky'
        SpeedButtonOptions.GroupIndex = 5
        ExplicitTop = 39
      end
    end
    object ScrollBox1: TScrollBox
      Left = 0
      Top = 100
      Width = 185
      Height = 204
      Align = alClient
      BevelInner = bvNone
      BevelOuter = bvNone
      BorderStyle = bsNone
      Color = clWhite
      Ctl3D = False
      ParentColor = False
      ParentCtl3D = False
      TabOrder = 1
      object cxGroupBox1: TcxGroupBox
        Left = 0
        Top = 0
        Align = alClient
        Caption = 'Arama'
        Style.LookAndFeel.SkinName = 'LondonLiquidSky'
        StyleDisabled.LookAndFeel.SkinName = 'LondonLiquidSky'
        StyleFocused.LookAndFeel.SkinName = 'LondonLiquidSky'
        StyleHot.LookAndFeel.SkinName = 'LondonLiquidSky'
        TabOrder = 0
        Height = 204
        Width = 185
        object ScrollBox2: TScrollBox
          Left = 2
          Top = 18
          Width = 181
          Height = 179
          Align = alClient
          BevelInner = bvNone
          BevelOuter = bvNone
          BorderStyle = bsNone
          Color = clWhite
          Ctl3D = False
          ParentColor = False
          ParentCtl3D = False
          TabOrder = 0
          ExplicitLeft = 1
          ExplicitTop = 17
          ExplicitWidth = 183
          ExplicitHeight = 186
          object pcArama: TcxPageControl
            Left = 0
            Top = 0
            Width = 181
            Height = 179
            Align = alClient
            HideTabs = True
            TabOrder = 0
            ExplicitWidth = 183
            ExplicitHeight = 186
            ClientRectBottom = 178
            ClientRectLeft = 1
            ClientRectRight = 180
            ClientRectTop = 1
          end
        end
      end
    end
  end
  object JvPanel1: TJvPanel
    Left = 185
    Top = 0
    Width = 266
    Height = 304
    HotTrackFont.Charset = DEFAULT_CHARSET
    HotTrackFont.Color = clWindowText
    HotTrackFont.Height = -11
    HotTrackFont.Name = 'Tahoma'
    HotTrackFont.Style = []
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 1
    object AnaSayfaDenetimi: TcxPageControl
      Left = 0
      Top = 28
      Width = 266
      Height = 276
      Align = alClient
      HideTabs = True
      TabOrder = 0
      ClientRectBottom = 275
      ClientRectLeft = 1
      ClientRectRight = 265
      ClientRectTop = 1
    end
    object pnlBaslik: TJvPanel
      Left = 0
      Top = 0
      Width = 266
      Height = 28
      HotTrackFont.Charset = DEFAULT_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -11
      HotTrackFont.Name = 'Tahoma'
      HotTrackFont.Style = []
      FlatBorderColor = clBlue
      OnPaint = pnlBaslikPaint
      Align = alTop
      BevelOuter = bvNone
      BorderWidth = 1
      Color = clSilver
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clBlack
      Font.Height = -16
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentBackground = False
      ParentFont = False
      TabOrder = 1
    end
  end
end
