SET NOCOUNT ON;
SET XACT_ABORT ON;
-- Tetikleyici duzeldi; donusum SP'si artik DEVRE DISI BIRAKMADAN calismali
DECLARE @sip INT = (SELECT TOP 1 S.ID FROM SIPARIS S
   WHERE S.TUR=19 AND S.DURUM IN (0,1)
     AND EXISTS(SELECT 1 FROM SIPARISDETAY SD CROSS APPLY dbo.fn_Api_Donusum_Kalan(2,409,SD.ID,0) K
                WHERE SD.SIPARISID=S.ID AND K.Kalan>0.0001)
   ORDER BY S.ID DESC);
SELECT 'Kaynak siparis' AS x, ID, TUR, DURUM, SIPARISNO FROM SIPARIS WHERE ID=@sip;
BEGIN TRAN;
DECLARE @j NVARCHAR(MAX) = N'{"SiparisId":' + CAST(@sip AS varchar(20)) +
   N',"HedefTur":14,"Tarih":"2026-08-08","Oturum":{"KulId":2,"SubeId":-1}}';
EXEC dbo.sp_Api_Donusum_SiparistenBelge_Json @j;
DECLARE @hed INT = (SELECT TOP 1 ID FROM FATBASLIK ORDER BY ID DESC);
SELECT 'Hedef irsaliye' AS x, ID, TUR, FATURANO, FATURA_MATRAHI, KDV_TUTARI, FATURA_TUTARI, ACIKLAMA FROM FATBASLIK WHERE ID=@hed;
SELECT 'Satirlar' AS x, ID, URUNID, ADET, TUTAR, YERI, YERID FROM FATURA WHERE FATBASID=@hed;
SELECT 'Siparis durumu' AS x, DURUM FROM SIPARIS WHERE ID=@sip;
ROLLBACK;
SELECT 'Rollback sonrasi' AS x, (SELECT COUNT(*) FROM FATBASLIK WHERE ID=@hed) AS Hedef,
       (SELECT DURUM FROM SIPARIS WHERE ID=@sip) AS SipDurum;
