object Form1: TForm1
  Left = 511
  Top = 257
  Width = 326
  Height = 250
  Caption = 'www.delphiturkiye.com'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 55
    Top = 104
    Width = 208
    Height = 24
    Caption = 'www.delphiturkiye.com'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Times New Roman'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 120
    Top = 136
    Width = 75
    Height = 13
    Caption = 'Mustafa '#350'im'#351'ek'
  end
  object Label3: TLabel
    Left = 120
    Top = 160
    Width = 53
    Height = 13
    Caption = 'Freeman35'
  end
  object Label4: TLabel
    Left = 120
    Top = 184
    Width = 59
    Height = 13
    Caption = 'O'#287'uz '#214'zt'#252'rk'
  end
  object cxIntl1: TcxIntl
    Connected = True
    cxLibrary.CantCreateRegistryKey = '\%s isimli registry anahtar'#305' olu'#351'turulamad'#305'.'
    PageControl2.ImageListIndexError = '(%d) indeksi 0 ve %d aral'#305#287#305'nda olmal'#305
    PageControl2.NoBaseImages = 'BaseImages is not assigned'
    PageControl2.NoRegisteredStyles = 'Kay'#305'tl'#305' hi'#231'bir stil yok'
    PageControl2.PageIndexError = 
      '%d de'#287'er ge'#231'erli bir sayfa indeks de'#287'eri de'#287'il. Sayfa indeksi 0 ' +
      've %d aral'#305#287#305'nda olmal'#305'.'
    PageControl2.PainterClassError = 'PCPainterClass'#39#305' yok'
    PageControl2.StandardStyleError = '%s stili, standart stiller taraf'#305'ndan desteklenmiyor'
    PageControl2.StyleNameError = '%s adl'#305' stil kay'#305'tl'#305' de'#287'il'
    PageControl2.TabCountEqualsZero = 'Tabs.Count = 0'
    PageControl2.TabIndexError = 'Tab indeksi (%d) s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    PageControl2.TabVisibleIndexOutsOfBounds = 
      'TabG'#246'r'#252'nme'#304'ndeksi (TabVisibleIndex) (%d), 0 ve %d de'#287'erleri aras' +
      #305'nda olmal'#305
    PageControl2.VisibleTabListEmpty = 'G'#246'r'#252'n'#252'r bir Tab yok'
    QuantumGrid5.GridRecursiveLevels = 'Tekrar eden seviye olu'#351'turamazs'#305'n'#305'z.'
    QuantumGrid5.GridDeletingConfirmationCaption = 'Onayla'
    QuantumGrid5.GridDeletingFocusedConfirmationText = 'Kay'#305't Sil?'
    QuantumGrid5.GridDeletingSelectedConfirmationText = 'Se'#231'ili t'#252'm kay'#305'tlar sil?'
    QuantumGrid5.GridNoDataInfoText = '<G'#246'sterilecek herhangi bir veri bulunmuyor>'
    QuantumGrid5.GridNewItemRowInfoText = 'Yeni bir kay'#305't eklemek i'#231'in buraya t'#305'klay'#305'n'
    QuantumGrid5.GridFilterIsEmpty = '<S'#252'zme i'#351'lemi bo'#351'>'
    QuantumGrid5.GridCustomizationFormCaption = #214'zelle'#351'tirme'
    QuantumGrid5.GridCustomizationFormColumnsPageCaption = 'Kolonlar'
    QuantumGrid5.GridGroupByBoxCaption = 
      #304'lgili kolona g'#246're guruplama yapmak i'#231'in kolon ba'#351'l'#305#287#305'n'#305' s'#252'r'#252'kle' +
      'yin'
    QuantumGrid5.GridFilterCustomizeButtonCaption = #214'zelle'#351'tir...'
    QuantumGrid5.GridColumnsQuickCustomizationHint = 'G'#246'r'#252'lebilir kolonlar'#305' g'#246'rmek i'#231'in buraya t'#305'klay'#305'n.'
    QuantumGrid5.GridCustomizationFormBandsPageCaption = 'Bantlar'
    QuantumGrid5.GridBandsQuickCustomizationHint = 'G'#246'r'#252'lebilir bantlar g'#246'rmek i'#231'in buraya t'#305'klay'#305'n.'
    QuantumGrid5.GridCustomizationFormRowsPageCaption = 'Sat'#305'rlar'
    QuantumGrid5.GridConverterIntermediaryMissing = #304'kincil bile'#351'enler yok.'#13#10'L'#252'tfen forma bir %s bile'#351'eni ekleyin.'
    QuantumGrid5.GridConverterNotExistGrid = 'cxGrid'#39'i mevcut de'#287'il'
    QuantumGrid5.GridConverterNotExistComponent = 'Bile'#351'en mevcut de'#287'il'
    QuantumGrid5.ImportErrorCaption = 'Alma hatas'#305
    QuantumGrid5.NotExistGridView = 'Grid g'#246'r'#252'n'#252'm'#252' mevcut de'#287'il'
    QuantumGrid5.NotExistGridLevel = 'Aktif grid sevyesi mevcut de'#287'il'
    QuantumGrid5.CantCreateExportOutputFile = 'Kaydedilecek '#231#305'kt'#305' dosyas'#305' olu'#351'turulam'#305'yor.'
    QuantumGrid5.EditRepositoryExtLookupComboBoxItem = 
      'ExtLookupComboBox| QuantumGrid ile kullan'#305'lan bu bile'#351'en geli'#351'mi' +
      #351' lookup '#246'zelliklere sahiptir.'
    Navigator.NavigatorHint_First = #304'lk Kay'#305't'
    Navigator.NavigatorHint_Prior = #214'nceki Kay'#305't'
    Navigator.NavigatorHint_PriorPage = #214'nceki Sayfa'
    Navigator.NavigatorHint_Next = 'Sonraki Kay'#305't'
    Navigator.NavigatorHint_NextPage = 'Sonraki Sayfa'
    Navigator.NavigatorHint_Last = 'Son Kay'#305't'
    Navigator.NavigatorHint_Insert = 'Yeni Kay'#305't Ekle'
    Navigator.NavigatorHint_Delete = 'Kay'#305't'#305' Sil'
    Navigator.NavigatorHint_Edit = 'Kay'#305't'#305' De'#287'i'#351'tir'
    Navigator.NavigatorHint_Post = 'De'#287'i'#351'ikli'#287'i Kaydet'
    Navigator.NavigatorHint_Cancel = 'De'#287'i'#351'iklikleri '#304'ptal Et'
    Navigator.NavigatorHint_Refresh = 'Veriyi Tazele'
    Navigator.NavigatorHint_SaveBookmark = #304#351'aretli Kay'#305't'#305' Kaydet'
    Navigator.NavigatorHint_GotoBookmark = #304#351'aretli Kay'#305'ta Git'
    Navigator.NavigatorHint_Filter = 'Veriyi S'#252'z'
    Navigator.Navigator_DeleteRecordQuestion = 'Kay'#305't Sil?'
    Editors5.EditDateConvertError = 'Tarih bilgisi '#231'evirilemedi'
    Editors5.EditInvalidRepositoryItem = 'Depolanan '#246#287'e kabul edilemez'
    Editors5.EditNumericValueConvertError = 'Say'#305'sal de'#287'er '#231'evrilemiyor.'
    Editors5.EditPopupCircularReferencingError = 'Dolamba'#231'l'#305' referanslara izin verilmez.'
    Editors5.EditPostError = 'De'#287'i'#351'iklikleri kay'#305't esnas'#305'nda hata olu'#351'tu.'
    Editors5.EditTimeConvertError = 'Zaman '#231'evrilmesi yap'#305'lamad'#305'. '#199#305'kmak i'#231'in Escape tu'#351'unu kullan'#305'n'
    Editors5.EditValidateErrorText = 'Ge'#231'ersiz de'#287'er. '#199#305'kmak i'#231'in Escape tu'#351'unu kullan'#305'n'
    Editors5.EditValueOutOfBounds = 'De'#287'er s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    Editors5.EditCheckBoxChecked = 'Do'#287'ru'
    Editors5.EditCheckBoxUnchecked = 'Yanl'#305#351
    Editors5.TextTrue = 'Do'#287'ru'
    Editors5.TextFalse = 'Yanl'#305#351
    Editors5.BlobButtonOK = '&TAMAM'
    Editors5.BlobButtonCancel = '&'#304'ptal'
    Editors5.BlobButtonClose = '&Kapat'
    Editors5.BlobMemo = '(MEMO)'
    Editors5.BlobMemoEmpty = '(memo)'
    Editors5.BlobPicture = '(RES'#304'M)'
    Editors5.BlobPictureEmpty = '(resim)'
    Editors5.MenuItemCaptionCut = 'K&es'
    Editors5.MenuItemCaptionCopy = '&Kopyala'
    Editors5.MenuItemCaptionPaste = 'Ya&p'#305#351't'#305'r'
    Editors5.MenuItemCaptionDelete = '&Sil'
    Editors5.MenuItemCaptionLoad = '&Y'#252'kle...'
    Editors5.MenuItemCaptionSave = '&Farkl'#305' Kaydet...'
    Editors5.DatePopupClear = 'Temizle'
    Editors5.DatePopupNow = #350'imdi'
    Editors5.DatePopupOK = 'TAMAM'
    Editors5.DatePopupToday = 'Bug'#252'n'
    Editors5.DateError = 'Ge'#231'ersiz Tarih'
    Editors5.DateToday = 'bug'#252'n'
    Editors5.DateYesterday = 'd'#252'n'
    Editors5.DateTomorrow = 'yar'#305'n'
    Editors5.DateSunday = 'Pazar'
    Editors5.DateMonday = 'Pazartesi'
    Editors5.DateTuesday = 'Sal'#305
    Editors5.DateWednesday = #199'ar'#351'amba'
    Editors5.DateThursday = 'Per'#351'embe'
    Editors5.DateFriday = 'Cuma'
    Editors5.DateSaturday = 'Cumartesi'
    Editors5.DateFirst = 'ilk'
    Editors5.DateSecond = 'ikinci'
    Editors5.DateThird = #252#231#252'nc'#252
    Editors5.DateFourth = 'd'#246'rd'#252'nc'#252
    Editors5.DateFifth = 'be'#351'inci'
    Editors5.DateSixth = 'alt'#305'nc'#305
    Editors5.DateSeventh = 'yedinci'
    Editors5.DateBOM = 'bom'
    Editors5.DateEOM = 'eom'
    Editors5.DateNow = #351'imdi'
    Editors5.CalcError = 'Hata'
    Editors5.HyperLinkPrefix = 'http://'
    Editors5.HyperLinkDoubleSlash = '//'
    Editors5.EditRepositoryBlobItem = 'BlobEdit|BLOB alanlar'#305' d'#252'zenlemek i'#231'in'
    Editors5.EditRepositoryButtonItem = 'ButtonEdit|T'#252'mle'#351'ik olarak i'#231'inde buton (lar) yer al'#305'r'
    Editors5.EditRepositoryCalcItem = 'CalcEdit|A'#231#305'lan bir pencerede hesap makinas'#305' sunar'
    Editors5.EditRepositoryCheckBoxItem = 'CheckBox|Bir se'#231'ene'#287'i se'#231'mek i'#231'in'
    Editors5.EditRepositoryComboBoxItem = 
      'ComboBox|A'#231#305'lan listede bulunan birden '#231'ok de'#287'erden birini se'#231'me' +
      'k i'#231'in'
    Editors5.EditRepositoryCurrencyItem = 'CurrencyEdit|Parasal verileri d'#252'zenlemek i'#231'in'
    Editors5.EditRepositoryDateItem = 'DateEdit|Tarihsel verileri d'#252'zenlemek i'#231'in edit kutusu sunar'
    Editors5.EditRepositoryHyperLinkItem = 'HyperLink|K'#252'pr'#252' bilgilerini d'#252'zenlemek i'#231'in'
    Editors5.EditRepositoryImageComboBoxItem = 'ImageComboBox|Verileri ili'#351'kili bir resim g'#252'stererek se'#231'mek i'#231'in'
    Editors5.EditRepositoryImageItem = 'Image|Resimleri se'#231'mek i'#231'in'
    Editors5.EditRepositoryLookupComboBoxItem = 'LookupComboBox|Ba'#351'ka bir tablodan verileri almak i'#231'in'
    Editors5.EditRepositoryMaskItem = 'MaskEdit|Verileri belirli bir bi'#231'imde girmek i'#231'in'
    Editors5.EditRepositoryMemoItem = 'Memo|Memo alanlar'#305' d'#252'zenlemek i'#231'in'
    Editors5.EditRepositoryMRUItem = 'MRUEdit|Son girilen de'#287'erleri haf'#305'zas'#305'nda saklar'
    Editors5.EditRepositoryPopupItem = 
      'PopupEdit|A'#231#305'lan bir liste i'#231'inde birden '#231'ok de'#287'erden birini se'#231 +
      'mek i'#231'in'
    Editors5.EditRepositorySpinItem = 'SpinEdit|SpinEdit '
    Editors5.EditRepositoryRadioGroupItem = 'RadioGroup|Se'#231'eneklerden birini se'#231'mek i'#231'in'
    Editors5.EditRepositoryTextItem = 'TextEdit|Veri giri'#351'i i'#231'in yaz'#305' edit'#246'r'#252
    Editors5.EditRepositoryTimeItem = 'TimeEdit|Saat de'#287'erlerini d'#252'zenlemek i'#231'in'
    Editors5.RegExprLine = #199'izgi'
    Editors5.RegExprChar = 'Karakter (Char)'
    Editors5.RegExprNotAssignedSourceStream = 'Kaynak stream yok'
    Editors5.RegExprEmptySourceStream = 'Kaynak stream bo'#351
    Editors5.RegExprCantUsePlusQuantifier = #39'+'#39' burada uygulanamaz'
    Editors5.RegExprCantUseStarQuantifier = #39'*'#39' burada uygulanamaz'
    Editors5.RegExprCantCreateEmptyAlt = 'Alternatif bo'#351' olmamal'#305
    Editors5.RegExprCantCreateEmptyBlock = 'Blok bo'#351' olmamal'#305
    Editors5.RegExprIllegalSymbol = 'Ge'#231'ersiz '#39'%s'#39
    Editors5.RegExprIllegalQuantifier = 'Ge'#231'ersiz belirleyici '#39'%s'#39
    Editors5.RegExprNotSupportQuantifier = 'Parametre girdisi desteklenmiyor'
    Editors5.RegExprIllegalIntegerValue = 'Ge'#231'ersiz say'#305'sal de'#287'er'
    Editors5.RegExprTooBigReferenceNumber = 'Referans numaras'#305' '#231'ok b'#252'y'#252'k'
    Editors5.RegExprCantCreateEmptyEnum = 'Bo'#351' liste olu'#351'amaz'
    Editors5.RegExprSubrangeOrder = 
      'Alt sevyedeki ba'#351'lang'#305#231' karakteri en sonda olacak olan karakterd' +
      'en daha k'#252#231#252'k olmal'#305'd'#305'r.'
    Editors5.RegExprHexNumberExpected0 = 'Hexadesimal say'#305' bekleniyor'
    Editors5.RegExprHexNumberExpected = 'Hexadesimal say'#305' yerine '#39'%s'#39' bulundu'
    Editors5.RegExprMissing = #39'%s'#39' yok'
    Editors5.RegExprUnnecessary = 'Gereksiz '#39'%s'#39
    Editors5.RegExprIncorrectSpace = #39'\'#39' karakterinden sonra bo'#351'luk karakterine izin verilmez'
    Editors5.RegExprNotCompiled = 'Standart ifade derlenemedi'
    Editors5.RegExprIncorrectParameterQuantifier = 'Yanl'#305#351' parametre girdisi'
    Editors5.RegExprCantUseParameterQuantifier = 'Parametre Say'#305'c'#305's'#305' buraya uygulanamaz'
    Editors5.MaskEditRegExprError = 'Genel ifade hatalar'#305' :'
    Editors5.MaskEditInvalidEditValue = 'Girilen de'#287'er ge'#231'ersiz'
    Editors5.MaskEditNoMask = 'Yok'
    Editors5.MaskEditIllegalFileFormat = 'Ge'#231'ersiz dosya bi'#231'imi'
    Editors5.MaskEditEmptyMaskCollectionFile = 'Mask koleksiyon dosyas'#305' bo'#351
    Editors5.MaskEditMaskCollectionFiles = 'Mask koleksiyon dosyalar'#305
    Editors5.SpinEditInvalidNumericValue = 'Ge'#231'ersiz say'#305'sal de'#287'er'
    Datacontroller.DataReadError = 'Stream okuma hatas'#305
    Datacontroller.DataWriteError = 'Veri yazma s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    Datacontroller.DataItemExistError = 'Bu veri zaten var'
    Datacontroller.DataRecordIndexError = 'Kay'#305't indeksi hatas'#305
    Datacontroller.DataItemIndexError = 'Veri indeksi s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    Datacontroller.DataProviderModeError = 'Bu i'#351'lem sa'#287'lay'#305'c'#305' modunda desteklenmiyor'
    Datacontroller.DataInvalidStreamFormat = 'Ge'#231'ersiz stream bi'#231'imi'
    Datacontroller.DataRowIndexError = 'Sat'#305'r indeksi s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    Datacontroller.DataCustomDataSourceInvalidCompare = 'Kar'#351#305'la'#351't'#305'r'#305'lacak gerekli bilgi bulunamad'#305
    Datacontroller.DBDetailFilterControllerNotFound = 'Detay Filtre Kontrol'#252' bulunamad'#305
    Datacontroller.DBNotInGridMode = 'Veri kontrol'#252' grid modunda de'#287'il'
    Datacontroller.DBKeyFieldNotFound = 'Anahtar alan bulunamad'#305'.'
    Filter.FilterOperatorEqual = 'e'#351'it'
    Filter.FilterOperatorNotEqual = 'e'#351'it de'#287'il'
    Filter.FilterOperatorLess = 'daha k'#252#231#252'k'
    Filter.FilterOperatorLessEqual = 'daha k'#252#231#252'k veya e'#351'it'
    Filter.FilterOperatorGreater = 'daha b'#252'y'#252'k'
    Filter.FilterOperatorGreaterEqual = 'daha b'#252'y'#252'k veya e'#351'it'
    Filter.FilterOperatorLike = 'benzer'
    Filter.FilterOperatorNotLike = 'benzer de'#287'il'
    Filter.FilterOperatorBetween = 'aral'#305#287#305'nda'
    Filter.FilterOperatorNotBetween = 'aral'#305#287#305'nda de'#287'il'
    Filter.FilterOperatorInList = 'i'#231'inde'
    Filter.FilterOperatorNotInList = 'i'#231'inde de'#287'il'
    Filter.FilterOperatorYesterday = 'd'#252'n'
    Filter.FilterOperatorToday = 'bug'#252'n'
    Filter.FilterOperatorTomorrow = 'yar'#305'n'
    Filter.FilterOperatorLastWeek = 'son hafta'
    Filter.FilterOperatorLastMonth = 'son ay'
    Filter.FilterOperatorLastYear = 'son y'#305'l'
    Filter.FilterOperatorThisWeek = 'bu hafta i'#231'inde'
    Filter.FilterOperatorThisMonth = 'bu ay i'#231'inde'
    Filter.FilterOperatorThisYear = 'bu y'#305'l i'#231'inde'
    Filter.FilterOperatorNextWeek = 'bir sonraki hafta'
    Filter.FilterOperatorNextMonth = 'bir sonraki ay'
    Filter.FilterOperatorNextYear = 'bir sonraki y'#305'l'
    Filter.FilterAndCaption = 've'
    Filter.FilterOrCaption = 'veya'
    Filter.FilterNotCaption = 'de'#287'il'
    Filter.FilterBlankCaption = 'bo'#351
    Filter.FilterOperatorIsNull = 'bo'#351
    Filter.FilterOperatorIsNotNull = 'bo'#351' de'#287'il'
    Filter.FilterOperatorBeginsWith = 'ile ba'#351'lar'
    Filter.FilterOperatorDoesNotBeginWith = 'ile ba'#351'lamaz'
    Filter.FilterOperatorEndsWith = 'ile sona erer'
    Filter.FilterOperatorDoesNotEndWith = 'ile sona ermez'
    Filter.FilterOperatorContains = 'kapsar'
    Filter.FilterOperatorDoesNotContain = 'kapsamaz'
    Filter.FilterBoxAllCaption = '(Hepsi)'
    Filter.FilterBoxCustomCaption = '('#214'zelle'#351'tirme...)'
    Filter.FilterBoxBlanksCaption = '(Bo'#351' Olanlar)'
    Filter.FilterBoxNonBlanksCaption = '(Bo'#351' Olmayanlar)'
    Filter.FilterBoolOperatorAnd = 'VE'
    Filter.FilterBoolOperatorOr = 'VEYA'
    Filter.FilterBoolOperatorNotAnd = 'VE DE'#286#304'L'
    Filter.FilterBoolOperatorNotOr = 'VEYA DE'#286#304'L'
    Filter.FilterRootButtonCaption = 'S'#252'zme'
    Filter.FilterAddCondition = '&Ko'#351'ul Ekle'
    Filter.FilterAddGroup = '&Gurup Ekle'
    Filter.FilterRemoveRow = '&Sat'#305'r'#305' Sil'
    Filter.FilterClearAll = '&T'#252'm'#252'n'#252' Temizle'
    Filter.FilterFooterAddCondition = 'yeni bir ko'#351'ul eklemek i'#231'in butona t'#305'klay'#305'n'
    Filter.FilterGroupCaption = 'a'#351'a'#287#305'da ki ko'#351'ullara uygular'
    Filter.FilterRootGroupCaption = '<k'#246'k>'
    Filter.FilterControlNullString = '<bo'#351'>'
    Filter.FilterErrorBuilding = 'Kaynaktan s'#252'zme i'#351'lemi olu'#351'turam'#305'yor'
    Filter.FilterDialogCaption = 'Al'#305#351#305'lm'#305#351' S'#252'zme'
    Filter.FilterDialogInvalidValue = 'Ge'#231'ersiz de'#287'er'
    Filter.FilterDialogUse = 'Kullan'
    Filter.FilterDialogSingleCharacter = 'Herhangi tek bir karakteri temsil etmek i'#231'in'
    Filter.FilterDialogCharactersSeries = 'Herhangi bir karakter serisini temsil etmek i'#231'in'
    Filter.FilterDialogOperationAnd = 'VE'
    Filter.FilterDialogOperationOr = 'VEYA'
    Filter.FilterDialogRows = 'Sat'#305'rlar'#305'n g'#246'sterilece'#287'i konum :'
    Filter.FilterControlDialogCaption = 'S'#252'zme Olu'#351'turucusu'
    Filter.FilterControlDialogNewFile = 'bo'#351'.flt'
    Filter.FilterControlDialogOpenDialogCaption = 'Halihaz'#305'rda ki bi s'#252'zmeyi kullan'
    Filter.FilterControlDialogSaveDialogCaption = 'Kullan'#305'lmakta olan s'#252'zmeyi dosyaya kaydet'
    Filter.FilterControlDialogActionSaveCaption = '&Farkl'#305' Kaydet...'
    Filter.FilterControlDialogActionOpenCaption = '&A'#231'...'
    Filter.FilterControlDialogActionApplyCaption = '&Uygula'
    Filter.FilterControlDialogActionOkCaption = 'TAMAM'
    Filter.FilterControlDialogActionCancelCaption = #304'ptal'
    Filter.FilterControlDialogFileExt = 'flt'
    Filter.FilterControlDialogFileFilter = 'S'#252'zme Dosyalar'#305' (*.flt)|*.flt'
    GridPopupMenu.GridNone = 'Hi'#231'biri'
    GridPopupMenu.GridSortColumnAsc = 'Artan S'#305'ralama'
    GridPopupMenu.GridSortColumnDesc = 'Azalan S'#305'ralama'
    GridPopupMenu.GridGroupByThisField = 'Bu alana g'#246're gurupla'
    GridPopupMenu.GridRemoveThisGroupItem = 'Guruplamadan '#231#305'kart'
    GridPopupMenu.GridGroupByBox = 'Bu kutuya g'#246're gurupla'
    GridPopupMenu.GridAlignmentSubMenu = 'Hizalama'
    GridPopupMenu.GridAlignLeft = 'Sola Hizala'
    GridPopupMenu.GridAlignRight = 'Sa'#287'a Hizala'
    GridPopupMenu.GridAlignCenter = 'Ortaya Hizala'
    GridPopupMenu.GridRemoveColumn = 'Bu kolonu sil'
    GridPopupMenu.GridFieldChooser = 'Alan Se'#231'ici'
    GridPopupMenu.GridBestFit = 'En iyi uyan'
    GridPopupMenu.GridBestFitAllColumns = 'En iyi uyan (B'#252't'#252'n kolonlar)'
    GridPopupMenu.GridShowFooter = #214'zet'
    GridPopupMenu.GridShowGroupFooter = 'Gurup '#214'zetleri'
    GridPopupMenu.GridSumMenuItem = 'Toplam'
    GridPopupMenu.GridMinMenuItem = 'En K'#252#231#252'k'
    GridPopupMenu.GridMaxMenuItem = 'En B'#252'y'#252'k'
    GridPopupMenu.GridCountMenuItem = 'Say'
    GridPopupMenu.GridAvgMenuItem = 'Ortalama'
    GridPopupMenu.GridNoneMenuItem = 'Hi'#231'biri'
    GridExport.UnsupportedExport = 'Desteklenmeyen g'#246'nderme tipi: %1'
    GridExport.StyleManagerKill = 
      'Stil y'#246'neticisi '#351'uanda ba'#351'ka biryerde kullan'#305'ld'#305#287#305' i'#231'in bu a'#351'ama' +
      'da eri'#351'ilemez '
    GridExport.StyleManagerCreate = 'Stil y'#246'neticisini olu'#351'turam'#305'yor'
    GridExport.ExportToHtml = 'WEB dosyas'#305' olarak kaydet (*.html)'
    GridExport.ExportToXml = 'XML dosyas'#305' olarak kaydet (*.xml)'
    GridExport.ExportToText = 'Text dosyas'#305' olarak kaydet (*.txt)'
    GridExport.EmptyExportCache = 'Export cache is empty'
    GridExport.IncorrectUnion = 'Yanl'#305#351' h'#252'crelerin birle'#351'imi'
    GridExport.IllegalWidth = 'Kolon geni'#351'li'#287'i ge'#231'ersiz'
    GridExport.InvalidColumnRowCount = 'Ge'#231'ersiz kolon veya sat'#305'r say'#305's'#305
    GridExport.IllegalHeight = 'Sat'#305'r y'#252'ksekli'#287'i ge'#231'ersiz'
    GridExport.InvalidColumnIndex = 'Kolon indeksi %d s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    GridExport.InvalidRowIndex = 'Sat'#305'r indeksi %d s'#305'n'#305'rlar'#305'n d'#305#351#305'nda'
    GridExport.InvalidStyleIndex = 'Ge'#231'ersiz index %d tipi'
    GridExport.ExportToExcel = 'MS Excel dosyas'#305' olarak kaydet (*.xls)'
    GridExport.WorkbookWrite = 'XLS dosyas'#305'na hata yaz'#305'ld'#305
    GridExport.InvalidCellDimension = 'Ge'#231'ersiz h'#252'cre boyutu'
    GridExport.BoolTrue = 'Do'#287'ru'
    GridExport.BoolFalse = 'Yanl'#305#351
    Translate.cxLibrary = True
    Translate.PageControl2 = True
    Translate.QuantumGrid5 = True
    Translate.Editors5 = True
    Translate.Datacontroller = True
    Translate.Filter = True
    Translate.GridPopupMenu = True
    Translate.GridExport = True
    Translate.Navigator = True
    Version = '5.0'
    Left = 145
    Top = 40
  end
end
