-- ============================================================
-- GenDepoKur3 : EBELGEMESAJ tablosu (GENDEPO) + ana DB synonym
--   e-Belge islem/mesaj gecmisi (gonderim sonucu, hata, durum). FK -> EBELGE.
--   GenDepoKur2'den (EBELGE) SONRA. Idempotent.
-- ============================================================
SET NOCOUNT ON;
IF DB_ID('GENDEPO') IS NULL EXEC('CREATE DATABASE [GENDEPO] COLLATE SQL_Latin1_General_CP1254_CI_AS');

IF OBJECT_ID('GENDEPO.dbo.EBELGEMESAJ','U') IS NULL
EXEC('USE GENDEPO;
CREATE TABLE dbo.EBELGEMESAJ(
  ID                bigint IDENTITY(1,1) NOT NULL,
  EBELGEID          bigint NOT NULL,
  YON               tinyint NOT NULL,
  ISLEMTURU         tinyint NOT NULL,
  MESAJTIPI         tinyint NOT NULL CONSTRAINT DF_EBELGEMESAJ_MESAJTIPI DEFAULT(0),
  MESAJ             nvarchar(max) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  HTTPKODU          int NULL,
  SERVISKODU        nvarchar(100) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  HATAKODU          nvarchar(100) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  HATAMESAJI        nvarchar(max) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  EKLEYEN           int NULL,
  EKLEMETARIHI      datetime NOT NULL CONSTRAINT DF_EBELGEMESAJ_EKLEMETARIHI DEFAULT(GETDATE()),
  SENKRON_TURU      tinyint NULL,
  ONCEKI_DURUM_KODU nvarchar(100) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  YENI_DURUM_KODU   nvarchar(100) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  YANIT_JSON        nvarchar(max) COLLATE SQL_Latin1_General_CP1254_CI_AS NULL,
  CONSTRAINT PK_EBELGEMESAJ PRIMARY KEY CLUSTERED (ID)
);
CREATE INDEX IX_EBELGEHAREKET_EBELGEID ON dbo.EBELGEMESAJ(EBELGEID, EKLEMETARIHI DESC);
IF OBJECT_ID(''dbo.EBELGE'',''U'') IS NOT NULL AND OBJECT_ID(''dbo.FK_EBELGEHAREKET_EBELGE'') IS NULL
  ALTER TABLE dbo.EBELGEMESAJ WITH CHECK ADD CONSTRAINT FK_EBELGEHAREKET_EBELGE
    FOREIGN KEY(EBELGEID) REFERENCES dbo.EBELGE(ID);
');

IF OBJECT_ID('dbo.EBELGEMESAJ','U') IS NULL AND OBJECT_ID('dbo.EBELGEMESAJ','SN') IS NULL
   CREATE SYNONYM dbo.EBELGEMESAJ FOR GENDEPO.dbo.EBELGEMESAJ;

SELECT EBELGEMESAJ = CASE WHEN OBJECT_ID('GENDEPO.dbo.EBELGEMESAJ','U') IS NOT NULL THEN 'VAR' ELSE 'YOK!' END,
       SYNONYM_DURUM = CASE WHEN OBJECT_ID('dbo.EBELGEMESAJ','SN') IS NOT NULL THEN 'VAR' ELSE 'YOK/TABLO' END;
