program Gentegre;

{$R *.dres}
uses
  WinApi.Shellapi,
  Vcl.Forms,
  SysUtils,
  Classes,
  WinTypes,
  cxFormats,
  WinApi.Messages,
  Vcl.Dialogs,
  FireDAC.Comp.Client,
  Umesaj  in '..\Ortak\Umesaj.pas' {MesajForm},
  UDokum in '..\Ortak\UDokum.pas' {DokumDlg},
  Fetautil in '..\Ortak\Fetautil.pas',
  UCombo in '..\Ortak\UCombo.pas' {ListeAyarlaDlg},
  Uliste in '..\Ortak\Uliste.pas' {ListeDlg},
  UGrid in '..\Ortak\UGrid.pas' {GridAyarlaDlg},
  UPrinter in '..\Ortak\UPrinter.pas' {PrinterDlg},
  UPaylasim in '..\Ortak\UPaylasim.pas',
  ULisans in '..\Ortak\ULisans.pas' {LisansDlg},
  UKasa in 'IcerikFrame\UKasa.pas' {KasaDlg: TFrame},
  ULOGO in 'ULOGO.PAS' {LogoDlg},
  UOPSDLG in 'UOPSDLG.pas' {OpsiyonDlg},
  UlisteCheck in '..\ortak\UlisteCheck.pas' {ListeCheckDlg},
  UVersiyon in 'UVersiyon.pas' {VersiyonDlg},
  UKrediNotlar in 'UKrediNotlar.pas' {KrediNotlarDlg},
  UVadesiGelmisler in 'UVadesiGelmisler.pas' {VadesiGelmislerDlg},
  UCekSenetArama in 'UCekSenetArama.pas' {CekSenetAramaDlg},
  UQuantGrid in '..\Ortak\UQuantGrid.pas' {QuantGrid: TDataModule},
  UDoviz in 'UDoviz.pas' {DovizDlg},
  USMS in '..\Ortak\USMS.pas' {SmsDlg},
  UMailYaz in 'UMailYaz.pas' {MailGonderDlg},
  lisansws in 'lisansws.pas',
  UCxUtils in '..\Ortak\UCxUtils.pas' {cxUtils: TDataModule},
  UCekListe in 'UCekListe.pas' {CekListeDlg},
  UDegerAra in 'UDegerAra.pas' {DegerAraDlg},
  UTakvim in 'IcerikFrame\UTakvim.pas' {TakvimDlg},
  UKrediEkle in 'UKrediEkle.pas' {KrediEkleDlg},
  UGunlukTakvim in 'UGunlukTakvim.pas' {GunlukTakvimDlg},
  UOlaylar in 'UOlaylar.pas' {OlaylarDlg},
  UMaasTablo in 'IcerikFrame\UMaasTablo.pas' {MaasTabloDlg},
  UKrediler in 'IcerikFrame\UKrediler.pas' {KredilerDlg},
  UTeminatMektubu in 'IcerikFrame\UTeminatMektubu.pas' {TeminatMektubuDlg},
  UFrameYoneticisi in '..\Ortak\UFrameYoneticisi.pas',
  FetaKurulusSiniflari in '..\Ortak\FetaKurulusSiniflari.pas',
  FetaClassExtensions in '..\Ortak\FetaClassExtensions.pas',
  FetaClassExtensionsConsts in '..\Ortak\FetaClassExtensionsConsts.pas',
  UMultiCastEvent in '..\Ortak\UMultiCastEvent.pas',
  UGenelAnaSekmeFrame in 'AnaFrame\UGenelAnaSekmeFrame.pas' {GenelAnaSekmeFrame: TFrame},
  UReharadlg in 'IcerikFrame\UReharadlg.pas' {RehberAraDlg: TFrame},
  UMultiDataSetEvent in 'UMultiDataSetEvent.pas',
  URehberAramaFrame in 'AramaFrame\URehberAramaFrame.pas' {RehberAramaFrame: TFrame},
  UAramaYokFrame in 'AramaFrame\UAramaYokFrame.pas' {AramaYokFrame: TFrame},
  UBankalarAramaFrame in 'AramaFrame\UBankalarAramaFrame.pas' {BankalarAramaFrame: TFrame},
  UBankaKredileriAramaFrame in 'AramaFrame\UBankaKredileriAramaFrame.pas' {BankaKredileriAramaFrame: TFrame},
  UTeminatMektubuAramaFrame in 'AramaFrame\UTeminatMektubuAramaFrame.pas' {TeminatMektubuAramaFrame: TFrame},
  UVadeliHesapAramaFrame in 'AramaFrame\UVadeliHesapAramaFrame.pas' {VadeliHesapAramaFrame: TFrame},
  UBankaCekleriAramaFrame in 'AramaFrame\UBankaCekleriAramaFrame.pas' {BankaCekleriAramaFrame: TFrame},
  UFaturalarAramaFrame in 'AramaFrame\UFaturalarAramaFrame.pas' {FaturalarAramaFrame: TFrame},
  UGunlukAksiyonAramaFrame in 'AramaFrame\UGunlukAksiyonAramaFrame.pas' {GunlukAksiyonAramaFrame: TFrame},
  UGenelGirisSayfasiFrame in 'GirisSayfaFrame\UGenelGirisSayfasiFrame.pas' {GenelGirisSayfasiFrame: TFrame},
  UBankaKredileriListeFrame in 'ListeFrame\UBankaKredileriListeFrame.pas' {BankaKredileriListeFrame: TFrame},
  UTeminatMektuplariListeFrame in 'ListeFrame\UTeminatMektuplariListeFrame.pas' {TeminatMektuplariListeFrame: TFrame},
  UVadeliHesaplarListeFrame in 'ListeFrame\UVadeliHesaplarListeFrame.pas' {VadeliHesaplarListeFrame: TFrame},
  UAnaGirisSayfasiFrame in 'GirisSayfaFrame\UAnaGirisSayfasiFrame.pas' {AnaGirisSayfasiFrame: TFrame},
  UFastRap in '..\Ortak\UFastRap.pas' {FastRaporDlg},
  UTakvimAksiyonFrame in 'AramaFrame\UTakvimAksiyonFrame.pas' {TakvimAksiyonFrame: TFrame},
  UDokumGirisFrame in 'GirisSayfaFrame\UDokumGirisFrame.pas' {DokumGirisFrame: TFrame},
  UDokumlerAksiyonFrame in 'AramaFrame\UDokumlerAksiyonFrame.pas' {DokumlerAksiyonFrame: TFrame},
  UGentegreFrameYonetimi in 'UGentegreFrameYonetimi.pas',
  UAksiyonlarGorevFrame in 'GorevFrame\UAksiyonlarGorevFrame.pas' {AksiyonlarGorevFrame: TFrame},
  UBankaGorevFrame in 'GorevFrame\UBankaGorevFrame.pas' {BankaGorevFrame: TFrame},
  UCariGorevFrame in 'GorevFrame\UCariGorevFrame.pas' {CariGorevFrame: TFrame},
  UCekSenetGorevFrame in 'GorevFrame\UCekSenetGorevFrame.pas' {CekSenetGorevFrame: TFrame},
  UFaturaGorevFrame in 'GorevFrame\UFaturaGorevFrame.pas' {FaturaGorevFrame: TFrame},
  UKasaGorevFrame in 'GorevFrame\UKasaGorevFrame.pas' {KasaGorevFrame: TFrame},
  URaporAraclari in 'URaporAraclari.pas',
  UCekRiskPayi in 'UCekRiskPayi.pas' {CekRiskPayiDlg},
  UDBSListeFrame in 'UDBSListeFrame.pas' {DBSListeFrame: TFrame},
  UDBSAramaFrame in 'UDBSAramaFrame.pas' {DBSAramaFrame: TFrame},
  UDBS in 'UDBS.pas' {DBSDlg: TFrame},
  UBankalarListeFrame in 'UBankalarListeFrame.pas' {BankalarListeFrame: TFrame},
  UKasalarListeFrame in 'UKasalarListeFrame.pas' {KasalarListeFrame: TFrame},
  UKasalarAramaFrame in 'UKasalarAramaFrame.pas' {KasalarAramaFrame: TFrame},
  UMasrafGelir in 'UMasrafGelir.pas' {MasrafGelirDlg: TFrame},
  Notlar in 'Notlar.pas',
  UBankaSecimi in 'UBankaSecimi.pas' {BankaSecimDlg},
  UAcilisKaydi in 'UAcilisKaydi.pas' {AcilisKaydiDlg},
  UVadeliHesap in 'IcerikFrame\UVadeliHesap.pas' {VadeliHesapDlg: TFrame},
  GT_RehberAbout in 'GT_RehberAbout.pas' {AboutBox},
  UDokumAramaFrame in 'AramaFrame\UDokumAramaFrame.pas' {DokumAramaFrame: TFrame},
  PrjConst in 'PrjConst.pas',
  UBinarySave in '..\Ortak\UBinarySave.pas',
  UTakvimIslemleri in 'UTakvimIslemleri.pas',
  UBelgeIslemleri in 'UBelgeIslemleri.pas' {BelgeIslemleriDlg},
  UKasaWizard in 'UKasaWizard.pas' {KasaWizardDlg},
  UHesapPlani in 'UHesapPlani.pas' {HesapPlaniDlg},
  UResim in 'UResim.pas' {ResimDlg},
  URehberAyar in 'URehberAyar.pas' {RehberAyarDlg},
  UPOSListeFrame in 'UPOSListeFrame.pas' {POSListeFrame: TFrame},
  UKrediKartiListeFrame in 'UKrediKartiListeFrame.pas' {KrediKartiListeFrame: TFrame},
  UKrediKarti in 'UKrediKarti.pas' {KrediKarti: TFrame},
  UPOS in 'UPOS.pas' {POS: TFrame},
  UGirdi in '..\Ortak\UGirdi.pas' {GirdiAyarlaDlg},
  UTakvimAcilisKaydi in 'UTakvimAcilisKaydi.pas' {frmTakvimAcilis},
  UHesapKoduPicker in 'UHesapKoduPicker.pas' {HesapKoduPicker},
  UCekListeFrame in 'ListeFrame\UCekListeFrame.pas' {CekSenetListeFrame: TFrame},
  UCekAramaFrame in 'AramaFrame\UCekAramaFrame.pas' {CekAramaFrame: TFrame},
  USenetAramaFrame in 'AramaFrame\USenetAramaFrame.pas' {SenetAramaFrame},
  UKullaniciYetki in 'UKullaniciYetki.pas' {KullaniciYetkiDlg},
  UTabloGiris in '..\Ortak\UTabloGiris.pas' {TabloGirisDlg},
  UParaDegisiklik in 'UParaDegisiklik.pas' {ParaDegisiklikDlg},
  UReplikasyon in 'UReplikasyon.pas' {ReplikasyonDlg},
  UTakvimKKEkstresi in 'UTakvimKKEkstresi.pas' {TakvimKKEkstresiDlg},
  UTakvimGenelHareket in 'UTakvimGenelHareket.pas' {TakvimGenelHareketDlg},
  UOpsiyonCari in 'UOpsiyonCari.pas' {OpsiyonCariDlg},
  UGorevListeAramaFrame in 'AramaFrame\UGorevListeAramaFrame.pas' {GorevListeAramaFrame: TFrame},
  UGorevListeDlg in 'ListeFrame\UGorevListeDlg.pas' {GorevListeDlg: TFrame},
  UOpsiyonAksiyon in 'UOpsiyonAksiyon.pas' {OpsiyonAksiyonDlg},
  UStokAksiyonFrame in 'AramaFrame\UStokAksiyonFrame.pas' {StokAksiyonFrame: TFrame},
  UStokAramaFrame in 'AramaFrame\UStokAramaFrame.pas' {StokAramaFrame: TFrame},
  UTeklifAksiyonFrame in 'AramaFrame\UTeklifAksiyonFrame.pas' {TeklifAksiyonFrame: TFrame},
  UTeklifAramaFrame in 'AramaFrame\UTeklifAramaFrame.pas' {TeklifAramaFrame: TFrame},
  UStokListeDlg in 'ListeFrame\UStokListeDlg.pas' {StokListeDlg: TFrame},
  UTeklifListeDlg in 'ListeFrame\UTeklifListeDlg.pas' {TeklifListeDlg: TFrame},
  UStokGorevFrame in 'GorevFrame\UStokGorevFrame.pas' {StokGorevFrame: TFrame},
  UTeklifGorevFrame in 'GorevFrame\UTeklifGorevFrame.pas' {TeklifGorevFrame: TFrame},
  UStokWizard in 'UStokWizard.pas' {StokWizardDlg},
  UOpsiyonStok in 'UOpsiyonStok.pas' {OpsiyonStokDlg},
  UFirsatListeAramaFrame in 'ListeFrame\UFirsatListeAramaFrame.pas' {FirsatListeAramaFrame: TFrame},
  UTakvimProje in 'IcerikFrame\UTakvimProje.pas' {TakvimProje: TFrame},
  UTakvimProjeAramaFrame in 'AramaFrame\UTakvimProjeAramaFrame.pas' {TakvimProjeAramaFrame: TFrame},
  UTeklifWizard in 'UTeklifWizard.pas' {TeklifWizardDlg},
  UOpsiyonTeklif in 'UOpsiyonTeklif.pas' {OpsiyonTeklifDlg},
  UOpsiyonFatura in 'UOpsiyonFatura.pas' {OpsiyonFaturaDlg},
  URehberWizard in 'URehberWizard.pas' {RehberWizardDlg},
  UCariFonksiyonlar in 'UCariFonksiyonlar.pas',
  UFaturalar in 'IcerikFrame\UFaturalar.pas' {FaturalarDlg: TFrame},
  UFaturaWizard in 'UFaturaWizard.pas' {FaturaWizardDlg},
  UTablodanDuzenle in 'UTablodanDuzenle.pas' {TablodanDuzenleDlg},
  UKasaTanimWizard in 'UKasaTanimWizard.pas' {KasaTanimWizardDlg},
  UBankaTanimWizard in 'UBankaTanimWizard.pas' {BankaTanimWizardDlg},
  UAlarm in 'UAlarm.pas' {AlarmDlg},
  UStokTalepListe in 'ListeFrame\UStokTalepListe.pas' {StokTalepListeDlg: TFrame},
  UFatTransferWizard in 'UFatTransferWizard.pas' {FatTransferWizardDlg},
  UStokTalepAramaFrame in 'AramaFrame\UStokTalepAramaFrame.pas' {StokTalepAramaFrame: TFrame},
  UComboImgDuzenle in '..\Ortak\UComboImgDuzenle.pas' {ImgListeAyarlaDlg},
  Usifre in 'Usifre.pas' {PasswordDlg},
  UKullaniciDuzenle in 'UKullaniciDuzenle.pas' {KullaniciDuzenleDlg},
  UStokSayim in 'UStokSayim.pas' {StokSayimDlg},
  UOpsiyonCekSenet in 'UOpsiyonCekSenet.pas' {OpsiyonCekSenetDlg},
  EntegraActivityAutomationService1 in 'EntegraActivityAutomationService1.pas',
  UCekWizard in 'UCekWizard.pas' {CekWizardDlg},
  UMakbuzWizard in 'UMakbuzWizard.pas' {MakbuzWizardDlg},
  UNakitDlg in 'UNakitDlg.pas' {NakitDlg},
  UVersiyonGuncelle in 'UVersiyonGuncelle.pas',
  UServisAramaFrame in 'AramaFrame\UServisAramaFrame.pas' {ServisAramaFrame: TFrame},
  UServisGorevFrame in 'GorevFrame\UServisGorevFrame.pas' {ServisGorevFrame: TFrame},
  UServisListeDlg in 'ListeFrame\UServisListeDlg.pas' {ServisListeDlg: TFrame},
  USecForm in 'USecForm.pas' {SecimDlg},
  UServisWizard in 'UServisWizard.pas' {ServisWizardDlg},
  URehberAramaEkrani in 'URehberAramaEkrani.pas' {RehberAramaEkrani},
  UDemirbasAramaFrame in 'AramaFrame\UDemirbasAramaFrame.pas' {DemirbasAramaFrame: TFrame},
  UDemirbasListeDlg in 'ListeFrame\UDemirbasListeDlg.pas' {DemirbasListeDlg: TFrame},
  UDemirbasGorevFrame in 'GorevFrame\UDemirbasGorevFrame.pas' {DemirbasGorevFrame: TFrame},
  UDemirbasWizard in 'UDemirbasWizard.pas' {DemirbasWizardDlg},
  UAnaForm in 'UAnaForm.pas' {AnaForm},
  UKrediHesapMakineDlg in 'UKrediHesapMakineDlg.pas' {KrediHesapMakineDlg},
  UKodAgaci in 'UKodAgaci.pas' {KodAgaciDlg},
  UMailDokum in 'UMailDokum.pas' {MailDokumDlg},
  UYedekCalistir in 'UYedekCalistir.pas' {YedekCalistirDlg},
  UBekletme in 'UBekletme.pas' {BekletmeDlg},
  USeyirDefteri in 'USeyirDefteri.pas' {SeyirDefteriDlg},
  MSS_Sender in 'MSS_Sender.pas',
  UDokumSart in 'IcerikFrame\UDokumSart.pas' {DokumSartDlg},
  UOpsiyonBanka in 'UOpsiyonBanka.pas' {OpsiyonBankaDlg},
  USiparisWizard in 'USiparisWizard.pas' {SiparisWizardDlg},
  UKaliteParametre in 'UKaliteParametre.pas' {KaliteParametreDlg},
  UHizliGiris in 'UHizliGiris.pas' {HizliGirisDlg},
  UHizliGirisTahsilat in 'UHizliGirisTahsilat.pas' {HizliGirisTahsilatDlg},
  UHizliGirisIsk in 'UHizliGirisIsk.pas' {HizliGirisIsk},
  UHizliGirisBaski in 'UHizliGirisBaski.pas' {HizliGirisBaskiDlg},
  UHizliGirisKKTahsilat in 'UHizliGirisKKTahsilat.pas' {HizliGirisKKTahsilatDlg},
  UHizliGirisKasaSay in 'UHizliGirisKasaSay.pas' {HizliGirisKasaSayDlg},
  UGiderPusulasi in 'UGiderPusulasi.pas' {GiderPusulasiDlg},
  UKullaniciGiris in 'UKullaniciGiris.pas' {KullaniciGirisDlg},
  UOpsiyonKasa in 'UOpsiyonKasa.pas' {OpsiyonKasaDlg},
  UKampanyalar in 'UKampanyalar.pas' {KampanyalarDlg},
  UitsBusiness in 'UitsBusiness.pas',
  UItsEczaDepo in 'UItsEczaDepo.pas' {ITSEzcaDepoDlg},
  DepoMalIadeServis in 'ItsServisler\DepoMalIadeServis.pas',
  DepoSatisServis in 'ItsServisler\DepoSatisServis.pas',
  DepoSatisIptalServis in 'ItsServisler\DepoSatisIptalServis.pas',
  DepoUrunDogrulamaServis in 'ItsServisler\DepoUrunDogrulamaServis.pas',
  DeaktivasyonBildirimServis in 'ItsServisler\DeaktivasyonBildirimServis.pas',
  DepoMalAlmServis in 'ItsServisler\DepoMalAlmServis.pas',
  UHizliGirisDokumDlg in 'UHizliGirisDokumDlg.pas' {HizliGirisDokumDlg},
  GenUpdateWCF in 'GenUpdateWCF.pas',
  UEkipmanWizard in 'UEkipmanWizard.pas' {EkipmanWizardDlg},
  UEkipmanListeDlg in 'ListeFrame\UEkipmanListeDlg.pas' {EkipmanListeDlg: TFrame},
  KAZip in 'kazip\KAZip.pas',
  UServisDetayPersonel in 'UServisDetayPersonel.pas' {ServisDetayPersonelDlg},
  UServisIslemDetaylari in 'UServisIslemDetaylari.pas' {ServisIslemDetaylariDlg},
  UServisEkipmanSec in 'UServisEkipmanSec.pas' {ServisEkipmanSecDlg},
  UOpsiyonServis in 'UOpsiyonServis.pas' {OpsiyonServisDlg},
  URehberBilgiDuzenle in 'URehberBilgiDuzenle.pas' {RehberBilgiDuzenleDlg},
  UGENINIDuzenle in 'UGENINIDuzenle.pas' {GENINIDuzenleDlg},
  UServisTanimListeleriAramaFrame in 'AramaFrame\UServisTanimListeleriAramaFrame.pas' {ServisTanimListeleriAramaFrame: TFrame},
  UBankaKredileriListeTanimlariFrame in 'AramaFrame\UBankaKredileriListeTanimlariFrame.pas' {BankaKredileriListeTanimlariFrame: TFrame},
  UDokumanGorevFrame in 'GorevFrame\UDokumanGorevFrame.pas' {DokumanGorevFrame: TFrame},
  UDokumanAramaFrame in 'AramaFrame\UDokumanAramaFrame.pas' {DokumanAramaFrame: TFrame},
  UDokumanAksiyonFrame in 'AramaFrame\UDokumanAksiyonFrame.pas' {DokumanAksiyonFrame: TFrame},
  UDokumanListeFrame in 'ListeFrame\UDokumanListeFrame.pas' {DokumanListeFrame: TFrame},
  UDokumanWizard in 'UDokumanWizard.pas' {DokumanWizard},
  UGirisKutusuEx in '..\Ortak\UGirisKutusuEx.pas' {GirisKutusuEx},
  FileAssociationDetails in '..\Ortak\FileAssociationDetails.pas',
  UUretimAramaFrame in 'AramaFrame\UUretimAramaFrame.pas' {UretimAramaFrame: TFrame},
  UUretimListeDlg in 'ListeFrame\UUretimListeDlg.pas' {UretimListeDlg: TFrame},
  UUretimWizard in 'UUretimWizard.pas' {UretimWizardDlg},
  UKaliteYonetimAramaFrame in 'AramaFrame\UKaliteYonetimAramaFrame.pas' {KaliteYonetimAramaFrame: TFrame},
  UKYDuzelticiVeOnleyiciFaalListeDlg in 'ListeFrame\UKYDuzelticiVeOnleyiciFaalListeDlg.pas' {KYDuzelticiVeOnleyiciFaalListeDlg: TFrame},
  UAlanlar in 'UAlanlar.pas' {AlanlarDlg},
  UStokHizmetAra in 'UStokHizmetAra.pas' {StokHizmetAraDlg},
  UDuyuruOku in 'UDuyuruOku.pas' {DuyuruOkuDlg},
  UCokluSecim in 'UCokluSecim.pas' {CokluSecimDlg},
  UGenNotificationUtils in '..\Ortak\UGenNotificationUtils.pas',
  UHizliGirisFatBaslikBilgileri in 'UHizliGirisFatBaslikBilgileri.pas' {HizliGirisFatBaslikBilgileriDlg},
  UEntegrasyonEslestirme in 'UEntegrasyonEslestirme.pas' {EntegrasyonEslestirmeDlg},
  UUretimRecete in 'UUretimRecete.pas' {UretimReceteDlg},
  UFiyatSor in 'UFiyatSor.pas' {FiyatSorDlg},
  UUretimGorevFrame in 'GorevFrame\UUretimGorevFrame.pas' {UretimGorevFrame: TFrame},
  UUretimEmriListeDlg in 'ListeFrame\UUretimEmriListeDlg.pas' {UretimEmriListeDlg: TFrame},
  UUretimEmriAramaFrame in 'AramaFrame\UUretimEmriAramaFrame.pas' {UretimEmriAramaFrame: TFrame},
  UUretimEmriWizard in 'UUretimEmriWizard.pas' {UretimEmriWizardDlg},
  UYilSonuDevirIslemleri in 'UYilSonuDevirIslemleri.pas' {YilSonuDevirIslemleriDlg},
  UBarkodYazdir in 'UBarkodYazdir.pas' {BarkodYazdirDlg},
  ADODB2010 in 'MailReaderMapi2\ADODB2010.pas',
  DAO2010 in 'MailReaderMapi2\DAO2010.pas',
  GenOutLookInterface in 'MailReaderMapi2\GenOutLookInterface.pas',
  MAPIOLEMailreader in 'MailReaderMapi2\MAPIOLEMailreader.pas',
  Outlook2010 in 'MailReaderMapi2\Outlook2010.pas',
  Excel2010 in 'MailReaderMapi2\Excel2010.pas',
  Office2010 in 'MailReaderMapi2\Office2010.pas',
  UTerazi in 'UTerazi.pas' {TeraziDlg},
  UUretimPlanlamaListeDlg in 'ListeFrame\UUretimPlanlamaListeDlg.pas' {UretimPlanlamaListeDlg: TFrame},
  UUretimPlanlamaAramaFrame in 'AramaFrame\UUretimPlanlamaAramaFrame.pas' {UretimPlanlamaAramaFrame: TFrame},
  UHizliGirisAnaMenu in 'UHizliGirisAnaMenu.pas' {HizliGirisAnaMenu},
  UIzleme in 'UIzleme.pas' {IzlemeDlg},
  UFaturaKapama in 'UFaturaKapama.pas' {FaturaKapamaDlg},
  Utablo in 'Utablo.pas' {Tablo: TDataModule},
  UKategori in 'UKategori.pas' {KategoriDlg},
  UOpsiyonKasiyer in 'UOpsiyonKasiyer.pas' {OpsiyonKasiyerDlg},
  USatinAlmaListeDlg in 'ListeFrame\USatinAlmaListeDlg.pas' {SatinAlmaListeDlg: TFrame},
  USatinAlmaWizard in 'USatinAlmaWizard.pas' {SatinAlmaWizard},
  USatinAlmaAramaFrame in 'AramaFrame\USatinAlmaAramaFrame.pas' {SatinAlmaAramaFrame: TFrame},
  UStokDurumDetay in 'UStokDurumDetay.pas' {StokDurumDetayDlg},
  URaporium in 'URaporium.pas' {RaporiumDlg},
  UWebServis in 'UWebServis.pas',
  UMaliyetlerListeFrame in 'ListeFrame\UMaliyetlerListeFrame.pas' {MaliyetlerListeFrame: TFrame},
  UMaliyetAramaFrame in 'AramaFrame\UMaliyetAramaFrame.pas' {MaliyetAramaFrame: TFrame},
  UHizliGirisPDKS in 'UHizliGirisPDKS.pas' {HizliGirisPDKSDlg},
  UOpsiyonDemirbas in 'UOpsiyonDemirbas.pas' {OpsiyonDemirbasDlg},
  UFislerAramaFrame in 'AramaFrame\UFislerAramaFrame.pas' {FislerAramaFrame: TFrame},
  UFislerListeFrame in 'ListeFrame\UFislerListeFrame.pas' {FislerListeFrame: TFrame},
  Ubelgegiris in 'Ubelgegiris.pas' {belgegirisdlg},
  EFaturaOIB in 'EFaturaOIB.pas',
  Gentegre.UI.EFatura.FirmaAra in 'Gentegre.UI.EFatura.FirmaAra.pas' {EFaturaFirmaAra},
  GenoTIP.Ortak.GridPivotUtils in '..\Ortak\GenoTIP.Ortak.GridPivotUtils.pas',
  UMasrafAnaliz in 'UMasrafAnaliz.pas' {MasrafAnalizDlg},
  UIKGorevFrame in 'GorevFrame\UIKGorevFrame.pas' {IKGorevFrame: TFrame},
  UIKListeDlg in 'ListeFrame\UIKListeDlg.pas' {IKListeDlg: TFrame},
  UIKDlgGenelAramaFrame in 'AramaFrame\UIKDlgGenelAramaFrame.pas' {IKDlgGenelAramaFrame: TFrame},
  UIKWizard in 'UIKWizard.pas' {IKWizardDlg},
  UPDKSListeFrame in 'ListeFrame\UPDKSListeFrame.pas' {PDKSListeFrame: TFrame},
  UIskontoDlg in 'UIskontoDlg.pas' {IskontoDlg},
  oPENsqlsERVER in '..\Ortak\oPENsqlsERVER.pas' {OpenSQLServerForm},
  UOpsiyonIK in 'UOpsiyonIK.pas' {OpsiyonIKDlg},
  UMaasListe in 'UMaasListe.pas' {MaasListeDlg},
  UBarkod in 'UBarkod.pas' {BarkodDlg},
  UCallerId in 'UCallerId.pas' {CallerIdDlg},
  UCariEkle in 'UCariEkle.pas' {CariEkleDlg},
  UHizliSiparisSecim in 'UHizliSiparisSecim.pas' {HizliSiparisSecim},
  UBelgeZarflari in 'UBelgeZarflari.pas' {BelgeZarflariDlg},
  UHizliGunsonuDlg in 'UHizliGunsonuDlg.pas' {HizliGunsonuDlg},
  UDokumanKaydet in 'UDokumanKaydet.pas' {DokumanKaydetDlg},
  USonlandir in 'USonlandir.pas' {SonlandirDlg},
  UKalibrasyon in 'UKalibrasyon.pas' {KalibrasyonDlg},
  UHizliGunsonuForm in 'UHizliGunsonuForm.pas' {HizliGunsonuForm},
  GenoTIP.eFatura.NativeApi in 'GenoTIP.eFatura.NativeApi.pas',
  UMesajGrup in 'UMesajGrup.pas' {MesajGrupDlg},
  UGorevDlg in 'UGorevDlg.pas' {GorevDlg},
  UOpsiyonDokuman in 'UOpsiyonDokuman.pas' {OpsiyonDokumanDlg},
  UScanner in 'UScanner.pas' {ScannerDlg},
  UYazarKasa_Ingenico in 'UYazarKasa_Ingenico.pas',
  UProgramSonuDialog in '..\Ortak\UProgramSonuDialog.pas' {ProgramSonuDialog},
  dlgSearchText in '..\Ortak\dlgSearchText.pas' {TextSearchDialog},
  dlgReplaceText in '..\Ortak\dlgReplaceText.pas' {TextReplaceDialog},
  dlgConfirmReplace in '..\Ortak\dlgConfirmReplace.pas' {ConfirmReplaceDialog},
  uKosulDetayAra in '..\Ortak\uKosulDetayAra.pas' {KosulDetayAra},
  UOpsiyonUretimDlg in 'UOpsiyonUretimDlg.pas' {OpsiyonUretimDlg},
  USMSIslemleri in '..\Ortak\USMSIslemleri.pas',
  UHazirSMS in '..\Ortak\UHazirSMS.pas' {HazirSMSDlg},
  UServisSonlandir in 'UServisSonlandir.pas' {ServisSonlandirDlg},
  UUyari in 'UUyari.pas' {UyariDlg},
  UMailSablonDuzenle in 'UMailSablonDuzenle.pas' {MailSablonDuzenleDlg},
  UDemirbasDurumDegis in 'UDemirbasDurumDegis.pas' {DemirbasDurumDegisDlg},
  UKYSapmaOlayListeDlg in 'ListeFrame\UKYSapmaOlayListeDlg.pas' {KYSapmaOlayListeDlg: TFrame},
  UUnitTests in 'UUnitTests.pas',
  UKaliteToplanti in 'UKaliteToplanti.pas' {KaliteToplantiDlg},
  UKYToplantiListeDlg in 'UKYToplantiListeDlg.pas' {KYToplantiListeDlg: TFrame},
  UKYDuzelticiVeOnleyiciFaalWizard in 'UKYDuzelticiVeOnleyiciFaalWizard.pas' {KYDuzelticiVeOnleyiciFaalWizardDlg},
  UKYSapmaOlayWizard in 'UKYSapmaOlayWizard.pas' {KYSapmaOlayWizardDlg},
  UMailGonderim in 'UMailGonderim.pas',
  UExceldenVeriAl in 'UExceldenVeriAl.pas',
  URotatifDonemFaiz in 'URotatifDonemFaiz.pas' {RotatifDonemFaizDlg},
  UProjeMaliyet in 'UProjeMaliyet.pas' {ProjeMaliyetDlg},
  UBankaHareketleri in 'UBankaHareketleri.pas' {BankaHareketlerDlg},
  UBankaHareketKural in 'UBankaHareketKural.pas' {BankaHareketKuralDlg},
  USatinAlmaWizard2 in 'USatinAlmaWizard2.pas' {SatinAlmaWizard2},
  UStokTalepWizard in 'UStokTalepWizard.pas' {StokTalepWizard},
  UFaturaTransferListe in 'IcerikFrame\UFaturaTransferListe.pas' {FatTransferListeDlg: TFrame},
  UIsEmriPersonelZaman in 'UIsEmriPersonelZaman.pas' {IsEmriPersonelZamanDlg},
  UMesajlasma in 'UMesajlasma.pas' {MesajlasmaDlg},
  UFirsatListeDlg in 'ListeFrame\UFirsatListeDlg.pas' {FirsatListeDlg: TFrame},
  UFirsatWizard in 'UFirsatWizard.pas' {FirsatWizardDlg},
  UProjeListeDlg in 'ListeFrame\UProjeListeDlg.pas' {ProjeListeDlg: TFrame},
  UProjeListeAramaFrame in 'ListeFrame\UProjeListeAramaFrame.pas' {ProjeListeAramaFrame: TFrame},
  UProjeWizard in 'UProjeWizard.pas' {ProjeWizardDlg},
  UUTSDlg in 'UTS\UUTSDlg.pas' {UTSDlg},
  ModelApi in 'UTS\ModelApi.pas',
  Models in 'UTS\Models.pas',
  RestUTS in 'UTS\RestUTS.pas',
  UIsListesi in 'ListeFrame\UIsListesi.pas',
  UKYEgitimListeDlg in 'UKYEgitimListeDlg.pas' {KYEgitimListeDlg: TFrame},
  UKYDenetimWizard in 'UKYDenetimWizard.pas' {KYDenetimWizardDlg},
  UKYDenetimListeDlg in 'ListeFrame\UKYDenetimListeDlg.pas' {KYDenetimListeDlg: TFrame},
  UServisHareketEkle in 'UServisHareketEkle.pas' {ServisHareketDlg},
  URichEdit in 'URichEdit.pas' {RichEditDlg},
  UKYKontrolListeDlg in 'ListeFrame\UKYKontrolListeDlg.pas' {KYKontrolListeDlg: TFrame},
  UOpsiyonKalite in 'UOpsiyonKalite.pas' {OpsiyonKaliteDlg},
  UYetkiKategori in 'UYetkiKategori.pas' {YetkiKategoriDlg},
  UBelgeDonusum in 'UBelgeDonusum.pas' {BelgeDonusumDlg},
  UGoogleSifre in 'UGoogleSifre.pas' {GoogleSifreDlg},
  UFatTransferAramaFrame in 'AramaFrame\UFatTransferAramaFrame.pas' {FatTransferAramaFrame: TFrame},
  UMutabakat in 'UMutabakat.pas' {MutabakatDlg},
  UTahakkukDlg in 'UTahakkukDlg.pas' {TahakkukDlg},
  UUTSKontrol in 'UUTSKontrol.pas' {UTSKontrolDlg},
  {$IFDEF 3Dparty}
  uUtility_my in '..\3dparty\uUtility_my.pas',
  {$endif 3Dparty}
  fbCommon in 'Social\MetaModules\fbCommon.pas',
  fbDatamodule in 'Social\MetaModules\fbDatamodule.pas',
  fbClasses in 'Social\MetaModules\fbClasses.pas',
  uSocialListFrame in 'Social\uSocialListFrame.pas' {SocialMediaFrame: TFrame},
  uSocialAramaFrame in 'Social\uSocialAramaFrame.pas' {SocialAramaFrame: TFrame},
  dmIMAPModule in 'Social\ImapModules\dmIMAPModule.pas' {IMAPModule: TDataModule},
  uOrtakLog in 'Social\uOrtakLog.pas',
  uSocialCommon in 'Social\uSocialCommon.pas',
  GenGoogleCalenderService in '..\GoogleTakvim\GenGoogleCalenderService.pas',
  URehberTemsilci in 'URehberTemsilci.pas' {RehberTemsilciDlg},
  UInfo in 'UInfo.pas' {InfoDlg};

{$R Gentegre.KLR}

{$R *.RES}
//
// {$R ..\Ortak\cxTurkce_19_v3_ANSI.res}
//     RESOURCE olmadan UTablo.GridTurkcelestir zaten bu iþi yapýyor
//var
//  searchResult : TSearchRec;
var
  DateNow : string;
begin
  // Set8087CW($133F);
//  LocalizerOnFly.SoftMode:=true;
//  LocalizerOnFly.Init;

  Application.Initialize;
  {$IFDEF 3Dparty}
    SysUtils.DateTimeToString(DateNow,'yyyy-mm-dd',Now);
    //_LogInterface._LogFileName := 'Gentegre_'+DateNow+'.log';
    _LogInterface._LogFileName := 'Gentegre_.log';
    SysUtils.DateTimeToString(DateNow,'yyyy-mm-dd hh:nn:ss ',Now);
    _LogEkle('INFO','*************************************************************');
    _LogEkle('STARTUP','Baþlangýç '+DateNow);
    _LogEkle('INFO','*************************************************************');
  {$ENDIF 3Dparty}

  if not ProgKapat then begin
     if GetThreadLocale <> $41F then
        SetThreadLocale($41F);
     GetFormatSettings;
     cxFormatController.UseDelphiDateTimeFormats := True;

     Application.CreateForm(TTablo, Tablo);

  if (not ProgKapat)and(PasswordEkrani('Gentegre')) then begin
       LogoDlg := TLogoDlg.Create(Application);

       //LogoDlg.Show;
       //LogoDlg.Update;
       //03-03-2022 Application.CreateForm(TQuantGrid, QuantGrid);
       TRaporAraclari.Modul := 'C';
       Application.CreateForm(TAnaForm, AnaForm);
       Application.CreateForm(TFastRaporDlg, FastRaporDlg);
       TRaporAraclari.Ini := RehberIni;
       LogoDlg.Free;
       Application.Run;
       if (RestartProgram) then
           ShellExecute(0, 'open', PChar(Application.ExeName),PWideChar(RestartParameters), nil, SW_SHOWNORMAL);
     end;
     try
      ExitProcess(ExitCode);
      exit;
     except
      Halt;
     end;

  end;

end.














