CREATE OR ALTER PROC [dbo].[sp_Grnt_AlisFaturaHareketIslem](@jsonData NVARCHAR(MAX), @TIP INT, @SONUC_ID INT OUTPUT,@SONUC_MESAJ VARCHAR(5000) OUTPUT) 
AS
BEGIN
	DECLARE 
		@GNTP_FATBASLIKID INT, 
		@GNTP_FATURAID INT,
		@FATBASID INT,
		@FATURADETAYID INT,
		@REHBERID INT, 
		@TUR VARCHAR(50), 
		@URUNKOD VARCHAR(50), 
		@ACIKLAMA VARCHAR(250), 
		@ADET DECIMAL(24,6), 
		@BIRIM VARCHAR(50), 
		@BIRIMFIYAT FLOAT, 
		@TUTAR FLOAT, 
		@ISKONTO FLOAT,
		@URUNNO NVARCHAR(40),
		@KDV FLOAT,
		@MASRAFKOD VARCHAR(50), 
		@KUR VARCHAR(50), 
		@DOVIZ_TUTARI FLOAT, 
		@DOVIZ_KURU VARCHAR(50),
		@DOVIZ_BIRIMFIYAT FLOAT, 
		@DOVIZKURDEGERI FLOAT, 
		@EKLEYEN INT, 
		@SUBE NVARCHAR(100),
		@SUBEID INT, 
		@EKLEMETARIHI DATETIME,
		@FATURANO NVARCHAR(100),
		@KDVDURUM NVARCHAR(100),
		@KDVMUHAFIYETI SMALLINT,
		@OZELKOD_SATIR NVARCHAR(100),
		@OZELKOD2_SATIR NVARCHAR(100),
		@MASRAFID INT,
		@URUNID INT,
		@YERI INT,
		@YERID INT,
		@BIRIMID INT,
		@DEPO NVARCHAR(100),
		@DEPOID INT,
		@LOTNO NVARCHAR(100),
		@SERINO NVARCHAR(100),
		@SKT DATETIME,
		@SERILOTID INT,
		@IZLEMID INT

	SELECT
		@FATBASID = JSON_VALUE(@jsonData, '$.FATBASID'),
		@GNTP_FATURAID = JSON_VALUE(@jsonData, '$.FATURAID'),
		@FATURADETAYID = JSON_VALUE(@jsonData, '$.FATURADETAYID '),
		@REHBERID = JSON_VALUE(@jsonData, '$.REHBERID'),
		@URUNKOD = JSON_VALUE(@jsonData, '$.URUNKOD'),
		@MASRAFKOD = JSON_VALUE(@jsonData, '$.MASRAFKOD'),
		@ADET = JSON_VALUE(@jsonData, '$.ADET'),
		@BIRIM = JSON_VALUE(@jsonData, '$.BIRIM'),
		@BIRIMFIYAT = JSON_VALUE(@jsonData, '$.BIRIMFIYAT'),
		@TUTAR = JSON_VALUE(@jsonData, '$.TUTAR'),
		@ISKONTO = JSON_VALUE(@jsonData, '$.ISKONTO'),
		@URUNNO = JSON_VALUE(@jsonData, '$.URUNNO'),
		@KDV = JSON_VALUE(@jsonData, '$.KDV'),
		@KUR = JSON_VALUE(@jsonData, '$.KUR'),
		@DOVIZ_BIRIMFIYAT = JSON_VALUE(@jsonData, '$.DOVIZ_BIRIMFIYAT'),
		@DOVIZ_TUTARI = JSON_VALUE(@jsonData, '$.DOVIZ_TUTARI'),
		@DOVIZ_KURU = JSON_VALUE(@jsonData, '$.DOVIZ_KURU'),
		@DOVIZKURDEGERI = JSON_VALUE(@jsonData, '$.DOVIZKURDEGERI'),
		@KDVMUHAFIYETI = JSON_VALUE(@jsonData, '$.KDVMUHAFIYETI'),
		@EKLEYEN = JSON_VALUE(@jsonData, '$.EKLEYEN'),
		@SUBE = JSON_VALUE(@jsonData, '$.SUBE'),
		@ACIKLAMA = JSON_VALUE(@jsonData, '$.ACIKLAMA'),
		@OZELKOD_SATIR = JSON_VALUE(@jsonData, '$.OZELKOD'),
		@OZELKOD2_SATIR = JSON_VALUE(@jsonData, '$.OZELKOD2'),
		@KDVDURUM = JSON_VALUE(@jsonData, '$.KDVDURUM'),
		@DEPO = JSON_VALUE(@jsonData, '$.DEPO'),
		@LOTNO = JSON_VALUE(@jsonData, '$.LOTNO'),
		--@SERINO = JSON_VALUE(@jsonData, '$.SERINO'),
		@SKT = JSON_VALUE(@jsonData, '$.SKT')

	SET @SUBEID = ISNULL((SELECT ID FROM REHBER WHERE FIRMA = @SUBE AND ID < 0),0)
	SET @EKLEYEN = 2
	SET @EKLEMETARIHI = GETDATE()
	SET @SONUC_ID = 0
	SET @SONUC_MESAJ = '��lem ba�ar�s�z.'
	SET @YERI = 0

	SET @REHBERID = ISNULL(@REHBERID,0) -- NULLSA CAR� HESAP TUTULMAYAN TEDAR�K��

	DECLARE @FaturaDipToplam AS TABLE (
		   [FATBASID] int,
		   [TUR] float NULL,
		   [ACIKLAMA] VARCHAR(255) NULL,
		   [DEGER] FLOAT NULL,
		   [DOVIZTUTARI] FLOAT NULL,
		   [KUR] VARCHAR(5) NULL,
		   [DOVIZ_KURU] VARCHAR(5) NULL,
		   [DOVIZKUR] FLOAT NULL,
		   [KDVMUHAFIYETI] SMALLINT NULL,
		   [FATURADOVIZI] VARCHAR(5) NULL
	)

		SET @MASRAFID = ISNULL((SELECT ID FROM MASRAFGELIR WHERE KOD = @MASRAFKOD),0)
		SET @URUNID = ISNULL((SELECT ID FROM STOKLAR WHERE KOD = @URUNKOD),0)
		SET @TUR = CASE WHEN ISNULL(@URUNID,0) <> 0 THEN 1 ELSE 0 END -- Hizmet/Stok
		SET @BIRIMID = CASE WHEN ISNULL(@MASRAFID,0) <> 0 THEN 51 ELSE ISNULL((SELECT G.DEGER FROM GENINI G WHERE G.BOLUM = -2702 AND G.ANAHTAR = @BIRIM),0) END
		IF(NOT EXISTS(SELECT * FROM GENINI G WHERE G.BOLUM = -2702 AND G.ANAHTAR = @BIRIM) AND ISNULL(@BIRIMID,0) = 0)
		BEGIN
			INSERT INTO GENINI(BOLUM,ANAHTAR,DEGER,DIL,SIRA)
			SELECT -2702,@BIRIM,ISNULL((SELECT MAX(DEGER)+1 FROM GENINI WHERE BOLUM = -2702),1),-1,ISNULL((SELECT MAX(DEGER)+1 FROM GENINI WHERE BOLUM = -2702),1)
			SET @BIRIMID = (SELECT SCOPE_IDENTITY())
		END

		SET @OZELKOD_SATIR = CASE WHEN ISNULL(@MASRAFID,0) <> 0 THEN ISNULL((SELECT OZELKOD FROM MASRAFGELIR WHERE ID = @MASRAFID),0) ELSE ISNULL((SELECT OZELKOD FROM STOKLAR WHERE ID = @URUNID),0) END

		SET @ACIKLAMA = CASE WHEN ISNULL(@MASRAFID,0) <> 0 THEN ISNULL((SELECT ACIKLAMA FROM MASRAFGELIR WHERE ID = @MASRAFID),0) ELSE @ACIKLAMA END

		SET @DEPOID = ISNULL((SELECT GIRISDEPO FROM FATBASLIK WHERE ID = ((SELECT FATBASID FROM FATURA WHERE ID = @FATURADETAYID))),(SELECT ID FROM DEPOLAR D WHERE D.DEPOADI = @DEPO))

		IF(ISNULL(@LOTNO,'') <> '' AND NOT EXISTS(SELECT * FROM STOKSERILOT SL WHERE SL.STOKID = @URUNID AND ((ISNULL(@LOTNO,'') <> '' AND SL.LOTNO = @LOTNO))))
		BEGIN
			INSERT INTO STOKSERILOT (STOKID,LOTNO,SKT)
			SELECT @URUNID,@LOTNO,@SKT
			SET @SERILOTID = (SELECT SCOPE_IDENTITY())
			
		END
		IF((ISNULL(@LOTNO,'') <> '' ) AND EXISTS(SELECT * FROM STOKSERILOT SL WHERE SL.STOKID = @URUNID AND ((ISNULL(@LOTNO,'') <> '' AND SL.LOTNO = @LOTNO))))
		BEGIN
			SET @SERILOTID = (SELECT ID FROM STOKSERILOT SL WHERE STOKID = @URUNID AND ((ISNULL(@LOTNO,'') <> '' AND SL.LOTNO = @LOTNO)))
		END

    BEGIN TRY 
    -- Ekleme i�lemleri
    IF @TIP = 1
    BEGIN

		IF (ISNULL(@FATBASID,0) <> 0 AND EXISTS (SELECT ID FROM FATBASLIK WHERE ID = @FATBASID))	
		BEGIN
		    --SET @FATBASID = (SELECT ID FROM FATBASLIK WHERE GNTPID_GELISID = @GNTP_GELISLERID)
		    SET @TUTAR = (SELECT CASE  WHEN @KDVDURUM = 'Dahil' THEN (@BIRIMFIYAT*@ADET) / (1 + (@KDV / 100.0)) * (1 - (@ISKONTO / 100.0)) ELSE  @TUTAR END)
		    SET @BIRIMFIYAT = (SELECT CASE  WHEN @KDVDURUM = 'Dahil' THEN (@BIRIMFIYAT) / (1 + (@KDV / 100.0)) ELSE  @BIRIMFIYAT END)
		    SET @DOVIZ_TUTARI = (SELECT CASE WHEN @DOVIZ_KURU = 'TL' THEN @TUTAR ELSE @DOVIZ_TUTARI END)
		    SET @DOVIZ_BIRIMFIYAT = (SELECT CASE WHEN @DOVIZ_KURU = 'TL' THEN @BIRIMFIYAT ELSE @DOVIZ_BIRIMFIYAT END)

			SET @YERID = 0 -- (SELECT SD.ID FROM SIPARISDETAY SD WHERE SD.GNTPID = @GNTP_PARAID AND SD.REHBERID = @REHBERID)

		    INSERT INTO FATURA( FATBASID ,REHBERID, TUR, URUNID, ACIKLAMA, ADET, BIRIM, MIKTAR, BIRIMFIYAT, TUTAR, ISKONTO, KDV, MASRAFID, OZELKOD, KUR, DOVIZ_TUTARI, DOVIZ_KURU, ISKONTO2, DOVIZ_BIRIMFIYAT, DOVIZKURDEGERI,KDVMUHAFIYETI, EKLEYEN,  SUBEID, YERI,YERID,GIRDEPO,CIKDEPO,STOKDURUMDEGIS,IZLEME,IZLEMEKODU)
		    SELECT @FATBASID,@REHBERID, @TUR, CASE WHEN ISNULL(@URUNID,0) <> 0 THEN @URUNID ELSE @MASRAFID END, @ACIKLAMA, @ADET, @BIRIMID, @ADET, @BIRIMFIYAT , @TUTAR , ISNULL(@ISKONTO,0), @KDV, CASE WHEN ISNULL(@URUNID,0) = 0 THEN ISNULL(@MASRAFID,0) ELSE NULL END, @OZELKOD_SATIR, 'TL',  @DOVIZ_TUTARI, ISNULL(@DOVIZ_KURU,'TL'), 0, @DOVIZ_BIRIMFIYAT, ISNULL(@DOVIZKURDEGERI,1),ISNULL(@KDVMUHAFIYETI,0), @EKLEYEN, @SUBEID, @YERI,@YERID,@DEPOID,0,1,CASE WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') <> '' THEN 5 WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') = '' THEN 2 ELSE 0 END, ISNULL(@URUNNO,N'')

			SET @FATURADETAYID = (SELECT SCOPE_IDENTITY())

			IF(ISNULL(@SERILOTID,0)<>0)
			BEGIN
				INSERT INTO STOKIZLEME (STOKID,BELGETUR,BASLIKID,SATIRID,YER,YERID,KALAN,ADET,DONUSID,SERILOTID,IZLEMTUR)
				SELECT @URUNID,11,@FATBASID,@FATURADETAYID,0,0,@ADET,@ADET,0,@SERILOTID,CASE WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') <> '' THEN 5 WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') = '' THEN 2 ELSE 0 END

				SET @IZLEMID = (SELECT SCOPE_IDENTITY())

				INSERT INTO STOKIZLEMEDEPO
				SELECT @IZLEMID,@DEPOID,@ADET
			END

			INSERT INTO @FaturaDipToplam (TUR,ACIKLAMA,DEGER,DOVIZTUTARI,KUR,DOVIZ_KURU,DOVIZKUR,KDVMUHAFIYETI,FATURADOVIZI)
			EXEC SP_PRG_FaturaDipToplami @FATBASID

			UPDATE @FaturaDipToplam SET FATBASID = @FATBASID

			UPDATE FB SET 
				FB.FATURA_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Genel Toplam'),--(select SUM(F.KDVDAHILFIYAT) from FATURA F where FB.ID=F.FATBASID),
				FB.FATURA_MATRAHI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Ara Toplam'),--(select SUM(F.TUTAR) from FATURA F where FB.ID=F.FATBASID),
				FB.DOVIZ_TUTARI=(SELECT FB1.DOVIZTUTARI FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Genel Toplam'),--(select SUM(F.DOVIZ_TUTARI*(1 + (F.KDV / 100.0))) from FATURA F where FB.ID=F.FATBASID),
				FB.KDV_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'KDV Toplam')--(select SUM(F.KDVDAHILFIYAT-F.TUTAR) from FATURA F where FB.ID=F.FATBASID)  
			FROM 
				FATBASLIK FB INNER JOIN @FaturaDipToplam FB1 ON FB1.FATBASID = FB.ID
			WHERE 
				FB.ID = @FATBASID

				SET @SONUC_ID = 1
				SET @SONUC_MESAJ = '��lem ba�ar�l�.'
		END
		ELSE
		BEGIN
			SET @SONUC_ID = 12
			SET @SONUC_MESAJ = 'Bu kay�t daha �nce eklenmi�.XX'
		END
	END
    -- Silme i�lemleri (Di�er tablolar eklenecek sonras�nda)
    IF @TIP = 0
    BEGIN
		IF (ISNULL(@FATURADETAYID,0) <> 0)
		BEGIN
		SET @FATBASID  = (SELECT FATBASID FROM FATURA WHERE ID = @FATURADETAYID)

			DELETE FROM FATURA WHERE ID = @FATURADETAYID
			DELETE FROM STOKIZLEME WHERE SATIRID = @FATURADETAYID

			INSERT INTO @FaturaDipToplam (TUR,ACIKLAMA,DEGER,DOVIZTUTARI,KUR,DOVIZ_KURU,DOVIZKUR,KDVMUHAFIYETI,FATURADOVIZI)
			EXEC SP_PRG_FaturaDipToplami @FATBASID

			UPDATE @FaturaDipToplam SET FATBASID = @FATBASID

			UPDATE FB SET 
				FB.FATURA_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Genel Toplam'),--(select SUM(F.KDVDAHILFIYAT) from FATURA F where FB.ID=F.FATBASID),
				FB.FATURA_MATRAHI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Ara Toplam'),--(select SUM(F.TUTAR) from FATURA F where FB.ID=F.FATBASID),
				FB.DOVIZ_TUTARI=(SELECT FB1.DOVIZTUTARI FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Genel Toplam'),--(select SUM(F.DOVIZ_TUTARI*(1 + (F.KDV / 100.0))) from FATURA F where FB.ID=F.FATBASID),
				FB.KDV_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'KDV Toplam')--(select SUM(F.KDVDAHILFIYAT-F.TUTAR) from FATURA F where FB.ID=F.FATBASID)  
			FROM 
				FATBASLIK FB INNER JOIN @FaturaDipToplam FB1 ON FB1.FATBASID = FB.ID
			WHERE 
				FB.ID = @FATBASID
		END

		SET @SONUC_ID = 1
		SET @SONUC_MESAJ = '��lem ba�ar�l�.'
    END
    -- G�ncelleme i�lemleri
    IF @TIP = 2
    BEGIN

	    IF (ISNULL(@FATURADETAYID,0) <> 0)
	    BEGIN

		    SET @FATBASID = (SELECT FATBASID FROM FATURA WHERE ID = @FATURADETAYID)
		    SET @TUTAR = (SELECT CASE  WHEN @KDVDURUM = 'Dahil' THEN (@BIRIMFIYAT*@ADET) / (1 + (@KDV / 100.0)) * (1 - (@ISKONTO / 100.0)) ELSE  @TUTAR END)
		    SET @BIRIMFIYAT = (SELECT CASE  WHEN @KDVDURUM = 'Dahil' THEN (@BIRIMFIYAT) / (1 + (@KDV / 100.0)) ELSE  @BIRIMFIYAT END)
		    SET @DOVIZ_TUTARI = (SELECT CASE WHEN @DOVIZ_KURU = 'TL' THEN @TUTAR ELSE @DOVIZ_TUTARI END)
		    SET @DOVIZ_BIRIMFIYAT = (SELECT CASE WHEN @DOVIZ_KURU = 'TL' THEN @BIRIMFIYAT ELSE @DOVIZ_BIRIMFIYAT END)


			UPDATE FATURA SET 	
				ACIKLAMA=@ACIKLAMA, 
				ADET=@ADET,
				BIRIM=@BIRIMID, 
				MIKTAR=@ADET, 
				BIRIMFIYAT=@BIRIMFIYAT,
				TUTAR=@TUTAR,
				ISKONTO=ISNULL(@ISKONTO,0), 
				KDV=@KDV, 
				OZELKOD=@OZELKOD_SATIR, 
				KUR=@KUR,
				DOVIZ_TUTARI=@DOVIZ_TUTARI, 
				DOVIZ_KURU=ISNULL(@DOVIZ_KURU,'TL'),
				DOVIZ_BIRIMFIYAT= @DOVIZ_BIRIMFIYAT,
				DOVIZKURDEGERI=CASE WHEN ISNULL(@DOVIZKURDEGERI,0) <> 0 THEN @DOVIZKURDEGERI WHEN ISNULL(@DOVIZ_KURU,'TL')='TL' THEN 1 ELSE (SELECT TOP 1 SATIS FROM DOVIZ D WHERE CONVERT(DATE,D.TARIH,102)=CONVERT(DATE,GETDATE(),102) AND CINSI=@DOVIZ_KURU) END,
				KDVMUHAFIYETI = ISNULL(@KDVMUHAFIYETI,0),
				EKLEYEN=@EKLEYEN, 
				OZELKOD2=@OZELKOD2_SATIR,
				GIRDEPO = @DEPOID,
				CIKDEPO = 0,
				STOKDURUMDEGIS = 1,
				IZLEME = CASE WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') <> '' THEN 5 WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') = '' THEN 2 ELSE 0 END, IZLEMEKODU = ISNULL(@URUNNO,N'')
			WHERE 
				FATBASID = @FATBASID
				AND ID = @FATURADETAYID

			IF(ISNULL(@SERILOTID,0)<>0)
			BEGIN
				IF(NOT EXISTS(SELECT * FROM STOKIZLEME WHERE BASLIKID = @FATBASID AND SATIRID = @FATURADETAYID AND SERILOTID = @SERILOTID))				
				BEGIN
					INSERT INTO STOKIZLEME (STOKID,BELGETUR,BASLIKID,SATIRID,YER,YERID,KALAN,ADET,DONUSID,SERILOTID,IZLEMTUR)
					SELECT @URUNID,@TUR,@FATBASID,@FATURADETAYID,0,0,@ADET,@ADET,0,@SERILOTID,CASE WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') <> '' THEN 5 WHEN ISNULL(@LOTNO,'') <> '' AND ISNULL(@SKT,'') = '' THEN 2 ELSE 0 END

					SET @IZLEMID = (SELECT SCOPE_IDENTITY())

					INSERT INTO STOKIZLEMEDEPO
					SELECT @IZLEMID,@DEPOID,@ADET
				END
				IF(EXISTS(SELECT * FROM STOKIZLEME WHERE BASLIKID = @FATBASID AND SATIRID = @FATURADETAYID AND SERILOTID = @SERILOTID))
				BEGIN
					UPDATE STOKIZLEME SET SERILOTID = @SERILOTID,ADET = @ADET, KALAN = @ADET WHERE BASLIKID = @FATBASID AND SATIRID = @FATURADETAYID
					UPDATE SID SET DEPOID = @DEPOID, ADET = @ADET FROM STOKIZLEME SI INNER JOIN STOKIZLEMEDEPO SID ON SID.IZLEMID = SI.ID WHERE SI.BASLIKID = @FATBASID AND SI.SATIRID = @FATURADETAYID
				END
			END

			
			INSERT INTO @FaturaDipToplam (TUR,ACIKLAMA,DEGER,DOVIZTUTARI,KUR,DOVIZ_KURU,DOVIZKUR,KDVMUHAFIYETI,FATURADOVIZI)
			EXEC SP_PRG_FaturaDipToplami @FATBASID

			UPDATE @FaturaDipToplam SET FATBASID = @FATBASID

			UPDATE FB SET 
				FB.FATURA_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Genel Toplam'),--(select SUM(F.KDVDAHILFIYAT) from FATURA F where FB.ID=F.FATBASID),
				FB.FATURA_MATRAHI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Ara Toplam'),--(select SUM(F.TUTAR) from FATURA F where FB.ID=F.FATBASID),
				FB.DOVIZ_TUTARI=(SELECT FB1.DOVIZTUTARI FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'Genel Toplam'),--(select SUM(F.DOVIZ_TUTARI*(1 + (F.KDV / 100.0))) from FATURA F where FB.ID=F.FATBASID),
				FB.KDV_TUTARI=(SELECT FB1.DEGER FROM @FaturaDipToplam FB1 WHERE FB1.FATBASID = FB.ID AND FB1.ACIKLAMA = 'KDV Toplam')--(select SUM(F.KDVDAHILFIYAT-F.TUTAR) from FATURA F where FB.ID=F.FATBASID)  
			FROM 
				FATBASLIK FB INNER JOIN @FaturaDipToplam FB1 ON FB1.FATBASID = FB.ID
			WHERE 
				FB.ID = @FATBASID

			SET @SONUC_ID = 1
			SET @SONUC_MESAJ = '��lem ba�ar�l�.'
		END

		SET @SONUC_ID = 1
		SET @SONUC_MESAJ = '��lem ba�ar�l�.'

    END
    END TRY
    BEGIN CATCH
        SET @SONUC_ID = -2;
        SET @SONUC_MESAJ = ERROR_MESSAGE();
    END CATCH
END
GO


