CREATE OR ALTER PROC [dbo].[sp_Grnt_CariIslem](@jsonData NVARCHAR(MAX), @TIP INT, @SONUC_ID INT OUTPUT,@SONUC_MESAJ VARCHAR(5000) OUTPUT) 
AS 
BEGIN
    DECLARE
		@GNTPID INT,
		@REHBERID INT,
		@REHBERILETISIMID INT,
		@DURUM tinyint,
		@SUBEID smallint,
		@EKLEMETARIHI datetime,
		@KOD nvarchar(20),
		@FIRMA nvarchar(150),
		@GRUP smallint,
		@HESAPKODU nvarchar(100),
		@HESAPTURU nvarchar(100),
		@EKLEYEN int,
		@DTARIHI datetime,
		@CINSIYET nvarchar(100),
		@ULKETELKOD nvarchar(100),
		@ISTEL nvarchar(100),
		@ISTEL2 nvarchar(100),
		@FAKS nvarchar(100),
		@WEB nvarchar(100),
		@ADRES nvarchar(100),
		@PK nvarchar(100),
		@EVTEL nvarchar(100),
		@EPOSTA nvarchar(100),
		@CEPTEL nvarchar(100),
		@YABANCIULKETEL nvarchar(100),
		@ILCE nvarchar(100),
		@IL nvarchar(100),
		@ULKE nvarchar(100),
		@VNO nvarchar(100),
		@VD nvarchar(100),
		@FATURABASLIK nvarchar(200),
		@DOGUMYERIILCE nvarchar(100),
		@DOGUMYERIIL nvarchar(100),
		@UYRUK nvarchar(100), --UYRUK
		@DEPARTMAN nvarchar(100),
		@GOREV nvarchar(100),
		@ISEGIRISTARIHI datetime,
		@OGRDURUMU nvarchar(100),
		@DOGUMYERI int,
		@UYRUKID int,
		@OGRDURUMUID int,
		@ROLID int,
		@DEPARTMANID int,
		@GOREVID int,
		@UZMANLIK NVARCHAR(100),
		@HASTANE NVARCHAR(100),
		@ICSORUMLU NVARCHAR(100),
		@DISSORUMLU NVARCHAR(100),
		@ICSORUMLUREHBERID NVARCHAR(100),
		@DISSORUMLUREHBERID NVARCHAR(100),
		@SINIF INT,
		@KULLANICIKOD NVARCHAR(100),
		@OZELKOD NVARCHAR(100),
		@ILKTEMAS NVARCHAR(100),
		@ILKTEMASID INT

	SET @SUBEID = 0 -- ORTAK
	--SET @EKLEYEN = 2
	SET @EKLEMETARIHI = GETDATE()

	SET @SONUC_ID = 0
	SET @SONUC_MESAJ = 'İşlem Başarısız.'


	SELECT
		@GNTPID = JSON_VALUE(@jsonData, '$.ID'),
		@REHBERID = JSON_VALUE(@jsonData, '$.REHBERID'),
		@FIRMA = JSON_VALUE(@jsonData, '$.FIRMA'),
		--@GRUP = JSON_VALUE(@jsonData, '$.GRUP'),
		@HESAPTURU = JSON_VALUE(@jsonData, '$.HESAPTURU'),
		@EKLEYEN = JSON_VALUE(@jsonData, '$.EKLEYEN'),
		@EPOSTA = JSON_VALUE(@jsonData, '$.EPOSTA'),
		@CEPTEL = JSON_VALUE(@jsonData, '$.CEPTEL'),
		@DTARIHI = JSON_VALUE(@jsonData, '$.DTARIHI'),
		@CINSIYET = JSON_VALUE(@jsonData, '$.CINSIYET'),
		@YABANCIULKETEL = JSON_VALUE(@jsonData, '$.YABANCIULKETEL'),
		@ILCE = JSON_VALUE(@jsonData, '$.ILCE'),
		@IL = JSON_VALUE(@jsonData, '$.IL'),
		@ULKE = JSON_VALUE(@jsonData, '$.ULKE'),
		@ULKETELKOD = JSON_VALUE(@jsonData, '$.ULKETELKOD'),
		@ISTEL = JSON_VALUE(@jsonData, '$.ISTEL'),
		@ISTEL2 = JSON_VALUE(@jsonData, '$.ISTEL2'),
		@FAKS = JSON_VALUE(@jsonData, '$.FAKS'),
		@WEB = JSON_VALUE(@jsonData, '$.WEB'),
		@ADRES = JSON_VALUE(@jsonData, '$.ADRES'),
		@PK = JSON_VALUE(@jsonData, '$.PK'),
		@EVTEL = JSON_VALUE(@jsonData, '$.EVTEL'),
		@VNO = JSON_VALUE(@jsonData, '$.VNO'),
		@VD = JSON_VALUE(@jsonData, '$.VD'),
		@FATURABASLIK =JSON_VALUE(@jsonData, '$.FATURABASLIK'),
		@DOGUMYERIILCE = JSON_VALUE(@jsonData, '$.DOGUMYERIILCE'),
		@DOGUMYERIIL = JSON_VALUE(@jsonData, '$.DOGUMYERIIL'),
		@UYRUK = JSON_VALUE(@jsonData, '$.UYRUK'), --UYRUK
		@DEPARTMAN = JSON_VALUE(@jsonData, '$.DEPARTMAN'),
		@GOREV = JSON_VALUE(@jsonData, '$.GOREV'),
		@ISEGIRISTARIHI = JSON_VALUE(@jsonData, '$.ISEGIRISTARIHI'),
		@OGRDURUMU = JSON_VALUE(@jsonData, '$.OGRDURUMU'),
		@UZMANLIK = JSON_VALUE(@jsonData, '$.UZMANLIK'),
		@HASTANE = JSON_VALUE(@jsonData, '$.HASTANE'),
		@ICSORUMLU = JSON_VALUE(@jsonData, '$.ICSORUMLU'),
		@DISSORUMLU = JSON_VALUE(@jsonData, '$.DISSORUMLU'),
	    @KULLANICIKOD = JSON_VALUE(@jsonData, '$.KULLANICIKOD'),
		@DURUM = JSON_VALUE(@jsonData, '$.DURUM'),
		@OZELKOD = JSON_VALUE(@jsonData,'$.DOSYANO'),
		@ILKTEMAS = JSON_VALUE(@jsonData,'$.REFERANS')

    BEGIN TRY 

				DECLARE 
					@DIGITSAY INT,
					@SONKAYIT NVARCHAR(100),
					@SONKISIM NVARCHAR(100)

	SET @OGRDURUMUID = (SELECT DEGER FROM GENINI WHERE BOLUM = -2255 AND ANAHTAR = @OGRDURUMU)--gelen bilgi inide yoksa ekle
	IF(ISNULL(@OGRDURUMUID,0) = 0 AND ISNULL(@OGRDURUMU,'') <> '')
	BEGIN
		INSERT INTO GENINI
		SELECT -2255,@OGRDURUMU,(SELECT MAX(DEGER)+1 FROM GENINI WHERE BOLUM = -2255),-1,(SELECT MAX(SIRA)+1 FROM GENINI WHERE BOLUM = -2255)
		SET @OGRDURUMUID = (SELECT DEGER FROM GENINI WHERE BOLUM = -2255 AND ANAHTAR = @OGRDURUMU)
	END

	SET @ILKTEMASID = (SELECT DEGER FROM GENINI WHERE BOLUM = -2207 AND ANAHTAR = @ILKTEMAS)--gelen bilgi inide yoksa ekle
	IF(ISNULL(@ILKTEMASID,0) = 0 AND ISNULL(@ILKTEMAS,'') <> '')
	BEGIN
		INSERT INTO GENINI
		SELECT -2207,@ILKTEMAS,(SELECT MAX(DEGER)+1 FROM GENINI WHERE BOLUM = -2207),-1,(SELECT MAX(SIRA)+1 FROM GENINI WHERE BOLUM = -2207)
		SET @ILKTEMASID = (SELECT DEGER FROM GENINI WHERE BOLUM = -2207 AND ANAHTAR = @ILKTEMAS)
	END

	SET @HESAPKODU = ISNULL((SELECT HESAPKODU FROM HESAPPLANI WHERE ACIKLAMA = @HESAPTURU),1)

	SET @GRUP = CASE WHEN @HESAPTURU = 'GEN-POTANSIYEL' THEN '1' ELSE REVERSE( SUBSTRING(REVERSE(@HESAPKODU),CHARINDEX('.',REVERSE (@HESAPKODU),1)+1,LEN(@HESAPKODU)-(CHARINDEX('.',REVERSE(@HESAPKODU),1)-1))) END
	
	SET @DURUM = ISNULL(@DURUM,1)

	IF (@GRUP = 335)
	BEGIN
		SET @DEPARTMANID = (SELECT DEGER FROM GENINI WHERE BOLUM = -2251 AND ANAHTAR = @DEPARTMAN)
		SET @GOREVID = (SELECT DEGER FROM GENINI WHERE BOLUM = -2252 AND ANAHTAR = @GOREV)
		IF (ISNULL(@GOREVID,0) = 0)
		BEGIN
			INSERT INTO GENINI
			SELECT -2252,@GOREV,(SELECT MAX(DEGER)+1 FROM GENINI WHERE BOLUM = -2252),-1,(SELECT MAX(SIRA)+1 FROM GENINI WHERE BOLUM = -2252)
		END

		IF (ISNULL(@DEPARTMAN,'') <> '' AND ISNULL(@GOREV,'') <> '')
		BEGIN
			SET @ROLID = (SELECT ID FROM ROLLER WHERE DEPARTMAN = @DEPARTMANID AND GOREVID = @GOREVID)
			IF(ISNULL(@ROLID,0) = 0)
			BEGIN
				INSERT INTO ROLLER (DURUM,EKLEYEN,EKLEMETARIHI,SUBEID,TY,DEPARTMAN,GOREVID)
				SELECT 1,2,GETDATE(),@SUBEID,1,@DEPARTMANID,@GOREVID
			END
		END
		IF (ISNULL(@DEPARTMAN,'') <> '' AND ISNULL(@GOREV,'') = '')
		BEGIN
			SET @ROLID = (SELECT TOP 1 ID FROM ROLLER WHERE DEPARTMAN = @DEPARTMANID)
		END
		IF (ISNULL(@DEPARTMAN,'') = '' AND ISNULL(@GOREV,'') <> '')
		BEGIN
			SET @ROLID = (SELECT TOP 1 ID FROM ROLLER WHERE  GOREVID = @GOREVID)
		END
	END

	IF (ISNULL(@DOGUMYERIILCE,'') <> '' AND ISNULL(@DOGUMYERIIL,'') <> '')
	BEGIN
	SET @DOGUMYERI = (select TOP 1 ILCENO from ILILCE where  ILADI like '%'+@DOGUMYERIIL+'%' AND ILCEADI like '%'+@DOGUMYERIILCE+'%')

	END
	ELSE IF (ISNULL(@DOGUMYERIILCE,'') = '' AND ISNULL(@DOGUMYERIIL,'') <> '')
	BEGIN
	SET @DOGUMYERI = (select TOP 1 ILCENO from ILILCE where  ILADI like '%'+@DOGUMYERIIL+'%' AND ILCEADI IS NULL)
	END
	ELSE IF (ISNULL(@DOGUMYERIILCE,'') <> '' AND ISNULL(@DOGUMYERIIL,'') = '')
	BEGIN
	SET @DOGUMYERI = (select TOP 1 ILCENO from ILILCE where ILCEADI like '%'+@DOGUMYERIILCE+'%')
	END
	ELSE
	BEGIN
		SET @DOGUMYERI = NULL
	END
	
	SET @UYRUKID = CASE WHEN ISNULL(@UYRUK,'') <> '' THEN (select TOP 1 ILNO from ILLER where ILNO > 100 and ILADI like '%'+@UYRUK+'%'  ORDER BY 1) ELSE NULL END

	SET @SINIF = CASE 
					WHEN @HESAPTURU = 'GEN-HASTA' THEN (SELECT DEGER FROM GENINI WHERE BOLUM = -2203 AND ANAHTAR = 'HASTA') 
					WHEN @HESAPTURU = 'GEN-DOKTOR' THEN (SELECT DEGER FROM GENINI WHERE BOLUM = -2203 AND ANAHTAR = 'DIŞ DOKTOR')
					WHEN @HESAPTURU = 'GEN-KURUM' THEN (SELECT DEGER FROM GENINI WHERE BOLUM = -2203 AND ANAHTAR = 'ANLAŞMALI KURUM') 
					ELSE NULL 
				END	

    -- Ekleme işlemleri
    IF @TIP = 1
    BEGIN
		IF ((ISNULL(@GNTPID,'') <> '' AND ISNULL(@HESAPKODU,'') <> '') OR (@HESAPTURU = 'GEN-POTANSIYEL'))
		BEGIN
			IF (@HESAPTURU <> 'GEN-POTANSIYEL' AND NOT EXISTS (SELECT ID FROM REHBER WHERE GNTPID = @GNTPID AND KOD LIKE @HESAPKODU+'%' )) OR (@HESAPTURU = 'GEN-POTANSIYEL' AND NOT EXISTS (SELECT R.ID FROM REHBER R INNER JOIN REHBERILETISIM RI ON RI.REHBERID = R.ID INNER JOIN REHBERBILGI RB ON RB.YERI = 1 AND RB.YER_ID = RI.ID AND RB.ETIKET = 'Cep Tel' AND RB.BILGI = @CEPTEL WHERE FIRMA = @FIRMA AND GRUP = 1 ))
			BEGIN
			 --set @SONUC_ID = 99


				SET @DIGITSAY = (Select isnull(DIGITSAY,2) as DIGITSAY from HESAPPLANI where HESAPKODU= @HESAPKODU)
				SET @SONKAYIT  = (Select TOP 1 R.KOD from REHBER R where KOD like @HESAPKODU+'%' and LEN(CASE WHEN ISNULL(CHARINDEX('.',KOD),0)<1 THEN KOD ELSE  REVERSE( SUBSTRING(REVERSE(KOD),1,CHARINDEX('.',REVERSE(KOD),1)-1)) END) >= @DIGITSAY order by LEN(R.KOD) desc , 1 desc)
				SET @SONKISIM = SUBSTRING(@SONKAYIT, LEN(@HESAPKODU) + 2, LEN(@SONKAYIT) - LEN(@HESAPKODU) - 1)

				SET @KOD = CASE WHEN @HESAPTURU = 'GEN-POTANSIYEL' THEN CAST(ISNULL((SELECT MAX(ID)+1 FROM REHBER R),1) AS nvarchar) ELSE CASE WHEN @SONKAYIT IS NULL THEN @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + '1', @DIGITSAY) ELSE  @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + CAST(CAST(@SONKISIM AS INT) + 1 AS NVARCHAR), @DIGITSAY) END END

				

				INSERT INTO REHBER (KOD, FIRMA, GRUP, SINIF, DURUM, EKLEYEN, EKLEMETARIHI, SUBEID, GNTPID,DTARIH,STATU,BOLGE,ALTBOLGE,KATEGORI,OZELKOD,TEMAS) 
				SELECT 
					@KOD, @FIRMA, @GRUP, CASE WHEN @GRUP = 335 THEN @ROLID ELSE @SINIF END, @DURUM, @EKLEYEN, @EKLEMETARIHI, @SUBEID, @GNTPID, @DTARIHI, 
					CASE WHEN @GRUP = 335 THEN CASE WHEN ISNULL(@CINSIYET,'') = '' THEN NULL WHEN @CINSIYET = 'KADIN' THEN 0 WHEN @CINSIYET = 'ERKEK' THEN 1 ELSE 2 END ELSE NULL END AS CINSIYET,
					CASE WHEN @GRUP = 335 THEN @DOGUMYERI ELSE NULL END AS [BOLGE/DOGUMYERI],
					CASE WHEN @GRUP = 335 THEN @UYRUKID ELSE NULL END AS [ALTBOLGE/UYRUK],
					CASE WHEN @GRUP = 335 THEN @OGRDURUMUID ELSE NULL END,
					@OZELKOD,
					@ILKTEMASID


				SET @REHBERID = (SELECT SCOPE_IDENTITY())

				INSERT INTO REHBERILETISIM (REHBERID, AD, VARSAYILAN, AKTIF, EKLEYEN, EKLEMETARIHI, SUBEID)
				SELECT @REHBERID, 'Merkez', 1, @DURUM, @EKLEYEN, GETDATE(), @SUBEID

				SET @REHBERILETISIMID = (SELECT SCOPE_IDENTITY())

				INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN,SUBEID) 
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Eposta'),'Eposta',@EPOSTA,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Cep Tel'),'Cep Tel',@CEPTEL,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Doğum Tarihi'),'Doğum Tarihi',CONVERT(VARCHAR(10),@DTARIHI,104),@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Cinsiyet'),'Cinsiyet',@CINSIYET,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Yabancı Ülke Tel'),'Yabancı Ülke Tel',@YABANCIULKETEL,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İlçe'),'İlçe',@ILCE,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İl'),'İl',@IL,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Ülke'),'Ülke',@ULKE,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Ülke Tel Kod'),'Ülke Tel Kod',@ULKETELKOD,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İş Tel'),'İş Tel',@ISTEL,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İş Tel 2'),'İş Tel 2',@ISTEL2,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Faks'),'Faks',@FAKS,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Web'),'Web',@WEB,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Adres'),'Adres',@ADRES,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'PK'),'PK',@PK,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Ev Tel'),'Ev Tel',@EVTEL,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Uzmanlık'),'Uzmanlık',@UZMANLIK,@EKLEYEN,@SUBEID
				UNION
				SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Hastane'),'Hastane',@HASTANE,@EKLEYEN,@SUBEID

				--IF(NOT EXISTS(SELECT * FROM REHBERBILGI WHERE YERI = 1 AND YER_ID = @REHBERILETISIMID))
				--BEGIN
				--	SELECT @SONUC = 'Yeni cari kaydı oluşturuldu. İletişim bilgileri oluşturulamadı. ID :'+CONVERT(VARCHAR(10),@REHBERID) + ' Kod :'+@KOD

				--END

				INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN,SUBEID) 
				SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Vergi Dairesi'),'Vergi Dairesi',@VD,@EKLEYEN,@SUBEID
				UNION
				SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Vergi No'),'Vergi No',@VNO,@EKLEYEN,@SUBEID
				UNION
				SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Fatura Başlığı'),'Fatura Başlığı',@FATURABASLIK,@EKLEYEN,@SUBEID


				--Personel bilgilerin eklenmesi


				IF (@HESAPTURU = 'GEN-PERSONEL')
				BEGIN
					IF(ISNULL(@VNO,'') <> '')
					BEGIN
						INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN,SUBEID) 
						SELECT 3,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 3 AND ETIKET = 'T.C.Kmlik No'),'T.C.Kmlik No',@VNO,@EKLEYEN,@SUBEID
					END
					IF (ISNULL(@ISEGIRISTARIHI,'') <> '')
					BEGIN
						INSERT INTO PERS_HAREKET (REHBERID,TARIH,TUR) VALUES(@REHBERID,@ISEGIRISTARIHI,1)
					END
					INSERT INTO KULLANICI (REHBERID,SIFRE,KOD,ROLID,DURUM,EKLEYEN,EKLEMETARIHI,SUBEID,DIL)
					SELECT @REHBERID,'AA',@KULLANICIKOD,@ROLID,@DURUM,@EKLEYEN,@EKLEMETARIHI,@SUBEID,NULL

				END				
				--Sorumlu
				IF (@HESAPTURU = 'GEN-DOKTOR')
				BEGIN
					SET @DISSORUMLUREHBERID = ISNULL((SELECT ID FROM REHBER WHERE GRUP = 335 AND FIRMA = @DISSORUMLU),0)
					--SET @ICSORUMLUREHBERID = (SELECT ID FROM REHBER WHERE GRUP = 335 AND FIRMA = @ICSORUMLU)
					IF (ISNULL(@DISSORUMLUREHBERID,0) = 0)
					BEGIN

						SET @HESAPKODU = (SELECT HESAPKODU FROM HESAPPLANI WHERE ACIKLAMA = 'GEN-PERSONEL')
						SET @DIGITSAY = (Select isnull(DIGITSAY,2) as DIGITSAY from HESAPPLANI where HESAPKODU= @HESAPKODU)
						SET @SONKAYIT  = (Select TOP 1 R.KOD from REHBER R where KOD like @HESAPKODU+'%' and LEN(CASE WHEN ISNULL(CHARINDEX('.',KOD),0)<1 THEN KOD ELSE  REVERSE( SUBSTRING(REVERSE(KOD),1,CHARINDEX('.',REVERSE(KOD),1)-1)) END) >= @DIGITSAY order by LEN(R.KOD) desc , 1 desc)
						SET @SONKISIM = SUBSTRING(@SONKAYIT, LEN(@HESAPKODU) + 2, LEN(@SONKAYIT) - LEN(@HESAPKODU) - 1)

						SET @KOD = CASE WHEN @SONKAYIT IS NULL THEN @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + '1', @DIGITSAY) ELSE  @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + CAST(CAST(@SONKISIM AS INT) + 1 AS NVARCHAR), @DIGITSAY) END
						SET @GRUP = REVERSE( SUBSTRING(REVERSE(@HESAPKODU),CHARINDEX('.',REVERSE (@HESAPKODU),1)+1,LEN(@HESAPKODU)-(CHARINDEX('.',REVERSE(@HESAPKODU),1)-1)))


						INSERT INTO REHBER (KOD, FIRMA, GRUP, SINIF, DURUM, EKLEYEN, EKLEMETARIHI, SUBEID, GNTPID) 
						SELECT 
							@KOD, @DISSORUMLU, @GRUP, NULL, @DURUM, @EKLEYEN, @EKLEMETARIHI, @SUBEID, (SELECT R.SIRANO FROM GEN2005..REHBERINI R WHERE BOLUM = 'SORUMLU' AND ANAHTAR = @DISSORUMLU)

						SET @DISSORUMLUREHBERID = (SELECT SCOPE_IDENTITY())

						INSERT INTO REHBERILETISIM (REHBERID, AD, VARSAYILAN, AKTIF, EKLEYEN, EKLEMETARIHI, SUBEID)
						SELECT @DISSORUMLUREHBERID, 'Merkez', 1, @DURUM, @EKLEYEN, GETDATE(), @SUBEID
					END

					UPDATE REHBER SET TEMSILCI = @DISSORUMLUREHBERID WHERE ID = @REHBERID

					--IF (ISNULL(@ICSORUMLUREHBERID,0) = 0)
					--BEGIN

					--	SET @HESAPKODU = (SELECT HESAPKODU FROM HESAPPLANI WHERE ACIKLAMA = 'GEN-PERSONEL')
					--	SET @DIGITSAY = (Select isnull(DIGITSAY,2) as DIGITSAY from HESAPPLANI where HESAPKODU= @HESAPKODU)
					--	SET @SONKAYIT  = (Select TOP 1 R.KOD from REHBER R where KOD like @HESAPKODU+'%' and LEN(CASE WHEN ISNULL(CHARINDEX('.',KOD),0)<1 THEN KOD ELSE  REVERSE( SUBSTRING(REVERSE(KOD),1,CHARINDEX('.',REVERSE(KOD),1)-1)) END) >= @DIGITSAY order by LEN(R.KOD) desc , 1 desc)
					--	SET @SONKISIM = SUBSTRING(@SONKAYIT, LEN(@HESAPKODU) + 2, LEN(@SONKAYIT) - LEN(@HESAPKODU) - 1)

					--	SET @KOD = CASE WHEN @SONKAYIT IS NULL THEN @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + '1', @DIGITSAY) ELSE  @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + CAST(CAST(@SONKISIM AS INT) + 1 AS NVARCHAR), @DIGITSAY) END
					--	SET @GRUP = REVERSE( SUBSTRING(REVERSE(@HESAPKODU),CHARINDEX('.',REVERSE (@HESAPKODU),1)+1,LEN(@HESAPKODU)-(CHARINDEX('.',REVERSE(@HESAPKODU),1)-1)))

					--	INSERT INTO REHBER (KOD, FIRMA, GRUP, SINIF, DURUM, EKLEYEN, EKLEMETARIHI, SUBEID, GNTPID,DTARIH,STATU,BOLGE,ALTBOLGE,KATEGORI) 
					--	SELECT 
					--		@KOD, @ICSORUMLU, @GRUP, NULL, @DURUM, @EKLEYEN, @EKLEMETARIHI, @SUBEID, R.SIRANO FROM GEN2005..REHBERINI R WHERE BOLUM = 'ICSORUMLU' AND ANAHTAR = @ICSORUMLU

					--	SET @ICSORUMLUREHBERID = (SELECT SCOPE_IDENTITY())

					--	INSERT INTO REHBERILETISIM (REHBERID, AD, VARSAYILAN, AKTIF, EKLEYEN, EKLEMETARIHI, SUBEID)
					--	SELECT @ICSORUMLUREHBERID, 'Merkez', 1, @DURUM, @EKLEYEN, GETDATE(), @SUBEID
					--	END


					END

				SET @SONUC_ID = 1
				SET @SONUC_MESAJ = 'Kayıt eklendi.'

			END
			ELSE
			BEGIN
				
				SET @SONUC_ID = 0
				SET @SONUC_MESAJ = 'Bu kayıt daha önce eklenmiş.'
			END
		END
		ELSE
		BEGIN
			SET @SONUC_ID = 0
			SET @SONUC_MESAJ = 'ID/Hesap kodu boş olamaz.'
		END
	END

    -- Silme işlemleri (Diğer tablolar eklenecek sonrasında)
    IF @TIP = 0
    BEGIN

		DELETE FROM REHBERBILGI WHERE YER_ID = @REHBERID AND YERI = 2
		DELETE FROM REHBERBILGI WHERE YER_ID IN (SELECT ID FROM REHBERILETISIM WHERE REHBERID = @REHBERID) AND YERI = 1
		DELETE FROM REHBERILETISIM WHERE REHBERID = @REHBERID
		DELETE FROM PERS_HAREKET WHERE REHBERID = @REHBERID
		DELETE FROM KULLANICI WHERE REHBERID = @REHBERID
		DELETE FROM REHBER WHERE ID = @REHBERID
		SET @SONUC_ID = 1
		SET @SONUC_MESAJ = 'Kayıt silindi.'
    END

    -- Güncelleme işlemleri
    IF @TIP = 2
    BEGIN
		SET @REHBERILETISIMID = (SELECT ID FROM REHBERILETISIM WHERE REHBERID = @REHBERID)
		SET @GRUP = (SELECT GRUP FROM REHBER WHERE ID = @REHBERID)
		SET @GNTPID = (SELECT GNTPID FROM REHBER WHERE ID = @REHBERID)

		UPDATE REHBER SET FIRMA = @FIRMA, DEGISTIREN = @EKLEYEN, DEGISTIRMETARIHI = GETDATE(), SINIF =CASE WHEN @GRUP = 335 THEN @ROLID ELSE @SINIF END, TEMAS = @ILKTEMASID WHERE ID = @REHBERID
		IF(@GRUP = '335')
		BEGIN
			UPDATE 
				REHBER 
			SET 
				DTARIH = @DTARIHI, 
				STATU = CASE WHEN @GRUP = 335 THEN CASE WHEN ISNULL(@CINSIYET,'') = '' THEN NULL WHEN @CINSIYET = 'KADIN' THEN 0 WHEN @CINSIYET = 'ERKEK' THEN 1 ELSE 2 END ELSE NULL END, 
				BOLGE = CASE WHEN @GRUP = 335 THEN @DOGUMYERI ELSE NULL END, 
				ALTBOLGE = CASE WHEN @GRUP = 335 THEN @UYRUKID ELSE NULL END, 
				KATEGORI = CASE WHEN @GRUP = 335 THEN @OGRDURUMUID ELSE NULL END 
			WHERE 
				ID = @REHBERID
		END

		UPDATE REHBERBILGI SET BILGI=@EPOSTA WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Eposta'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Eposta'),'Eposta',@EPOSTA,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@CEPTEL WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Cep Tel'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Cep Tel'),'Cep Tel',@CEPTEL,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=CONVERT(VARCHAR(10),@DTARIHI,104) WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Doğum Tarihi'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Doğum Tarihi'),'Doğum Tarihi',CONVERT(VARCHAR(10),@DTARIHI,104),@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@CINSIYET WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Cinsiyet'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Cinsiyet'),'Cinsiyet',@CINSIYET,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@YABANCIULKETEL WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Yabancı Ülke Tel'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Yabancı Ülke Tel'),'Yabancı Ülke Tel',@YABANCIULKETEL,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@ILCE WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'İlçe'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İlçe'),'İlçe',@ILCE,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@IL WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'İl'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İl'),'İl',@IL,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@ULKE WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Ülke'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Ülke'),'Ülke',@ULKE,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@ULKETELKOD WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Ülke Tel Kod'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Ülke Tel Kod'),'Ülke Tel Kod',@ULKETELKOD,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@ISTEL WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'İş Tel'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İş Tel'),'İş Tel',@ISTEL,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@ISTEL2 WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'İş Tel 2'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'İş Tel 2'),'İş Tel 2',@ISTEL2,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@FAKS WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Faks'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Faks'),'Faks',@FAKS,@EKLEYEN
		END		
		UPDATE REHBERBILGI SET BILGI=@WEB WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Web'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Web'),'Web',@WEB,@EKLEYEN
		END		
		UPDATE REHBERBILGI SET BILGI=@ADRES WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Adres'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Adres'),'Adres',@ADRES,@EKLEYEN
		END				
		UPDATE REHBERBILGI SET BILGI=@PK WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'PK'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'PK'),'PK',@PK,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@EVTEL WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Ev Tel'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Ev Tel'),'Ev Tel',@EVTEL,@EKLEYEN
		END
		--UPDATE SIPARIS SET HASTATCKN = @VNO WHERE GNTP_KIMLIKID = @GNTPID
		UPDATE REHBERBILGI SET BILGI=@VD WHERE YER_ID=@REHBERID AND YERI = 2 AND ETIKET = 'Vergi Dairesi'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Vergi Dairesi'),'Vergi Dairesi',@VD,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@UZMANLIK WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Uzmanlık'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Uzmanlık'),'Uzmanlık',@UZMANLIK,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@HASTANE WHERE YER_ID=@REHBERILETISIMID AND YERI = 1 AND ETIKET = 'Hastane'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 1,@REHBERILETISIMID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 1 AND ETIKET = 'Hastane'),'Hastane',@HASTANE,@EKLEYEN
		END
		UPDATE REHBERBILGI SET BILGI=@FATURABASLIK WHERE YER_ID=@REHBERID AND YERI = 2 AND ETIKET = 'Fatura Başlığı'
		IF @@ROWCOUNT=0  
		BEGIN 
			INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
			SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Fatura Başlığı'),'Fatura Başlığı',ISNULL(@FATURABASLIK,@FIRMA),@EKLEYEN
		END
		IF(ISNULL(@DISSORUMLU,'') <> '')
		BEGIN

			SET @DISSORUMLUREHBERID = ISNULL((SELECT TOP 1 ID FROM REHBER WHERE GRUP = 335 AND FIRMA = @DISSORUMLU),0)
			--SET @ICSORUMLUREHBERID = (SELECT ID FROM REHBER WHERE GRUP = 335 AND FIRMA = @ICSORUMLU)
			IF (ISNULL(@DISSORUMLUREHBERID,0) = 0)
			BEGIN

				SET @HESAPKODU = (SELECT HESAPKODU FROM HESAPPLANI WHERE ACIKLAMA = 'GEN-PERSONEL')
				SET @DIGITSAY = (Select isnull(DIGITSAY,2) as DIGITSAY from HESAPPLANI where HESAPKODU= @HESAPKODU)
				SET @SONKAYIT  = (Select TOP 1 R.KOD from REHBER R where KOD like @HESAPKODU+'%' and LEN(CASE WHEN ISNULL(CHARINDEX('.',KOD),0)<1 THEN KOD ELSE  REVERSE( SUBSTRING(REVERSE(KOD),1,CHARINDEX('.',REVERSE(KOD),1)-1)) END) >= @DIGITSAY order by LEN(R.KOD) desc , 1 desc)
				SET @SONKISIM = SUBSTRING(@SONKAYIT, LEN(@HESAPKODU) + 2, LEN(@SONKAYIT) - LEN(@HESAPKODU) - 1)

				SET @KOD = CASE WHEN @SONKAYIT IS NULL THEN @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + '1', @DIGITSAY) ELSE  @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + CAST(CAST(@SONKISIM AS INT) + 1 AS NVARCHAR), @DIGITSAY) END
				SET @GRUP = REVERSE( SUBSTRING(REVERSE(@HESAPKODU),CHARINDEX('.',REVERSE (@HESAPKODU),1)+1,LEN(@HESAPKODU)-(CHARINDEX('.',REVERSE(@HESAPKODU),1)-1)))

				INSERT INTO REHBER (KOD, FIRMA, GRUP, SINIF, DURUM, EKLEYEN, EKLEMETARIHI, SUBEID, GNTPID) 
				SELECT 
					@KOD, @DISSORUMLU, @GRUP, NULL, @DURUM, @EKLEYEN, @EKLEMETARIHI, @SUBEID,(SELECT R.SIRANO FROM GEN2005..REHBERINI R WHERE BOLUM = 'SORUMLU' AND ANAHTAR = @DISSORUMLU)

				SET @DISSORUMLUREHBERID = (SELECT SCOPE_IDENTITY())

				INSERT INTO REHBERILETISIM (REHBERID, AD, VARSAYILAN, AKTIF, EKLEYEN, EKLEMETARIHI, SUBEID)
				SELECT @DISSORUMLUREHBERID, 'Merkez', 1, @DURUM, @EKLEYEN, GETDATE(), @SUBEID
				END

			--IF (ISNULL(@ICSORUMLUREHBERID,0) = 0)
			--BEGIN

			--	SET @HESAPKODU = (SELECT HESAPKODU FROM HESAPPLANI WHERE ACIKLAMA = 'GEN-PERSONEL')
			--	SET @DIGITSAY = (Select isnull(DIGITSAY,2) as DIGITSAY from HESAPPLANI where HESAPKODU= @HESAPKODU)
			--	SET @SONKAYIT  = (Select TOP 1 R.KOD from REHBER R where KOD like @HESAPKODU+'%' and LEN(CASE WHEN ISNULL(CHARINDEX('.',KOD),0)<1 THEN KOD ELSE  REVERSE( SUBSTRING(REVERSE(KOD),1,CHARINDEX('.',REVERSE(KOD),1)-1)) END) >= @DIGITSAY order by LEN(R.KOD) desc , 1 desc)
			--	SET @SONKISIM = SUBSTRING(@SONKAYIT, LEN(@HESAPKODU) + 2, LEN(@SONKAYIT) - LEN(@HESAPKODU) - 1)

			--	SET @KOD = CASE WHEN @SONKAYIT IS NULL THEN @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + '1', @DIGITSAY) ELSE  @HESAPKODU + '.' + RIGHT(REPLICATE('0', @DIGITSAY) + CAST(CAST(@SONKISIM AS INT) + 1 AS NVARCHAR), @DIGITSAY) END
			--	SET @GRUP = REVERSE( SUBSTRING(REVERSE(@HESAPKODU),CHARINDEX('.',REVERSE (@HESAPKODU),1)+1,LEN(@HESAPKODU)-(CHARINDEX('.',REVERSE(@HESAPKODU),1)-1)))

			--	INSERT INTO REHBER (KOD, FIRMA, GRUP, SINIF, DURUM, EKLEYEN, EKLEMETARIHI, SUBEID, GNTPID,DTARIH,STATU,BOLGE,ALTBOLGE,KATEGORI) 
			--	SELECT 
			--		@KOD, @ICSORUMLU, @GRUP, NULL, @DURUM, @EKLEYEN, @EKLEMETARIHI, @SUBEID, R.SIRANO FROM GEN2005..REHBERINI R WHERE BOLUM = 'ICSORUMLU' AND ANAHTAR = @ICSORUMLU

			--	SET @ICSORUMLUREHBERID = (SELECT SCOPE_IDENTITY())

			--	INSERT INTO REHBERILETISIM (REHBERID, AD, VARSAYILAN, AKTIF, EKLEYEN, EKLEMETARIHI, SUBEID)
			--	SELECT @ICSORUMLUREHBERID, 'Merkez', 1, @DURUM, @EKLEYEN, GETDATE(), @SUBEID
			--	END

				UPDATE REHBER SET TEMSILCI = @DISSORUMLUREHBERID WHERE ID = @REHBERID
		END

		IF (@GRUP = '335')
		BEGIN 
			UPDATE REHBERBILGI SET BILGI=@VNO WHERE YER_ID=@REHBERID AND YERI = 3 AND ETIKET = 'T.C.Kmlik No'
			IF @@ROWCOUNT=0  
			BEGIN 
				INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
				SELECT 3,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 3 AND ETIKET = 'T.C.Kmlik No'),'T.C.Kmlik No',@VNO,@EKLEYEN
			END
			UPDATE PERS_HAREKET SET TARIH = @ISEGIRISTARIHI WHERE REHBERID = @REHBERID	
			UPDATE KULLANICI SET ROLID = @ROLID, DURUM = @DURUM, KOD = @KULLANICIKOD WHERE REHBERID = @REHBERID
		END
		IF (@GRUP <> '335')
		BEGIN
			UPDATE REHBERBILGI SET BILGI=@VNO WHERE YER_ID=@REHBERID AND YERI = 2 AND ETIKET = 'Vergi No'
			IF @@ROWCOUNT=0  
			BEGIN 
				INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
				SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Vergi No'),'Vergi No',@VNO,@EKLEYEN
			END
			UPDATE REHBERBILGI SET BILGI=ISNULL(@FATURABASLIK,@FIRMA) WHERE YER_ID=@REHBERID AND YERI = 2 AND ETIKET = 'Fatura Başlığı'
			IF @@ROWCOUNT=0  
			BEGIN 
				INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
				SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Fatura Başlığı'),'Fatura Başlığı',ISNULL(@FATURABASLIK,@FIRMA),@EKLEYEN
			END
			--IF NOT EXISTS(SELECT * FROM REHBERBILGI WHERE YERI = 2 AND YER_ID = @REHBERID AND ETIKET = 'Fatura Başlığı')
			--BEGIN
			--	INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN,SUBEID) 
			--	SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Fatura Başlığı'),'Fatura Başlığı',@FATURABASLIK,@EKLEYEN,@SUBEID
			--END
			ELSE
			BEGIN
				UPDATE REHBERBILGI SET BILGI=ISNULL(@FATURABASLIK,@FIRMA) WHERE YER_ID=@REHBERID AND YERI = 2 AND ETIKET = 'Fatura Başlığı'
				IF @@ROWCOUNT=0  
				BEGIN 
					INSERT INTO REHBERBILGI (YERI,YER_ID,SIRA,ETIKET,BILGI,EKLEYEN) 
					SELECT 2,@REHBERID,(SELECT SIRA FROM REHBERAYAR WHERE YERI = 2 AND ETIKET = 'Fatura Başlığı'),'Fatura Başlığı',ISNULL(@FATURABASLIK,@FIRMA),@EKLEYEN
				END
			END
		END

		SET @SONUC_ID = 1
		SET @SONUC_MESAJ = 'Kayıt güncellendi.'
		
    END	
	
	SET @SONUC_ID = 1
	SET @SONUC_MESAJ = 'İşlem başarılı'

  END TRY
    BEGIN CATCH
        -- Hata oluşursa
		
        SET @SONUC_ID = -2;
        SET @SONUC_MESAJ = ERROR_MESSAGE();


    END CATCH


END
GO


