SET NOCOUNT ON;
DECLARE @Kul INT = (SELECT TOP 1 REHBERID FROM dbo.KULLANICI WHERE ISNULL(DURUM,0)=1 ORDER BY REHBERID);
DECLARE @J NVARCHAR(200) = N'{"KulId":' + CAST(@Kul AS NVARCHAR(12)) + N'}';
CREATE TABLE #k (KANALID INT, TUR INT, ADI NVARCHAR(200), KARSIID INT, RESIMVAR INT, GRUPDOSYAID INT,
 UYESAYISI INT, UYELER NVARCHAR(MAX), SONMESAJ NVARCHAR(200), SONGONDEREN NVARCHAR(200),
 SONTARIH DATETIME2(0), OKUNMAMIS INT, BILDIRIM INT, YONETICI INT, FAVORI INT);
INSERT #k EXEC dbo.sp_Prog_Mesaj_Kanal_Liste_Json2 @Kosullar=@J;
SELECT sohbet_sayisi = COUNT(*), bos_birebir = SUM(CASE WHEN TUR=1 AND SONTARIH IS NULL THEN 1 ELSE 0 END) FROM #k;
DROP TABLE #k;
