-- MenuTasnifDisinaTasi sifirlama alanlari FATBASLIK'ta var mi?
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FATBASLIK'
  AND COLUMN_NAME IN ('FATURA_MATRAHI','KDV_TUTARI','FATURA_TUTARI','DOVIZ_TUTARI')
ORDER BY COLUMN_NAME;
