-- ============================================================
-- GENDEPO kurulum + gecis (Faz 2: e-Belge)
-- EBELGE, EBELGEMESAJ, EBELGEKUYRUK -> ayni instance'ta 2. DB "GENDEPO".
-- Ana DB'de ayni isimli SYNONYM birakir (kod/SP degismeden calisir).
-- Orijinaller <T>_YEDEK olarak saklanir (geri donus icin).
--
-- * Idempotent: tekrar calistirilabilir (guardli).
-- * ps1 (SqlDataAdapter, GO yok) ile uyumlu: her sey tek batch + EXEC (dinamik).
-- * Ana DB adindan bagimsiz (kaynak = mevcut DB). Simdilik hedef adi sabit 'GENDEPO';
--   ileride GENINI'den okunacak.
-- ! ONCE YEDEK AL, mesai disi calistir. CREATE DATABASE tran'a alinamaz.
-- ============================================================
SET NOCOUNT ON;
SET XACT_ABORT ON;

-- 1) GENDEPO veritabani (ayni instance)
IF DB_ID('GENDEPO') IS NULL EXEC('CREATE DATABASE [GENDEPO]');

-- 2) 3 tabloyu yapi + identity + veri ile kopyala (yoksa). Kaynak = mevcut ana DB.
IF OBJECT_ID('GENDEPO.dbo.EBELGE') IS NULL
    EXEC('SELECT * INTO GENDEPO.dbo.EBELGE       FROM dbo.EBELGE');
IF OBJECT_ID('GENDEPO.dbo.EBELGEMESAJ') IS NULL
    EXEC('SELECT * INTO GENDEPO.dbo.EBELGEMESAJ  FROM dbo.EBELGEMESAJ');
IF OBJECT_ID('GENDEPO.dbo.EBELGEKUYRUK') IS NULL
    EXEC('SELECT * INTO GENDEPO.dbo.EBELGEKUYRUK FROM dbo.EBELGEKUYRUK');

-- 3) GENDEPO icinde PK / index / default / FK (guardli). USE dinamik EXEC ile scope'lu.
EXEC('USE GENDEPO;
-- ---- EBELGE ----
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGE'') AND type=''PK'')
  ALTER TABLE dbo.EBELGE ADD CONSTRAINT PK_EBELGE PRIMARY KEY CLUSTERED (ID);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''UX_EBELGE_UUID'' AND object_id=OBJECT_ID(''dbo.EBELGE''))
  CREATE UNIQUE INDEX UX_EBELGE_UUID ON dbo.EBELGE(UUID) WHERE UUID IS NOT NULL;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_EBELGE_FATBASLIKID'' AND object_id=OBJECT_ID(''dbo.EBELGE''))
  CREATE INDEX IX_EBELGE_FATBASLIKID ON dbo.EBELGE(FATBASLIKID);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_EBELGE_LISTE'' AND object_id=OBJECT_ID(''dbo.EBELGE''))
  CREATE INDEX IX_EBELGE_LISTE ON dbo.EBELGE(YON,BELGETURU,DURUM);
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGE'') AND COL_NAME(parent_object_id,parent_column_id)=''DURUM'')
  ALTER TABLE dbo.EBELGE ADD CONSTRAINT DF_EBELGE_DURUM DEFAULT((0)) FOR DURUM;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGE'') AND COL_NAME(parent_object_id,parent_column_id)=''EKLEMETARIHI'')
  ALTER TABLE dbo.EBELGE ADD CONSTRAINT DF_EBELGE_EKLEMETARIHI DEFAULT(GETDATE()) FOR EKLEMETARIHI;
-- ---- EBELGEMESAJ ----
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEMESAJ'') AND type=''PK'')
  ALTER TABLE dbo.EBELGEMESAJ ADD CONSTRAINT PK_EBELGEMESAJ PRIMARY KEY CLUSTERED (ID);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_EBELGEHAREKET_EBELGEID'' AND object_id=OBJECT_ID(''dbo.EBELGEMESAJ''))
  CREATE INDEX IX_EBELGEHAREKET_EBELGEID ON dbo.EBELGEMESAJ(EBELGEID, EKLEMETARIHI DESC);
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEMESAJ'') AND COL_NAME(parent_object_id,parent_column_id)=''MESAJTIPI'')
  ALTER TABLE dbo.EBELGEMESAJ ADD CONSTRAINT DF_EBELGEMESAJ_MESAJTIPI DEFAULT((0)) FOR MESAJTIPI;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEMESAJ'') AND COL_NAME(parent_object_id,parent_column_id)=''EKLEMETARIHI'')
  ALTER TABLE dbo.EBELGEMESAJ ADD CONSTRAINT DF_EBELGEMESAJ_EKLEMETARIHI DEFAULT(GETDATE()) FOR EKLEMETARIHI;
-- ---- EBELGEKUYRUK ----
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEKUYRUK'') AND type=''PK'')
  ALTER TABLE dbo.EBELGEKUYRUK ADD CONSTRAINT PK_BELGEKUYRUK PRIMARY KEY CLUSTERED (ID);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''IX_EBELGEKUYRUK_AKTIF'' AND object_id=OBJECT_ID(''dbo.EBELGEKUYRUK''))
  CREATE INDEX IX_EBELGEKUYRUK_AKTIF ON dbo.EBELGEKUYRUK(DURUM,SONRAKI_DENEME_TARIHI,ONCELIK,ID)
    INCLUDE(EBELGEID,FATBASLIKID,ISLEMTURU,BELGETURU,YON);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''UX_EBELGEKUYRUK_AKTIF_IS'' AND object_id=OBJECT_ID(''dbo.EBELGEKUYRUK''))
  CREATE UNIQUE INDEX UX_EBELGEKUYRUK_AKTIF_IS ON dbo.EBELGEKUYRUK(EBELGEID,ISLEMTURU) WHERE DURUM IN (0,1,9);
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEKUYRUK'') AND COL_NAME(parent_object_id,parent_column_id)=''DURUM'')
  ALTER TABLE dbo.EBELGEKUYRUK ADD CONSTRAINT DF_EBELGEKUYRUK_DURUM DEFAULT((0)) FOR DURUM;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEKUYRUK'') AND COL_NAME(parent_object_id,parent_column_id)=''ONCELIK'')
  ALTER TABLE dbo.EBELGEKUYRUK ADD CONSTRAINT DF_EBELGEKUYRUK_ONCELIK DEFAULT((5)) FOR ONCELIK;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEKUYRUK'') AND COL_NAME(parent_object_id,parent_column_id)=''DENEME_SAYISI'')
  ALTER TABLE dbo.EBELGEKUYRUK ADD CONSTRAINT DF_EBELGEKUYRUK_DENEME DEFAULT((0)) FOR DENEME_SAYISI;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(''dbo.EBELGEKUYRUK'') AND COL_NAME(parent_object_id,parent_column_id)=''EKLEMETARIHI'')
  ALTER TABLE dbo.EBELGEKUYRUK ADD CONSTRAINT DF_EBELGEKUYRUK_EKLEMETARIHI DEFAULT(GETDATE()) FOR EKLEMETARIHI;
-- ---- FK''lar (GENDEPO ici) ----
IF OBJECT_ID(''dbo.FK_EBELGEHAREKET_EBELGE'') IS NULL
  ALTER TABLE dbo.EBELGEMESAJ  WITH CHECK ADD CONSTRAINT FK_EBELGEHAREKET_EBELGE FOREIGN KEY(EBELGEID) REFERENCES dbo.EBELGE(ID);
IF OBJECT_ID(''dbo.FK_BELGEKUYRUK_EBELGE'') IS NULL
  ALTER TABLE dbo.EBELGEKUYRUK WITH CHECK ADD CONSTRAINT FK_BELGEKUYRUK_EBELGE FOREIGN KEY(EBELGEID) REFERENCES dbo.EBELGE(ID);
');

-- 4) GECIS: ana DB''de FK''lari dusur, orijinalleri yedekle, SYNONYM yarat.
--    Yalnizca EBELGE hala GERCEK TABLO ise (synonym degilse) calisir -> idempotent.
IF OBJECT_ID('dbo.EBELGE','U') IS NOT NULL
   AND OBJECT_ID('GENDEPO.dbo.EBELGE') IS NOT NULL
BEGIN
    IF OBJECT_ID('dbo.FK_BELGEKUYRUK_EBELGE') IS NOT NULL
        ALTER TABLE dbo.EBELGEKUYRUK DROP CONSTRAINT FK_BELGEKUYRUK_EBELGE;
    IF OBJECT_ID('dbo.FK_EBELGEHAREKET_EBELGE') IS NOT NULL
        ALTER TABLE dbo.EBELGEMESAJ DROP CONSTRAINT FK_EBELGEHAREKET_EBELGE;

    EXEC sp_rename 'dbo.EBELGEKUYRUK', 'EBELGEKUYRUK_YEDEK';
    EXEC sp_rename 'dbo.EBELGEMESAJ',  'EBELGEMESAJ_YEDEK';
    EXEC sp_rename 'dbo.EBELGE',       'EBELGE_YEDEK';

    CREATE SYNONYM dbo.EBELGE       FOR GENDEPO.dbo.EBELGE;
    CREATE SYNONYM dbo.EBELGEMESAJ  FOR GENDEPO.dbo.EBELGEMESAJ;
    CREATE SYNONYM dbo.EBELGEKUYRUK FOR GENDEPO.dbo.EBELGEKUYRUK;
END

-- 5) DOGRULAMA
SELECT ASAMA='SATIR', TABLO='EBELGE',
       ANA_YEDEK=(SELECT COUNT(*) FROM dbo.EBELGE_YEDEK),
       GENDEPO=(SELECT COUNT(*) FROM GENDEPO.dbo.EBELGE)
UNION ALL SELECT 'SATIR','EBELGEMESAJ',
       (SELECT COUNT(*) FROM dbo.EBELGEMESAJ_YEDEK),
       (SELECT COUNT(*) FROM GENDEPO.dbo.EBELGEMESAJ)
UNION ALL SELECT 'SATIR','EBELGEKUYRUK',
       (SELECT COUNT(*) FROM dbo.EBELGEKUYRUK_YEDEK),
       (SELECT COUNT(*) FROM GENDEPO.dbo.EBELGEKUYRUK);

SELECT NESNE=name, TUR=CASE WHEN type='SN' THEN 'SYNONYM' ELSE type_desc END
FROM sys.objects WHERE name IN ('EBELGE','EBELGEMESAJ','EBELGEKUYRUK') AND type='SN';
