SET NOCOUNT ON;
SET XACT_ABORT ON;
DECLARE @id INT = 114001;   -- TUR=4 cikis fisi, 3 satir, 4 izlem
DECLARE @depo sysname = dbo.fn_Api_DepoDBAdi();
DECLARE @lt sysname = N'LOG' + CAST(YEAR(GETDATE()) AS varchar(4));

SELECT 'ONCE' AS x,
  (SELECT COUNT(*) FROM FATBASLIK WHERE ID=@id) AS Baslik,
  (SELECT COUNT(*) FROM FATURA WHERE FATBASID=@id) AS Satir,
  (SELECT COUNT(*) FROM STOKIZLEME WHERE BASLIKID=@id) AS Izlem,
  (SELECT COUNT(*) FROM STOKIZLEMEDEPO WHERE IZLEMID IN (SELECT ID FROM STOKIZLEME WHERE BASLIKID=@id)) AS IzlemDepo,
  (SELECT COUNT(*) FROM KASA WHERE TUR IN (61,71) AND FATURAID=@id) AS Kasa;

BEGIN TRAN;   -- test: sonunda GERI ALINACAK

DECLARE @j NVARCHAR(MAX) = N'{"BelgeId":' + CAST(@id AS varchar(20)) +
     N',"KilitKaldirildi":false,"Oturum":{"KulId":9,"SubeId":-1,"Ip":"1.2.3.4","Istasyon":"SILTEST"}}';
EXEC dbo.sp_Api_Belge_Sil_Json @j;

SELECT 'SONRA (tran ici)' AS x,
  (SELECT COUNT(*) FROM FATBASLIK WHERE ID=@id) AS Baslik,
  (SELECT COUNT(*) FROM FATURA WHERE FATBASID=@id) AS Satir,
  (SELECT COUNT(*) FROM STOKIZLEME WHERE BASLIKID=@id) AS Izlem,
  (SELECT COUNT(*) FROM STOKIZLEMEDEPO WHERE IZLEMID IN (SELECT ID FROM STOKIZLEME WHERE BASLIKID=@id)) AS IzlemDepo,
  (SELECT COUNT(*) FROM KASA WHERE TUR IN (61,71) AND FATURAID=@id) AS Kasa;

DECLARE @s NVARCHAR(MAX) = N'
SELECT ''YAZILAN LOGLAR'' AS x, TABLOID, COUNT(*) AS Adet, MIN(ID) AS IlkId, MAX(ID) AS SonId
FROM [' + @depo + N'].dbo.' + @lt + N' WHERE ISTASYON=''SILTEST'' GROUP BY TABLOID ORDER BY MIN(ID);
SELECT ''LOG SIRASI'' AS y, ID, TABLOID, KAYITID, USTTABLOID, USTKAYITID
FROM [' + @depo + N'].dbo.' + @lt + N' WHERE ISTASYON=''SILTEST'' ORDER BY ID;';
EXEC sp_executesql @s;

ROLLBACK;   -- her sey geri alinir (loglar dahil)

SELECT 'ROLLBACK SONRASI' AS x,
  (SELECT COUNT(*) FROM FATBASLIK WHERE ID=@id) AS Baslik,
  (SELECT COUNT(*) FROM FATURA WHERE FATBASID=@id) AS Satir,
  (SELECT COUNT(*) FROM STOKIZLEME WHERE BASLIKID=@id) AS Izlem;
DECLARE @s2 NVARCHAR(MAX) = N'SELECT ''KALAN TEST LOGU'' AS x, COUNT(*) AS Adet FROM [' + @depo + N'].dbo.' + @lt + N' WHERE ISTASYON=''SILTEST'';';
EXEC sp_executesql @s2;
