SET NOCOUNT ON;
DECLARE @FATBASID INT = 114127;
SELECT 'FATBASLIK' T, ID, TUR, FATURANO, FATURATARIH, REHBERID, DURUM, GIRISDEPO, CIKISDEPO
  FROM FATBASLIK WHERE ID=@FATBASID;
SELECT 'FATURA' T, ID, URUNID, ADET, MIKTAR, BIRIMFIYAT, TUTAR, IZLEME, EKIPMANID, YERI, YERID
  FROM FATURA WHERE FATBASID=@FATBASID ORDER BY ID;
SELECT 'STOKIZLEME' T, ID, BASLIKID, SATIRID, STOKID, SERILOTID, ADET, KALAN, DONUSID, IZLEMTUR, BELGETUR
  FROM STOKIZLEME WHERE BASLIKID=@FATBASID ORDER BY ID;
SELECT 'STOKIZLEMEDEPO' T, IZLEMID, DEPOID, ADET
  FROM STOKIZLEMEDEPO WHERE IZLEMID IN (SELECT ID FROM STOKIZLEME WHERE BASLIKID=@FATBASID) ORDER BY IZLEMID, DEPOID;
SELECT 'STOKDURUM' T, STOKID, DEPOID, GIREN, CIKAN, KALAN
  FROM STOKDURUM WHERE STOKID IN (SELECT URUNID FROM FATURA WHERE FATBASID=@FATBASID) ORDER BY STOKID, DEPOID;
SELECT 'STOKDURUMIZLEME' T, STOKID, DEPOID, SERILOTID, KALAN
  FROM STOKDURUMIZLEME WHERE STOKID IN (SELECT URUNID FROM FATURA WHERE FATBASID=@FATBASID) ORDER BY STOKID, SERILOTID, DEPOID;
