SET NOCOUNT ON;
DECLARE @ID INT = 1046;
SELECT 'TEKLIF' T, ID, TEKLIFNO, REHBERID, DURUM, PROJEID FROM TEKLIF WHERE ID=@ID;
SELECT 'TEKLIFDETAY' T, ID, TEKLIFID, URUNID, ADET, BIRIMFIYAT, TUTAR FROM TEKLIFDETAY WHERE TEKLIFID=@ID ORDER BY ID;
SELECT 'TEKLIF_USER' T, * FROM TEKLIF_USER WHERE ID=@ID;
SELECT 'IMAJ80' T, ID, YERI, YER_ID, BELGEADI FROM IMAJ WHERE YERI=80 AND YER_ID=@ID ORDER BY ID;
SELECT 'GOREVYORUM' T, ID, TUR, GOREVID, EKLEYEN FROM GOREVYORUM WHERE TUR=97 AND GOREVID=@ID ORDER BY ID;
SELECT 'DOKUMAN' T, ID, MODUL, MODULID, AD FROM DOKUMAN
  WHERE MODUL=210 AND MODULID IN (SELECT ID FROM GOREVYORUM WHERE TUR=97 AND GOREVID=@ID) ORDER BY ID;
SELECT 'LOG' T, COUNT(*) N FROM BILIM_GENDEPO.dbo.ISLEMLOG WHERE USTKAYITID=@ID AND USTTABLOID=97;
