CREATE TRIGGER [dbo].[trg_FATBASLIK_DOKTOR]
ON [dbo].[FATBASLIK]
AFTER INSERT,UPDATE
AS
BEGIN
    SET NOCOUNT ON;

	DECLARE 
		@FATBASID INT,
		@ID INT,
		@YERID INT,
		@YERI INT,
		@TUR INT,
		@DOKTOR NVARCHAR(100),
		@HASTA NVARCHAR(100),
		@KIMLIK_TUR NVARCHAR(100),
		@KIMLIK_NO NVARCHAR(100),
		@KURUM NVARCHAR(100),
		@ISLEMNO NVARCHAR(100),
		@OPTARIHI DATETIME,
		@PROTOKOLNO NVARCHAR(100),
		@HISNO NVARCHAR(100),
		@IHALETALEPNO NVARCHAR(100),
		@DOSYANO NVARCHAR(100),
		@REHBER_KOD NVARCHAR(50)

	SELECT TOP 1
		@DOKTOR = FB.DOKTOR,
		@HASTA = FB.HASTA,
		@KIMLIK_TUR = FB.KIMLIK_TUR,
		@KIMLIK_NO = FB.KIMLIK_NO,
		@KURUM = FB.KURUM,
		@ISLEMNO = FB.ISLEMNO,
		@OPTARIHI = FB.OPERASYONTARIHI,
		@PROTOKOLNO = FB.PROTOKOLNO,
		@HISNO = FB.HISNO,
		@IHALETALEPNO = FB.IHALETALEPNO,
		@DOSYANO = FB.DOSYANO,
		@FATBASID = FB.ID,
		@ID = F.ID,
		@YERID = F.YERID,
		@YERI = F.YERI,
		@TUR = FB.TUR
	FROM
		inserted FB
			INNER JOIN FATURA F ON F.FATBASID = FB.ID

	SET @REHBER_KOD = (SELECT KOD FROM REHBER WHERE FIRMA = @KURUM)

	IF (@TUR IN (14) AND ISNULL(@KURUM,'') <> '')
	BEGIN
		UPDATE FATBASLIK SET KURUM_KOD = @REHBER_KOD WHERE ID = @FATBASID
	END

	IF(@TUR IN (15,16) AND ISNULL(@YERI,0) IN (411,424))
	BEGIN
		IF (ISNULL(@DOKTOR,'') = '')
		BEGIN
			SET @DOKTOR  = (SELECT FB.DOKTOR FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET DOKTOR = @DOKTOR WHERE ID = @FATBASID
		END

		IF (ISNULL(@HASTA,'') = '')
		BEGIN
			SET @HASTA  = (SELECT FB.HASTA FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET HASTA = @HASTA WHERE ID = @FATBASID
		END

		IF (ISNULL(@KIMLIK_TUR,'') = '')
		BEGIN
			SET @KIMLIK_TUR  = (SELECT FB.KIMLIK_TUR FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET KIMLIK_TUR = @KIMLIK_TUR WHERE ID = @FATBASID
		END

		IF (ISNULL(@KIMLIK_NO,'') = '')
		BEGIN
			SET @KIMLIK_NO  = (SELECT FB.KIMLIK_NO FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET KIMLIK_NO = @KIMLIK_NO WHERE ID = @FATBASID
		END

		IF (ISNULL(@REHBER_KOD,'') = '')
		BEGIN
			SET @REHBER_KOD  = (SELECT FB.KURUM_KOD FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET KURUM_KOD = @REHBER_KOD WHERE ID = @FATBASID
		END

		IF (ISNULL(@KURUM,'') = '')
		BEGIN
			SET @KURUM  = (SELECT FB.KURUM FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET KURUM = @KURUM WHERE ID = @FATBASID
		END

		IF (ISNULL(@ISLEMNO,'') = '')
		BEGIN
			SET @ISLEMNO  = (SELECT FB.ISLEMNO FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET ISLEMNO = @ISLEMNO WHERE ID = @FATBASID
		END

		IF (ISNULL(@OPTARIHI,'') = '')
		BEGIN
			SET @OPTARIHI  = (SELECT FB.OPERASYONTARIHI FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET OPERASYONTARIHI = @OPTARIHI WHERE ID = @FATBASID
		END

		IF (ISNULL(@PROTOKOLNO,'') = '')
		BEGIN
			SET @PROTOKOLNO  = (SELECT FB.PROTOKOLNO FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET PROTOKOLNO = @PROTOKOLNO WHERE ID = @FATBASID
		END

		IF (ISNULL(@HISNO,'') = '')
		BEGIN
			SET @HISNO  = (SELECT FB.HISNO FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET HISNO = @HISNO WHERE ID = @FATBASID
		END

		IF (ISNULL(@IHALETALEPNO,'') = '')
		BEGIN
			SET @IHALETALEPNO  = (SELECT FB.IHALETALEPNO FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET IHALETALEPNO = @IHALETALEPNO WHERE ID = @FATBASID
		END

		IF (ISNULL(@DOSYANO,'') = '')
		BEGIN
			SET @DOSYANO  = (SELECT FB.DOSYANO FROM FATBASLIK FB INNER JOIN FATURA F ON F.FATBASID = FB.ID WHERE F.ID = @YERID)
			UPDATE FATBASLIK SET DOSYANO = @DOSYANO WHERE ID = @FATBASID
		END

	END

END
