object HizliGirisOdemeTipiDlg: THizliGirisOdemeTipiDlg
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'HizliGirisOdemeTipiDlg'
  ClientHeight = 271
  ClientWidth = 228
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  OnKeyUp = FormKeyUp
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 228
    Height = 271
    Align = alClient
    BevelInner = bvLowered
    BevelKind = bkSoft
    TabOrder = 0
    object BtnOdemeYok: TJvNavPanelButton
      Left = 2
      Top = 226
      Width = 220
      Height = 39
      Align = alBottom
      AllowAllUp = True
      Caption = #304'ptal                      [Esc]'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 1
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = 15395562
      Colors.ButtonColorTo = 12566463
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 1
      OnClick = BtnOdemeYokClick
      ExplicitLeft = 15
      ExplicitTop = 209
      ExplicitWidth = 193
    end
    object LblOnay: TcxLabel
      Left = 20
      Top = 21
      Caption = #304'ade i'#231'in '#246'deme t'#252'r'#252' se'#231'iniz.'
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -16
      Style.Font.Name = 'Trebuchet MS'
      Style.Font.Style = []
      Style.TextColor = clGreen
      Style.TextStyle = []
      Style.TransparentBorder = True
      Style.IsFontAssigned = True
      Properties.WordWrap = True
      Transparent = True
      OnKeyUp = FormKeyUp
      Width = 157
    end
    object Panel2: TPanel
      Left = 2
      Top = 82
      Width = 220
      Height = 144
      Align = alBottom
      TabOrder = 1
      object BtnNakit: TJvNavPanelButton
        Left = 1
        Top = 1
        Width = 218
        Height = 39
        Align = alTop
        AllowAllUp = True
        Caption = 'Nakit                     [Ent]'
        Font.Charset = TURKISH_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        GroupIndex = 1
        HotTrack = False
        HotTrackFont.Charset = TURKISH_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -13
        HotTrackFont.Name = 'Trebuchet MS'
        HotTrackFont.Style = [fsBold]
        ParentFont = False
        WordWrap = True
        Colors.ButtonColorFrom = 15395562
        Colors.ButtonColorTo = 12566463
        Colors.ButtonHotColorFrom = 14256961
        Colors.ButtonHotColorTo = 11694645
        Colors.ButtonSelectedColorFrom = 14256961
        Colors.ButtonSelectedColorTo = 11694645
        ParentStyleManager = False
        ImageIndex = 10
        OnClick = BtnNakitClick
        ExplicitLeft = -8
        ExplicitTop = 66
        ExplicitWidth = 193
      end
      object BtnKK: TJvNavPanelButton
        Left = 1
        Top = 79
        Width = 218
        Height = 39
        Align = alTop
        AllowAllUp = True
        Caption = 'KK                         [F4]'
        Font.Charset = TURKISH_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        GroupIndex = 1
        HotTrack = False
        HotTrackFont.Charset = TURKISH_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -13
        HotTrackFont.Name = 'Trebuchet MS'
        HotTrackFont.Style = [fsBold]
        ParentFont = False
        WordWrap = True
        Colors.ButtonColorFrom = 15395562
        Colors.ButtonColorTo = 12566463
        Colors.ButtonHotColorFrom = 14256961
        Colors.ButtonHotColorTo = 11694645
        Colors.ButtonSelectedColorFrom = 14256961
        Colors.ButtonSelectedColorTo = 11694645
        ParentStyleManager = False
        ImageIndex = 12
        OnClick = BtnKKClick
        ExplicitLeft = -8
        ExplicitTop = 75
        ExplicitWidth = 193
      end
      object BtnIC: TJvNavPanelButton
        Left = 1
        Top = 40
        Width = 218
        Height = 39
        Align = alTop
        AllowAllUp = True
        Caption = #304'ade '#199'eki               [F5]'
        Font.Charset = TURKISH_CHARSET
        Font.Color = clBlack
        Font.Height = -13
        Font.Name = 'Trebuchet MS'
        Font.Style = [fsBold]
        GroupIndex = 1
        HotTrack = False
        HotTrackFont.Charset = TURKISH_CHARSET
        HotTrackFont.Color = clWindowText
        HotTrackFont.Height = -13
        HotTrackFont.Name = 'Trebuchet MS'
        HotTrackFont.Style = [fsBold]
        ParentFont = False
        WordWrap = True
        Colors.ButtonColorFrom = 15395562
        Colors.ButtonColorTo = 12566463
        Colors.ButtonHotColorFrom = 14256961
        Colors.ButtonHotColorTo = 11694645
        Colors.ButtonSelectedColorFrom = 14256961
        Colors.ButtonSelectedColorTo = 11694645
        ParentStyleManager = False
        ImageIndex = 32
        OnClick = BtnICClick
        ExplicitTop = 52
        ExplicitWidth = 193
      end
    end
  end
end
