object HizliGirisGenelTahsilatlarDlg: THizliGirisGenelTahsilatlarDlg
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'HizliGirisGenelTahsilatlarDlg'
  ClientHeight = 389
  ClientWidth = 440
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 440
    Height = 389
    Align = alClient
    BevelInner = bvLowered
    BevelKind = bkSoft
    TabOrder = 0
    ExplicitWidth = 490
    ExplicitHeight = 387
    object Panel3: TPanel
      Left = 2
      Top = 313
      Width = 432
      Height = 70
      Align = alBottom
      TabOrder = 0
      ExplicitTop = 311
      ExplicitWidth = 482
      object BtnSecimiSil: TJvExpressButton
        Left = 1
        Top = 1
        Width = 75
        Height = 68
        Align = alLeft
        Caption = 'Se'#231'imi Sil'
        FillColor = 15395562
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        HighlightFont.Charset = DEFAULT_CHARSET
        HighlightFont.Color = clWindowText
        HighlightFont.Height = -11
        HighlightFont.Name = 'Tahoma'
        HighlightFont.Style = []
        ImageIndex = 1
        LargeImages = HizliGirisDlg.cxImageList1
        OnClick = BtnSecimiSilClick
        ExplicitLeft = 41
        ExplicitTop = -3
        ExplicitHeight = 73
      end
      object BtnTumunuSil: TJvExpressButton
        Left = 76
        Top = 1
        Width = 75
        Height = 68
        Align = alLeft
        Caption = 'T'#252'm'#252'n'#252' Sil'
        FillColor = 15395562
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        HighlightFont.Charset = DEFAULT_CHARSET
        HighlightFont.Color = clWindowText
        HighlightFont.Height = -11
        HighlightFont.Name = 'Tahoma'
        HighlightFont.Style = []
        ImageIndex = 2
        LargeImages = HizliGirisDlg.cxImageList1
        OnClick = BtnTumunuSilClick
        ExplicitLeft = 117
        ExplicitTop = -3
        ExplicitHeight = 73
      end
    end
    object Panel2: TPanel
      Left = 2
      Top = 2
      Width = 432
      Height = 25
      Align = alTop
      Caption = 'Tahsilat Bilgileri D'#252'zenleme'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clMoneyGreen
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      ExplicitLeft = -107
      ExplicitTop = 47
      ExplicitWidth = 444
      object BtnKapat: TcxButton
        Left = 405
        Top = 1
        Width = 24
        Height = 23
        ParentCustomHint = False
        BiDiMode = bdLeftToRight
        Cancel = True
        Caption = 'X'
        Colors.Default = clRed
        Colors.DefaultText = clWhite
        Colors.Normal = clRed
        Colors.NormalText = clBlack
        Colors.Hot = clMaroon
        Colors.HotText = clWhite
        Colors.Pressed = clMaroon
        Colors.PressedText = clWhite
        Colors.Disabled = clRed
        Colors.DisabledText = clWhite
        ModalResult = 2
        ParentBiDiMode = False
        ParentShowHint = False
        ShowHint = False
        TabOrder = 0
        TabStop = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWhite
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        OnClick = BtnKapatClick
      end
    end
    object cxGridTahsilatlar: TcxGrid
      Left = 2
      Top = 27
      Width = 432
      Height = 286
      Align = alClient
      TabOrder = 2
      TabStop = False
      ExplicitWidth = 482
      ExplicitHeight = 284
      object cxGridTahsilatlarDBCardView1: TcxGridDBCardView
        NavigatorButtons.ConfirmDelete = False
        DataController.DataSource = HizliGirisDlg.DtsTahDetay
        DataController.Summary.DefaultGroupSummaryItems = <>
        DataController.Summary.FooterSummaryItems = <>
        DataController.Summary.SummaryGroups = <>
        OptionsData.Deleting = False
        OptionsData.DeletingConfirmation = False
        OptionsData.Editing = False
        OptionsData.Inserting = False
        OptionsSelection.CellSelect = False
        OptionsSelection.HideFocusRectOnExit = False
        object cxGridTahsilatlarDBCardView1TUR: TcxGridDBCardViewRow
          Caption = 'T'#252'r'
          DataBinding.FieldName = 'TUR'
          RepositoryItem = Tablo.RepKasaTurleriReadOnly
          Position.BeginsLayer = True
        end
        object cxGridTahsilatlarDBCardView1HESAPID: TcxGridDBCardViewRow
          Caption = 'Detay'
          DataBinding.FieldName = 'HESAPID'
          OnGetDisplayText = cxGridTahsilatlarDBCardView1HESAPIDGetDisplayText
          Position.BeginsLayer = True
        end
        object cxGridTahsilatlarDBCardView1TUTAR: TcxGridDBCardViewRow
          Caption = 'Tutar'
          DataBinding.FieldName = 'TUTAR'
          RepositoryItem = Tablo.cxEditRepository1CurrencyItem1
          Position.BeginsLayer = True
          Position.Width = 200
        end
        object cxGridTahsilatlarDBCardView1KUR: TcxGridDBCardViewRow
          DataBinding.FieldName = 'KUR'
          RepositoryItem = Tablo.cxEditRepository1ComboBoxItemKurlar
          Options.ShowCaption = False
          Position.BeginsLayer = False
        end
      end
      object cxGridTahsilatlarLevel1: TcxGridLevel
        GridView = cxGridTahsilatlarDBCardView1
      end
    end
  end
end
