object KullaniciGirisDlg: TKullaniciGirisDlg
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  Caption = 'Kullan'#305'c'#305' Giri'#351
  ClientHeight = 289
  ClientWidth = 512
  Color = clBtnFace
  Font.Charset = TURKISH_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Trebuchet MS'
  Font.Style = []
  Position = poScreenCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnKeyUp = FormKeyUp
  OnShow = FormShow
  TextHeight = 16
  object PanelKey: TPanel
    Left = 340
    Top = 0
    Width = 172
    Height = 289
    Align = alRight
    BevelInner = bvLowered
    BevelKind = bkSoft
    TabOrder = 0
    ExplicitLeft = 336
    ExplicitHeight = 288
    DesignSize = (
      168
      285)
    object BtnNum1: TJvNavPanelButton
      Left = 12
      Top = 135
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '1'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum8: TJvNavPanelButton
      Left = 62
      Top = 36
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '8'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum7: TJvNavPanelButton
      Left = 12
      Top = 36
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '7'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum6: TJvNavPanelButton
      Left = 112
      Top = 85
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '6'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum4: TJvNavPanelButton
      Left = 12
      Top = 85
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '4'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum5: TJvNavPanelButton
      Left = 62
      Top = 85
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '5'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum2: TJvNavPanelButton
      Left = 62
      Top = 135
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '2'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum3: TJvNavPanelButton
      Left = 112
      Top = 135
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '3'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum9: TJvNavPanelButton
      Left = 112
      Top = 36
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '9'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNum0: TJvNavPanelButton
      Left = 12
      Top = 185
      Width = 98
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      Alignment = taCenter
      AllowAllUp = True
      Caption = '0'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNum0Click
    end
    object BtnNumBspc: TJvNavPanelButton
      Tag = 55
      Left = 112
      Top = 185
      Width = 48
      Height = 48
      Margins.Left = 1
      Margins.Top = 1
      Margins.Right = 1
      Margins.Bottom = 1
      Align = alCustom
      AllowAllUp = True
      Caption = '  '#8592
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      GroupIndex = 2
      HotTrack = False
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -13
      HotTrackFont.Name = 'Trebuchet MS'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      WordWrap = True
      Colors.ButtonColorFrom = clMedGray
      Colors.ButtonColorTo = clBlack
      Colors.ButtonHotColorFrom = 14256961
      Colors.ButtonHotColorTo = 11694645
      Colors.ButtonSelectedColorFrom = 14256961
      Colors.ButtonSelectedColorTo = 11694645
      ParentStyleManager = False
      ImageIndex = 19
      OnClick = BtnNumBspcClick
    end
    object btnLogin: TJvNavPanelButton
      Left = 14
      Top = 237
      Width = 147
      Height = 52
      Alignment = taCenter
      Caption = 'Tamam'
      Font.Charset = TURKISH_CHARSET
      Font.Color = clRed
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      HotTrackFont.Charset = TURKISH_CHARSET
      HotTrackFont.Color = clWindowText
      HotTrackFont.Height = -12
      HotTrackFont.Name = 'Segoe UI'
      HotTrackFont.Style = [fsBold]
      ParentFont = False
      Colors.ButtonColorFrom = clBtnFace
      Colors.ButtonColorTo = clGray
      ImageIndex = 11
      OnClick = btnLoginClick
    end
    object JvNavPanelButton1: TJvNavPanelButton
      Left = 123
      Top = 2
      Width = 40
      Height = 35
      Font.Charset = TURKISH_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentFont = False
      Colors.ButtonColorFrom = clBtnFace
      Colors.ButtonColorTo = clBtnFace
      ImageIndex = 36
      Images = Tablo.cxImageList1
      OnClick = JvNavPanelButton1Click
    end
    object cxLabel2: TcxLabel
      Left = 7
      Top = 11
      Anchors = [akLeft, akBottom]
      Caption = #350'ifre'
      Transparent = True
      ExplicitTop = 10
    end
    object edPassword: TcxTextEdit
      Left = 35
      Top = 8
      Properties.EchoMode = eemPassword
      TabOrder = 1
      OnKeyUp = FormKeyUp
      Width = 86
    end
  end
  object cxGridKul: TcxGrid
    Left = 0
    Top = 0
    Width = 340
    Height = 289
    Align = alClient
    BorderStyle = cxcbsNone
    TabOrder = 1
    LookAndFeel.Kind = lfStandard
    LookAndFeel.NativeStyle = True
    ExplicitWidth = 336
    ExplicitHeight = 288
    object cxGridKulDBCardView1: TcxGridDBCardView
      OnDblClick = btnLoginClick
      Navigator.Buttons.CustomButtons = <>
      ScrollbarAnnotations.CustomAnnotations = <>
      OnCellClick = cxGridKulDBCardView1CellClick
      DataController.DataSource = DtsKullanici
      DataController.Summary.DefaultGroupSummaryItems = <>
      DataController.Summary.FooterSummaryItems = <>
      DataController.Summary.SummaryGroups = <>
      OptionsSelection.CellSelect = False
      OptionsSelection.HideFocusRectOnExit = False
      OptionsSelection.UnselectFocusedRecordOnExit = False
      OptionsView.CardIndent = 7
      OptionsView.CardWidth = 130
      OptionsView.EmptyRows = False
      Styles.Background = Tablo.cxStyle13
      Styles.CardBorder = Tablo.cxStyle12
      Styles.LayerSeparator = Tablo.cxStyle10
      Styles.Selection = Tablo.cxstSecili
      object cxGridKulDBCardView1IMAJ: TcxGridDBCardViewRow
        DataBinding.FieldName = 'IMAJ'
        DataBinding.IsNullValueType = True
        PropertiesClassName = 'TcxImageProperties'
        Properties.GraphicClassName = 'TdxSmartImage'
        Properties.ReadOnly = True
        Options.ShowCaption = False
        Position.BeginsLayer = True
        Position.LineCount = 2
      end
      object cxGridKulDBCardView1FIRMA: TcxGridDBCardViewRow
        DataBinding.FieldName = 'FIRMA'
        DataBinding.IsNullValueType = True
        PropertiesClassName = 'TcxLabelProperties'
        Properties.WordWrap = True
        Options.ShowCaption = False
        Position.BeginsLayer = False
        Position.LineCount = 2
      end
    end
    object cxGridLevel1: TcxGridLevel
      GridView = cxGridKulDBCardView1
    end
  end
  object TabKullanici: TFDQuery
    Connection = Tablo.FDCnn
    ParamData = <>
    SQL.Strings = (
      'select K.*,R.FIRMA,R.KOD,'
      
        'IMAJ=(select top 1 I.BELGE from IMAJ I where I.VARSAYILAN=1 and ' +
        'I.REHBERID=R.ID order by I.ID desc)'
      'from KULLANICI K inner join REHBER R on K.REHBERID=R.ID '
      'where R.DURUM=1')
    Left = 33
    Top = 158
  end
  object DtsKullanici: TDataSource
    DataSet = TabKullanici
    Left = 146
    Top = 147
  end
end

