object UyariDlg: TUyariDlg
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  ClientHeight = 124
  ClientWidth = 431
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    AlignWithMargins = True
    Left = 0
    Top = 91
    Width = 431
    Height = 33
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alBottom
    TabOrder = 0
    ExplicitTop = 83
    object BtnOk: TcxButton
      AlignWithMargins = True
      Left = 338
      Top = 1
      Width = 92
      Height = 31
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alRight
      Caption = 'Tamam'
      OptionsImage.ImageIndex = 1
      OptionsImage.Images = Tablo.cxImageListPDKS
      TabOrder = 0
      OnClick = BtnOkClick
    end
    object btnNo: TcxButton
      AlignWithMargins = True
      Left = 258
      Top = 1
      Width = 80
      Height = 31
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alRight
      Caption = 'Hay'#305'r'
      OptionsImage.ImageIndex = 2
      OptionsImage.Images = Tablo.cxImageListPDKS
      TabOrder = 1
      Visible = False
      OnClick = btnNoClick
    end
    object btnYes: TcxButton
      AlignWithMargins = True
      Left = 178
      Top = 1
      Width = 80
      Height = 31
      Margins.Left = 0
      Margins.Top = 0
      Margins.Right = 0
      Margins.Bottom = 0
      Align = alRight
      Caption = 'Evet'
      OptionsImage.ImageIndex = 1
      OptionsImage.Images = Tablo.cxImageListPDKS
      TabOrder = 2
      Visible = False
      OnClick = btnYesClick
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 0
    Width = 431
    Height = 91
    Align = alClient
    TabOrder = 1
    ExplicitHeight = 83
    object lblUyariMsg: TcxLabel
      AlignWithMargins = True
      Left = 17
      Top = 17
      Margins.Left = 16
      Margins.Top = 16
      Margins.Right = 16
      Margins.Bottom = 16
      Align = alClient
      AutoSize = False
      ParentFont = False
      Style.Font.Charset = DEFAULT_CHARSET
      Style.Font.Color = clWindowText
      Style.Font.Height = -13
      Style.Font.Name = 'Tahoma'
      Style.Font.Style = []
      Style.IsFontAssigned = True
      Properties.WordWrap = True
      Transparent = True
      ExplicitHeight = 49
      Height = 57
      Width = 397
    end
  end
end
