-- ============================================================================
-- fn_prg_bankaekstre  (PG portu, TVF-per-engine)
-- MSSQL orijinali: dbo.Sp_Prg_BankaEkstre (@BankaHesapID,@BasTar,@BitTar)
-- Cagri: UBankalarListeFrame EKSTRE.SQL -> EXEC -> PgSqlCevir -> select * from fn(...)
-- Yapi: Ara Devir (acilis bakiyesi, cift-nest SUM swap) + hareketler UNION,
--       sonra window ile yuruyen bakiye (BORCBAKIYE/ALACAKBAKIYE/YERELBAKIYE).
-- NOT: nested swap/dedup MSSQL ile bire bir; differential veri olunca dogrulanmali.
-- ============================================================================
DROP FUNCTION IF EXISTS fn_prg_bankaekstre(integer, timestamp, timestamp);

CREATE OR REPLACE FUNCTION fn_prg_bankaekstre(p_bankahesapid integer, p_bastar timestamp, p_bittar timestamp)
RETURNS TABLE(
  "SIRANO"       integer,
  "CEKID"        integer,
  "TARIH"        timestamp,
  "AKSIYONTARIH" timestamp,
  "NO"           varchar(20),
  "TUR"          smallint,
  "BASLIK"       varchar(150),
  "TURAD"        varchar(50),
  "REHBERID"     integer,
  "KOD"          varchar(20),
  "AD"           varchar(100),
  "ACIKLAMA"     varchar(500),
  "HESAPID"      integer,
  "HESAPKODU"    varchar(100),
  "HESAPADI"     varchar(150),
  "DURUM"        smallint,
  "BORC"         numeric,
  "ALACAK"       numeric,
  "YERELTUTAR"   numeric,
  "KUR"          varchar(6),
  "YERELKUR"     numeric,
  "MASRAFID"     integer,
  "MASRAFKOD"    varchar(50),
  "MASRAFAD"     varchar(100),
  "SUBEID"       integer,
  "VADETARIHI"   timestamp,
  "BORCBAKIYE"   numeric,
  "ALACAKBAKIYE" numeric,
  "YERELBAKIYE"  numeric
)
LANGUAGE sql
AS $func$
WITH raw AS (
  -- ===== Ara Devir (acilis) : cift-nest SUM swap (MSSQL birebir) =============
  SELECT CEKID,TARIH,AKSIYONTARIH,no,TUR,BASLIK,TURAD,REHBERID,KOD,AD,ACIKLAMA,HESAPID,HESAPKODU,HESAPADI,DURUM,
         SUM(ALACAK) AS BORC, SUM(BORC) AS ALACAK, KUR, YERELKUR, MASRAFID,MASRAFKOD,MASRAFAD,YERELTUTAR,SUBEID,
         NULL::timestamp AS VADETARIHI
  FROM (
    SELECT CEKID,TARIH,AKSIYONTARIH,no,TUR,BASLIK,TURAD,REHBERID,KOD,AD,ACIKLAMA,HESAPID,HESAPKODU,HESAPADI,DURUM,
           SUM(ALACAK) AS BORC, SUM(BORC) AS ALACAK, KUR, YERELKUR, MASRAFID,MASRAFKOD,MASRAFAD,YERELTUTAR,SUBEID,
           NULL::timestamp AS VADETARIHI
    FROM (
      SELECT
        0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar AS no, 2::smallint AS TUR,
        '' AS BASLIK, 'Ara Devir' AS TURAD, 0 AS REHBERID, '' AS KOD, '' AS AD, 'Ara Devir' AS ACIKLAMA,
        NULL::int AS HESAPID, NULL::varchar AS HESAPKODU, NULL::varchar AS HESAPADI, 1::smallint AS DURUM,
        K.ALACAK AS BORC, K.BORC AS ALACAK, K.KUR, 0::numeric AS YERELKUR, 0 AS MASRAFID, '' AS MASRAFKOD, '' AS MASRAFAD,
        (SELECT SUM(A) FROM (
           SELECT CASE
                    WHEN K1.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K1.BORC>0  THEN -1*K1.DOVIZ_TUTARI
                    WHEN K1.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K1.ALACAK>0 THEN K1.DOVIZ_TUTARI
                    WHEN K1.TUR=88 THEN K1.DOVIZ_TUTARI
                    WHEN K1.TUR=98 THEN -1*K1.DOVIZ_TUTARI
                    ELSE K1.ALACAK-K1.BORC
                  END AS A
           FROM KASA K1
           WHERE K1.HESAPID=p_bankahesapid AND K1.ISLEMTARIHI <= p_bastar AND K.HESAPTURU='B'
        ) S) AS YERELTUTAR,
        K.SUBEID, NULL::timestamp AS VADETARIHI
      FROM KASA K
        LEFT JOIN REHBER R ON R.ID=K.REHBERID
        LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
        LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
      WHERE K.ISLEMTARIHI <= p_bastar AND extract(year from K.ISLEMTARIHI)=extract(year from p_bastar)
        AND K.HESAPID=p_bankahesapid AND K.HESAPTURU='B'
        AND NOT EXISTS (SELECT 1 FROM KASA K1 WHERE K1.ID=K.ID AND K1.TUR NOT IN (2)
                        AND K.ISLEMTARIHI=K1.ISLEMTARIHI AND K1.ISLEMTARIHI>=p_bastar)
    ) ABC
    GROUP BY CEKID,TARIH,AKSIYONTARIH,no,TUR,BASLIK,TURAD,REHBERID,KOD,AD,ACIKLAMA,HESAPID,HESAPKODU,HESAPADI,DURUM,
             YERELTUTAR,KUR,YERELKUR,MASRAFID,MASRAFKOD,MASRAFAD,SUBEID,VADETARIHI
  ) XYZ
  GROUP BY CEKID,TARIH,AKSIYONTARIH,no,TUR,BASLIK,TURAD,REHBERID,KOD,AD,ACIKLAMA,HESAPID,HESAPKODU,HESAPADI,DURUM,
           YERELTUTAR,KUR,YERELKUR,MASRAFID,MASRAFKOD,MASRAFAD,SUBEID,VADETARIHI

  UNION ALL

  -- ===== Hareketler =========================================================
  SELECT
    K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.ISLEMTARIHI AS AKSIYONTARIH, K.BELGENO AS no, K.TUR, '' AS BASLIK,
    KasaTurleri.ANAHTAR AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU
       WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT cast(ID as varchar(5)) FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT KODU FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS KOD,
    (CASE K.HESAPTURU
       WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT ADI FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT ADI FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS AD,
    K.ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END) AS HESAPADI,
    K.DURUM,
    K.ALACAK AS BORC, K.BORC AS ALACAK, K.KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0  THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN -K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END)
         / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END)) AS YERELKUR,
    K.MASRAFID, M.KOD AS MASRAFKOD, M.AD AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0  THEN -1*K.DOVIZ_TUTARI
          WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
          WHEN K.TUR=88 THEN K.DOVIZ_TUTARI
          WHEN K.TUR=98 THEN -1*K.DOVIZ_TUTARI
          ELSE K.ALACAK-K.BORC END) AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE K.ISLEMTARIHI BETWEEN p_bastar AND p_bittar
    AND K.HESAPID=p_bankahesapid AND K.HESAPTURU='B'
),
tmp AS (
  SELECT
    row_number() OVER (ORDER BY KUR, TARIH, CASE WHEN TUR=2 AND CEKID=0 THEN 0 ELSE 1 END, CEKID)::int AS SIRANO,
    CEKID::int, TARIH::timestamp, AKSIYONTARIH::timestamp, no::varchar(20) AS no, TUR::smallint,
    BASLIK::varchar(150) AS BASLIK, TURAD::varchar(50) AS TURAD, REHBERID::int, KOD::varchar(20) AS KOD,
    AD::varchar(100) AS AD, ACIKLAMA::varchar(500) AS ACIKLAMA, HESAPID::int, HESAPKODU::varchar(100) AS HESAPKODU,
    HESAPADI::varchar(150) AS HESAPADI, DURUM::smallint, BORC::numeric, ALACAK::numeric, KUR::varchar(6) AS KUR,
    YERELKUR::numeric, MASRAFID::int, MASRAFKOD::varchar(50) AS MASRAFKOD, MASRAFAD::varchar(100) AS MASRAFAD,
    YERELTUTAR::numeric, SUBEID::int, VADETARIHI::timestamp
  FROM raw
)
SELECT
  A.SIRANO, A.CEKID, A.TARIH, A.AKSIYONTARIH, A.no, A.TUR, A.BASLIK, A.TURAD, A.REHBERID, A.KOD, A.AD, A.ACIKLAMA,
  A.HESAPID, A.HESAPKODU, A.HESAPADI, A.DURUM,
  (CASE WHEN A.TUR=2 AND A.ACIKLAMA='Ara Devir' THEN 0 ELSE A.BORC END)::numeric   AS BORC,
  (CASE WHEN A.TUR=2 AND A.ACIKLAMA='Ara Devir' THEN 0 ELSE A.ALACAK END)::numeric AS ALACAK,
  A.YERELTUTAR, A.KUR, A.YERELKUR, A.MASRAFID, A.MASRAFKOD, A.MASRAFAD, A.SUBEID, A.VADETARIHI,
  (CASE WHEN SUM(A.BORC-A.ALACAK) OVER (ORDER BY A.KUR, A.SIRANO) > 0
        THEN SUM(A.BORC-A.ALACAK) OVER (ORDER BY A.KUR, A.SIRANO) ELSE 0 END)::numeric AS BORCBAKIYE,
  (CASE WHEN SUM(A.ALACAK-A.BORC) OVER (ORDER BY A.KUR, A.SIRANO) > 0
        THEN SUM(A.ALACAK-A.BORC) OVER (ORDER BY A.KUR, A.SIRANO) ELSE 0 END)::numeric AS ALACAKBAKIYE,
  (SUM(A.YERELTUTAR) OVER (ORDER BY A.KUR, A.SIRANO))::numeric AS YERELBAKIYE
FROM tmp A
WHERE NOT EXISTS (
  SELECT 1 FROM tmp B
  WHERE B.TARIH IN (SELECT C.TARIH FROM tmp C WHERE B.TARIH=C.TARIH AND C.TUR=2 AND C.CEKID=0)
    AND B.CEKID=A.CEKID AND B.TUR=2 AND A.CEKID<>0
)
ORDER BY A.KUR, A.SIRANO;
$func$;
