-- ============================================================================
-- fn_prg_cekekstre  (PG portu, TVF-per-engine)
-- MSSQL orijinali: dbo.Sp_Prg_CekEkstre (@Kod varchar,@BasTar,@BitTar)
-- Cagri: EKSTRE.SQL EXEC -> PgSqlCevir -> select * from fn_prg_cekekstre(:Kod,:Bas,:Bit)
--   NOT: app 3 param'i da VARCHAR bind ediyor -> imza (varchar,varchar,varchar);
--        tarihler ICERIDE ::timestamp cast'lenir.
-- Yapi: Devir (acilis, HESAPPLANI+CEKHAREKET+KASA) + cek/kasa hareketleri UNION,
--       sonra window ile yuruyen bakiye. MSSQL ile birebir; differential veriyle dogrulanmali.
-- ============================================================================
DROP FUNCTION IF EXISTS fn_prg_cekekstre(varchar, varchar, varchar);

CREATE OR REPLACE FUNCTION fn_prg_cekekstre(p_kod varchar, p_bastar varchar, p_bittar varchar)
RETURNS TABLE(
  "SIRANO"       integer,
  "CEKID"        integer,
  "TARIH"        timestamp,
  "AKSIYONTARIH" timestamp,
  "NO"           varchar(20),
  "TUR"          smallint,
  "BASLIK"       varchar(150),
  "TURAD"        varchar(50),
  "REHBERID"     integer,
  "KOD"          varchar(20),
  "AD"           varchar(100),
  "ACIKLAMA"     varchar(500),
  "HESAPID"      integer,
  "HESAPKODU"    varchar(100),
  "HESAPADI"     varchar(150),
  "DURUM"        smallint,
  "BORC"         numeric,
  "ALACAK"       numeric,
  "YERELTUTAR"   numeric,
  "KUR"          varchar(6),
  "YERELKUR"     numeric,
  "MASRAFID"     integer,
  "MASRAFKOD"    varchar(50),
  "MASRAFAD"     varchar(100),
  "SUBEID"       integer,
  "VADETARIHI"   timestamp,
  "BORCBAKIYE"   numeric,
  "ALACAKBAKIYE" numeric,
  "YERELBAKIYE"  numeric
)
LANGUAGE sql
AS $func$
WITH bt AS (SELECT p_bastar::timestamp AS bastar, p_bittar::timestamp AS bittar),
raw AS (
  -- ===== Devir (acilis) =====================================================
  SELECT 0 AS CEKID, (SELECT bastar FROM bt) AS TARIH, (SELECT bastar FROM bt) AS AKSIYONTARIH,
         NULL::varchar AS no, 2::smallint AS TUR, '-Devir-' AS BASLIK, '-Devir-' AS TURAD, 0 AS REHBERID,
         HESAPKODU AS KOD, HESAPADI AS AD, '-Devir-' AS ACIKLAMA, 0 AS HESAPID, HESAPKODU, HESAPADI, 1::smallint AS DURUM,
         (CASE WHEN SUM(DOVIZ_BAKIYE)>0 THEN SUM(DOVIZ_BAKIYE) ELSE 0.0 END) AS BORC,
         (CASE WHEN SUM(DOVIZ_BAKIYE)>0 THEN 0.0 ELSE -SUM(DOVIZ_BAKIYE) END) AS ALACAK,
         DOVIZ_KURU AS KUR,
         (CASE WHEN SUM(BAKIYE)=0.0 THEN 0.0 ELSE ABS(SUM(DOVIZ_BAKIYE)/SUM(BAKIYE)) END) AS YERELKUR,
         0 AS MASRAFID, NULL::varchar AS MASRAFKOD, NULL::varchar AS MASRAFAD,
         ABS(SUM(BAKIYE)) AS YERELTUTAR, -1 AS SUBEID, (SELECT bastar FROM bt) AS VADETARIHI
  FROM (
        -- devir borc
        SELECT H.HESAPKODU, H.HESAPADI, CH.DOVIZ_TUTARI AS BORC, 0.0 AS ALACAK, CH.DOVIZ_TUTARI AS BAKIYE,
               CH.DOVIZ_KURU AS KUR, C.TUTAR AS DOVIZ_BORC, 0.0 AS DOVIZ_ALACAK, C.TUTAR AS DOVIZ_BAKIYE, C.KUR AS DOVIZ_KURU
        FROM CEKLER C
          INNER JOIN CEKHAREKET CH ON C.ID=CH.CEKSENETLERID
          INNER JOIN HESAPPLANI H ON H.KUR=C.KUR AND H.MUHASEBE=CH.ISLEM AND H.VARSAYILAN=C.CEKSENET
        WHERE CH.TARIH < (SELECT bastar FROM bt) AND H.HESAPKODU=p_kod
        UNION ALL
        -- devir alacak
        SELECT H.HESAPKODU, H.HESAPADI, 0.0 AS BORC, CH.DOVIZ_TUTARI AS ALACAK, -CH.DOVIZ_TUTARI AS BAKIYE,
               CH.DOVIZ_KURU AS KUR, 0.0 AS DOVIZ_BORC, C.TUTAR AS DOVIZ_ALACAK, -C.TUTAR AS DOVIZ_BAKIYE, C.KUR AS DOVIZ_KURU
        FROM CEKLER C
          INNER JOIN CEKHAREKET CH ON C.ID=CH.CEKSENETLERID
          INNER JOIN CEKHAREKET CHD ON CH.GERIDONUSID=CHD.ID
          INNER JOIN HESAPPLANI H ON H.KUR=C.KUR AND H.MUHASEBE=CHD.ISLEM AND H.VARSAYILAN=C.CEKSENET
        WHERE CH.TARIH < (SELECT bastar FROM bt) AND H.HESAPKODU=p_kod
        UNION ALL
        -- devir kasa (88/98)
        SELECT H.HESAPKODU, H.HESAPADI,
               (CASE WHEN K.TUR=98 THEN 0.0 ELSE K.DOVIZ_TUTARI END) AS BORC,
               (CASE WHEN K.TUR=98 THEN K.DOVIZ_TUTARI ELSE 0.0 END) AS ALACAK,
               (CASE WHEN K.TUR=98 THEN K.DOVIZ_TUTARI ELSE -K.DOVIZ_TUTARI END) AS BAKIYE,
               K.DOVIZ_KURU AS KUR, 0.0 AS DOVIZ_BORC, 0.0 AS DOVIZ_ALACAK, 0.0 AS DOVIZ_BAKIYE, K.KUR AS DOVIZ_KURU
        FROM KASA K
          INNER JOIN HESAPPLANI H ON H.ID=K.HESAPID
          LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
          INNER JOIN ISLEMTURLERI Turler ON Turler.TUR=K.TUR AND Turler.TIP=0
        WHERE H.HESAPKODU=p_kod AND K.ISLEMTARIHI < (SELECT bastar FROM bt) AND K.TUR IN (88,98) AND K.HESAPTURU='Ç'
  ) XX
  GROUP BY HESAPKODU, HESAPADI, KUR, DOVIZ_KURU

  UNION ALL

  -- ===== Cek hareket (borc) =================================================
  SELECT C.ID AS CEKID, CH.TARIH, C.TARIH AS AKSIYONTARIH, C.SERINO::varchar AS no, CH.ISLEM AS TUR, C.BORCLU AS BASLIK,
         G.ANAHTAR AS TURAD, CH.REHBERID, H.HESAPKODU AS KOD, H.HESAPADI AS AD,
         replace(CH.BILGI,'&','') AS ACIKLAMA, 0 AS HESAPID, H.HESAPKODU, H.HESAPADI, C.DURUM,
         C.TUTAR AS BORC, 0.0 AS ALACAK, C.KUR AS KUR, CH.DOVIZ_TUTARI/C.TUTAR AS YERELKUR,
         0 AS MASRAFID, '' AS MASRAFKOD, '' AS MASRAFAD, CH.DOVIZ_TUTARI AS YERELTUTAR, CH.SUBEID, C.VADE AS VADETARIHI
  FROM CEKLER C
    INNER JOIN CEKHAREKET CH ON C.ID=CH.CEKSENETLERID
    INNER JOIN REHBER R ON R.ID=C.REHBERID
    INNER JOIN HESAPPLANI H ON H.KUR=C.KUR AND H.MUHASEBE=CH.ISLEM AND H.VARSAYILAN=C.CEKSENET
    LEFT JOIN GENINI G ON G.BOLUM=-1005 AND CH.ISLEM=G.DEGER AND G.DIL=-1
  WHERE CH.TARIH BETWEEN (SELECT bastar FROM bt) AND (SELECT bittar FROM bt) AND H.HESAPKODU=p_kod

  UNION ALL

  -- ===== Cek hareket (alacak, geridonus) ====================================
  SELECT C.ID AS CEKID, CH.TARIH, C.TARIH AS AKSIYONTARIH, C.SERINO::varchar AS no, CH.ISLEM AS TUR, C.BORCLU AS BASLIK,
         G.ANAHTAR AS TURAD, CH.REHBERID, H.HESAPKODU AS KOD, H.HESAPADI AS AD,
         replace(coalesce(CHD.BILGI,''),'&','') || ' >> ' || replace(coalesce(CH.BILGI,''),'&','') AS ACIKLAMA,
         H.ID AS HESAPID, H.HESAPKODU, H.HESAPADI, C.DURUM,
         0.0 AS BORC, C.TUTAR AS ALACAK, C.KUR AS KUR, CH.DOVIZ_TUTARI/C.TUTAR AS YERELKUR,
         0 AS MASRAFID, '' AS MASRAFKOD, '' AS MASRAFAD, -CH.DOVIZ_TUTARI AS YERELTUTAR, CH.SUBEID, C.VADE AS VADETARIHI
  FROM CEKLER C
    INNER JOIN CEKHAREKET CH ON C.ID=CH.CEKSENETLERID
    INNER JOIN CEKHAREKET CHD ON CH.GERIDONUSID=CHD.ID
    INNER JOIN REHBER R ON R.ID=C.REHBERID
    INNER JOIN HESAPPLANI H ON H.KUR=C.KUR AND H.MUHASEBE=CHD.ISLEM AND H.VARSAYILAN=C.CEKSENET
    LEFT JOIN GENINI G ON G.BOLUM=-1005 AND CH.ISLEM=G.DEGER AND G.DIL=-1
  WHERE CH.TARIH BETWEEN (SELECT bastar FROM bt) AND (SELECT bittar FROM bt) AND H.HESAPKODU=p_kod

  UNION ALL

  -- ===== Kasa (88/98) : gelir arttiracak, masraf dusurecek ==================
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.PLANTARIHI AS AKSIYONTARIH, '0' AS no, K.TUR, '' AS BASLIK,
         Turler.AD AS TURAD, K.REHBERID, H.HESAPKODU AS KOD, H.HESAPADI AS AD, K.ACIKLAMA, H.ID AS HESAPID,
         H.HESAPKODU, H.HESAPADI, K.DURUM, K.BORC, K.ALACAK, K.KUR AS KUR,
         ABS( K.BORC - K.ALACAK /
              CASE WHEN ((CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)
                        -(CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END))=0 THEN 1
                   ELSE ((CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)
                        -(CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END)) END
            ) AS YERELKUR,
         K.MASRAFID, M.KOD AS MASRAFKOD, M.AD AS MASRAFAD,
         (CASE WHEN K.TUR=98 THEN -K.DOVIZ_TUTARI ELSE K.DOVIZ_TUTARI END) AS YERELTUTAR, K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    INNER JOIN HESAPPLANI H ON H.ID=K.HESAPID
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
    INNER JOIN ISLEMTURLERI Turler ON Turler.TUR=K.TUR AND Turler.TIP=0
  WHERE H.HESAPKODU=p_kod AND K.ISLEMTARIHI BETWEEN (SELECT bastar FROM bt) AND (SELECT bittar FROM bt)
    AND K.TUR IN (88,98) AND K.HESAPTURU='Ç'
),
tmp AS (
  SELECT
    row_number() OVER (ORDER BY KUR, TARIH, CASE WHEN TUR=2 AND CEKID=0 THEN 0 ELSE 1 END, CEKID)::int AS SIRANO,
    CEKID::int, TARIH::timestamp, AKSIYONTARIH::timestamp, no::varchar(20) AS no, TUR::smallint,
    BASLIK::varchar(150) AS BASLIK, TURAD::varchar(50) AS TURAD, REHBERID::int, KOD::varchar(20) AS KOD,
    AD::varchar(100) AS AD, ACIKLAMA::varchar(500) AS ACIKLAMA, HESAPID::int, HESAPKODU::varchar(100) AS HESAPKODU,
    HESAPADI::varchar(150) AS HESAPADI, DURUM::smallint, BORC::numeric, ALACAK::numeric, KUR::varchar(6) AS KUR,
    YERELKUR::numeric, MASRAFID::int, MASRAFKOD::varchar(50) AS MASRAFKOD, MASRAFAD::varchar(100) AS MASRAFAD,
    YERELTUTAR::numeric, SUBEID::int, VADETARIHI::timestamp
  FROM raw
)
SELECT
  A.SIRANO, A.CEKID, A.TARIH, A.AKSIYONTARIH, A.no, A.TUR, A.BASLIK, A.TURAD, A.REHBERID, A.KOD, A.AD, A.ACIKLAMA,
  A.HESAPID, A.HESAPKODU, A.HESAPADI, A.DURUM,
  A.BORC, A.ALACAK,
  (CASE WHEN A.TUR=2 THEN 0 ELSE A.YERELTUTAR END)::numeric AS YERELTUTAR,
  A.KUR, A.YERELKUR, A.MASRAFID, A.MASRAFKOD, A.MASRAFAD, A.SUBEID, A.VADETARIHI,
  (CASE WHEN SUM(A.BORC-A.ALACAK) OVER (ORDER BY A.KUR, A.SIRANO) > 0
        THEN SUM(A.BORC-A.ALACAK) OVER (ORDER BY A.KUR, A.SIRANO) ELSE 0 END)::numeric AS BORCBAKIYE,
  (CASE WHEN SUM(A.ALACAK-A.BORC) OVER (ORDER BY A.KUR, A.SIRANO) > 0
        THEN SUM(A.ALACAK-A.BORC) OVER (ORDER BY A.KUR, A.SIRANO) ELSE 0 END)::numeric AS ALACAKBAKIYE,
  (SUM((CASE WHEN A.TUR=2 THEN 0 ELSE A.YERELTUTAR END)) OVER (ORDER BY A.KUR, A.SIRANO))::numeric AS YERELBAKIYE
FROM tmp A
ORDER BY A.KUR, A.SIRANO;
$func$;
