-- ============================================================================
-- Hesap-ekstre ailesi (PG portu, TVF-per-engine): POS / Kasa Iade / Hediye / Kupon
-- MSSQL: fn_POS_Ekstre, fn_Kasa_Iade_Ekstre, fn_Kasa_Hediye_Ekstre, fn_Kasa_Kupon_Ekstre
-- Cagri: EKSTRE/TabCariListe 'select * from fn_X(id,''tarih'',''tarih''[,kupon])'
--        literal tarih (unknown)->timestamp param'a coerce.
-- Yuruyen bakiye: MSSQL cursor (TUR 60-79 haric) -> window SUM OVER(PARTITION BY KUR ORDER BY SIRANO).
--   BORCBAKIYE=max(sum(BORC-ALACAK excl 60-79),0), ALACAKBAKIYE=max(sum(ALACAK-BORC),0), YERELBAKIYE=sum(YERELTUTAR).
-- Devir: pre-bastar (variant filtre) KUR,SUBEID grupla; sonra pre-bastar satirlari at.
-- NOT: birebir port; differential veriyle dogrulanmali.
-- ============================================================================

-- ortak dokuman: movement kolonlari K(KASA), R(REHBER), M(MASRAFGELIR), KasaTurleri(GENINI -1005)
--   BORC=K.ALACAK, ALACAK=K.BORC (swap). doviz: BOLUM=-10135 cari doviz.

-- ========================================================== fn_pos_ekstre
DROP FUNCTION IF EXISTS fn_pos_ekstre(integer, timestamp, timestamp);
CREATE OR REPLACE FUNCTION fn_pos_ekstre(p_id integer, p_bastar timestamp, p_bittar timestamp)
RETURNS TABLE("SIRANO" integer,"CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),
  "TUR" smallint,"BASLIK" varchar(150),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(100),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(150),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"KUR" varchar(6),"YERELKUR" numeric,"MASRAFID" integer,"MASRAFKOD" varchar(50),
  "MASRAFAD" varchar(100),"BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELTUTAR" numeric,"YERELBAKIYE" numeric,
  "SUBEID" integer,"VADETARIHI" timestamp)
LANGUAGE sql AS $$
WITH mov AS (
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.ISLEMTARIHI AS AKSIYONTARIH, K.BELGENO::varchar AS no, K.TUR::smallint AS TUR,
    ''::varchar(150) AS BASLIK, KasaTurleri.ANAHTAR AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT cast(ID as varchar(5)) FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT KODU FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS KOD,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT ADI FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT ADI FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS AD,
    K.ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END) AS HESAPADI,
    K.DURUM::smallint AS DURUM, K.ALACAK AS BORC, K.BORC AS ALACAK, K.KUR::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END) / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END)) AS YERELKUR,
    K.MASRAFID, M.KOD AS MASRAFKOD, M.AD AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
          WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
          ELSE K.ALACAK-K.BORC END) AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE extract(year from K.ISLEMTARIHI) >= extract(year from p_bastar)
    AND extract(year from K.ISLEMTARIHI) <= extract(year from p_bittar)
    AND K.ISLEMTARIHI <= p_bittar AND K.HESAPID=p_id AND K.HESAPTURU='P'
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, TARIH) AS SIRANO FROM mov),
bal AS (SELECT *,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS ALACAKBAKIYE,
  SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE YERELTUTAR END) OVER (PARTITION BY KUR ORDER BY SIRANO) AS YERELBAKIYE
  FROM seq)
SELECT row_number() OVER (ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID)::int AS SIRANO,
  q.CEKID, q.TARIH, q.AKSIYONTARIH, q.no, q.TUR, q.BASLIK, q.TURAD, q.REHBERID, q.KOD, q.AD, q.ACIKLAMA,
  q.HESAPID, q.HESAPKODU, q.HESAPADI, q.DURUM, q.BORC, q.ALACAK, q.KUR, q.YERELKUR, q.MASRAFID, q.MASRAFKOD,
  q.MASRAFAD, q.BORCBAKIYE, q.ALACAKBAKIYE, q.YERELTUTAR, q.YERELBAKIYE, q.SUBEID, q.VADETARIHI
FROM (
  -- devir (POS: BORC/ALACAK=0)
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar(20) AS no, 2::smallint AS TUR,
    ''::varchar(150) AS BASLIK, 'Devir'::varchar(50) AS TURAD, 0 AS REHBERID, ''::varchar(20) AS KOD, ''::varchar(100) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    0::numeric AS BORC, 0::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR, 0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(100) AS MASRAFAD,
    (CASE WHEN SUM(BORC-ALACAK)>0 THEN SUM(BORC-ALACAK) ELSE 0 END)::numeric AS BORCBAKIYE,
    (CASE WHEN SUM(ALACAK-BORC)>0 THEN SUM(ALACAK-BORC) ELSE 0 END)::numeric AS ALACAKBAKIYE,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR,
    (CASE WHEN SUM(YERELTUTAR)>0 THEN SUM(YERELTUTAR) ELSE 0 END)::numeric AS YERELBAKIYE,
    SUBEID, p_bastar AS VADETARIHI
  FROM bal WHERE TUR IN (1,2,25,44) AND TARIH < p_bastar GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1 AS devirsira, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU,
    HESAPADI, DURUM, BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, BORCBAKIYE, ALACAKBAKIYE, YERELTUTAR, YERELBAKIYE, SUBEID, VADETARIHI
  FROM bal WHERE TARIH >= p_bastar
) q
ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID;
$$;

-- ========================================================== fn_kasa_iade_ekstre
-- ========================================================== fn_kasa_iade_ekstre
DROP FUNCTION IF EXISTS fn_kasa_iade_ekstre(integer, timestamp, timestamp);
CREATE OR REPLACE FUNCTION fn_kasa_iade_ekstre(p_id integer, p_bastar timestamp, p_bittar timestamp)
RETURNS TABLE("SIRANO" integer,"CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),
  "TUR" smallint,"BASLIK" varchar(150),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(100),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(150),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"KUR" varchar(6),"YERELKUR" numeric,"MASRAFID" integer,"MASRAFKOD" varchar(50),
  "MASRAFAD" varchar(100),"BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELTUTAR" numeric,"YERELBAKIYE" numeric,
  "SUBEID" integer,"VADETARIHI" timestamp)
LANGUAGE sql AS $$
WITH mov AS (
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.ISLEMTARIHI AS AKSIYONTARIH, K.BELGENO::varchar AS no, K.TUR::smallint AS TUR,
    ''::varchar(150) AS BASLIK, KasaTurleri.ANAHTAR AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT cast(ID as varchar(5)) FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT KODU FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS KOD,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT ADI FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT ADI FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS AD,
    K.ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END) AS HESAPADI,
    K.DURUM::smallint AS DURUM, K.ALACAK AS BORC, K.BORC AS ALACAK, K.KUR::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END) / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END)) AS YERELKUR,
    K.MASRAFID, M.KOD AS MASRAFKOD, M.AD AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
          WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
          ELSE K.ALACAK-K.BORC END) AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE extract(year from K.ISLEMTARIHI) >= extract(year from p_bastar)
    AND extract(year from K.ISLEMTARIHI) <= extract(year from p_bittar)
    AND K.ISLEMTARIHI <= p_bittar AND K.HESAPID=p_id AND K.HESAPTURU='H' AND K.TUR IN (28,38,55)
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, TARIH) AS SIRANO FROM mov),
bal AS (SELECT *,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS ALACAKBAKIYE,
  SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE YERELTUTAR END) OVER (PARTITION BY KUR ORDER BY SIRANO) AS YERELBAKIYE
  FROM seq)
SELECT row_number() OVER (ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID)::int AS SIRANO,
  q.CEKID, q.TARIH, q.AKSIYONTARIH, q.no, q.TUR, q.BASLIK, q.TURAD, q.REHBERID, q.KOD, q.AD, q.ACIKLAMA,
  q.HESAPID, q.HESAPKODU, q.HESAPADI, q.DURUM, q.BORC, q.ALACAK, q.KUR, q.YERELKUR, q.MASRAFID, q.MASRAFKOD,
  q.MASRAFAD, q.BORCBAKIYE, q.ALACAKBAKIYE, q.YERELTUTAR, q.YERELBAKIYE, q.SUBEID, q.VADETARIHI
FROM (
  -- devir (POS: BORC/ALACAK=0)
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar(20) AS no, 2::smallint AS TUR,
    ''::varchar(150) AS BASLIK, 'Devir'::varchar(50) AS TURAD, 0 AS REHBERID, ''::varchar(20) AS KOD, ''::varchar(100) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    SUM(BORC)::numeric AS BORC, SUM(ALACAK)::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR, 0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(100) AS MASRAFAD,
    (CASE WHEN SUM(BORC-ALACAK)>0 THEN SUM(BORC-ALACAK) ELSE 0 END)::numeric AS BORCBAKIYE,
    (CASE WHEN SUM(ALACAK-BORC)>0 THEN SUM(ALACAK-BORC) ELSE 0 END)::numeric AS ALACAKBAKIYE,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR,
    (CASE WHEN SUM(YERELTUTAR)>0 THEN SUM(YERELTUTAR) ELSE 0 END)::numeric AS YERELBAKIYE,
    SUBEID, p_bastar AS VADETARIHI
  FROM bal WHERE ((TUR IN (40,42,49)) OR (TUR NOT BETWEEN 40 AND 79)) AND TARIH < p_bastar GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1 AS devirsira, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU,
    HESAPADI, DURUM, BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, BORCBAKIYE, ALACAKBAKIYE, YERELTUTAR, YERELBAKIYE, SUBEID, VADETARIHI
  FROM bal WHERE TARIH >= p_bastar
) q
ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID;
$$;

-- ========================================================== fn_kasa_hediye_ekstre
-- ========================================================== fn_kasa_hediye_ekstre
DROP FUNCTION IF EXISTS fn_kasa_hediye_ekstre(integer, timestamp, timestamp);
CREATE OR REPLACE FUNCTION fn_kasa_hediye_ekstre(p_id integer, p_bastar timestamp, p_bittar timestamp)
RETURNS TABLE("SIRANO" integer,"CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),
  "TUR" smallint,"BASLIK" varchar(150),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(100),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(150),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"KUR" varchar(6),"YERELKUR" numeric,"MASRAFID" integer,"MASRAFKOD" varchar(50),
  "MASRAFAD" varchar(100),"BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELTUTAR" numeric,"YERELBAKIYE" numeric,
  "SUBEID" integer,"VADETARIHI" timestamp)
LANGUAGE sql AS $$
WITH mov AS (
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.ISLEMTARIHI AS AKSIYONTARIH, K.BELGENO::varchar AS no, K.TUR::smallint AS TUR,
    ''::varchar(150) AS BASLIK, KasaTurleri.ANAHTAR AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT cast(ID as varchar(5)) FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT KODU FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS KOD,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT ADI FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT ADI FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS AD,
    K.ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END) AS HESAPADI,
    K.DURUM::smallint AS DURUM, K.ALACAK AS BORC, K.BORC AS ALACAK, K.KUR::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END) / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END)) AS YERELKUR,
    K.MASRAFID, M.KOD AS MASRAFKOD, M.AD AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
          WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
          ELSE K.ALACAK-K.BORC END) AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE extract(year from K.ISLEMTARIHI) >= extract(year from p_bastar)
    AND extract(year from K.ISLEMTARIHI) <= extract(year from p_bittar)
    AND K.ISLEMTARIHI <= p_bittar AND K.HESAPID=p_id AND K.HESAPTURU='H' AND K.TUR IN (29,39,56)
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, TARIH) AS SIRANO FROM mov),
bal AS (SELECT *,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS ALACAKBAKIYE,
  SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE YERELTUTAR END) OVER (PARTITION BY KUR ORDER BY SIRANO) AS YERELBAKIYE
  FROM seq)
SELECT row_number() OVER (ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID)::int AS SIRANO,
  q.CEKID, q.TARIH, q.AKSIYONTARIH, q.no, q.TUR, q.BASLIK, q.TURAD, q.REHBERID, q.KOD, q.AD, q.ACIKLAMA,
  q.HESAPID, q.HESAPKODU, q.HESAPADI, q.DURUM, q.BORC, q.ALACAK, q.KUR, q.YERELKUR, q.MASRAFID, q.MASRAFKOD,
  q.MASRAFAD, q.BORCBAKIYE, q.ALACAKBAKIYE, q.YERELTUTAR, q.YERELBAKIYE, q.SUBEID, q.VADETARIHI
FROM (
  -- devir (POS: BORC/ALACAK=0)
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar(20) AS no, 2::smallint AS TUR,
    ''::varchar(150) AS BASLIK, 'Devir'::varchar(50) AS TURAD, 0 AS REHBERID, ''::varchar(20) AS KOD, ''::varchar(100) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    SUM(BORC)::numeric AS BORC, SUM(ALACAK)::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR, 0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(100) AS MASRAFAD,
    (CASE WHEN SUM(BORC-ALACAK)>0 THEN SUM(BORC-ALACAK) ELSE 0 END)::numeric AS BORCBAKIYE,
    (CASE WHEN SUM(ALACAK-BORC)>0 THEN SUM(ALACAK-BORC) ELSE 0 END)::numeric AS ALACAKBAKIYE,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR,
    (CASE WHEN SUM(YERELTUTAR)>0 THEN SUM(YERELTUTAR) ELSE 0 END)::numeric AS YERELBAKIYE,
    SUBEID, p_bastar AS VADETARIHI
  FROM bal WHERE ((TUR IN (40,42,49)) OR (TUR NOT BETWEEN 40 AND 79)) AND TARIH < p_bastar GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1 AS devirsira, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU,
    HESAPADI, DURUM, BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, BORCBAKIYE, ALACAKBAKIYE, YERELTUTAR, YERELBAKIYE, SUBEID, VADETARIHI
  FROM bal WHERE TARIH >= p_bastar
) q
ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID;
$$;

-- ========================================================== fn_kasa_kupon_ekstre
-- ========================================================== fn_kasa_kupon_ekstre
DROP FUNCTION IF EXISTS fn_kasa_kupon_ekstre(integer, timestamp, timestamp, integer);
CREATE OR REPLACE FUNCTION fn_kasa_kupon_ekstre(p_id integer, p_bastar timestamp, p_bittar timestamp, p_kuponid integer)
RETURNS TABLE("SIRANO" integer,"CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),
  "TUR" smallint,"BASLIK" varchar(150),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(100),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(150),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"KUR" varchar(6),"YERELKUR" numeric,"MASRAFID" integer,"MASRAFKOD" varchar(50),
  "MASRAFAD" varchar(100),"BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELTUTAR" numeric,"YERELBAKIYE" numeric,
  "SUBEID" integer,"VADETARIHI" timestamp)
LANGUAGE sql AS $$
WITH mov AS (
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.ISLEMTARIHI AS AKSIYONTARIH, K.BELGENO::varchar AS no, K.TUR::smallint AS TUR,
    ''::varchar(150) AS BASLIK, KasaTurleri.ANAHTAR AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT cast(ID as varchar(5)) FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT KODU FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS KOD,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT ADI FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT ADI FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END) AS AD,
    K.ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END) AS HESAPADI,
    K.DURUM::smallint AS DURUM, K.ALACAK AS BORC, K.BORC AS ALACAK, K.KUR::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END) / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END)) AS YERELKUR,
    K.MASRAFID, M.KOD AS MASRAFKOD, M.AD AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
          WHEN K.DOVIZ_KURU=(SELECT ANAHTAR FROM GENINI WHERE BOLUM=-10135 LIMIT 1) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
          ELSE K.ALACAK-K.BORC END) AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE extract(year from K.ISLEMTARIHI) >= extract(year from p_bastar)
    AND extract(year from K.ISLEMTARIHI) <= extract(year from p_bittar)
    AND K.ISLEMTARIHI <= p_bittar AND K.HESAPID=p_id AND K.HESAPTURU='H' AND K.TUR IN (26,36,81) AND (p_kuponid=0 OR p_kuponid=coalesce(K.CEKSENETID,0))
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, TARIH) AS SIRANO FROM mov),
bal AS (SELECT *,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS ALACAKBAKIYE,
  SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE YERELTUTAR END) OVER (PARTITION BY KUR ORDER BY SIRANO) AS YERELBAKIYE
  FROM seq)
SELECT row_number() OVER (ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID)::int AS SIRANO,
  q.CEKID, q.TARIH, q.AKSIYONTARIH, q.no, q.TUR, q.BASLIK, q.TURAD, q.REHBERID, q.KOD, q.AD, q.ACIKLAMA,
  q.HESAPID, q.HESAPKODU, q.HESAPADI, q.DURUM, q.BORC, q.ALACAK, q.KUR, q.YERELKUR, q.MASRAFID, q.MASRAFKOD,
  q.MASRAFAD, q.BORCBAKIYE, q.ALACAKBAKIYE, q.YERELTUTAR, q.YERELBAKIYE, q.SUBEID, q.VADETARIHI
FROM (
  -- devir (POS: BORC/ALACAK=0)
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar(20) AS no, 2::smallint AS TUR,
    ''::varchar(150) AS BASLIK, 'Devir'::varchar(50) AS TURAD, 0 AS REHBERID, ''::varchar(20) AS KOD, ''::varchar(100) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    SUM(BORC)::numeric AS BORC, SUM(ALACAK)::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR, 0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(100) AS MASRAFAD,
    (CASE WHEN SUM(BORC-ALACAK)>0 THEN SUM(BORC-ALACAK) ELSE 0 END)::numeric AS BORCBAKIYE,
    (CASE WHEN SUM(ALACAK-BORC)>0 THEN SUM(ALACAK-BORC) ELSE 0 END)::numeric AS ALACAKBAKIYE,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR,
    (CASE WHEN SUM(YERELTUTAR)>0 THEN SUM(YERELTUTAR) ELSE 0 END)::numeric AS YERELBAKIYE,
    SUBEID, p_bastar AS VADETARIHI
  FROM bal WHERE ((TUR IN (40,42,49)) OR (TUR NOT BETWEEN 40 AND 79)) AND TARIH < p_bastar GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1 AS devirsira, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU,
    HESAPADI, DURUM, BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, BORCBAKIYE, ALACAKBAKIYE, YERELTUTAR, YERELBAKIYE, SUBEID, VADETARIHI
  FROM bal WHERE TARIH >= p_bastar
) q
ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID;
$$;
