-- ============================================================================
-- Hesap-ekstre (PG portu): fn_Kasa_Nakit_Ekstre, fn_Kredi_Ekstre
-- 2-parca: KASA + FATBASLIK(masraf fatura). Yuruyen bakiye window (TUR 60-79 haric),
-- Devir (pre-bastar, variant filtre), sonra pre-bastar at. MSSQL cursor->window.
-- doviz cari = GENINI BOLUM=-10135. NOT: birebir; differential veriyle dogrulanmali.
-- ============================================================================

-- ========================================================== fn_kasa_nakit_ekstre
DROP FUNCTION IF EXISTS fn_kasa_nakit_ekstre(integer, timestamp, timestamp);
CREATE OR REPLACE FUNCTION fn_kasa_nakit_ekstre(p_id integer, p_bastar timestamp, p_bittar timestamp)
RETURNS TABLE("SIRANO" integer,"CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),
  "TUR" smallint,"BASLIK" varchar(150),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(150),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(150),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"KUR" varchar(6),"YERELKUR" numeric,"MASRAFID" integer,"MASRAFKOD" varchar(50),
  "MASRAFAD" varchar(100),"BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELTUTAR" numeric,"YERELBAKIYE" numeric,
  "SUBEID" integer,"VADETARIHI" timestamp)
LANGUAGE sql AS $$
WITH dc AS (SELECT ANAHTAR AS d FROM GENINI WHERE BOLUM=-10135 LIMIT 1),
mov AS (
  -- part1: KASA (HESAPTURU='K')
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.ISLEMTARIHI AS AKSIYONTARIH, K.BELGENO::varchar(20) AS no, K.TUR::smallint AS TUR,
    ''::varchar(150) AS BASLIK, KasaTurleri.ANAHTAR::varchar(50) AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT cast(ID as varchar(5)) FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT KODU FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END)::varchar(20) AS KOD,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'H' THEN (SELECT ADI FROM PARA_KUPON PK WHERE PK.ID=K.HESAPID)
       WHEN 'K' THEN (SELECT KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
       WHEN 'P' THEN (SELECT ADI FROM POS P WHERE P.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID)
       WHEN 'V' THEN (SELECT ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END)::varchar(150) AS AD,
    K.ACIKLAMA::varchar(500) AS ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END)::varchar(100) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END)::varchar(150) AS HESAPADI,
    K.DURUM::smallint AS DURUM, K.ALACAK::numeric AS BORC, K.BORC::numeric AS ALACAK, K.KUR::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END) / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END))::numeric AS YERELKUR,
    K.MASRAFID, M.KOD::varchar(50) AS MASRAFKOD, M.AD::varchar(100) AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
          WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
          ELSE K.ALACAK-K.BORC END)::numeric AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE extract(year from K.ISLEMTARIHI) >= extract(year from p_bastar)
    AND extract(year from K.ISLEMTARIHI) <= extract(year from p_bittar)
    AND K.ISLEMTARIHI <= p_bittar AND K.HESAPID=p_id AND K.HESAPTURU='K'

  UNION ALL

  -- part2: FATBASLIK (masraf fatura, REHBERID=-1*KasaID, TUR 13/17)
  SELECT F.ID AS CEKID, F.FATURATARIH AS TARIH, F.FATURATARIH AS AKSIYONTARIH, F.FATURANO::varchar(20) AS no, F.TUR::smallint AS TUR,
    F.BASLIK::varchar(150) AS BASLIK, (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=F.TUR LIMIT 1)::varchar(50) AS TURAD,
    F.REHBERID, R.KOD::varchar(20) AS KOD, R.FIRMA::varchar(150) AS AD, F.ACIKLAMA::varchar(500) AS ACIKLAMA,
    NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, F.DURUM::smallint AS DURUM,
    (CASE WHEN F.TUR IN (13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric AS BORC,
    (CASE WHEN F.TUR IN (17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric AS ALACAK,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_CINSI ELSE F.KUR END)::varchar(6) AS KUR,
    ABS((CASE WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (17) THEN F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (13) THEN -1*F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (17) THEN F.FATURA_TUTARI
              WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (13) THEN -1*F.FATURA_TUTARI END)
        / (CASE WHEN ((CASE WHEN F.TUR IN (13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                     -(CASE WHEN F.TUR IN (17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END))=0 THEN 1
                ELSE ((CASE WHEN F.TUR IN (13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                     -(CASE WHEN F.TUR IN (17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)) END))::numeric AS YERELKUR,
    F.MASRAFID, M.KOD::varchar(50) AS MASRAFKOD, M.AD::varchar(100) AS MASRAFAD,
    (CASE WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (17) THEN F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (13) THEN -1*F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (17) THEN F.FATURA_TUTARI
          WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (13) THEN -1*F.FATURA_TUTARI END)::numeric AS YERELTUTAR,
    F.SUBEID, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp AS VADETARIHI
  FROM FATBASLIK F
    LEFT JOIN REHBER R ON F.REHBERID=R.ID AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=F.MASRAFID
  WHERE F.REHBERID=-1*p_id
    AND extract(year from F.FATURATARIH) >= extract(year from p_bastar)
    AND extract(year from F.FATURATARIH) <= extract(year from p_bittar)
    AND F.FATURATARIH <= p_bittar AND F.REHBERID<0 AND F.TUR IN (13,17)
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, TARIH) AS SIRANO FROM mov),
bal AS (SELECT *,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS ALACAKBAKIYE,
  SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE YERELTUTAR END) OVER (PARTITION BY KUR ORDER BY SIRANO) AS YERELBAKIYE
  FROM seq)
SELECT row_number() OVER (ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID)::int AS SIRANO,
  q.CEKID, q.TARIH, q.AKSIYONTARIH, q.no, q.TUR, q.BASLIK, q.TURAD, q.REHBERID, q.KOD, q.AD, q.ACIKLAMA,
  q.HESAPID, q.HESAPKODU, q.HESAPADI, q.DURUM, q.BORC, q.ALACAK, q.KUR, q.YERELKUR, q.MASRAFID, q.MASRAFKOD,
  q.MASRAFAD, q.BORCBAKIYE, q.ALACAKBAKIYE, q.YERELTUTAR, q.YERELBAKIYE, q.SUBEID, q.VADETARIHI
FROM (
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar(20) AS no, 2::smallint AS TUR,
    ''::varchar(150) AS BASLIK, 'Devir'::varchar(50) AS TURAD, 0 AS REHBERID, ''::varchar(20) AS KOD, ''::varchar(150) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    SUM(BORC)::numeric AS BORC, SUM(ALACAK)::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR, 0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(100) AS MASRAFAD,
    (CASE WHEN SUM(BORC-ALACAK)>0 THEN SUM(BORC-ALACAK) ELSE 0 END)::numeric AS BORCBAKIYE,
    (CASE WHEN SUM(ALACAK-BORC)>0 THEN SUM(ALACAK-BORC) ELSE 0 END)::numeric AS ALACAKBAKIYE,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR,
    (CASE WHEN SUM(YERELTUTAR)>0 THEN SUM(YERELTUTAR) ELSE 0 END)::numeric AS YERELBAKIYE,
    SUBEID, p_bastar AS VADETARIHI
  FROM bal WHERE TUR IN (1,2,13,17,21,31,40,41,42,45,46,51,52,53,54) AND TARIH < p_bastar GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1 AS devirsira, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU,
    HESAPADI, DURUM, BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, BORCBAKIYE, ALACAKBAKIYE, YERELTUTAR, YERELBAKIYE, SUBEID, VADETARIHI
  FROM bal WHERE TARIH >= p_bastar
) q
ORDER BY q.KUR, q.TARIH, q.devirsira, q.CEKID;
$$;
