-- ============================================================================
-- fn_kredi_ekstre (PG portu): 2-parca KASA(HESAPTURU='R' kosullu swap + masraf) + FATBASLIK(masraf)
-- Param: (KrediID, BasTar, BitTar, MasrafGoster). Kolon adlari: ISLEMTARIHI/VALOR.
-- part1 ISLEMTARIHI>=bastar (devir bos kalir). Yuruyen bakiye window (TUR 60-79 haric).
-- @CariDov = GENINI BOLUM=-10135. NOT: birebir; differential veriyle dogrulanmali.
-- ============================================================================
DROP FUNCTION IF EXISTS fn_kredi_ekstre(integer, timestamp, timestamp, integer);
CREATE OR REPLACE FUNCTION fn_kredi_ekstre(p_id integer, p_bastar timestamp, p_bittar timestamp, p_masrafgoster integer)
-- NOT: kolon adlari TIRNAKSIZ (lowercase) -> app 'select * ... order by KUR' (tirnaksiz) PG'de
--   'kur'a fold eder; tirnakli "KUR" case-sensitive olsaydi eslesmezdi ("column kur does not exist").
--   FieldByName case-insensitive, select * kullanildigi icin app tarafi etkilenmez. MSSQL zaten CI.
RETURNS TABLE(sirano integer,cekid integer,islemtarihi timestamp,valor timestamp,no varchar(40),
  tur smallint,baslik varchar(250),turad varchar(100),rehberid integer,kod varchar(40),ad varchar(150),
  aciklama varchar(500),hesapid integer,hesapkodu varchar(100),hesapadi varchar(150),durum smallint,
  borc numeric,alacak numeric,kur varchar(6),yerelkur numeric,masrafid integer,masrafkod varchar(50),
  masrafad varchar(150),borcbakiye numeric,alacakbakiye numeric,yereltutar numeric,yerelbakiye numeric,
  subeid integer,vadetarihi timestamp)
LANGUAGE sql AS $$
WITH dc AS (SELECT ANAHTAR AS d FROM GENINI WHERE BOLUM=-10135 LIMIT 1),
mov AS (
  -- part1: KASA (kredi hareket, HESAPTURU='R' kosullu swap; + masraf YERI=47)
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS ISLEMTARIHI, K.PLANTARIHI AS VALOR, K.BELGENO::varchar(40) AS no, K.TUR::smallint AS TUR,
    ''::varchar(250) AS BASLIK, KasaTurleri.ANAHTAR::varchar(100) AS TURAD, K.HESAPID AS REHBERID,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT KREDIKODU FROM KREDILER KR WHERE KR.ID=K.HESAPID) END)::varchar(40) AS KOD,
    (CASE K.HESAPTURU WHEN 'B' THEN (SELECT HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
       WHEN 'R' THEN (SELECT ADI FROM KREDILER KR WHERE KR.ID=K.HESAPID) END)::varchar(150) AS AD,
    K.ACIKLAMA::varchar(500) AS ACIKLAMA, K.REHBERID AS HESAPID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END)::varchar(100) AS HESAPKODU,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END)::varchar(150) AS HESAPADI,
    K.DURUM::smallint AS DURUM,
    (CASE WHEN (K.HESAPID=p_id AND K.HESAPTURU='R') THEN K.ALACAK ELSE K.BORC END)::numeric AS BORC,
    (CASE WHEN (K.HESAPID=p_id AND K.HESAPTURU='R') THEN K.BORC ELSE K.ALACAK END)::numeric AS ALACAK,
    K.KUR::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.BORC>0 THEN -1*K.DOVIZ_TUTARI
              WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.ALACAK>0 THEN K.DOVIZ_TUTARI
              ELSE K.ALACAK-K.BORC END) / (CASE WHEN (K.ALACAK-K.BORC)=0 THEN 1 ELSE (K.ALACAK-K.BORC) END))::numeric AS YERELKUR,
    K.MASRAFID, M.KOD::varchar(50) AS MASRAFKOD, M.AD::varchar(150) AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.BORC>0 THEN (CASE WHEN (K.HESAPID=p_id AND K.HESAPTURU='R') THEN -1*K.DOVIZ_TUTARI ELSE K.DOVIZ_TUTARI END)
          WHEN K.DOVIZ_KURU=(SELECT d FROM dc) AND K.ALACAK>0 THEN (CASE WHEN (K.HESAPID=p_id AND K.HESAPTURU='R') THEN K.DOVIZ_TUTARI ELSE -1*K.DOVIZ_TUTARI END)
          ELSE (CASE WHEN (K.HESAPID=p_id AND K.HESAPTURU='R') THEN K.ALACAK-K.BORC ELSE K.BORC-K.ALACAK END) END)::numeric AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI
  FROM KASA K
    LEFT JOIN REHBER R ON R.ID=K.REHBERID
    LEFT JOIN GENINI KasaTurleri ON K.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
  WHERE K.ISLEMTARIHI>=p_bastar AND K.ISLEMTARIHI<=p_bittar
    AND ((K.HESAPID=p_id AND K.HESAPTURU='R') OR (p_masrafgoster=1 AND K.YERI=47 AND K.YERID=p_id))

  UNION ALL

  -- part2: FATBASLIK masraf (YERI=47)
  SELECT F.ID AS CEKID, F.FATURATARIH AS ISLEMTARIHI, F.TARIH AS VALOR, F.FATURANO::varchar(40) AS no, F.TUR::smallint AS TUR,
    F.BASLIK::varchar(250) AS BASLIK, (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=F.TUR LIMIT 1)::varchar(100) AS TURAD,
    F.REHBERID, R.KOD::varchar(40) AS KOD, R.FIRMA::varchar(150) AS AD, F.ACIKLAMA::varchar(500) AS ACIKLAMA,
    NULL::int AS HESAPID, M.KOD::varchar(100) AS HESAPKODU, M.AD::varchar(150) AS HESAPADI, F.DURUM::smallint AS DURUM,
    (CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 WHEN F.TIPI=5 THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric AS BORC,
    (CASE WHEN F.TUR IN (15,16,17) THEN 0.0 WHEN F.TIPI=5 THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric AS ALACAK,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_CINSI ELSE F.KUR END)::varchar(6) AS KUR,
    (CASE WHEN F.TIPI=5 THEN F.DOVIZKUR ELSE
      ABS((CASE WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (15,16,17) THEN F.DOVIZ_TUTARI
                WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (8,11,12,13) THEN -1*F.DOVIZ_TUTARI
                WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (15,16,17) THEN F.FATURA_TUTARI
                WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (8,11,12,13) THEN -1*F.FATURA_TUTARI END)
          / (CASE WHEN ((CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                       -(CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END))=0 THEN 1
                  ELSE ((CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                       -(CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)) END)) END)::numeric AS YERELKUR,
    F.MASRAFID, M.KOD::varchar(50) AS MASRAFKOD, M.AD::varchar(150) AS MASRAFAD,
    (CASE WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (15,16,17) THEN F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ=(SELECT d FROM dc) AND F.TUR IN (8,11,12,13) THEN -1*F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (15,16,17) THEN F.FATURA_TUTARI
          WHEN F.RAPORDOVIZ<>(SELECT d FROM dc) AND F.TUR IN (8,11,12,13) THEN -1*F.FATURA_TUTARI END)::numeric AS YERELTUTAR,
    F.SUBEID, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp AS VADETARIHI
  FROM FATBASLIK F
    LEFT JOIN REHBER R ON R.ID=F.REHBERID
    LEFT JOIN GENINI KasaTurleri ON F.TUR=KasaTurleri.DEGER AND KasaTurleri.DIL=-1 AND KasaTurleri.BOLUM=-1005
    LEFT JOIN MASRAFGELIR M ON M.ID=F.MASRAFID
  WHERE p_masrafgoster=1 AND F.FATURATARIH>=p_bastar AND F.FATURATARIH<=p_bittar AND F.YERI=47 AND F.YERID=p_id AND F.TUR IN (13,17)
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, ISLEMTARIHI) AS SIRANO FROM mov),
bal AS (SELECT *,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0) AS ALACAKBAKIYE,
  SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE YERELTUTAR END) OVER (PARTITION BY KUR ORDER BY SIRANO) AS YERELBAKIYE
  FROM seq)
SELECT row_number() OVER (ORDER BY q.KUR, q.ISLEMTARIHI, q.devirsira, q.CEKID)::int AS SIRANO,
  q.CEKID, q.ISLEMTARIHI, q.VALOR, q.no, q.TUR, q.BASLIK, q.TURAD, q.REHBERID, q.KOD, q.AD, q.ACIKLAMA,
  q.HESAPID, q.HESAPKODU, q.HESAPADI, q.DURUM, q.BORC, q.ALACAK, q.KUR, q.YERELKUR, q.MASRAFID, q.MASRAFKOD,
  q.MASRAFAD, q.BORCBAKIYE, q.ALACAKBAKIYE, q.YERELTUTAR, q.YERELBAKIYE, q.SUBEID, q.VADETARIHI
FROM (
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS ISLEMTARIHI, p_bastar AS VALOR, NULL::varchar(40) AS no, 2::smallint AS TUR,
    ''::varchar(250) AS BASLIK, 'Devir'::varchar(100) AS TURAD, 0 AS REHBERID, ''::varchar(40) AS KOD, ''::varchar(150) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    SUM(BORC)::numeric AS BORC, SUM(ALACAK)::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR, 0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(150) AS MASRAFAD,
    (CASE WHEN SUM(BORC-ALACAK)>0 THEN SUM(BORC-ALACAK) ELSE 0 END)::numeric AS BORCBAKIYE,
    (CASE WHEN SUM(ALACAK-BORC)>0 THEN SUM(ALACAK-BORC) ELSE 0 END)::numeric AS ALACAKBAKIYE,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR,
    (CASE WHEN SUM(YERELTUTAR)>0 THEN SUM(YERELTUTAR) ELSE 0 END)::numeric AS YERELBAKIYE,
    SUBEID, p_bastar AS VADETARIHI
  FROM bal WHERE ((TUR IN (40,42,49)) OR (TUR NOT BETWEEN 40 AND 79)) AND ISLEMTARIHI < p_bastar GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1 AS devirsira, CEKID, ISLEMTARIHI, VALOR, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU,
    HESAPADI, DURUM, BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, BORCBAKIYE, ALACAKBAKIYE, YERELTUTAR, YERELBAKIYE, SUBEID, VADETARIHI
  FROM bal WHERE ISLEMTARIHI >= p_bastar
) q
ORDER BY q.KUR, q.ISLEMTARIHI, q.devirsira, q.CEKID;
$$;
