-- ============================================================================
-- fn_prg_caridetayekstre2012 (PG portu, TVF-per-engine)
-- MSSQL: Sp_Prg_CariDetayEkstre2012 (@RehberID,@BasTar,@BitTar,@TurDurum)
-- 6 kaynak union: KASA + FATBASLIK(Tahakkuk TUR 13/17) + FATBASLIK(ek vergi EKVERGI<>0)
--   + FATBASLIK/FATURA(satir detay TUR 8/11/12/15/16) + CEK(CEKHAREKET) + SENET.
-- Detay surumde DEVIR YOK (MSSQL SP devir uretmez); SIRANO = row_number ORDER BY KUR,TARIH.
-- Final cikti 28 kolon: SIRANO/TURDURUM/ADET/BIRIM/BIRIMFIYAT PROJEKTE EDILMEZ; YERELTUTAR KUR'dan ONCE.
-- Window: BORCBAKIYE/ALACAKBAKIYE PARTITION BY KUR; YERELBAKIYE global (ORDER BY KUR,SIRANO) - verbatim.
-- Guardsiz bolme paydalari -> nullif(...,0) (PG sifir-bolme onle). @YERELKUR=GENINI -10135.
-- NOT: NOTLAR REHBER'de; MASRAFID kolonlari smallint/integer karisik -> ::int; differential dogrula.
-- ============================================================================
DROP FUNCTION IF EXISTS fn_prg_caridetayekstre2012(integer, timestamp, timestamp, integer);
CREATE OR REPLACE FUNCTION fn_prg_caridetayekstre2012(p_rehberid integer, p_bastar timestamp, p_bittar timestamp, p_turdurum integer)
RETURNS TABLE(
  "CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),"TUR" smallint,
  "BASLIK" varchar(250),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(100),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(250),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"YERELTUTAR" numeric,"KUR" varchar(6),"YERELKUR" numeric,
  "MASRAFID" integer,"MASRAFKOD" varchar(50),"MASRAFAD" varchar(200),"SUBEID" integer,"VADETARIHI" timestamp,
  "BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELBAKIYE" numeric)
LANGUAGE sql AS $$
WITH yk AS (SELECT ANAHTAR AS d FROM GENINI WHERE BOLUM=-10135 LIMIT 1),
har AS (
  -- KASA (Kasa Hareketleri)
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.PLANTARIHI AS AKSIYONTARIH, K.BELGENO::varchar(20) AS no, K.TUR::smallint AS TUR,
    (CASE WHEN K.TUR IN (61,71) THEN 1 ELSE 0 END)::smallint AS TURDURUM, ''::varchar(250) AS BASLIK, Turler.AD::varchar(50) AS TURAD, K.REHBERID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END)::varchar(20) AS KOD, (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END)::varchar(100) AS AD,
    K.ACIKLAMA::varchar(500) AS ACIKLAMA, K.HESAPID::int AS HESAPID,
    (CASE K.HESAPTURU WHEN 'B' THEN Banka.HESAPKODU WHEN 'H' THEN KS.KASAKODU||'('||PK.ADI||')' WHEN 'K' THEN KS.KASAKODU
       WHEN 'P' THEN POS.KODU WHEN 'V' THEN KK.KODU END)::varchar(100) AS HESAPKODU,
    (CASE K.HESAPTURU WHEN 'B' THEN Banka.HESAPADI WHEN 'H' THEN KS.KASAADI||'('||PK.ADI||')' WHEN 'K' THEN KS.KASAADI
       WHEN 'P' THEN POS.ADI WHEN 'V' THEN KK.ADI END)::varchar(250) AS HESAPADI,
    K.DURUM::smallint AS DURUM,
    (CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)::numeric AS BORC,
    (CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END)::numeric AS ALACAK,
    (CASE WHEN K.EKSTREDEKULLAN=1 THEN K.DOVIZ_KURU ELSE K.KUR END)::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=YK.d AND K.BORC>0 THEN K.DOVIZ_TUTARI WHEN K.DOVIZ_KURU=YK.d AND K.ALACAK>0 THEN -1*K.DOVIZ_TUTARI ELSE K.BORC-K.ALACAK END)
        / (CASE WHEN ((CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)-(CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END))=0 THEN 1
                ELSE ((CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)-(CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END)) END))::numeric AS YERELKUR,
    K.MASRAFID::int AS MASRAFID, M.KOD::varchar(50) AS MASRAFKOD, M.AD::varchar(200) AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=YK.d AND K.BORC>0 THEN K.DOVIZ_TUTARI WHEN K.DOVIZ_KURU=YK.d AND K.ALACAK>0 THEN -1*K.DOVIZ_TUTARI ELSE K.BORC-K.ALACAK END)::numeric AS YERELTUTAR,
    K.SUBEID::int AS SUBEID, K.ISLEMTARIHI AS VADETARIHI, 1.0::double precision AS ADET, ''::varchar(30) AS BIRIM, 0.0::numeric AS BIRIMFIYAT
  FROM KASA K
    LEFT JOIN REHBER R ON K.REHBERID=R.ID
    LEFT JOIN KASALAR KS ON KS.ID=K.HESAPID
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
    LEFT JOIN BANKAHESAPLAR Banka ON Banka.ID=K.HESAPID
    LEFT JOIN POS ON POS.ID=K.HESAPID
    LEFT JOIN KREDIKARTI KK ON KK.ID=K.HESAPID
    LEFT JOIN PARA_KUPON PK ON PK.ID=K.CEKSENETID
    INNER JOIN ISLEMTURLERI Turler ON Turler.TUR=K.TUR AND Turler.TIP=0
    CROSS JOIN yk YK
  WHERE K.REHBERID=p_rehberid AND extract(year from K.ISLEMTARIHI)>=extract(year from p_bastar) AND extract(year from K.ISLEMTARIHI)<=extract(year from p_bittar)
    AND K.ISLEMTARIHI<=p_bittar AND ((K.TUR IN (49,61,71)) OR (K.TUR NOT BETWEEN 40 AND 79))

  UNION ALL
  -- FATBASLIK (Tahakkuklar) TUR IN (13,17)
  SELECT F.ID, F.FATURATARIH, F.FATURATARIH, F.FATURANO::varchar(20), F.TUR::smallint,
    (CASE WHEN F.TUR IN (61,71) THEN 1 ELSE 0 END)::smallint, F.BASLIK::varchar(250), IT.AD::varchar(50), F.REHBERID,
    R.KOD::varchar(20), R.FIRMA::varchar(100), F.ACIKLAMA::varchar(500), NULL::int, NULL::varchar(100), NULL::varchar(250), F.DURUM::smallint,
    (CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric,
    (CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_CINSI ELSE F.KUR END)::varchar(6),
    ABS((CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (15,16,17) THEN F.DOVIZ_TUTARI WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12,13) THEN -1*F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (15,16,17) THEN F.FATURA_TUTARI WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12,13) THEN -1*F.FATURA_TUTARI END)
        / (CASE WHEN ((CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                     -(CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END))=0 THEN 1
                ELSE ((CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                     -(CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)) END))::numeric,
    F.MASRAFID::int, M.KOD::varchar(50), M.AD::varchar(200),
    (CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (15,16,17) THEN F.DOVIZ_TUTARI WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12,13) THEN -1*F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (15,16,17) THEN F.FATURA_TUTARI WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12,13) THEN -1*F.FATURA_TUTARI END)::numeric,
    F.SUBEID::int, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp, 1.0::double precision, ''::varchar(30), 0.0::numeric
  FROM FATBASLIK F
    INNER JOIN REHBER R ON F.REHBERID=R.ID AND F.TUR IN (8,11,12,13,15,16,17) AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=F.MASRAFID
    INNER JOIN ISLEMTURLERI IT ON IT.TUR=F.TUR AND IT.TIP IN (0,1)
    CROSS JOIN yk YK
  WHERE F.REHBERID=p_rehberid AND extract(year from F.FATURATARIH)>=extract(year from p_bastar) AND extract(year from F.FATURATARIH)<=extract(year from p_bittar)
    AND F.FATURATARIH<=p_bittar AND F.TUR IN (13,17)

  UNION ALL
  -- FATBASLIK (ek vergiler) EKVERGI<>0
  SELECT F.ID, F.FATURATARIH, F.FATURATARIH, F.FATURANO::varchar(20), F.TUR::smallint,
    (CASE WHEN F.TUR IN (61,71) THEN 1 ELSE 0 END)::smallint, F.BASLIK::varchar(250), IT.AD::varchar(50), F.REHBERID,
    R.KOD::varchar(20), R.FIRMA::varchar(100), F.ACIKLAMA::varchar(500), NULL::int, NULL::varchar(100), NULL::varchar(250), F.DURUM::smallint,
    (CASE WHEN F.KUR=F.DOVIZ_CINSI THEN (CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE F.EKVERGI END)
          ELSE ((CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE F.EKVERGI END)/nullif(F.DOVIZKUR,0)) END)::numeric,
    (CASE WHEN F.KUR=F.DOVIZ_CINSI THEN (CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE F.EKVERGI END)
          ELSE ((CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE F.EKVERGI END)/nullif(F.DOVIZKUR,0)) END)::numeric,
    F.DOVIZ_CINSI::varchar(6),
    0::numeric,
    F.MASRAFID::int, M.KOD::varchar(50), M.AD::varchar(200),
    (CASE WHEN F.TUR IN (8,11,12,13) THEN F.EKVERGI WHEN F.TUR IN (15,16,17) THEN -1*F.EKVERGI END)::numeric,
    F.SUBEID::int, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp, 1.0::double precision, ''::varchar(30), 0.0::numeric
  FROM FATBASLIK F
    INNER JOIN REHBER R ON F.REHBERID=R.ID AND F.TUR IN (8,11,12,13,15,16,17) AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=F.MASRAFID
    INNER JOIN ISLEMTURLERI IT ON IT.TUR=F.TUR AND IT.TIP IN (0,1)
    CROSS JOIN yk YK
  WHERE F.REHBERID=p_rehberid AND coalesce(F.EKVERGI,0.0)<>0.0
    AND extract(year from F.FATURATARIH)>=extract(year from p_bastar) AND extract(year from F.FATURATARIH)<=extract(year from p_bittar)
    AND F.FATURATARIH<=p_bittar

  UNION ALL
  -- FATBASLIK / FATURA (Fatura Detaylari) TUR IN (8,11,12,15,16)
  SELECT F.ID, F.FATURATARIH, F.FATURATARIH, F.FATURANO::varchar(20), F.TUR::smallint,
    (CASE WHEN F.TUR IN (61,71) THEN 1 ELSE 0 END)::smallint, F.BASLIK::varchar(250), IT.AD::varchar(50), F.REHBERID,
    R.KOD::varchar(20), R.FIRMA::varchar(100), FA.ACIKLAMA::varchar(500), FA.URUNID::int,
    (CASE WHEN FA.TUR IN (1,11) THEN (SELECT KOD FROM STOKLAR WHERE ID=FA.URUNID) ELSE (SELECT KOD FROM MASRAFGELIR WHERE ID=FA.URUNID) END)::varchar(100),
    (CASE WHEN FA.TUR IN (1,11) THEN (SELECT STOKADI FROM STOKLAR WHERE ID=FA.URUNID) ELSE (SELECT AD FROM MASRAFGELIR WHERE ID=FA.URUNID) END)::varchar(250),
    F.DURUM::smallint,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE FA.DOVIZ_TUTARI END)
          ELSE (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (CASE WHEN F.KDVDURUM='Dahil' THEN FA.TUTAR ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END) END)::numeric,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE FA.DOVIZ_TUTARI END)
          ELSE (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (CASE WHEN F.KDVDURUM='Dahil' THEN FA.TUTAR ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END) END)::numeric,
    F.DOVIZ_CINSI::varchar(6),
    ABS((CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12) THEN F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12) THEN -1*F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12) THEN F.FATURA_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12) THEN -1*F.FATURA_TUTARI END)
        / nullif((CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END) ELSE (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END)
                -(CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END) ELSE (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END),0))::numeric,
    F.MASRAFID::int, M.KOD::varchar(50), M.AD::varchar(200),
    (CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12) THEN F.DOVIZ_TUTARI WHEN F.DOVIZ_CINSI='TL' AND F.TUR IN (8,11,12) THEN -1*F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12) THEN F.FATURA_TUTARI WHEN F.DOVIZ_CINSI<>'TL' AND F.TUR IN (8,11,12) THEN -1*F.FATURA_TUTARI END)::numeric,
    F.SUBEID::int, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp, FA.ADET::double precision,
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-2702 AND DIL=-1 AND DEGER=FA.BIRIM LIMIT 1)::varchar(30),
    (CASE WHEN F.KUR=F.DOVIZ_CINSI THEN ((FA.TUTAR*(FA.KDV+100)/100)/nullif(FA.ADET,0))
          ELSE (((FA.TUTAR*(FA.KDV+100)/100)/nullif(FA.ADET,0))/nullif(F.DOVIZKUR,0)) END)::numeric
  FROM FATBASLIK F INNER JOIN FATURA FA ON F.ID=FA.FATBASID
    INNER JOIN REHBER R ON F.REHBERID=R.ID AND F.TUR IN (8,11,12,15,16) AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=FA.MASRAFID
    INNER JOIN ISLEMTURLERI IT ON IT.TUR=F.TUR AND IT.TIP IN (0,1)
    CROSS JOIN yk YK
  WHERE F.REHBERID=p_rehberid AND extract(year from F.FATURATARIH)>=extract(year from p_bastar) AND extract(year from F.FATURATARIH)<=extract(year from p_bittar)
    AND F.FATURATARIH<=p_bittar AND F.TUR IN (8,11,12,15,16)

  UNION ALL
  -- CEK (CEKHAREKET)
  SELECT C.ID, CH.TARIH, C.VADE, C.MAKBUZNO::varchar(20), (CASE WHEN CH.ISLEM IN (130,141) THEN 23 ELSE 33 END)::smallint,
    0::smallint, ''::varchar(250),
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=(CASE WHEN CH.ISLEM IN (130,141) THEN 23 ELSE 33 END) AND DIL=-1 LIMIT 1)::varchar(50),
    CH.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100), ('Serino:'||C.SERINO::varchar||' '||rtrim(coalesce(CH.ACIKLAMA,'')))::varchar(500),
    CH.BANKAHESAPLARID::int, BH.HESAPKODU::varchar(100), BH.HESAPADI::varchar(250), C.DURUM::smallint,
    (CASE WHEN CH.ISLEM IN (140,131,132,133,134,137) THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN CH.ISLEM IN (130,141) THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_KURU ELSE coalesce(C.KUR,'TL') END)::varchar(6),
    ABS((CASE WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (140,131,132,133,134,137) THEN C.DOVIZ_TUTARI
              WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (130,141) THEN -1*C.DOVIZ_TUTARI END)
        / nullif(((CASE WHEN CH.ISLEM IN (140,131,132,133,134,137) THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)
                 -(CASE WHEN CH.ISLEM IN (130,141) THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)),0))::numeric,
    C.MASRAFID::int, M.KOD::varchar(50), M.AD::varchar(200),
    (CASE WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (140,131,132,133,134,137) THEN C.DOVIZ_TUTARI
          WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (130,141) THEN -1*C.DOVIZ_TUTARI
          WHEN C.DOVIZ_KURU<>YK.d AND CH.ISLEM IN (140,131,132,133,134,137) THEN C.TUTAR
          WHEN C.DOVIZ_KURU<>YK.d AND CH.ISLEM IN (130,141) THEN -1*C.TUTAR END)::numeric,
    C.SUBEID::int, C.VADE, 1.0::double precision, ''::varchar(30), 0.0::numeric
  FROM CEKLER C INNER JOIN CEKHAREKET CH ON C.ID=CH.CEKSENETLERID
    LEFT JOIN REHBER R ON CH.REHBERID=R.ID
    LEFT JOIN BANKAHESAPLAR BH ON CH.BANKAHESAPLARID=BH.ID
    LEFT JOIN MASRAFGELIR M ON M.ID=C.MASRAFID
    CROSS JOIN yk YK
  WHERE CH.REHBERID=p_rehberid AND extract(year from CH.TARIH)>=extract(year from p_bastar) AND extract(year from CH.TARIH)<=extract(year from p_bittar)
    AND CH.TARIH<=p_bittar AND CH.ISLEM IN (130,131,132,134,137,140,141)

  UNION ALL
  -- SENET
  SELECT C.ID, C.TARIH, C.VADE, C.MAKBUZNO::varchar(20), C.TUR::smallint,
    (CASE WHEN C.TUR IN (61,71) THEN 1 ELSE 0 END)::smallint, ''::varchar(250), IT.AD::varchar(50),
    C.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100), rtrim(coalesce(R.NOTLAR,''))::varchar(500), NULL::int, NULL::varchar(100), NULL::varchar(250), C.DURUM::smallint,
    (CASE WHEN C.TUR=34 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN C.TUR=24 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_KURU ELSE coalesce(C.KUR,'TL') END)::varchar(6),
    ABS((CASE WHEN C.DOVIZ_KURU=YK.d AND C.TUR=34 THEN C.DOVIZ_TUTARI WHEN C.DOVIZ_KURU=YK.d AND C.TUR=24 THEN -1*C.DOVIZ_TUTARI
              WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=34 THEN C.TUTAR WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=24 THEN -1*C.TUTAR END)
        / nullif(((CASE WHEN C.TUR=34 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)
                 -(CASE WHEN C.TUR=24 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)),0))::numeric,
    C.MASRAFID::int, M.KOD::varchar(50), M.AD::varchar(200),
    (CASE WHEN C.DOVIZ_KURU=YK.d AND C.TUR=34 THEN C.DOVIZ_TUTARI WHEN C.DOVIZ_KURU=YK.d AND C.TUR=24 THEN -1*C.DOVIZ_TUTARI
          WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=34 THEN C.TUTAR WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=24 THEN -1*C.TUTAR END)::numeric,
    C.SUBEID::int, C.VADE, 1.0::double precision, ''::varchar(30), 0.0::numeric
  FROM SENETLER C
    INNER JOIN REHBER R ON C.REHBERID=R.ID
    LEFT JOIN MASRAFGELIR M ON M.ID=C.MASRAFID
    INNER JOIN ISLEMTURLERI IT ON IT.TUR=C.TUR AND IT.TIP=0
    CROSS JOIN yk YK
  WHERE C.REHBERID=p_rehberid AND extract(year from C.TARIH)>=extract(year from p_bastar) AND extract(year from C.TARIH)<=extract(year from p_bittar)
    AND C.TARIH<=p_bittar
),
seq AS (SELECT *, row_number() OVER (ORDER BY KUR, TARIH, CEKID)::int AS SIRANO FROM har)
SELECT CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU, HESAPADI, DURUM,
  (CASE WHEN TUR=2 AND ACIKLAMA='Ara Devir' THEN 0 ELSE BORC END)::numeric AS BORC,
  (CASE WHEN TUR=2 AND ACIKLAMA='Ara Devir' THEN 0 ELSE ALACAK END)::numeric AS ALACAK,
  (CASE WHEN TUR=2 THEN 0 ELSE YERELTUTAR END)::numeric AS YERELTUTAR,
  KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, SUBEID, VADETARIHI,
  (CASE WHEN SUM(BORC-ALACAK) OVER (PARTITION BY KUR ORDER BY KUR, SIRANO)>0 THEN SUM(BORC-ALACAK) OVER (PARTITION BY KUR ORDER BY KUR, SIRANO) ELSE 0 END)::numeric AS BORCBAKIYE,
  (CASE WHEN SUM(ALACAK-BORC) OVER (PARTITION BY KUR ORDER BY KUR, SIRANO)>0 THEN SUM(ALACAK-BORC) OVER (PARTITION BY KUR ORDER BY KUR, SIRANO) ELSE 0 END)::numeric AS ALACAKBAKIYE,
  (SUM(YERELTUTAR) OVER (ORDER BY KUR, SIRANO))::numeric AS YERELBAKIYE
FROM seq
WHERE TURDURUM=p_turdurum
ORDER BY KUR, SIRANO;
$$;
