-- ============================================================================
-- fn_cari_detayli_ekstre (PG portu, TVF-per-engine)
-- MSSQL: fn_Cari_Detayli_Ekstre(@RehberID, @BasTar, @BitTar)
-- 6 kaynak union: KASA + FATBASLIK(tahakkuk) + FATBASLIK(ek vergi) + FATBASLIK(fatura detay)
--                 + CEK(CEKHAREKET) + SENET; Devir(pre-BasTar aggregate) + hareketler.
-- Running balance (MSSQL per-KUR cursor, TUR 60-79 haric) -> window:
--   BORCBAKIYE  = greatest(SUM(CASE 60..79->0 ELSE BORC-ALACAK END) OVER(PARTITION BY KUR ORDER BY SIRANO),0)
--   ALACAKBAKIYE= greatest(SUM(CASE 60..79->0 ELSE ALACAK-BORC END) OVER(PARTITION BY KUR ORDER BY SIRANO),0)
--   YERELBAKIYE =          SUM(CASE 60..79->0 ELSE YERELTUTAR  END) OVER(PARTITION BY KUR ORDER BY SIRANO)
-- #tmp IDENTITY SIRANO -> row_number() (Devir devirsira=0 once). @YERELKUR = GENINI BOLUM=-10135.
-- Guardsiz bolme paydalari -> nullif(...,0). NOT: differential dogrula.
-- ============================================================================
DROP FUNCTION IF EXISTS fn_cari_detayli_ekstre(integer, timestamp, timestamp);
CREATE OR REPLACE FUNCTION fn_cari_detayli_ekstre(p_rehberid integer, p_bastar timestamp, p_bittar timestamp)
RETURNS TABLE(
  "SIRANO" integer,"CEKID" integer,"TARIH" timestamp,"AKSIYONTARIH" timestamp,"NO" varchar(20),"TUR" smallint,
  "BASLIK" varchar(150),"TURAD" varchar(50),"REHBERID" integer,"KOD" varchar(20),"AD" varchar(100),
  "ACIKLAMA" varchar(500),"HESAPID" integer,"HESAPKODU" varchar(100),"HESAPADI" varchar(150),"DURUM" smallint,
  "BORC" numeric,"ALACAK" numeric,"KUR" varchar(6),"YERELKUR" numeric,"MASRAFID" integer,"MASRAFKOD" varchar(50),
  "MASRAFAD" varchar(100),"BORCBAKIYE" numeric,"ALACAKBAKIYE" numeric,"YERELTUTAR" numeric,"YERELBAKIYE" numeric,
  "SUBEID" integer,"VADETARIHI" timestamp,"ADET" double precision,"BIRIM" varchar(20),"BIRIMFIYAT" numeric)
LANGUAGE sql AS $$
WITH yk AS (SELECT ANAHTAR AS d FROM GENINI WHERE BOLUM=-10135 LIMIT 1),
har AS (
  -- ============================ KASA ============================
  SELECT K.ID AS CEKID, K.ISLEMTARIHI AS TARIH, K.PLANTARIHI AS AKSIYONTARIH, K.BELGENO::varchar(20) AS no,
    K.TUR::smallint AS TUR, ''::varchar(150) AS BASLIK,
    (CASE WHEN CAST(K.TUR AS varchar) LIKE '26__' THEN (SELECT ANAHTAR||' tahsilatı ' FROM GENINI WHERE BOLUM=-2329 AND 2600+DEGER=K.TUR LIMIT 1)
          WHEN CAST(K.TUR AS varchar) LIKE '36__' THEN (SELECT ANAHTAR||' ödemesi ' FROM GENINI WHERE BOLUM=-2329 AND 3600+DEGER=K.TUR LIMIT 1)
          ELSE (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=K.TUR LIMIT 1) END)::varchar(50) AS TURAD,
    K.REHBERID,
    (CASE WHEN K.REHBERID=0 THEN M.KOD ELSE R.KOD END)::varchar(20) AS KOD,
    (CASE WHEN K.REHBERID=0 THEN M.AD ELSE R.FIRMA END)::varchar(100) AS AD,
    K.ACIKLAMA::varchar(500) AS ACIKLAMA, K.HESAPID,
    (CASE K.HESAPTURU
        WHEN 'B' THEN (SELECT BH.HESAPKODU FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
        WHEN 'H' THEN (SELECT K2.KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)||coalesce(' ('||(SELECT PK.ADI FROM PARA_KUPON PK WHERE PK.ID=K.CEKSENETID)||')','')
        WHEN 'K' THEN (SELECT K2.KASAKODU FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
        WHEN 'P' THEN (SELECT P.KODU FROM POS P WHERE P.ID=K.HESAPID)
        WHEN 'V' THEN (SELECT KK.KODU FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END)::varchar(100) AS HESAPKODU,
    (CASE K.HESAPTURU
        WHEN 'B' THEN (SELECT BH.HESAPADI FROM BANKAHESAPLAR BH WHERE BH.ID=K.HESAPID)
        WHEN 'H' THEN (SELECT K2.KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)||coalesce(' ('||(SELECT PK.ADI FROM PARA_KUPON PK WHERE PK.ID=K.CEKSENETID)||')','')
        WHEN 'K' THEN (SELECT K2.KASAADI FROM KASALAR K2 WHERE K2.ID=K.HESAPID)
        WHEN 'P' THEN (SELECT P.ADI FROM POS P WHERE P.ID=K.HESAPID)
        WHEN 'V' THEN (SELECT KK.ADI FROM KREDIKARTI KK WHERE KK.ID=K.HESAPID) END)::varchar(150) AS HESAPADI,
    K.DURUM::smallint AS DURUM,
    (CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)::numeric AS BORC,
    (CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END)::numeric AS ALACAK,
    (CASE WHEN K.EKSTREDEKULLAN=1 THEN K.DOVIZ_KURU ELSE K.KUR END)::varchar(6) AS KUR,
    ABS((CASE WHEN K.DOVIZ_KURU=YK.d AND K.BORC>0 THEN K.DOVIZ_TUTARI WHEN K.DOVIZ_KURU=YK.d AND K.ALACAK>0 THEN -1*K.DOVIZ_TUTARI ELSE K.BORC-K.ALACAK END)
        / (CASE WHEN ((CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)-(CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END))=0 THEN 1
                ELSE ((CASE WHEN K.EKSTREDEKULLAN=1 AND K.BORC>0 THEN K.DOVIZ_TUTARI ELSE K.BORC END)-(CASE WHEN K.EKSTREDEKULLAN=1 AND K.ALACAK>0 THEN K.DOVIZ_TUTARI ELSE K.ALACAK END)) END))::numeric AS YERELKUR,
    K.MASRAFID, M.KOD::varchar(50) AS MASRAFKOD, M.AD::varchar(100) AS MASRAFAD,
    (CASE WHEN K.DOVIZ_KURU=YK.d AND K.BORC>0 THEN K.DOVIZ_TUTARI WHEN K.DOVIZ_KURU=YK.d AND K.ALACAK>0 THEN -1*K.DOVIZ_TUTARI ELSE K.BORC-K.ALACAK END)::numeric AS YERELTUTAR,
    K.SUBEID, K.ISLEMTARIHI AS VADETARIHI, 1.0::double precision AS ADET, ''::varchar(20) AS BIRIM, 0.0::numeric AS BIRIMFIYAT
  FROM KASA K
    LEFT JOIN REHBER R ON K.REHBERID=R.ID
    LEFT JOIN MASRAFGELIR M ON M.ID=K.MASRAFID
    CROSS JOIN yk YK
  WHERE K.REHBERID=p_rehberid
    AND extract(year from K.ISLEMTARIHI)>=extract(year from p_bastar) AND extract(year from K.ISLEMTARIHI)<=extract(year from p_bittar)
    AND K.ISLEMTARIHI<=p_bittar AND ((K.TUR IN (49)) OR (K.TUR NOT BETWEEN 40 AND 79))

  UNION ALL
  -- ==================== FATBASLIK (tahakkuklar, TUR 13/17) ====================
  SELECT F.ID, F.FATURATARIH, F.FATURATARIH, F.FATURANO::varchar(20), F.TUR::smallint, F.BASLIK::varchar(150),
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=F.TUR LIMIT 1)::varchar(50),
    F.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100), F.ACIKLAMA::varchar(500),
    NULL::int, NULL::varchar(100), NULL::varchar(150), F.DURUM::smallint,
    (CASE WHEN F.TUR IN (13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric,
    (CASE WHEN F.TUR IN (17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)::numeric,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_CINSI ELSE F.KUR END)::varchar(6),
    ABS((CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (13) THEN F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (17) THEN -1*F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (13) THEN F.FATURA_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (17) THEN -1*F.FATURA_TUTARI END)
        / (CASE WHEN ((CASE WHEN F.TUR IN (13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                     -(CASE WHEN F.TUR IN (17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END))=0 THEN 1
                ELSE ((CASE WHEN F.TUR IN (13) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)
                     -(CASE WHEN F.TUR IN (17) THEN 0.0 ELSE (CASE WHEN F.EKSTREDEKULLAN=1 THEN F.DOVIZ_TUTARI ELSE F.FATURA_TUTARI END) END)) END))::numeric,
    F.MASRAFID, M.KOD::varchar(50), M.AD::varchar(100),
    (CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (13) THEN F.DOVIZ_TUTARI WHEN F.DOVIZ_CINSI=YK.d AND F.TUR IN (17) THEN -1*F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (13) THEN F.FATURA_TUTARI WHEN F.DOVIZ_CINSI<>YK.d AND F.TUR IN (17) THEN -1*F.FATURA_TUTARI END)::numeric,
    F.SUBEID, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp, 1.0::double precision, ''::varchar(20), 0.0::numeric
  FROM FATBASLIK F
    INNER JOIN REHBER R ON F.REHBERID=R.ID AND F.TUR IN (13,17) AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=F.MASRAFID
    CROSS JOIN yk YK
  WHERE F.REHBERID=p_rehberid
    AND extract(year from F.FATURATARIH)>=extract(year from p_bastar) AND extract(year from F.FATURATARIH)<=extract(year from p_bittar)
    AND F.FATURATARIH<=p_bittar AND F.TUR IN (13,17)

  UNION ALL
  -- ==================== FATBASLIK (ek vergiler) ====================
  SELECT F.ID, F.FATURATARIH, F.FATURATARIH, F.FATURANO::varchar(20), F.TUR::smallint, F.BASLIK::varchar(150),
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=F.TUR LIMIT 1)::varchar(50),
    F.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100), F.ACIKLAMA::varchar(500),
    NULL::int, NULL::varchar(100), NULL::varchar(150), F.DURUM::smallint,
    (CASE WHEN F.KUR=F.DOVIZ_CINSI THEN (CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE F.EKVERGI END)
          ELSE ((CASE WHEN F.TUR IN (8,11,12,13) THEN 0.0 ELSE F.EKVERGI END)/nullif(F.DOVIZKUR,0)) END)::numeric,
    (CASE WHEN F.KUR=F.DOVIZ_CINSI THEN (CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE F.EKVERGI END)
          ELSE ((CASE WHEN F.TUR IN (15,16,17) THEN 0.0 ELSE F.EKVERGI END)/nullif(F.DOVIZKUR,0)) END)::numeric,
    F.DOVIZ_CINSI::varchar(6),
    0::numeric,
    F.MASRAFID, M.KOD::varchar(50), M.AD::varchar(100),
    (CASE WHEN F.TUR IN (8,11,12,13) THEN F.EKVERGI WHEN F.TUR IN (15,16,17) THEN -1*F.EKVERGI END)::numeric,
    F.SUBEID, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp, 1.0::double precision, ''::varchar(20), 0.0::numeric
  FROM FATBASLIK F
    INNER JOIN REHBER R ON F.REHBERID=R.ID AND F.TUR IN (8,11,12,13,15,16,17) AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=F.MASRAFID
  WHERE F.REHBERID=p_rehberid
    AND coalesce(F.EKVERGI,0.0)<>0.0
    AND extract(year from F.FATURATARIH)>=extract(year from p_bastar) AND extract(year from F.FATURATARIH)<=extract(year from p_bittar)
    AND F.FATURATARIH<=p_bittar

  UNION ALL
  -- ==================== FATBASLIK (fatura detaylari) ====================
  SELECT F.ID, F.FATURATARIH, F.FATURATARIH, F.FATURANO::varchar(20), F.TUR::smallint, F.BASLIK::varchar(150),
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=F.TUR LIMIT 1)::varchar(50),
    F.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100), FA.ACIKLAMA::varchar(500),
    FA.URUNID,
    (CASE WHEN FA.TUR IN (1,11) THEN (SELECT KOD FROM STOKLAR WHERE ID=FA.URUNID LIMIT 1)
          ELSE (SELECT KOD FROM MASRAFGELIR WHERE ID=FA.URUNID LIMIT 1) END)::varchar(100),
    (CASE WHEN FA.TUR IN (1,11) THEN (SELECT STOKADI FROM STOKLAR WHERE ID=FA.URUNID LIMIT 1)
          ELSE (SELECT AD FROM MASRAFGELIR WHERE ID=FA.URUNID LIMIT 1) END)::varchar(150),
    F.DURUM::smallint,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END)
          ELSE (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END)::numeric,
    (CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END)
          ELSE (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END)::numeric,
    F.DOVIZ_CINSI::varchar(6),
    ABS((CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12) THEN F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12) THEN -1*F.DOVIZ_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12) THEN F.FATURA_TUTARI
              WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12) THEN -1*F.FATURA_TUTARI END)
        / (CASE WHEN ((CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END) ELSE (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END)
                     -(CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END) ELSE (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END))=0 THEN 1
                ELSE ((CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END) ELSE (CASE WHEN F.TUR IN (8,11,12) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END)
                     -(CASE WHEN F.EKSTREDEKULLAN=1 THEN (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.DOVIZ_TUTARI*(FA.KDV+100)/100) END) ELSE (CASE WHEN F.TUR IN (15,16) THEN 0.0 ELSE (FA.TUTAR*(FA.KDV+100)/100) END) END)) END))::numeric,
    F.MASRAFID, M.KOD::varchar(50), M.AD::varchar(100),
    (CASE WHEN F.RAPORDOVIZ=YK.d AND F.TUR IN (8,11,12) THEN F.DOVIZ_TUTARI WHEN F.DOVIZ_CINSI='TL' AND F.TUR IN (8,11,12) THEN -1*F.DOVIZ_TUTARI
          WHEN F.RAPORDOVIZ<>YK.d AND F.TUR IN (8,11,12) THEN F.FATURA_TUTARI WHEN F.DOVIZ_CINSI<>'TL' AND F.TUR IN (8,11,12) THEN -1*F.FATURA_TUTARI END)::numeric,
    F.SUBEID, (F.FATURATARIH + (coalesce(F.VADE,0)*interval '1 day'))::timestamp,
    FA.ADET::double precision,
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-2702 AND DIL=-1 AND DEGER=FA.BIRIM LIMIT 1)::varchar(20),
    (CASE WHEN F.KUR=F.DOVIZ_CINSI THEN ((FA.TUTAR*(FA.KDV+100)/100)/nullif(FA.ADET,0))
          ELSE (((FA.TUTAR*(FA.KDV+100)/100)/nullif(FA.ADET,0))/nullif(F.DOVIZKUR,0)) END)::numeric
  FROM FATBASLIK F INNER JOIN FATURA FA ON F.ID=FA.FATBASID
    INNER JOIN REHBER R ON F.REHBERID=R.ID AND F.TUR IN (8,11,12,15,16) AND coalesce(F.DURUM,0)<>6
    LEFT JOIN MASRAFGELIR M ON M.ID=FA.MASRAFID
    CROSS JOIN yk YK
  WHERE F.REHBERID=p_rehberid
    AND extract(year from F.FATURATARIH)>=extract(year from p_bastar) AND extract(year from F.FATURATARIH)<=extract(year from p_bittar)
    AND F.FATURATARIH<=p_bittar AND F.TUR IN (8,11,12,15,16)

  UNION ALL
  -- ==================== CEK (CEKHAREKET) ====================
  SELECT C.ID, CH.TARIH, C.VADE, C.MAKBUZNO::varchar(20),
    (CASE WHEN CH.ISLEM BETWEEN 130 AND 139 AND C.CEKSENET=1 THEN 23
          WHEN CH.ISLEM BETWEEN 140 AND 149 AND C.CEKSENET=1 THEN 33
          WHEN CH.ISLEM BETWEEN 130 AND 139 AND C.CEKSENET=2 THEN 24
          WHEN CH.ISLEM BETWEEN 140 AND 149 AND C.CEKSENET=2 THEN 44
          ELSE 0 END)::smallint,
    ''::varchar(150),
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=(CASE WHEN CH.ISLEM IN (130,141) THEN 23 ELSE 33 END) AND DIL=-1 LIMIT 1)::varchar(50),
    CH.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100),
    ('Serino: '||C.SERINO::varchar||rtrim(coalesce(CH.ACIKLAMA,'')))::varchar(500),
    CH.BANKAHESAPLARID, BH.HESAPKODU::varchar(100), BH.HESAPADI::varchar(150), C.DURUM::smallint,
    (CASE WHEN CH.ISLEM IN (140,131,132,133,134,137) THEN (CASE WHEN CH.EKSTREDEKULLAN=1 THEN CH.TUTAR ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN CH.ISLEM IN (130,141) THEN (CASE WHEN CH.EKSTREDEKULLAN=1 THEN CH.TUTAR ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN CH.EKSTREDEKULLAN=1 THEN CH.KUR ELSE coalesce(C.KUR,'TL') END)::varchar(6),
    ABS((CASE WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (140,131,132,133,134,137) THEN C.DOVIZ_TUTARI
              WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (130,141) THEN -1*C.DOVIZ_TUTARI END)
        / nullif(((CASE WHEN CH.ISLEM IN (140,131,132,133,134,137) THEN (CASE WHEN CH.EKSTREDEKULLAN=1 THEN CH.TUTAR ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)
                 -(CASE WHEN CH.ISLEM IN (130,141) THEN (CASE WHEN CH.EKSTREDEKULLAN=1 THEN CH.TUTAR ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)),0))::numeric,
    C.MASRAFID, M.KOD::varchar(50), M.AD::varchar(100),
    (CASE WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (140,131,132,133,134,137) THEN C.DOVIZ_TUTARI
          WHEN C.DOVIZ_KURU=YK.d AND CH.ISLEM IN (130,141) THEN -1*C.DOVIZ_TUTARI
          WHEN C.DOVIZ_KURU<>YK.d AND CH.ISLEM IN (140,131,132,133,134,137) THEN C.TUTAR
          WHEN C.DOVIZ_KURU<>YK.d AND CH.ISLEM IN (130,141) THEN -1*C.TUTAR END)::numeric,
    C.SUBEID, C.VADE, 1.0::double precision, ''::varchar(20), 0.0::numeric
  FROM CEKLER C INNER JOIN CEKHAREKET CH ON C.ID=CH.CEKSENETLERID
    LEFT JOIN REHBER R ON CH.REHBERID=R.ID
    LEFT JOIN BANKAHESAPLAR BH ON CH.BANKAHESAPLARID=BH.ID
    LEFT JOIN MASRAFGELIR M ON M.ID=C.MASRAFID
    CROSS JOIN yk YK
  WHERE CH.ISLEM IN (130,131,132,134,137,140,141) AND CH.REHBERID=p_rehberid
    AND extract(year from CH.TARIH)>=extract(year from p_bastar) AND extract(year from CH.TARIH)<=extract(year from p_bittar)
    AND CH.TARIH<=p_bittar

  UNION ALL
  -- ==================== SENET ====================
  SELECT C.ID, C.TARIH, C.VADE, C.MAKBUZNO::varchar(20), C.TUR::smallint, ''::varchar(150),
    (SELECT ANAHTAR FROM GENINI WHERE BOLUM=-1005 AND DEGER=C.TUR LIMIT 1)::varchar(50),
    C.REHBERID, R.KOD::varchar(20), R.FIRMA::varchar(100), rtrim(coalesce(R.NOTLAR,''))::varchar(500),
    NULL::int, NULL::varchar(100), NULL::varchar(150), C.DURUM::smallint,
    (CASE WHEN C.TUR=34 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN C.TUR=24 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)::numeric,
    (CASE WHEN coalesce(C.DOVIZ_KURU,'')<>YK.d THEN C.DOVIZ_KURU ELSE coalesce(C.KUR,'TL') END)::varchar(6),
    ABS((CASE WHEN C.DOVIZ_KURU=YK.d AND C.TUR=34 THEN C.DOVIZ_TUTARI WHEN C.DOVIZ_KURU=YK.d AND C.TUR=24 THEN -1*C.DOVIZ_TUTARI
              WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=34 THEN C.TUTAR WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=24 THEN -1*C.TUTAR END)
        / nullif(((CASE WHEN C.TUR=34 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)
                 -(CASE WHEN C.TUR=24 THEN (CASE WHEN C.EKSTREDEKULLAN=1 THEN C.DOVIZ_TUTARI ELSE coalesce(C.TUTAR,0) END) ELSE 0 END)),0))::numeric,
    C.MASRAFID, M.KOD::varchar(50), M.AD::varchar(100),
    (CASE WHEN C.DOVIZ_KURU=YK.d AND C.TUR=34 THEN C.DOVIZ_TUTARI WHEN C.DOVIZ_KURU=YK.d AND C.TUR=24 THEN -1*C.DOVIZ_TUTARI
          WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=34 THEN C.TUTAR WHEN C.DOVIZ_KURU<>YK.d AND C.TUR=24 THEN -1*C.TUTAR END)::numeric,
    C.SUBEID, C.VADE, 1.0::double precision, ''::varchar(20), 0.0::numeric
  FROM SENETLER C
    INNER JOIN REHBER R ON C.REHBERID=R.ID
    LEFT JOIN MASRAFGELIR M ON M.ID=C.MASRAFID
    CROSS JOIN yk YK
  WHERE C.REHBERID=p_rehberid
    AND extract(year from C.TARIH)>=extract(year from p_bastar) AND extract(year from C.TARIH)<=extract(year from p_bittar)
    AND C.TARIH<=p_bittar
),
allrows AS (
  -- Devir (pre-BasTar aggregate, per KUR,SUBEID); MSSQL filtre: TUR in(49) or TUR not between 40 and 79
  SELECT 0 AS devirsira, 0 AS CEKID, p_bastar AS TARIH, p_bastar AS AKSIYONTARIH, NULL::varchar(20) AS no, 2::smallint AS TUR,
    ''::varchar(150) AS BASLIK, 'Devir'::varchar(50) AS TURAD, 0 AS REHBERID, ''::varchar(20) AS KOD, ''::varchar(100) AS AD,
    'Devir'::varchar(500) AS ACIKLAMA, NULL::int AS HESAPID, NULL::varchar(100) AS HESAPKODU, NULL::varchar(150) AS HESAPADI, 1::smallint AS DURUM,
    SUM(BORC)::numeric AS BORC, SUM(ALACAK)::numeric AS ALACAK, KUR, NULL::numeric AS YERELKUR,
    0 AS MASRAFID, ''::varchar(50) AS MASRAFKOD, ''::varchar(100) AS MASRAFAD,
    SUM(YERELTUTAR)::numeric AS YERELTUTAR, SUBEID, p_bastar AS VADETARIHI,
    NULL::double precision AS ADET, NULL::varchar(20) AS BIRIM, NULL::numeric AS BIRIMFIYAT
  FROM har WHERE TARIH < p_bastar AND ((TUR IN (49)) OR (TUR NOT BETWEEN 40 AND 79)) GROUP BY KUR, SUBEID
  UNION ALL
  SELECT 1, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU, HESAPADI, DURUM,
    BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD, YERELTUTAR, SUBEID, VADETARIHI, ADET, BIRIM, BIRIMFIYAT
  FROM har
),
seq AS (SELECT allrows.*, (row_number() OVER (ORDER BY devirsira, KUR, TARIH, CEKID))::int AS SIRANO FROM allrows)
SELECT
  SIRANO, CEKID, TARIH, AKSIYONTARIH, no, TUR, BASLIK, TURAD, REHBERID, KOD, AD, ACIKLAMA, HESAPID, HESAPKODU, HESAPADI, DURUM,
  BORC, ALACAK, KUR, YERELKUR, MASRAFID, MASRAFKOD, MASRAFAD,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE BORC-ALACAK END) OVER (PARTITION BY KUR ORDER BY SIRANO),0)::numeric AS BORCBAKIYE,
  greatest(SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE ALACAK-BORC END) OVER (PARTITION BY KUR ORDER BY SIRANO),0)::numeric AS ALACAKBAKIYE,
  YERELTUTAR,
  (SUM(CASE WHEN TUR BETWEEN 60 AND 79 THEN 0 ELSE coalesce(YERELTUTAR,0) END) OVER (PARTITION BY KUR ORDER BY SIRANO))::numeric AS YERELBAKIYE,
  SUBEID, VADETARIHI, ADET, BIRIM, BIRIMFIYAT
FROM seq
WHERE TARIH >= p_bastar
ORDER BY KUR, SIRANO;
$$;
