-- ============================================================================
--  Gentegre AI — F0-03a
--  002_stg_kaynak_tablolar.sql
--
--  Gocun KAYNAK tarafi. MSSQL (BILIM) uzerindeki REHBER / REHBERBILGI /
--  REHBERILETISIM tablolarinin ham kopyalari "stg" semasinda tutulur;
--  donusum 003_goc_rehber.sql icinde bu tablolardan okur.
--  Bu dosya MSSQL sema bilgisinden URETILDI (sys.columns).
--
--  DIKKAT: "create table IF NOT EXISTS" kullanilir - dosya tekrar calistirildiginda
--    stg VERISI SILINMEZ. (Onceki surum "drop table" yapiyordu; sema kurulumunu
--    tekrar calistirmak kaynak veriyi sessizce siliyor, goc bos calisiyordu.)
--    Kaynak sema degisirse ilgili tabloyu ELLE drop edin.
-- ============================================================================
\set ON_ERROR_STOP on

CREATE SCHEMA IF NOT EXISTS stg;

CREATE TABLE IF NOT EXISTS stg.depolar (
    id                     integer,
    depoadi                varchar(50),
    durum                  smallint,
    ekleyen                smallint,
    eklemetarihi           timestamp,
    degistiren             smallint,
    degistirmetarihi       timestamp,
    sonsayimtarihi         timestamp,
    varsayilan             smallint,
    subeid                 smallint,
    maliyeti_etkilesin     smallint
);

CREATE TABLE IF NOT EXISTS stg.doviz (
    cinsi                  varchar(5),
    tarih                  timestamp,
    alis                   double precision,
    satis                  double precision,
    efalis                 double precision,
    efsatis                double precision,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp
);

CREATE TABLE IF NOT EXISTS stg.fatbaslik (
    id                     integer,
    tarih                  timestamp,
    tur                    smallint,
    tipi                   smallint,
    rehberid               integer,
    projeid                integer,
    aktiviteid             integer,
    anakayitid             integer,
    faturatarih            timestamp,
    kocanno                integer,
    faturaseri             varchar(5),
    faturano               varchar(20),
    girisdepo              smallint,
    cikisdepo              smallint,
    baslik                 varchar(150),
    adres                  varchar(150),
    ilce                   varchar(50),
    il                     varchar(50),
    vd                     varchar(50),
    vno                    varchar(50),
    kdvdurum               varchar(5),
    lotno                  varchar(8),
    fatura_gon_tarihi      timestamp,
    fatura_matrahi         numeric(19,4),
    kdv_tutari             numeric(19,4),
    ekvergi                numeric(19,4),
    fatura_tutari          numeric(19,4),
    kur                    varchar(5),
    doviz_tutari           numeric(19,4),
    doviz_cinsi            varchar(6),
    kasa                   smallint,
    onay                   smallint,
    sayfa                  smallint,
    masrafid               smallint,
    aciklama               varchar(300),
    isyeri                 smallint,
    bolum                  smallint,
    fatura_maliyeti_ort    numeric(19,4),
    saticikodu             integer,
    durum                  smallint,
    irsaliye_tipi          smallint,
    odemeplani             smallint,
    ozelkod                varchar(20),
    yetkikodu              varchar(10),
    fiyat_listesi          smallint,
    stokisk                double precision,
    vade                   smallint,
    r                      smallint,
    irsaliyeno             varchar(50),
    irsaliyetarih          timestamp,
    planid                 integer,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    kasatakipid            integer,
    detaybolumu            varchar(20),
    dovizkur               numeric(19,4),
    acik_kapali            smallint,
    dil                    smallint,
    sayfasay               smallint,
    rehberiletid           integer,
    subeid                 smallint,
    baglifaturaid          integer,
    muhaktar               smallint,
    aktarmatarihi          timestamp,
    yeri                   smallint,
    yerid                  integer,
    lokasyon               integer,
    onaylayan              integer,
    girissube              smallint,
    zarfid                 integer,
    irsaliyeli             smallint,
    merkezid               integer,
    efaturadurum           smallint,
    donusumturu            integer,
    yazdirildi             smallint,
    efaturasonuc           smallint,
    senaryo                smallint,
    ekstredekullan         smallint,
    giriskaynak            smallint,
    rapordoviz             varchar(5),
    faturadovizi           varchar(5),
    servisid               integer,
    aciklama2              varchar(50),
    demirbasid             integer,
    ozelkod2               varchar(20),
    pozno                  integer,
    sanal                  smallint,
    doktor                 varchar(100),
    hasta                  varchar(100),
    gntpid                 integer,
    gntp_fatbasid          integer
);

CREATE TABLE IF NOT EXISTS stg.fatura (
    id                     integer,
    fatbasid               integer,
    rehberid               integer,
    sec                    varchar(1),
    tur                    smallint,
    urunid                 integer,
    aciklama               text,
    adet                   numeric(24,6),
    mf                     numeric(24,6),
    birim                  smallint,
    miktar                 numeric(24,6),
    birimfiyat             numeric(24,6),
    tutar                  numeric(24,2),
    kur                    varchar(5),
    iskonto                double precision,
    kdv                    smallint,
    masrafid               integer,
    izlemekodu             varchar(40),
    ozelkod                varchar(20),
    muhkodu                varchar(25),
    kasa                   smallint,
    onay                   varchar(1),
    doviz_tutari           numeric(24,2),
    doviz_kuru             varchar(5),
    iskonto2               double precision,
    izleme                 smallint,
    iadeadet               double precision,
    iadefaturaid           integer,
    yeri                   integer,
    yerid                  integer,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    doviz_birimfiyat       numeric(24,6),
    dovizkurdegeri         numeric(19,4),
    projeid                integer,
    kampanyaid             integer,
    vade                   smallint,
    stokdurumdegis         smallint,
    subeid                 smallint,
    kdvmuhafiyeti          smallint,
    ekmaliyet              numeric(19,4),
    bastar                 timestamp,
    bittar                 timestamp,
    uretimplanid           integer,
    uretimplandetayid      integer,
    merkezid               integer,
    giriskaynak            smallint,
    ekipmanid              integer,
    girdepo                smallint,
    cikdepo                smallint,
    otvyuzde               smallint,
    otvmiktar              numeric(6,2),
    sira                   integer,
    saticikodu             integer,
    iskontolubrmfiyat      double precision,
    kdvdahilbrmfiyat       numeric(38,9),
    kdvdahilfiyat          double precision,
    demirbasid             integer,
    ozelkod2               varchar(20),
    stokid                 integer,
    pozno                  integer,
    validfrom              timestamp,
    validto                timestamp
);

CREATE TABLE IF NOT EXISTS stg.fiyatlar (
    id                     integer,
    hizmetid               integer,
    fiyatadi               smallint,
    sec                    varchar(5),
    fiyat                  numeric(19,4),
    kur                    varchar(5),
    ekleyen                smallint,
    eklemetarihi           timestamp,
    degistiren             smallint,
    degistirmetarihi       timestamp,
    kdvdurum               smallint,
    paketid                integer,
    satis                  smallint
);

CREATE TABLE IF NOT EXISTS stg.genini (
    bolum                  integer,
    anahtar                varchar(150),
    deger                  integer,
    dil                    smallint,
    sira                   smallint
);

CREATE TABLE IF NOT EXISTS stg.kasa (
    id                     integer,
    tur                    smallint,
    plantarihi             timestamp,
    islemtarihi            timestamp,
    belgeno                varchar(30),
    rehberid               integer,
    hesapid                integer,
    borc                   numeric(19,4),
    alacak                 numeric(19,4),
    kur                    varchar(6),
    hesapturu              varchar(1),
    doviz_tutari           numeric(19,4),
    doviz_kuru             varchar(6),
    musterihesapid         integer,
    durum                  smallint,
    kasa                   smallint,
    onay                   varchar(1),
    masrafid               smallint,
    aciklama               varchar(100),
    uyar                   smallint,
    uyarigun               smallint,
    animsat                smallint,
    faturaid               integer,
    ceksenetid             integer,
    geridonusid            integer,
    krediid                integer,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    yedek                  numeric(19,4),
    yeri                   integer,
    yerid                  bigint,
    subeid                 smallint,
    muhaktar               smallint,
    aktarmatarihi          timestamp,
    merkezid               integer,
    r                      smallint,
    ekstredekullan         smallint,
    giriskaynak            smallint,
    demirbasid             integer,
    projeid                integer,
    ozelkod                varchar(20)
);

CREATE TABLE IF NOT EXISTS stg.kullanici (
    id                     integer,
    rehberid               integer,
    sifre                  varchar(100),
    kod                    varchar(5),
    rolid                  integer,
    durum                  smallint,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint,
    dil                    smallint,
    token                  uuid,
    mobil                  smallint,
    soru                   smallint,
    cevap                  varchar(100),
    sifredegisme           timestamp,
    skinadi                varchar(50)
);

CREATE TABLE IF NOT EXISTS stg.masrafgelir (
    id                     smallint,
    gelirmi                smallint,
    baslik                 smallint,
    digitsay               smallint,
    kod                    varchar(20),
    ad                     varchar(200),
    tur                    smallint,
    grubu                  smallint,
    kdv                    smallint,
    aciklama               varchar(40),
    barkod                 varchar(15),
    ozelkod                varchar(20),
    yetkikodu              varchar(20),
    muhkodu                varchar(10),
    durum                  smallint,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    varsayilan             smallint,
    kisayolgrubu           smallint,
    birim                  smallint,
    subeid                 smallint,
    resim                  bytea,
    muhaktar               smallint,
    zarfmaliyetdurumu      smallint,
    yer                    integer,
    yer_id                 integer
);

CREATE TABLE IF NOT EXISTS stg.rehber (
    id                     integer,
    kod                    varchar(20),
    firma                  varchar(120),
    statu                  smallint,
    grup                   smallint,
    kategori               smallint,
    sinif                  integer,
    durum                  smallint,
    temsilci               integer,
    notlar                 varchar(1000),
    ozelkod                varchar(20),
    yetkikodu              varchar(10),
    ozel                   varchar(10),
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint,
    muhaktar               smallint,
    bolge                  smallint,
    muhkodu                varchar(20),
    r                      smallint,
    bagid                  integer,
    giriskaynak            smallint,
    dtarih                 timestamp,
    sektor                 smallint,
    altbolge               smallint,
    peryot                 smallint,
    altsektor              integer,
    resim                  bytea,
    posta                  smallint,
    eposta                 smallint,
    temas                  integer,
    efatura                smallint,
    konum                  varchar(50),
    gntpid                 integer,
    kdr_disi               varchar(30)
);

CREATE TABLE IF NOT EXISTS stg.rehberbilgi (
    id                     integer,
    modul                  smallint,
    yeri                   smallint,
    yer_id                 integer,
    sira                   smallint,
    etiket                 varchar(30),
    bilgi                  varchar(100),
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint
);

CREATE TABLE IF NOT EXISTS stg.rehberiletisim (
    id                     integer,
    rehberid               integer,
    ad                     varchar(50),
    varsayilan             smallint,
    aktif                  smallint,
    ekleyen                smallint,
    eklemetarihi           timestamp,
    degistiren             smallint,
    degistirmetarihi       timestamp,
    subeid                 smallint
);

CREATE TABLE IF NOT EXISTS stg.sayac (
    anahtar                varchar(200),
    tabloadi               text,
    alanadi                text,
    kapsam                 varchar(80),
    sonno                  bigint,
    guncelleme             timestamp
);

CREATE TABLE IF NOT EXISTS stg.stokbarkod (
    id                     integer,
    barkod                 varchar(50),
    stokid                 integer,
    barkodtipi             integer,
    barkodbirimi           integer,
    varsayilan             smallint,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint,
    yeri                   integer,
    yerid                  integer
);

CREATE TABLE IF NOT EXISTS stg.stokdurum (
    stokid                 integer,
    depoid                 smallint,
    giren                  double precision,
    cikan                  double precision,
    kalan                  double precision,
    subeid                 smallint
);

CREATE TABLE IF NOT EXISTS stg.stokfiyat (
    id                     integer,
    stokid                 integer,
    fiyatadi               smallint,
    birim                  smallint,
    fiyat                  numeric(18,4),
    kur                    varchar(5),
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    kdvdurum               smallint,
    paketid                integer,
    satis                  smallint
);

CREATE TABLE IF NOT EXISTS stg.stokizleme (
    id                     integer,
    stokid                 integer,
    belgetur               smallint,
    baslikid               integer,
    satirid                integer,
    izlemtur               smallint,
    kalan                  double precision,
    yer                    integer,
    yerid                  integer,
    ekleyen                integer,
    eklemetarihi           timestamp,
    donusid                integer,
    adet                   double precision,
    serilotid              integer
);

CREATE TABLE IF NOT EXISTS stg.stoklar (
    id                     integer,
    kod                    varchar(25),
    stokadi                varchar(100),
    kategori               smallint,
    tipi                   smallint,
    marka                  smallint,
    model                  smallint,
    grubu                  smallint,
    ozellik                smallint,
    ozelkod                varchar(20),
    muhkodu                varchar(30),
    anabirim               smallint,
    birim2                 smallint,
    birim2miktar           double precision,
    minstok                integer,
    yeri                   smallint,
    ureticiid              integer,
    saticiid               integer,
    kdv                    smallint,
    ekvergi                smallint,
    xbarkodx               varchar(15),
    durum                  smallint,
    fiyat_liste            smallint,
    izleme                 smallint,
    rafomru_sure           smallint,
    rafomru_birim          integer,
    masrafid               smallint,
    gelirid                smallint,
    boyut_en               double precision,
    boyut_boy              double precision,
    boyut_yukseklik        double precision,
    boyut_alan             double precision,
    boyut_net_hacim        double precision,
    boyut_brut_hacim       double precision,
    boyut_net_agirlik      double precision,
    boyut_brut_agirlik     double precision,
    uzunluk_birimi         smallint,
    alan_birimi            smallint,
    hacim_birimi           smallint,
    agirlik_birimi         smallint,
    notlar                 varchar(500),
    yetkikodu              varchar(10),
    garantisuresi          smallint,
    kisayolgrubu           smallint,
    paket                  smallint,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    detaybolumu            varchar(20),
    subeid                 smallint,
    uretici                integer,
    icerik                 smallint,
    muhaktar               smallint,
    aktarmatarihi          timestamp,
    isk2                   double precision,
    boyutgrubu             integer,
    resim                  bytea,
    iskontosuz             smallint,
    giriskaynak            smallint,
    kullanim               smallint,
    ekipman                smallint,
    otvyuzde               smallint,
    otvmiktar              numeric(6,2),
    miktarsec              smallint,
    internet_satis         smallint,
    teminsuresi            smallint,
    ozelkod2               varchar(20),
    bildirim               smallint,
    urunno                 varchar(20),
    lot                    varchar(30),
    hucre                  varchar(50),
    gtip                   varchar(30),
    teditfatura_stok_adi   varchar(30)
);

CREATE TABLE IF NOT EXISTS stg.stokserilot (
    id                     integer,
    stokid                 integer,
    serino                 varchar(64),
    lotno                  varchar(30),
    urt                    timestamp,
    skt                    timestamp,
    lotno_ex               varchar(30)
);

-- ---------------------------------------------------------------------------
--  Kimlik / yetki kaynak tablolari (F0-05, 021_goc_kimlik.sql okur)
--    KULLANICI yukarida zaten var.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stg.roller (
    id                     integer,
    rol                    varchar(100),
    durum                  smallint,
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint,
    ustid                  integer,
    ty                     smallint,
    departman              smallint,
    gorevid                smallint
);

CREATE TABLE IF NOT EXISTS stg.modul (
    id                     integer,
    modulid                bigint,
    moduladi               varchar(40),
    aciklama               text,
    tur                    integer,
    otogunyeni             smallint,
    tarihyeni              timestamp,
    otogunguncel           smallint,
    tarihguncel            timestamp,
    subeid                 smallint,
    dokumtur               varchar(5),
    l                      varchar(100),
    kasatur                smallint,
    kilityeni              smallint,
    kilitguncel            smallint
);

CREATE TABLE IF NOT EXISTS stg.yetki (
    id                     integer,
    rolid                  integer,
    modulid                bigint,
    hak                    smallint,
    tur                    smallint,
    bilgi                  varchar(10),
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint
);

CREATE TABLE IF NOT EXISTS stg.yetkiek (
    id                     integer,
    rolid                  integer,
    modulid                bigint,
    bilgi                  varchar(50),
    ekleyen                integer,
    eklemetarihi           timestamp,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint,
    bilgi2                 varchar(25)
);

CREATE TABLE IF NOT EXISTS stg.yetkialani (
    id                     integer,
    alanturu               integer,
    sahiprehberid          integer,
    rehberid               integer,
    ekleyen                integer,
    degistiren             integer,
    degistirmetarihi       timestamp,
    subeid                 smallint
);
