-- ============================================================================
--  Gentegre AI — ÇEVİRİ (ana menü + ekran etiketleri)
--  194_ceviri.sql
--
--  Dil seçimi vardı (taraf_kullanici.dil · TR/EN/DE bayrakları) ama ekranda
--  hiçbir metin değişmiyordu: menü, kart sekmeleri ve kolon başlıkları koda
--  Türkçe gömülüydü.
--
--  TASARIM — ANAHTAR TÜRKÇE METNİN KENDİSİDİR:
--    ceviri(kapsam='menu', anahtar='Satış Faturaları', dil=1) -> 'Sales Invoices'
--  Ayrı anahtar sözlüğü tutulmaz; yeni ekran eklendiğinde çeviri yoksa Türkçe
--  görünür (kademeli doldurulabilir). Aynı kelimenin bağlama göre farklı
--  karşılığı olabildiği için KAPSAM ayrımı var ('menu' · 'etiket').
--
--  TEK KAYNAK: sözlüğü hem sunucu (katalog başlıkları) hem arayüz (menü, sabit
--  metinler) aynı tablodan okur - iki ayrı sözlük zamanla ayrışırdı.
--
--  dil kodları: 0 Türkçe (kaynak metin) · 1 English · 2 Deutsch
-- ============================================================================
\set ON_ERROR_STOP on

create table if not exists public.ceviri (
    kapsam            varchar(20)  not null,
    anahtar           varchar(200) not null,
    dil               smallint     not null,
    metin             varchar(300) not null,
    ekleyen           integer   not null default 0,
    ekleme_tarihi     timestamp not null default now()::timestamp,
    degistiren        integer   not null default 0,
    degistirme_tarihi timestamp,
    constraint pk_ceviri primary key (kapsam, anahtar, dil)
);

comment on table public.ceviri is
  'Arayuz cevirileri (194). Anahtar TURKCE metnin kendisidir; ceviri yoksa Turkce gosterilir.';

-- Tek metin: yoksa Türkçe (anahtarın kendisi) döner.
create or replace function public.fn_ceviri(p_kapsam varchar, p_anahtar varchar,
                                            p_dil smallint)
returns varchar language sql stable as $$
    select coalesce((select c.metin from public.ceviri c
                      where c.kapsam = p_kapsam and c.anahtar = p_anahtar
                        and c.dil = p_dil), p_anahtar)
$$;

comment on function public.fn_ceviri(varchar, varchar, smallint) is
  'Ceviri metni; kayit yoksa anahtarin kendisi (Turkce) doner (194).';

-- Bir dilin TAMAMI: arayuz girişte tek çağrıda indirir, sunucu önbelleğe alır.
create or replace function public.fn_ceviri_sozluk(p_dil smallint)
returns table (kapsam varchar, anahtar varchar, metin varchar)
language sql stable as $$
    select c.kapsam, c.anahtar, c.metin
      from public.ceviri c where c.dil = p_dil
     order by c.kapsam, c.anahtar
$$;

insert into public.ceviri (kapsam, anahtar, dil, metin)
select v.kapsam, v.anahtar, v.dil, v.metin
  from (values
    ('menu', 'Hasta Listesi', 1, 'Patients'),
    ('menu', 'Hasta Listesi', 2, 'Patienten'),
    ('menu', 'Projeler', 1, 'Projects'),
    ('menu', 'Projeler', 2, 'Projekte'),
    ('menu', 'Görevler', 1, 'Tasks'),
    ('menu', 'Görevler', 2, 'Aufgaben'),
    ('menu', 'Satış Fırsatları', 1, 'Opportunities'),
    ('menu', 'Satış Fırsatları', 2, 'Verkaufschancen'),
    ('menu', 'Aday Müşteriler', 1, 'Leads'),
    ('menu', 'Aday Müşteriler', 2, 'Interessenten'),
    ('menu', 'Müşteri Listesi', 1, 'Customers'),
    ('menu', 'Müşteri Listesi', 2, 'Kunden'),
    ('menu', 'Tedarikçi Listesi', 1, 'Suppliers'),
    ('menu', 'Tedarikçi Listesi', 2, 'Lieferanten'),
    ('menu', 'Kişi Listesi', 1, 'Contacts'),
    ('menu', 'Kişi Listesi', 2, 'Kontakte'),
    ('menu', 'Satış Siparişleri', 1, 'Sales Orders'),
    ('menu', 'Satış Siparişleri', 2, 'Kundenaufträge'),
    ('menu', 'Satış İrsaliyeleri', 1, 'Sales Dispatches'),
    ('menu', 'Satış İrsaliyeleri', 2, 'Lieferscheine (Verkauf)'),
    ('menu', 'Satış Faturaları', 1, 'Sales Invoices'),
    ('menu', 'Satış Faturaları', 2, 'Ausgangsrechnungen'),
    ('menu', 'Gelen Kutusu', 1, 'Inbox'),
    ('menu', 'Gelen Kutusu', 2, 'Posteingang'),
    ('menu', 'Satış Fişleri', 1, 'Sales Receipts'),
    ('menu', 'Satış Fişleri', 2, 'Verkaufsbelege'),
    ('menu', 'Tahakkuklar', 1, 'Accruals'),
    ('menu', 'Tahakkuklar', 2, 'Abgrenzungen'),
    ('menu', 'Satış Konsinyeler', 1, 'Sales Consignments'),
    ('menu', 'Satış Konsinyeler', 2, 'Kommission (Verkauf)'),
    ('menu', 'Alış Siparişleri', 1, 'Purchase Orders'),
    ('menu', 'Alış Siparişleri', 2, 'Bestellungen'),
    ('menu', 'Alış İrsaliyeleri', 1, 'Purchase Dispatches'),
    ('menu', 'Alış İrsaliyeleri', 2, 'Lieferscheine (Einkauf)'),
    ('menu', 'Alış Faturaları', 1, 'Purchase Invoices'),
    ('menu', 'Alış Faturaları', 2, 'Eingangsrechnungen'),
    ('menu', 'Alış Fişleri', 1, 'Purchase Receipts'),
    ('menu', 'Alış Fişleri', 2, 'Einkaufsbelege'),
    ('menu', 'Alış Konsinyeler', 1, 'Purchase Consignments'),
    ('menu', 'Alış Konsinyeler', 2, 'Kommission (Einkauf)'),
    ('menu', 'Açık Satırlar', 1, 'Open Lines'),
    ('menu', 'Açık Satırlar', 2, 'Offene Positionen'),
    ('menu', 'Kasa İşlemleri', 1, 'Cash Transactions'),
    ('menu', 'Kasa İşlemleri', 2, 'Kassenvorgänge'),
    ('menu', 'Vade / Planlar', 1, 'Due Dates / Plans'),
    ('menu', 'Vade / Planlar', 2, 'Fälligkeiten / Pläne'),
    ('menu', 'Kasa Hareketleri', 1, 'Cash Movements'),
    ('menu', 'Kasa Hareketleri', 2, 'Kassenbewegungen'),
    ('menu', 'Kasa Hesapları', 1, 'Cash Accounts'),
    ('menu', 'Kasa Hesapları', 2, 'Kassenkonten'),
    ('menu', 'Banka Hesapları', 1, 'Bank Accounts'),
    ('menu', 'Banka Hesapları', 2, 'Bankkonten'),
    ('menu', 'Krediler', 1, 'Loans'),
    ('menu', 'Krediler', 2, 'Kredite'),
    ('menu', 'POS', 1, 'POS'),
    ('menu', 'POS', 2, 'POS'),
    ('menu', 'Kredi Kartı', 1, 'Credit Card'),
    ('menu', 'Kredi Kartı', 2, 'Kreditkarte'),
    ('menu', 'Banka Tanımları', 1, 'Banks'),
    ('menu', 'Banka Tanımları', 2, 'Banken'),
    ('menu', 'Çek Listesi', 1, 'Cheques'),
    ('menu', 'Çek Listesi', 2, 'Schecks'),
    ('menu', 'Senet Listesi', 1, 'Promissory Notes'),
    ('menu', 'Senet Listesi', 2, 'Wechsel'),
    ('menu', 'Hesap Ekstresi', 1, 'Account Statement'),
    ('menu', 'Hesap Ekstresi', 2, 'Kontoauszug'),
    ('menu', 'Cari Ekstre', 1, 'Customer Statement'),
    ('menu', 'Cari Ekstre', 2, 'Kontokorrentauszug'),
    ('menu', 'Masraf Listesi', 1, 'Expenses'),
    ('menu', 'Masraf Listesi', 2, 'Aufwendungen'),
    ('menu', 'Stok Listesi', 1, 'Items'),
    ('menu', 'Stok Listesi', 2, 'Artikel'),
    ('menu', 'Hizmet Listesi', 1, 'Services'),
    ('menu', 'Hizmet Listesi', 2, 'Dienstleistungen'),
    ('menu', 'Stoktan Talep', 1, 'Stock Requests'),
    ('menu', 'Stoktan Talep', 2, 'Lageranforderungen'),
    ('menu', 'Stok Transfer', 1, 'Stock Transfers'),
    ('menu', 'Stok Transfer', 2, 'Umlagerungen'),
    ('menu', 'Giriş Fişi', 1, 'Goods Receipt'),
    ('menu', 'Giriş Fişi', 2, 'Wareneingang'),
    ('menu', 'Çıkış Fişi', 1, 'Goods Issue'),
    ('menu', 'Çıkış Fişi', 2, 'Warenausgang'),
    ('menu', 'Personel Listesi', 1, 'Employees'),
    ('menu', 'Personel Listesi', 2, 'Mitarbeiter'),
    ('menu', 'e-Belge', 1, 'e-Document'),
    ('menu', 'e-Belge', 2, 'e-Beleg'),
    ('menu', 'İşlem Günlüğü', 1, 'Audit Log'),
    ('menu', 'İşlem Günlüğü', 2, 'Protokoll'),
    ('menu', 'Muhasebe Fişleri', 1, 'Journal Entries'),
    ('menu', 'Muhasebe Fişleri', 2, 'Buchungssätze'),
    ('menu', 'Fiş Satırları', 1, 'Journal Lines'),
    ('menu', 'Fiş Satırları', 2, 'Buchungszeilen'),
    ('menu', 'Hesap Planı', 1, 'Chart of Accounts'),
    ('menu', 'Hesap Planı', 2, 'Kontenplan'),
    ('menu', 'Masraf Merkezleri', 1, 'Cost Centers'),
    ('menu', 'Masraf Merkezleri', 2, 'Kostenstellen'),
    ('menu', 'İşlem Türleri', 1, 'Transaction Types'),
    ('menu', 'İşlem Türleri', 2, 'Vorgangsarten'),
    ('menu', 'Roller', 1, 'Roles'),
    ('menu', 'Roller', 2, 'Rollen'),
    ('menu', 'Firma Bilgileri', 1, 'Company'),
    ('menu', 'Firma Bilgileri', 2, 'Firmendaten'),
    ('menu', 'Genel', 1, 'General'),
    ('menu', 'Genel', 2, 'Allgemein'),
    ('menu', 'Stok Ayarları', 1, 'Item Settings'),
    ('menu', 'Stok Ayarları', 2, 'Artikeleinstellungen'),
    ('menu', 'Kasa', 1, 'Cash'),
    ('menu', 'Kasa', 2, 'Kasse'),
    ('menu', 'Satış Belgeleri', 1, 'Sales Documents'),
    ('menu', 'Satış Belgeleri', 2, 'Verkaufsbelege'),
    ('menu', 'Alış Belgeleri', 1, 'Purchase Documents'),
    ('menu', 'Alış Belgeleri', 2, 'Einkaufsbelege'),
    ('menu', 'Ana Sayfa', 1, 'Home'),
    ('menu', 'Ana Sayfa', 2, 'Startseite'),
    ('menu', 'Kayıt Kabul', 1, 'Admissions'),
    ('menu', 'Kayıt Kabul', 2, 'Aufnahme'),
    ('menu', 'CRM', 1, 'CRM'),
    ('menu', 'CRM', 2, 'CRM'),
    ('menu', 'Cari', 1, 'Accounts'),
    ('menu', 'Cari', 2, 'Geschäftspartner'),
    ('menu', 'Satış', 1, 'Sales'),
    ('menu', 'Satış', 2, 'Verkauf'),
    ('menu', 'Alış', 1, 'Purchasing'),
    ('menu', 'Alış', 2, 'Einkauf'),
    ('menu', 'Banka', 1, 'Bank'),
    ('menu', 'Banka', 2, 'Bank'),
    ('menu', 'Stok & Hizmet', 1, 'Items & Services'),
    ('menu', 'Stok & Hizmet', 2, 'Artikel & Leistungen'),
    ('menu', 'İK', 1, 'HR'),
    ('menu', 'İK', 2, 'Personal'),
    ('menu', 'Yönetim', 1, 'Administration'),
    ('menu', 'Yönetim', 2, 'Verwaltung'),
    ('menu', 'Ayarlar', 1, 'Settings'),
    ('menu', 'Ayarlar', 2, 'Einstellungen'),
    ('menu', 'Calisma alani', 1, 'Workspace'),
    ('menu', 'Calisma alani', 2, 'Arbeitsbereich'),
    ('menu', 'Oturum', 1, 'Session'),
    ('menu', 'Oturum', 2, 'Sitzung'),
    ('etiket', 'Kaydet', 1, 'Save'),
    ('etiket', 'Kaydet', 2, 'Speichern'),
    ('etiket', 'Kapat', 1, 'Close'),
    ('etiket', 'Kapat', 2, 'Schließen'),
    ('etiket', 'İptal', 1, 'Cancel'),
    ('etiket', 'İptal', 2, 'Abbrechen'),
    ('etiket', 'Sil', 1, 'Delete'),
    ('etiket', 'Sil', 2, 'Löschen'),
    ('etiket', 'Yeni', 1, 'New'),
    ('etiket', 'Yeni', 2, 'Neu'),
    ('etiket', 'Düzenle', 1, 'Edit'),
    ('etiket', 'Düzenle', 2, 'Bearbeiten'),
    ('etiket', 'Ara', 1, 'Search'),
    ('etiket', 'Ara', 2, 'Suchen'),
    ('etiket', 'Yazdır', 1, 'Print'),
    ('etiket', 'Yazdır', 2, 'Drucken'),
    ('etiket', 'Uygula', 1, 'Apply'),
    ('etiket', 'Uygula', 2, 'Anwenden'),
    ('etiket', 'Temizle', 1, 'Clear'),
    ('etiket', 'Temizle', 2, 'Zurücksetzen'),
    ('etiket', 'Aç', 1, 'Open'),
    ('etiket', 'Aç', 2, 'Öffnen'),
    ('etiket', 'Görüntüle', 1, 'View'),
    ('etiket', 'Görüntüle', 2, 'Anzeigen'),
    ('etiket', 'Kopyala', 1, 'Copy'),
    ('etiket', 'Kopyala', 2, 'Kopieren'),
    ('etiket', 'Dönüştür', 1, 'Convert'),
    ('etiket', 'Dönüştür', 2, 'Umwandeln'),
    ('etiket', 'Gönder', 1, 'Send'),
    ('etiket', 'Gönder', 2, 'Senden'),
    ('etiket', 'Hazırla', 1, 'Prepare'),
    ('etiket', 'Hazırla', 2, 'Vorbereiten'),
    ('etiket', 'Ön İzle', 1, 'Preview'),
    ('etiket', 'Ön İzle', 2, 'Vorschau'),
    ('etiket', 'Tümü', 1, 'All'),
    ('etiket', 'Tümü', 2, 'Alle'),
    ('etiket', 'Tumu', 1, 'All'),
    ('etiket', 'Tumu', 2, 'Alle'),
    ('etiket', 'Son', 1, 'Recent'),
    ('etiket', 'Son', 2, 'Zuletzt'),
    ('etiket', 'Sık', 1, 'Favorites'),
    ('etiket', 'Sık', 2, 'Favoriten'),
    ('etiket', 'Evet', 1, 'Yes'),
    ('etiket', 'Evet', 2, 'Ja'),
    ('etiket', 'Hayır', 1, 'No'),
    ('etiket', 'Hayır', 2, 'Nein'),
    ('etiket', 'Tamam', 1, 'OK'),
    ('etiket', 'Tamam', 2, 'OK'),
    ('etiket', 'Kimlik', 1, 'Identity'),
    ('etiket', 'Kimlik', 2, 'Stammdaten'),
    ('etiket', 'Adres', 1, 'Address'),
    ('etiket', 'Adres', 2, 'Adresse'),
    ('etiket', 'Adres & İletişim', 1, 'Address & Contact'),
    ('etiket', 'Adres & İletişim', 2, 'Adresse & Kontakt'),
    ('etiket', 'İletişim', 1, 'Contact'),
    ('etiket', 'İletişim', 2, 'Kontakt'),
    ('etiket', 'Depolar', 1, 'Warehouses'),
    ('etiket', 'Depolar', 2, 'Lager'),
    ('etiket', 'Mali', 1, 'Financial'),
    ('etiket', 'Mali', 2, 'Finanzen'),
    ('etiket', 'Logo & Kaşe', 1, 'Logo & Stamp'),
    ('etiket', 'Logo & Kaşe', 2, 'Logo & Stempel'),
    ('etiket', 'Mükellefiyet', 1, 'Liability'),
    ('etiket', 'Mükellefiyet', 2, 'Steuerpflicht'),
    ('etiket', 'Gönderici', 1, 'Sender'),
    ('etiket', 'Gönderici', 2, 'Absender'),
    ('etiket', 'Mali Dönem', 1, 'Fiscal Period'),
    ('etiket', 'Mali Dönem', 2, 'Geschäftsjahr'),
    ('etiket', 'Muhasebe Entegrasyonu', 1, 'Accounting Integration'),
    ('etiket', 'Muhasebe Entegrasyonu', 2, 'Buchhaltungsintegration'),
    ('etiket', 'Amortisman', 1, 'Depreciation'),
    ('etiket', 'Amortisman', 2, 'Abschreibung'),
    ('etiket', 'Vergi & Yuvarlama', 1, 'Tax & Rounding'),
    ('etiket', 'Vergi & Yuvarlama', 2, 'Steuer & Rundung'),
    ('etiket', 'Resim / Doküman', 1, 'Image / Document'),
    ('etiket', 'Resim / Doküman', 2, 'Bild / Dokument'),
    ('etiket', 'Yorum / Medya', 1, 'Notes / Media'),
    ('etiket', 'Yorum / Medya', 2, 'Notizen / Medien'),
    ('etiket', 'Kalemler', 1, 'Lines'),
    ('etiket', 'Kalemler', 2, 'Positionen'),
    ('etiket', 'Tahsilat', 1, 'Collection'),
    ('etiket', 'Tahsilat', 2, 'Zahlungseingang'),
    ('etiket', 'Ekstre', 1, 'Statement'),
    ('etiket', 'Ekstre', 2, 'Auszug'),
    ('etiket', 'Kod', 1, 'Code'),
    ('etiket', 'Kod', 2, 'Code'),
    ('etiket', 'Ad', 1, 'Name'),
    ('etiket', 'Ad', 2, 'Name'),
    ('etiket', 'Ünvan', 1, 'Title'),
    ('etiket', 'Ünvan', 2, 'Firmenname'),
    ('etiket', 'Kısa Ad', 1, 'Short Name'),
    ('etiket', 'Kısa Ad', 2, 'Kurzname'),
    ('etiket', 'Durum', 1, 'Status'),
    ('etiket', 'Durum', 2, 'Status'),
    ('etiket', 'Tarih', 1, 'Date'),
    ('etiket', 'Tarih', 2, 'Datum'),
    ('etiket', 'Tutar', 1, 'Amount'),
    ('etiket', 'Tutar', 2, 'Betrag'),
    ('etiket', 'Miktar', 1, 'Quantity'),
    ('etiket', 'Miktar', 2, 'Menge'),
    ('etiket', 'Birim', 1, 'Unit'),
    ('etiket', 'Birim', 2, 'Einheit'),
    ('etiket', 'Birim Fiyat', 1, 'Unit Price'),
    ('etiket', 'Birim Fiyat', 2, 'Einzelpreis'),
    ('etiket', 'İskonto', 1, 'Discount'),
    ('etiket', 'İskonto', 2, 'Rabatt'),
    ('etiket', 'KDV', 1, 'VAT'),
    ('etiket', 'KDV', 2, 'MwSt.'),
    ('etiket', 'Matrah', 1, 'Net Amount'),
    ('etiket', 'Matrah', 2, 'Nettobetrag'),
    ('etiket', 'Genel Toplam', 1, 'Grand Total'),
    ('etiket', 'Genel Toplam', 2, 'Gesamtsumme'),
    ('etiket', 'Açıklama', 1, 'Description'),
    ('etiket', 'Açıklama', 2, 'Beschreibung'),
    ('etiket', 'Belge No', 1, 'Document No'),
    ('etiket', 'Belge No', 2, 'Belegnummer'),
    ('etiket', 'Belge Türü', 1, 'Document Type'),
    ('etiket', 'Belge Türü', 2, 'Belegart'),
    ('etiket', 'Cari', 1, 'Account'),
    ('etiket', 'Cari', 2, 'Geschäftspartner'),
    ('etiket', 'Müşteri', 1, 'Customer'),
    ('etiket', 'Müşteri', 2, 'Kunde'),
    ('etiket', 'Tedarikçi', 1, 'Supplier'),
    ('etiket', 'Tedarikçi', 2, 'Lieferant'),
    ('etiket', 'Şube', 1, 'Branch'),
    ('etiket', 'Şube', 2, 'Filiale'),
    ('etiket', 'Depo', 1, 'Warehouse'),
    ('etiket', 'Depo', 2, 'Lager'),
    ('etiket', 'Proje', 1, 'Project'),
    ('etiket', 'Proje', 2, 'Projekt'),
    ('etiket', 'Telefon', 1, 'Phone'),
    ('etiket', 'Telefon', 2, 'Telefon'),
    ('etiket', 'E-posta', 1, 'E-mail'),
    ('etiket', 'E-posta', 2, 'E-Mail'),
    ('etiket', 'Vergi Dairesi', 1, 'Tax Office'),
    ('etiket', 'Vergi Dairesi', 2, 'Finanzamt'),
    ('etiket', 'VKN / TCKN', 1, 'Tax / ID No'),
    ('etiket', 'VKN / TCKN', 2, 'Steuer-/ID-Nr.'),
    ('etiket', 'Aktif', 1, 'Active'),
    ('etiket', 'Aktif', 2, 'Aktiv'),
    ('etiket', 'Pasif', 1, 'Inactive'),
    ('etiket', 'Pasif', 2, 'Inaktiv'),
    ('etiket', 'Borç', 1, 'Debit'),
    ('etiket', 'Borç', 2, 'Soll'),
    ('etiket', 'Alacak', 1, 'Credit'),
    ('etiket', 'Alacak', 2, 'Haben'),
    ('etiket', 'Bakiye', 1, 'Balance'),
    ('etiket', 'Bakiye', 2, 'Saldo'),
    ('etiket', 'Fiş No', 1, 'Entry No'),
    ('etiket', 'Fiş No', 2, 'Belegnummer'),
    ('etiket', 'Hesap', 1, 'Account'),
    ('etiket', 'Hesap', 2, 'Konto'),
    ('etiket', 'Kullanıcı', 1, 'User'),
    ('etiket', 'Kullanıcı', 2, 'Benutzer'),
    ('etiket', 'Kaydet ve Kapat', 1, 'Save & Close'),
    ('etiket', 'Kaydet ve Kapat', 2, 'Speichern & Schließen'),
    ('etiket', 'Kayıt', 1, 'Record'),
    ('etiket', 'Kayıt', 2, 'Datensatz'),
    ('etiket', 'Toplam', 1, 'Total'),
    ('etiket', 'Toplam', 2, 'Summe'),
    ('etiket', 'Seçili', 1, 'Selected'),
    ('etiket', 'Seçili', 2, 'Ausgewählt'),
    ('etiket', 'Sayfa', 1, 'Page'),
    ('etiket', 'Sayfa', 2, 'Seite'),
    ('etiket', 'Önceki', 1, 'Previous'),
    ('etiket', 'Önceki', 2, 'Zurück'),
    ('etiket', 'Sonraki', 1, 'Next'),
    ('etiket', 'Sonraki', 2, 'Weiter')
  ) as v(kapsam, anahtar, dil, metin)
 where not exists (select 1 from public.ceviri c
                    where c.kapsam = v.kapsam and c.anahtar = v.anahtar and c.dil = v.dil);

do $$
declare v_en integer; v_de integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    select count(*) into v_de from public.ceviri where dil = 2;
    raise notice '194 tamam: ceviri sozlugu (EN % / DE % kayit); eksik ceviride Turkce gosterilir.', v_en, v_de;
end $$;
