-- ============================================================================
--  Gentegre AI — ÇEVİRİ SÖZLÜĞÜ EKİ (liste başlıkları + kolon etiketleri)
--  195_ceviri_ek.sql
--
--  194 menü ve ortak etiketleri getirdi; ekranda kalan Türkçe metinler liste
--  başlıkları ("Hastalar") ve kolon adlarıydı ("Dosya No", "Ad Soyad").
--  Sözlük KADEMELİ doldurulur: çevirisi olmayan metin Türkçe görünür, ekran
--  boş kalmaz. Arayüz eksik çevirileri toplar (dil/ceviri.ts · eksikCeviriler).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin)
select v.kapsam, v.anahtar, v.dil, v.metin
  from (values
    ('menu', 'Hastalar', 1, 'Patients'),
    ('menu', 'Hastalar', 2, 'Patienten'),
    ('menu', 'Projeler', 1, 'Projects'),
    ('menu', 'Projeler', 2, 'Projekte'),
    ('menu', 'Görevler', 1, 'Tasks'),
    ('menu', 'Görevler', 2, 'Aufgaben'),
    ('menu', 'Fırsatlar', 1, 'Opportunities'),
    ('menu', 'Fırsatlar', 2, 'Verkaufschancen'),
    ('menu', 'Aday Müşteriler', 1, 'Leads'),
    ('menu', 'Aday Müşteriler', 2, 'Interessenten'),
    ('menu', 'Müşteriler', 1, 'Customers'),
    ('menu', 'Müşteriler', 2, 'Kunden'),
    ('menu', 'Tedarikçiler', 1, 'Suppliers'),
    ('menu', 'Tedarikçiler', 2, 'Lieferanten'),
    ('menu', 'Kisiler', 1, 'Contacts'),
    ('menu', 'Kisiler', 2, 'Kontakte'),
    ('menu', 'Kişiler', 1, 'Contacts'),
    ('menu', 'Kişiler', 2, 'Kontakte'),
    ('menu', 'Belgeler', 1, 'Documents'),
    ('menu', 'Belgeler', 2, 'Belege'),
    ('menu', 'Stoklar', 1, 'Items'),
    ('menu', 'Stoklar', 2, 'Artikel'),
    ('menu', 'Hizmetler', 1, 'Services'),
    ('menu', 'Hizmetler', 2, 'Dienstleistungen'),
    ('menu', 'Masraflar', 1, 'Expenses'),
    ('menu', 'Masraflar', 2, 'Aufwendungen'),
    ('menu', 'Personeller', 1, 'Employees'),
    ('menu', 'Personeller', 2, 'Mitarbeiter'),
    ('menu', 'Depolar', 1, 'Warehouses'),
    ('menu', 'Depolar', 2, 'Lager'),
    ('menu', 'Bankalar', 1, 'Banks'),
    ('menu', 'Bankalar', 2, 'Banken'),
    ('menu', 'Hesaplar', 1, 'Accounts'),
    ('menu', 'Hesaplar', 2, 'Konten'),
    ('menu', 'Çekler', 1, 'Cheques'),
    ('menu', 'Çekler', 2, 'Schecks'),
    ('menu', 'Senetler', 1, 'Promissory Notes'),
    ('menu', 'Senetler', 2, 'Wechsel'),
    ('menu', 'Kasa İşlemleri', 1, 'Cash Transactions'),
    ('menu', 'Kasa İşlemleri', 2, 'Kassenvorgänge'),
    ('menu', 'Muhasebe Fişleri', 1, 'Journal Entries'),
    ('menu', 'Muhasebe Fişleri', 2, 'Buchungssätze'),
    ('menu', 'Hesap Planı', 1, 'Chart of Accounts'),
    ('menu', 'Hesap Planı', 2, 'Kontenplan'),
    ('menu', 'Roller', 1, 'Roles'),
    ('menu', 'Roller', 2, 'Rollen'),
    ('menu', 'İşlem Günlüğü', 1, 'Audit Log'),
    ('menu', 'İşlem Günlüğü', 2, 'Protokoll'),
    ('menu', 'Gelen Kutusu', 1, 'Inbox'),
    ('menu', 'Gelen Kutusu', 2, 'Posteingang'),
    ('menu', 'Şube Tanımları', 1, 'Branches'),
    ('menu', 'Şube Tanımları', 2, 'Filialen'),
    ('etiket', 'Dosya No', 1, 'File No'),
    ('etiket', 'Dosya No', 2, 'Aktennummer'),
    ('etiket', 'Ad Soyad', 1, 'Full Name'),
    ('etiket', 'Ad Soyad', 2, 'Name'),
    ('etiket', 'TCKN', 1, 'National ID'),
    ('etiket', 'TCKN', 2, 'Personalausweis-Nr.'),
    ('etiket', 'Cep', 1, 'Mobile'),
    ('etiket', 'Cep', 2, 'Mobil'),
    ('etiket', 'E-Mail', 1, 'E-mail'),
    ('etiket', 'E-Mail', 2, 'E-Mail'),
    ('etiket', 'Cari Kodu', 1, 'Account Code'),
    ('etiket', 'Cari Kodu', 2, 'Kontonummer'),
    ('etiket', 'Stok Kodu', 1, 'Item Code'),
    ('etiket', 'Stok Kodu', 2, 'Artikelnummer'),
    ('etiket', 'Stok Adı', 1, 'Item Name'),
    ('etiket', 'Stok Adı', 2, 'Artikelname'),
    ('etiket', 'Hizmet', 1, 'Service'),
    ('etiket', 'Hizmet', 2, 'Dienstleistung'),
    ('etiket', 'Masraf', 1, 'Expense'),
    ('etiket', 'Masraf', 2, 'Aufwand'),
    ('etiket', 'Tür', 1, 'Type'),
    ('etiket', 'Tür', 2, 'Art'),
    ('etiket', 'Tipi', 1, 'Type'),
    ('etiket', 'Tipi', 2, 'Art'),
    ('etiket', 'Seri', 1, 'Series'),
    ('etiket', 'Seri', 2, 'Serie'),
    ('etiket', 'Fatura No', 1, 'Invoice No'),
    ('etiket', 'Fatura No', 2, 'Rechnungsnummer'),
    ('etiket', 'İrsaliye No', 1, 'Dispatch No'),
    ('etiket', 'İrsaliye No', 2, 'Lieferscheinnummer'),
    ('etiket', 'Protokol', 1, 'Protocol'),
    ('etiket', 'Protokol', 2, 'Protokoll'),
    ('etiket', 'Saat', 1, 'Time'),
    ('etiket', 'Saat', 2, 'Uhrzeit'),
    ('etiket', 'Vade', 1, 'Due Date'),
    ('etiket', 'Vade', 2, 'Fälligkeit'),
    ('etiket', 'Vade (gün)', 1, 'Term (days)'),
    ('etiket', 'Vade (gün)', 2, 'Zahlungsziel (Tage)'),
    ('etiket', 'Döviz', 1, 'Currency'),
    ('etiket', 'Döviz', 2, 'Währung'),
    ('etiket', 'Kur', 1, 'Rate'),
    ('etiket', 'Kur', 2, 'Kurs'),
    ('etiket', 'KDV Tutarı', 1, 'VAT Amount'),
    ('etiket', 'KDV Tutarı', 2, 'MwSt.-Betrag'),
    ('etiket', 'Net Tutar', 1, 'Net Amount'),
    ('etiket', 'Net Tutar', 2, 'Nettobetrag'),
    ('etiket', 'Kalan', 1, 'Remaining'),
    ('etiket', 'Kalan', 2, 'Restbetrag'),
    ('etiket', 'Tahsil', 1, 'Collected'),
    ('etiket', 'Tahsil', 2, 'Eingezogen'),
    ('etiket', 'Hasta', 1, 'Patient'),
    ('etiket', 'Hasta', 2, 'Patient'),
    ('etiket', 'Hekim', 1, 'Doctor'),
    ('etiket', 'Hekim', 2, 'Arzt'),
    ('etiket', 'Klinik', 1, 'Clinic'),
    ('etiket', 'Klinik', 2, 'Klinik'),
    ('etiket', 'Sıra', 1, 'Queue'),
    ('etiket', 'Sıra', 2, 'Reihenfolge'),
    ('etiket', 'Kaynak', 1, 'Source'),
    ('etiket', 'Kaynak', 2, 'Quelle'),
    ('etiket', 'Hedef', 1, 'Target'),
    ('etiket', 'Hedef', 2, 'Ziel'),
    ('etiket', 'e-Fatura', 1, 'e-Invoice'),
    ('etiket', 'e-Fatura', 2, 'e-Rechnung'),
    ('etiket', 'e-Arşiv', 1, 'e-Archive'),
    ('etiket', 'e-Arşiv', 2, 'e-Archiv'),
    ('etiket', 'e-İrsaliye', 1, 'e-Dispatch'),
    ('etiket', 'e-İrsaliye', 2, 'e-Lieferschein'),
    ('etiket', 'Senaryo', 1, 'Scenario'),
    ('etiket', 'Senaryo', 2, 'Szenario'),
    ('etiket', 'Gönderici', 1, 'Sender'),
    ('etiket', 'Gönderici', 2, 'Absender'),
    ('etiket', 'Alıcı', 1, 'Receiver'),
    ('etiket', 'Alıcı', 2, 'Empfänger'),
    ('etiket', 'Depo', 1, 'Warehouse'),
    ('etiket', 'Depo', 2, 'Lager'),
    ('etiket', 'Giriş', 1, 'In'),
    ('etiket', 'Giriş', 2, 'Eingang'),
    ('etiket', 'Çıkış', 1, 'Out'),
    ('etiket', 'Çıkış', 2, 'Ausgang'),
    ('etiket', 'Miktar', 1, 'Quantity'),
    ('etiket', 'Miktar', 2, 'Menge'),
    ('etiket', 'Kritik Stok', 1, 'Critical Stock'),
    ('etiket', 'Kritik Stok', 2, 'Mindestbestand'),
    ('etiket', 'Kayıt Tarihi', 1, 'Created'),
    ('etiket', 'Kayıt Tarihi', 2, 'Erfasst am'),
    ('etiket', 'Değiştirme Tarihi', 1, 'Modified'),
    ('etiket', 'Değiştirme Tarihi', 2, 'Geändert am'),
    ('etiket', 'Ekleyen', 1, 'Created By'),
    ('etiket', 'Ekleyen', 2, 'Erstellt von'),
    ('etiket', 'Şube Kodu', 1, 'Branch Code'),
    ('etiket', 'Şube Kodu', 2, 'Filialcode'),
    ('etiket', 'Fiş No', 1, 'Entry No'),
    ('etiket', 'Fiş No', 2, 'Buchungsnummer'),
    ('etiket', 'Fiş Türü', 1, 'Entry Type'),
    ('etiket', 'Fiş Türü', 2, 'Buchungsart'),
    ('etiket', 'Dönem', 1, 'Period'),
    ('etiket', 'Dönem', 2, 'Periode'),
    ('etiket', 'Yetki', 1, 'Permission'),
    ('etiket', 'Yetki', 2, 'Berechtigung'),
    ('etiket', 'Rol', 1, 'Role'),
    ('etiket', 'Rol', 2, 'Rolle'),
    ('etiket', 'Bu listede ara…', 1, 'Search in this list…'),
    ('etiket', 'Bu listede ara…', 2, 'In dieser Liste suchen…'),
    ('etiket', 'Aksiyon Seç', 1, 'Select Action'),
    ('etiket', 'Aksiyon Seç', 2, 'Aktion wählen'),
    ('etiket', 'Tüm Liste', 1, 'Full List'),
    ('etiket', 'Tüm Liste', 2, 'Gesamte Liste'),
    ('etiket', 'Liste', 1, 'List'),
    ('etiket', 'Liste', 2, 'Liste'),
    ('etiket', 'Grup', 1, 'Group'),
    ('etiket', 'Grup', 2, 'Gruppe'),
    ('etiket', 'Analiz', 1, 'Analysis'),
    ('etiket', 'Analiz', 2, 'Analyse'),
    ('etiket', 'Ekstre', 1, 'Statement'),
    ('etiket', 'Ekstre', 2, 'Auszug'),
    ('etiket', 'Inaktiv', 1, 'Inactive'),
    ('etiket', 'Inaktiv', 2, 'Inaktiv'),
    ('etiket', 'Fatura', 1, 'Invoice'),
    ('etiket', 'Fatura', 2, 'Rechnung'),
    ('etiket', 'İade', 1, 'Return'),
    ('etiket', 'İade', 2, 'Retoure'),
    ('etiket', 'Kısmi', 1, 'Partial'),
    ('etiket', 'Kısmi', 2, 'Teilweise'),
    ('etiket', 'Kapandı', 1, 'Closed'),
    ('etiket', 'Kapandı', 2, 'Abgeschlossen'),
    ('etiket', 'Açık', 1, 'Open'),
    ('etiket', 'Açık', 2, 'Offen'),
    ('etiket', 'Taslak', 1, 'Draft'),
    ('etiket', 'Taslak', 2, 'Entwurf'),
    ('etiket', 'Kesin', 1, 'Final'),
    ('etiket', 'Kesin', 2, 'Endgültig')
  ) as v(kapsam, anahtar, dil, metin)
 where not exists (select 1 from public.ceviri c
                    where c.kapsam = v.kapsam and c.anahtar = v.anahtar and c.dil = v.dil);

do $$
declare v_top integer;
begin
    select count(*) into v_top from public.ceviri;
    raise notice '195 tamam: sozlukte toplam % ceviri kaydi.', v_top;
end $$;

-- Aksiyon adlari ve kirilma yolu parcalari (arayuzde kalan Turkce metinler).
insert into public.ceviri (kapsam, anahtar, dil, metin)
select v.kapsam, v.anahtar, v.dil, v.metin from (values
  ('menu','Satis',1,'Sales'), ('menu','Satis',2,'Verkauf'),
  ('menu','Alis',1,'Purchasing'), ('menu','Alis',2,'Einkauf'),
  ('menu','Yonetim',1,'Administration'), ('menu','Yonetim',2,'Verwaltung'),
  ('menu','Hasta',1,'Patient'), ('menu','Hasta',2,'Patient'),
  ('menu','Stok',1,'Items'), ('menu','Stok',2,'Artikel'),
  ('etiket','Belgeyi Ac',1,'Open Document'), ('etiket','Belgeyi Ac',2,'Beleg öffnen'),
  ('etiket','Belgeyi Aç',1,'Open Document'), ('etiket','Belgeyi Aç',2,'Beleg öffnen'),
  ('etiket','İrsaliyeyi Aç',1,'Open Dispatch'), ('etiket','İrsaliyeyi Aç',2,'Lieferschein öffnen'),
  ('etiket','GENEL TOPLAM',1,'GRAND TOTAL'), ('etiket','GENEL TOPLAM',2,'GESAMTSUMME'),
  ('etiket','Kesinlestir',1,'Finalize'), ('etiket','Kesinlestir',2,'Abschließen'),
  ('etiket','Belgeyi Iptal Et',1,'Cancel Document'), ('etiket','Belgeyi Iptal Et',2,'Beleg stornieren'),
  ('etiket','Muhasebe Fişini Aç',1,'Open Journal Entry'), ('etiket','Muhasebe Fişini Aç',2,'Buchungssatz öffnen'),
  ('etiket','Kaynak Belgeyi Aç',1,'Open Source Document'), ('etiket','Kaynak Belgeyi Aç',2,'Quellbeleg öffnen'),
  ('etiket','Hedef Belgeyi Aç',1,'Open Target Document'), ('etiket','Hedef Belgeyi Aç',2,'Zielbeleg öffnen'),
  ('etiket','Yeni Sipariş',1,'New Order'), ('etiket','Yeni Sipariş',2,'Neuer Auftrag'),
  ('etiket','Yeni İrsaliye',1,'New Dispatch'), ('etiket','Yeni İrsaliye',2,'Neuer Lieferschein'),
  ('etiket','Kutuyu Yenile',1,'Refresh Inbox'), ('etiket','Kutuyu Yenile',2,'Posteingang aktualisieren'),
  ('etiket','Faturaya Aktar',1,'Transfer to Invoice'), ('etiket','Faturaya Aktar',2,'In Rechnung übernehmen'),
  ('etiket','Kabul Et',1,'Accept'), ('etiket','Kabul Et',2,'Annehmen'),
  ('etiket','Reddet',1,'Reject'), ('etiket','Reddet',2,'Ablehnen'),
  ('etiket','Belgeyi Görüntüle',1,'View Document'), ('etiket','Belgeyi Görüntüle',2,'Beleg anzeigen')
) as v(kapsam, anahtar, dil, metin)
 where not exists (select 1 from public.ceviri c
                    where c.kapsam = v.kapsam and c.anahtar = v.anahtar and c.dil = v.dil);
