-- 320: Radyolojide kontrast / sarf malzeme düşümü.
--
-- İstemde kontrast tipi ve ml'si zaten tutuluyordu ama stoktan hiçbir şey
-- düşmüyordu: kontrast, enjektör, kanül, film ve CD kayıt dışı gidiyor;
-- tetkik maliyeti ve kârlılığı hesaplanamıyor, kritik stok uyarısı çıkmıyor.
--
-- Yaklaşım: radyolojiye AYRI stok mantığı yazılmaz. Çekim tamamlanınca
-- mevcut belge hattından bir STOK ÇIKIŞ FİŞİ (tur 4, carisiz) üretilir;
-- stok_durum, lot bakiyesi ve maliyet zaten orada çözülüyor. Bu göç yalnız
-- "hangi tetkikte ne kullanılır" tanımını ve istem ↔ fiş bağını ekler.

-- ------------------------------------------- protokolün malzeme listesi ----
-- Çekim protokolü (314) tetkikin NASIL çekileceğini anlatıyordu; malzeme
-- listesi onun stok karşılığıdır. Kontrastsız protokolde liste boş kalır.
create table if not exists public.radyoloji_protokol_malzeme (
    id                integer generated by default as identity primary key,
    protokol_id       integer   not null references public.radyoloji_protokol(id)
                                on delete cascade,
    stok_id           integer   not null references public.stok(id),
    miktar            numeric(24,6) not null default 1,
    -- 1 = Otomatik (her çekimde düşer), 2 = İstenirse (CD gibi: kabulde
    --   işaretlenmişse önerilir, işaretlenmemişse önerilmez).
    dusum_tipi        smallint  not null default 1,
    -- Serbest metin kural notu: "1,5 mL/kg — 100 mL üstü 2. flakon".
    --   Hesap YAPILMAZ, teknisyene gösterilir; gerçek miktarı o onaylar.
    kural             varchar(200) not null default '',
    sira              smallint  not null default 1,
    ekleyen           integer   not null default 0,
    ekleme_tarihi     timestamp not null default (now())::timestamp,
    degistiren        integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_rad_protokol_malzeme
    on public.radyoloji_protokol_malzeme (protokol_id, stok_id);

comment on table public.radyoloji_protokol_malzeme is
  'Tetkikin standart sarf listesi (320) - çekim sonrası düşüm bunu önerir.';

-- --------------------------------------------------- istemin sarf kaydı ----
-- Satır belge_satir'da da duruyor; bu tablo "hangi istemde ne kadar kullanıldı"
-- sorusunu tek adımda cevaplar (maliyet ve tüketim raporları belge hattını
-- taramak zorunda kalmasın).
create table if not exists public.radyoloji_sarf (
    id            integer generated by default as identity primary key,
    istem_id      integer   not null references public.radyoloji_istem(id)
                            on delete cascade,
    belge_id      integer,                       -- üretilen çıkış fişi (tur 4)
    stok_id       integer   not null references public.stok(id),
    miktar        numeric(24,6) not null,
    depo_id       integer   references public.depo(id),
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default (now())::timestamp
);

create index if not exists ix_rad_sarf_istem on public.radyoloji_sarf (istem_id);
create index if not exists ix_rad_sarf_belge on public.radyoloji_sarf (belge_id);

comment on table public.radyoloji_sarf is
  'İstemde kullanılan sarf/kontrast (320) - üretilen stok çıkış fişine bağlı.';

-- ------------------------------------------------------------- ayarlar -----
-- Sarf düşümü kurulum tercihidir: stok modülünü kullanmayan kurumda kapalı
-- kalır (aktif = 0) ve çekim ekranı hiç sormaz.
insert into public.referans (anahtar, deger, tip, kapsam, aciklama)
select v.anahtar, v.deger, 'metin', 'firma', v.aciklama
  from (values
    ('radyoloji.sarf_aktif', '1',
     'Çekim tamamlanınca sarf/kontrast düşümü sorulsun mu (320)'),
    ('radyoloji.sarf_depo', '',
     'Sarf çıkışının yapılacağı depo; boşsa varsayılan depo (320)')
  ) v(anahtar, deger, aciklama)
 where not exists (select 1 from public.referans r where r.anahtar = v.anahtar);

-- --------------------------------------------------------- kod listesi -----
insert into public.kod_liste (kod, ad)
select 'rad.dusum_tipi', 'Sarf Düşüm Tipi'
 where not exists (select 1 from public.kod_liste k where k.kod = 'rad.dusum_tipi');

insert into public.kod_deger (liste_id, deger, ad)
select kl.id, v.deger, v.ad
  from (values (1, 'Otomatik'), (2, 'İstenirse')) v(deger, ad)
  join public.kod_liste kl on kl.kod = 'rad.dusum_tipi'
 where not exists (select 1 from public.kod_deger d
                    where d.liste_id = kl.id and d.deger = v.deger);

-- ------------------------------------------- protokolün malzeme görünümü ---
-- Çekim sonrası öneri: protokol satırı + stok adı + o depodaki kalan + kritik
-- eşik. Kalan burada hesaplanır ki ekran ikinci bir sorgu atmasın.
create or replace view public.v_radyoloji_protokol_malzeme as
select m.id,
       m.protokol_id,
       p.hizmet_id,
       m.stok_id,
       coalesce(s.kod, '')                       as stok_kod,
       coalesce(s.ad, '')                        as stok_ad,
       coalesce(kb.ad, '')                       as birim,
       coalesce(s.izleme, 0)                     as izleme,
       m.miktar,
       m.dusum_tipi,
       m.kural,
       m.sira
  from public.radyoloji_protokol_malzeme m
  join public.radyoloji_protokol p on p.id = m.protokol_id
  left join public.stok s on s.id = m.stok_id
  left join public.kod_liste kl on kl.kod = 'stok.ana_birim'
  left join public.kod_deger kb on kb.liste_id = kl.id and kb.deger = s.ana_birim
 order by m.sira, m.id;

comment on view public.v_radyoloji_protokol_malzeme is
  'Tetkikin sarf listesi + stok bilgisi (320).';
