-- ============================================================================
--  398 - ONAM ALTYAPISI (Faz 0, ortak platform)
--
--  Teletıp görüşmesi, genetik vaka, girişimsel işlem, KVKK aydınlatma, açık
--  rıza... hepsi "kişiye metin gösterildi, kabul etti, kaydı duruyor" diyor.
--  Yol haritası bunu FAZ 0'a koydu: her modül kendi onam kopyasını yazarsa
--  (Delphi'de IMAJ/DOKUMAN/GOREVYORUM'un başına gelen) sonradan tek bir
--  "hangi onamı ne zaman verdi" sorusu cevaplanamaz.
--
--  İki tablo:
--    onam_metni  - METNİN kendisi ve SÜRÜMÜ. Metin değişince yeni sürüm açılır;
--                  eski onamlar hangi metne verildiğini bilir (hukuki dayanak).
--    onam        - kişinin verdiği/verMEDİĞİ cevap. Kaynak GENERIC
--                  (kaynak_tur + kaynak_id): başvuru, muayene, görüşme, vaka.
--
--  Islak imza görüntüsü / imzalı PDF mevcut doküman deposuna gider (dokuman_id) -
--  ikinci bir içerik deposu açılmaz.
-- ============================================================================

create table if not exists public.onam_metni (
    id                integer      primary key generated by default as identity,
    kod               varchar(40)  not null,
    ad                varchar(160) not null,
    -- 1 KVKK aydınlatma · 2 açık rıza · 3 tıbbi işlem · 4 teletıp
    -- 5 genetik · 6 fotoğraf/video · 9 diğer
    tur               smallint     not null default 9,
    surum             smallint     not null default 1,
    metin             text         not null default '',
    -- Metin biçimi: 0 düz metin · 1 HTML (şablon değişkenleri {{hasta_ad}} gibi)
    bicim             smallint     not null default 0,
    yururluk_bas      date         not null default current_date,
    yururluk_bit      date,
    zorunlu           smallint     not null default 0,   -- 1 ise ilgili akış onamsız ilerlemez
    durum             smallint     not null default 1,
    aciklama          varchar(300) not null default '',
    ekleyen           integer      not null default 0,
    ekleme_tarihi     timestamp    not null default now(),
    degistiren        integer      not null default 0,
    degistirme_tarihi timestamp,
    constraint ux_onam_metni_kod_surum unique (kod, surum)
);

comment on table public.onam_metni is
    'Onam metinleri ve sürümleri (398). Metin değişince yeni SÜRÜM açılır; eski onam eski metne bağlı kalır.';

create index if not exists ix_onam_metni_tur on public.onam_metni(tur, durum);

create table if not exists public.onam (
    id                integer   primary key generated by default as identity,
    metin_id          integer   not null references public.onam_metni(id),
    surum             smallint  not null,                       -- metnin o anki sürümü
    taraf_id          integer   not null references public.taraf(id),   -- onamı veren kişi
    -- Onam KİMİN ADINA verildi: hasta kendisi değilse (veli/vasi) kişi burada.
    veren_taraf_id    integer   references public.taraf(id),
    veren_yakinlik    varchar(60) not null default '',
    -- Kaynak GENERIC: 1 hasta (genel) · 2 başvuru/belge · 3 muayene
    -- 4 teletıp görüşmesi · 5 lab/genetik vaka · 6 radyoloji istemi
    kaynak_tur        smallint  not null default 1,
    kaynak_id         integer,
    -- 1 verildi · 0 reddedildi · 2 geri çekildi
    sonuc             smallint  not null default 1,
    -- 1 ıslak imza · 2 dijital (portal/tablet) · 3 sözlü (tanıklı) · 4 e-imza
    kanal             smallint  not null default 1,
    tarih             timestamp not null default now(),
    gecerlilik        date,
    dokuman_id        integer   references public.dokuman(id),  -- imzalı PDF / imza görüntüsü
    ip                varchar(45)  not null default '',
    aciklama          varchar(300) not null default '',
    geri_cekme_tarihi timestamp,
    geri_cekme_neden  varchar(300) not null default '',
    sube_id           integer,
    ekleyen           integer   not null default 0,
    ekleme_tarihi     timestamp not null default now(),
    degistiren        integer   not null default 0,
    degistirme_tarihi timestamp
);

comment on table public.onam is
    'Verilen/reddedilen onamlar (398). Kaynak generic: kaynak_tur + kaynak_id.';

create index if not exists ix_onam_taraf   on public.onam(taraf_id, tarih desc);
create index if not exists ix_onam_kaynak  on public.onam(kaynak_tur, kaynak_id);
create index if not exists ix_onam_metin   on public.onam(metin_id);

-- Aynı kaynak için aynı metin İKİ KEZ verilmiş sayılmasın (geri çekilen hariç).
create unique index if not exists ux_onam_kaynak_metin
    on public.onam(metin_id, kaynak_tur, coalesce(kaynak_id, 0), taraf_id)
 where sonuc = 1 and geri_cekme_tarihi is null;

-- ---------------------------------------------------------------- kod listesi
insert into public.kod_liste (kod, ad)
select 'onam.tur', 'Onam Türü'
 where not exists (select 1 from public.kod_liste where kod = 'onam.tur');

insert into public.kod_deger (liste_id, deger, ad, sira)
select l.id, v.deger, v.ad, v.sira
  from public.kod_liste l,
       (values (1,'KVKK Aydınlatma',1), (2,'Açık Rıza',2), (3,'Tıbbi İşlem',3),
               (4,'Teletıp',4), (5,'Genetik',5), (6,'Fotoğraf / Video',6),
               (9,'Diğer',9)) as v(deger, ad, sira)
 where l.kod = 'onam.tur'
   and not exists (select 1 from public.kod_deger d
                    where d.liste_id = l.id and d.deger = v.deger);

insert into public.kod_liste (kod, ad)
select 'onam.kanal', 'Onam Kanalı'
 where not exists (select 1 from public.kod_liste where kod = 'onam.kanal');

insert into public.kod_deger (liste_id, deger, ad, sira)
select l.id, v.deger, v.ad, v.sira
  from public.kod_liste l,
       (values (1,'Islak İmza',1), (2,'Dijital (portal/tablet)',2),
               (3,'Sözlü (tanıklı)',3), (4,'e-İmza',4)) as v(deger, ad, sira)
 where l.kod = 'onam.kanal'
   and not exists (select 1 from public.kod_deger d
                    where d.liste_id = l.id and d.deger = v.deger);
