-- =====================================================================
-- 442 - LABORATUVAR İÇ VE DIŞ KALİTE KONTROL (İKK / DKK)
--
-- Mockup: Ekranlar/Lab/lab_kalite_kontrol.html
--
-- NEDEN: hasta sonucunun doğruluğu, o gün cihazın doğru ölçtüğünün
-- kanıtına bağlıdır. Kontrol ölçümü tutmayan bir testin hasta sonucu -
-- normal görünse bile - güvenilmez. ISO 15189'un istediği de budur:
-- lot bazlı hedef/SD, Westgard kural seti, ret hâlinde düzeltici faaliyet
-- ve ETKİLENEN HASTA SONUÇLARININ gözden geçirilmesi.
--
-- EN ÖNEMLİ BAĞ: KK geçersizken o testin hasta sonuçları OTO-ONAYA
-- GİRMEZ (fn_lab_kk_gecerli). Kalite kontrolü ayrı bir kayıt defteri
-- olarak tutup sonuç hattına bağlamamak, kuralı süse çevirirdi.
-- =====================================================================

-- ---------------------------------------------------------------------
--  1) KONTROL LOTU ve HEDEFLERİ
--
--  HEDEF/SD LOT BAŞINADIR: yeni lot açıldığında değerler değişir; tek bir
--  "test hedefi" tutmak, lot geçişinde bütün grafiği kaydırırdı.
--  Üretici değeri başlangıçtır; laboratuvar kendi kümülatif ortalama ve
--  SD'sini biriktirir (20 ölçümden sonra kendi verisi esas alınır).
-- ---------------------------------------------------------------------
create table if not exists public.lab_kk_lot (
    id            integer generated by default as identity primary key,
    kod           varchar(30)  not null,
    materyal_ad   varchar(200) not null,
    lot           varchar(40)  not null,
    uretici       varchar(120) not null default '',
    skt           date,
    seviye_sayisi smallint     not null default 2,
    acilis_tarihi date,
    aciklama      varchar(300) not null default '',
    durum         smallint     not null default 0,   -- 0 aktif · 1 pasif
    sube_id       integer   not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_lab_kk_lot_kod
    on public.lab_kk_lot (upper(kod));

create table if not exists public.lab_kk_hedef (
    id            integer generated by default as identity primary key,
    lot_id        integer  not null references public.lab_kk_lot(id) on delete cascade,
    tetkik_id     integer  not null references public.lab_tetkik(id),
    seviye        smallint not null default 1,
    -- Üretici prospektüs değeri: laboratuvar kendi verisini biriktirene
    --   kadar kullanılır.
    uretici_hedef numeric(19,6),
    uretici_sd    numeric(19,6),
    -- Laboratuvarın KENDİ kümülatifi: yöntem, cihaz ve teknisyen etkisini
    --   içerir; üreticininki bunları göremez.
    kumulatif_n   integer  not null default 0,
    kumulatif_ort numeric(19,6),
    kumulatif_sd  numeric(19,6),
    -- Kümülatif geçerli sayılması için en az kaç ölçüm gerekli (CLSI: 20).
    esik_n        integer  not null default 20,
    birim         varchar(20) not null default '',
    durum         smallint not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_lab_kk_hedef
    on public.lab_kk_hedef (lot_id, tetkik_id, seviye);

-- YÜRÜRLÜKTEKİ HEDEF: kümülatif eşiği geçtiyse laboratuvarın kendi
--   değeri, geçmediyse üreticininki. Karar tek yerde - ekran, kural
--   motoru ve rapor aynı hedefi görmeli.
create or replace function public.fn_lab_kk_hedef(p_hedef_id integer)
returns table (hedef numeric, sd numeric, kaynak text)
language sql stable as $$
    select case when h.kumulatif_n >= h.esik_n and h.kumulatif_ort is not null
                then h.kumulatif_ort else h.uretici_hedef end,
           case when h.kumulatif_n >= h.esik_n and h.kumulatif_sd is not null
                then h.kumulatif_sd else h.uretici_sd end,
           case when h.kumulatif_n >= h.esik_n and h.kumulatif_sd is not null
                then 'laboratuvar kümülatif (n=' || h.kumulatif_n || ')'
                else 'üretici' end
      from public.lab_kk_hedef h
     where h.id = p_hedef_id;
$$;

-- ---------------------------------------------------------------------
--  2) WESTGARD KURAL SETİ
--
--  Kural seti TEST BAZLI: bir HbA1c ile bir troponinin tolere ettiği
--  sapma aynı değildir. Tetkik boş (null) olan satırlar VARSAYILAN sete
--  aittir; teste özel satır varsa o kazanır.
-- ---------------------------------------------------------------------
create table if not exists public.lab_kk_kural (
    id        integer generated by default as identity primary key,
    tetkik_id integer references public.lab_tetkik(id) on delete cascade,
    -- 1_3s · 2_2s · R_4s · 4_1s · 10x · 1_2s · 2of3_2s
    kural     varchar(12) not null,
    -- 0 kapalı · 1 uyarı · 2 ret
    davranis  smallint not null default 2,
    sira      smallint not null default 0,
    aciklama  varchar(200) not null default '',
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_lab_kk_kural
    on public.lab_kk_kural (coalesce(tetkik_id, 0), upper(kural));

-- ---------------------------------------------------------------------
--  3) KK ÖLÇÜMLERİ
--
--  Ölçüm CİHAZDAN (kontrol barkodu) ya da ELLE gelir. Kural sonucu ve
--  ihlal listesi satırda saklanır: kural seti sonradan değişse geçmiş
--  değerlendirme değişmemeli (hasta sonucundaki bayrakla aynı gerekçe).
-- ---------------------------------------------------------------------
create table if not exists public.lab_kk_olcum (
    id            bigint generated by default as identity primary key,
    hedef_id      integer  not null references public.lab_kk_hedef(id),
    lot_id        integer  not null references public.lab_kk_lot(id),
    tetkik_id     integer  not null references public.lab_tetkik(id),
    seviye        smallint not null default 1,
    cihaz_id      integer references public.cihaz(id),
    cihaz_mesaj_id bigint,
    olcum_zamani  timestamp not null default now(),
    deger         numeric(19,6) not null,
    -- Z SKORU saklanır: hedef/SD sonradan güncellenince eski ölçümün
    --   grafikteki yeri kaymamalı (Levey-Jennings geçmişi kayıt defteridir).
    z             numeric(9,3),
    hedef         numeric(19,6),
    sd            numeric(19,6),
    ihlaller      text[] not null default '{}',
    -- 1 kabul · 2 uyarı · 3 ret
    durum         smallint not null default 1,
    -- 1 cihaz · 2 elle
    kaynak        smallint not null default 2,
    tekrar        smallint not null default 0,   -- düzeltme sonrası tekrar ölçümü
    -- RET HÂLİNDE DÜZELTİCİ FAALİYET ZORUNLU (ISO 15189): serbest metin
    --   ama boş bırakılamaz - "ne yaptık" yazılmayan ret, kaydı denetimde
    --   savunulamaz kılar.
    aksiyon       varchar(600) not null default '',
    -- Etkilenen hasta sonuçlarının gözden geçirilmesi: kaç sonuç bakıldı,
    --   kaçı değişti.
    gozden_gecirilen integer not null default 0,
    duzeltilen    integer  not null default 0,
    onay_id       integer,
    onay_zamani   timestamp,
    sube_id       integer   not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create index if not exists ix_lab_kk_olcum_seri
    on public.lab_kk_olcum (hedef_id, olcum_zamani desc);
create index if not exists ix_lab_kk_olcum_tetkik
    on public.lab_kk_olcum (tetkik_id, olcum_zamani desc);

-- ---------------------------------------------------------------------
--  4) DIŞ KALİTE (DKK)
--
--  Dönem bazlı; SDI = (bizim sonuç − hedef) / grup SD. |SDI| ≤ 2 kabul,
--  2-3 uyarı, > 3 kabul edilemez (yaygın program pratiği).
-- ---------------------------------------------------------------------
create table if not exists public.lab_dkk_sonuc (
    id            integer generated by default as identity primary key,
    program       varchar(60) not null,          -- KBUDEK · RIQAS · …
    donem         varchar(20) not null,          -- 2026-08
    tetkik_id     integer not null references public.lab_tetkik(id),
    numune_kodu   varchar(30) not null default '',
    sonucumuz     numeric(19,6),
    hedef         numeric(19,6),
    grup_sd       numeric(19,6),
    grup_n        integer,
    yontem        varchar(120) not null default '',
    sdi           numeric(9,3),
    -- 1 kabul · 2 uyarı · 3 kabul edilemez
    degerlendirme smallint not null default 1,
    aksiyon       varchar(600) not null default '',
    rapor_tarihi  date,
    sube_id       integer   not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create index if not exists ix_lab_dkk_donem
    on public.lab_dkk_sonuc (donem, tetkik_id);

-- ---------------------------------------------------------------------
--  5) CİHAZ OLAYLARI
--
--  Kalibrasyon, bakım, reaktif lot değişimi, arıza. Levey-Jennings'teki
--  kaymanın nedeni çoğu zaman burada yazar; ayrı tutulmazsa "29-30.08
--  kayma eğilimi" ile "reaktif lot değişimi" arasındaki bağ kurulamaz.
-- ---------------------------------------------------------------------
create table if not exists public.lab_cihaz_olay (
    id            integer generated by default as identity primary key,
    cihaz_id      integer references public.cihaz(id),
    tetkik_id     integer references public.lab_tetkik(id),
    zaman         timestamp not null default now(),
    -- 1 kalibrasyon · 2 bakım · 3 reaktif lot değişimi · 4 arıza ·
    -- 5 KK ret sonrası tekrar · 9 diğer
    olay          smallint not null default 1,
    aciklama      varchar(600) not null default '',
    lot           varchar(40) not null default '',
    kullanici_id  integer,
    sube_id       integer   not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create index if not exists ix_lab_cihaz_olay
    on public.lab_cihaz_olay (cihaz_id, zaman desc);

-- ---------------------------------------------------------------------
--  6) WESTGARD DEĞERLENDİRMESİ
--
--  Kurallar seri gerektirir: 2₂ₛ ardışık iki ölçüm, R₄ₛ aynı çalışmadaki
--  iki seviye arasında 4 SD açıklık, 4₁ₛ son dört, 10ₓ son on ölçüm aynı
--  yönde. Tek ölçüme bakan bir kontrol, kaymayı (sistematik hatayı) hiç
--  göremez - asıl tehlike odur; rastgele hata gürültü yapar, kayma sessizce
--  bütün hastaları etkiler.
-- ---------------------------------------------------------------------
create or replace function public.fn_lab_westgard(p_olcum_id bigint)
returns table (durum smallint, ihlaller text[])
language plpgsql as $$
declare
    v_hedef_id integer;
    v_tetkik   integer;
    v_zaman    timestamp;
    v_z        numeric;
    v_ihlal    text[] := '{}';
    v_durum    smallint := 1;
    v_seri     numeric[];
    v_r4s      numeric;
    v_davranis smallint;
begin
    select o.hedef_id, o.tetkik_id, o.olcum_zamani, o.z
      into v_hedef_id, v_tetkik, v_zaman, v_z
      from public.lab_kk_olcum o where o.id = p_olcum_id;

    if v_z is null then
        return query select 1::smallint, '{}'::text[];
        return;
    end if;

    -- Bu ölçüm DAHİL, aynı hedef (lot+tetkik+seviye) için son 10 ölçüm,
    --   yeniden eskiye.
    select array_agg(z order by olcum_zamani desc, id desc)
      into v_seri
      from (select z, olcum_zamani, id
              from public.lab_kk_olcum
             where hedef_id = v_hedef_id and olcum_zamani <= v_zaman
               and z is not null
             order by olcum_zamani desc, id desc
             limit 10) s;

    -- 1_3s: tek ölçüm ±3 SD dışında (rastgele hata, klasik ret kuralı).
    if abs(v_z) > 3 then v_ihlal := array_append(v_ihlal, '1_3s'); end if;

    -- 1_2s: uyarı kuralı - tek başına ret değil, diğer kuralları TETİKLER.
    if abs(v_z) > 2 then v_ihlal := array_append(v_ihlal, '1_2s'); end if;

    -- 2_2s: ardışık iki ölçüm aynı yönde ±2 SD dışında (sistematik hata).
    if cardinality(v_seri) >= 2
       and abs(v_seri[1]) > 2 and abs(v_seri[2]) > 2
       and sign(v_seri[1]) = sign(v_seri[2]) then
        v_ihlal := array_append(v_ihlal, '2_2s');
    end if;

    -- R_4s: AYNI ÇALIŞMADA iki seviye arasında 4 SD açıklık (rastgele hata).
    --   Aynı çalışma = ±2 saat; kontroller birlikte konur.
    select max(abs(o2.z - v_z)) into v_r4s
      from public.lab_kk_olcum o2
      join public.lab_kk_hedef h2 on h2.id = o2.hedef_id
      join public.lab_kk_hedef h1 on h1.id = v_hedef_id
     where h2.lot_id = h1.lot_id and h2.tetkik_id = h1.tetkik_id
       and h2.seviye <> h1.seviye
       and o2.olcum_zamani between v_zaman - interval '2 hours'
                               and v_zaman + interval '2 hours'
       and o2.z is not null;
    if coalesce(v_r4s, 0) > 4 then v_ihlal := array_append(v_ihlal, 'R_4s'); end if;

    -- 4_1s: son dört ölçüm aynı yönde ±1 SD dışında (kayma başlangıcı).
    if cardinality(v_seri) >= 4
       and (v_seri[1] > 1 and v_seri[2] > 1 and v_seri[3] > 1 and v_seri[4] > 1
            or v_seri[1] < -1 and v_seri[2] < -1 and v_seri[3] < -1 and v_seri[4] < -1) then
        v_ihlal := array_append(v_ihlal, '4_1s');
    end if;

    -- 10x: son on ölçüm ortalamanın aynı tarafında (yerleşmiş kayma).
    if cardinality(v_seri) >= 10
       and ((select count(*) from unnest(v_seri) x where x > 0) = 10
            or (select count(*) from unnest(v_seri) x where x < 0) = 10) then
        v_ihlal := array_append(v_ihlal, '10x');
    end if;

    -- DAVRANIŞ kural setinden: teste özel satır varsa o, yoksa varsayılan.
    --   Kapalı (0) kurallar ihlal listesinde KALIR ama durumu değiştirmez -
    --   "bu kural kapalıydı" bilgisi denetimde gerekir.
    if cardinality(v_ihlal) > 0 then
        select max(k.davranis) into v_davranis
          from unnest(v_ihlal) i
          join lateral (
                select davranis from public.lab_kk_kural k
                 where upper(k.kural) = upper(i)
                   and (k.tetkik_id = v_tetkik or k.tetkik_id is null)
                 order by k.tetkik_id nulls last
                 limit 1) k on true;
        -- İKİ AYRI KOD UZAYI: kural davranışı 0 kapalı · 1 uyarı · 2 ret;
        --   ölçüm durumu 1 kabul · 2 uyarı · 3 ret. Doğrudan atamak, ret
        --   kuralını "uyarı" olarak kaydediyordu - yani oto-onay kapanmıyordu.
        v_durum := case coalesce(v_davranis, 0)
                       when 2 then 3::smallint      -- ret
                       when 1 then 2::smallint      -- uyarı
                       else 1::smallint end;        -- kapalı kural = kabul
    end if;

    update public.lab_kk_olcum
       set ihlaller = v_ihlal, durum = v_durum
     where id = p_olcum_id;

    return query select v_durum, v_ihlal;
end $$;

-- ---------------------------------------------------------------------
--  7) KK GEÇERLİLİĞİ - hasta sonucuna bağlanan yer
--
--  Bir testin son KK ölçümü RET ise ve düzeltme sonrası geçerli bir tekrar
--  yoksa, o testin sonuçları OTO-ONAYA GİRMEZ. Kural motorunun "temiz
--  sonuç" kararı cihazın o gün doğru ölçtüğü varsayımına dayanır; kontrol
--  tutmuyorsa varsayım çürümüştür.
--
--  Pencere: son 24 saat. Hiç KK yoksa "geçerli" sayılır - kalite kontrolü
--  tanımlanmamış bir testi çalıştırmamak ayrı bir karardır ve burada
--  zorlanmaz (kurulum aşamasındaki laboratuvarı kilitlerdi).
-- ---------------------------------------------------------------------
create or replace function public.fn_lab_kk_gecerli(p_tetkik_id integer,
                                                    p_zaman timestamp default null)
returns boolean language sql stable as $$
    -- localtimestamp (timestamptz DEĞİL): olcum_zamani saat dilimsiz
    --   tutuluyor; now() ile karşılaştırmak fonksiyonu "timestamp with
    --   time zone" imzasına zorluyor ve çağrılar 42883 ile düşüyordu.
    select coalesce(
        (select o.durum <> 3
           from public.lab_kk_olcum o
          where o.tetkik_id = p_tetkik_id
            and o.olcum_zamani <= coalesce(p_zaman, localtimestamp)
            and o.olcum_zamani >= coalesce(p_zaman, localtimestamp) - interval '24 hours'
          order by o.olcum_zamani desc, o.id desc
          limit 1),
        true);
$$;

comment on function public.fn_lab_kk_gecerli(integer, timestamp) is
    'Testin son 24 saatlik KK olcumu RET degilse true. Oto-onay bu bayraga '
    'bakar: kontrol tutmayan cihazin "temiz" sonucu otomatik onaylanmaz.';

-- ---------------------------------------------------------------------
--  8) KÜMÜLATİF İSTATİSTİK
--
--  Laboratuvarın kendi ortalama/SD'si RET EDİLEN ölçümler hariç tutularak
--  hesaplanır: ret bir ölçüm hatasıdır, hedefi kaydırmamalı.
-- ---------------------------------------------------------------------
create or replace function public.fn_lab_kk_kumulatif(p_hedef_id integer)
returns integer language plpgsql as $$
declare
    v_n integer; v_ort numeric; v_sd numeric;
begin
    select count(*), avg(deger), stddev_samp(deger)
      into v_n, v_ort, v_sd
      from public.lab_kk_olcum
     where hedef_id = p_hedef_id and durum <> 3;

    update public.lab_kk_hedef
       set kumulatif_n = coalesce(v_n, 0),
           kumulatif_ort = v_ort,
           kumulatif_sd = v_sd,
           degistirme_tarihi = now()
     where id = p_hedef_id;

    return coalesce(v_n, 0);
end $$;

-- ---------------------------------------------------------------------
--  9) LOOKUP'LAR ve GÖRÜNÜMLER
-- ---------------------------------------------------------------------
drop view if exists public.v_lab_kk_lot_lookup;
create view public.v_lab_kk_lot_lookup as
select l.id, l.kod, l.kod || ' · ' || l.materyal_ad || ' (lot ' || l.lot || ')' as ad,
       case when l.durum = 0 then 1 else 0 end::smallint as aktif
  from public.lab_kk_lot l;

-- LEVEY-JENNINGS SERİSİ: grafik ekranının kaynağı. Z skoru ölçümle
--   saklandığı için burada yeniden hesaplanmaz.
drop view if exists public.v_lab_kk_lj;
create view public.v_lab_kk_lj as
select o.id, o.hedef_id, o.lot_id, o.tetkik_id, t.kod as tetkik_kod, t.ad as tetkik_ad,
       o.seviye, o.olcum_zamani, o.deger, o.z, o.hedef, o.sd, o.durum, o.ihlaller,
       o.kaynak, o.aksiyon, coalesce(c.kod, '') as cihaz_kod, l.materyal_ad, l.lot,
       o.sube_id
  from public.lab_kk_olcum o
  join public.lab_kk_lot l on l.id = o.lot_id
  join public.lab_tetkik t on t.id = o.tetkik_id
  left join public.cihaz c on c.id = o.cihaz_id;

-- ---------------------------------------------------------------------
-- 10) YETKİ
-- ---------------------------------------------------------------------
insert into public.yetki (kod, ad, grup, tur, sira)
select v.kod, v.ad, 'Laboratuvar', v.tur, v.sira
  from (values ('lab.kk',      'Kalite kontrol (İKK/DKK)', 0::smallint, 459::smallint),
               ('lab.kk.onay', 'KK ret onayı / serbest bırakma', 1::smallint, 460::smallint))
         as v(kod, ad, tur, sira)
 where not exists (select 1 from public.yetki y where y.kod = v.kod);

insert into public.rol_yetki (rol_id, yetki_id, gor, ekle, degistir, sil)
select r.id, y.id, 1, 1, 1, 1
  from public.rol r, public.yetki y
 where r.ad in ('Yönetici', 'Yonetici')
   and y.kod in ('lab.kk', 'lab.kk.onay')
   and not exists (select 1 from public.rol_yetki x
                    where x.rol_id = r.id and x.yetki_id = y.id);

update public.rol set yetki_surumu = yetki_surumu + 1;

-- ---------------------------------------------------------------------
-- 11) VARSAYILAN WESTGARD SETİ (mockuptaki set)
--
--  1₃ₛ ret · 2₂ₛ ret · R₄ₛ ret · 4₁ₛ uyarı · 10ₓ uyarı · 1₂ₛ uyarı
--  (1₂ₛ tek başına ret DEĞİLDİR: her 20 ölçümden biri şansa ±2 SD dışına
--   düşer; ret sayılsa laboratuvar durmadan kalibrasyon yapardı.)
-- ---------------------------------------------------------------------
insert into public.lab_kk_kural (tetkik_id, kural, davranis, sira, aciklama)
select null, v.kural, v.davranis, v.sira, v.acik
  from (values
      ('1_3s', 2::smallint, 10::smallint, 'Tek ölçüm ±3 SD dışında - rastgele hata'),
      ('2_2s', 2::smallint, 20::smallint, 'Ardışık iki ölçüm aynı yönde ±2 SD dışında - sistematik hata'),
      ('R_4s', 2::smallint, 30::smallint, 'Aynı çalışmada iki seviye arası 4 SD açıklık'),
      ('4_1s', 1::smallint, 40::smallint, 'Son dört ölçüm aynı yönde ±1 SD dışında - kayma'),
      ('10x',  1::smallint, 50::smallint, 'Son on ölçüm ortalamanın aynı tarafında'),
      ('1_2s', 1::smallint, 60::smallint, 'Uyarı kuralı - tek başına ret değildir')
  ) as v(kural, davranis, sira, acik)
 where not exists (select 1 from public.lab_kk_kural k
                    where k.tetkik_id is null and upper(k.kural) = upper(v.kural));

do $$
begin
    raise notice '442 tamam: lab_kk_lot/hedef/kural/olcum, lab_dkk_sonuc, lab_cihaz_olay + Westgard';
end $$;
