-- =====================================================================
-- 445 - DIŞ LABORATUVAR GÖNDERİMİ
--
-- Mockup: lab_sureci.html §10 ("Katalogda dış lab'a işaretli tetkik:
-- gönderim listesi, kurye/sıcaklık, sonuç PDF/HL7 ile alınır, alış
-- faturası eşleştirilir"), lab_istem_numune_kabul.html ("📦 Dış Lab'a
-- Gönder"), lab_sonuc_formu_biyokimya.html ("Dış lab: —").
--
-- NEDEN AYRI TABLO: numune binadan ÇIKAR. O andan itibaren laboratuvarın
-- elinde olan tek şey kayıttır - hangi tüp, kime, ne zaman, hangi kurye
-- ile, hangi sıcaklıkta gitti. Numune kaybolduğunda ya da sonuç
-- gecikince cevabı verecek olan bu zincirdir; istem satırına bir
-- "dış lab" bayrağı koymak, sorumluluğun devredildiği anı kaydetmezdi.
--
-- SOĞUK ZİNCİR KAYDI ISO 15189 gereği: -20°C isteyen bir testin numunesi
-- oda sıcaklığında gittiyse sonuç geçersizdir ve bunu SONRADAN bilmek
-- gerekir.
--
-- DIŞ LAB SONUCU OTO-ONAYA GİRMEZ: başka bir laboratuvarın yöntemini,
-- referansını ve kalite kontrolünü biz doğrulamadık. Sonuç kaydedilir,
-- uzman görüp onaylar.
-- =====================================================================

-- ---------------------------------------------------------------------
--  1) DIŞ LABORATUVAR TANIMI
--
--  Kurum zaten `taraf` (tedarikçi); burada yalnız LABORATUVAR'a özgü
--  alanlar var: sonuç kanalı, taşıma koşulu, sözleşme TAT'ı.
-- ---------------------------------------------------------------------
create table if not exists public.lab_dis_lab (
    id            integer generated by default as identity primary key,
    taraf_id      integer not null references public.taraf(id),
    kod           varchar(20)  not null,
    ad            varchar(200) not null,
    -- 1 PDF/e-posta · 2 HL7 · 3 portal · 4 elden
    sonuc_kanali  smallint     not null default 1,
    -- Kurumun kendi test kodlarını kullandığı yer: eşleme lab_dis_test'te.
    yetkili       varchar(120) not null default '',
    telefon       varchar(30)  not null default '',
    eposta        varchar(120) not null default '',
    sozlesme_tat_gun smallint  not null default 3,
    kurye_firma   varchar(120) not null default '',
    aciklama      varchar(400) not null default '',
    durum         smallint     not null default 0,
    sube_id       integer   not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_lab_dis_lab_kod
    on public.lab_dis_lab (upper(kod));

-- DIŞ LABIN KENDİ TEST KODU: sonuç PDF/HL7 ile gelirken onların koduyla
--   gelir; eşleme olmadan hangi tetkiğe yazılacağı belirsiz kalır
--   (cihaz eşlemesiyle aynı desen, 434).
create table if not exists public.lab_dis_test (
    id           integer generated by default as identity primary key,
    dis_lab_id   integer not null references public.lab_dis_lab(id) on delete cascade,
    tetkik_id    integer not null references public.lab_tetkik(id),
    dis_kod      varchar(40)  not null default '',
    dis_ad       varchar(200) not null default '',
    birim        varchar(20)  not null default '',
    -- Anlaşma fiyatı: alış faturası eşleştirmesinde beklenen tutar.
    birim_fiyat  numeric(19,4),
    tat_gun      smallint,
    durum        smallint not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_lab_dis_test
    on public.lab_dis_test (dis_lab_id, tetkik_id);

-- ---------------------------------------------------------------------
--  2) GÖNDERİM (sevk) BAŞLIĞI
-- ---------------------------------------------------------------------
create table if not exists public.lab_dis_gonderim (
    id            integer generated by default as identity primary key,
    gonderim_no   varchar(30)  not null,
    dis_lab_id    integer not null references public.lab_dis_lab(id),
    gonderim_zamani timestamp not null default now(),
    gonderen_id   integer,

    -- KURYE ve SOĞUK ZİNCİR: numune binadan çıktıktan sonra elimizde
    --   yalnız bu kayıt kalır.
    kurye_firma   varchar(120) not null default '',
    kurye_ad      varchar(120) not null default '',
    kurye_tel     varchar(30)  not null default '',
    -- 1 oda sıcaklığı · 2 soğuk (2-8 °C) · 3 dondurulmuş (-20) · 4 kuru buz (-70)
    tasima_kosulu smallint     not null default 2,
    sicaklik      numeric(9,2),
    kap_sayisi    smallint     not null default 1,

    teslim_zamani timestamp,
    teslim_alan   varchar(120) not null default '',
    -- Karşı tarafın kendi kabul numarası: sonuç geldiğinde eşleştirmede
    --   ve itirazda tek ortak referans budur.
    dis_kabul_no  varchar(40)  not null default '',

    -- 0 iptal · 1 hazırlanıyor · 2 yolda · 3 teslim edildi ·
    -- 4 kısmi sonuç · 5 sonuçlandı
    durum         smallint     not null default 1,
    -- ALIŞ FATURASI eşleşmesi: dış lab hizmeti satın alınan bir hizmettir;
    --   fatura ile gönderim eşleşmezse "kime ne ödedik" cevapsız kalır.
    fatura_belge_id integer references public.belge(id),
    tutar         numeric(19,4),
    aciklama      varchar(600) not null default '',
    sube_id       integer   not null default 0,
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

create unique index if not exists ux_lab_dis_gonderim_no
    on public.lab_dis_gonderim (upper(gonderim_no));
create index if not exists ix_lab_dis_gonderim_durum
    on public.lab_dis_gonderim (durum, gonderim_zamani desc);

create table if not exists public.lab_dis_gonderim_satir (
    id            integer generated by default as identity primary key,
    gonderim_id   integer not null references public.lab_dis_gonderim(id) on delete cascade,
    istem_satir_id integer not null references public.lab_istem_satir(id),
    numune_id     integer references public.lab_numune(id),
    tetkik_id     integer not null references public.lab_tetkik(id),
    dis_kod       varchar(40)  not null default '',
    birim_fiyat   numeric(19,4),
    -- 1 gönderildi · 2 sonuç geldi · 3 dış lab reddetti · 4 numune kayboldu
    durum         smallint not null default 1,
    sonuc_zamani  timestamp,
    ret_neden     varchar(300) not null default '',
    ekleyen       integer   not null default 0,
    ekleme_tarihi timestamp not null default now(),
    degistiren    integer   not null default 0,
    degistirme_tarihi timestamp
);

-- AYNI TETKİK İKİ KEZ GÖNDERİLMEZ: mükerrer gönderim hem ikinci kez
--   faturalanır hem iki farklı sonuç döner.
create unique index if not exists ux_lab_dis_gonderim_satir
    on public.lab_dis_gonderim_satir (istem_satir_id)
 where durum <> 3;

create index if not exists ix_lab_dis_gonderim_satir_gonderim
    on public.lab_dis_gonderim_satir (gonderim_id);

-- İstem satırı hangi gönderimde: liste ve rapor bunu okur.
alter table public.lab_istem_satir
    add column if not exists dis_gonderim_id integer
        references public.lab_dis_gonderim(id);

-- Sonucun dış laboratuvardan geldiği raporda YAZILIR (mockup: "Dış lab: —").
alter table public.lab_sonuc
    add column if not exists dis_lab_id integer references public.lab_dis_lab(id);

-- ---------------------------------------------------------------------
--  3) GÖNDERİM NUMARASI
-- ---------------------------------------------------------------------
create or replace function public.fn_lab_dis_gonderim_no()
returns text language sql as $$
    select 'DL-' || to_char(current_date, 'YYYY') || '/' ||
           public.fn_numara_sirada(
               'lab_dis_gonderim.gonderim_no|Y' || to_char(current_date, 'YYYY'),
               'lab_dis_gonderim', 'gonderim_no',
               'yil ' || to_char(current_date, 'YYYY'), 5, 1);
$$;

-- ---------------------------------------------------------------------
--  4) GECİKME GÖRÜNÜMÜ
--
--  Sözleşme TAT'ını aşan gönderim: dış laboratuvarı aramanın zamanı.
--  Kimse elle takip edemez - hastanın sonucu başka bir binada bekliyor.
-- ---------------------------------------------------------------------
drop view if exists public.v_lab_dis_geciken;
create view public.v_lab_dis_geciken as
select g.id, g.gonderim_no, g.dis_lab_id, d.ad as dis_lab, g.gonderim_zamani,
       d.sozlesme_tat_gun,
       (current_date - g.gonderim_zamani::date) - d.sozlesme_tat_gun as gecikme_gun,
       count(s.id) filter (where s.durum = 1) as bekleyen,
       count(s.id) as toplam,
       g.durum, g.sube_id
  from public.lab_dis_gonderim g
  join public.lab_dis_lab d on d.id = g.dis_lab_id
  left join public.lab_dis_gonderim_satir s on s.gonderim_id = g.id
 where g.durum between 1 and 4
 group by g.id, g.gonderim_no, g.dis_lab_id, d.ad, g.gonderim_zamani,
          d.sozlesme_tat_gun, g.durum, g.sube_id
having (current_date - g.gonderim_zamani::date) > d.sozlesme_tat_gun
   and count(s.id) filter (where s.durum = 1) > 0;

-- ---------------------------------------------------------------------
--  5) LOOKUP ve YETKİ
-- ---------------------------------------------------------------------
drop view if exists public.v_lab_dis_lab_lookup;
create view public.v_lab_dis_lab_lookup as
select d.id, d.kod, d.kod || ' · ' || d.ad as ad,
       case when d.durum = 0 then 1 else 0 end::smallint as aktif
  from public.lab_dis_lab d;

insert into public.yetki (kod, ad, grup, tur, sira)
select 'lab.dislab', 'Dış laboratuvar gönderimi', 'Laboratuvar',
       0::smallint, 461::smallint
 where not exists (select 1 from public.yetki y where y.kod = 'lab.dislab');

insert into public.rol_yetki (rol_id, yetki_id, gor, ekle, degistir, sil)
select r.id, y.id, 1, 1, 1, 1
  from public.rol r, public.yetki y
 where r.ad in ('Yönetici', 'Yonetici') and y.kod = 'lab.dislab'
   and not exists (select 1 from public.rol_yetki x
                    where x.rol_id = r.id and x.yetki_id = y.id);

update public.rol set yetki_surumu = yetki_surumu + 1;

do $$
begin
    raise notice '445 tamam: lab_dis_lab / lab_dis_test / lab_dis_gonderim(_satir)';
end $$;
