-- =====================================================================
-- 448 - AI REHBER: EKRANIN AKSIYON KATALOGU ADI
--
-- Rehber "bu ekranda ne yapabilirsiniz" derken aksiyonlari `<kaynak>-liste`
-- kalibiyla ariyordu. Kalip TUTMUYOR: Radyoloji Calisma Listesi'nin kaynagi
-- `radyoloji-istem`, aksiyon ekrani ise `radyoloji-liste` - o ekranda hicbir
-- dugme sayilamiyordu. Ad artik TAHMIN degil, istemcideki tanimdan gelir.
-- =====================================================================

alter table public.ai_rehber_ekran
    add column if not exists aksiyon_ekrani varchar(60) not null default '';

update public.ai_rehber_ekran e set aksiyon_ekrani = v.aksiyon
  from (values
    ('/randevu','randevu-liste'),
    ('/hasta','hasta-liste'),
    ('/basvuru','basvuru-liste'),
    ('/sigorta-provizyon','sigorta-provizyon-liste'),
    ('/sigorta-hesap','sigorta-hesap-liste'),
    ('/sigorta-kod-esleme','sigorta-kod-esleme-liste'),
    ('/sigorta-istek-log','sigorta-istek-log-liste'),
    ('/cihaz','cihaz-liste'),
    ('/cihaz-mesaj','cihaz-mesaj-liste'),
    ('/its-bildirim','its-liste'),
    ('/enabiz-paket','enabiz-liste'),
    ('/recete','cari-liste'),
    ('/hasta-tibbi-ozet','cikti-liste'),
    ('/hasta-kronik','cari-liste'),
    ('/hasta-gecmis','cari-liste'),
    ('/hasta-alerji','cari-liste'),
    ('/hasta-ilac','cari-liste'),
    ('/muayene-sablon','cari-liste'),
    ('/metin-makro','cari-liste'),
    ('/hekim-listesi','hekim-liste'),
    ('/muayene','muayene-liste'),
    ('/lab-istem','lab-istem-liste'),
    ('/lab-numune','lab-numune-liste'),
    ('/lab-sonuc','lab-sonuc-liste'),
    ('/lab-tetkik','lab-tetkik-liste'),
    ('/lab-panel','lab-panel-liste'),
    ('/lab-kultur','lab-kultur-liste'),
    ('/lab-genetik-vaka','lab-genetik-liste'),
    ('/lab-varyant','lab-varyant-liste'),
    ('/lab-genetik-run','lab-genetik-run-liste'),
    ('/lab-kk-olcum','lab-kk-liste'),
    ('/lab-dkk','lab-dkk-liste'),
    ('/lab-kk-lot','lab-kk-lot-liste'),
    ('/lab-dis-gonderim','lab-dis-gonderim-liste'),
    ('/lab-dis-lab','lab-dis-lab-liste'),
    ('/lab-indeks-esik','lab-indeks-esik-liste'),
    ('/lab-kk-kural','lab-kk-kural-liste'),
    ('/lab-cihaz-olay','lab-cihaz-olay-liste'),
    ('/lab-gen','lab-gen-liste'),
    ('/lab-genetik-panel','lab-genetik-panel-liste'),
    ('/lab-organizma','lab-organizma-liste'),
    ('/lab-antibiyotik','lab-antibiyotik-liste'),
    ('/lab-besiyeri','lab-besiyeri-liste'),
    ('/lab-cihaz-esleme','lab-cihaz-esleme-liste'),
    ('/radyoloji','radyoloji-liste'),
    ('/radyoloji-sablon','cari-liste'),
    ('/radyoloji-protokol','cari-liste'),
    ('/radyoloji-cihaz','cari-liste'),
    ('/radyoloji-kritik','radyoloji-kritik-liste'),
    ('/radyoloji-konsultasyon','radyoloji-konsultasyon-liste'),
    ('/radyoloji-teslim','radyoloji-teslim-liste'),
    ('/kurum-icmal','icmal-liste'),
    ('/cari','cari-liste'),
    ('/tedarikci','cari-liste'),
    ('/kurum','cari-liste'),
    ('/kisi','kisi-liste'),
    ('/dis-hekim','dis-hekim-liste'),
    ('/proje','proje-liste'),
    ('/gorev','gorev-liste'),
    ('/firsat','firsat-liste'),
    ('/aday','aday-liste'),
    ('/muhasebe-fis','fis-liste'),
    ('/kampanya','cari-liste'),
    ('/teklif','teklif-liste'),
    ('/siparis','siparis-liste'),
    ('/satis-irsaliye','irsaliye-liste'),
    ('/belge','belge-liste'),
    ('/gelen-belge','gelen-belge-liste'),
    ('/satis-fisi','belge-liste'),
    ('/tahakkuk','belge-liste'),
    ('/satis-konsinye','belge-liste'),
    ('/alis-siparis','siparis-liste'),
    ('/alis-irsaliye','irsaliye-liste'),
    ('/alis-fatura','belge-liste'),
    ('/alis-fisi','belge-liste'),
    ('/borc-tahakkuk','belge-liste'),
    ('/alis-konsinye','belge-liste'),
    ('/kasa-islem','kasa-liste'),
    ('/plan-vade','plan-liste'),
    ('/kasa-hesap','hesap-liste'),
    ('/banka-hesap','hesap-liste'),
    ('/kredi-hesap','hesap-liste'),
    ('/pos-hesap','hesap-liste'),
    ('/kredi-karti','hesap-liste'),
    ('/banka','banka-liste'),
    ('/cek','cek-senet-liste'),
    ('/senet','cek-senet-liste'),
    ('/stok','stok-liste'),
    ('/hizmet','hizmet-liste'),
    ('/fiyat-listesi','fiyat-listesi-liste'),
    ('/fiyat-listesi-satir','fiyat-listesi-satir-liste'),
    ('/uts-envanter','uts-envanter-liste'),
    ('/uts-bildirim','uts-bildirim-liste'),
    ('/stok-talep','belge-liste'),
    ('/stok-transfer','belge-liste'),
    ('/giris-fis','belge-liste'),
    ('/cikis-fis','belge-liste'),
    ('/urun-agaci','urun-agaci-liste'),
    ('/uretim-emri','uretim-emri-liste'),
    ('/is-merkezi','is-merkezi-liste'),
    ('/personel','personel-liste'),
    ('/prim-plani','cari-liste'),
    ('/hakedis-satir','hakedis-liste'),
    ('/hakedis','hakedis-donem'),
    ('/demirbas','demirbas-liste'),
    ('/dokuman','dokuman-liste'),
    ('/dokuman-onay','dokuman-onay-liste'),
    ('/dokuman-kategori','dokuman-kategori-liste'),
    ('/dokuman-klasor','dokuman-klasor-liste'),
    ('/onam','cikti-liste'),
    ('/bildirim','bildirim-liste'),
    ('/zamanli-is','zamanli-is-liste'),
    ('/icd','cikti-liste'),
    ('/ilac','ilac-liste'),
    ('/rol','rol-liste')
       ) as v(rota, aksiyon)
 where e.rota = v.rota and e.aksiyon_ekrani <> v.aksiyon;

do $$
begin
    raise notice '448 tamam: ai_rehber_ekran.aksiyon_ekrani % satir',
        (select count(*) from public.ai_rehber_ekran where aksiyon_ekrani <> '');
end $$;
