-- =====================================================================
--  656_menu_ceviri_ingilizce.sql
--  MENÜ ÇEVİRİSİ - eksik İngilizce karşılıklar (kullanıcı: "ingilizceye
--  çevirdim ama bir çok menü türkçe kaldı").
--
--  Çeviri sözlüğü SUNUCUDA (`ceviri` tablosu, `/api/ceviri/{dil}`) ve
--  anahtar TÜRKÇE METNİN KENDİSİDİR - karşılığı olmayan metin Türkçe
--  görünür. Menüde 217 ayrı metin var, sözlükte bunların yalnız 79'u
--  vardı; kalan 138'i burada eklenir.
--
--  DİL 1 = İngilizce (2 = Almanca; Almanca karşılıklar bu dosyada YOK,
--  eksik olan İngilizceydi - uydurma çeviri eklemek, yanlış çeviriyi
--  "var" gösterip bir daha kimsenin bakmamasına yol açardı).
--
--  ÇAKIŞMA: aynı anahtar zaten varsa DOKUNULMAZ - kurumun elle girdiği
--  çeviri geri alınmasın.
--
--  KAPSAM 'menu': `c(metin, 'menu')`. İstemci menü sözlüğünde bulamazsa
--  etiket sözlüğüne de bakıyor, yani etiket olarak da işe yarar.
-- =====================================================================

insert into public.ceviri (kapsam, anahtar, dil, metin)
select 'menu', v.tr, 1, v.en
  from (values
    ('Alerjiler', 'Allergies'),
    ('Alış Tahakkukları', 'Purchase Accruals'),
    ('Anlaşmalı Kurumlar', 'Contracted Institutions'),
    ('Antibiyotik Kataloğu', 'Antibiotic Catalogue'),
    ('Antibiyotikler', 'Antibiotics'),
    ('Açık Sipariş Satırları', 'Open Order Lines'),
    ('Başvurular', 'Admissions'),
    ('Besiyeri Kataloğu', 'Culture Media Catalogue'),
    ('Besiyerleri', 'Culture Media'),
    ('Bildirim Kuyruğu', 'Notification Queue'),
    ('Bildirim Şablonları', 'Notification Templates'),
    ('Bildirimler', 'Notifications'),
    ('Bölüm / Görev', 'Department / Role'),
    ('Cihaz Eşleme', 'Device Mapping'),
    ('Cihaz Mesajları', 'Device Messages'),
    ('Cihaz Olayları', 'Device Events'),
    ('Cihaz Test Eşleme', 'Device Test Mapping'),
    ('Cihazlar', 'Devices'),
    ('Demirbaş', 'Fixed Assets'),
    ('Dizileme Runları', 'Sequencing Runs'),
    ('Doküman', 'Documents'),
    ('Doküman Kategorileri', 'Document Categories'),
    ('Doküman Klasörleri', 'Document Folders'),
    ('Doküman Onay Kuyruğu', 'Document Approval Queue'),
    ('Dokümanlar', 'Documents'),
    ('Dış Doktorlar', 'External Physicians'),
    ('Dış Kalite', 'External QC'),
    ('Dış Kalite (DKK)', 'External QC (EQA)'),
    ('Dış Lab Gönderimleri', 'Referral Lab Shipments'),
    ('Dış Laboratuvarlar', 'Referral Laboratories'),
    ('Fiyat Listeleri', 'Price Lists'),
    ('Fiyat Listesi Satırları', 'Price List Lines'),
    ('Gelen / Askıdakiler', 'Inbox / Pending'),
    ('Gen Kataloğu', 'Gene Catalogue'),
    ('Genel Ayarlar', 'General Settings'),
    ('Genetik Panelleri', 'Genetic Panels'),
    ('Genetik Vakalar', 'Genetic Cases'),
    ('Genler', 'Genes'),
    ('Geçmiş Olaylar', 'Past Events'),
    ('Giriş Fişleri', 'Goods Receipts'),
    ('Gönderim Kuyruğu', 'Submission Queue'),
    ('Hakediş Satırları', 'Commission Lines'),
    ('Hakedişler', 'Commissions'),
    ('Hasta Alerjileri', 'Patient Allergies'),
    ('Hasta Ekstresi', 'Patient Statement'),
    ('Hekim Çalışma Listesi', 'Physician Worklist'),
    ('ICD-10 Tanı', 'ICD-10 Diagnosis'),
    ('ICD-10 Tanı Kataloğu', 'ICD-10 Diagnosis Catalogue'),
    ('Islem Gunlugu', 'Audit Log'),
    ('Kalite Kontrol', 'Quality Control'),
    ('Kalite Kontrol (İKK)', 'Quality Control (IQC)'),
    ('Kampanyalar', 'Campaigns'),
    ('Kasa Ayarları', 'Cash Settings'),
    ('Kasalar', 'Cash Accounts'),
    ('Kategoriler', 'Categories'),
    ('Kayıt Kabul Ayarları', 'Registration Settings'),
    ('Klasörler', 'Folders'),
    ('Klinik Kataloglar', 'Clinical Catalogues'),
    ('Kod Eşleme', 'Code Mapping'),
    ('Konsültasyonlar', 'Consultations'),
    ('Kontrol Lotları', 'Control Lots'),
    ('Kredi Kartları', 'Credit Cards'),
    ('Kritik Bulgular', 'Critical Results'),
    ('Kronik Tanılar', 'Chronic Diagnoses'),
    ('Kullanılan İlaçlar', 'Current Medications'),
    ('Kurum Ekstresi', 'Institution Statement'),
    ('Kurum Hesapları', 'Institution Accounts'),
    ('Kurum Profili', 'Institution Profile'),
    ('Kurum İcmalleri', 'Institution Summaries'),
    ('Kültür Çalışma Listesi', 'Culture Worklist'),
    ('Lab Panelleri', 'Lab Panels'),
    ('Laboratuvar İstemleri', 'Laboratory Orders'),
    ('Mesajlar', 'Messages'),
    ('Metin Makroları', 'Text Macros'),
    ('Muayene Şablonları', 'Encounter Templates'),
    ('Numune Kabul', 'Specimen Reception'),
    ('Onam Kayıtları', 'Consent Records'),
    ('Onam Metinleri', 'Consent Texts'),
    ('Onamlar', 'Consents'),
    ('Onay Kuyruğu', 'Approval Queue'),
    ('Organizma Kataloğu', 'Organism Catalogue'),
    ('Organizmalar', 'Organisms'),
    ('POS Hesapları', 'POS Accounts'),
    ('Panel Kataloğu', 'Panel Catalogue'),
    ('Paneller', 'Panels'),
    ('Pano', 'Dashboard'),
    ('Personel', 'Staff'),
    ('Prim Planları', 'Commission Plans'),
    ('Provizyonlar', 'Pre-Authorisations'),
    ('Radyoloji', 'Radiology'),
    ('Radyoloji Panosu', 'Radiology Dashboard'),
    ('Radyoloji Çalışma Listesi', 'Radiology Worklist'),
    ('Randevu', 'Appointment'),
    ('Randevu Ayarları', 'Appointment Settings'),
    ('Randevular', 'Appointments'),
    ('Rapor Şablonları', 'Report Templates'),
    ('Reçeteler', 'Prescriptions'),
    ('Satış Tahakkukları', 'Sales Accruals'),
    ('Satış Teklifleri', 'Sales Quotes'),
    ('Serum İndeksi', 'Serum Index'),
    ('Serum İndeksi Eşikleri', 'Serum Index Thresholds'),
    ('Sigorta Hesapları', 'Insurance Accounts'),
    ('Sigorta Kod Eşleme', 'Insurance Code Mapping'),
    ('Sigorta Provizyonları', 'Insurance Pre-Authorisations'),
    ('Sigorta İstek Günlüğü', 'Insurance Request Log'),
    ('Sonuç Onay Kuyruğu', 'Result Approval Queue'),
    ('Sonuç Teslim', 'Result Delivery'),
    ('Sonuçlar', 'Results'),
    ('Stok Transferleri', 'Stock Transfers'),
    ('Stoktan Talepler', 'Stock Requests'),
    ('Tetkik Kataloğu', 'Test Catalogue'),
    ('Tıbbi Özet', 'Medical Summary'),
    ('Vakalar', 'Cases'),
    ('Varyantlar', 'Variants'),
    ('Veri Kalitesi', 'Data Quality'),
    ('Westgard Kuralları', 'Westgard Rules'),
    ('Yapay Zeka', 'Artificial Intelligence'),
    ('Zamanlanmış İşler', 'Scheduled Jobs'),
    ('e-Belge Kuyrugu', 'e-Document Queue'),
    ('e-Nabız', 'e-Nabiz'),
    ('e-Nabız Kod Eşleme', 'e-Nabiz Code Mapping'),
    ('e-Nabız Kuyruğu', 'e-Nabiz Queue'),
    ('e-Nabız Veri Kalitesi', 'e-Nabiz Data Quality'),
    ('Çalışma Listesi', 'Worklist'),
    ('Çekim Protokolleri', 'Imaging Protocols'),
    ('Çıkış Fişleri', 'Goods Issues'),
    ('ÜTS Askıdaki Ürünler', 'UTS Pending Products'),
    ('ÜTS Bildirimleri', 'UTS Notifications'),
    ('ÜTS Ürün Sorgu', 'UTS Product Lookup'),
    ('Üretim', 'Production'),
    ('Üretim Emirleri', 'Production Orders'),
    ('Ürün Ağaçları', 'Bills of Materials'),
    ('Ürün Sorgu', 'Product Lookup'),
    ('İTS Bildirimleri', 'ITS Notifications'),
    ('İlaç Kataloğu', 'Drug Catalogue'),
    ('İletişim & AI', 'Messaging & AI'),
    ('İstek Günlüğü', 'Request Log'),
    ('İş Merkezleri', 'Work Centres')
       ) v(tr, en)
 where not exists (select 1 from public.ceviri c
                    where c.kapsam = 'menu' and c.anahtar = v.tr and c.dil = 1);

do $kontrol$
begin
    raise notice '656 tamam: menu cevirisi (dil 1) %, etiket %',
        (select count(*) from public.ceviri where dil = 1 and kapsam = 'menu'),
        (select count(*) from public.ceviri where dil = 1 and kapsam = 'etiket');
end $kontrol$;
