-- ============================================================================
--  Gentegre AI — DÖKÜMLER & İSTATİSTİK (686)
--  686_dokum.sql
--
--  Plan: dokuman/10_DOKUM_ISTATISTIK_PLANI.md · mockup Ekranlar/Ayarlar/
--  dokum_tasarimcisi.html. Koşul verilerek (tarih aralığı, kurum, doktor…)
--  tasarlanan, kaydedilip tekrar çalıştırılan döküm tanımı.
--
--  SQL BURADA YOK: tanım jsonb olarak durur, sorguyu liste motorunun kendisi
--  (SorguUretici) üretir - alanlar katalogdan, değerler parametreden. Bu yüzden
--  tabloda "sorgu" kolonu yoktur ve olmayacaktır.
--
--  SÜRÜM: her kayıt yeni sürüm yazar (dokum_surum). Zamanlı gönderim hangi
--  sürümle çalıştıysa ileride arşivde o yazacak (Aşama C).
--
--  GÖRÜNÜRLÜK: 0 bana özel · 1 rollere paylaşılan (roller[]) · 2 kurum geneli.
--  Paylaşım VERİ yetkisi vermez: dökümü gören kişi kaynağı kendi yetkisiyle
--  görür (kaynak yetkisi + şube + alan yetkisi sunucuda uygulanır).
-- ============================================================================
\set ON_ERROR_STOP on

create table if not exists public.dokum_tanimi (
    id            integer      generated by default as identity primary key,
    kod           varchar(60)  not null unique,
    ad            varchar(160) not null,
    aciklama      varchar(400) not null default '',
    kaynak        varchar(40)  not null,               -- KaynakKatalogu adı
    tanim         jsonb        not null,               -- DokumTanimi (§2)
    surum         integer      not null default 1,
    sahip_id      integer      not null references public.taraf_kullanici(id),
    gorunurluk    smallint     not null default 0,
    roller        integer[]    not null default '{}',
    aktif         smallint     not null default 1,
    sube_id       integer,
    son_calisma   timestamp,
    calisma_sayisi integer     not null default 0,
    ekleyen       integer      not null default 0,
    ekleme_tarihi timestamp    not null default now(),
    degistiren    integer      not null default 0,
    degistirme_tarihi timestamp not null default now()
);
create index if not exists ix_dokum_tanimi_kaynak on public.dokum_tanimi(kaynak, aktif);
create index if not exists ix_dokum_tanimi_sahip  on public.dokum_tanimi(sahip_id, aktif);

comment on table public.dokum_tanimi is
  'Kayitli dokum tanimi (686). SQL yok: tanim jsonb, sorguyu SorguUretici uretir.';
comment on column public.dokum_tanimi.gorunurluk is
  '0 bana ozel · 1 roller[] ile paylasilan · 2 kurum geneli. Veri yetkisi VERMEZ.';

create table if not exists public.dokum_surum (
    dokum_id     integer   not null references public.dokum_tanimi(id) on delete cascade,
    surum        integer   not null,
    tanim        jsonb     not null,
    kullanici_id integer   not null default 0,
    tarih        timestamp not null default now(),
    not_         varchar(200) not null default '',
    primary key (dokum_id, surum)
);

-- ----------------------------------------------------------------- yetki --
-- Ekran yetkisi `dokum`: Gor = çalıştır, Ekle/Degistir = tasarla-kaydet,
--   Sil = pasife al. Yönetim grubunda "Ayarlar"dan hemen sonra.
insert into public.yetki (kod, ad, grup, modul, tur, urun_modu, sira, aktif)
select 'dokum', 'Dökümler', 'Yönetim', '', 0, 0, 385, 1
 where not exists (select 1 from public.yetki where kod = 'dokum');

-- GEÇİŞ: ayar (Genel Ayarlar) yetkisi olan roller dökümü de görsün - bugün
--   yalnız Yönetici. Diğer roller matristen açılır.
insert into public.rol_yetki (rol_id, yetki_id, gor, ekle, degistir, sil, deger, ekleyen)
select ry.rol_id, (select id from public.yetki where kod = 'dokum'),
       1, ry.ekle, ry.degistir, ry.sil, '', 0
  from public.rol_yetki ry
  join public.yetki y on y.id = ry.yetki_id and y.kod = 'ayar'
 where ry.gor = 1
   and not exists (select 1 from public.rol_yetki v
                    where v.rol_id = ry.rol_id
                      and v.yetki_id = (select id from public.yetki where kod = 'dokum'));

do $$
begin
    raise notice '686 tamam: dokum_tanimi + dokum_surum; dokum yetkisi % role verildi.',
                 (select count(*) from public.rol_yetki ry
                   join public.yetki y on y.id = ry.yetki_id where y.kod = 'dokum');
end $$;
