-- =====================================================================
--  722_eczane.sql
--  HASTANE ECZANESİ — eczacı kontrolü, ünite doz, hazırlama, iade/imha,
--  kontrollü ilaç defteri.
--
--  Mockup'lar: `Ekranlar/Eczane/*.html`.
--
--  TEMEL KARAR — ORDER TABLOSU AÇILMADI. Yatan hasta orderı `yatis_order`,
--    uygulamaları `order_uygulama` (695). Eczane bunları OKUR; kendi order
--    kopyasını açsaydı hastanın ilaç geçmişi ikiye bölünür, "bu hastaya ne
--    verildi" sorusu iki yerden toplanmak zorunda kalırdı. Bu dosya eczanenin
--    KENDİ kavramlarını ekliyor: eczacı kontrolü, ünite doz hazırlığı,
--    hazırlama (aseptik), iade, imha, kontrollü ilaç defteri.
--
--  TEMEL KARAR — STOK TABLOSU DA AÇILMADI. Miad, lot, depo ve bakiye
--    `stok_durum` / `stok_lot_durum` / `stok_seri_lot`'ta duruyor; eczane
--    deposu bir `depo` kaydıdır. Eczaneye ayrı stok yazsaydık FEFO iki yerde
--    hesaplanır ve ikisi zamanla ayrışırdı.
--
--  TEMEL KARAR — ECZACI KONTROLÜ DOZDAN ÖNCE, AYRI SATIR. Order satırına
--    "eczacı onayladı" bayrağı koymak yetmezdi: bir order satırı için BİRDEN
--    ÇOK uyarı çıkabilir (alerji + etkileşim + böbrek dozu) ve her birinin
--    kendi kararı, gerekçesi ve hekim bildirimi olur. Önlenen ilaç hatası
--    kalite göstergesidir - tek bayrakla sayılamaz.
--
--  TEMEL KARAR — HAZIRLANMIŞ DOZ STOĞA DÖNMEZ. İade kaydı "kabul" derse
--    stoğa girer, "ret" derse imhaya gider; kararı sistem değil eczacı verir
--    ama SEBEBİ kayda geçer (açıldı / sulandırıldı / soğuk zincir bozuldu).
-- =====================================================================

-- ==================================================== eczacı kontrolü ==
-- Bir order satırına birden çok uyarı düşebilir; her biri ayrı satır.
create table if not exists public.eczane_kontrol (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  order_id      integer not null references public.yatis_order(id) on delete cascade,
  -- 1 alerji · 2 etkileşim · 3 doz (böbrek/karaciğer/yaş) · 4 tekrar/mükerrer
  -- 5 yüksek riskli ilaç · 6 uygulama yolu · 7 antibiyotik kısıtlama
  -- 8 sözel order · 9 kontrollü ilaç · 99 diğer
  tur           smallint not null default 99,
  -- 1 bilgi · 2 uyarı · 3 yüksek (geçilemez)
  duzey         smallint not null default 2,
  bulgu         varchar(400) not null default '',
  -- Uyarının DAYANAĞI: hangi kayıt tetikledi (alerji kaydı, KrKl değeri...).
  kaynak        varchar(200) not null default '',
  -- 0 bekliyor · 1 uygun (onaylandı) · 2 öneri yapıldı · 3 durduruldu
  karar         smallint not null default 0,
  oneri         varchar(400) not null default '',
  eczaci_id     integer references public.taraf(id),
  karar_zamani  timestamptz,
  -- HEKİME BİLDİRİM izlenir: eczacı önerisi hekimi bağlamaz, karar hekimin -
  --   ama önerinin iletildiği ve okunduğu kayda geçmeli.
  hekim_id      integer references public.taraf(id),
  bildirim_zamani timestamptz,
  okundu_zamani timestamptz,
  hekim_yaniti  varchar(400) not null default '',
  -- ÖNLENEN HATA (SKS göstergesi): karar 3 ise ve hasta etkilenmediyse 1.
  onlenen_hata  smallint not null default 0,
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create index if not exists ix_eczane_kontrol_order on public.eczane_kontrol (order_id);
create index if not exists ix_eczane_kontrol_bekleyen
  on public.eczane_kontrol (sube_id, ekleme_tarihi) where karar = 0;

comment on table public.eczane_kontrol is
  'Eczaci kontrolu (722): order satirina dusen uyarilar ve kararlari. Bir satira '
  'birden cok uyari dusebilir - her biri ayri kayit.';

-- ======================================================== ünite doz ==
-- Hazırlanan doz, `order_uygulama` satırına bağlanır: plan orada, hazırlık
--   burada. Ayrı tablo, çünkü bir uygulama HAZIRLANMADAN da geçilebilir
--   (servis stoğundan) ve hazırlanmış doz İADE edilebilir.
create table if not exists public.eczane_doz (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  uygulama_id   integer not null references public.order_uygulama(id) on delete cascade,
  -- DOZ BARKODU: hasta bilekliğiyle eşleşen kimlik. Boş olabilir (numara
  --   şablonu tanımsızsa) ama varsa benzersizdir.
  doz_barkod    varchar(40) not null default '',
  stok_id       integer references public.stok(id),
  seri_lot_id   integer references public.stok_seri_lot(id),
  miktar        numeric(12,3) not null default 0,
  -- 0 bekliyor · 1 hazırlandı · 2 kontrol edildi · 3 teslim edildi
  -- 4 uygulandı · 8 iade · 9 imha
  durum         smallint not null default 0,
  hazirlayan_id integer references public.taraf(id),
  hazirlama_zamani timestamptz,
  -- ÇİFT KONTROL yüksek riskli ilaçta zorunlu; kimin kontrol ettiği ayrı alan.
  kontrol_eden_id integer references public.taraf(id),
  kontrol_zamani  timestamptz,
  teslim_zamani timestamptz,
  teslim_alan_id integer references public.taraf(id),
  aciklama      varchar(300) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create index if not exists ix_eczane_doz_uygulama on public.eczane_doz (uygulama_id);
create unique index if not exists ux_eczane_doz_barkod
  on public.eczane_doz (doz_barkod) where doz_barkod <> '';
create index if not exists ix_eczane_doz_bekleyen
  on public.eczane_doz (sube_id, durum) where durum in (0, 1, 2);

comment on table public.eczane_doz is
  'Unite doz hazirligi (722). Tek hasta, tek saat; lot/SKT dozla birlikte '
  'kaydedilir - geri cagirmada aranan budur.';

-- ============================================== aseptik hazırlama ==
-- Kemoterapi / TPN / sürekli infüzyon. Ayrı tablo çünkü ünite dozdan farklı:
--   protokole ve hastanın VYA/AUC değerine göre DOZ HESAPLANIR, iki eczacı
--   bağımsız doğrular, kabin koşulları kaydedilir ve ürünün ömrü saatlerledir.
create table if not exists public.eczane_hazirlama (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  hazirlama_no  varchar(30) not null default '',
  -- 1 kemoterapi · 2 TPN · 3 sürekli infüzyon · 9 diğer
  tur           smallint not null default 1,
  hasta_id      integer not null references public.taraf(id),
  yatis_id      integer references public.yatis(id),
  belge_id      integer references public.belge(id),
  protokol      varchar(200) not null default '',
  kur_no        smallint not null default 0,
  kur_toplam    smallint not null default 0,
  -- DOZ HESABININ GİRDİLERİ kayda geçer: aynı hastanın boyu/kilosu kürler
  --   arasında değişir, doz onunla değişir. Sonradan "bu doz nasıl çıktı"
  --   sorusu ancak girdilerle yanıtlanır.
  boy_cm        numeric(5,1),
  kilo_kg       numeric(6,2),
  vya_m2        numeric(5,3),
  krkl          numeric(6,2),
  planlanan     timestamptz,
  -- 0 sırada · 1 ön koşul bekliyor · 2 doz onayı bekliyor · 3 hazırlanıyor
  -- 4 hazır · 5 teslim edildi · 8 iptal
  durum         smallint not null default 0,
  iptal_neden   varchar(200) not null default '',
  -- HASTA GELMEDEN HAZIRLANMAZ: hazırlanıp iptal edilen ürün çöpe gider.
  hasta_geldi_zamani timestamptz,
  hazirlayan_id integer references public.taraf(id),
  hazirlama_zamani timestamptz,
  -- İKİNCİ ECZACI doğrulaması (çift kontrol) - kemoterapide yanlış doz geri alınamaz.
  dogrulayan_id integer references public.taraf(id),
  dogrulama_zamani timestamptz,
  kabin_kod     varchar(30) not null default '',
  -- SON KULLANIM HAZIRLAMA ANINDAN sayılır, ilacın kutu miadından değil.
  son_kullanim  timestamptz,
  saklama       varchar(80) not null default '',
  teslim_zamani timestamptz,
  teslim_alan_id integer references public.taraf(id),
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create index if not exists ix_eczane_hazirlama_gun
  on public.eczane_hazirlama (sube_id, planlanan);
create index if not exists ix_eczane_hazirlama_hasta on public.eczane_hazirlama (hasta_id);

comment on table public.eczane_hazirlama is
  'Aseptik hazirlama (722): kemoterapi / TPN / infuzyon. Doz VYA-AUC ile '
  'hesaplanir, ikinci eczaci dogrular, son kullanim hazirlama anindan sayilir.';

create table if not exists public.eczane_hazirlama_kalem (
  id            bigint generated by default as identity primary key,
  hazirlama_id  bigint not null references public.eczane_hazirlama(id) on delete cascade,
  sira          smallint not null default 0,
  -- 1 ana ilaç · 2 premedikasyon · 3 sulandırıcı · 4 elektrolit/katkı
  tur           smallint not null default 1,
  stok_id       integer references public.stok(id),
  ilac_id       integer references public.ilac(id),
  ad            varchar(200) not null default '',
  -- PROTOKOL DOZU ile HESAPLANAN ve YUVARLANAN ayrı tutulur: yuvarlama
  --   flakon büyüklüğüne göre yapılır ve denetimde "neden 870 değil de 875"
  --   sorusu buradan yanıtlanır.
  protokol_doz  varchar(40) not null default '',
  hesaplanan    numeric(12,3),
  uygulanan_doz numeric(12,3),
  birim         varchar(20) not null default '',
  sulandirici   varchar(80) not null default '',
  son_hacim_ml  numeric(10,2),
  sure_dk       smallint not null default 0,
  seri_lot_id   integer references public.stok_seri_lot(id),
  -- Kümülatif doz izlenen ilaçlar (antrasiklin) için o ana kadarki toplam.
  kumulatif     numeric(12,3),
  kumulatif_sinir numeric(12,3),
  aciklama      varchar(300) not null default ''
);
create index if not exists ix_eczane_hazirlama_kalem
  on public.eczane_hazirlama_kalem (hazirlama_id, sira);

-- ====================================================== servis iadesi ==
-- ÜÇ SORU karara bağlar: ambalaj açıldı mı, sulandırıldı mı, saklama koşulu
--   korundu mu. Üçü de "hayır" ise stoğa döner. Kararı eczacı verir ama
--   sebebi kayda geçer - "neden imha edildi" sonradan sorulur.
create table if not exists public.eczane_iade (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  -- Kaynak: hangi birimden geldi (departman) ve varsa hangi doz kaydı.
  departman_id  integer references public.departman(id),
  doz_id        bigint references public.eczane_doz(id),
  stok_id       integer references public.stok(id),
  seri_lot_id   integer references public.stok_seri_lot(id),
  ad            varchar(200) not null default '',
  miktar        numeric(12,3) not null default 0,
  iade_neden    varchar(300) not null default '',
  -- Karar ölçütleri (mockup'taki üç soru).
  ambalaj_acik  smallint not null default 0,
  sulandirildi  smallint not null default 0,
  soguk_zincir_bozuk smallint not null default 0,
  -- 0 bekliyor · 1 stoğa kabul · 2 imhaya · 3 kasaya (kontrollü ilaç)
  karar         smallint not null default 0,
  karar_veren_id integer references public.taraf(id),
  karar_zamani  timestamptz,
  -- Stoğa dönen iade GİRİŞ FİŞİ üretir; bağ burada durur.
  belge_id      integer references public.belge(id),
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create index if not exists ix_eczane_iade_bekleyen
  on public.eczane_iade (sube_id, ekleme_tarihi) where karar = 0;

-- ============================================================= imha ==
-- İMHA STOK DÜŞÜMÜ DEĞİLDİR: kalem stoktan çıkış fişiyle düşer, imha ayrıca
--   tutanakla kapanır. İkisi ayrı kayıt, çünkü imha komisyon işidir ve
--   karekodlu kalemde İTS bildirimi gerektirir.
create table if not exists public.eczane_imha (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  tutanak_no    varchar(30) not null default '',
  tarih         date not null default current_date,
  -- Stok çıkışını yapan fiş (tür 4). NULL = henüz düşülmedi.
  belge_id      integer references public.belge(id),
  -- 0 açık · 1 komisyon onayladı · 2 imha edildi · 3 İTS bildirildi
  durum         smallint not null default 0,
  komisyon      varchar(300) not null default '',
  atik_teslim_no varchar(60) not null default '',
  aciklama      varchar(400) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create unique index if not exists ux_eczane_imha_no
  on public.eczane_imha (sube_id, tutanak_no) where tutanak_no <> '';

create table if not exists public.eczane_imha_satir (
  id            bigint generated by default as identity primary key,
  imha_id       bigint not null references public.eczane_imha(id) on delete cascade,
  stok_id       integer references public.stok(id),
  seri_lot_id   integer references public.stok_seri_lot(id),
  ad            varchar(200) not null default '',
  miktar        numeric(12,3) not null default 0,
  tutar         numeric(18,2) not null default 0,
  -- 1 miadı geçti · 2 hasar/kırık · 3 soğuk zincir · 4 hazırlanmış kullanılmadı
  -- 5 geri çağırma · 9 diğer
  neden         smallint not null default 1,
  -- 1 tıbbi atık · 2 sitotoksik atık · 3 tehlikeli atık
  atik_sinifi   smallint not null default 1,
  iade_id       bigint references public.eczane_iade(id),
  aciklama      varchar(300) not null default ''
);
create index if not exists ix_eczane_imha_satir on public.eczane_imha_satir (imha_id);

-- ============================================= kontrollü ilaç defteri ==
-- KASA STOKTAN AYRIDIR ama ayrı bir stok tablosu açmıyoruz: kasa bir `depo`
--   kaydıdır, hareketler yine belge/stok hattından geçer. Buradaki tablo
--   DEFTERDİR: numaralı, çift imzalı, silinmeyen kayıt. Mevzuat defteri
--   istiyor; stok hareketi defterin yerine geçmez.
create table if not exists public.kontrollu_defter (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  defter_no     varchar(30) not null,
  zaman         timestamptz not null default now(),
  -- 1 giriş (mal kabul) · 2 çıkış (reçete/order) · 3 iade · 4 artık imha
  -- 5 devir · 6 sayım
  hareket       smallint not null default 2,
  stok_id       integer references public.stok(id),
  seri_lot_id   integer references public.stok_seri_lot(id),
  ad            varchar(200) not null default '',
  miktar        numeric(12,3) not null default 0,
  -- 1 kırmızı reçete (narkotik) · 2 yeşil reçete (psikotrop)
  recete_renk   smallint not null default 1,
  recete_no     varchar(40) not null default '',
  hasta_id      integer references public.taraf(id),
  departman_id  integer references public.departman(id),
  -- ÇİFT İMZA: teslim eden ve alan ayrı kişilerdir. Artık imhasında ayrıca
  --   TANIK istenir - yarım ampul "kayboldu" olamaz.
  teslim_eden_id integer references public.taraf(id),
  teslim_alan_id integer references public.taraf(id),
  tanik_id      integer references public.taraf(id),
  belge_id      integer references public.belge(id),
  aciklama      varchar(300) not null default '',
  -- DÜZELTME SATIRI: yanlış kayıt SİLİNMEZ, düzeltme satırıyla kapatılır.
  duzeltilen_id bigint references public.kontrollu_defter(id),
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create unique index if not exists ux_kontrollu_defter_no
  on public.kontrollu_defter (sube_id, defter_no);
create index if not exists ix_kontrollu_defter_stok
  on public.kontrollu_defter (stok_id, zaman);

comment on table public.kontrollu_defter is
  'Kontrollu ilac defteri (722): numarali, cift imzali, SILINMEZ. Yanlis kayit '
  'duzeltme satiriyla kapatilir (duzeltilen_id).';

-- Defter satırı silinemez - mevzuat defteridir.
create or replace function public.fn_kontrollu_defter_silinmez()
returns trigger language plpgsql as $tg$
begin
    raise exception 'Kontrollü ilaç defteri satırı silinemez; düzeltme satırı ekleyin.'
          using errcode = 'restrict_violation';
end;
$tg$;

drop trigger if exists tg_kontrollu_defter_silinmez on public.kontrollu_defter;
create trigger tg_kontrollu_defter_silinmez
  before delete on public.kontrollu_defter
  for each row execute function public.fn_kontrollu_defter_silinmez();

-- ====================================================== günlük sayım ==
create table if not exists public.kontrollu_sayim (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  tarih         date not null default current_date,
  sayan1_id     integer references public.taraf(id),
  sayan2_id     integer references public.taraf(id),
  -- 0 açık · 1 uyumlu kapandı · 2 farklı (tutanak açıldı)
  durum         smallint not null default 0,
  aciklama      varchar(400) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create unique index if not exists ux_kontrollu_sayim_gun
  on public.kontrollu_sayim (sube_id, tarih);

create table if not exists public.kontrollu_sayim_satir (
  id          bigint generated by default as identity primary key,
  sayim_id    bigint not null references public.kontrollu_sayim(id) on delete cascade,
  stok_id     integer references public.stok(id),
  ad          varchar(200) not null default '',
  defter      numeric(12,3) not null default 0,
  sayan1      numeric(12,3),
  sayan2      numeric(12,3),
  -- Hesaplanan: iki sayım ve defter uyuşuyor mu. Fark DÜZELTİLMEZ, tutanak açılır.
  uyumlu      smallint,
  aciklama    varchar(200) not null default ''
);
create index if not exists ix_kontrollu_sayim_satir on public.kontrollu_sayim_satir (sayim_id);

-- İKİ SAYIM BİRBİRİNİ GÖRMEDEN yapılır; uyumu tetik hesaplar - ekranda ve
--   sunucuda iki kez hesaplanırsa "tamam" diyen ekranla "fark var" diyen
--   kayıt yan yana gelir.
create or replace function public.fn_kontrollu_sayim_uyum()
returns trigger language plpgsql as $tg$
begin
    if new.sayan1 is null or new.sayan2 is null then
        new.uyumlu := null;
    else
        new.uyumlu := case when new.sayan1 = new.sayan2 and new.sayan1 = new.defter
                           then 1 else 0 end;
    end if;
    return new;
end;
$tg$;

drop trigger if exists tg_kontrollu_sayim_uyum on public.kontrollu_sayim_satir;
create trigger tg_kontrollu_sayim_uyum
  before insert or update of defter, sayan1, sayan2 on public.kontrollu_sayim_satir
  for each row execute function public.fn_kontrollu_sayim_uyum();

-- =========================================================== görünüm ==
-- MİAD + TÜKETİM TEK YERDE. Öneri yalnız tarihe değil tüketim hızına bakar:
--   günlük 6 giden kalem 14 gün kala iade edilmez, tüketilir. İki ekran
--   (eczane panosu, stok & miad) aynı hesabı okusun.
create or replace view public.v_eczane_miad as
select sd.stok_id, sd.depo_id, sl.id as seri_lot_id,
       s.ad, s.kod, sl.lot_no, sl.son_kullanma_tarihi as skt,
       (sl.son_kullanma_tarihi::date - current_date) as kalan_gun,
       ld.kalan as miktar,
       -- Son 90 günün günlük ortalama çıkışı. AYRI BİR HAREKET TABLOSU YOK:
       --   stok hareketi belge satırıdır (`belge_satir`), çıkış yönü belgenin
       --   türünden gelir. İkinci bir hareket defteri tutsaydık belge ile
       --   arasındaki fark ilk düzeltmede ortaya çıkardı.
       coalesce((select round(sum(bs.miktar) / 90.0, 2)
                   from public.belge_satir bs
                   join public.belge b on b.id = bs.belge_id
                  where bs.stok_id = ld.stok_id
                    and coalesce(bs.cikis_depo_id, b.cikis_depo_id) = ld.depo_id
                    and b.durum <> 0                    -- taslak sayılmaz
                    and b.belge_tarihi >= current_date - 90), 0) as gunluk_tuketim
  from public.stok_lot_durum ld
  join public.stok_durum sd on sd.stok_id = ld.stok_id and sd.depo_id = ld.depo_id
  join public.stok_seri_lot sl on sl.id = ld.seri_lot_id
  join public.stok s on s.id = ld.stok_id
 where ld.kalan > 0 and sl.son_kullanma_tarihi is not null;

comment on view public.v_eczane_miad is
  '722: miad + tuketim hizi TEK kaynak. Oneri yalniz tarihe degil tuketime bakar.';

-- =============================================================== yetki ==
insert into public.yetki (kod, ad, grup, tur, sira, aktif)
select 'eczane', 'Hastane Eczanesi', 'Eczane', 0, 46, 1
 where not exists (select 1 from public.yetki where kod = 'eczane');

insert into public.yetki (kod, ad, grup, tur, sira, aktif)
select v.kod, v.ad, 'Eczane', v.tur, v.sira, 1 from (values
    ('eczane.order',      'Order karşılama',                 0::smallint, 1::smallint),
    ('eczane.doz',        'Ünite doz hazırlama',             0, 2),
    ('eczane.hazirlama',  'Aseptik hazırlama',               0, 3),
    ('eczane.iade',       'İade kabul',                      0, 4),
    ('eczane.imha',       'İmha tutanağı',                   0, 5),
    ('eczane.kontrollu',  'Kontrollü ilaç kasası',           0, 6),
    -- AKSIYON YETKILERI (tur = 1): geri alinamaz ya da sorumluluk isteyen isler.
    ('eczane.onay',       'Eczacı onayı ver',                1, 7),
    ('eczane.imha_onay',  'İmhayı onayla',                   1, 8),
    ('eczane.kontrollu_teslim', 'Kontrollü ilaç teslim et',  1, 9)
  ) as v(kod, ad, tur, sira)
 where not exists (select 1 from public.yetki y where y.kod = v.kod);

insert into public.rol_yetki (rol_id, yetki_id, gor, ekle, degistir, sil, ekleyen)
select r.id, y.id, 1, 1, 1, 1, 0
  from public.rol r cross join public.yetki y
 where r.kod = 'yonetici'
   and (y.kod = 'eczane' or y.kod like 'eczane.%')
   and not exists (select 1 from public.rol_yetki ry
                    where ry.rol_id = r.id and ry.yetki_id = y.id);
