-- =====================================================================
--  724_satinalma.sql
--  SATINALMA — talep ve onay zinciri, teklif/değerlendirme, sipariş takibi,
--  üçlü eşleştirme, tedarikçi sözleşme ve performansı, bütçe.
--
--  Mockup'lar: `Ekranlar/Satinalma/*.html`.
--
--  TEMEL KARAR — SİPARİŞ VE FATURA TABLOSU AÇILMADI. Alış siparişi `belge`
--    tür 9, irsaliye 10, fatura 11'dir; satırlar `belge_satir`, tutarlar
--    `fn_belge_diptoplam`. İkinci bir sipariş tablosu açsaydık para iki yerde
--    hesaplanır ve ikisi zamanla ayrışırdı (CLAUDE.md: "para matematiği tek
--    yerde"). Bu dosya siparişin ÜSTÜNE süreç katmanı koyuyor: teslim
--    taahhüdü, gecikme, ceza, sözleşme bağı.
--
--  TEMEL KARAR — TALEP `belge` DEĞİL. Tür 105 (Stoktan Talep) servis → eczane
--    gibi İÇ taleptir, karşılığı transferdir. Satınalma talebi dışarı çıkar,
--    bütçe ve onay zinciri taşır, henüz bir belge değildir. Aynı türe
--    sıkıştırsaydık iki farklı iş akışı tek listede karışırdı.
--
--  TEMEL KARAR — ONAY ZİNCİRİ SATIR SATIR. Talebe "onaylandı" bayrağı koymak
--    yetmezdi: kim, ne zaman, hangi basamakta, hangi gerekçeyle onayladı -
--    denetimde sorulan budur. Basamakları sistem kurar (tutar + bütçe durumu
--    + malzeme türü), kullanıcı "kime göndereyim" diye sormaz.
--
--  TEMEL KARAR — TEDARİKÇİ SKORU HESAPLANIR, GİRİLMEZ. Her gecikme, kalite
--    uygunsuzluğu ve fatura farkı olay olarak yazılır; skor onlardan türer.
--    Elle girilen skor, dönem sonunda kimin hatırladığına bağlı kalırdı.
-- =====================================================================

-- ============================================================= bütçe ==
-- TAAHHÜT DE HARCAMADIR: açık sipariş henüz faturalanmadı ama parası
--   bağlandı. Kalan bütçe onu düşerek gösterilir - yoksa aynı para iki kez
--   harcanır.
create table if not exists public.butce_kalem (
  id            integer generated by default as identity primary key,
  sube_id       integer not null default 0,
  yil           smallint not null,
  kod           varchar(30) not null,
  ad            varchar(150) not null,
  -- Talep bu kaleme hangi ölçüte göre düşer: malzeme grubu ya da elle seçim.
  grup_kodu     varchar(40) not null default '',
  tutar         numeric(18,2) not null default 0,
  -- Aşım davranışı: 0 uyar · 1 ek onay ister · 2 engeller
  asim_davranis smallint not null default 1,
  aktif         smallint not null default 1,
  aciklama      varchar(300) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create unique index if not exists ux_butce_kalem
  on public.butce_kalem (sube_id, yil, kod);

-- ============================================================= talep ==
create table if not exists public.satinalma_talep (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  talep_no      varchar(30) not null default '',
  tarih         date not null default current_date,
  -- 1 birim talebi · 2 kritik stok (otomatik) · 3 arıza · 4 periyodik
  -- 5 yatırım · 9 diğer
  kaynak        smallint not null default 1,
  -- Otomatik doğan talebin kaynağı izlenir: hangi sarf/iş emri tetikledi.
  kaynak_tur    smallint not null default 0,
  kaynak_id     bigint,
  isteyen_id    integer references public.taraf(id),
  departman_id  integer references public.departman(id),
  butce_kalem_id integer references public.butce_kalem(id),
  -- 1 acil · 2 yüksek · 3 normal
  oncelik       smallint not null default 3,
  gerekce       varchar(600) not null default '',
  -- MİKTAR HESABI KAYDA GEÇER: tüketim + eldeki + açık sipariş. Onaylayan
  --   neye onay verdiğini görmeli - "gözden" gelen miktar denetlenemez.
  hesap_notu    varchar(400) not null default '',
  tahmini_tutar numeric(18,2) not null default 0,
  -- 0 taslak · 1 onayda · 2 onaylandı · 3 reddedildi · 4 teklifte
  -- 5 siparişe dönüştü · 8 iptal
  durum         smallint not null default 0,
  -- Birleştirme: aynı malzemenin açık talepleri tek siparişte toplanır.
  birlestirilen_id bigint references public.satinalma_talep(id),
  red_neden     varchar(300) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create unique index if not exists ux_satinalma_talep_no
  on public.satinalma_talep (sube_id, talep_no) where talep_no <> '';
create index if not exists ix_satinalma_talep_acik
  on public.satinalma_talep (sube_id, oncelik, tarih) where durum between 0 and 4;

comment on table public.satinalma_talep is
  '724: satinalma talebi - `belge` DEGIL. Tur 105 ic talep (transferle karsilanir); '
  'bu talep disari cikar, butce ve onay zinciri tasir.';

create table if not exists public.satinalma_talep_satir (
  id            bigint generated by default as identity primary key,
  talep_id      bigint not null references public.satinalma_talep(id) on delete cascade,
  sira          smallint not null default 0,
  stok_id       integer references public.stok(id),
  ilac_id       integer references public.ilac(id),
  hizmet_id     integer references public.hizmet(id),
  ad            varchar(200) not null,
  miktar        numeric(14,3) not null default 0,
  birim         varchar(20) not null default '',
  -- Son alış fiyatı TAHMİN içindir; gerçek fiyat teklif ya da sözleşmeden gelir.
  son_alis_fiyat numeric(18,4) not null default 0,
  tahmini_tutar numeric(18,2) not null default 0,
  -- TEKNİK ŞARTNAME talepte yazılır ki mal kabulde REDDETME HAKKI doğsun
  --   (asgari raf ömrü, soğuk zincir, ÜTS kaydı...).
  sartname      varchar(800) not null default '',
  -- Siparişe dönüşen satır belge satırına bağlanır: "bu talep ne oldu".
  belge_satir_id bigint references public.belge_satir(id),
  aciklama      varchar(300) not null default ''
);
create index if not exists ix_satinalma_talep_satir on public.satinalma_talep_satir (talep_id, sira);
create index if not exists ix_satinalma_talep_satir_acik
  on public.satinalma_talep_satir (stok_id) where belge_satir_id is null;

-- ONAY ZİNCİRİ SATIR SATIR (bkz başlık).
create table if not exists public.satinalma_onay (
  id            bigint generated by default as identity primary key,
  talep_id      bigint not null references public.satinalma_talep(id) on delete cascade,
  basamak       smallint not null default 1,
  -- 1 birim sorumlusu · 2 satınalma · 3 başhekim/müdür · 4 mali işler
  -- 5 yönetim kurulu
  rol           smallint not null default 1,
  onaylayan_id  integer references public.taraf(id),
  -- 0 bekliyor · 1 onaylandı · 2 reddedildi · 3 bilgi istendi
  -- 4 sözlü onay (24 saat içinde yazılı tamamlanacak)
  durum         smallint not null default 0,
  karar_zamani  timestamptz,
  gerekce       varchar(400) not null default '',
  -- Sözlü onayın yazılı tamamlanma süresi: geçerse uyarıya düşer.
  yazili_son    timestamptz,
  ekleme_tarihi timestamptz not null default now()
);
create unique index if not exists ux_satinalma_onay
  on public.satinalma_onay (talep_id, basamak);
create index if not exists ix_satinalma_onay_bekleyen
  on public.satinalma_onay (rol, ekleme_tarihi) where durum in (0, 4);

-- ============================================================ teklif ==
-- ALIŞ TEKLİFİ `belge` DEĞİL: tür 18 satış teklifidir (giden). Burada gelen
--   teklifler karşılaştırılıyor ve çoğu siparişe dönüşmüyor - belge açmak
--   her teklif için numara tüketmek olurdu.
create table if not exists public.satinalma_teklif (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  teklif_no     varchar(30) not null default '',
  talep_id      bigint references public.satinalma_talep(id),
  konu          varchar(200) not null default '',
  -- 1 doğrudan temin · 2 teklif toplama · 3 açık ihale · 4 pazarlık
  usul          smallint not null default 2,
  davet_tarihi  date,
  -- TEKLİFLER SON TARİHE KADAR AÇILMAZ ve hepsi birlikte açılır: erken
  --   açılan teklif, sonrakine söylenebilecek bir bilgidir.
  son_tarih     timestamptz,
  acilma_zamani timestamptz,
  tahmini_bedel numeric(18,2) not null default 0,
  -- DEĞERLENDİRME AĞIRLIKLARI TEKLİF DAVETİNDEN ÖNCE SABİTLENİR. Sonradan
  --   değiştirmek, kararı seçip gerekçeyi sonradan yazmaktır.
  agirlik_fiyat     smallint not null default 50,
  agirlik_teslim    smallint not null default 20,
  agirlik_garanti   smallint not null default 15,
  agirlik_performans smallint not null default 15,
  agirlik_kilit     smallint not null default 0,   -- 1 = davet gitti, değişmez
  -- 0 hazırlık · 1 davet gönderildi · 2 teklifler açıldı · 3 karar verildi
  -- 8 iptal
  durum         smallint not null default 0,
  karar_firma_id integer references public.taraf(id),
  karar_gerekce varchar(800) not null default '',
  karar_zamani  timestamptz,
  kurul         varchar(300) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create unique index if not exists ux_satinalma_teklif_no
  on public.satinalma_teklif (sube_id, teklif_no) where teklif_no <> '';
create index if not exists ix_satinalma_teklif_acik
  on public.satinalma_teklif (sube_id, son_tarih) where durum between 0 and 2;

-- Şartname maddeleri: ZORUNLU maddeyi karşılamayan teklif FİYATINA
--   BAKILMADAN elenir. Ucuz ama uyumsuz ürünün ucuzluğu tartışılmaz.
create table if not exists public.satinalma_teklif_kriter (
  id            bigint generated by default as identity primary key,
  teklif_id     bigint not null references public.satinalma_teklif(id) on delete cascade,
  sira          smallint not null default 0,
  madde         varchar(400) not null,
  zorunlu       smallint not null default 1
);
create index if not exists ix_satinalma_kriter on public.satinalma_teklif_kriter (teklif_id, sira);

create table if not exists public.satinalma_teklif_firma (
  id            bigint generated by default as identity primary key,
  teklif_id     bigint not null references public.satinalma_teklif(id) on delete cascade,
  firma_id      integer not null references public.taraf(id),
  davet_zamani  timestamptz,
  -- 0 davet edildi · 1 teklif verdi · 2 teklif vermedi · 3 teknik elendi
  -- 4 değerlendirildi · 5 kazandı
  durum         smallint not null default 0,
  teklif_zamani timestamptz,
  tutar         numeric(18,2) not null default 0,
  doviz         varchar(5) not null default 'TL',
  teslim_gun    smallint not null default 0,
  garanti_ay    smallint not null default 0,
  odeme_gun     smallint not null default 0,
  -- Puanlar ağırlıklara göre hesaplanır; SAKLANIR ki karar tutanağı
  --   sonradan yeniden hesaplanmasın (ağırlık değişirse geçmiş karar bozulur).
  puan_fiyat      numeric(6,2),
  puan_teslim     numeric(6,2),
  puan_garanti    numeric(6,2),
  puan_performans numeric(6,2),
  puan_toplam     numeric(6,2),
  eleme_neden   varchar(400) not null default '',
  aciklama      varchar(400) not null default ''
);
create unique index if not exists ux_satinalma_teklif_firma
  on public.satinalma_teklif_firma (teklif_id, firma_id);

-- Firma × şartname maddesi yanıtı.
create table if not exists public.satinalma_teklif_yanit (
  id            bigint generated by default as identity primary key,
  teklif_firma_id bigint not null references public.satinalma_teklif_firma(id) on delete cascade,
  kriter_id     bigint not null references public.satinalma_teklif_kriter(id) on delete cascade,
  -- 0 yanıtlanmadı · 1 karşılıyor · 2 kısmi · 3 karşılamıyor
  sonuc         smallint not null default 0,
  deger         varchar(200) not null default '',
  aciklama      varchar(300) not null default ''
);
create unique index if not exists ux_satinalma_teklif_yanit
  on public.satinalma_teklif_yanit (teklif_firma_id, kriter_id);

-- AĞIRLIK KİLİDİ: davet gönderildikten sonra ağırlık değişmez.
create or replace function public.fn_satinalma_agirlik_kilit()
returns trigger language plpgsql as $tg$
begin
    if old.agirlik_kilit = 1
       and (new.agirlik_fiyat is distinct from old.agirlik_fiyat
         or new.agirlik_teslim is distinct from old.agirlik_teslim
         or new.agirlik_garanti is distinct from old.agirlik_garanti
         or new.agirlik_performans is distinct from old.agirlik_performans) then
        raise exception 'Teklif daveti gönderildikten sonra değerlendirme ağırlıkları değiştirilemez.'
              using errcode = 'check_violation';
    end if;
    return new;
end;
$tg$;

drop trigger if exists tg_satinalma_agirlik_kilit on public.satinalma_teklif;
create trigger tg_satinalma_agirlik_kilit
  before update on public.satinalma_teklif
  for each row execute function public.fn_satinalma_agirlik_kilit();

-- ================================================= sipariş süreç katmanı ==
-- `belge` (tür 9) 1:1 uzantısı - `belge_basvuru` ile aynı desen. Siparişin
--   kendisi belgedir; buradaki alanlar SÜREÇTİR.
create table if not exists public.belge_satinalma (
  id            integer primary key references public.belge(id) on delete cascade,
  talep_id      bigint references public.satinalma_talep(id),
  teklif_id     bigint references public.satinalma_teklif(id),
  sozlesme_id   integer,
  -- SÖZ VERİLEN teslim: gecikme bundan sayılır, sipariş tarihinden değil.
  soz_teslim    date,
  ilk_teslim    date,
  son_teslim    date,
  -- Gecikme kaydı ELLE AÇILMAZ: tarih geçtiğinde açılır (uygulama/zamanlı iş).
  gecikme_gun   smallint not null default 0,
  gecikme_bildirim timestamptz,
  -- Ceza HESAPLANIR ama otomatik KESİLMEZ: mahsup kararı insanındır.
  ceza_tutar    numeric(18,2) not null default 0,
  ceza_islendi  smallint not null default 0,
  kismi_kabul   smallint not null default 1,
  -- 0 açık · 1 kısmi teslim · 2 tamamlandı · 8 iptal
  takip_durum   smallint not null default 0,
  aciklama      varchar(400) not null default ''
);
create index if not exists ix_belge_satinalma_gecikme
  on public.belge_satinalma (soz_teslim) where takip_durum in (0, 1);

comment on table public.belge_satinalma is
  '724: alis siparisinin (belge tur 9) SUREC uzantisi. Siparisin kendisi ve '
  'tutarlari belgede; burada teslim taahhudu, gecikme ve ceza durur.';

-- ============================================ üçlü eşleştirme / fatura ==
-- SİPARİŞ ↔ İRSALİYE/SAYIM ↔ FATURA. Üçü aynı şeyi söylemeden ödeme çıkmaz;
--   KISMİ ÖDEME YAPILMAZ - yanlış belgeye doğru para ödenmez.
create table if not exists public.satinalma_fatura_kontrol (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  -- Alış faturası (belge tür 11).
  fatura_belge_id integer not null references public.belge(id) on delete cascade,
  siparis_belge_id integer references public.belge(id),
  -- 0 kontrol edilmedi · 1 tuttu · 2 miktar farkı · 3 fiyat farkı
  -- 4 KDV/bilgi farkı · 5 birden çok fark
  sonuc         smallint not null default 0,
  siparis_tutar numeric(18,2) not null default 0,
  teslim_tutar  numeric(18,2) not null default 0,
  fatura_tutar  numeric(18,2) not null default 0,
  fark_tutar    numeric(18,2) not null default 0,
  fark_metni    varchar(600) not null default '',
  -- 0 beklemede · 1 ödemeye onay · 2 ödeme durduruldu · 3 itiraz edildi
  -- 4 düzeltildi
  odeme_durum   smallint not null default 0,
  mahsup_tutar  numeric(18,2) not null default 0,
  itiraz_zamani timestamptz,
  itiraz_metni  varchar(600) not null default '',
  karar_veren_id integer references public.taraf(id),
  karar_zamani  timestamptz,
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create unique index if not exists ux_satinalma_fatura_kontrol
  on public.satinalma_fatura_kontrol (fatura_belge_id);
create index if not exists ix_satinalma_fatura_acik
  on public.satinalma_fatura_kontrol (sube_id) where odeme_durum in (0, 2, 3);

-- Muayene kabul: mal depoya girer ama KABUL TUTANAĞI imzalanmadan ödeme
--   süreci başlamaz. Şartname uygunluğunu malzemeyi KULLANACAK birim onaylar.
create table if not exists public.satinalma_kabul (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  -- Alış irsaliyesi/fişi (belge tür 10/12).
  belge_id      integer not null references public.belge(id) on delete cascade,
  siparis_belge_id integer references public.belge(id),
  tarih         date not null default current_date,
  komisyon      varchar(300) not null default '',
  -- 0 açık · 1 kabul · 2 kısmi kabul · 3 ret
  sonuc         smallint not null default 0,
  uygunsuzluk   varchar(600) not null default '',
  kullanici_birim_onay smallint not null default 0,
  kullanici_birim_id integer references public.departman(id),
  tutanak_no    varchar(30) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create index if not exists ix_satinalma_kabul_belge on public.satinalma_kabul (belge_id);

-- ================================================ tedarikçi sözleşmesi ==
create table if not exists public.tedarikci_sozlesme (
  id            integer generated by default as identity primary key,
  sube_id       integer not null default 0,
  firma_id      integer not null references public.taraf(id),
  sozlesme_no   varchar(40) not null,
  konu          varchar(200) not null default '',
  -- 1 çerçeve (birim fiyat) · 2 tek seferlik · 3 bakım/servis · 4 kiralama
  tip           smallint not null default 1,
  baslangic     date,
  bitis         date,
  -- Öngörülen miktar TAAHHÜT DEĞİL: ihtiyaç kadar sipariş edilir.
  ongorulen_tutar numeric(18,2) not null default 0,
  teslim_gun    smallint not null default 0,
  acil_teslim_saat smallint not null default 0,
  -- Gecikme cezası oranı (binde) ve üst sınır (yüzde).
  ceza_binde    numeric(6,3) not null default 0,
  ceza_ust_yuzde numeric(6,2) not null default 10,
  asgari_raf_omru_ay smallint not null default 0,
  soguk_zincir  smallint not null default 0,
  -- FESİH SAYACI ekranda durur: "üst üste 3 gecikme" soyut madde değil,
  --   sayılan bir şey.
  fesih_gecikme_adet smallint not null default 0,
  fesih_uygunsuzluk_adet smallint not null default 0,
  -- 0 taslak · 1 yürürlükte · 2 sona erdi · 3 feshedildi
  durum         smallint not null default 1,
  aciklama      varchar(600) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now(),
  degistiren    integer not null default 0,
  degistirme_tarihi timestamptz
);
create unique index if not exists ux_tedarikci_sozlesme
  on public.tedarikci_sozlesme (sube_id, sozlesme_no);
create index if not exists ix_tedarikci_sozlesme_firma
  on public.tedarikci_sozlesme (firma_id, durum);

create table if not exists public.tedarikci_sozlesme_fiyat (
  id            bigint generated by default as identity primary key,
  sozlesme_id   integer not null references public.tedarikci_sozlesme(id) on delete cascade,
  stok_id       integer references public.stok(id),
  hizmet_id     integer references public.hizmet(id),
  ad            varchar(200) not null default '',
  birim_fiyat   numeric(18,4) not null default 0,
  doviz         varchar(5) not null default 'TL',
  gecerli_bas   date,
  gecerli_son   date
);
create index if not exists ix_tedarikci_sozlesme_fiyat
  on public.tedarikci_sozlesme_fiyat (sozlesme_id, stok_id);

-- ================================================ tedarikçi performansı ==
-- SKOR HESAPLANIR, GİRİLMEZ (bkz başlık). Olaylar burada birikir.
create table if not exists public.tedarikci_olay (
  id            bigint generated by default as identity primary key,
  sube_id       integer not null default 0,
  firma_id      integer not null references public.taraf(id),
  zaman         timestamptz not null default now(),
  -- 1 gecikme · 2 kalite uygunsuzluğu · 3 fatura farkı · 4 belge eksiği
  -- 5 olumlu (taahhüdün üstünde) · 9 diğer
  tur           smallint not null default 9,
  belge_id      integer references public.belge(id),
  sozlesme_id   integer references public.tedarikci_sozlesme(id),
  aciklama      varchar(400) not null default '',
  -- Skora etkisi (+/-). Ağırlık tür bazında ayarlanabilir olsun diye
  --   olayın kendisinde saklanır: geçmiş olayın etkisi sonradan değişmemeli.
  skor_etki     numeric(6,2) not null default 0,
  ekleyen       integer not null default 0
);
create index if not exists ix_tedarikci_olay on public.tedarikci_olay (firma_id, zaman desc);

create table if not exists public.tedarikci_belge (
  id            bigint generated by default as identity primary key,
  firma_id      integer not null references public.taraf(id) on delete cascade,
  -- 1 sicil gazetesi · 2 imza sirküleri · 3 vergi borcu yoktur
  -- 4 SGK borcu yoktur · 5 ÜTS firma kaydı · 6 kalite belgesi (ISO)
  -- 7 yasaklılık teyidi · 8 banka hesap teyidi · 99 diğer
  tur           smallint not null default 99,
  ad            varchar(200) not null default '',
  tarih         date,
  -- SÜRESİ DOLAN BELGE SİPARİŞİ DURDURUR: borcu yoktur yazısı bir aylıktır.
  gecerlilik    date,
  dokuman_id    integer references public.dokuman(id),
  aciklama      varchar(300) not null default '',
  ekleyen       integer not null default 0,
  ekleme_tarihi timestamptz not null default now()
);
create index if not exists ix_tedarikci_belge on public.tedarikci_belge (firma_id, tur);
create index if not exists ix_tedarikci_belge_suresi
  on public.tedarikci_belge (gecerlilik) where gecerlilik is not null;

-- =========================================================== görünümler ==
-- BÜTÇE: harcanan + TAAHHÜT (açık sipariş). İkisi ayrı gösterilir ama
--   kalan ikisini birden düşer.
create or replace view public.v_butce_durum as
select b.id, b.sube_id, b.yil, b.kod, b.ad, b.tutar,
       coalesce(h.harcanan, 0) as harcanan,
       coalesce(t.taahhut, 0) as taahhut,
       b.tutar - coalesce(h.harcanan, 0) - coalesce(t.taahhut, 0) as kalan,
       case when b.tutar > 0
            then round((coalesce(h.harcanan, 0) + coalesce(t.taahhut, 0))
                       / b.tutar * 100, 1) else 0 end as kullanim_yuzde
  from public.butce_kalem b
  -- HARCANAN: kesinleşmiş alış faturaları (tür 11).
  left join lateral (
      select sum(f.genel_toplam) as harcanan
        from public.belge f
        join public.satinalma_fatura_kontrol k on k.fatura_belge_id = f.id
        join public.belge s on s.id = k.siparis_belge_id
        join public.belge_satinalma bs on bs.id = s.id
        join public.satinalma_talep tl on tl.id = bs.talep_id
       where f.tur = 11 and f.durum <> 0
         and tl.butce_kalem_id = b.id
         and extract(year from f.belge_tarihi) = b.yil) h on true
  -- TAAHHÜT: açık siparişler (tür 9, takip_durum 0/1).
  left join lateral (
      select sum(s.genel_toplam) as taahhut
        from public.belge s
        join public.belge_satinalma bs on bs.id = s.id
        join public.satinalma_talep tl on tl.id = bs.talep_id
       where s.tur = 9 and s.durum <> 0 and bs.takip_durum in (0, 1)
         and tl.butce_kalem_id = b.id
         and extract(year from s.belge_tarihi) = b.yil) t on true
 where b.aktif = 1;

comment on view public.v_butce_durum is
  '724: butce kalemi durumu. TAAHHUT DE HARCAMADIR - acik siparis faturalanmadi '
  'ama parasi baglandi; kalan ikisini birden duser.';

-- TEDARİKÇİ SKORU: olaylardan türer, son 12 ay.
create or replace view public.v_tedarikci_skor as
select t.id as firma_id, t.unvan,
       coalesce(100 + sum(o.skor_etki) filter (
           where o.zaman >= now() - interval '12 months'), 100)::numeric(6,2) as skor,
       count(*) filter (where o.tur = 1 and o.zaman >= now() - interval '12 months') as gecikme,
       count(*) filter (where o.tur = 2 and o.zaman >= now() - interval '12 months') as uygunsuzluk,
       count(*) filter (where o.tur = 3 and o.zaman >= now() - interval '12 months') as fatura_farki,
       -- Belgesi süresi dolmuş firma yeni sipariş açamaz.
       exists (select 1 from public.tedarikci_belge b
                where b.firma_id = t.id and b.gecerlilik is not null
                  and b.gecerlilik < current_date) as belge_suresi_doldu
  from public.taraf t
  left join public.tedarikci_olay o on o.firma_id = t.id
 where t.tedarikci = 1
 group by t.id, t.unvan;

comment on view public.v_tedarikci_skor is
  '724: skor OLAYLARDAN turer (son 12 ay), elle girilmez. 70 alti izleme, '
  '50 alti askiya alma esigi - esikler uygulamada.';

-- =============================================================== yetki ==
insert into public.yetki (kod, ad, grup, tur, sira, aktif)
select 'satinalma', 'Satınalma', 'Satınalma', 0, 48, 1
 where not exists (select 1 from public.yetki where kod = 'satinalma');

insert into public.yetki (kod, ad, grup, tur, sira, aktif)
select v.kod, v.ad, 'Satınalma', v.tur, v.sira, 1 from (values
    ('satinalma.talep',      'Satınalma talebi',            0::smallint, 1::smallint),
    ('satinalma.teklif',     'Teklif / ihale',              0, 2),
    ('satinalma.siparis',    'Sipariş',                     0, 3),
    ('satinalma.kabul',      'Muayene kabul',               0, 4),
    ('satinalma.tedarikci',  'Tedarikçi yönetimi',          0, 5),
    ('satinalma.butce',      'Bütçe tanımları',             0, 6),
    -- AKSIYON: onay basamaklari ve para cikaran kararlar ayri yetki.
    ('satinalma.onay_birim', 'Talebi onayla (birim)',       1, 7),
    ('satinalma.onay_satinalma', 'Talebi onayla (satınalma)', 1, 8),
    ('satinalma.onay_ust',   'Talebi onayla (üst yönetim)', 1, 9),
    ('satinalma.karar',      'Teklif kararı ver',           1, 10),
    ('satinalma.odeme_onay', 'Ödemeye onay ver',            1, 11),
    ('satinalma.ceza',       'Gecikme cezası işlet',        1, 12),
    ('satinalma.askiya_al',  'Tedarikçiyi askıya al',       1, 13)
  ) as v(kod, ad, tur, sira)
 where not exists (select 1 from public.yetki y where y.kod = v.kod);

insert into public.rol_yetki (rol_id, yetki_id, gor, ekle, degistir, sil, ekleyen)
select r.id, y.id, 1, 1, 1, 1, 0
  from public.rol r cross join public.yetki y
 where r.kod = 'yonetici'
   and (y.kod = 'satinalma' or y.kod like 'satinalma.%')
   and not exists (select 1 from public.rol_yetki ry
                    where ry.rol_id = r.id and ry.yetki_id = y.id);
