-- =====================================================================
-- 801 - TELERADYOLOJI NOBET CIZELGESI + OTOMATIK ATAMA KURALLARI
--
-- Kullanici: *"nöbet çizelgesi ve atama kurallarıyla devam et"*.
-- Tasarim: `Ekranlar/Teleradyoloji/telerad_sureci.html` adim 4 (Atama).
--
-- 797'de atama YALNIZ ELLE yapilabiliyordu: gelen is sirada bekliyor, birinin
-- listeye bakip "bunu ben alayim" demesi gerekiyordu. Gece ve hafta sonu
-- teleradyolojinin asil is saatidir; o saatte listeye bakan kisi
-- olmayabilir. Iki eksik parca:
--
--   1. NOBET CIZELGESI - "su an kim is basinda". Calisma plani (718) hekimin
--      POLIKLINIK duzenidir; teleradyoloji nobeti ayri bir seydir: radyolog
--      evden okur, vardiyasi gece yariisini gecer, gun icinde devredilir.
--   2. ATAMA KURALI - "hangi is kime". Modalite/oncelik/kurum/saat esler,
--      hedefi ya belirli bir radyolog ya da O ANKI NOBETCI olur.
--
-- ONERI TEK YERDE: `fn_telerad_radyolog_oner` hem ekranin "Otomatik Dagit"
-- dugmesinin hem ileride DICOM alimindan gelen isin cagirdigi tek fonksiyon.
-- Kurali iki yerde yorumlamak, ekran ile arka planin farkli radyolog secmesi
-- demekti.
--
-- ATAMANIN KENDISI YINE TEK KAPIDAN GECER: fonksiyon ONERIR, yazan yine
-- `telerad_istek.atanan_radyolog_id` guncellemesidir - durum gecisini ve
-- atama izini 797 tetikleri yazar.
-- =====================================================================

-- ----------------------------------------------------------- yetkiler ----
-- Cizelge ve kural TANIM ekranlaridir: gunluk isin (`telerad.ata`) degil,
--   kurulumun yetkisi. Ayri olmalari, gece okuyan radyologa kural
--   degistirme hakki vermeden atama hakki verebilmek icin.
insert into public.yetki (kod, ad, grup, tur, sira, aktif, urun_modu, modul)
select x.kod, x.ad, 'Teleradyoloji', 0, x.sira, 1, 2, 'teleradyoloji'
  from (values ('teleradyoloji.nobet', 'Teleradyoloji nöbet çizelgesi', 40),
               ('teleradyoloji.kural', 'Teleradyoloji atama kuralları',  50))
       as x(kod, ad, sira)
 where not exists (select 1 from public.yetki y where y.kod = x.kod);

-- ------------------------------------------------------------- nobet ----
create table if not exists public.telerad_nobet (
    id             integer generated by default as identity primary key,
    radyolog_id    integer     not null references public.taraf(id),
    -- ZAMAN ARALIGI TIMESTAMP: nobet gun yarisini gecer ("20:00 - 08:00").
    --   Calisma plani (718) gibi 'HH:MM' saklamak, geceyi iki satira bolmek
    --   ya da "bitis baslangictan kucuk" gibi bir istisna kurali uydurmak
    --   demekti.
    baslangic      timestamp   not null,
    bitis          timestamp   not null,
    tur            smallint    not null default 1,   -- 1 gunduz · 2 gece · 3 hafta sonu · 4 yedek
    -- YEDEK NOBETCI (tur 4): asil nobetci ulasilamazsa/doluysa is buna duser.
    --   Oneri fonksiyonu once asillara bakar.
    kurum_id       integer     references public.telerad_kurum(id),
    modalite       smallint    not null default 0,   -- 0 hepsi
    azami_is       integer     not null default 0,   -- 0 sinirsiz; ustundeyse atlanir
    aciklama       varchar(200) not null default '',
    aktif          smallint    not null default 1,
    sube_id        integer     references public.sube(id),
    ekleyen        integer     not null default 0,
    ekleme_tarihi  timestamptz not null default now(),
    degistiren     integer     not null default 0,
    degistirme_tarihi timestamptz,
    constraint ck_telerad_nobet_zaman check (bitis > baslangic),
    constraint ck_telerad_nobet_tur check (tur between 1 and 4)
);

comment on table public.telerad_nobet is
  '801: teleradyoloji nobet cizelgesi - "su an kim is basinda". Poliklinik '
  'calisma planindan AYRI: radyolog evden okur, vardiya gece yariisini gecer.';

create index if not exists ix_telerad_nobet_zaman
    on public.telerad_nobet (baslangic, bitis) where aktif = 1;
create index if not exists ix_telerad_nobet_radyolog
    on public.telerad_nobet (radyolog_id, baslangic desc);

-- AYNI RADYOLOG AYNI ANDA IKI NOBETTE OLAMAZ: cizelge kendi icinde
--   celisirse "su an kim nobetci" sorusunun iki cevabi olur. Tetikle
--   korunuyor - exclusion constraint btree_gist ister, kurulumda yok.
create or replace function public.tg_telerad_nobet_cakisma()
returns trigger
language plpgsql
as $function$
declare
    v_cakisan integer;
begin
    if new.aktif = 0 then return new; end if;

    select n.id into v_cakisan
      from public.telerad_nobet n
     where n.radyolog_id = new.radyolog_id
       and n.aktif = 1
       and n.id <> coalesce(new.id, 0)
       and n.baslangic < new.bitis
       and n.bitis > new.baslangic
     limit 1;

    if v_cakisan is not null then
        raise exception
          'Bu radyologun ayni saatlerde baska bir nobeti var (nobet %). '
          'Cizelge kendi icinde celisirse "su an kim nobetci" sorusunun iki '
          'cevabi olur.', v_cakisan
          using errcode = '23505';
    end if;

    if tg_op = 'UPDATE' then new.degistirme_tarihi := now(); end if;
    return new;
end $function$;

drop trigger if exists tg_telerad_nobet_cakisma on public.telerad_nobet;
create trigger tg_telerad_nobet_cakisma
    before insert or update on public.telerad_nobet
    for each row execute function public.tg_telerad_nobet_cakisma();

-- ------------------------------------------------------ atama kurali ----
create table if not exists public.telerad_atama_kurali (
    id             integer generated by default as identity primary key,
    ad             varchar(120) not null default '',
    -- SIRA = KARAR SIRASI: ilk uyan kural kazanir. "Acil BT once Dr. X'e"
    --   kurali "her is nobetciye" kuralinin USTUNDE durmali; sirasiz bir
    --   kural kumesi hangi kuralin islediğini rastgele birakirdi.
    sira           integer     not null default 10,
    -- --------------------------------------------------------- kosul ----
    kurum_id       integer     references public.telerad_kurum(id),  -- null = hepsi
    modalite       smallint    not null default 0,                   -- 0 = hepsi
    oncelik        smallint    not null default 0,                   -- 0 = hepsi
    -- SAAT PENCERESI calisma plani (718) bicimiyle AYNI: 'HH:MM' metin,
    --   gunler "1,2,3" (1 Pzt … 7 Paz). Iki ekran iki farkli saat bicimi
    --   kullanmasin. Bos = her saat / her gun.
    gunler         varchar(20)  not null default '',
    saat_bas       varchar(5)   not null default '',
    saat_bit       varchar(5)   not null default '',
    -- --------------------------------------------------------- hedef ----
    -- 1 nobetci (o an nobette olan) · 2 belirli radyolog · 3 en az yuklu
    hedef_tur      smallint    not null default 1,
    hedef_radyolog_id integer  references public.taraf(id),
    -- AZAMI BEKLEYEN: radyologun uzerindeki acik is bunu asiyorsa kural onu
    --   atlar. Otomatik dagitim "bir kisiyi bogmak" olmamali.
    azami_is       integer     not null default 0,   -- 0 sinirsiz
    aktif          smallint    not null default 1,
    sube_id        integer     references public.sube(id),
    ekleyen        integer     not null default 0,
    ekleme_tarihi  timestamptz not null default now(),
    degistiren     integer     not null default 0,
    degistirme_tarihi timestamptz,
    constraint ck_telerad_kural_hedef check (hedef_tur between 1 and 3),
    constraint ck_telerad_kural_oncelik check (oncelik between 0 and 3),
    -- HEDEF "BELIRLI RADYOLOG" ISE KIMIN oldugu YAZILMALI: yoksa kural
    --   sessizce hicbir zaman eslesmezdi.
    constraint ck_telerad_kural_radyolog
        check (hedef_tur <> 2 or hedef_radyolog_id is not null)
);

comment on table public.telerad_atama_kurali is
  '801: otomatik atama kurallari - hangi is kime. SIRA karar sirasidir, ilk '
  'uyan kural kazanir. Hedef: o anki nobetci · belirli radyolog · en az yuklu.';

create index if not exists ix_telerad_kural_sira
    on public.telerad_atama_kurali (sira, id) where aktif = 1;

-- ------------------------------------------------- nobetci gorunumu ----
-- "SU AN KIM IS BASINDA": ekran da oneri fonksiyonu da buradan okur.
create or replace view public.v_telerad_nobetci as
select n.id, n.radyolog_id,
       coalesce(t.unvan, '')                         as radyolog_adi,
       n.baslangic, n.bitis, n.tur,
       case n.tur when 2 then 'Gece' when 3 then 'Hafta sonu'
                  when 4 then 'Yedek' else 'Gündüz' end as tur_adi,
       n.kurum_id, n.modalite, n.azami_is, n.sube_id,
       -- Uzerindeki ACIK is: atanmis ama onaylanmamis (durum 3 atandi ·
       --   4 okunuyor · 5 taslak).
       (select count(*) from public.telerad_istek i
         where i.atanan_radyolog_id = n.radyolog_id
           and i.durum between 3 and 5)              as acik_is,
       (now()::timestamp >= n.baslangic
        and now()::timestamp < n.bitis)::int::smallint as su_an
  from public.telerad_nobet n
  left join public.taraf t on t.id = n.radyolog_id
 where n.aktif = 1;

comment on view public.v_telerad_nobetci is
  '801: nobet cizelgesi + o radyologun acik is sayisi; su_an = simdi nobette.';

-- --------------------------------------------- radyolog oneri fonksiyonu ----
-- KURALI TEK YERDE YORUMLA: ekranin "Otomatik Dagit" dugmesi de, ileride
--   DICOM alimindan gelen is de burayi cagirir. Iki yerde yorumlamak, ekran
--   ile arka planin farkli radyolog secmesi demekti.
-- Donus: onerilen radyolog (taraf id) ya da null (kural uymadi / herkes dolu).
create or replace function public.fn_telerad_radyolog_oner(p_istek_id integer)
returns integer
language plpgsql
stable
as $function$
declare
    v_istek   record;
    v_kural   record;
    v_gun     text;
    v_saat    text;
    v_sonuc   integer;
begin
    select i.id, i.kurum_id, i.modalite, i.oncelik, i.sube_id, i.durum,
           i.atanan_radyolog_id
      into v_istek
      from public.telerad_istek i
     where i.id = p_istek_id;

    if not found then return null; end if;
    -- ATANMIS ISI YENIDEN DAGITMA: "yeniden atama" ayri bir karardir.
    if v_istek.atanan_radyolog_id is not null then return null; end if;
    -- Iptal ve bitmis is dagitilmaz; goruntusu gelmemis is de SIRADA degildir.
    if v_istek.durum not in (2, 8) then return null; end if;

    v_gun  := extract(isodow from now())::text;      -- 1 Pzt … 7 Paz
    v_saat := to_char(now(), 'HH24:MI');

    for v_kural in
        select k.*
          from public.telerad_atama_kurali k
         where k.aktif = 1
           and (k.sube_id is null or v_istek.sube_id is null
                or k.sube_id = v_istek.sube_id)
           and (k.kurum_id is null or k.kurum_id = v_istek.kurum_id)
           and (k.modalite = 0 or k.modalite = v_istek.modalite)
           and (k.oncelik = 0 or k.oncelik = v_istek.oncelik)
           -- Gun maskesi bos = her gun. Listedeki gunlerden biri olmali.
           and (k.gunler = '' or v_gun = any (string_to_array(k.gunler, ',')))
           -- SAAT PENCERESI GECE YARISINI GECEBILIR ("20:00-08:00"):
           --   bas <= bit ise normal aralik, degilse gun asiran aralik.
           and (k.saat_bas = '' or k.saat_bit = ''
                or (k.saat_bas <= k.saat_bit
                    and v_saat >= k.saat_bas and v_saat < k.saat_bit)
                or (k.saat_bas > k.saat_bit
                    and (v_saat >= k.saat_bas or v_saat < k.saat_bit)))
         order by k.sira, k.id
    loop
        if v_kural.hedef_tur = 2 then
            -- BELIRLI RADYOLOG: doluysa kural atlanir, sonraki kural denenir.
            select v_kural.hedef_radyolog_id into v_sonuc
             where v_kural.azami_is = 0
                or (select count(*) from public.telerad_istek i
                     where i.atanan_radyolog_id = v_kural.hedef_radyolog_id
                       and i.durum between 3 and 5) < v_kural.azami_is;

        elsif v_kural.hedef_tur = 1 then
            -- O ANKI NOBETCI: birden fazlaysa EN AZ YUKLU olan. Yedek
            --   nobetci (tur 4) en sona dusurulur - asil nobetci varken
            --   yedege is vermek cizelgeyi anlamsiz kilar.
            select n.radyolog_id into v_sonuc
              from public.v_telerad_nobetci n
             where n.su_an = 1
               and (n.kurum_id is null or n.kurum_id = v_istek.kurum_id)
               and (n.modalite = 0 or n.modalite = v_istek.modalite)
               and (n.sube_id is null or v_istek.sube_id is null
                    or n.sube_id = v_istek.sube_id)
               and (n.azami_is = 0 or n.acik_is < n.azami_is)
               and (v_kural.azami_is = 0 or n.acik_is < v_kural.azami_is)
             order by case when n.tur = 4 then 1 else 0 end, n.acik_is, n.radyolog_id
             limit 1;

        else
            -- EN AZ YUKLU: nobet tanimli degilse de calissin diye - o gun
            --   is almis radyologlar arasindan seçer; hic kimse yoksa null
            --   doner ve is sirada kalir (uydurma atama yapilmaz).
            select i.atanan_radyolog_id into v_sonuc
              from public.telerad_istek i
             where i.atanan_radyolog_id is not null
               and (v_istek.sube_id is null or i.sube_id = v_istek.sube_id)
               and i.ekleme_tarihi > now() - interval '30 day'
             group by i.atanan_radyolog_id
            having v_kural.azami_is = 0
                or count(*) filter (where i.durum between 3 and 5) < v_kural.azami_is
             order by count(*) filter (where i.durum between 3 and 5), i.atanan_radyolog_id
             limit 1;
        end if;

        if v_sonuc is not null then return v_sonuc; end if;
    end loop;

    return null;   -- kural uymadi ya da herkes dolu: is SIRADA kalir
end $function$;

comment on function public.fn_telerad_radyolog_oner(integer) is
  '801: istegi hangi radyologun almasi gerektigini KURALLARA gore onerir. '
  'Ekran da arka plan da burayi cagirir - kural iki yerde yorumlanmasin. '
  'Atamayi yazmaz: null donerse is sirada kalir.';

-- ---------------------------------------------------- yetki dagitimi ----
-- YENI YETKI KIMSEDE YOKSA EKRAN DA YOK (797'deki ders): teleradyoloji
--   yetkisi olan role cizelge/kural yetkisi de verilir; salt okuma rolleri
--   yalniz gorur.
insert into public.rol_yetki (rol_id, yetki_id, gor, ekle, degistir, sil, deger)
select r.id, y.id,
       1,
       case when r.kod in ('rapor_goruntuleyici', 'ust_yonetim') then 0 else 1 end,
       case when r.kod in ('rapor_goruntuleyici', 'ust_yonetim') then 0 else 1 end,
       case when r.kod = 'yonetici' then 1 else 0 end, ''
  from public.rol r
  cross join public.yetki y
 where y.kod in ('teleradyoloji.nobet', 'teleradyoloji.kural')
   and exists (select 1 from public.rol_yetki ry
                 join public.yetki y2 on y2.id = ry.yetki_id
                where ry.rol_id = r.id and y2.kod = 'teleradyoloji' and ry.gor = 1)
   and not exists (select 1 from public.rol_yetki ry
                    where ry.rol_id = r.id and ry.yetki_id = y.id);

do $$
declare r record;
begin
    for r in select y.kod, count(ry.rol_id) as rol
               from public.yetki y
               left join public.rol_yetki ry on ry.yetki_id = y.id
              where y.kod in ('teleradyoloji.nobet', 'teleradyoloji.kural')
              group by y.kod
    loop
        raise notice '801: % yetkisi % role verildi.', r.kod, r.rol;
    end loop;
end $$;
