-- ============================================================================
--  Gentegre AI — HBYS İNGİLİZCE SÖZLÜK (849)
--  849_ingilizce_sozluk_hbys.sql
--
--  Kullanıcı: *"GentegreAI içindeki HBYS modülünü İngilizce diline hazırla"*.
--
--  ============ MEVCUT ALTYAPI GENİŞLETİLDİ ===========================
--  Çeviri sistemi 194'ten beri VAR: sözlük `ceviri` tablosunda, arayüz
--  `/api/ceviri/{dil}` ile indiriyor, dil kullanıcı kaydında
--  (`taraf_kullanici.dil`: 0 Türkçe · 1 English · 2 Deutsch) ve üst şeritte
--  bayrakla değişiyor. Koda GÖMÜLÜ ikinci bir sözlük kurulmadı - iki sözlük
--  zamanla ayrışır ve yeni çeviri için sürüm çıkmak gerekirdi (194 kararı).
--
--  Bu betik İngilizce satırları toplu ekler: kart/liste başlıkları
--  (`etiket`) ve menü/ekran adları (`menu`). Anahtar Türkçe metnin
--  kendisidir - çevirisi olmayan metin Türkçe görünür, ekran boş kalmaz.
--
--  ÇEVRİLMEYENLER (bilerek): SUT, SKRS, MEDULA, e-Nabız, ÜTS, GİB, ICD,
--  LOINC, PACS, DICOM terimleri (Accession, Study UID, AE Title, Modality)
--  ve SpO₂ - bunlar mevzuat/standart adlarıdır, çevrilince tanınmaz olur.
--
--  Idempotent: aynı anahtar varsa metni günceller (`on conflict`).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin) values
    ('etiket', 'Id', 1, 'Id'),
    ('etiket', 'Genel', 1, 'General'),
    ('etiket', 'Durum Kodu', 1, 'Status code'),
    ('etiket', 'Sonuç', 1, 'Result'),
    ('etiket', 'Zaman', 1, 'Time'),
    ('etiket', 'Bitiş', 1, 'End'),
    ('etiket', 'Not', 1, 'Note'),
    ('etiket', 'Hasta Id', 1, 'Patient Id'),
    ('etiket', 'Tür Kodu', 1, 'Type code'),
    ('etiket', 'Tanım', 1, 'Definition'),
    ('etiket', 'Cihaz', 1, 'Device'),
    ('etiket', 'Başlangıç', 1, 'Start'),
    ('etiket', 'Olay', 1, 'Event'),
    ('etiket', 'Talep', 1, 'Request'),
    ('etiket', 'Takip', 1, 'Follow-up'),
    ('etiket', 'İstem', 1, 'Order'),
    ('etiket', 'Tanımlama', 1, 'Identification'),
    ('etiket', 'Tetkik', 1, 'Test'),
    ('etiket', 'Çekim', 1, 'Acquisition'),
    ('etiket', 'Bölüm', 1, 'Department'),
    ('etiket', 'Değerlendirme', 1, 'Assessment'),
    ('etiket', 'Gerekçe', 1, 'Justification'),
    ('etiket', 'Başlama', 1, 'Start'),
    ('etiket', 'Diğer', 1, 'Other'),
    ('etiket', 'Çağrı', 1, 'Call'),
    ('etiket', 'Lot', 1, 'Lot'),
    ('etiket', '🗑 Sil', 1, 'Delete'),
    ('etiket', 'Plan', 1, 'Plan'),
    ('etiket', 'Seans', 1, 'Session'),
    ('etiket', 'Firma', 1, 'Company'),
    ('etiket', 'Ziyaret', 1, 'Visit'),
    ('etiket', 'Kurum', 1, 'Institution'),
    ('etiket', 'Sözleşme', 1, 'Contract'),
    ('etiket', 'Randevu', 1, 'Appointment'),
    ('etiket', 'İlaç', 1, 'Drug'),
    ('etiket', 'İşlem', 1, 'Procedure'),
    ('etiket', 'Maliyet', 1, 'Cost'),
    ('etiket', 'Kapsam', 1, 'Scope'),
    ('etiket', 'Konu', 1, 'Subject'),
    ('etiket', 'Akış', 1, 'Workflow'),
    ('etiket', 'Öncelik', 1, 'Priority'),
    ('etiket', 'Teslim', 1, 'Delivery'),
    ('etiket', 'Karar', 1, 'Decision'),
    ('etiket', 'Uygulama', 1, 'Administration'),
    ('etiket', '✎ Düzenle', 1, 'Edit'),
    ('etiket', 'Süre', 1, 'Duration'),
    ('etiket', 'Biyomedikal', 1, 'Biomedical'),
    ('etiket', 'İş', 1, 'Work'),
    ('etiket', 'Program', 1, 'Program'),
    ('etiket', 'Belge', 1, 'Document'),
    ('etiket', 'Tanım / Sınıflandırma', 1, 'Definition / Classification'),
    ('etiket', 'Detay', 1, 'Detail'),
    ('etiket', '🖨️ Yazdır', 1, 'Print'),
    ('etiket', 'Bildirim', 1, 'Notification'),
    ('etiket', 'Başvuru', 1, 'Encounter'),
    ('etiket', 'Geçerlilik', 1, 'Validity'),
    ('etiket', 'İş Emri', 1, 'Work order'),
    ('etiket', 'Kampanya', 1, 'Campaign'),
    ('etiket', 'Kategori', 1, 'Category'),
    ('etiket', 'Süre (dk)', 1, 'Duration (min)'),
    ('etiket', 'Bağlantı', 1, 'Connection'),
    ('etiket', 'Bütçe', 1, 'Budget'),
    ('etiket', 'Rapor', 1, 'Report'),
    ('etiket', 'Sevk', 1, 'Referral'),
    ('etiket', 'Ölçüm', 1, 'Measurement'),
    ('etiket', 'Personel', 1, 'Employee'),
    ('etiket', 'Doz', 1, 'Dose'),
    ('etiket', 'Gönderim', 1, 'Submission'),
    ('etiket', 'Firma Kimliği', 1, 'Company identity'),
    ('etiket', 'Tanı', 1, 'Diagnosis'),
    ('etiket', 'Anamnez', 1, 'History'),
    ('etiket', 'POS / Kart', 1, 'POS / Card'),
    ('etiket', 'Metin', 1, 'Text'),
    ('etiket', 'Sorumlu', 1, 'Owner'),
    ('etiket', 'Stok', 1, 'Item'),
    ('etiket', 'Adres / Fatura Bilgisi', 1, 'Address / Billing'),
    ('etiket', 'Göz', 1, 'Eye'),
    ('etiket', 'Taahhüt', 1, 'Commitment'),
    ('etiket', 'Order', 1, 'Order'),
    ('etiket', 'Yatak', 1, 'Bed'),
    ('etiket', 'Kişi', 1, 'Person'),
    ('etiket', 'Kanal', 1, 'Channel'),
    ('etiket', 'Fatura / Vergi Kimligi', 1, 'Invoice / Tax identity'),
    ('etiket', 'Adı', 1, 'Name'),
    ('etiket', 'Kimlik Bilgileri', 1, 'Identity details'),
    ('etiket', 'Sınıflandırma', 1, 'Classification'),
    ('etiket', 'Periyot & Geçerlilik', 1, 'Period & validity'),
    ('etiket', 'Adres ve Durum', 1, 'Address and status'),
    ('etiket', 'Sürüm', 1, 'Version'),
    ('etiket', 'Şablon', 1, 'Template'),
    ('etiket', 'Reçete (OD / OS)', 1, 'Prescription (OD / OS)'),
    ('etiket', 'Kullanım', 1, 'Usage'),
    ('etiket', 'İmza', 1, 'Signature'),
    ('etiket', 'Sonuç ve Birim', 1, 'Result and unit'),
    ('etiket', 'Süre ve Onay', 1, 'Duration and approval'),
    ('etiket', 'İçerik', 1, 'Content'),
    ('etiket', 'Kabul', 1, 'Admission'),
    ('etiket', 'Vergi & Ana Birim', 1, 'Tax & base unit'),
    ('etiket', 'Taraf', 1, 'Party'),
    ('etiket', 'Barkod', 1, 'Barcode'),
    ('etiket', 'Yön', 1, 'Direction'),
    ('etiket', 'Muayene', 1, 'Examination'),
    ('etiket', 'Fiyat & Onay', 1, 'Price & approval'),
    ('etiket', 'Planlanan', 1, 'Planned'),
    ('etiket', 'Hazırlama', 1, 'Preparation'),
    ('etiket', 'Yöntem', 1, 'Method'),
    ('etiket', 'Kanaat', 1, 'Opinion'),
    ('etiket', 'Numune', 1, 'Specimen'),
    ('etiket', 'Sevk / Konsültasyon', 1, 'Referral / Consultation'),
    ('etiket', 'Seri No', 1, 'Serial No'),
    ('etiket', 'Referans', 1, 'Reference'),
    ('etiket', 'Kuyruk', 1, 'Queue'),
    ('etiket', 'Bölge', 1, 'Region'),
    ('etiket', 'Görev', 1, 'Position'),
    ('etiket', 'Merkez Adresi', 1, 'Head office address'),
    ('etiket', 'Gen', 1, 'Gene'),
    ('etiket', 'Tatil', 1, 'Holiday'),
    ('etiket', 'Banka', 1, 'Bank'),
    ('etiket', 'Fırsat', 1, 'Opportunity'),
    ('etiket', 'Tutar / Tahmin', 1, 'Amount / Estimate'),
    ('etiket', 'Gösterge', 1, 'Indicator'),
    ('etiket', 'Eşleme', 1, 'Mapping'),
    ('etiket', 'Teklif', 1, 'Quotation'),
    ('etiket', 'Emanet', 1, 'Deposit'),
    ('etiket', 'Kodlar', 1, 'Codes'),
    ('etiket', 'Belge Id', 1, 'Document Id'),
    ('etiket', 'Sube', 1, 'Branch'),
    ('etiket', 'Aşama', 1, 'Stage'),
    ('etiket', 'Ameliyat', 1, 'Surgery'),
    ('etiket', 'Müdahale', 1, 'Intervention'),
    ('etiket', 'Agent', 1, 'Agent'),
    ('etiket', 'Yatış', 1, 'Admission'),
    ('etiket', 'İzlem', 1, 'Monitoring'),
    ('etiket', 'Varsayılan', 1, 'Default'),
    ('etiket', 'Ağrı & Nörolojik', 1, 'Pain & neurological'),
    ('etiket', 'Panel', 1, 'Panel'),
    ('etiket', 'Termin', 1, 'Due date'),
    ('etiket', 'Yıl', 1, 'Year'),
    ('etiket', 'Hazırlık', 1, 'Preparation'),
    ('etiket', 'Modalite', 1, 'Modality'),
    ('etiket', 'Kalem', 1, 'Line item'),
    ('etiket', 'Hata', 1, 'Error'),
    ('etiket', 'Yükümlülük', 1, 'Obligation'),
    ('etiket', 'Ücret', 1, 'Fee'),
    ('etiket', 'Başvuru Id', 1, 'Encounter Id'),
    ('etiket', 'Malzeme', 1, 'Material'),
    ('etiket', 'e-Belge Ayarlari', 1, 'e-Document settings'),
    ('etiket', 'Satın Alma', 1, 'Purchasing'),
    ('etiket', 'Sözleşme & Ömür', 1, 'Contract & lifetime'),
    ('etiket', 'Uyarı', 1, 'Warning'),
    ('etiket', 'Yerel Ayarlar', 1, 'Regional settings'),
    ('etiket', 'e-Belge', 1, 'e-Document'),
    ('etiket', 'Yer', 1, 'Location'),
    ('etiket', 'Red Nedeni', 1, 'Rejection reason'),
    ('etiket', 'İzin', 1, 'Leave'),
    ('etiket', 'Avans', 1, 'Advance'),
    ('etiket', 'Kural', 1, 'Rule'),
    ('etiket', 'Banka Bilgileri', 1, 'Bank details'),
    ('etiket', 'Görev Bilgileri', 1, 'Position details'),
    ('etiket', 'Beyan', 1, 'Declaration'),
    ('etiket', 'Tanı (ICD-10)', 1, 'Diagnosis (ICD-10)'),
    ('etiket', 'Numaralama', 1, 'Numbering'),
    ('etiket', 'Deneme', 1, 'Attempt'),
    ('etiket', 'Radyolog', 1, 'Radiologist'),
    ('etiket', 'Görüntü', 1, 'Image'),
    ('etiket', 'Süre & İmza', 1, 'Duration & signature'),
    ('etiket', 'Öncelik Kodu', 1, 'Priority code'),
    ('etiket', 'Sonuç Kodu', 1, 'Result code'),
    ('etiket', 'Bölüm Id', 1, 'Department Id'),
    ('etiket', 'Modalite Kodu', 1, 'Modality code'),
    ('etiket', 'Alan', 1, 'Field'),
    ('etiket', 'İptal Nedeni', 1, 'Cancellation reason'),
    ('etiket', 'SKT', 1, 'Expiry date'),
    ('etiket', 'Talep No', 1, 'Request No'),
    ('etiket', 'Yapan', 1, 'Performed by'),
    ('etiket', 'Zorunlu', 1, 'Required'),
    ('etiket', 'Adımlar', 1, 'Steps'),
    ('etiket', 'Tarih & Saat', 1, 'Date & time'),
    ('etiket', 'Yürürlük', 1, 'Effective from'),
    ('etiket', 'Hareket', 1, 'Movement'),
    ('etiket', 'Gün', 1, 'Day'),
    ('etiket', 'Güvenlik', 1, 'Security'),
    ('etiket', 'Model', 1, 'Model'),
    ('etiket', 'Laboratuvar', 1, 'Laboratory'),
    ('etiket', 'Kabin', 1, 'Cubicle'),
    ('etiket', 'Tutanak', 1, 'Minutes'),
    ('etiket', 'Adet', 1, 'Quantity'),
    ('etiket', 'Planlama', 1, 'Planning'),
    ('etiket', 'Cam & Optik', 1, 'Lens & optics'),
    ('etiket', 'Lens Değerleri', 1, 'Lens values'),
    ('etiket', 'Çalışan', 1, 'Worker'),
    ('etiket', 'Atama & Sözleşme', 1, 'Assignment & contract'),
    ('etiket', 'Hakediş', 1, 'Earnings'),
    ('etiket', 'Pozisyon', 1, 'Position'),
    ('etiket', 'Eşik', 1, 'Threshold'),
    ('etiket', 'Tip', 1, 'Type'),
    ('etiket', 'Makbuz No', 1, 'Receipt No'),
    ('etiket', 'Periyot', 1, 'Period'),
    ('etiket', 'Çalışma Zamanları', 1, 'Working hours'),
    ('etiket', 'Vekâlet', 1, 'Acting assignment'),
    ('etiket', 'Kaynak Id', 1, 'Source Id'),
    ('etiket', 'Sağlayıcı', 1, 'Provider'),
    ('etiket', 'Koşul', 1, 'Condition'),
    ('etiket', 'Bekleyen', 1, 'Pending'),
    ('etiket', 'Tip Kodu', 1, 'Type code'),
    ('etiket', 'Hekim Id', 1, 'Physician Id'),
    ('etiket', 'Kurum Id', 1, 'Institution Id'),
    ('etiket', 'Doviz', 1, 'Currency'),
    ('etiket', 'Şikâyet', 1, 'Complaint'),
    ('etiket', 'Sayım', 1, 'Stock count'),
    ('etiket', 'Unvan', 1, 'Title'),
    ('etiket', 'Cinsiyet', 1, 'Gender'),
    ('etiket', 'Fiyatlandırma', 1, 'Pricing'),
    ('etiket', 'İl', 1, 'Province'),
    ('etiket', 'Konum / Zimmet', 1, 'Location / Assignment'),
    ('etiket', 'Bulgu', 1, 'Finding'),
    ('etiket', 'Hazırlayan', 1, 'Prepared by'),
    ('etiket', 'Para Birimi', 1, 'Currency'),
    ('etiket', 'Çıktı Ayarları', 1, 'Print settings'),
    ('etiket', 'ICD', 1, 'ICD'),
    ('etiket', 'Test', 1, 'Test'),
    ('etiket', 'Davranış', 1, 'Behaviour'),
    ('etiket', 'Muhasebe', 1, 'Accounting'),
    ('etiket', 'İlgili Kayıt', 1, 'Related record'),
    ('etiket', 'Gösterge Kartı', 1, 'Indicator card'),
    ('etiket', 'Etken Madde', 1, 'Active ingredient'),
    ('etiket', 'Basamak', 1, 'Step'),
    ('etiket', 'İstem Bilgisi', 1, 'Order details'),
    ('etiket', 'Yol', 1, 'Route'),
    ('etiket', 'Garanti', 1, 'Warranty'),
    ('etiket', 'Atama & SLA', 1, 'Assignment & SLA'),
    ('etiket', 'Bakanlık', 1, 'Ministry'),
    ('etiket', 'Zamanlama', 1, 'Scheduling'),
    ('etiket', 'Personel Id', 1, 'Employee Id'),
    ('etiket', 'Stok Id', 1, 'Item Id'),
    ('etiket', '＋ Yeni', 1, 'New'),
    ('etiket', '🧾 Onay Zinciri', 1, 'Approval chain'),
    ('etiket', 'Tekrar', 1, 'Repeat'),
    ('etiket', 'Triyaj', 1, 'Triage'),
    ('etiket', 'Salon', 1, 'Theatre'),
    ('etiket', 'İsteyen Hekim', 1, 'Ordering physician'),
    ('etiket', 'Şube (boş = tümü)', 1, 'Branch (blank = all)'),
    ('etiket', 'Şablon Adı', 1, 'Template name'),
    ('etiket', 'Slot (dk)', 1, 'Slot (min)'),
    ('etiket', 'Temsilci', 1, 'Representative'),
    ('etiket', 'Notlar', 1, 'Notes'),
    ('etiket', 'İlçe', 1, 'District'),
    ('etiket', 'Demirbaş No', 1, 'Asset No'),
    ('etiket', 'Marka', 1, 'Brand'),
    ('etiket', 'Ödenen', 1, 'Paid'),
    ('etiket', 'Son Kullanım', 1, 'Expiry'),
    ('etiket', 'Teslim Alan', 1, 'Received by'),
    ('etiket', 'Değer', 1, 'Value'),
    ('etiket', 'Kurallar', 1, 'Rules'),
    ('etiket', 'Ölçek', 1, 'Scale'),
    ('etiket', 'Skor', 1, 'Score'),
    ('etiket', 'Hedef & Plan', 1, 'Target & plan'),
    ('etiket', 'Ödeyen & Rapor', 1, 'Payer & report'),
    ('etiket', 'Reçete No', 1, 'Prescription No'),
    ('etiket', 'Marka / Model', 1, 'Make / Model'),
    ('etiket', 'Tespit & Öneri', 1, 'Finding & recommendation'),
    ('etiket', 'Bildirim & Kök neden', 1, 'Notification & root cause'),
    ('etiket', 'Seviye', 1, 'Level'),
    ('etiket', 'Neden', 1, 'Reason'),
    ('etiket', 'Kodlar & Bildirim', 1, 'Codes & notification'),
    ('etiket', 'Ön Ek', 1, 'Prefix'),
    ('etiket', 'Başlama No', 1, 'Start No'),
    ('etiket', 'Oluşturma', 1, 'Created'),
    ('etiket', 'İstem No', 1, 'Order No'),
    ('etiket', 'Sipariş', 1, 'Purchase order'),
    ('etiket', 'KDV %', 1, 'VAT %'),
    ('etiket', 'İstek No', 1, 'Request No'),
    ('etiket', 'Onay', 1, 'Approval'),
    ('etiket', 'Teslim & Ücret', 1, 'Delivery & fee'),
    ('etiket', 'SLA', 1, 'SLA'),
    ('etiket', 'Saat Ücreti', 1, 'Hourly rate'),
    ('etiket', 'Fason', 1, 'Outsourced'),
    ('etiket', 'Satır', 1, 'Line'),
    ('etiket', 'Ödeyen & Refakat', 1, 'Payer & companion'),
    ('etiket', 'Cari Id', 1, 'Account Id'),
    ('etiket', 'Kanal Kodu', 1, 'Channel code'),
    ('etiket', 'Servis', 1, 'Service'),
    ('etiket', 'İstem Id', 1, 'Order Id'),
    ('etiket', 'Kaynak Kodu', 1, 'Source code'),
    ('etiket', 'Tetkik Id', 1, 'Test Id'),
    ('etiket', 'Tur Kodu', 1, 'Type code'),
    ('etiket', 'Rol Kodu', 1, 'Role code'),
    ('etiket', 'Yatış Id', 1, 'Admission Id'),
    ('etiket', '✖ İptal Et', 1, 'Cancel'),
    ('etiket', '✖ Reddet', 1, 'Reject'),
    ('etiket', 'İptal Et', 1, 'Cancel'),
    ('etiket', 'Kapanış', 1, 'Closing'),
    ('etiket', 'Tedavi', 1, 'Treatment'),
    ('etiket', 'ICD-10', 1, 'ICD-10'),
    ('etiket', 'Bildiren', 1, 'Reported by'),
    ('etiket', 'Komplikasyon', 1, 'Complication'),
    ('etiket', 'Bulgular', 1, 'Findings'),
    ('etiket', 'Ön Hazırlık', 1, 'Preparation'),
    ('etiket', 'Alt konu', 1, 'Sub-subject'),
    ('etiket', 'Değerlendiren', 1, 'Assessed by'),
    ('etiket', 'Kanal & Kota', 1, 'Channel & quota'),
    ('etiket', 'Soyad', 1, 'Surname'),
    ('etiket', 'Cep Telefonu', 1, 'Mobile phone'),
    ('etiket', 'Adres Tipi', 1, 'Address type'),
    ('etiket', 'Ana Rol', 1, 'Primary role'),
    ('etiket', 'Yönetici', 1, 'Manager'),
    ('etiket', 'Prim Rolü', 1, 'Commission role'),
    ('etiket', 'Amaç', 1, 'Purpose'),
    ('etiket', 'Sözleşme No', 1, 'Contract No'),
    ('etiket', 'Fiyat Listesi', 1, 'Price list'),
    ('etiket', 'SKRS Kodu', 1, 'SKRS code'),
    ('etiket', 'Son Mesaj', 1, 'Last message'),
    ('etiket', 'Ödeyen Kurum', 1, 'Payer institution'),
    ('etiket', 'Net', 1, 'Net'),
    ('etiket', 'Taksit', 1, 'Instalment'),
    ('etiket', 'Yapılan', 1, 'Completed'),
    ('etiket', 'Kalite Kontrol', 1, 'Quality control'),
    ('etiket', 'Anestezi', 1, 'Anaesthesia'),
    ('etiket', 'Tutanak No', 1, 'Minutes No'),
    ('etiket', 'Doz Girdileri', 1, 'Dose entries'),
    ('etiket', 'Son Sonuç', 1, 'Last result'),
    ('etiket', 'Fiyat', 1, 'Price'),
    ('etiket', 'Çarpan', 1, 'Multiplier'),
    ('etiket', 'Fizyoterapist', 1, 'Physiotherapist'),
    ('etiket', 'Ünite', 1, 'Unit'),
    ('etiket', 'Üretici', 1, 'Manufacturer'),
    ('etiket', 'İşyeri hekimi', 1, 'Occupational physician'),
    ('etiket', 'Öykü', 1, 'History'),
    ('etiket', 'Doğrulandı', 1, 'Verified'),
    ('etiket', 'Ödeme', 1, 'Payment'),
    ('etiket', 'Tarih / Saat', 1, 'Date / Time'),
    ('etiket', 'Tahmini Tutar', 1, 'Estimated amount'),
    ('etiket', 'Sağlık Olgusu', 1, 'Health case'),
    ('etiket', 'Pay', 1, 'Share'),
    ('etiket', 'LOINC', 1, 'LOINC'),
    ('etiket', 'Dış Laboratuvar', 1, 'External laboratory'),
    ('etiket', 'Çevrim', 1, 'Conversion'),
    ('etiket', 'Gövde', 1, 'Body'),
    ('etiket', 'Kesinti', 1, 'Deduction'),
    ('etiket', 'Takip No', 1, 'Tracking No'),
    ('etiket', 'Klinik Bilgi', 1, 'Clinical information'),
    ('etiket', 'Aciklama', 1, 'Description'),
    ('etiket', 'PACS', 1, 'PACS'),
    ('etiket', 'Yerleşim / DICOM', 1, 'Layout / DICOM'),
    ('etiket', 'Klasör', 1, 'Folder'),
    ('etiket', 'Kayıt Id', 1, 'Record Id'),
    ('etiket', 'Varsayılanlar', 1, 'Defaults'),
    ('etiket', 'Muayene Id', 1, 'Examination Id'),
    ('etiket', 'Süreç', 1, 'Process'),
    ('etiket', 'SKRS', 1, 'SKRS'),
    ('etiket', 'Uygunsuzluk', 1, 'Nonconformity'),
    ('etiket', 'Soğuk Zincir', 1, 'Cold chain'),
    ('etiket', 'Erişim No', 1, 'Accession No'),
    ('etiket', 'Raporlama', 1, 'Reporting'),
    ('etiket', 'İşçilik', 1, 'Labour'),
    ('etiket', 'İş Merkezi', 1, 'Work centre'),
    ('etiket', 'Oda', 1, 'Room'),
    ('etiket', 'Kurallar & Ücret', 1, 'Rules & fee'),
    ('etiket', 'Bekleme (gün)', 1, 'Waiting (days)'),
    ('etiket', 'Teslim Eden', 1, 'Delivered by'),
    ('etiket', 'Satır Id', 1, 'Line Id'),
    ('etiket', 'Aktif Kodu', 1, 'Active code'),
    ('etiket', 'Gecikme (gün)', 1, 'Delay (days)'),
    ('etiket', 'Ortam', 1, 'Environment'),
    ('etiket', 'Göz Kodu', 1, 'Eye code'),
    ('etiket', 'Cihaz Id', 1, 'Device Id'),
    ('etiket', 'TL Tutar', 1, 'Amount (TRY)'),
    ('etiket', 'Hane', 1, 'Decimals'),
    ('etiket', 'Elle Girilir', 1, 'Entered manually'),
    ('etiket', 'Kategori Id', 1, 'Category Id'),
    ('etiket', 'Accession', 1, 'Accession'),
    ('etiket', 'Müşteri Id', 1, 'Customer Id'),
    ('etiket', '✖ İptal', 1, 'Cancel'),
    ('etiket', 'XML Kaydet', 1, 'Save XML'),
    ('etiket', '📤 Onaya Gönder', 1, 'Send for approval'),
    ('etiket', 'Çıkış Şekli', 1, 'Discharge type'),
    ('etiket', 'Hedef Bölüm', 1, 'Target department'),
    ('etiket', 'Cerrah', 1, 'Surgeon'),
    ('etiket', 'Gecikme Nedeni', 1, 'Delay reason'),
    ('etiket', 'Madde', 1, 'Item'),
    ('etiket', 'Uyum', 1, 'Compliance'),
    ('etiket', 'Kayıt No', 1, 'Record No'),
    ('etiket', 'Alt Sınır', 1, 'Lower limit'),
    ('etiket', 'Üst Sınır', 1, 'Upper limit'),
    ('etiket', 'Tamamlanma', 1, 'Completion'),
    ('etiket', 'Çıkış Fişi', 1, 'Issue voucher'),
    ('etiket', 'Özet', 1, 'Summary'),
    ('etiket', 'Musteri', 1, 'Customer'),
    ('etiket', 'Fatura Unvani', 1, 'Invoice title'),
    ('etiket', 'Sınıf', 1, 'Class'),
    ('etiket', 'Yakınlık', 1, 'Relationship'),
    ('etiket', 'Doğum Tarihi', 1, 'Date of birth'),
    ('etiket', 'Hekim Bilgisi', 1, 'Physician details'),
    ('etiket', 'Kurum Türü', 1, 'Institution type'),
    ('etiket', 'Kullanıcı Kodu', 1, 'User code'),
    ('etiket', 'Üst Kategori', 1, 'Parent category'),
    ('etiket', 'Lokasyon', 1, 'Location'),
    ('etiket', 'Diş', 1, 'Tooth'),
    ('etiket', 'Ödeme Tarihi', 1, 'Payment date'),
    ('etiket', 'Tüp', 1, 'Tube'),
    ('etiket', 'Panik Alt', 1, 'Panic low'),
    ('etiket', 'Panik Üst', 1, 'Panic high'),
    ('etiket', 'Cihaz Birimi', 1, 'Analyser unit'),
    ('etiket', 'Ofset', 1, 'Offset'),
    ('etiket', 'Alt Kod', 1, 'Sub code'),
    ('etiket', 'Study UID', 1, 'Study UID'),
    ('etiket', 'Bolum', 1, 'Department'),
    ('etiket', 'Bağlar', 1, 'Links'),
    ('etiket', 'Rapor Id', 1, 'Report Id'),
    ('etiket', 'Görüntü Bağlantısı', 1, 'Image link'),
    ('etiket', 'Sıklık', 1, 'Frequency'),
    ('etiket', 'Bina', 1, 'Building'),
    ('etiket', 'Kat', 1, 'Floor'),
    ('etiket', 'Bölüm Kodu', 1, 'Department code'),
    ('etiket', 'Kimliksiz', 1, 'De-identified'),
    ('etiket', 'Geliş Şekli', 1, 'Arrival type'),
    ('etiket', 'Çıkış Saati', 1, 'Discharge time'),
    ('etiket', 'Yatak Kodu', 1, 'Bed code'),
    ('etiket', 'Tedarikci', 1, 'Supplier'),
    ('etiket', 'Aday', 1, 'Candidate'),
    ('etiket', 'Kisi', 1, 'Person'),
    ('etiket', 'ÜTS Kurum No', 1, 'ÜTS institution No'),
    ('etiket', 'e-Fatura mukellefi', 1, 'e-Invoice registered'),
    ('etiket', 'Alias / e-Posta', 1, 'Alias / e-mail'),
    ('etiket', 'Sektör', 1, 'Sector'),
    ('etiket', 'Kisi Kodu', 1, 'Person code'),
    ('etiket', 'Gorev', 1, 'Position'),
    ('etiket', 'Sicil No', 1, 'Employee No'),
    ('etiket', 'Bitiş (süreli ise)', 1, 'End (if temporary)'),
    ('etiket', 'Önerilen', 1, 'Recommended'),
    ('etiket', 'Çalışma Şekli', 1, 'Employment type'),
    ('etiket', 'Uyruğu', 1, 'Nationality'),
    ('etiket', 'Medeni Hal', 1, 'Marital status'),
    ('etiket', 'Kan Grubu', 1, 'Blood group'),
    ('etiket', 'Öğle Bitiş', 1, 'Lunch end'),
    ('etiket', 'Branş', 1, 'Specialty'),
    ('etiket', 'Hasta Bilgisi', 1, 'Patient details'),
    ('etiket', 'Kurum / Ödeyen', 1, 'Institution / payer'),
    ('etiket', 'Parola Tarihi', 1, 'Password date'),
    ('etiket', 'Son Giriş', 1, 'Last sign-in'),
    ('etiket', 'Sözleşmeler', 1, 'Contracts'),
    ('etiket', 'Cari (tedarikçi)', 1, 'Account (supplier)'),
    ('etiket', 'Sözleşme TAT (gün)', 1, 'Contract TAT (days)'),
    ('etiket', 'Kurye Firması', 1, 'Courier company'),
    ('etiket', 'Yetkili', 1, 'Contact person'),
    ('etiket', 'Karar No', 1, 'Decision No'),
    ('etiket', 'Tetkik Kodu', 1, 'Test code'),
    ('etiket', 'Tetkik Adı', 1, 'Test name'),
    ('etiket', 'Çalışma Düzeni', 1, 'Work pattern'),
    ('etiket', 'Çalışma Günleri', 1, 'Working days'),
    ('etiket', 'İsteyen Kurum', 1, 'Ordering institution'),
    ('etiket', 'Kontrast', 1, 'Contrast'),
    ('etiket', 'Kritik Bulgu', 1, 'Critical finding'),
    ('etiket', 'AE Title', 1, 'AE Title'),
    ('etiket', 'Hazırlık Talimatı', 1, 'Preparation instructions'),
    ('etiket', 'Özel Uyarı', 1, 'Special warning'),
    ('etiket', 'Sablon Adi', 1, 'Template name'),
    ('etiket', 'Bagli Tetkik', 1, 'Linked test'),
    ('etiket', 'Varsayilan', 1, 'Default'),
    ('etiket', 'Kullanim', 1, 'Usage'),
    ('etiket', 'Sira', 1, 'Order'),
    ('etiket', 'Alan Kodu', 1, 'Field code'),
    ('etiket', 'Kutu', 1, 'Box'),
    ('etiket', 'Etken / Ürün', 1, 'Agent / product'),
    ('etiket', 'Reaksiyon', 1, 'Reaction'),
    ('etiket', 'Kayıt Muayenesi', 1, 'Registration examination'),
    ('etiket', 'Ret Nedeni', 1, 'Rejection reason'),
    ('etiket', 'SKRS Listesi', 1, 'SKRS list'),
    ('etiket', 'SKRS Karşılığı', 1, 'SKRS equivalent'),
    ('etiket', 'Geliş', 1, 'Arrival'),
    ('etiket', 'SLA (dk)', 1, 'SLA (min)'),
    ('etiket', 'SLA Aşıldı', 1, 'SLA breached'),
    ('etiket', 'Tesis Kodu', 1, 'Facility code'),
    ('etiket', 'DICOM AE', 1, 'DICOM AE'),
    ('etiket', 'Rapor Şablonu', 1, 'Report template'),
    ('etiket', 'Ücret Modeli', 1, 'Fee model'),
    ('etiket', 'Tarife', 1, 'Tariff'),
    ('etiket', 'Aylık Sabit', 1, 'Monthly fixed'),
    ('etiket', 'Acil Ek %', 1, 'Emergency surcharge %'),
    ('etiket', 'Sorumlu Hekim', 1, 'Attending physician'),
    ('etiket', 'Tahmini Çıkış', 1, 'Estimated discharge'),
    ('etiket', 'Refakatçi', 1, 'Companion'),
    ('etiket', 'Sözel order', 1, 'Verbal order'),
    ('etiket', 'Nabız', 1, 'Pulse'),
    ('etiket', 'Solunum', 1, 'Respiration'),
    ('etiket', 'Gözlem', 1, 'Observation'),
    ('etiket', 'Oda Kodu', 1, 'Room code'),
    ('etiket', 'Yatak Ücreti (hizmet)', 1, 'Bed charge (service)'),
    ('etiket', 'Uygulanan', 1, 'Administered'),
    ('etiket', 'Uygulayan', 1, 'Administered by'),
    ('etiket', 'Atlama Nedeni', 1, 'Omission reason'),
    ('etiket', 'Elle doğrulandı', 1, 'Manually verified'),
    ('etiket', 'Eklendi', 1, 'Added'),
    ('etiket', 'Randevu (plan)', 1, 'Appointment (scheduled)'),
    ('etiket', 'Dış Hekim', 1, 'External physician'),
    ('etiket', 'Hizmet Id', 1, 'Service Id'),
    ('etiket', 'Rapor Onayı', 1, 'Report approval'),
    ('etiket', 'İstek Id', 1, 'Request Id'),
    ('etiket', 'Protokol No', 1, 'Protocol No'),
    ('etiket', 'Geçici Ad', 1, 'Temporary name'),
    ('etiket', 'Geliş (kapı) Saati', 1, 'Arrival (door) time'),
    ('etiket', 'Geliş Notu', 1, 'Arrival note'),
    ('etiket', 'Triyaj Düzeyi', 1, 'Triage level'),
    ('etiket', 'Triyaj Saati', 1, 'Triage time'),
    ('etiket', 'Triyajı Yapan', 1, 'Triaged by'),
    ('etiket', 'Hekimin Gördüğü An', 1, 'Time seen by physician'),
    ('etiket', 'Adli Vaka', 1, 'Forensic case'),
    ('etiket', 'Çıkış Tanısı (ICD-10)', 1, 'Discharge diagnosis (ICD-10)'),
    ('etiket', 'Çıkış Notu / Öneriler', 1, 'Discharge note / recommendations'),
    ('etiket', 'Çağrı Türü', 1, 'Call type'),
    ('etiket', 'Hedef Kişi', 1, 'Target person'),
    ('etiket', 'Yanıt', 1, 'Response'),
    ('etiket', 'Yanıtlayan', 1, 'Answered by'),
    ('etiket', 'Çağrılar', 1, 'Calls'),
    ('etiket', 'Referans No', 1, 'Reference No'),
    ('etiket', 'Satış Fiyat Listesi', 1, 'Sales price list'),
    ('etiket', 'Alış Fiyat Listesi', 1, 'Purchase price list'),
    ('etiket', 'Web', 1, 'Web'),
    ('etiket', 'İlk Temas', 1, 'First contact'),
    ('etiket', 'Alt Sektör', 1, 'Sub-sector'),
    ('etiket', 'Ozel Kod', 1, 'Custom code'),
    ('etiket', 'Bagli Cari', 1, 'Linked account'),
    ('etiket', '2. E-posta', 1, 'Second e-mail'),
    ('etiket', 'Geçmiş', 1, 'History'),
    ('etiket', 'Ev Telefonu', 1, 'Home phone'),
    ('etiket', 'E-posta (İş)', 1, 'E-mail (work)'),
    ('etiket', 'E-posta (Kişisel)', 1, 'E-mail (personal)'),
    ('etiket', 'Çalıştığı Şube', 1, 'Assigned branch'),
    ('etiket', 'Unvan (serbest)', 1, 'Title (free text)'),
    ('etiket', 'Kadro Geçmişi', 1, 'Position history'),
    ('etiket', 'Prim Rolleri', 1, 'Commission roles'),
    ('etiket', 'e-Posta', 1, 'E-mail'),
    ('etiket', 'Acil Durumda Aranacak Kişiler', 1, 'Emergency contacts'),
    ('etiket', 'Doğum Yeri', 1, 'Place of birth'),
    ('etiket', 'İşe Giriş Tarihi', 1, 'Hire date'),
    ('etiket', 'İşten Çıkış Tarihi', 1, 'Termination date'),
    ('etiket', 'Vardiya Türü', 1, 'Shift type'),
    ('etiket', 'SGK Başlama Tarihi', 1, 'SGK start date'),
    ('etiket', 'Sözleşme Türü', 1, 'Contract type'),
    ('etiket', 'Deneme Süresi', 1, 'Probation period'),
    ('etiket', 'SGK Sicil No', 1, 'SGK registration No'),
    ('etiket', 'Meslek Kodu', 1, 'Occupation code'),
    ('etiket', 'Özlük', 1, 'Personnel file'),
    ('etiket', 'İzinler', 1, 'Leave'),
    ('etiket', 'Tarih/Yıl', 1, 'Date / year'),
    ('etiket', 'Eğitim / Sertifika', 1, 'Training / certificate'),
    ('etiket', 'Öğle Başl.', 1, 'Lunch start'),
    ('etiket', 'Aralık (dk)', 1, 'Interval (min)'),
    ('etiket', 'Günler (1 Pzt … 7 Paz)', 1, 'Days (1 Mon … 7 Sun)'),
    ('etiket', 'Randevuya Açık', 1, 'Bookable'),
    ('etiket', 'Randevu Ayarları', 1, 'Appointment settings'),
    ('etiket', 'Diploma / Tescil No', 1, 'Diploma / registration No'),
    ('etiket', 'Dogum Tarihi', 1, 'Date of birth'),
    ('etiket', 'Dogum Yeri', 1, 'Place of birth'),
    ('etiket', 'Meslek', 1, 'Occupation'),
    ('etiket', 'Kayıt Tipi', 1, 'Record type'),
    ('etiket', 'Pasaport No', 1, 'Passport No'),
    ('etiket', 'Ana Adı', 1, 'Mother''s name'),
    ('etiket', 'Baba Adı', 1, 'Father''s name'),
    ('etiket', 'Kimliksiz Hasta', 1, 'Unidentified patient'),
    ('etiket', 'Yabancı Hasta Türü', 1, 'Foreign patient type'),
    ('etiket', 'Ülkeye Giriş Tarihi', 1, 'Date of entry to country'),
    ('etiket', 'Vefat', 1, 'Deceased'),
    ('etiket', 'Vefat Tarihi', 1, 'Date of death'),
    ('etiket', 'Mahremiyet Notu', 1, 'Confidentiality note'),
    ('etiket', 'Kurum / Sigorta', 1, 'Institution / insurance'),
    ('etiket', 'Poliçe No', 1, 'Policy No'),
    ('etiket', 'Arayüz Dili', 1, 'Interface language'),
    ('etiket', 'Son Giriş IP', 1, 'Last sign-in IP'),
    ('etiket', 'Hatalı Giriş', 1, 'Failed sign-ins'),
    ('etiket', 'Kilit Bitişi', 1, 'Lock expires'),
    ('etiket', '2 Adımlı Doğrulama', 1, 'Two-factor authentication'),
    ('etiket', 'Varsayılan parola', 1, 'Default password'),
    ('etiket', 'Üst Rol', 1, 'Parent role'),
    ('etiket', 'Sistem Rolü', 1, 'System role'),
    ('etiket', 'Alt Kurum / Poliçe', 1, 'Sub-institution / policy'),
    ('etiket', 'SUT Listesi', 1, 'SUT list'),
    ('etiket', 'SGK Carisi', 1, 'SGK account'),
    ('etiket', 'Faturalama', 1, 'Billing'),
    ('etiket', 'Varsayılan Karşılama %', 1, 'Default coverage %'),
    ('etiket', 'Üst Birim', 1, 'Parent unit'),
    ('etiket', 'Randevusuz Kabul (acil / lab)', 1, 'Walk-in admission (emergency / lab)'),
    ('etiket', 'Üst Görev', 1, 'Parent position'),
    ('etiket', 'Sonuç Kanalı', 1, 'Result channel'),
    ('etiket', 'Dış Lab Kodu', 1, 'External lab code'),
    ('etiket', 'Dış Lab Test Adı', 1, 'External lab test name'),
    ('etiket', 'Anlaşma Fiyatı', 1, 'Contract price'),
    ('etiket', 'TAT (gün)', 1, 'TAT (days)'),
    ('etiket', 'Ad Soyad', 1, 'Full name'),
    ('etiket', 'Kimlik No', 1, 'ID number'),
    ('etiket', 'İşe Giriş', 1, 'Hire date'),
    ('etiket', 'Görev / unvan', 1, 'Position / title'),
    ('etiket', 'Kaynak', 1, 'Source'),
    ('etiket', 'Yaş', 1, 'Age'),
    ('etiket', 'Yaş/C', 1, 'Age/Sex'),
    ('etiket', 'İsteyen', 1, 'Ordered by'),
    ('etiket', 'Bölümler', 1, 'Departments'),
    ('etiket', 'Açık', 1, 'Open'),
    ('etiket', 'Birim', 1, 'Unit'),
    ('etiket', 'Hekim', 1, 'Physician'),
    ('etiket', 'Uyruk', 1, 'Nationality'),
    ('etiket', 'Yan Rol', 1, 'Secondary role'),
    ('etiket', 'Yan Roller', 1, 'Secondary roles'),
    ('etiket', 'Kullanıcı Rolleri', 1, 'User roles'),
    ('etiket', 'Ek roller', 1, 'Additional roles'),
    ('etiket', 'İşten Çıkış', 1, 'Termination date'),
    ('etiket', 'SGK Başlama', 1, 'SGK start'),
    ('etiket', 'Ad', 1, 'Name'),
    ('etiket', 'Şube', 1, 'Branch'),
    ('etiket', 'Rol', 1, 'Role'),
    ('etiket', 'Durum', 1, 'Status'),
    ('etiket', 'Telefon', 1, 'Phone'),
    ('etiket', 'Cep', 1, 'Mobile'),
    ('etiket', 'E-posta', 1, 'E-mail'),
    ('etiket', 'Adres', 1, 'Address'),
    ('etiket', 'Fotoğraf', 1, 'Photo'),
    ('etiket', 'İş Bilgileri', 1, 'Employment'),
    ('etiket', 'Resim / Doküman', 1, 'Image / Document'),
    ('etiket', 'İletişim', 1, 'Contact'),
    ('menu', 'Seanslar', 1, 'Sessions'),
    ('menu', 'Dökümler', 1, 'Exports'),
    ('menu', 'Medula Hasta Kabul / Provizyon', 1, 'MEDULA admission / authorisation'),
    ('menu', 'Bu şubenin kurum profili', 1, 'Institution profile of this branch'),
    ('menu', 'Acil — Triyaj ve Kabul', 1, 'Emergency — triage and admission'),
    ('menu', 'Acil — Takip Panosu', 1, 'Emergency — tracking board'),
    ('menu', 'Acil — Çağrılar', 1, 'Emergency — calls'),
    ('menu', 'Acil Yatakları', 1, 'Emergency beds'),
    ('menu', 'Ameliyat Planı', 1, 'Surgery schedule'),
    ('menu', 'Masa Çizelgesi', 1, 'Table schedule'),
    ('menu', 'Bekleyen Ameliyat Talepleri', 1, 'Pending surgery requests'),
    ('menu', 'Ameliyathane Salonları', 1, 'Operating theatres'),
    ('menu', 'Cihaz Envanteri', 1, 'Device inventory'),
    ('menu', 'Kalibrasyon & Güvenlik Testi', 1, 'Calibration & safety testing'),
    ('menu', 'İş Emirleri (Bakım & Arıza)', 1, 'Work orders (maintenance & faults)'),
    ('menu', 'Operatör Panosu', 1, 'Operator board'),
    ('menu', 'Giden Arama · Kampanya', 1, 'Outbound calls · campaign'),
    ('menu', 'Çağrı Kayıtları', 1, 'Call records'),
    ('menu', 'Çağrı (kart)', 1, 'Call (card)'),
    ('menu', 'Kampanya Kişileri', 1, 'Campaign contacts'),
    ('menu', 'Süpervizör Panosu', 1, 'Supervisor board'),
    ('menu', 'Kalite Değerlendirmeleri', 1, 'Quality assessments'),
    ('menu', 'Konu Ağacı', 1, 'Subject tree'),
    ('menu', 'Kuyruklar', 1, 'Queues'),
    ('menu', 'Agentlar', 1, 'Agents'),
    ('menu', 'Santral · IVR · Kanallar', 1, 'PBX · IVR · channels'),
    ('menu', 'Diş Kliniği Günlük Akış', 1, 'Dental clinic daily flow'),
    ('menu', 'Diş Hastaları', 1, 'Dental patients'),
    ('menu', 'Tedavi Planları', 1, 'Treatment plans'),
    ('menu', 'Lab İş Emirleri', 1, 'Lab work orders'),
    ('menu', 'Ödeme Planları', 1, 'Payment plans'),
    ('menu', 'Ünitler', 1, 'Dental units'),
    ('menu', 'Laboratuvarlar', 1, 'Laboratories'),
    ('menu', 'Eczacı Kontrolü', 1, 'Pharmacist review'),
    ('menu', 'Ünite Doz', 1, 'Unit dose'),
    ('menu', 'Hazırlama (Kemoterapi / TPN)', 1, 'Compounding (chemotherapy / TPN)'),
    ('menu', 'Servis İadeleri', 1, 'Ward returns'),
    ('menu', 'İmha Tutanakları', 1, 'Destruction records'),
    ('menu', 'Kontrollü İlaç Defteri', 1, 'Controlled drug register'),
    ('menu', 'Miad & Tüketim', 1, 'Expiry & consumption'),
    ('menu', 'Form Şablonları', 1, 'Form templates'),
    ('menu', 'Form Kütüphanesi', 1, 'Form library'),
    ('menu', 'Doldurulan Formlar', 1, 'Completed forms'),
    ('menu', 'Form Kuralları (tetikleyiciler)', 1, 'Form rules (triggers)'),
    ('menu', 'Ünite Panosu', 1, 'Unit board'),
    ('menu', 'FTR Değerlendirmeleri', 1, 'PMR assessments'),
    ('menu', 'Tedavi Programları (Kür)', 1, 'Treatment programmes (course)'),
    ('menu', 'Tedavi Programı (kart)', 1, 'Treatment programme (card)'),
    ('menu', 'Ölçekler', 1, 'Scales'),
    ('menu', 'Üniteler & Kabinler', 1, 'Units & cubicles'),
    ('menu', 'Göz Ünitesi Akışı', 1, 'Eye unit flow'),
    ('menu', 'Göz Muayeneleri', 1, 'Eye examinations'),
    ('menu', 'Göz Görüntüleme', 1, 'Ophthalmic imaging'),
    ('menu', 'Göz İşlemleri', 1, 'Eye procedures'),
    ('menu', 'Gözlük Reçeteleri', 1, 'Spectacle prescriptions'),
    ('menu', 'Göz Hastalık Takibi', 1, 'Eye disease follow-up'),
    ('menu', 'Göz Hasta Özeti', 1, 'Eye patient summary'),
    ('menu', 'Kontakt Lens', 1, 'Contact lenses'),
    ('menu', 'İşlem Protokolleri', 1, 'Procedure protocols'),
    ('menu', 'Göz Cihazları', 1, 'Ophthalmic devices'),
    ('menu', 'Dikte Sözlüğü', 1, 'Dictation dictionary'),
    ('menu', 'Firma Panosu', 1, 'Company board'),
    ('menu', 'Periyodik Muayene Takvimi', 1, 'Periodic examination calendar'),
    ('menu', 'Çalışanlar', 1, 'Workers'),
    ('menu', 'Çalışan (kart)', 1, 'Worker (card)'),
    ('menu', 'Ek-2 Muayeneleri', 1, 'Annex-2 examinations'),
    ('menu', 'İşyeri Ziyaretleri', 1, 'Workplace visits'),
    ('menu', 'İş Kazası ve Olaylar', 1, 'Occupational accidents and incidents'),
    ('menu', 'Firmalar (İşverenler)', 1, 'Companies (employers)'),
    ('menu', 'İzin Talepleri', 1, 'Leave requests'),
    ('menu', 'İzin Bakiyeleri', 1, 'Leave balances'),
    ('menu', 'Personel Avansları', 1, 'Employee advances'),
    ('menu', 'Masraf Beyanları', 1, 'Expense claims'),
    ('menu', 'Belge Talepleri', 1, 'Document requests'),
    ('menu', 'Resmî Tatiller', 1, 'Public holidays'),
    ('menu', 'İzin Hakedişleri', 1, 'Leave accruals'),
    ('menu', 'Kadro Hareketleri', 1, 'Position movements'),
    ('menu', 'Çalışma Planları', 1, 'Work schedules'),
    ('menu', 'Çalışma Şablonları', 1, 'Schedule templates'),
    ('menu', 'İzin & İstisnalar', 1, 'Leave & exceptions'),
    ('menu', 'İskonto Onayı', 1, 'Discount approval'),
    ('menu', 'Hasta Avansları', 1, 'Patient deposits'),
    ('menu', 'Hakedişlerim', 1, 'My earnings'),
    ('menu', 'Klinik Kalite Göstergeleri', 1, 'Clinical quality indicators'),
    ('menu', 'Klinik Kalite Dönem Sonuçları', 1, 'Clinical quality period results'),
    ('menu', 'Klinik Kalite Kod Havuzu', 1, 'Clinical quality code pool'),
    ('menu', 'Medula Takipleri', 1, 'MEDULA follow-ups'),
    ('menu', 'Medula Hizmet Kayıtları', 1, 'MEDULA service records'),
    ('menu', 'e-Reçete (Medula)', 1, 'e-Prescription (MEDULA)'),
    ('menu', 'e-Rapor (Medula)', 1, 'e-Report (MEDULA)'),
    ('menu', 'Medula Fatura & Dönem', 1, 'MEDULA invoice & period'),
    ('menu', 'Medula Faturaları', 1, 'MEDULA invoices'),
    ('menu', 'Medula Dönemleri', 1, 'MEDULA periods'),
    ('menu', 'Medula Kesintileri', 1, 'MEDULA deductions'),
    ('menu', 'Medula Gönderim Kuyruğu & Ayarlar', 1, 'MEDULA submission queue & settings'),
    ('menu', 'Medula Çağrı Günlüğü', 1, 'MEDULA call log'),
    ('menu', 'Onayımdakiler', 1, 'Awaiting my approval'),
    ('menu', 'Onay Akışları', 1, 'Approval workflows'),
    ('menu', 'Onay Vekâletleri', 1, 'Approval delegations'),
    ('menu', 'Faturalarım', 1, 'My invoices'),
    ('menu', 'Cari Ekstrem', 1, 'Account statement'),
    ('menu', 'Satınalma Talepleri', 1, 'Purchase requests'),
    ('menu', 'Teklif / İhale', 1, 'Quotation / tender'),
    ('menu', 'Sipariş Takibi', 1, 'Order tracking'),
    ('menu', 'Mal Kabul (muayene tutanağı)', 1, 'Goods receipt (inspection report)'),
    ('menu', 'Fatura Kontrolü (üçlü eşleştirme)', 1, 'Invoice check (three-way match)'),
    ('menu', 'Tedarikçi Performansı', 1, 'Supplier performance'),
    ('menu', 'Bütçe Durumu', 1, 'Budget status'),
    ('menu', 'Servis Çağrıları', 1, 'Service calls'),
    ('menu', 'Servis İş Emirleri', 1, 'Service work orders'),
    ('menu', 'Teknisyen Çizelgesi', 1, 'Technician schedule'),
    ('menu', 'Ziyaretler', 1, 'Visits'),
    ('menu', 'Emanet Cihazlar', 1, 'Devices in custody'),
    ('menu', 'Müşteri Cihaz Parkı', 1, 'Customer device fleet'),
    ('menu', 'Servis Sözleşmeleri', 1, 'Service contracts'),
    ('menu', 'Teleradyoloji Çalışma Listesi', 1, 'Teleradiology worklist'),
    ('menu', 'Teleradyoloji Panosu', 1, 'Teleradiology board'),
    ('menu', 'Teleradyoloji Kurumları', 1, 'Teleradiology institutions'),
    ('menu', 'Teleradyoloji Dönem Faturası', 1, 'Teleradiology period invoice'),
    ('menu', 'Teleradyoloji Nöbet Çizelgesi', 1, 'Teleradiology on-call roster'),
    ('menu', 'Teleradyoloji Atama Kuralları', 1, 'Teleradiology assignment rules'),
    ('menu', 'Teleradyoloji Sözleşmeleri', 1, 'Teleradiology contracts'),
    ('menu', 'Teslim Kuyruğu', 1, 'Delivery queue'),
    ('menu', 'Gelen Raporlar', 1, 'Incoming reports'),
    ('menu', 'Bakanlık Gönderim Eksikleri', 1, 'Ministry submission gaps'),
    ('menu', 'Faturalar', 1, 'Invoices'),
    ('menu', 'Yatan Hastalar', 1, 'Inpatients'),
    ('menu', 'Yatak Panosu', 1, 'Bed board'),
    ('menu', 'Order Listesi', 1, 'Order list'),
    ('menu', 'Doz Kuyruğu', 1, 'Dose queue'),
    ('menu', 'Hemşire İzlem', 1, 'Nursing observations'),
    ('menu', 'Hizmet İcmali', 1, 'Service summary'),
    ('menu', 'Odalar', 1, 'Rooms'),
    ('menu', 'Kullanıcılar', 1, 'Users'),
    ('menu', 'Giriş Kayıtları', 1, 'Sign-in log'),
    ('menu', 'Firma / Şubeler', 1, 'Company / branches'),
    ('hata', 'YETKISIZ', 1, 'Your session is invalid or has expired.'),
    ('hata', 'YASAK', 1, 'You are not allowed to perform this action.'),
    ('hata', 'BULUNAMADI', 1, 'Record not found.'),
    ('hata', 'CAKISMA', 1, 'Another user changed this record.'),
    ('hata', 'SUNUCU', 1, 'An unexpected error occurred.')
on conflict (kapsam, anahtar, dil) do update set metin = excluded.metin,
    degistirme_tarihi = now();

do $$
declare v_en integer; v_tr integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    select count(*) into v_tr from public.ceviri where dil = 2;
    raise notice '849 tamam: ingilizce % satir, almanca % satir.', v_en, v_tr;
end $$;
