-- ============================================================================
--  Gentegre AI — DİŞ · FTR · RADYOLOJİ RAPOR EKRANLARI İNGİLİZCE (850)
--  850_ingilizce_sozluk_dis_ftr_radyoloji.sql
--
--  Kullanıcı: *"diş, FTR, radyoloji rapor ekranlarını da çevir"* (849'un
--  devamı; kalan modüller sırayla kapatılıyor).
--
--  İki kaynak birlikte çevrildi:
--    · katalog başlıkları (sunucu metadatası - kart/kolon/grup),
--    · ekranların İÇİNDEKİ sabit metinler (başlık, boş durum, buton,
--      yer tutucu) - bunlar `c()` ile sarıldı, çeviri buradan gelir.
--
--  ÇEVRİLMEYENLER (bilerek):
--    · Standart/mevzuat adları: SUT, SKRS, MEDULA, ÜTS, DICOM (MWL, WADO,
--      MSH-3…18, ORC-21, ACK), PACS, ICD-10, VAS, EHA/ROM, SLR, FABER,
--      Schober, BOP, CAL, DLP, CTDIvol, STL, Vita.
--    · Örnek klinik veri ve kısaltmalar: "MOD", "US-2", "Hotpack",
--      "MB 20,5 · DB 20 · P 21,5", "Artikain %4 + epi 1:100k",
--      "Peşinat 4.000 + 3 taksit" - bunlar metin değil, örnek değerdir.
--
--  Idempotent (`on conflict do update`).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin) values
    ('etiket', 'Plan No', 1, 'Plan No'),
    ('etiket', 'Varyant', 1, 'Variant'),
    ('etiket', 'İndirim', 1, 'Discount'),
    ('etiket', 'İnd.', 1, 'Disc.'),
    ('etiket', 'Hasta Onayı', 1, 'Patient consent'),
    ('etiket', 'Yüzey', 1, 'Surface'),
    ('etiket', 'Lab', 1, 'Lab'),
    ('etiket', 'Ünit', 1, 'Unit'),
    ('etiket', 'Tedavi Planı', 1, 'Treatment plan'),
    ('etiket', 'Plan Satırı', 1, 'Plan line'),
    ('etiket', 'Plan Satırları', 1, 'Plan lines'),
    ('etiket', 'Beklenen', 1, 'Expected'),
    ('etiket', 'Varsayılan Hekim', 1, 'Default physician'),
    ('etiket', 'Tedarikçi Cari', 1, 'Supplier account'),
    ('etiket', 'Kurye Günleri', 1, 'Courier days'),
    ('etiket', 'Peşinat', 1, 'Down payment'),
    ('etiket', 'Taksit Tutarı', 1, 'Instalment amount'),
    ('etiket', 'İlk Vade', 1, 'First due date'),
    ('etiket', 'Ana Plan (B için)', 1, 'Main plan (for B)'),
    ('etiket', 'Ödeme Seçeneği', 1, 'Payment option'),
    ('etiket', 'Proforma No', 1, 'Proforma No'),
    ('etiket', 'Onay Yöntemi', 1, 'Consent method'),
    ('etiket', 'Faz', 1, 'Phase'),
    ('etiket', 'Dişler (köprü)', 1, 'Teeth (bridge)'),
    ('etiket', 'Ücretlendirme', 1, 'Pricing'),
    ('etiket', 'Onam', 1, 'Consent'),
    ('etiket', 'Asistan', 1, 'Assistant'),
    ('etiket', 'Sterilizasyon Paketi', 1, 'Sterilisation pack'),
    ('etiket', 'Uygulama Notu', 1, 'Procedure note'),
    ('etiket', 'Hastaya Talimat', 1, 'Patient instructions'),
    ('etiket', 'Sonraki Seans Planı', 1, 'Next session plan'),
    ('etiket', 'Anestezi Türü', 1, 'Anaesthesia type'),
    ('etiket', 'Seans No', 1, 'Session No'),
    ('etiket', 'Seans no', 1, 'Session no'),
    ('etiket', 'Bu seansta tamamlandı', 1, 'Completed in this session'),
    ('etiket', 'Yapılan İşlemler', 1, 'Procedures performed'),
    ('etiket', 'Malzeme & Sarf', 1, 'Materials & consumables'),
    ('etiket', 'Malzeme / Sarf', 1, 'Materials / consumables'),
    ('etiket', 'İş Emri No', 1, 'Work order No'),
    ('etiket', 'İş Türü', 1, 'Job type'),
    ('etiket', 'İş Türü Kodu', 1, 'Job type code'),
    ('etiket', 'Diş / Üye', 1, 'Tooth / unit'),
    ('etiket', 'Renk (Vita)', 1, 'Shade (Vita)'),
    ('etiket', 'Ölçü Tipi', 1, 'Impression type'),
    ('etiket', 'Ek İstekler', 1, 'Additional requests'),
    ('etiket', 'Garanti Bitişi', 1, 'Warranty end'),
    ('etiket', 'Lab Fiyatı', 1, 'Lab price'),
    ('etiket', 'Lab Maliyeti', 1, 'Lab cost'),
    ('etiket', 'Hastaya Yansıyan', 1, 'Charged to patient'),
    ('etiket', 'Aşama Geçmişi', 1, 'Stage history'),
    ('etiket', 'Aşama Kodu', 1, 'Stage code'),
    ('etiket', 'Sarf Deposu', 1, 'Consumables warehouse'),
    ('etiket', 'Laboratuvar Adı', 1, 'Laboratory name'),
    ('etiket', 'Dijital (STL) alır', 1, 'Accepts digital (STL)'),
    ('etiket', 'Dijital', 1, 'Digital'),
    ('etiket', 'Portal Adresi', 1, 'Portal address'),
    ('etiket', 'SLA (iş günü)', 1, 'SLA (business days)'),
    ('etiket', 'SLA (gün)', 1, 'SLA (days)'),
    ('etiket', 'Lab Fiyat Listesi', 1, 'Lab price list'),
    ('etiket', 'Taksit Sayısı', 1, 'Number of instalments'),
    ('etiket', 'Ödeme Yöntemi', 1, 'Payment method'),
    ('etiket', 'Taksitler', 1, 'Instalments'),
    ('etiket', 'Geciken Taksit', 1, 'Overdue instalment'),
    ('etiket', 'Anlaşmalı Testler', 1, 'Contracted tests'),
    ('etiket', 'Cep Tel', 1, 'Mobile'),
    ('etiket', 'Aktif Plan', 1, 'Active plan'),
    ('etiket', 'Son Muayene', 1, 'Last examination'),
    ('etiket', 'Son Seans', 1, 'Last session'),
    ('etiket', 'Yapılan Tutar', 1, 'Completed amount'),
    ('etiket', 'İşlemler', 1, 'Procedures'),
    ('etiket', 'Malzeme · Renk', 1, 'Material · shade'),
    ('etiket', 'Gecikti', 1, 'Overdue'),
    ('etiket', 'Sonraki Randevu', 1, 'Next appointment'),
    ('etiket', 'Gönderim No', 1, 'Dispatch No'),
    ('etiket', 'Taşıma Kodu', 1, 'Shipment code'),
    ('etiket', 'Kurye', 1, 'Courier'),
    ('etiket', 'Dış Kabul No', 1, 'External receipt No'),
    ('etiket', 'Alış Faturası', 1, 'Purchase invoice'),
    ('etiket', 'Dış Lab Id', 1, 'External lab Id'),
    ('etiket', 'FTR Uzmanı', 1, 'PMR specialist'),
    ('etiket', 'FTR e-Rapor No', 1, 'PMR e-Report No'),
    ('etiket', 'FTR Rapor', 1, 'PMR report'),
    ('etiket', 'Rapor seans hakkı', 1, 'Sessions granted by report'),
    ('etiket', 'Kırmızı bayrak', 1, 'Red flag'),
    ('etiket', 'Kırmızı bayrak notu', 1, 'Red flag note'),
    ('etiket', 'Devamsız', 1, 'No-show'),
    ('etiket', 'Parametre', 1, 'Parameter'),
    ('etiket', 'VAS önce', 1, 'VAS before'),
    ('etiket', 'VAS sonra', 1, 'VAS after'),
    ('etiket', 'VAS ilk', 1, 'VAS initial'),
    ('etiket', 'VAS son', 1, 'VAS final'),
    ('etiket', 'VAS', 1, 'VAS'),
    ('etiket', 'VAS istirahat (0-10)', 1, 'VAS at rest (0-10)'),
    ('etiket', 'VAS aktivite (0-10)', 1, 'VAS on activity (0-10)'),
    ('etiket', 'VAS gece (0-10)', 1, 'VAS at night (0-10)'),
    ('etiket', 'Uzman', 1, 'Specialist'),
    ('etiket', 'Program Id', 1, 'Programme Id'),
    ('etiket', 'Program No', 1, 'Programme No'),
    ('etiket', 'Taraf (sağ/sol/bilateral)', 1, 'Side (right/left/bilateral)'),
    ('etiket', 'Sevk / kaynak', 1, 'Referral / source'),
    ('etiket', 'Şikayet', 1, 'Complaint'),
    ('etiket', 'Şikayet süresi', 1, 'Duration of complaint'),
    ('etiket', 'Ağrı karakteri', 1, 'Pain character'),
    ('etiket', 'Gece ağrısı', 1, 'Night pain'),
    ('etiket', 'Önceki tedavi', 1, 'Previous treatment'),
    ('etiket', 'Meslek / aktivite', 1, 'Occupation / activity'),
    ('etiket', 'Komorbidite (kalp pili, gebelik, malignite…)', 1, 'Comorbidity (pacemaker, pregnancy, malignancy…)'),
    ('etiket', 'Duyu', 1, 'Sensation'),
    ('etiket', 'Refleks', 1, 'Reflexes'),
    ('etiket', 'Motor', 1, 'Motor'),
    ('etiket', 'Postür', 1, 'Posture'),
    ('etiket', 'Yürüyüş / denge', 1, 'Gait / balance'),
    ('etiket', 'Özel testler (SLR, FABER, Schober…)', 1, 'Special tests (SLR, FABER, Schober…)'),
    ('etiket', 'Kısa vadeli hedef', 1, 'Short-term goal'),
    ('etiket', 'Orta vadeli hedef', 1, 'Medium-term goal'),
    ('etiket', 'Uzun vadeli hedef', 1, 'Long-term goal'),
    ('etiket', 'Program önerisi', 1, 'Programme recommendation'),
    ('etiket', 'Aktif °', 1, 'Active °'),
    ('etiket', 'Pasif °', 1, 'Passive °'),
    ('etiket', 'Norm °', 1, 'Normal °'),
    ('etiket', 'Kas gücü (0-5)', 1, 'Muscle strength (0-5)'),
    ('etiket', 'EHA (ROM) & Kas Gücü', 1, 'ROM & muscle strength'),
    ('etiket', 'Ölçekler', 1, 'Scales'),
    ('etiket', 'Seans sayısı', 1, 'Number of sessions'),
    ('etiket', 'Haftada seans', 1, 'Sessions per week'),
    ('etiket', 'Seans süresi (dk)', 1, 'Session length (min)'),
    ('etiket', 'Seans saati', 1, 'Session time'),
    ('etiket', 'Tahmini bitiş', 1, 'Estimated end'),
    ('etiket', 'Tahmini Bitiş', 1, 'Estimated end'),
    ('etiket', 'Ara değerlendirme seansı', 1, 'Interim assessment session'),
    ('etiket', 'Kalan yıllık hak', 1, 'Remaining annual entitlement'),
    ('etiket', 'Kalan Hak', 1, 'Remaining entitlement'),
    ('etiket', 'Ödeyen kurum', 1, 'Payer institution'),
    ('etiket', 'Ödeyen', 1, 'Payer'),
    ('etiket', 'Yapılan seans', 1, 'Sessions completed'),
    ('etiket', 'Tedavi yanıtı', 1, 'Treatment response'),
    ('etiket', 'Kür sonu notu', 1, 'End-of-course note'),
    ('etiket', 'Uygulama (SUT)', 1, 'Procedure (SUT)'),
    ('etiket', 'Uygulamalar (SUT)', 1, 'Procedures (SUT)'),
    ('etiket', 'Uygulamalar', 1, 'Procedures'),
    ('etiket', 'Seans (baş)', 1, 'Session (start)'),
    ('etiket', 'Seans (bit)', 1, 'Session (end)'),
    ('etiket', 'Egzersiz', 1, 'Exercise'),
    ('etiket', 'Egzersiz Programı', 1, 'Exercise programme'),
    ('etiket', 'Set × tekrar', 1, 'Sets × reps'),
    ('etiket', 'Aşama (baş)', 1, 'Stage (start)'),
    ('etiket', 'Aşama (bit)', 1, 'Stage (end)'),
    ('etiket', 'Ev programı uyumu', 1, 'Home programme adherence'),
    ('etiket', 'Uygulama notu', 1, 'Procedure note'),
    ('etiket', 'Hastaya talimat', 1, 'Patient instructions'),
    ('etiket', 'Yarım bırakma nedeni', 1, 'Reason for discontinuation'),
    ('etiket', 'Hasta imzası', 1, 'Patient signature'),
    ('etiket', 'Yapıldı', 1, 'Done'),
    ('etiket', 'Yapılmadıysa neden', 1, 'Reason if not performed'),
    ('etiket', 'Kapasite', 1, 'Capacity'),
    ('etiket', 'Cihazlar', 1, 'Devices'),
    ('etiket', 'Kabinler', 1, 'Cubicles'),
    ('etiket', 'Bölge Kodu', 1, 'Region code'),
    ('etiket', 'Sonraki Seans', 1, 'Next session'),
    ('etiket', 'Fzt Id', 1, 'Physiotherapist Id'),
    ('etiket', 'Accession No', 1, 'Accession No'),
    ('etiket', 'Dış Hekim (kayıtsız)', 1, 'External physician (unregistered)'),
    ('etiket', 'Cihaz listesine (MWL) gönder', 1, 'Send to modality worklist (MWL)'),
    ('etiket', 'Randevu SMS''i', 1, 'Appointment SMS'),
    ('etiket', 'Hazırlık talimatı verildi', 1, 'Preparation instructions given'),
    ('etiket', 'Sonuç CD''si hazırlanacak', 1, 'Result CD to be prepared'),
    ('etiket', 'Ön Tanı (ICD-10)', 1, 'Provisional diagnosis (ICD-10)'),
    ('etiket', 'Ön Tanı', 1, 'Provisional diagnosis'),
    ('etiket', 'Tekniker', 1, 'Technologist'),
    ('etiket', 'Çekim Zamanı', 1, 'Acquisition time'),
    ('etiket', 'Çekim Süresi (dk)', 1, 'Acquisition time (min)'),
    ('etiket', 'Kontrast (ml)', 1, 'Contrast (ml)'),
    ('etiket', 'Kontrast Yolu', 1, 'Contrast route'),
    ('etiket', 'Varsayılan Kontrast', 1, 'Default contrast'),
    ('etiket', 'Etkin Madde', 1, 'Active ingredient'),
    ('etiket', 'Konsantrasyon (mg/ml)', 1, 'Concentration (mg/ml)'),
    ('etiket', 'DLP (mGy·cm)', 1, 'DLP (mGy·cm)'),
    ('etiket', 'CTDIvol (mGy)', 1, 'CTDIvol (mGy)'),
    ('etiket', 'Seri Sayısı', 1, 'Number of series'),
    ('etiket', 'Görüntü Sayısı', 1, 'Number of images'),
    ('etiket', 'Seri / Pozisyon', 1, 'Series / position'),
    ('etiket', 'Seri / Pozisyon Tarifi', 1, 'Series / position description'),
    ('etiket', 'Cihaz Adı', 1, 'Device name'),
    ('etiket', 'Oda / Kat', 1, 'Room / floor'),
    ('etiket', 'Cihaz Sorumlusu', 1, 'Device owner'),
    ('etiket', 'Randevu Verilir', 1, 'Bookable'),
    ('etiket', 'Mesai Başlangıç', 1, 'Shift start'),
    ('etiket', 'Mesai Bitiş', 1, 'Shift end'),
    ('etiket', 'Öğle Başlangıç', 1, 'Lunch start'),
    ('etiket', 'Varsayılan Süre (dk)', 1, 'Default duration (min)'),
    ('etiket', 'Aynı Anda (hasta)', 1, 'Concurrent (patients)'),
    ('etiket', 'Acil için Ayrılan Slot', 1, 'Slots reserved for emergencies'),
    ('etiket', 'Kapatma / Bakım', 1, 'Closure / maintenance'),
    ('etiket', 'Stok / Malzeme', 1, 'Item / material'),
    ('etiket', 'Düşüm', 1, 'Deduction'),
    ('etiket', 'Kural / Not', 1, 'Rule / note'),
    ('etiket', 'Surum', 1, 'Version'),
    ('etiket', 'Baslik', 1, 'Heading'),
    ('etiket', 'Varsayilan Metin', 1, 'Default text'),
    ('etiket', 'Yazdir', 1, 'Print'),
    ('etiket', 'Bolumler', 1, 'Departments'),
    ('etiket', 'Kisayol', 1, 'Shortcut'),
    ('etiket', 'Hedef Bolum', 1, 'Target department'),
    ('etiket', 'Makrolar', 1, 'Macros'),
    ('etiket', 'Alan Adi', 1, 'Field name'),
    ('etiket', 'Secenekler (| ile)', 1, 'Options (separated by |)'),
    ('etiket', 'Rapora Bas', 1, 'Print on report'),
    ('etiket', 'Skor Alanlari', 1, 'Score fields'),
    ('etiket', 'Gönderen Kurum', 1, 'Referring institution'),
    ('etiket', 'Hasta Kaydı', 1, 'Patient record'),
    ('etiket', 'Kurum Dosya No', 1, 'Institution file No'),
    ('etiket', 'İsteyen Hekim TCKN', 1, 'Ordering physician national ID'),
    ('etiket', 'Paylaşım Onamı', 1, 'Sharing consent'),
    ('etiket', 'SLA Bitişi', 1, 'SLA deadline'),
    ('etiket', 'Okuma', 1, 'Reading'),
    ('etiket', 'Teslim Durum', 1, 'Delivery status'),
    ('etiket', 'Teslim Hata', 1, 'Delivery error'),
    ('etiket', 'Teslim Kanalı', 1, 'Delivery channel'),
    ('etiket', 'Teslim Adresi', 1, 'Delivery address'),
    ('etiket', 'Sözleşme Id', 1, 'Contract Id'),
    ('etiket', 'İç İstem Id', 1, 'Internal order Id'),
    ('etiket', 'Fatura Id', 1, 'Invoice Id'),
    ('etiket', 'Atama', 1, 'Assignment'),
    ('etiket', 'Bırakma', 1, 'Release'),
    ('etiket', 'Atama Geçmişi', 1, 'Assignment history'),
    ('etiket', 'DICOM Sunucu', 1, 'DICOM server'),
    ('etiket', 'DICOM Port', 1, 'DICOM port'),
    ('etiket', 'Alıcı Uygulama (MSH-5)', 1, 'Receiving application (MSH-5)'),
    ('etiket', 'Alıcı Tesis (MSH-6)', 1, 'Receiving facility (MSH-6)'),
    ('etiket', 'Bakanlığa Bildir', 1, 'Report to the Ministry'),
    ('etiket', 'SKRS Kodu (ORC-21)', 1, 'SKRS code (ORC-21)'),
    ('etiket', 'Firma Kodu (MSH-3)', 1, 'Sending application (MSH-3)'),
    ('etiket', 'Gönderen Tesis (MSH-4)', 1, 'Sending facility (MSH-4)'),
    ('etiket', 'Encoding (MSH-18)', 1, 'Encoding (MSH-18)'),
    ('etiket', 'WADO Adresi', 1, 'WADO address'),
    ('etiket', 'Vars. Öncelik', 1, 'Default priority'),
    ('etiket', 'Gece Nöbeti', 1, 'Night shift'),
    ('etiket', 'Onam Zorunlu', 1, 'Consent required'),
    ('etiket', 'SLA Rutin (dk)', 1, 'SLA routine (min)'),
    ('etiket', 'SLA Rutin', 1, 'SLA routine'),
    ('etiket', 'SLA Acil (dk)', 1, 'SLA emergency (min)'),
    ('etiket', 'SLA Öncelikli', 1, 'SLA priority'),
    ('etiket', 'SLA aşımı', 1, 'SLA breach'),
    ('etiket', 'SLA Ceza %', 1, 'SLA penalty %'),
    ('etiket', 'Adet Sınırı', 1, 'Volume limit'),
    ('etiket', 'Öncelikli Ek %', 1, 'Priority surcharge %'),
    ('etiket', 'Acil dk', 1, 'Emergency min'),
    ('etiket', 'Öncelikli dk', 1, 'Priority min'),
    ('etiket', 'Rutin dk', 1, 'Routine min'),
    ('etiket', 'İstem Yapan', 1, 'Ordered by'),
    ('etiket', 'İstem Hekim Id', 1, 'Ordering physician Id'),
    ('etiket', 'Kritik', 1, 'Critical'),
    ('etiket', 'Rapor Durum Kodu', 1, 'Report status code'),
    ('etiket', 'Bildirilen Hekim', 1, 'Physician notified'),
    ('etiket', 'Bulan Radyolog', 1, 'Reporting radiologist'),
    ('etiket', 'Teyit', 1, 'Acknowledgement'),
    ('etiket', 'Geçen (dk)', 1, 'Elapsed (min)'),
    ('etiket', 'Kapatma', 1, 'Closure'),
    ('etiket', 'Bildirim Id', 1, 'Notification Id'),
    ('etiket', 'İstek', 1, 'Request'),
    ('etiket', 'İstenen', 1, 'Requested'),
    ('etiket', 'Soru / Gerekçe', 1, 'Question / justification'),
    ('etiket', 'Cevap', 1, 'Answer'),
    ('etiket', 'Cevap Zamanı', 1, 'Answered at'),
    ('etiket', 'Acil', 1, 'Emergency'),
    ('etiket', 'CD İstendi', 1, 'CD requested'),
    ('etiket', 'Bekleme (dk)', 1, 'Waiting (min)'),
    ('etiket', 'Geldi', 1, 'Arrived'),
    ('etiket', 'Kalan (dk)', 1, 'Remaining (min)'),
    ('etiket', 'Görüntü Durum Kodu', 1, 'Image status code'),
    ('etiket', 'Yön Kodu', 1, 'Direction code'),
    ('etiket', 'Eksik Alanlar', 1, 'Missing fields'),
    ('etiket', 'Hedef Kodu', 1, 'Target code'),
    ('etiket', 'Son Deneme', 1, 'Last attempt'),
    ('etiket', 'Sıradaki', 1, 'Next in queue'),
    ('etiket', 'ACK', 1, 'ACK'),
    ('etiket', 'Raporlayan', 1, 'Reported by'),
    ('etiket', 'Hasta TCKN', 1, 'Patient national ID'),
    ('etiket', 'Kaynak IP', 1, 'Source IP'),
    ('etiket', '#', 1, '#'),
    ('etiket', 'Yükleniyor…', 1, 'Loading…'),
    ('etiket', 'Yenile', 1, 'Refresh'),
    ('etiket', 'Esc ile kapanır', 1, 'Press Esc to close'),
    ('etiket', 'Ekle', 1, 'Add'),
    ('etiket', 'Seçimi kaldır', 1, 'Clear selection'),
    ('etiket', 'Vazgeç', 1, 'Cancel'),
    ('etiket', 'Kaldır', 1, 'Remove'),
    ('etiket', 'Bilgi', 1, 'Info'),
    ('etiket', 'Kayıt yok.', 1, 'No records.'),
    ('etiket', 'Sonuç yok.', 1, 'No results.'),
    ('etiket', 'Bugün', 1, 'Today'),
    ('etiket', 'Günlük', 1, 'Daily'),
    ('etiket', 'Önizleme', 1, 'Preview'),
    ('etiket', 'Tamamlanan', 1, 'Completed'),
    ('etiket', 'Mevcut durum', 1, 'Current state'),
    ('etiket', 'Fark', 1, 'Difference'),
    ('etiket', 'Yok', 1, 'None'),
    ('etiket', 'Bilinmiyor', 1, 'Unknown'),
    ('etiket', 'Sürüyor', 1, 'In progress'),
    ('etiket', 'Yapmadı', 1, 'Did not do'),
    ('etiket', 'Gelmedi', 1, 'Did not attend'),
    ('etiket', 'Randevulu', 1, 'Scheduled'),
    ('etiket', 'Onaylandı', 1, 'Approved'),
    ('etiket', 'Onay yok', 1, 'Not approved'),
    ('etiket', 'Cevaplandı', 1, 'Answered'),
    ('etiket', 'Kaydeden', 1, 'Saved by'),
    ('etiket', 'Görüş', 1, 'Opinion'),
    ('etiket', 'Soru', 1, 'Question'),
    ('etiket', 'Yük', 1, 'Load'),
    ('etiket', 'Önce', 1, 'Before'),
    ('etiket', 'Sonra', 1, 'After'),
    ('etiket', 'Eğilim', 1, 'Trend'),
    ('etiket', 'Pasifleştir', 1, 'Deactivate'),
    ('etiket', 'Diş › Günlük Akış', 1, 'Dental › Daily flow'),
    ('etiket', 'Diş › Hasta Kartı', 1, 'Dental › Patient card'),
    ('etiket', 'Diş › Ayarlar › Ünitler', 1, 'Dental › Settings › Units'),
    ('etiket', 'Hasta ara…', 1, 'Search patient…'),
    ('etiket', 'Ünit doluluk', 1, 'Chair utilisation'),
    ('etiket', 'Ort. seans', 1, 'Avg. session'),
    ('etiket', 'Bugün ciro', 1, 'Revenue today'),
    ('etiket', 'Lab teslim bekleyen', 1, 'Awaiting lab delivery'),
    ('etiket', 'Plan onayı bekleyen', 1, 'Awaiting plan approval'),
    ('etiket', 'Ünit tanımlı değil -', 1, 'No units defined -'),
    ('etiket', 'Ünitsiz randevular:', 1, 'Appointments without a unit:'),
    ('etiket', 'Hekim / Ünit', 1, 'Physician / unit'),
    ('etiket', 'Ünit / hekim', 1, 'Unit / physician'),
    ('etiket', 'Planlı işlem', 1, 'Planned procedure'),
    ('etiket', 'Plan durumu', 1, 'Plan status'),
    ('etiket', 'Lab işi geldi', 1, 'Lab work received'),
    ('etiket', 'Seans kartı', 1, 'Session card'),
    ('etiket', 'Tıbbi uyarılar', 1, 'Medical alerts'),
    ('etiket', 'Alerji', 1, 'Allergy'),
    ('etiket', 'Kronik tanı', 1, 'Chronic diagnosis'),
    ('etiket', 'Sürekli ilaç', 1, 'Regular medication'),
    ('etiket', 'Dental anamnez', 1, 'Dental history'),
    ('etiket', 'Dental anamnezi düzenle', 1, 'Edit dental history'),
    ('etiket', 'Son ziyaret / hekim', 1, 'Last visit / physician'),
    ('etiket', 'Daimi dişler', 1, 'Permanent teeth'),
    ('etiket', 'Süt dişleri', 1, 'Primary teeth'),
    ('etiket', 'Çürük', 1, 'Caries'),
    ('etiket', 'Amalgam', 1, 'Amalgam'),
    ('etiket', 'Kompozit', 1, 'Composite'),
    ('etiket', 'Kron / köprü', 1, 'Crown / bridge'),
    ('etiket', 'İmplant', 1, 'Implant'),
    ('etiket', 'Eksik', 1, 'Missing'),
    ('etiket', 'Son bulgu', 1, 'Last finding'),
    ('etiket', 'Perio (cep max)', 1, 'Perio (max pocket)'),
    ('etiket', 'Yapılanlar', 1, 'Completed'),
    ('etiket', 'Bekleyenler', 1, 'Pending'),
    ('etiket', 'Plan satırı yok.', 1, 'No plan lines.'),
    ('etiket', 'İşlem ara (ad / kod)…', 1, 'Search procedure (name / code)…'),
    ('etiket', 'Seçili diş:', 1, 'Selected tooth:'),
    ('etiket', 'Kayıt yok - sağlam.', 1, 'No records - healthy.'),
    ('etiket', 'Hızlı bulgu', 1, 'Quick finding'),
    ('etiket', 'Ağız özeti', 1, 'Oral summary'),
    ('etiket', 'Plan &amp; ücret özeti', 1, 'Plan &amp; fee summary'),
    ('etiket', 'Bakiye (yapılan−tahsil)', 1, 'Balance (completed − collected)'),
    ('etiket', 'Bakiye (yapılan − tahsil)', 1, 'Balance (completed − collected)'),
    ('etiket', 'Plak indeksi', 1, 'Plaque index'),
    ('etiket', 'Kanama (BOP)', 1, 'Bleeding (BOP)'),
    ('etiket', 'Cep ≥ 5 mm', 1, 'Pocket ≥ 5 mm'),
    ('etiket', 'Ortalama CAL', 1, 'Mean CAL'),
    ('etiket', 'Evre / derece', 1, 'Stage / grade'),
    ('etiket', 'En derin cep', 1, 'Deepest pocket'),
    ('etiket', 'Tedavi geçmişi', 1, 'Treatment history'),
    ('etiket', 'Seans kaydı yok.', 1, 'No session records.'),
    ('etiket', 'Protez / lab işleri', 1, 'Prosthetics / lab work'),
    ('etiket', 'Malzeme / renk', 1, 'Material / shade'),
    ('etiket', 'Lab işi yok.', 1, 'No lab work.'),
    ('etiket', 'Hasta *', 1, 'Patient *'),
    ('etiket', 'Hekim *', 1, 'Physician *'),
    ('etiket', 'Fiyat listesi', 1, 'Price list'),
    ('etiket', 'Önceki plan', 1, 'Previous plan'),
    ('etiket', 'Plan satırı ekle', 1, 'Add plan line'),
    ('etiket', 'Plan satırı', 1, 'Plan line'),
    ('etiket', 'Plan satırları', 1, 'Plan lines'),
    ('etiket', 'İşlem ara (SUT / kod / ad)…', 1, 'Search procedure (SUT / code / name)…'),
    ('etiket', 'İşlem (SUT / kod)', 1, 'Procedure (SUT / code)'),
    ('etiket', 'Lab iş emri aç', 1, 'Open lab work order'),
    ('etiket', 'Onaylı planda satır fiyatı değişmez.', 1, 'Line prices cannot change on an approved plan.'),
    ('etiket', 'Randevu = ünit + hekim + süre;', 1, 'Appointment = unit + physician + duration;'),
    ('etiket', 'Kalan iş', 1, 'Remaining work'),
    ('etiket', 'Bekleyen satır yok.', 1, 'No pending lines.'),
    ('etiket', 'Toplam kalan:', 1, 'Total remaining:'),
    ('etiket', 'Seans önerisi', 1, 'Suggested sessions'),
    ('etiket', 'Proforma', 1, 'Proforma'),
    ('etiket', 'Proforma no', 1, 'Proforma no'),
    ('etiket', 'Sunum / onay', 1, 'Presentation / approval'),
    ('etiket', 'Toplam / indirim / net', 1, 'Total / discount / net'),
    ('etiket', 'Açıklama (proformada görünür)', 1, 'Description (shown on the proforma)'),
    ('etiket', 'Alternatif plan', 1, 'Alternative plan'),
    ('etiket', 'Alternatif planlar', 1, 'Alternative plans'),
    ('etiket', 'Hasta onayı', 1, 'Patient consent'),
    ('etiket', 'Proforma önizleme', 1, 'Proforma preview'),
    ('etiket', 'Ödeme planı', 1, 'Payment plan'),
    ('etiket', 'Ödeme seçeneği', 1, 'Payment option'),
    ('etiket', 'Toplam (net)', 1, 'Total (net)'),
    ('etiket', 'Nakit', 1, 'Cash'),
    ('etiket', 'POS taksit', 1, 'POS instalments'),
    ('etiket', 'Havale', 1, 'Bank transfer'),
    ('etiket', 'Kredi', 1, 'Loan'),
    ('etiket', 'Taksit sayısı', 1, 'Number of instalments'),
    ('etiket', 'İlk vade', 1, 'First due date'),
    ('etiket', 'Ücret akışı', 1, 'Fee flow'),
    ('etiket', 'Yapılan işlem', 1, 'Procedure performed'),
    ('etiket', 'Yapılan işlemler', 1, 'Procedures performed'),
    ('etiket', 'Lab işleri', 1, 'Lab work'),
    ('etiket', 'İş emri', 1, 'Work order'),
    ('etiket', 'İş emri açılmadı', 1, 'No work order opened'),
    ('etiket', 'Lab gerektiren satır yok.', 1, 'No lines requiring lab work.'),
    ('etiket', 'Lab maliyeti', 1, 'Lab cost'),
    ('etiket', 'Lab maliyeti (hakedişten düşer)', 1, 'Lab cost (deducted from earnings)'),
    ('etiket', 'Lab gerektiren satır (hizmet kartı', 1, 'Lines requiring lab work (service card'),
    ('etiket', 'Varyant ayrı plan kaydıdır (', 1, 'A variant is a separate plan record ('),
    ('etiket', 'Bu seans', 1, 'This session'),
    ('etiket', 'Önceki seans notu', 1, 'Previous session note'),
    ('etiket', 'Önceki seans', 1, 'Previous session'),
    ('etiket', 'Başvuru / plan', 1, 'Encounter / plan'),
    ('etiket', 'İşlem (plan satırı)', 1, 'Procedure (plan line)'),
    ('etiket', 'Açık plan satırı yok.', 1, 'No open plan lines.'),
    ('etiket', 'Plan dışı işlem', 1, 'Unplanned procedure'),
    ('etiket', 'İşlem ara…', 1, 'Search procedure…'),
    ('etiket', 'Çalışma boyu (mm) · kanal bazlı', 1, 'Working length (mm) · per canal'),
    ('etiket', 'Sonraki seans planı (bu satır)', 1, 'Next session plan (this line)'),
    ('etiket', 'Ekip & süre', 1, 'Team & duration'),
    ('etiket', 'Başlangıç / bitiş', 1, 'Start / end'),
    ('etiket', 'Seans notu & hastaya talimat', 1, 'Session note & patient instructions'),
    ('etiket', 'Anestezi & seans notu', 1, 'Anaesthesia & session note'),
    ('etiket', 'Anestezi türü', 1, 'Anaesthesia type'),
    ('etiket', 'İnfiltratif / rejyonel', 1, 'Infiltration / regional'),
    ('etiket', 'Seans notu (genel)', 1, 'Session note (general)'),
    ('etiket', 'Seans notu', 1, 'Session note'),
    ('etiket', 'Komplikasyon (seans)', 1, 'Complication (session)'),
    ('etiket', 'Sterilizasyon paketi', 1, 'Sterilisation pack'),
    ('etiket', 'Malzeme & sarf', 1, 'Materials & consumables'),
    ('etiket', 'Sarf kaydı yok.', 1, 'No consumable records.'),
    ('etiket', 'Toplam sarf', 1, 'Total consumables'),
    ('etiket', 'Ücret & tahsilat', 1, 'Fee & collection'),
    ('etiket', 'Bu seansın ücreti (bitince)', 1, 'Fee for this session (once finished)'),
    ('etiket', 'Plan yapılan', 1, 'Plan completed'),
    ('etiket', 'Lab: Tümü', 1, 'Lab: all'),
    ('etiket', 'Hekim: Tümü', 1, 'Physician: all'),
    ('etiket', 'SLA çubuğu: gönderim → beklenen', 1, 'SLA bar: dispatch → expected'),
    ('etiket', 'Diş / iş', 1, 'Tooth / job'),
    ('etiket', 'Renk · ölçü', 1, 'Shade · impression'),
    ('etiket', 'Gönderim → beklenen', 1, 'Dispatch → expected'),
    ('etiket', 'Lab / hasta fiyatı', 1, 'Lab / patient price'),
    ('etiket', 'Ek istek', 1, 'Additional request'),
    ('etiket', 'Aşama geçişi', 1, 'Stage transition'),
    ('etiket', 'Aşama geçmişi', 1, 'Stage history'),
    ('etiket', 'Kayıt yok (iş emri açıldı).', 1, 'No records (work order opened).'),
    ('etiket', 'Ölçü', 1, 'Impression'),
    ('etiket', 'Beklenen (SLA)', 1, 'Expected (SLA)'),
    ('etiket', 'Ölçü bekleyen iş emri yok.', 1, 'No work orders awaiting an impression.'),
    ('etiket', 'Prova randevusu', 1, 'Try-in appointment'),
    ('etiket', 'Prova / teslim randevusu', 1, 'Try-in / delivery appointment'),
    ('etiket', 'Gelen iş yok.', 1, 'No incoming work.'),
    ('etiket', 'Kurye / portal', 1, 'Courier / portal'),
    ('etiket', 'İş · malzeme · renk', 1, 'Job · material · shade'),
    ('etiket', 'Seanslar', 1, 'Sessions'),
    ('etiket', 'Ünite Panosu', 1, 'Unit board'),
    ('etiket', 'FTR › Ünite Panosu', 1, 'PMR › Unit board'),
    ('etiket', 'Kabin doluluk', 1, 'Cubicle utilisation'),
    ('etiket', 'Bekleyen (planlı)', 1, 'Waiting (scheduled)'),
    ('etiket', 'Bekleyenler & sıra', 1, 'Waiting list & queue'),
    ('etiket', 'Bekleyen yok.', 1, 'Nobody waiting.'),
    ('etiket', 'Fizyoterapist yükü (bugün)', 1, 'Physiotherapist load (today)'),
    ('etiket', 'Bugün atanmış fizyoterapist yok.', 1, 'No physiotherapist assigned today.'),
    ('etiket', 'Günün programı', 1, 'Today''s programme'),
    ('etiket', 'Bugün seans yok.', 1, 'No sessions today.'),
    ('etiket', 'Bugün seans', 1, 'Sessions today'),
    ('etiket', 'Fizyoterapist · kabin', 1, 'Physiotherapist · cubicle'),
    ('etiket', 'Bölge · tanı', 1, 'Region · diagnosis'),
    ('etiket', 'Seans · sıklık · süre', 1, 'Sessions · frequency · duration'),
    ('etiket', 'Ödeyen · rapor', 1, 'Payer · report'),
    ('etiket', 'Başlangıç → tahmini bitiş', 1, 'Start → estimated end'),
    ('etiket', 'Yıllık hak (bölge)', 1, 'Annual entitlement (region)'),
    ('etiket', 'Devamsızlık', 1, 'Non-attendance'),
    ('etiket', 'Planlı seans', 1, 'Scheduled session'),
    ('etiket', 'Uygulama ekle', 1, 'Add procedure'),
    ('etiket', 'SUT kodu / ad ara…', 1, 'Search SUT code / name…'),
    ('etiket', 'Serbest ad', 1, 'Free-text name'),
    ('etiket', 'Ekle (serbest)', 1, 'Add (free text)'),
    ('etiket', 'SUT · uygulama', 1, 'SUT · procedure'),
    ('etiket', 'Cihaz / kabin', 1, 'Device / cubicle'),
    ('etiket', 'Seans takvimi', 1, 'Session calendar'),
    ('etiket', 'Seans süresi', 1, 'Session length'),
    ('etiket', 'Sonraki seans', 1, 'Next session'),
    ('etiket', 'VAS önce → sonra', 1, 'VAS before → after'),
    ('etiket', 'VAS seyri (seans öncesi → sonrası)', 1, 'VAS trend (before → after session)'),
    ('etiket', 'VAS seans öncesi', 1, 'VAS before session'),
    ('etiket', 'VAS seans sonrası', 1, 'VAS after session'),
    ('etiket', 'Egzersiz programı', 1, 'Exercise programme'),
    ('etiket', 'Egzersiz tanımlı değil.', 1, 'No exercises defined.'),
    ('etiket', 'Programlar', 1, 'Programmes'),
    ('etiket', 'Yaptı (tam)', 1, 'Completed (full)'),
    ('etiket', 'Yaptı (kısmi)', 1, 'Completed (partial)'),
    ('etiket', 'Yapılmadı (neden)', 1, 'Not performed (reason)'),
    ('etiket', 'Komplikasyon / yan etki', 1, 'Complication / adverse effect'),
    ('etiket', 'Ev egzersizi 2×/gün · ağrı artarsa ara', 1, 'Home exercise 2×/day · call if pain increases'),
    ('etiket', 'Radyoloji Raporu', 1, 'Radiology report'),
    ('etiket', 'İstem bulunamadı.', 1, 'Order not found.'),
    ('etiket', 'Önceki Tetkikler', 1, 'Prior studies'),
    ('etiket', 'Önceki tetkik yok.', 1, 'No prior studies.'),
    ('etiket', 'Ön tanı:', 1, 'Provisional diagnosis:'),
    ('etiket', 'Klinik:', 1, 'Clinical:'),
    ('etiket', 'İsteyen:', 1, 'Ordered by:'),
    ('etiket', 'Ödeyen:', 1, 'Payer:'),
    ('etiket', 'Seri / Görüntü', 1, 'Series / image'),
    ('etiket', 'PACS eşleşmesi yok.', 1, 'No PACS match.'),
    ('etiket', 'Kritik Bulgu Bildirimleri', 1, 'Critical finding notifications'),
    ('etiket', 'Kritik Bulgu Bildirimi', 1, 'Critical finding notification'),
    ('etiket', 'Bu tetkikte kritik bulgu var', 1, 'This study has a critical finding'),
    ('etiket', 'Bu şablonda makro yok.', 1, 'No macros in this template.'),
    ('etiket', 'Yapılandırılmış Alanlar', 1, 'Structured fields'),
    ('etiket', 'Bakanlık Değerlendirmesi', 1, 'Ministry assessment'),
    ('etiket', 'İstem Nedeni', 1, 'Reason for order'),
    ('etiket', 'Çekim Kalitesi', 1, 'Image quality'),
    ('etiket', 'Sonuç ve Öneriler', 1, 'Conclusion and recommendations'),
    ('etiket', 'Konsültasyon', 1, 'Consultation'),
    ('etiket', 'İstenmiş konsültasyon yok.', 1, 'No consultation requested.'),
    ('etiket', 'İkinci Görüş İste', 1, 'Request second opinion'),
    ('etiket', 'Konsültasyon Görüşü', 1, 'Consultation opinion'),
    ('etiket', 'Geri bildirim', 1, 'Feedback'),
    ('etiket', 'Bildirilen kişi', 1, 'Person notified'),
    ('etiket', 'Bildirim yolu', 1, 'Notification method'),
    ('etiket', 'Karşı taraf bulguyu aldığını', 1, 'The recipient confirms receipt of the finding'),
    ('etiket', 'Toplam tetkik', 1, 'Total studies'),
    ('etiket', 'Bu ay', 1, 'This month'),
    ('etiket', 'Raporlanan', 1, 'Reported'),
    ('etiket', 'Toplam tutar', 1, 'Total amount'),
    ('etiket', 'Son gönderim', 1, 'Last submission'),
    ('etiket', 'İstem No:', 1, 'Order No:'),
    ('etiket', 'Rapor:', 1, 'Report:'),
    ('etiket', 'Oluşturan:', 1, 'Created by:'),
    ('etiket', 'Tetkik Seçimi', 1, 'Study selection'),
    ('etiket', 'Soldaki listeden tetkik seçin.', 1, 'Select a study from the list on the left.'),
    ('etiket', 'Listeden çıkar', 1, 'Remove from list'),
    ('etiket', 'İsteyen Hekim (dış)', 1, 'Ordering physician (external)'),
    ('etiket', 'Kayıtlı hekim seç…', 1, 'Select a registered physician…'),
    ('etiket', 'Dış hekim ara', 1, 'Search external physician'),
    ('etiket', 'Hekim Adı (kayıtsız)', 1, 'Physician name (unregistered)'),
    ('etiket', 'Kurum seç…', 1, 'Select institution…'),
    ('etiket', 'Kurum ara', 1, 'Search institution'),
    ('etiket', 'Klinik Bilgi / İstem Gerekçesi', 1, 'Clinical information / reason for order'),
    ('etiket', 'Kabul Sonrası', 1, 'After admission'),
    ('etiket', 'Ödeme / Kabul', 1, 'Payment / admission'),
    ('etiket', 'Hasta kendi öder…', 1, 'Patient self-pays…'),
    ('etiket', 'Başvuru aç ve ücretlendir', 1, 'Open encounter and charge'),
    ('etiket', 'Liste tutarı', 1, 'List amount'),
    ('etiket', 'Protokol:', 1, 'Protocol:'),
    ('etiket', 'Genel toplam:', 1, 'Grand total:'),
    ('etiket', 'Kurumdan:', 1, 'From institution:'),
    ('etiket', 'Hastadan:', 1, 'From patient:'),
    ('etiket', 'Sorulan:', 1, 'Asked:'),
    ('etiket', 'Çekim Öncesi Kontrol Listesi', 1, 'Pre-acquisition checklist'),
    ('etiket', 'Randevu Bekleyen', 1, 'Awaiting appointment'),
    ('etiket', 'Listeyi tazele', 1, 'Refresh the list'),
    ('etiket', 'Hasta / tetkik ara…', 1, 'Search patient / study…'),
    ('etiket', 'Randevu bekleyen istem yok.', 1, 'No orders awaiting an appointment.'),
    ('etiket', 'Tarih/saat seçerek randevu ver', 1, 'Book by choosing a date and time'),
    ('etiket', 'Kullanılan', 1, 'Used'),
    ('etiket', 'Lot / SKT', 1, 'Lot / expiry'),
    ('etiket', 'Teslim edilen', 1, 'Delivered'),
    ('etiket', 'Kimlik doğrulandı', 1, 'Identity verified'),
    ('etiket', 'Kapat', 1, 'Close'),
    ('etiket', 'Kaydet', 1, 'Save'),
    ('etiket', 'Seans', 1, 'Session'),
    ('etiket', 'Ödeme Planı', 1, 'Payment plan'),
    ('etiket', 'Muayene / Seans Aç', 1, 'Open examination / session'),
    ('etiket', 'Tedavi Programı', 1, 'Treatment programme'),
    ('etiket', 'Seansı Bitir', 1, 'Finish session'),
    ('etiket', 'Başlat', 1, 'Start'),
    ('etiket', 'Hasta Kartı', 1, 'Patient card'),
    ('etiket', 'Diş Kliniği — Günlük Akış', 1, 'Dental clinic — daily flow'),
    ('etiket', 'Yeni Plan', 1, 'New plan'),
    ('etiket', 'Yeni Seans', 1, 'New session'),
    ('etiket', 'İş Emri', 1, 'Work order'),
    ('etiket', 'Plan Onayla', 1, 'Approve plan'),
    ('etiket', 'Proforma Yazdır', 1, 'Print proforma'),
    ('etiket', 'Rapor', 1, 'Report'),
    ('etiket', 'Raporu Onayla', 1, 'Approve report'),
    ('etiket', 'Taslak Kaydet', 1, 'Save draft'),
    ('etiket', 'Kritik Bulgu', 1, 'Critical finding'),
    ('etiket', 'Konsültasyon İste', 1, 'Request consultation'),
    ('etiket', 'Önizle', 1, 'Preview'),
    ('etiket', 'Yazdır', 1, 'Print'),
    ('etiket', 'Sil', 1, 'Delete'),
    ('etiket', 'İptal', 1, 'Cancel'),
    ('etiket', 'Geri', 1, 'Back'),
    ('etiket', 'Seçiniz', 1, 'Select'),
    ('etiket', 'yok', 1, 'none'),
    ('etiket', 'plan yok', 1, 'no plan'),
    ('etiket', 'plan dışı', 1, 'unplanned'),
    ('etiket', 'bekliyor', 1, 'waiting'),
    ('etiket', 'devam', 1, 'ongoing'),
    ('etiket', '— seçiniz —', 1, '— select —')
on conflict (kapsam, anahtar, dil) do update set metin = excluded.metin,
    degistirme_tarihi = now();

do $$
declare v_en integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    raise notice '850 tamam: ingilizce sozluk % satir.', v_en;
end $$;
