-- ============================================================================
--  Gentegre AI — KOD DEĞERLERİ İNGİLİZCE (852)
--  852_ingilizce_sozluk_kod_degerleri.sql
--
--  Kullanıcı: *"kod değerlerini de çevir"* (849/850/851'in devamı).
--
--  Kapsam: durum/tür adları - grid hücrelerinde rozet olarak, kart ve detay
--  combolarında seçenek olarak görünen değerler. İki kaynak var, ikisi de
--  aynı sözlükten çevrilir:
--    · `kod_deger.ad` (veritabanı kod listeleri),
--    · katalogdaki `SabitKodlar` sözlükleri (C#).
--
--  KAPSAM `kod`: aynı Türkçe kelime etikette başka anlama gelebilir
--  ("Açık" = open / light). Karşılığı olmayan değer `etiket` kapsamına
--  düşer - çoğu terim orada zaten var, iki kez yazılmaz.
--
--  ÇEVRİLMEYEN LİSTELER (bilerek): `taraf.meslek` (5.461 meslek),
--  `hekim.brans` / `klinik.kod` / `skrs.klinik` (SKRS klinik kodları),
--  `hasta.uyruk` (ülke listesi) - bunlar SKRS/resmî kod listeleridir,
--  çevirisi kurumca değil kaynak listeyle yapılmalı.
--
--  ÇEVRİLMEYEN DEĞERLER: teknik sabitler ('utf-8', 'Windows1254',
--  'bb.personel_id', SQL parçaları), ölçek adları (Barthel, Berg, DASH,
--  WOMAC, KOOS, Lysholm, Oswestry), standart kısaltmalar (OCT, ERG/VEP,
--  DEXA, HL7, DICOM, FHIR) ve kan grupları.
--
--  İLAÇ ADLARI uluslararası (INN) yazımına çevrildi: Aflibersept →
--  Aflibercept, Bevasizumab → Bevacizumab, Farisimab → Faricimab.
--
--  Idempotent (`on conflict do update`).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin) values
    ('kod', '$ USD · ABD Doları', 1, '$ USD · US dollar'),
    ('kod', '%5 CO₂', 1, '5% CO₂'),
    ('kod', '(açık)', 1, '(open)'),
    ('kod', '(farketmez)', 1, '(any)'),
    ('kod', '-Boş-', 1, '-Empty-'),
    ('kod', '0 RH +', 1, '0 Rh+'),
    ('kod', '0 RH -', 1, '0 Rh−'),
    ('kod', '1 Ay', 1, '1 month'),
    ('kod', '1 Kırmızı (resüsitasyon)', 1, '1 Red (resuscitation)'),
    ('kod', '1 · Dar spektrum (her zaman raporlanır)', 1, '1 · Narrow spectrum (always reported)'),
    ('kod', '1 · Kırmızı (resüsitasyon)', 1, '1 · Red (resuscitation)'),
    ('kod', '1 · Salona girişte (sign in)', 1, '1 · On entering theatre (sign in)'),
    ('kod', '10 dk', 1, '10 min'),
    ('kod', '112 ambulans', 1, '112 ambulance'),
    ('kod', '112 çağrıldı', 1, '112 called'),
    ('kod', '15 dk', 1, '15 min'),
    ('kod', '15-49 Kadın Hastalar', 1, 'Female patients aged 15-49'),
    ('kod', '2 Ay', 1, '2 months'),
    ('kod', '2 Turuncu (acil)', 1, '2 Orange (emergency)'),
    ('kod', '2 · Alternatif (1. basamakta duyarlı yoksa)', 1, '2 · Alternative (if nothing susceptible at tier 1)'),
    ('kod', '2 · Kesi öncesi (time out)', 1, '2 · Before incision (time out)'),
    ('kod', '2 · Turuncu (acil)', 1, '2 · Orange (emergency)'),
    ('kod', '20 dk', 1, '20 min'),
    ('kod', '3 Ay', 1, '3 months'),
    ('kod', '3 Aylık', 1, 'Quarterly'),
    ('kod', '3 Sarı (acele)', 1, '3 Yellow (urgent)'),
    ('kod', '3 aylık', 1, 'quarterly'),
    ('kod', '3 · Kısıtlı / geniş spektrum (1 ve 2''de duyarlı yoksa)', 1, '3 · Restricted / broad spectrum (if nothing susceptible at tiers 1 and 2)'),
    ('kod', '3 · Sarı (acele)', 1, '3 · Yellow (urgent)'),
    ('kod', '3 · Çıkmadan (sign out)', 1, '3 · Before leaving (sign out)'),
    ('kod', '30 dk', 1, '30 min'),
    ('kod', '4 Ay', 1, '4 months'),
    ('kod', '4 Yeşil (az acil)', 1, '4 Green (less urgent)'),
    ('kod', '4 · Yeşil (az acil)', 1, '4 · Green (less urgent)'),
    ('kod', '45 dk', 1, '45 min'),
    ('kod', '5 Mavi (acil değil)', 1, '5 Blue (non-urgent)'),
    ('kod', '5 dk', 1, '5 min'),
    ('kod', '5 · Mavi (acil değil)', 1, '5 · Blue (non-urgent)'),
    ('kod', '6 Aylık', 1, 'Every 6 months'),
    ('kod', '6 aylık', 1, 'every 6 months'),
    ('kod', '6 saat aç gelin. Kan sulandırıcı kullanıyorsanız hekiminize danışın; yanınızda refakatçi bulunsun.', 1, 'Fast for 6 hours. If you take blood thinners, consult your physician; bring a companion.'),
    ('kod', '60 dk', 1, '60 min'),
    ('kod', '65 Yaş Üstü Hastalar', 1, 'Patients over 65'),
    ('kod', '78D', 1, '78D'),
    ('kod', '90 dk', 1, '90 min'),
    ('kod', '90D', 1, '90D'),
    ('kod', '< (küçük)', 1, '< (less than)'),
    ('kod', '> (büyük)', 1, '> (greater than)'),
    ('kod', '@bugun', 1, '@bugun'),
    ('kod', '@simdi', 1, '@simdi'),
    ('kod', 'A', 1, 'A'),
    ('kod', 'A (ana plan)', 1, 'A (main plan)'),
    ('kod', 'A RH +', 1, 'A Rh+'),
    ('kod', 'A RH -', 1, 'A Rh−'),
    ('kod', 'AB RH +', 1, 'AB Rh+'),
    ('kod', 'AB RH -', 1, 'AB Rh−'),
    ('kod', 'ACİL', 1, 'EMERGENCY'),
    ('kod', 'AF · Afganistan', 1, 'AF · Afghanistan'),
    ('kod', 'AFAD', 1, 'AFAD'),
    ('kod', 'ALT', 1, 'ALT'),
    ('kod', 'AMD', 1, 'AMD'),
    ('kod', 'API', 1, 'API'),
    ('kod', 'ASTM E1394', 1, 'ASTM E1394'),
    ('kod', 'AT · Avusturya', 1, 'AT · Austria'),
    ('kod', 'ATC ilaç', 1, 'ATC drug'),
    ('kod', 'AZ · Azerbaycan', 1, 'AZ · Azerbaijan'),
    ('kod', 'Acil / ağrı giderme', 1, 'Emergency / pain relief'),
    ('kod', 'Acilden', 1, 'From the emergency department'),
    ('kod', 'Aciliyet Durumu Atanmamış', 1, 'Urgency not assigned'),
    ('kod', 'Aciliyet Durumu Atanmış - Acil', 1, 'Urgency assigned - emergency'),
    ('kod', 'Aciliyet Durumu Atanmış - Elektif', 1, 'Urgency assigned - elective'),
    ('kod', 'Adli Merci', 1, 'Judicial authority'),
    ('kod', 'Adli vaka', 1, 'Forensic case'),
    ('kod', 'Aerob', 1, 'Aerobic'),
    ('kod', 'Aflibersept', 1, 'Aflibercept'),
    ('kod', 'Akrabası', 1, 'Relative'),
    ('kod', 'Aldığı', 1, 'Intake'),
    ('kod', 'Alma', 1, 'Receipt'),
    ('kod', 'Alt emir', 1, 'Sub-order'),
    ('kod', 'Alıcı adresine teslim', 1, 'Delivered to the buyer''s address'),
    ('kod', 'Alıcı kendi aracıyla', 1, 'Collected by the buyer'),
    ('kod', 'Alınmadı', 1, 'Not received'),
    ('kod', 'Alış / Satış', 1, 'Purchase / sale'),
    ('kod', 'Amalgam dolgu', 1, 'Amalgam filling'),
    ('kod', 'Ambalaj', 1, 'Packaging'),
    ('kod', 'Ambliyopi', 1, 'Amblyopia'),
    ('kod', 'Ameliyat başladı', 1, 'Surgery started'),
    ('kod', 'Ameliyat planlandı', 1, 'Surgery scheduled'),
    ('kod', 'Ameliyathane', 1, 'Operating theatre'),
    ('kod', 'Amputasyon-Replantasyon', 1, 'Amputation-replantation'),
    ('kod', 'Amsterdam / Brüksel (UTC+1, yaz +2)', 1, 'Amsterdam / Brussels (UTC+1, summer +2)'),
    ('kod', 'Ana Tanı', 1, 'Primary diagnosis'),
    ('kod', 'Ana ilaç', 1, 'Main drug'),
    ('kod', 'Ana işlem', 1, 'Main procedure'),
    ('kod', 'Anaerob', 1, 'Anaerobic'),
    ('kod', 'Anafilaksi', 1, 'Anaphylaxis'),
    ('kod', 'Anestezi teknikeri', 1, 'Anaesthesia technician'),
    ('kod', 'Anestezi uzmanı', 1, 'Anaesthetist'),
    ('kod', 'Anjiyo', 1, 'Angiography'),
    ('kod', 'Anjiyografi (BTA / MRA)', 1, 'Angiography (CTA / MRA)'),
    ('kod', 'Anket', 1, 'Survey'),
    ('kod', 'Annesi', 1, 'Mother'),
    ('kod', 'Antirefle', 1, 'Anti-reflective'),
    ('kod', 'Ara değerlendirme', 1, 'Interim assessment'),
    ('kod', 'Ara mesafe', 1, 'Intermediate'),
    ('kod', 'Aralıklı', 1, 'Intermittent'),
    ('kod', 'Arka kapsül yırtığı (PCR)', 1, 'Posterior capsule rupture (PCR)'),
    ('kod', 'Arkadaşı', 1, 'Friend'),
    ('kod', 'Artık imha', 1, 'Residue destruction'),
    ('kod', 'Arıza', 1, 'Fault'),
    ('kod', 'Askeri Hastaneye Sevk', 1, 'Referral to a military hospital'),
    ('kod', 'Askerliğe Elverişli', 1, 'Fit for military service'),
    ('kod', 'Atandı', 1, 'Assigned'),
    ('kod', 'Atlandı', 1, 'Omitted'),
    ('kod', 'Atlandı (gerekçeli)', 1, 'Omitted (with reason)'),
    ('kod', 'Ayak / ayak bileği', 1, 'Foot / ankle'),
    ('kod', 'Ayaktan', 1, 'Outpatient'),
    ('kod', 'Ayaktan (A)', 1, 'Outpatient (A)'),
    ('kod', 'Aylık', 1, 'Monthly'),
    ('kod', 'Aylık sabit + aşım', 1, 'Monthly fixed + overage'),
    ('kod', 'Aynı Seviye Yoğun Bakıma Sevk', 1, 'Referral to same-level intensive care'),
    ('kod', 'Ayırıcı Tanı', 1, 'Differential diagnosis'),
    ('kod', 'Az tehlikeli', 1, 'Low hazard'),
    ('kod', 'Azalan bakiyeler', 1, 'Reducing balance'),
    ('kod', 'Açık Rıza', 1, 'Explicit consent'),
    ('kod', 'Açık ihale', 1, 'Open tender'),
    ('kod', 'Ağır metal (kurşun vb.)', 1, 'Heavy metal (lead etc.)'),
    ('kod', 'Aşı / Enjeksiyon', 1, 'Vaccination / injection'),
    ('kod', 'Aşı kampanyası', 1, 'Vaccination campaign'),
    ('kod', 'Aşınma', 1, 'Wear'),
    ('kod', 'B (alternatif)', 1, 'B (alternative)'),
    ('kod', 'B RH +', 1, 'B Rh+'),
    ('kod', 'B RH -', 1, 'B Rh−'),
    ('kod', 'B,P,C', 1, 'B,P,C'),
    ('kod', 'B-scan USG', 1, 'B-scan ultrasound'),
    ('kod', 'BCVA (en iyi düzeltilmiş)', 1, 'BCVA (best corrected)'),
    ('kod', 'BE · Belçika', 1, 'BE · Belgium'),
    ('kod', 'BOS', 1, 'CSF'),
    ('kod', 'BT', 1, 'CT'),
    ('kod', 'BT - kontrastlı (4 saat açlık, kreatinin)', 1, 'CT - with contrast (4 h fasting, creatinine)'),
    ('kod', 'Babası', 1, 'Father'),
    ('kod', 'Bakteri', 1, 'Bacteria'),
    ('kod', 'Bakü (UTC+4)', 1, 'Baku (UTC+4)'),
    ('kod', 'Bakım / Sözleşme', 1, 'Maintenance / contract'),
    ('kod', 'Bakım / servis', 1, 'Maintenance / service'),
    ('kod', 'Bankada Tahsilde', 1, 'At the bank for collection'),
    ('kod', 'Bankaya Tahsile', 1, 'To the bank for collection'),
    ('kod', 'Bankaya aktarımda', 1, 'In transfer to the bank'),
    ('kod', 'Banko', 1, 'Front desk'),
    ('kod', 'Barthel', 1, 'Barthel'),
    ('kod', 'Basil', 1, 'Bacillus'),
    ('kod', 'Basılı Rapor', 1, 'Printed report'),
    ('kod', 'Batın ultrasonu için 6-8 saat aç gelin. Üriner sistem için 4-6 bardak su içip idrarınızı tutun.', 1, 'Fast 6-8 hours for an abdominal ultrasound. For the urinary tract, drink 4-6 glasses of water and hold your urine.'),
    ('kod', 'Bağ-Kur', 1, 'Bağ-Kur'),
    ('kod', 'Bağdat (UTC+3)', 1, 'Baghdad (UTC+3)'),
    ('kod', 'Bağkur', 1, 'Bağ-Kur'),
    ('kod', 'Başhekim / Müdür', 1, 'Chief physician / director'),
    ('kod', 'Başhekim / müdür', 1, 'Chief physician / director'),
    ('kod', 'Başka kliniğe nakil', 1, 'Transfer to another clinic'),
    ('kod', 'Başka kurumdan sevk', 1, 'Referred from another institution'),
    ('kod', 'Başvuru Türü (yerel kod ile eşleşir)', 1, 'Encounter type (matches the local code)'),
    ('kod', 'Bebek Hastalar', 1, 'Infant patients'),
    ('kod', 'Bekar', 1, 'Single'),
    ('kod', 'Beklemede', 1, 'Pending'),
    ('kod', 'Bekleniyor', 1, 'Awaited'),
    ('kod', 'Beklenmeyen kutu', 1, 'Unexpected pack'),
    ('kod', 'Beklet', 1, 'Hold'),
    ('kod', 'Bekletme bitti', 1, 'Hold ended'),
    ('kod', 'Bekâr', 1, 'Single'),
    ('kod', 'Belge Talebi', 1, 'Document request'),
    ('kod', 'Belge bazında', 1, 'Per document'),
    ('kod', 'Belge başına ayrı fiş', 1, 'A separate voucher per document'),
    ('kod', 'Belge eksiği', 1, 'Missing document'),
    ('kod', 'Belge kaydında anında', 1, 'Immediately when the document is saved'),
    ('kod', 'Belirlenemedi', 1, 'Could not be determined'),
    ('kod', 'Belirli Süreli', 1, 'Fixed term'),
    ('kod', 'Belirli günlerde (seri)', 1, 'On specific days (series)'),
    ('kod', 'Belirli radyolog', 1, 'Specific radiologist'),
    ('kod', 'Belirsiz Süreli', 1, 'Indefinite term'),
    ('kod', 'Belirtilmedi', 1, 'Not specified'),
    ('kod', 'Belirtilmemiş', 1, 'Unspecified'),
    ('kod', 'Berg denge', 1, 'Berg balance'),
    ('kod', 'Berlin / Viyana (UTC+1, yaz +2)', 1, 'Berlin / Vienna (UTC+1, summer +2)'),
    ('kod', 'Bevasizumab', 1, 'Bevacizumab'),
    ('kod', 'Beyan (onay kutusu)', 1, 'Declaration (checkbox)'),
    ('kod', 'Beyaz Kod', 1, 'White Code'),
    ('kod', 'Beyazlatma', 1, 'Whitening'),
    ('kod', 'Bifokal', 1, 'Bifocal'),
    ('kod', 'Bilanço Esası', 1, 'Balance sheet basis'),
    ('kod', 'Bilateral', 1, 'Bilateral'),
    ('kod', 'Bildirildi', 1, 'Reported'),
    ('kod', 'Bilet', 1, 'Ticket'),
    ('kod', 'Bilgi farkı', 1, 'Information discrepancy'),
    ('kod', 'Bilgi istedi', 1, 'Requested information'),
    ('kod', 'Bilgi kartı', 1, 'Info card'),
    ('kod', 'Bilgi verildi', 1, 'Information given'),
    ('kod', 'Bilgisayar / BT', 1, 'Computer / IT'),
    ('kod', 'Bilinmeyen / Bildirilmeyen', 1, 'Unknown / not reported'),
    ('kod', 'Bir Alt Seviye Yoğun Bakıma Sevk', 1, 'Referral to a lower-level intensive care'),
    ('kod', 'Bir Üst Seviye Yoğun Bakıma Sevk', 1, 'Referral to a higher-level intensive care'),
    ('kod', 'Birden çok fark', 1, 'Multiple discrepancies'),
    ('kod', 'Birim değişikliği', 1, 'Unit change'),
    ('kod', 'Birim sorumlusu', 1, 'Unit supervisor'),
    ('kod', 'Birim talebi', 1, 'Unit request'),
    ('kod', 'Birleştirildi', 1, 'Merged'),
    ('kod', 'Biyokimya', 1, 'Biochemistry'),
    ('kod', 'Biyolojik', 1, 'Biological'),
    ('kod', 'Boş', 1, 'Empty'),
    ('kod', 'Boş Yer Olmaması', 1, 'No available capacity'),
    ('kod', 'Boşanmış', 1, 'Divorced'),
    ('kod', 'Boşanmış / Dul / Ayrı Yaşıyor', 1, 'Divorced / widowed / separated'),
    ('kod', 'Braden bası yarası', 1, 'Braden pressure ulcer'),
    ('kod', 'Brüt', 1, 'Gross'),
    ('kod', 'Bulaşıcı hastalık', 1, 'Communicable disease'),
    ('kod', 'Bulgu var', 1, 'Findings present'),
    ('kod', 'Bölgesel', 1, 'Regional'),
    ('kod', 'Bırakmış', 1, 'Former user'),
    ('kod', 'CD / DVD', 1, 'CD / DVD'),
    ('kod', 'CEO', 1, 'CEO'),
    ('kod', 'CH · İsviçre', 1, 'CH · Switzerland'),
    ('kod', 'CHF', 1, 'CHF'),
    ('kod', 'CHF · İsviçre Frangı', 1, 'CHF · Swiss franc'),
    ('kod', 'Cek', 1, 'Cheque'),
    ('kod', 'Cerrahi Merkeze Sevk (Yenidoğan Nakil)', 1, 'Referral to a surgical centre (neonatal transfer)'),
    ('kod', 'Check-up', 1, 'Check-up'),
    ('kod', 'Cihaz yok / arızalı', 1, 'No device / faulty'),
    ('kod', 'Ciro Edildi', 1, 'Endorsed'),
    ('kod', 'Constant (omuz)', 1, 'Constant (shoulder)'),
    ('kod', 'DASH', 1, 'DASH'),
    ('kod', 'DCR', 1, 'DCR'),
    ('kod', 'DE · Almanya', 1, 'DE · Germany'),
    ('kod', 'DEXA', 1, 'DEXA'),
    ('kod', 'DEXA - son 5 gün kontrast sorgusu', 1, 'DEXA - check for contrast in the last 5 days'),
    ('kod', 'DICOM', 1, 'DICOM'),
    ('kod', 'DICOM (alım)', 1, 'DICOM (receive)'),
    ('kod', 'Dahiliye', 1, 'Internal medicine'),
    ('kod', 'Daimi', 1, 'Permanent'),
    ('kod', 'Damar yolu açık olmalı (18-20 G, antekübital)', 1, 'An IV line is required (18-20 G, antecubital)'),
    ('kod', 'Damga', 1, 'Stamp duty'),
    ('kod', 'Damlacık', 1, 'Droplet'),
    ('kod', 'Davet edildi', 1, 'Invited'),
    ('kod', 'Davet gönderildi', 1, 'Invitation sent'),
    ('kod', 'Dekolman alanı', 1, 'Detachment area'),
    ('kod', 'Deksametazon implant', 1, 'Dexamethasone implant'),
    ('kod', 'Demirbaş İş Emri', 1, 'Asset work order'),
    ('kod', 'Deneme Süreli', 1, 'Probationary'),
    ('kod', 'Dental genel', 1, 'Dental general'),
    ('kod', 'Depoda', 1, 'In the warehouse'),
    ('kod', 'Depoda teslim', 1, 'Ex works'),
    ('kod', 'Devam', 1, 'Continue'),
    ('kod', 'Değerlendirildi', 1, 'Assessed'),
    ('kod', 'Değerlendirilmedi', 1, 'Not assessed'),
    ('kod', 'Difüzyon ağırlıklı (DWI/ADC)', 1, 'Diffusion weighted (DWI/ADC)'),
    ('kod', 'Dijital (STL)', 1, 'Digital (STL)'),
    ('kod', 'Dijital (portal/tablet)', 1, 'Digital (portal/tablet)'),
    ('kod', 'Dinamik / çok fazlı (arteriyel, portal, geç)', 1, 'Dynamic / multiphase (arterial, portal, delayed)'),
    ('kod', 'Dinleyici (cihaz bize bağlanır)', 1, 'Listener (the device connects to us)'),
    ('kod', 'Dinî', 1, 'Religious'),
    ('kod', 'Diploma', 1, 'Diploma'),
    ('kod', 'Dirsek', 1, 'Elbow'),
    ('kod', 'Diyabetik retinopati', 1, 'Diabetic retinopathy'),
    ('kod', 'Diyet', 1, 'Diet'),
    ('kod', 'Diz', 1, 'Knee'),
    ('kod', 'Diğer (SUT, Vaka Başı veya Paket İşlemler)', 1, 'Other (SUT, per case or package procedures)'),
    ('kod', 'Doküman Sürümü', 1, 'Document version'),
    ('kod', 'Doküman tipi', 1, 'Document type'),
    ('kod', 'Dolgu', 1, 'Filling'),
    ('kod', 'Dolu', 1, 'Occupied'),
    ('kod', 'Doppler (renkli + spektral)', 1, 'Doppler (colour + spectral)'),
    ('kod', 'Dosya (XML/CSV/PDF)', 1, 'File (XML/CSV/PDF)'),
    ('kod', 'Dosya / klasör', 1, 'File / folder'),
    ('kod', 'Doz onayı bekliyor', 1, 'Awaiting dose approval'),
    ('kod', 'Doç.Dr.', 1, 'Assoc. Prof.'),
    ('kod', 'Doğrudan temin', 1, 'Direct procurement'),
    ('kod', 'Doğum', 1, 'Birth'),
    ('kod', 'Doğum masası', 1, 'Delivery table'),
    ('kod', 'Doğum sonrası', 1, 'Postnatal'),
    ('kod', 'Doğum öncesi', 1, 'Antenatal'),
    ('kod', 'Dr.', 1, 'Dr'),
    ('kod', 'Dr.Dt.', 1, 'Dr DDS'),
    ('kod', 'Drenaj', 1, 'Drainage'),
    ('kod', 'Drusen', 1, 'Drusen'),
    ('kod', 'Dt.', 1, 'DDS'),
    ('kod', 'Dul', 1, 'Widowed'),
    ('kod', 'Duraklatıldı', 1, 'Paused'),
    ('kod', 'Durdu', 1, 'Stopped'),
    ('kod', 'Durduruldu', 1, 'Stopped'),
    ('kod', 'Duruş', 1, 'Downtime'),
    ('kod', 'Dönem kapandı', 1, 'Period closed'),
    ('kod', 'Dönem İcmali', 1, 'Period summary'),
    ('kod', 'Dönemde', 1, 'In the period'),
    ('kod', 'Düz metin', 1, 'Plain text'),
    ('kod', 'Düzelme', 1, 'Improvement'),
    ('kod', 'Düzelt / Ret', 1, 'Correct / reject'),
    ('kod', 'Düzeltildi', 1, 'Corrected'),
    ('kod', 'Düzenleme', 1, 'Edit'),
    ('kod', 'Düzenli', 1, 'Regular'),
    ('kod', 'Düşük', 1, 'Low'),
    ('kod', 'Düşük ↓', 1, 'Low ↓'),
    ('kod', 'Dış', 1, 'External'),
    ('kod', 'Dış Tetkik', 1, 'External test'),
    ('kod', 'Dış hekim', 1, 'External physician'),
    ('kod', 'Dış iş (müşteri)', 1, 'External job (customer)'),
    ('kod', 'Dış kayıt', 1, 'External record'),
    ('kod', 'Dış kurum', 1, 'External institution'),
    ('kod', 'Dış serviste', 1, 'At an external service'),
    ('kod', 'Dışarıda', 1, 'Outside'),
    ('kod', 'Dışlandı', 1, 'Excluded'),
    ('kod', 'E-Posta (SMTP) Sağlayıcı', 1, 'E-mail (SMTP) provider'),
    ('kod', 'ECCE', 1, 'ECCE'),
    ('kod', 'ERG / VEP', 1, 'ERG / VEP'),
    ('kod', 'EST raporu', 1, 'EST report'),
    ('kod', 'ETDRS', 1, 'ETDRS'),
    ('kod', 'EUR', 1, 'EUR'),
    ('kod', 'Edildi · bekliyor', 1, 'Done · pending'),
    ('kod', 'Edilmedi', 1, 'Not done'),
    ('kod', 'Egzersiz salonu', 1, 'Exercise room'),
    ('kod', 'Ek Not Eklendi', 1, 'Additional note added'),
    ('kod', 'Ek Tanı', 1, 'Secondary diagnosis'),
    ('kod', 'Ek görüntü istendi', 1, 'Additional images requested'),
    ('kod', 'Ek işlem', 1, 'Additional procedure'),
    ('kod', 'Ek mesai', 1, 'Overtime'),
    ('kod', 'Ek onay ister', 1, 'Requires additional approval'),
    ('kod', 'Ekranlı araç', 1, 'Display screen equipment'),
    ('kod', 'Eksik seri', 1, 'Missing series'),
    ('kod', 'El / el bileği', 1, 'Hand / wrist'),
    ('kod', 'Elden', 1, 'By hand'),
    ('kod', 'Elektriksel güvenlik', 1, 'Electrical safety'),
    ('kod', 'Elektrolit / katkı', 1, 'Electrolyte / additive'),
    ('kod', 'Elle', 1, 'Manual'),
    ('kod', 'Elle (otomatik üretme)', 1, 'Manual (do not auto-generate)'),
    ('kod', 'Elle Girilen', 1, 'Manually entered'),
    ('kod', 'Elle giriş', 1, 'Manual entry'),
    ('kod', 'Elle müdahale', 1, 'Manual intervention'),
    ('kod', 'Emekli Sandığı', 1, 'Emekli Sandığı'),
    ('kod', 'En az yüklü', 1, 'Least loaded'),
    ('kod', 'En az yüklü radyolog', 1, 'Least loaded radiologist'),
    ('kod', 'Endodonti', 1, 'Endodontics'),
    ('kod', 'Endoftalmi', 1, 'Endophthalmitis'),
    ('kod', 'Endotel', 1, 'Endothelium'),
    ('kod', 'Endotel (spekülar)', 1, 'Endothelium (specular)'),
    ('kod', 'Engeller', 1, 'Blockers'),
    ('kod', 'Epidural', 1, 'Epidural'),
    ('kod', 'Ergonomik / ağır kaldırma', 1, 'Ergonomic / heavy lifting'),
    ('kod', 'Erişim Reddi', 1, 'Access denied'),
    ('kod', 'Erkek', 1, 'Male'),
    ('kod', 'Erken kontrol', 1, 'Early follow-up'),
    ('kod', 'Erken kuru', 1, 'Early dry'),
    ('kod', 'Ertelendi', 1, 'Postponed'),
    ('kod', 'Estetik', 1, 'Aesthetic'),
    ('kod', 'Etiketlendi', 1, 'Labelled'),
    ('kod', 'Etiketsiz', 1, 'Unlabelled'),
    ('kod', 'Etkileyen', 1, 'Affecting'),
    ('kod', 'Etkileşim', 1, 'Interaction'),
    ('kod', 'Europe/Istanbul', 1, 'Europe/Istanbul'),
    ('kod', 'Ev', 1, 'Home'),
    ('kod', 'Ev Adresi', 1, 'Home address'),
    ('kod', 'Ev Hanımı', 1, 'Homemaker'),
    ('kod', 'Ev Kazası', 1, 'Domestic accident'),
    ('kod', 'Evde Sağlık', 1, 'Home healthcare'),
    ('kod', 'Eve Nakil', 1, 'Transfer home'),
    ('kod', 'Evet / Hayır', 1, 'Yes / no'),
    ('kod', 'Evli', 1, 'Married'),
    ('kod', 'Evli (Resmen Evli Ya Da Birlikte Yaşıyor)', 1, 'Married (legally married or cohabiting)'),
    ('kod', 'Eğitim Yöneticisi', 1, 'Training manager'),
    ('kod', 'Eğitim kaydı', 1, 'Training record'),
    ('kod', 'Eğitim, Öğretim  İçin Gelen Kişiler ve Bunların Eğitimleri Süresince Bakmakla Yükümlü Oldukları Yakınları', 1, 'People arriving for education or training and their dependants during that training'),
    ('kod', 'Eşi', 1, 'Spouse'),
    ('kod', 'Eşi Ölmüş', 1, 'Widowed'),
    ('kod', 'Eşleşmedi', 1, 'No match'),
    ('kod', 'FA / ICGA', 1, 'FA / ICGA'),
    ('kod', 'FAF (otofloresans)', 1, 'FAF (autofluorescence)'),
    ('kod', 'FHIR', 1, 'FHIR'),
    ('kod', 'FR · Fransa', 1, 'FR · France'),
    ('kod', 'FTR program açıldı/kapandı', 1, 'PMR programme opened/closed'),
    ('kod', 'FTR programı', 1, 'PMR programme'),
    ('kod', 'Fako + IOL', 1, 'Phaco + IOL'),
    ('kod', 'Farisimab', 1, 'Faricimab'),
    ('kod', 'Farketmez', 1, 'Any'),
    ('kod', 'Farklı (tutanak açıldı)', 1, 'Different (a report was raised)'),
    ('kod', 'Fatura / Fiş', 1, 'Invoice / receipt'),
    ('kod', 'Fatura / satın alma', 1, 'Invoice / purchasing'),
    ('kod', 'Fatura farkı', 1, 'Invoice variance'),
    ('kod', 'Faturalamada', 1, 'In billing'),
    ('kod', 'Feshedildi', 1, 'Terminated'),
    ('kod', 'Film', 1, 'Film'),
    ('kod', 'Firar', 1, 'Absconded'),
    ('kod', 'Fiyat Farkı', 1, 'Price difference'),
    ('kod', 'Fiyat farkı', 1, 'Price difference'),
    ('kod', 'Fizik Tedavi', 1, 'Physical therapy'),
    ('kod', 'Fiş / Perakende Satış Belgesi', 1, 'Receipt / retail sales document'),
    ('kod', 'Fokal / grid', 1, 'Focal / grid'),
    ('kod', 'Fonksiyonel / perfüzyon', 1, 'Functional / perfusion'),
    ('kod', 'Fotokromik', 1, 'Photochromic'),
    ('kod', 'Fotoğraf / Video', 1, 'Photo / video'),
    ('kod', 'Fuar / Etkinlik', 1, 'Trade fair / event'),
    ('kod', 'Fundus fotoğrafı', 1, 'Fundus photograph'),
    ('kod', 'Fundus kamera', 1, 'Fundus camera'),
    ('kod', 'GB · Birleşik Krallık', 1, 'GB · United Kingdom'),
    ('kod', 'GBP', 1, 'GBP'),
    ('kod', 'GRCh38', 1, 'GRCh38'),
    ('kod', 'GSS', 1, 'Universal health insurance (GSS)'),
    ('kod', 'Gaita', 1, 'Stool'),
    ('kod', 'Gebe Hastalar', 1, 'Pregnant patients'),
    ('kod', 'Gebelik sorgusu yapılacak (son adet tarihi kaydedilsin)', 1, 'Ask about pregnancy (record the last menstrual period)'),
    ('kod', 'Gece plağı', 1, 'Night guard'),
    ('kod', 'Gece çalışması', 1, 'Night work'),
    ('kod', 'Gelen (biz raporlarız)', 1, 'Incoming (we report)'),
    ('kod', 'Gelen (onlar gönderir, biz raporlarız)', 1, 'Incoming (they send, we report)'),
    ('kod', 'Geleneksel', 1, 'Traditional'),
    ('kod', 'Gelir', 1, 'Income'),
    ('kod', 'Genel - randevu talimatına uyun', 1, 'General - follow the appointment instructions'),
    ('kod', 'Genel Cerrahi', 1, 'General surgery'),
    ('kod', 'Genel Müdür', 1, 'General manager'),
    ('kod', 'Genetik', 1, 'Genetics'),
    ('kod', 'Gerekmiyor', 1, 'Not required'),
    ('kod', 'Geri Gönderildi', 1, 'Sent back'),
    ('kod', 'Geri Merkeze Sevk (Yenidoğan Nakil)', 1, 'Referral back to the centre (neonatal transfer)'),
    ('kod', 'Geri aranacak', 1, 'To be called back'),
    ('kod', 'Geri gönderildi', 1, 'Sent back'),
    ('kod', 'Geri çağırma', 1, 'Recall'),
    ('kod', 'Geri-yıkama (operasyon bildirimiyle)', 1, 'Back-wash (with an operation notice)'),
    ('kod', 'Geriye Sevk', 1, 'Referral back'),
    ('kod', 'Germline (kalıtsal)', 1, 'Germline (inherited)'),
    ('kod', 'Gerçekleşti', 1, 'Completed'),
    ('kod', 'Gezici Hizmet', 1, 'Mobile service'),
    ('kod', 'Gezici Hizmet Alan Hastalar', 1, 'Patients receiving a mobile service'),
    ('kod', 'Geçici Koruma Kapsamına Alınan Kişiler', 1, 'People under temporary protection'),
    ('kod', 'Geçici Sağlık Kuruluna Sevk', 1, 'Referral to a temporary medical board'),
    ('kod', 'Geçmiş (remisyon)', 1, 'Past (remission)'),
    ('kod', 'Giden (biz gönderiyoruz)', 1, 'Outgoing (we send)'),
    ('kod', 'Giden (dışarı gönderiyoruz)', 1, 'Outgoing (we send out)'),
    ('kod', 'Gider', 1, 'Expense'),
    ('kod', 'Gider Pusulası', 1, 'Expense voucher'),
    ('kod', 'Girişim', 1, 'Intervention'),
    ('kod', 'Girişim / İşlem', 1, 'Intervention / procedure'),
    ('kod', 'Girişimsel - 6 saat açlık, refakatçi', 1, 'Interventional - 6 h fasting, companion required'),
    ('kod', 'Girişte', 1, 'On entry'),
    ('kod', 'Gizli', 1, 'Confidential'),
    ('kod', 'Glasgow koma skalası', 1, 'Glasgow coma scale'),
    ('kod', 'Glokom', 1, 'Glaucoma'),
    ('kod', 'Goldmann aplanasyon', 1, 'Goldmann applanation'),
    ('kod', 'Gram negatif', 1, 'Gram negative'),
    ('kod', 'Gram pozitif', 1, 'Gram positive'),
    ('kod', 'Gri (Florür / Glukoz)', 1, 'Grey (fluoride / glucose)'),
    ('kod', 'Grip', 1, 'Influenza'),
    ('kod', 'Gömülü', 1, 'Impacted'),
    ('kod', 'Gönderiliyor', 1, 'Sending'),
    ('kod', 'Görev açıldı', 1, 'Task created'),
    ('kod', 'Görme alanı', 1, 'Visual field'),
    ('kod', 'Görme alanı (GA)', 1, 'Visual field (VF)'),
    ('kod', 'Görüntü bekleniyor', 1, 'Awaiting images'),
    ('kod', 'Görüntüleme (Yenidoğan Nakil)', 1, 'Imaging (neonatal transfer)'),
    ('kod', 'Görüntüleme /Cihaz Bulunmaması', 1, 'No imaging / device available'),
    ('kod', 'Görüşme / Aktivite', 1, 'Meeting / activity'),
    ('kod', 'Görüşmede', 1, 'In a call'),
    ('kod', 'Gün sonu toplu', 1, 'Batched at end of day'),
    ('kod', 'Güneş / koruyucu', 1, 'Sun / protective'),
    ('kod', 'Günlük tek fiş', 1, 'One voucher per day'),
    ('kod', 'Günlük · belge türüne göre', 1, 'Daily · by document type'),
    ('kod', 'Günübirlik', 1, 'Day case'),
    ('kod', 'Gürültü', 1, 'Noise'),
    ('kod', 'GİB yükselmesi', 1, 'IOP rise'),
    ('kod', 'Gıda', 1, 'Food'),
    ('kod', 'Gıda (portör)', 1, 'Food (carrier screening)'),
    ('kod', 'HL7', 1, 'HL7'),
    ('kod', 'HL7 ORU (MLLP)', 1, 'HL7 ORU (MLLP)'),
    ('kod', 'HL7 v2 (MLLP)', 1, 'HL7 v2 (MLLP)'),
    ('kod', 'HL7V2', 1, 'HL7v2'),
    ('kod', 'HTML (şablon değişkenli)', 1, 'HTML (with template variables)'),
    ('kod', 'Hafif', 1, 'Mild'),
    ('kod', 'Haliyle Çıkış/Taburcu', 1, 'Discharged as is'),
    ('kod', 'Hammadde', 1, 'Raw material'),
    ('kod', 'Hasar / kırık', 1, 'Damage / breakage'),
    ('kod', 'Hasta / yakını talebi', 1, 'Patient / relative request'),
    ('kod', 'Hasta Başvurusu', 1, 'Patient encounter'),
    ('kod', 'Hasta Beyanı', 1, 'Patient declaration'),
    ('kod', 'Hasta beyanı', 1, 'Patient declaration'),
    ('kod', 'Hasta ek katkısı', 1, 'Additional patient contribution'),
    ('kod', 'Hasta kaydı', 1, 'Patient record'),
    ('kod', 'Hasta kendi imkânı', 1, 'Patient''s own means'),
    ('kod', 'Hasta payı (provizyon sonrası)', 1, 'Patient share (after authorisation)'),
    ('kod', 'Hasta reddetti', 1, 'Patient refused'),
    ('kod', 'Hasta İsteği', 1, 'Patient request'),
    ('kod', 'Hastanede  Testin (Laboratuvar Tetkiki) Yapılmaması', 1, 'The test (laboratory) is not performed at the hospital'),
    ('kod', 'Hastanede Özellikli Biriminin Olmaması', 1, 'The hospital has no specialised unit'),
    ('kod', 'Hastanın İsteği Üzerine', 1, 'At the patient''s request'),
    ('kod', 'Hatanede Özellikli Birimin Doluluğu', 1, 'The specialised unit at the hospital is full'),
    ('kod', 'Hazırlanacak', 1, 'To be prepared'),
    ('kod', 'Hazırlanmış, kullanılmadı', 1, 'Prepared, not used'),
    ('kod', 'Hazırlanıyor', 1, 'Being prepared'),
    ('kod', 'Hekim Yönlendirmesi', 1, 'Physician referral'),
    ('kod', 'Hekim unvanı', 1, 'Physician title'),
    ('kod', 'Hekim İhtiyacı Nedeniyle', 1, 'Due to the need for a physician'),
    ('kod', 'Hekimin İzinli/Raporlu/Geçici Görevde Olması', 1, 'The physician is on leave/sick leave/temporary duty'),
    ('kod', 'Hematoloji', 1, 'Haematology'),
    ('kod', 'Hemoliz (H)', 1, 'Haemolysis (H)'),
    ('kod', 'Hemolizli', 1, 'Haemolysed'),
    ('kod', 'Hemşirelik', 1, 'Nursing'),
    ('kod', 'Hepatit A', 1, 'Hepatitis A'),
    ('kod', 'Hepatit B', 1, 'Hepatitis B'),
    ('kod', 'Her hafta', 1, 'Every week'),
    ('kod', 'Her yeni lot', 1, 'Every new lot'),
    ('kod', 'Her İki Cinsiyet/Belirsiz', 1, 'Both sexes / unspecified'),
    ('kod', 'Herkese Açık', 1, 'Public'),
    ('kod', 'Hidroterapi', 1, 'Hydrotherapy'),
    ('kod', 'Hijyen', 1, 'Hygiene'),
    ('kod', 'Hikaye', 1, 'History'),
    ('kod', 'Hizmet (alt) tipi', 1, 'Service (sub) type'),
    ('kod', 'Hizmet / Proje', 1, 'Service / project'),
    ('kod', 'Hizmet kartından', 1, 'From the service card'),
    ('kod', 'Hormon', 1, 'Hormone'),
    ('kod', 'Hurda', 1, 'Scrap'),
    ('kod', 'Hükümlü Hastalar', 1, 'Convicted patients'),
    ('kod', 'I', 1, 'I'),
    ('kod', 'ICD-10 tanı', 1, 'ICD-10 diagnosis'),
    ('kod', 'ICL', 1, 'ICL'),
    ('kod', 'II', 1, 'II'),
    ('kod', 'III', 1, 'III'),
    ('kod', 'IM', 1, 'IM'),
    ('kod', 'IQ · Irak', 1, 'IQ · Iraq'),
    ('kod', 'IT Destek', 1, 'IT support'),
    ('kod', 'IV', 1, 'IV'),
    ('kod', 'Iade', 1, 'Return'),
    ('kod', 'Iade Edildi', 1, 'Returned'),
    ('kod', 'Iptal', 1, 'Cancelled'),
    ('kod', 'Iptal / Geri Alma', 1, 'Cancellation / reversal'),
    ('kod', 'Is Avansi Kasasi', 1, 'Work advance cash desk'),
    ('kod', 'Islak İmza', 1, 'Wet signature'),
    ('kod', 'JPY', 1, 'JPY'),
    ('kod', 'K', 1, 'F'),
    ('kod', 'KDV İstisna', 1, 'VAT exempt'),
    ('kod', 'KK ret sonrası tekrar', 1, 'Repeat after QC rejection'),
    ('kod', 'KKK', 1, 'PPE'),
    ('kod', 'KOOS', 1, 'KOOS'),
    ('kod', 'KVKK Aydınlatma', 1, 'KVKK privacy notice'),
    ('kod', 'Kabul (|SDI| ≤ 2)', 1, 'Acceptable (|SDI| ≤ 2)'),
    ('kod', 'Kabul edilemez (|SDI| > 3)', 1, 'Unacceptable (|SDI| > 3)'),
    ('kod', 'Kabul · iade', 1, 'Acceptance · return'),
    ('kod', 'Kadın', 1, 'Female'),
    ('kod', 'Kadın Doğum', 1, 'Obstetrics and gynaecology'),
    ('kod', 'Kaldırıldı', 1, 'Removed'),
    ('kod', 'Kalibrasyon kaydı', 1, 'Calibration record'),
    ('kod', 'Kalibrasyon kaynaklı', 1, 'Calibration related'),
    ('kod', 'Kalite kontrol', 1, 'Quality control'),
    ('kod', 'Kalite uygunsuzluğu', 1, 'Quality nonconformity'),
    ('kod', 'Kalp pili, koklear implant, nörostimülatör sorgulanacak', 1, 'Ask about a pacemaker, cochlear implant or neurostimulator'),
    ('kod', 'Kalça', 1, 'Hip'),
    ('kod', 'Kan alma', 1, 'Blood collection'),
    ('kod', 'Kan kültür şişesi', 1, 'Blood culture bottle'),
    ('kod', 'Kan ürünü', 1, 'Blood product'),
    ('kod', 'Kanal tedavili', 1, 'Root-treated'),
    ('kod', 'Kanal tedavisi', 1, 'Root canal treatment'),
    ('kod', 'Kanama', 1, 'Bleeding'),
    ('kod', 'Kanvas (tablet)', 1, 'Canvas (tablet)'),
    ('kod', 'Kapak / adneks', 1, 'Lid / adnexa'),
    ('kod', 'Kapalı (arıza/tadilat)', 1, 'Closed (fault/refurbishment)'),
    ('kod', 'Kapatıldı', 1, 'Closed'),
    ('kod', 'Karar / İşlem', 1, 'Decision / action'),
    ('kod', 'Karar Verici', 1, 'Decision maker'),
    ('kod', 'Karar verildi', 1, 'Decided'),
    ('kod', 'Kargo', 1, 'Courier'),
    ('kod', 'Kargo / nakliye firması', 1, 'Courier / carrier'),
    ('kod', 'Karma', 1, 'Mixed'),
    ('kod', 'Karma (SGK + Tamamlayıcı)', 1, 'Mixed (SGK + complementary)'),
    ('kod', 'Karsiliksiz', 1, 'Dishonoured'),
    ('kod', 'Karttan', 1, 'From the card'),
    ('kod', 'Karyotip', 1, 'Karyotype'),
    ('kod', 'Karışık', 1, 'Mixed'),
    ('kod', 'Karşılama Oranı (%)', 1, 'Coverage rate (%)'),
    ('kod', 'Karşılaştırma', 1, 'Comparison'),
    ('kod', 'Karşılıksız', 1, 'Dishonoured'),
    ('kod', 'Kasaya', 1, 'To the cash desk'),
    ('kod', 'Katarakt', 1, 'Cataract'),
    ('kod', 'Kateter Lab', 1, 'Cath lab'),
    ('kod', 'Katı (agar)', 1, 'Solid (agar)'),
    ('kod', 'Katılım Payı (sabit tutar)', 1, 'Co-payment (fixed amount)'),
    ('kod', 'Kaybedildi', 1, 'Lost'),
    ('kod', 'Kaydedildi', 1, 'Saved'),
    ('kod', 'Kayıp', 1, 'Loss'),
    ('kod', 'Kayıp / HEK', 1, 'Loss / write-off'),
    ('kod', 'Kayıt bekliyor', 1, 'Awaiting registration'),
    ('kod', 'Kayıtlı', 1, 'Registered'),
    ('kod', 'Kazandı', 1, 'Won'),
    ('kod', 'Kazanıldı', 1, 'Won'),
    ('kod', 'Kağıt tarama', 1, 'Paper scan'),
    ('kod', 'Kemoterapi', 1, 'Chemotherapy'),
    ('kod', 'Kendi garantimiz', 1, 'Our own warranty'),
    ('kod', 'Kendi imkânı', 1, 'Own means'),
    ('kod', 'Kendi imkânıyla', 1, 'By their own means'),
    ('kod', 'Kendi isteğiyle', 1, 'At their own request'),
    ('kod', 'Kendi İmkânıyla', 1, 'By their own means'),
    ('kod', 'Keratokonus', 1, 'Keratoconus'),
    ('kod', 'Keratoplasti (PK/DALK/DMEK)', 1, 'Keratoplasty (PK/DALK/DMEK)'),
    ('kod', 'Kesildi', 1, 'Cut off'),
    ('kod', 'Kesinleşti', 1, 'Finalised'),
    ('kod', 'Kiev (UTC+2, yaz +3)', 1, 'Kyiv (UTC+2, summer +3)'),
    ('kod', 'Kilitli', 1, 'Locked'),
    ('kod', 'Kimlik tipi', 1, 'Identity type'),
    ('kod', 'Kimyasal / solvent', 1, 'Chemical / solvent'),
    ('kod', 'Kira', 1, 'Rent'),
    ('kod', 'Kiralama', 1, 'Leasing'),
    ('kod', 'Kişiye atanır', 1, 'Assigned to a person'),
    ('kod', 'Klasör izleme', 1, 'Folder watch'),
    ('kod', 'Klinik + ev', 1, 'Clinic + home'),
    ('kod', 'Klinik / Bölüm (bölüm ile eşleşir)', 1, 'Clinic / department (matches the department)'),
    ('kod', 'Klinik Yatak (Yataklı Servisin) Doluluğu', 1, 'The clinical ward is full'),
    ('kod', 'Klinik korelasyon', 1, 'Clinical correlation'),
    ('kod', 'Klinik nakli', 1, 'Clinic transfer'),
    ('kod', 'Klostrofobi öyküsü - sedasyon gerekebilir, hekime danışın', 1, 'History of claustrophobia - sedation may be needed, consult the physician'),
    ('kod', 'Koagülasyon', 1, 'Coagulation'),
    ('kod', 'Kok', 1, 'Coccus'),
    ('kod', 'Kokobasil', 1, 'Coccobacillus'),
    ('kod', 'Komisyon onayladı', 1, 'Approved by the committee'),
    ('kod', 'Kompozit dolgu', 1, 'Composite filling'),
    ('kod', 'Komut', 1, 'Command'),
    ('kod', 'Kongre / eğitim', 1, 'Congress / training'),
    ('kod', 'Konsinye Alış', 1, 'Consignment purchase'),
    ('kod', 'Konsinye Satış', 1, 'Consignment sale'),
    ('kod', 'Konsultasyon Muayenesi', 1, 'Consultation examination'),
    ('kod', 'Konsültasyon (Yenidoğan Nakil)', 1, 'Consultation (neonatal transfer)'),
    ('kod', 'Kontakt lens', 1, 'Contact lens'),
    ('kod', 'Kontakt lensle', 1, 'With contact lenses'),
    ('kod', 'Kontrast alerjisi öyküsü - premedikasyon protokolü uygulanır', 1, 'History of contrast allergy - the premedication protocol applies'),
    ('kod', 'Kontrastlı (tek faz)', 1, 'With contrast (single phase)'),
    ('kod', 'Kontrastlı çekimde 4 saat aç gelin, böbrek değerleriniz (kreatinin) yanınızda olsun. Metal içeren giysi ve takıları çıkarın.', 1, 'For a contrast study, fast for 4 hours and bring your kidney results (creatinine). Remove clothing and jewellery containing metal.'),
    ('kod', 'Kontrastsız + kontrastlı', 1, 'Without and with contrast'),
    ('kod', 'Kontrol Altında', 1, 'Under control'),
    ('kod', 'Kontrol Muayenesi', 1, 'Follow-up examination'),
    ('kod', 'Kontrol edildi', 1, 'Checked'),
    ('kod', 'Kontrol edilmedi', 1, 'Not checked'),
    ('kod', 'Kontrol listesi', 1, 'Checklist'),
    ('kod', 'Kontrollü', 1, 'Controlled'),
    ('kod', 'Kornea boyanması', 1, 'Corneal staining'),
    ('kod', 'Kornea lekesi / nefelyon', 1, 'Corneal scar / nebula'),
    ('kod', 'Kornea topografisi', 1, 'Corneal topography'),
    ('kod', 'Kornea ödemi', 1, 'Corneal oedema'),
    ('kod', 'Koruyucu (nötropenik)', 1, 'Protective (neutropenic)'),
    ('kod', 'Kreatinin / eGFR sonucu görülmeden kontrast verilmez', 1, 'Contrast is not given before the creatinine / eGFR result is seen'),
    ('kod', 'Kritik stok', 1, 'Critical stock'),
    ('kod', 'Kron', 1, 'Crown'),
    ('kod', 'Kuduz', 1, 'Rabies'),
    ('kod', 'Kullanıcı (e-imza)', 1, 'User (e-signature)'),
    ('kod', 'Kullanılmıyor', 1, 'Not in use'),
    ('kod', 'Kullanım dışı', 1, 'Out of service'),
    ('kod', 'Kullanım kılavuzu', 1, 'User manual'),
    ('kod', 'Kullanımda', 1, 'In use'),
    ('kod', 'Kupon Kasasi', 1, 'Coupon cash desk'),
    ('kod', 'Kupon Kasası', 1, 'Coupon cash desk'),
    ('kod', 'Kur Değerlemesi', 1, 'Currency revaluation'),
    ('kod', 'Kur Farkı', 1, 'Exchange difference'),
    ('kod', 'Kurum Aracı', 1, 'Institution vehicle'),
    ('kod', 'Kurum Dışı Sevk', 1, 'Referral outside the institution'),
    ('kod', 'Kurum Dışına Sevk', 1, 'Referral out of the institution'),
    ('kod', 'Kurum ambulansı', 1, 'Institution ambulance'),
    ('kod', 'Kurum aracı', 1, 'Institution vehicle'),
    ('kod', 'Kurum dışına sevk', 1, 'Referral out of the institution'),
    ('kod', 'Kurum içi nakil', 1, 'Internal transfer'),
    ('kod', 'Kurum ödüyor', 1, 'The institution pays'),
    ('kod', 'Kurum İçi', 1, 'Internal'),
    ('kod', 'Kurum İçi Sevk', 1, 'Internal referral'),
    ('kod', 'Kurum İçine Sevk', 1, 'Referral into the institution'),
    ('kod', 'Kurumu Öder', 1, 'The institution pays'),
    ('kod', 'Kusma', 1, 'Vomiting'),
    ('kod', 'Kuvöz', 1, 'Incubator'),
    ('kod', 'Kuyrukta', 1, 'Queued'),
    ('kod', 'Kâbil (UTC+4:30)', 1, 'Kabul (UTC+4:30)'),
    ('kod', 'Köprü', 1, 'Bridge'),
    ('kod', 'Köprü ayağı', 1, 'Bridge abutment'),
    ('kod', 'Köprü gövdesi', 1, 'Bridge pontic'),
    ('kod', 'Kötü', 1, 'Poor'),
    ('kod', 'Küf', 1, 'Mould'),
    ('kod', 'Kültür', 1, 'Culture'),
    ('kod', 'Kür başı', 1, 'Start of cycle'),
    ('kod', 'Kür sonu', 1, 'End of cycle'),
    ('kod', 'Küçük cerrahi', 1, 'Minor surgery'),
    ('kod', 'Kırmızı', 1, 'Red'),
    ('kod', 'Kırmızı (narkotik)', 1, 'Red (narcotic)'),
    ('kod', 'Kırık', 1, 'Fracture'),
    ('kod', 'Kısa mola', 1, 'Short break'),
    ('kod', 'Kısmi Dönüştü', 1, 'Partially converted'),
    ('kod', 'Kısmi Onay', 1, 'Partial approval'),
    ('kod', 'Kısmi kabul', 1, 'Partial acceptance'),
    ('kod', 'Kısmi sarf', 1, 'Partial consumption'),
    ('kod', 'Kısmi tamamlandı', 1, 'Partially completed'),
    ('kod', 'Kısmi teslim', 1, 'Partial delivery'),
    ('kod', 'Kısmi yanıt', 1, 'Partial response'),
    ('kod', 'Kıst dönem', 1, 'Pro-rata period'),
    ('kod', 'Kızı', 1, 'Daughter'),
    ('kod', 'LOGO GO/GOLD', 1, 'LOGO GO/GOLD'),
    ('kod', 'Laboratuvar / Görüntüleme', 1, 'Laboratory / imaging'),
    ('kod', 'Laser spotu', 1, 'Laser spot'),
    ('kod', 'Lateks', 1, 'Latex'),
    ('kod', 'Lea (pediatri)', 1, 'Lea (paediatric)'),
    ('kod', 'Link Açılma', 1, 'Link opened'),
    ('kod', 'Lipemi (L)', 1, 'Lipaemia (L)'),
    ('kod', 'Lipemik', 1, 'Lipaemic'),
    ('kod', 'Liste fiyatı', 1, 'List price'),
    ('kod', 'Lokal', 1, 'Local'),
    ('kod', 'Lokal / subtenon', 1, 'Local / sub-Tenon'),
    ('kod', 'Lomber', 1, 'Lumbar'),
    ('kod', 'Londra (UTC+0, yaz +1)', 1, 'London (UTC+0, summer +1)'),
    ('kod', 'Lysholm (diz)', 1, 'Lysholm (knee)'),
    ('kod', 'MEDULA (SGK)', 1, 'MEDULA (SGK)'),
    ('kod', 'MHRS', 1, 'MHRS'),
    ('kod', 'MHRS ile Sevk', 1, 'Referral via MHRS'),
    ('kod', 'MLPA', 1, 'MLPA'),
    ('kod', 'MR', 1, 'MRI'),
    ('kod', 'MR - metal / implant uyarısı', 1, 'MRI - metal / implant warning'),
    ('kod', 'Maas Avansi Kasasi', 1, 'Salary advance cash desk'),
    ('kod', 'Maaş Yazısı', 1, 'Salary letter'),
    ('kod', 'Mali işler', 1, 'Finance'),
    ('kod', 'Mali/Muhasebe', 1, 'Finance/accounting'),
    ('kod', 'Malzeme raporu', 1, 'Material report'),
    ('kod', 'Malzeme tipi', 1, 'Material type'),
    ('kod', 'Mamografi', 1, 'Mammography'),
    ('kod', 'Mamografi - deodorant yok, adet 1. hafta', 1, 'Mammography - no deodorant, first week after menstruation'),
    ('kod', 'Mantar', 1, 'Fungus'),
    ('kod', 'Manuel', 1, 'Manual'),
    ('kod', 'Manuel terapi', 1, 'Manual therapy'),
    ('kod', 'Masaüstü telefon', 1, 'Desk phone'),
    ('kod', 'Masraf Beyanı', 1, 'Expense claim'),
    ('kod', 'Mavi (Sitrat / Koagülasyon)', 1, 'Blue (citrate / coagulation)'),
    ('kod', 'Mavi Kartlılar', 1, 'Blue Card holders'),
    ('kod', 'Mavi Kod', 1, 'Blue Code'),
    ('kod', 'Mavi ışık filtresi', 1, 'Blue light filter'),
    ('kod', 'Maya', 1, 'Yeast'),
    ('kod', 'Mazeret', 1, 'Excused'),
    ('kod', 'Medula Kabul', 1, 'MEDULA admission'),
    ('kod', 'Medula kabul', 1, 'MEDULA admission'),
    ('kod', 'Memnuniyet anketi', 1, 'Satisfaction survey'),
    ('kod', 'Memur', 1, 'Civil servant'),
    ('kod', 'Merkez', 1, 'Head office'),
    ('kod', 'Merkez Kasa', 1, 'Head office cash desk'),
    ('kod', 'Merkez dışı', 1, 'Outside the head office'),
    ('kod', 'Merkezi tutan', 1, 'Kept centrally'),
    ('kod', 'Mesai içi', 1, 'Within working hours'),
    ('kod', 'Mesaj / sistem', 1, 'Message / system'),
    ('kod', 'Mesaj gönderildi', 1, 'Message sent'),
    ('kod', 'Meslek Hastalığı', 1, 'Occupational disease'),
    ('kod', 'Meslek hastalığı', 1, 'Occupational disease'),
    ('kod', 'Meslek hastalığı şüphesi', 1, 'Suspected occupational disease'),
    ('kod', 'Metal dumanı / kaynak', 1, 'Metal fume / welding'),
    ('kod', 'Metformin kullanımı - kontrast sonrası 48 saat kesilir', 1, 'Metformin use - stop for 48 hours after contrast'),
    ('kod', 'Mevcut Müşteri / Tekrar Satış', 1, 'Existing customer / repeat sale'),
    ('kod', 'Mevcut gözlük (lensmetre)', 1, 'Current spectacles (lensmeter)'),
    ('kod', 'Mevcut gözlükle', 1, 'With current spectacles'),
    ('kod', 'Mevsimlik', 1, 'Seasonal'),
    ('kod', 'Miadı geçti', 1, 'Expired'),
    ('kod', 'Mikroaerofil', 1, 'Microaerophilic'),
    ('kod', 'Mikroanevrizma', 1, 'Microaneurysm'),
    ('kod', 'Mikroarray', 1, 'Microarray'),
    ('kod', 'Mikrobiyoloji', 1, 'Microbiology'),
    ('kod', 'Mikropuls', 1, 'Micropulse'),
    ('kod', 'Miktar farkı', 1, 'Quantity variance'),
    ('kod', 'Millî', 1, 'National'),
    ('kod', 'Mineral (cam)', 1, 'Mineral (glass)'),
    ('kod', 'Mitokondriyal', 1, 'Mitochondrial'),
    ('kod', 'Mobil', 1, 'Mobile'),
    ('kod', 'Mobilya', 1, 'Furniture'),
    ('kod', 'Mola', 1, 'Break'),
    ('kod', 'Mor', 1, 'Purple'),
    ('kod', 'Mor (EDTA / Hemogram)', 1, 'Purple (EDTA / CBC)'),
    ('kod', 'Moskova (UTC+3)', 1, 'Moscow (UTC+3)'),
    ('kod', 'Muayene / görüntüleme', 1, 'Examination / imaging'),
    ('kod', 'Muayene istemi', 1, 'Examination order'),
    ('kod', 'Multifokal', 1, 'Multifocal'),
    ('kod', 'Mutfak', 1, 'Kitchen'),
    ('kod', 'Müdahalede', 1, 'In intervention'),
    ('kod', 'Mükemmel', 1, 'Excellent'),
    ('kod', 'Mükerrer', 1, 'Duplicate'),
    ('kod', 'Mülteci ve Kacak Giris', 1, 'Refugees and irregular entrants'),
    ('kod', 'Müzakere', 1, 'Negotiation'),
    ('kod', 'Müşahede', 1, 'Observation'),
    ('kod', 'NCT (hava üflemeli)', 1, 'NCT (air puff)'),
    ('kod', 'NDI (boyun)', 1, 'NDI (neck)'),
    ('kod', 'NGS panel', 1, 'NGS panel'),
    ('kod', 'NL · Hollanda', 1, 'NL · Netherlands'),
    ('kod', 'NRS-2002 beslenme', 1, 'NRS-2002 nutrition'),
    ('kod', 'Nazım', 1, 'Control account'),
    ('kod', 'Net tutar', 1, 'Net amount'),
    ('kod', 'New York (UTC-5, yaz -4)', 1, 'New York (UTC-5, summer -4)'),
    ('kod', 'Nitelendirme', 1, 'Qualification'),
    ('kod', 'Normal (eşit tutarlı)', 1, 'Normal (equal instalments)'),
    ('kod', 'Normal hesap dönemi', 1, 'Normal accounting period'),
    ('kod', 'Normal yatış', 1, 'Normal admission'),
    ('kod', 'Numune Alındı', 1, 'Specimen collected'),
    ('kod', 'Nöbet devri', 1, 'Shift handover'),
    ('kod', 'Nörolojik / genel', 1, 'Neurological / general'),
    ('kod', 'O anki nöbetçi', 1, 'Whoever is on call'),
    ('kod', 'OCT', 1, 'OCT'),
    ('kod', 'OCT — RNFL / GCC', 1, 'OCT — RNFL / GCC'),
    ('kod', 'OCT — maküla', 1, 'OCT — macula'),
    ('kod', 'OCT — ön segment', 1, 'OCT — anterior segment'),
    ('kod', 'OCT-A', 1, 'OCT-A'),
    ('kod', 'OD', 1, 'OD'),
    ('kod', 'OD (sağ)', 1, 'OD (right)'),
    ('kod', 'ORKA', 1, 'ORKA'),
    ('kod', 'OS', 1, 'OS'),
    ('kod', 'OS (sol)', 1, 'OS (left)'),
    ('kod', 'OU (her iki)', 1, 'OU (both)'),
    ('kod', 'Obez Hastalar', 1, 'Obese patients'),
    ('kod', 'Oda talebi', 1, 'Room request'),
    ('kod', 'Odendi', 1, 'Paid'),
    ('kod', 'Okunuyor', 1, 'Being read'),
    ('kod', 'Okutuldu', 1, 'Scanned'),
    ('kod', 'Olay Afet', 1, 'Incident / disaster'),
    ('kod', 'Olumlu (taahhüdün üstünde)', 1, 'Positive (above commitment)'),
    ('kod', 'Omuz', 1, 'Shoulder'),
    ('kod', 'On beş günlük', 1, 'Fortnightly'),
    ('kod', 'Onay / ret', 1, 'Approval / rejection'),
    ('kod', 'Onaya Gönderme', 1, 'Send for approval'),
    ('kod', 'Onayladı', 1, 'Approved'),
    ('kod', 'Onkolojik', 1, 'Oncological'),
    ('kod', 'Op.Dr.', 1, 'Op. Dr'),
    ('kod', 'Optiğe verildi', 1, 'Sent to the optician'),
    ('kod', 'Oral', 1, 'Oral'),
    ('kod', 'Oral / parenteral', 1, 'Oral / parenteral'),
    ('kod', 'Organ Nakli Sebebiyle', 1, 'Due to organ transplant'),
    ('kod', 'Organik (CR-39)', 1, 'Organic (CR-39)'),
    ('kod', 'Orta', 1, 'Moderate'),
    ('kod', 'Orta kuru', 1, 'Intermediate dry'),
    ('kod', 'Ortodonti', 1, 'Orthodontics'),
    ('kod', 'Ortodonti apareyi', 1, 'Orthodontic appliance'),
    ('kod', 'Ortokeratoloji', 1, 'Orthokeratology'),
    ('kod', 'Ortopedi', 1, 'Orthopaedics'),
    ('kod', 'Oswestry (ODI)', 1, 'Oswestry (ODI)'),
    ('kod', 'Otomatik (kod listesi var)', 1, 'Automatic (a code list exists)'),
    ('kod', 'Otomatik (kural)', 1, 'Automatic (rule)'),
    ('kod', 'Otorefraktometre', 1, 'Autorefractometer'),
    ('kod', 'Otorefraktometre / keratometre', 1, 'Autorefractometer / keratometer'),
    ('kod', 'Otozomal dominant', 1, 'Autosomal dominant'),
    ('kod', 'Otozomal resesif', 1, 'Autosomal recessive'),
    ('kod', 'Oğlu', 1, 'Son'),
    ('kod', 'PCR / RT-PCR', 1, 'PCR / RT-PCR'),
    ('kod', 'PDF / e-posta', 1, 'PDF / e-mail'),
    ('kod', 'PO (ağızdan)', 1, 'PO (by mouth)'),
    ('kod', 'PPA (beta)', 1, 'PPA (beta)'),
    ('kod', 'PPV (vitrektomi)', 1, 'PPV (vitrectomy)'),
    ('kod', 'PRN (gerektiğinde)', 1, 'PRN (as needed)'),
    ('kod', 'PRP (panretinal)', 1, 'PRP (panretinal)'),
    ('kod', 'Paket / Set', 1, 'Package / set'),
    ('kod', 'Pakimetre', 1, 'Pachymeter'),
    ('kod', 'Pakimetri haritası', 1, 'Pachymetry map'),
    ('kod', 'Panik ⚠', 1, 'Panic ⚠'),
    ('kod', 'Parazit', 1, 'Parasite'),
    ('kod', 'Parenteral', 1, 'Parenteral'),
    ('kod', 'Paris (UTC+1, yaz +2)', 1, 'Paris (UTC+1, summer +2)'),
    ('kod', 'Parsiyel protez', 1, 'Partial denture'),
    ('kod', 'Parça bekliyor', 1, 'Waiting for parts'),
    ('kod', 'Pasif (eski sürüm)', 1, 'Inactive (previous version)'),
    ('kod', 'Patoloji', 1, 'Pathology'),
    ('kod', 'Paylaşım Linki', 1, 'Share link'),
    ('kod', 'Pazarlık', 1, 'Negotiated procedure'),
    ('kod', 'Pediatrik hasta - doz ayarı (ALARA) ve refakatçi kurşun önlük', 1, 'Paediatric patient - adjust dose (ALARA) and provide a lead apron for the companion'),
    ('kod', 'Pedodonti', 1, 'Paediatric dentistry'),
    ('kod', 'Pedodonti (veli)', 1, 'Paediatric dentistry (guardian)'),
    ('kod', 'Pembe Kod', 1, 'Pink Code'),
    ('kod', 'Performans Dışı Hastalar', 1, 'Patients outside performance scoring'),
    ('kod', 'Periferi (saat kadranı)', 1, 'Periphery (clock hours)'),
    ('kod', 'Periodontal', 1, 'Periodontal'),
    ('kod', 'Perioküler enjeksiyon', 1, 'Periocular injection'),
    ('kod', 'Periyodik', 1, 'Periodic'),
    ('kod', 'Periyodik bakım', 1, 'Preventive maintenance'),
    ('kod', 'Personel Avansı', 1, 'Employee advance'),
    ('kod', 'Personel İzni', 1, 'Employee leave'),
    ('kod', 'Pinhole', 1, 'Pinhole'),
    ('kod', 'Pitozis', 1, 'Ptosis'),
    ('kod', 'Plan Kapandı', 1, 'Plan closed'),
    ('kod', 'Planlandı', 1, 'Scheduled'),
    ('kod', 'Plazma', 1, 'Plasma'),
    ('kod', 'Polarize', 1, 'Polarised'),
    ('kod', 'Polikarbonat', 1, 'Polycarbonate'),
    ('kod', 'Poliklinik', 1, 'Outpatient clinic'),
    ('kod', 'Poliklinikten', 1, 'From the outpatient clinic'),
    ('kod', 'Polis/Jandarma', 1, 'Police/gendarmerie'),
    ('kod', 'Poliçe tipi', 1, 'Policy type'),
    ('kod', 'Poliçe türü', 1, 'Policy type'),
    ('kod', 'Portal', 1, 'Portal'),
    ('kod', 'Portfoyde', 1, 'In portfolio'),
    ('kod', 'Portfoye Giris', 1, 'Entry into portfolio'),
    ('kod', 'Portföyde', 1, 'In portfolio'),
    ('kod', 'Postop', 1, 'Post-op'),
    ('kod', 'Postop kontrol', 1, 'Post-op follow-up'),
    ('kod', 'Premedikasyon', 1, 'Premedication'),
    ('kod', 'Preop', 1, 'Pre-op'),
    ('kod', 'Primli', 1, 'Commission bearing'),
    ('kod', 'Prof.Dr.', 1, 'Prof.'),
    ('kod', 'Progresif', 1, 'Progressive'),
    ('kod', 'Protetik', 1, 'Prosthetic'),
    ('kod', 'Protez', 1, 'Prosthesis'),
    ('kod', 'Prova', 1, 'Try-in'),
    ('kod', 'Pterjium', 1, 'Pterygium'),
    ('kod', 'Pterjiyum', 1, 'Pterygium'),
    ('kod', 'Push', 1, 'Push'),
    ('kod', 'Pıhtılı', 1, 'Clotted'),
    ('kod', 'R0 — retinopati yok', 1, 'R0 — no retinopathy'),
    ('kod', 'R1 — hafif NPDR', 1, 'R1 — mild NPDR'),
    ('kod', 'R2 — orta NPDR', 1, 'R2 — moderate NPDR'),
    ('kod', 'R3 — ağır NPDR', 1, 'R3 — severe NPDR'),
    ('kod', 'R4 — PDR', 1, 'R4 — PDR'),
    ('kod', 'REST', 1, 'REST'),
    ('kod', 'RET (sonuç verilemez)', 1, 'REJ (no result can be issued)'),
    ('kod', 'RGP (sert gaz geçirgen)', 1, 'RGP (rigid gas permeable)'),
    ('kod', 'RU · Rusya', 1, 'RU · Russia'),
    ('kod', 'RVG / panoramik', 1, 'RVG / panoramic'),
    ('kod', 'Radyasyon', 1, 'Radiation'),
    ('kod', 'Ramak kala', 1, 'Near miss'),
    ('kod', 'Randevu hatırlatma', 1, 'Appointment reminder'),
    ('kod', 'Randevu oluştu', 1, 'Appointment created'),
    ('kod', 'Randevu verildi', 1, 'Appointment booked'),
    ('kod', 'Ranibizumab', 1, 'Ranibizumab'),
    ('kod', 'Raporlanıyor', 1, 'Being reported'),
    ('kod', 'Reaktif lot değişimi', 1, 'Reagent lot change'),
    ('kod', 'Reddedildi', 1, 'Rejected'),
    ('kod', 'Reddetti', 1, 'Refused'),
    ('kod', 'Refakat', 1, 'Accompanying'),
    ('kod', 'Referans sertifikası', 1, 'Reference certificate'),
    ('kod', 'Refraktif (LASIK/PRK/SMILE)', 1, 'Refractive (LASIK/PRK/SMILE)'),
    ('kod', 'Refraktif değerlendirme', 1, 'Refractive assessment'),
    ('kod', 'Rektal', 1, 'Rectal'),
    ('kod', 'Restoratif', 1, 'Restorative'),
    ('kod', 'Resüsitasyon', 1, 'Resuscitation'),
    ('kod', 'Retina dekolmanı', 1, 'Retinal detachment'),
    ('kod', 'Retina kanaması', 1, 'Retinal haemorrhage'),
    ('kod', 'Retinopeksi', 1, 'Retinopexy'),
    ('kod', 'Retinoskopi', 1, 'Retinoscopy'),
    ('kod', 'Riyad (UTC+3)', 1, 'Riyadh (UTC+3)'),
    ('kod', 'Robotik', 1, 'Robotic'),
    ('kod', 'Roland-Morris', 1, 'Roland-Morris'),
    ('kod', 'Rutin', 1, 'Routine'),
    ('kod', 'Rutin - kontrastsız', 1, 'Routine - without contrast'),
    ('kod', 'Röntgen', 1, 'X-ray'),
    ('kod', 'Röntgen - takı çıkarma, gebelik sorgusu', 1, 'X-ray - remove jewellery, ask about pregnancy'),
    ('kod', 'S. Meslek Makbuzu', 1, 'Self-employment receipt'),
    ('kod', 'SA · S. Arabistan', 1, 'SA · Saudi Arabia'),
    ('kod', 'SAR · Riyal', 1, 'SAR · riyal'),
    ('kod', 'SC', 1, 'SC'),
    ('kod', 'SF-12 fiziksel', 1, 'SF-12 physical'),
    ('kod', 'SGK', 1, 'SGK'),
    ('kod', 'SGK (Sosyal Güvenlik Kurumu)', 1, 'SGK (Social Security Institution)'),
    ('kod', 'SGK Hizmet Dökümü', 1, 'SGK service statement'),
    ('kod', 'SGK Kapsamında Yer Alan Yabancı Uyruklu  Kişiler / İkili Sosyal Güvenlik Sözleşmeleri Kapsamındaki Kişiler', 1, 'Foreign nationals covered by SGK / people under bilateral social security agreements'),
    ('kod', 'SGK katılım payı (ciro dışı)', 1, 'SGK co-payment (excluded from turnover)'),
    ('kod', 'SGK payı', 1, 'SGK share'),
    ('kod', 'SGK provizyon', 1, 'SGK authorisation'),
    ('kod', 'SKRS / Sağlık.NET Kod Sunucusu', 1, 'SKRS / Sağlık.NET code server'),
    ('kod', 'SLT', 1, 'SLT'),
    ('kod', 'SMS', 1, 'SMS'),
    ('kod', 'SMS OTP', 1, 'SMS OTP'),
    ('kod', 'SMS Sağlayıcı', 1, 'SMS provider'),
    ('kod', 'SSK', 1, 'SSK'),
    ('kod', 'SSK Kurum Personeli', 1, 'SSK institution staff'),
    ('kod', 'SUT (SGK)', 1, 'SUT (SGK)'),
    ('kod', 'SUT işlem', 1, 'SUT procedure'),
    ('kod', 'SY · Suriye', 1, 'SY · Syria'),
    ('kod', 'Saat değişikliği', 1, 'Shift change'),
    ('kod', 'Saatlik', 1, 'Hourly'),
    ('kod', 'Sabit aralık', 1, 'Fixed interval'),
    ('kod', 'Sabit tutar', 1, 'Fixed amount'),
    ('kod', 'Sadece binek otoda', 1, 'Passenger cars only'),
    ('kod', 'Saha / Dışarıda', 1, 'Field / off site'),
    ('kod', 'Saha muayene günü', 1, 'Field examination day'),
    ('kod', 'Saha ziyareti', 1, 'Field visit'),
    ('kod', 'Sanger', 1, 'Sanger'),
    ('kod', 'Sarf', 1, 'Consumable'),
    ('kod', 'Sarf / Tekrarlı', 1, 'Consumable / recurring'),
    ('kod', 'Sarf edildi', 1, 'Consumed'),
    ('kod', 'Sarı', 1, 'Yellow'),
    ('kod', 'Sarı (Jelli / Biyokimya)', 1, 'Yellow (gel / biochemistry)'),
    ('kod', 'Satis Kasasi', 1, 'Sales cash desk'),
    ('kod', 'Satınalma Sorumlusu', 1, 'Purchasing officer'),
    ('kod', 'Satınalma Talebi', 1, 'Purchase request'),
    ('kod', 'Satış Destek', 1, 'Sales support'),
    ('kod', 'Satış Sorumlusu', 1, 'Sales officer'),
    ('kod', 'Sayı', 1, 'Number'),
    ('kod', 'Sayım Eksiği', 1, 'Count shortage'),
    ('kod', 'Sayım Fazlası', 1, 'Count surplus'),
    ('kod', 'Sayısal', 1, 'Numeric'),
    ('kod', 'Sağ', 1, 'Right'),
    ('kod', 'Sağ-Sol Belirsiz', 1, 'Side unspecified'),
    ('kod', 'Sağ-Sol Birlikte', 1, 'Both sides'),
    ('kod', 'Sağlam', 1, 'Sound'),
    ('kod', 'Sağlık Bakanlığı-Milletlerarası Sözleşme', 1, 'Ministry of Health - international agreement'),
    ('kod', 'Sağlık Tedbiri Kararı', 1, 'Health measure order'),
    ('kod', 'Sağlık Turizmi', 1, 'Health tourism'),
    ('kod', 'Sağlık durumu', 1, 'Health status'),
    ('kod', 'Scrub hemşire', 1, 'Scrub nurse'),
    ('kod', 'Seans başına oran', 1, 'Rate per session'),
    ('kod', 'Sedasyon', 1, 'Sedation'),
    ('kod', 'Sekonder IOL', 1, 'Secondary IOL'),
    ('kod', 'Senet', 1, 'Promissory note'),
    ('kod', 'Serbest', 1, 'Free'),
    ('kod', 'Serbest Meslek Kazanç Defteri', 1, 'Self-employment ledger'),
    ('kod', 'Serbest liste', 1, 'Free list'),
    ('kod', 'Serbest liste (elle eklenir)', 1, 'Free list (added manually)'),
    ('kod', 'Serbest çizgi', 1, 'Freehand line'),
    ('kod', 'Serbest çizim', 1, 'Freehand drawing'),
    ('kod', 'Seri metin (RS-232)', 1, 'Serial text (RS-232)'),
    ('kod', 'Seroloji', 1, 'Serology'),
    ('kod', 'Sert eksuda', 1, 'Hard exudate'),
    ('kod', 'Sert kaplama', 1, 'Hard coating'),
    ('kod', 'Sertifika', 1, 'Certificate'),
    ('kod', 'Serum', 1, 'Serum'),
    ('kod', 'Serum / sıvı', 1, 'Serum / fluid'),
    ('kod', 'Servikal', 1, 'Cervical'),
    ('kod', 'Servis / sipariş', 1, 'Service / order'),
    ('kod', 'Servis Müdürü', 1, 'Service manager'),
    ('kod', 'Servis Mühendisi', 1, 'Service engineer'),
    ('kod', 'Servis el kitabı', 1, 'Service manual'),
    ('kod', 'Servis raporu', 1, 'Service report'),
    ('kod', 'Servise Sevk', 1, 'Referral to a ward'),
    ('kod', 'Servise yatış', 1, 'Admission to a ward'),
    ('kod', 'Sesli mesaj', 1, 'Voicemail'),
    ('kod', 'Sevk raporu', 1, 'Referral report'),
    ('kod', 'Sevkiyat', 1, 'Shipment'),
    ('kod', 'Sevkle', 1, 'By referral'),
    ('kod', 'Sevkli', 1, 'Referred'),
    ('kod', 'Seçenek', 1, 'Option'),
    ('kod', 'Seçenekli', 1, 'With options'),
    ('kod', 'Sikloplejik', 1, 'Cycloplegic'),
    ('kod', 'Silindi', 1, 'Deleted'),
    ('kod', 'Sineşi', 1, 'Synechia'),
    ('kod', 'Siparişe dönüştü', 1, 'Converted to an order'),
    ('kod', 'Siparişe üretim', 1, 'Make to order'),
    ('kod', 'Sirküle hemşire', 1, 'Circulating nurse'),
    ('kod', 'Sistem Sorgusu', 1, 'System query'),
    ('kod', 'Sitotoksik atık', 1, 'Cytotoxic waste'),
    ('kod', 'Siyah', 1, 'Black'),
    ('kod', 'Skleral', 1, 'Scleral'),
    ('kod', 'Skleral çökertme', 1, 'Scleral buckling'),
    ('kod', 'Skopi', 1, 'Fluoroscopy'),
    ('kod', 'Sol', 1, 'Left'),
    ('kod', 'Somatik (tümör)', 1, 'Somatic (tumour)'),
    ('kod', 'Son 3 gün taburcu', 1, 'Discharged in the last 3 days'),
    ('kod', 'Son 5 gün içinde kontrastlı tetkik yaptırdıysanız bildirin. Metal içermeyen rahat kıyafet giyin.', 1, 'Tell us if you had a contrast study in the last 5 days. Wear comfortable clothing without metal.'),
    ('kod', 'Sona erdi', 1, 'Ended'),
    ('kod', 'Sonlandırıldı', 1, 'Terminated'),
    ('kod', 'Sonucu hazır, 7 gündür alınmamış', 1, 'Result ready, not collected for 7 days'),
    ('kod', 'Sonuç Bekliyor', 1, 'Awaiting result'),
    ('kod', 'Sonuç bilgisi', 1, 'Result information'),
    ('kod', 'Sonuç hazır', 1, 'Result ready'),
    ('kod', 'Sonuçlandı', 1, 'Completed'),
    ('kod', 'Soğuk Temas', 1, 'Cold contact'),
    ('kod', 'Soğuk zincir', 1, 'Cold chain'),
    ('kod', 'Spinal', 1, 'Spinal'),
    ('kod', 'Stabil', 1, 'Stable'),
    ('kod', 'Stajyer/Çırak', 1, 'Intern/apprentice'),
    ('kod', 'Standart hafta', 1, 'Standard week'),
    ('kod', 'Stoğa kabul', 1, 'Received into stock'),
    ('kod', 'Stoğa üretim', 1, 'Make to stock'),
    ('kod', 'Subjektif', 1, 'Subjective'),
    ('kod', 'Suit', 1, 'Suite'),
    ('kod', 'Sunuldu', 1, 'Presented'),
    ('kod', 'Suçiçeği', 1, 'Chickenpox'),
    ('kod', 'Swab', 1, 'Swab'),
    ('kod', 'Sözlü (tanıklı)', 1, 'Verbal (witnessed)'),
    ('kod', 'Sözlü onay', 1, 'Verbal consent'),
    ('kod', 'Sürekli (7/24)', 1, 'Continuous (24/7)'),
    ('kod', 'Süresi Geçti / Kota Doldu', 1, 'Expired / quota reached'),
    ('kod', 'Süresi doldu', 1, 'Expired'),
    ('kod', 'Süresi dolmuş', 1, 'Expired'),
    ('kod', 'Sürmemiş', 1, 'Unerupted'),
    ('kod', 'Süt', 1, 'Milk'),
    ('kod', 'Süt kalıntısı', 1, 'Retained primary tooth'),
    ('kod', 'Sıcak / soğuk ortam', 1, 'Hot / cold environment'),
    ('kod', 'Sık cümle', 1, 'Frequent phrase'),
    ('kod', 'Sınıf I', 1, 'Class I'),
    ('kod', 'Sınıf III', 1, 'Class III'),
    ('kod', 'Sınıf IIa', 1, 'Class IIa'),
    ('kod', 'Sınıf IIb', 1, 'Class IIb'),
    ('kod', 'Sınır dışı', 1, 'Out of range'),
    ('kod', 'Sırada', 1, 'In queue'),
    ('kod', 'Sıvı (buyyon)', 1, 'Liquid (broth)'),
    ('kod', 'T.C. Sağlık Bakanlığı Sağlık ve Tıp Alanında İkili İş Birliği Anlaşmaları Kapsamındaki Hastalar', 1, 'Patients covered by the Ministry of Health''s bilateral cooperation agreements in health and medicine'),
    ('kod', 'TL', 1, 'TRY'),
    ('kod', 'TME / çene', 1, 'TMJ / jaw'),
    ('kod', 'TPN', 1, 'TPN'),
    ('kod', 'TR', 1, 'TR'),
    ('kod', 'TR · Türkiye', 1, 'TR · Türkiye'),
    ('kod', 'TRY', 1, 'TRY'),
    ('kod', 'TSS (Tamamlayıcı Sağlık Sigortası)', 1, 'Complementary health insurance (TSS)'),
    ('kod', 'TTB / HUV', 1, 'TTB / HUV'),
    ('kod', 'Tablet / kiosk', 1, 'Tablet / kiosk'),
    ('kod', 'Taburcu', 1, 'Discharged'),
    ('kod', 'Taburcu (Yatan Hasta)', 1, 'Discharged (inpatient)'),
    ('kod', 'Taburcu / muayene bitti', 1, 'Discharged / examination finished'),
    ('kod', 'Taburcu planlandı', 1, 'Discharge planned'),
    ('kod', 'Tahakkuk', 1, 'Accrual'),
    ('kod', 'Tahsil Edildi / Odendi', 1, 'Collected / paid'),
    ('kod', 'Tahsil Edildi / Ödendi', 1, 'Collected / paid'),
    ('kod', 'Tahsil edilen (matrah)', 1, 'Collected (taxable base)'),
    ('kod', 'Tahsilat anında', 1, 'At the time of collection'),
    ('kod', 'Tahsilatta', 1, 'In collection'),
    ('kod', 'Takipli Hasta', 1, 'Patient under follow-up'),
    ('kod', 'Talep türü', 1, 'Request type'),
    ('kod', 'Tam Kan', 1, 'Whole blood'),
    ('kod', 'Tam Zamanlı', 1, 'Full time'),
    ('kod', 'Tam kapsam (parça dahil)', 1, 'Full coverage (parts included)'),
    ('kod', 'Tam muayene', 1, 'Full examination'),
    ('kod', 'Tamamlanınca', 1, 'On completion'),
    ('kod', 'Tarama (DR)', 1, 'Screening (DR)'),
    ('kod', 'Tarihli', 1, 'Dated'),
    ('kod', 'Tasarım onayı', 1, 'Design approval'),
    ('kod', 'Tedavi Önerileriyle Çıkış', 1, 'Discharged with treatment recommendations'),
    ('kod', 'Tediye', 1, 'Payment'),
    ('kod', 'Tehlikeli', 1, 'Hazardous'),
    ('kod', 'Tehlikeli atık', 1, 'Hazardous waste'),
    ('kod', 'Tek kişilik', 1, 'Single room'),
    ('kod', 'Tek seferde (Başlat''ta)', 1, 'All at once (on start)'),
    ('kod', 'Tek seferlik', 1, 'One off'),
    ('kod', 'Tek yön (AP)', 1, 'Single view (AP)'),
    ('kod', 'Teklif toplama', 1, 'Collecting bids'),
    ('kod', 'Teklif verdi', 1, 'Bid submitted'),
    ('kod', 'Teklif vermedi', 1, 'No bid'),
    ('kod', 'Teklifler açıldı', 1, 'Bids opened'),
    ('kod', 'Teklifte', 1, 'In bidding'),
    ('kod', 'Teknik elendi', 1, 'Technically disqualified'),
    ('kod', 'Tekrar numune bekliyor', 1, 'Awaiting a repeat specimen'),
    ('kod', 'Teletıp', 1, 'Telemedicine'),
    ('kod', 'Teller (pediatri)', 1, 'Tumbling E (paediatric)'),
    ('kod', 'Temaslı', 1, 'Contact'),
    ('kod', 'Temel', 1, 'Basic'),
    ('kod', 'Teminata Verildi', 1, 'Pledged as collateral'),
    ('kod', 'Teminatta', 1, 'Held as collateral'),
    ('kod', 'Teminattan Donus', 1, 'Returned from collateral'),
    ('kod', 'Temizlik bekliyor', 1, 'Awaiting cleaning'),
    ('kod', 'Temizlikte', 1, 'Being cleaned'),
    ('kod', 'Terfi / unvan', 1, 'Promotion / title'),
    ('kod', 'Terim', 1, 'Term'),
    ('kod', 'Ters Fişle İptal', 1, 'Cancelled by a reversing voucher'),
    ('kod', 'Teslim edildi', 1, 'Delivered'),
    ('kod', 'Tetanoz-difteri (Td)', 1, 'Tetanus-diphtheria (Td)'),
    ('kod', 'Tetkik / Tahlil', 1, 'Test / analysis'),
    ('kod', 'Tetkik başı', 1, 'Per study'),
    ('kod', 'Tevkifatlı', 1, 'With withholding'),
    ('kod', 'Ticari', 1, 'Commercial'),
    ('kod', 'Titreşim', 1, 'Vibration'),
    ('kod', 'Tono-Pen', 1, 'Tono-Pen'),
    ('kod', 'Tonometre (NCT)', 1, 'Tonometer (NCT)'),
    ('kod', 'Topikal', 1, 'Topical'),
    ('kod', 'Toplantı', 1, 'Meeting'),
    ('kod', 'Topografi', 1, 'Topography'),
    ('kod', 'Torakal', 1, 'Thoracic'),
    ('kod', 'Torik', 1, 'Toric'),
    ('kod', 'Total protez', 1, 'Complete denture'),
    ('kod', 'Toz', 1, 'Dust'),
    ('kod', 'Trabekülektomi', 1, 'Trabeculectomy'),
    ('kod', 'Trafik Kazası', 1, 'Road traffic accident'),
    ('kod', 'Trafik kazası', 1, 'Road traffic accident'),
    ('kod', 'Transfüzyon', 1, 'Transfusion'),
    ('kod', 'Travma', 1, 'Trauma'),
    ('kod', 'Treat & extend', 1, 'Treat & extend'),
    ('kod', 'Triamsinolon', 1, 'Triamcinolone'),
    ('kod', 'Triyaj bekliyor', 1, 'Awaiting triage'),
    ('kod', 'Turistin Sağlığı', 1, 'Tourist health'),
    ('kod', 'Turuncu', 1, 'Orange'),
    ('kod', 'Tuttu', 1, 'Matched'),
    ('kod', 'Tüm Hastalar', 1, 'All patients'),
    ('kod', 'Tüm kıymetlerde', 1, 'On all assets'),
    ('kod', 'Tüm metal eşyaları (takı, saat, saç tokası, işitme cihazı) çıkarın. Kalp pili, koklear implant veya vücudunuzda metal varsa mutlaka bildirin. Çekim 20-40 dk sürer.', 1, 'Remove all metal items (jewellery, watch, hair clips, hearing aid). You must tell us about a pacemaker, cochlear implant or any metal in your body. The scan takes 20-40 minutes.'),
    ('kod', 'Tüp implantı', 1, 'Tube implant'),
    ('kod', 'Türk Soylu Yabancılar', 1, 'Foreigners of Turkish descent'),
    ('kod', 'Türkiye', 1, 'Türkiye'),
    ('kod', 'TİKA Tarafından Getirilen Hastalar', 1, 'Patients brought by TİKA'),
    ('kod', 'Tıbbi Cihaz', 1, 'Medical device'),
    ('kod', 'Tıbbi Ekipman Eksikliği', 1, 'Lack of medical equipment'),
    ('kod', 'Tıbbi Teknik Arıza', 1, 'Medical technical fault'),
    ('kod', 'Tıbbi atık', 1, 'Medical waste'),
    ('kod', 'Tıbbi Önerileri/Tedavileri Redderedek Çıkış', 1, 'Discharged against medical advice'),
    ('kod', 'Tıbbi İşlem', 1, 'Medical procedure'),
    ('kod', 'UA · Ukrayna', 1, 'UA · Ukraine'),
    ('kod', 'UBM', 1, 'UBM'),
    ('kod', 'UCVA (düzeltmesiz)', 1, 'UCVA (uncorrected)'),
    ('kod', 'US - batın açlık / üriner dolu mesane', 1, 'US - fasting for abdomen / full bladder for urinary tract'),
    ('kod', 'US · ABD', 1, 'US · United States'),
    ('kod', 'USD', 1, 'USD'),
    ('kod', 'USG', 1, 'Ultrasound'),
    ('kod', 'UV filtre', 1, 'UV filter'),
    ('kod', 'UYUŞMUYOR', 1, 'MISMATCH'),
    ('kod', 'Uluslararası Koruma Başvurusu veya Statüsü Sahibi Kişiler (Mülteci/ Şartlı Mülteci/ İkincil Koruma)', 1, 'People applying for or holding international protection (refugee / conditional refugee / subsidiary protection)'),
    ('kod', 'Uyar, geçir', 1, 'Warn and continue'),
    ('kod', 'Uyarı (2 < |SDI| ≤ 3)', 1, 'Warning (2 < |SDI| ≤ 3)'),
    ('kod', 'Uyarı yok', 1, 'No warning'),
    ('kod', 'Uygulama yolu', 1, 'Route of administration'),
    ('kod', 'Uygulanamaz', 1, 'Not applicable'),
    ('kod', 'Uygulanmaz', 1, 'Not applicable'),
    ('kod', 'Uygulanmıyor', 1, 'Not in use'),
    ('kod', 'Uygun / Onay', 1, 'Acceptable / approved'),
    ('kod', 'Uygun değil', 1, 'Not acceptable'),
    ('kod', 'Uygunsuz', 1, 'Nonconforming'),
    ('kod', 'Uyumlu kapandı', 1, 'Closed as matching'),
    ('kod', 'Uyuyor', 1, 'Matches'),
    ('kod', 'Uzak', 1, 'Distance'),
    ('kod', 'Uzaktan', 1, 'Remote'),
    ('kod', 'Uzm.Dr.', 1, 'Specialist Dr'),
    ('kod', 'Uzm.Dt.', 1, 'Specialist DDS'),
    ('kod', 'Uzman hekim yok', 1, 'No specialist physician'),
    ('kod', 'V (ölüm)', 1, 'D (death)'),
    ('kod', 'Vadesi geçen bakiye (parametre: tutar eşiği)', 1, 'Overdue balance (parameter: amount threshold)'),
    ('kod', 'Vaka Bazlı Fatura', 1, 'Case-based invoice'),
    ('kod', 'Vaka başı', 1, 'Per case'),
    ('kod', 'Vaka tipi', 1, 'Case type'),
    ('kod', 'Vardiyalı', 1, 'Shift work'),
    ('kod', 'Vardiyalı - gece postası var', 1, 'Shift work - includes night shifts'),
    ('kod', 'Vatansız Olarak Tanınan Kişiler', 1, 'People recognised as stateless'),
    ('kod', 'Vazgeçildi', 1, 'Abandoned'),
    ('kod', 'Vazgeçti', 1, 'Withdrew'),
    ('kod', 'Vekâlet (süreli)', 1, 'Acting (temporary)'),
    ('kod', 'Verilmedi', 1, 'Not given'),
    ('kod', 'Verme', 1, 'Dispense'),
    ('kod', 'Virüs', 1, 'Virus'),
    ('kod', 'Vital / Monitör', 1, 'Vitals / monitor'),
    ('kod', 'Vitreolizis', 1, 'Vitreolysis'),
    ('kod', 'Vitreus kaybı', 1, 'Vitreous loss'),
    ('kod', 'Vize Yazısı', 1, 'Visa letter'),
    ('kod', 'Vücut Şeması', 1, 'Body diagram'),
    ('kod', 'WES (tüm ekzom)', 1, 'WES (whole exome)'),
    ('kod', 'WGS (tüm genom)', 1, 'WGS (whole genome)'),
    ('kod', 'WOMAC', 1, 'WOMAC'),
    ('kod', 'Web / Form', 1, 'Web / form'),
    ('kod', 'Web formu', 1, 'Web form'),
    ('kod', 'WhatsApp', 1, 'WhatsApp'),
    ('kod', 'X''e bağlı', 1, 'X-linked'),
    ('kod', 'YAG iridotomi', 1, 'YAG iridotomy'),
    ('kod', 'YAG kapsülotomi', 1, 'YAG capsulotomy'),
    ('kod', 'Yakın', 1, 'Near'),
    ('kod', 'Yalancı düşüklük', 1, 'Falsely low'),
    ('kod', 'Yalancı yükseklik', 1, 'Falsely high'),
    ('kod', 'Yalnız Erkek', 1, 'Male only'),
    ('kod', 'Yalnız Kadın', 1, 'Female only'),
    ('kod', 'Yalnız bilgilendirme', 1, 'Information only'),
    ('kod', 'Yalnız erkek', 1, 'Male only'),
    ('kod', 'Yalnız gece', 1, 'Night only'),
    ('kod', 'Yalnız kadın', 1, 'Female only'),
    ('kod', 'Yan Dal Uzman Hekim İhtiyacı', 1, 'Need for a subspecialist physician'),
    ('kod', 'Yanlış tüp', 1, 'Wrong tube'),
    ('kod', 'Yanık Ünitesi İhtiyacı', 1, 'Need for a burns unit'),
    ('kod', 'Yanıt yok', 1, 'No response'),
    ('kod', 'Yanıtsız', 1, 'Unanswered'),
    ('kod', 'Yapılmadı', 1, 'Not performed'),
    ('kod', 'Yarı Mamul', 1, 'Semi-finished good'),
    ('kod', 'Yarı Zamanlı', 1, 'Part time'),
    ('kod', 'Yarım', 1, 'Half'),
    ('kod', 'Yarınki randevular (planlı)', 1, 'Tomorrow''s appointments (scheduled)'),
    ('kod', 'Yatak yok', 1, 'No bed'),
    ('kod', 'Yatakta', 1, 'In bed'),
    ('kod', 'Yatan', 1, 'Inpatient'),
    ('kod', 'Yatan (Y)', 1, 'Inpatient (I)'),
    ('kod', 'Yatan Hasta', 1, 'Inpatient'),
    ('kod', 'Yatis Devam Ediyor', 1, 'Admission ongoing'),
    ('kod', 'Yatırım', 1, 'Investment'),
    ('kod', 'Yatış Önerisi', 1, 'Admission recommended'),
    ('kod', 'Yayında', 1, 'Published'),
    ('kod', 'Yazılım Geliştirme', 1, 'Software development'),
    ('kod', 'Yaş (neovasküler)', 1, 'Wet (neovascular)'),
    ('kod', 'Yaşam desteği', 1, 'Life support'),
    ('kod', 'Yedek', 1, 'Spare'),
    ('kod', 'Yedek (asıl nöbetçi doluysa)', 1, 'Backup (if the primary on-call is busy)'),
    ('kod', 'Yemek', 1, 'Meal'),
    ('kod', 'Yeniden atama', 1, 'Reassignment'),
    ('kod', 'Yenidoğan', 1, 'Newborn'),
    ('kod', 'Yerel (ücretli)', 1, 'Local (paying)'),
    ('kod', 'Yerinde', 1, 'On site'),
    ('kod', 'Yetersiz', 1, 'Insufficient'),
    ('kod', 'Yetersiz miktar', 1, 'Insufficient quantity'),
    ('kod', 'Yeşil', 1, 'Green'),
    ('kod', 'Yeşil (Heparin)', 1, 'Green (heparin)'),
    ('kod', 'Yeşil (psikotrop)', 1, 'Green (psychotropic)'),
    ('kod', 'Yeşil Kart', 1, 'Green Card'),
    ('kod', 'Yeşil alan', 1, 'Green area'),
    ('kod', 'Yoğun Bakım', 1, 'Intensive care'),
    ('kod', 'Yoğun Bakım Doluluğu', 1, 'Intensive care is full'),
    ('kod', 'Yoğun Bakım Olmaması', 1, 'No intensive care unit'),
    ('kod', 'Yoğun Bakım İhtiyacı', 1, 'Need for intensive care'),
    ('kod', 'Yoğun bakım', 1, 'Intensive care'),
    ('kod', 'Yumuşak aylık', 1, 'Soft monthly'),
    ('kod', 'Yumuşak eksuda (CWS)', 1, 'Soft exudate (CWS)'),
    ('kod', 'Yumuşak günlük', 1, 'Soft daily'),
    ('kod', 'Yurt dışı sevk', 1, 'Referral abroad'),
    ('kod', 'Yön belirsiz', 1, 'Direction unspecified'),
    ('kod', 'Yönetici Asistanı', 1, 'Executive assistant'),
    ('kod', 'Yönetici değişikliği', 1, 'Manager change'),
    ('kod', 'Yönetim kurulu', 1, 'Board of directors'),
    ('kod', 'Yönlendirildi', 1, 'Redirected'),
    ('kod', 'Yüksek', 1, 'High'),
    ('kod', 'Yüksek indeks 1.60', 1, 'High index 1.60'),
    ('kod', 'Yüksek indeks 1.67', 1, 'High index 1.67'),
    ('kod', 'Yüksek indeks 1.74', 1, 'High index 1.74'),
    ('kod', 'Yüksek riskli', 1, 'High risk'),
    ('kod', 'Yüksek çözünürlük (ince kesit)', 1, 'High resolution (thin slice)'),
    ('kod', 'Yüksek ↑', 1, 'High ↑'),
    ('kod', 'Yüksekte çalışma', 1, 'Work at height'),
    ('kod', 'Yüz Yüze', 1, 'Face to face'),
    ('kod', 'Yüz yüze', 1, 'Face to face'),
    ('kod', 'Yüzde', 1, 'Percentage'),
    ('kod', 'Yüzde (SUT üzerinden)', 1, 'Percentage (of SUT)'),
    ('kod', 'Yıllık', 1, 'Annual'),
    ('kod', 'Yıllık İzin', 1, 'Annual leave'),
    ('kod', 'Yırtık / delik', 1, 'Tear / hole'),
    ('kod', 'Zonül diyalizi', 1, 'Zonular dialysis'),
    ('kod', 'Zürih (UTC+1, yaz +2)', 1, 'Zurich (UTC+1, summer +2)'),
    ('kod', 'belge', 1, 'document'),
    ('kod', 'belge satırı', 1, 'document line'),
    ('kod', 'depo stok bakiyesi', 1, 'warehouse stock balance'),
    ('kod', 'e-Arşiv Fatura', 1, 'e-Archive invoice'),
    ('kod', 'e-Fatura / e-Belge Entegratörü', 1, 'e-Invoice / e-Document integrator'),
    ('kod', 'fiyat listesi', 1, 'price list'),
    ('kod', 'hakediş', 1, 'earnings'),
    ('kod', 'hakediş satırı', 1, 'earnings line'),
    ('kod', 'kasa / banka hesabı', 1, 'cash / bank account'),
    ('kod', 'kasa işlemi', 1, 'cash transaction'),
    ('kod', 'kasa/banka hareketi', 1, 'cash/bank movement'),
    ('kod', 'kullanıcı bağı', 1, 'user link'),
    ('kod', 'muhasebe fişi satırı', 1, 'accounting voucher line'),
    ('kod', 'müdür', 1, 'manager'),
    ('kod', 'radyoloji istemi', 1, 'radiology order'),
    ('kod', 'randevu', 1, 'appointment'),
    ('kod', 'rol-şube ataması', 1, 'role-branch assignment'),
    ('kod', 'stok hareketi', 1, 'stock movement'),
    ('kod', '£ GBP · Sterlin', 1, '£ GBP · pound sterling'),
    ('kod', 'Âmir (henüz yok)', 1, 'Manager (not set yet)'),
    ('kod', 'Çaldı', 1, 'Rang'),
    ('kod', 'Çalıyor', 1, 'Ringing'),
    ('kod', 'Çalışma Belgesi', 1, 'Employment letter'),
    ('kod', 'Çalışma şekli / sözleşme', 1, 'Employment type / contract'),
    ('kod', 'Çalışıldı', 1, 'Processed'),
    ('kod', 'Çalışılıyor', 1, 'Being processed'),
    ('kod', 'Çağrı Merkezi', 1, 'Call centre'),
    ('kod', 'Çağrıda', 1, 'On a call'),
    ('kod', 'Çek', 1, 'Cheque'),
    ('kod', 'Çekim / cerrahi', 1, 'Extraction / surgery'),
    ('kod', 'Çekim bölgesindeki takı ve metal aksesuarları çıkarın. Gebelik ihtimaliniz varsa bildirin.', 1, 'Remove jewellery and metal accessories from the area being imaged. Tell us if you might be pregnant.'),
    ('kod', 'Çekim endikasyonu', 1, 'Indication for the study'),
    ('kod', 'Çekim günü koltuk altına deodorant, pudra veya krem sürmeyin. Adet döneminin ilk haftası tercih edilir.', 1, 'Do not use deodorant, powder or cream under the arms on the day. The first week after menstruation is preferred.'),
    ('kod', 'Çerçeve (birim fiyat)', 1, 'Frame (unit price)'),
    ('kod', 'Çevresel', 1, 'Environmental'),
    ('kod', 'Çift kişilik', 1, 'Double room'),
    ('kod', 'Çifte Vatandaşlar', 1, 'Dual citizens'),
    ('kod', 'Çocuk', 1, 'Child'),
    ('kod', 'Çocuk Hastalar', 1, 'Paediatric patients'),
    ('kod', 'Çocuk izlem', 1, 'Child follow-up'),
    ('kod', 'Çok Vatandaşlığı Bulunanlar (Çifte Vatandaş) / (Mavi Kartlılar) Çıkma İzni Almak Suretiyle Türk Vatandaşlığını Kaybedenler', 1, 'People with multiple citizenships (dual citizens) / (Blue Card holders) who lost Turkish citizenship with permission'),
    ('kod', 'Çok iyi', 1, 'Very good'),
    ('kod', 'Çok kötü', 1, 'Very poor'),
    ('kod', 'Çok tehlikeli', 1, 'Very hazardous'),
    ('kod', 'Çok yataklı', 1, 'Multi-bed'),
    ('kod', 'Çözümlenemedi', 1, 'Could not be resolved'),
    ('kod', 'Çürük (başlangıç)', 1, 'Caries (initial)'),
    ('kod', 'Çürük (dentin)', 1, 'Caries (dentin)'),
    ('kod', 'Çürük (derin)', 1, 'Caries (deep)'),
    ('kod', 'Çıkardığı', 1, 'Output'),
    ('kod', 'ÖSS', 1, 'Private health insurance'),
    ('kod', 'ÖSS (Özel Sağlık Sigortası)', 1, 'Private health insurance (ÖSS)'),
    ('kod', 'Ödeme durduruldu', 1, 'Payment stopped'),
    ('kod', 'Ödeme linki', 1, 'Payment link'),
    ('kod', 'Ödemeye onay', 1, 'Approved for payment'),
    ('kod', 'Ödendi', 1, 'Paid'),
    ('kod', 'Ölçü bekliyor', 1, 'Awaiting impression'),
    ('kod', 'Ölçülmedi', 1, 'Not measured'),
    ('kod', 'Ölüm', 1, 'Death'),
    ('kod', 'Ön', 1, 'Front'),
    ('kod', 'Ön Değerlendirme', 1, 'Pre-assessment'),
    ('kod', 'Ön koşul bekliyor', 1, 'Awaiting a prerequisite'),
    ('kod', 'Ön segment', 1, 'Anterior segment'),
    ('kod', 'Ön tetkik', 1, 'Pre-test'),
    ('kod', 'Öncelikli', 1, 'Priority'),
    ('kod', 'Öneri yapıldı', 1, 'Recommendation made'),
    ('kod', 'Özel (Ücretli)', 1, 'Private (paying)'),
    ('kod', 'Özel - metin elle yazılır', 1, 'Custom - text entered manually'),
    ('kod', 'Özel Nitelikli (KVKK)', 1, 'Special category (KVKK)'),
    ('kod', 'Özel Sigorta', 1, 'Private insurance'),
    ('kod', 'Özel ambulans', 1, 'Private ambulance'),
    ('kod', 'Özel hesap dönemi', 1, 'Special accounting period'),
    ('kod', 'Özel sigorta payı', 1, 'Private insurance share'),
    ('kod', 'Öğrenci', 1, 'Student'),
    ('kod', 'ÜTS (Ürün Takip Sistemi)', 1, 'ÜTS (Product Tracking System)'),
    ('kod', 'ÜTS / CE belgesi', 1, 'ÜTS / CE certificate'),
    ('kod', 'ÜTS bildirimi', 1, 'ÜTS notification'),
    ('kod', 'Ücretli', 1, 'Paying'),
    ('kod', 'Ücretsiz izin / askı', 1, 'Unpaid leave / suspension'),
    ('kod', 'Ücretsiz İzin', 1, 'Unpaid leave'),
    ('kod', 'Üretici garantisi', 1, 'Manufacturer warranty'),
    ('kod', 'Üretimde', 1, 'In production'),
    ('kod', 'Ürün', 1, 'Product'),
    ('kod', 'Ürün Satışı', 1, 'Product sale'),
    ('kod', 'Üst yönetim', 1, 'Senior management'),
    ('kod', 'Üveit', 1, 'Uveitis'),
    ('kod', 'çek / senet', 1, 'cheque / note'),
    ('kod', 'İK / Teknik müdür (akışa göre)', 1, 'HR / technical manager (per workflow)'),
    ('kod', 'İSG kurulu', 1, 'OHS committee'),
    ('kod', 'İSG muayene', 1, 'OHS examination'),
    ('kod', 'İSG muayene randevusu', 1, 'OHS examination appointment'),
    ('kod', 'İSG periyodik muayene', 1, 'OHS periodic examination'),
    ('kod', 'İSG periyodik muayene (30 gün)', 1, 'OHS periodic examination (30 days)'),
    ('kod', 'İTS bildirildi', 1, 'Reported to İTS'),
    ('kod', 'İTS doğruladı', 1, 'İTS confirmed'),
    ('kod', 'İV', 1, 'IV'),
    ('kod', 'İV + Oral', 1, 'IV + oral'),
    ('kod', 'İade Edildi', 1, 'Returned'),
    ('kod', 'İade alındı', 1, 'Return received'),
    ('kod', 'İdame', 1, 'Maintenance'),
    ('kod', 'İdarî', 1, 'Administrative'),
    ('kod', 'İdrar', 1, 'Urine'),
    ('kod', 'İdrar Kabı', 1, 'Urine container'),
    ('kod', 'İhale / Kamu', 1, 'Tender / public'),
    ('kod', 'İhracat', 1, 'Export'),
    ('kod', 'İhraç Kayıtlı', 1, 'Export registered'),
    ('kod', 'İki haftada bir', 1, 'Every two weeks'),
    ('kod', 'İki yön', 1, 'Two views'),
    ('kod', 'İki yönlü (AP + lateral)', 1, 'Two views (AP + lateral)'),
    ('kod', 'İkinci okuma', 1, 'Second read'),
    ('kod', 'İkter (İ)', 1, 'Icterus (I)'),
    ('kod', 'İkterik', 1, 'Icteric'),
    ('kod', 'İlaç / Tıbbi Cihaz', 1, 'Drug / medical device'),
    ('kod', 'İlaç kullanım', 1, 'Medication use'),
    ('kod', 'İlaç kullanım raporu', 1, 'Medication use report'),
    ('kod', 'İleri Merkeze Sevk (Yenidoğan Nakil)', 1, 'Referral to a tertiary centre (neonatal transfer)'),
    ('kod', 'İleri kuru (GA)', 1, 'Advanced dry (GA)'),
    ('kod', 'İleri tetkik / tedavi', 1, 'Further tests / treatment'),
    ('kod', 'İleri Özelleşmiş Hekim İhtiyacı', 1, 'Need for a highly specialised physician'),
    ('kod', 'İlgili Branş Hekiminin Bulunmaması', 1, 'No physician in the relevant specialty'),
    ('kod', 'İlgili Hizmet Unsurlarının Tadilatı', 1, 'The relevant service facilities are being refurbished'),
    ('kod', 'İlgili Kliniğin (Yataklı Servisin) Bulunmaması', 1, 'There is no relevant clinic (inpatient ward)'),
    ('kod', 'İlk Muayene', 1, 'Initial examination'),
    ('kod', 'İlk yatak', 1, 'First bed'),
    ('kod', 'İlk yatana göre kilitlenir', 1, 'Locked to the first patient admitted'),
    ('kod', 'İmal', 1, 'Manufactured'),
    ('kod', 'İmha (Bozuk / SKT Geçmiş)', 1, 'Destruction (damaged / expired)'),
    ('kod', 'İmha / Bertaraf', 1, 'Destruction / disposal'),
    ('kod', 'İmha Edildi', 1, 'Destroyed'),
    ('kod', 'İmha edildi', 1, 'Destroyed'),
    ('kod', 'İmplant üstü', 1, 'Implant supported'),
    ('kod', 'İmzalı', 1, 'Signed'),
    ('kod', 'İncelemede', 1, 'Under review'),
    ('kod', 'İncelendi', 1, 'Reviewed'),
    ('kod', 'İndirekt oftalmoskopi', 1, 'Indirect ophthalmoscopy'),
    ('kod', 'İndirme', 1, 'Download'),
    ('kod', 'İnfüzyon', 1, 'Infusion'),
    ('kod', 'İngilizce', 1, 'English'),
    ('kod', 'İnhaler', 1, 'Inhaler'),
    ('kod', 'İnlay / onlay', 1, 'Inlay / onlay'),
    ('kod', 'İnsan Ticareti Mağduru', 1, 'Victim of human trafficking'),
    ('kod', 'İntravitreal enjeksiyon', 1, 'Intravitreal injection'),
    ('kod', 'İptal etti', 1, 'Cancelled'),
    ('kod', 'İptal nedeni', 1, 'Cancellation reason'),
    ('kod', 'İskonto Talebi', 1, 'Discount request'),
    ('kod', 'İstanbul (UTC+3)', 1, 'Istanbul (UTC+3)'),
    ('kod', 'İstemci (biz cihaza bağlanırız)', 1, 'Client (we connect to the device)'),
    ('kod', 'İstendi', 1, 'Requested'),
    ('kod', 'İstenirse', 1, 'On request'),
    ('kod', 'İstirahat', 1, 'Rest'),
    ('kod', 'İtaki düşme riski', 1, 'İtaki fall risk'),
    ('kod', 'İthal', 1, 'Imported'),
    ('kod', 'İthalat', 1, 'Import'),
    ('kod', 'İthalat İhracat Sorumlusu', 1, 'Import-export officer'),
    ('kod', 'İtiraz edildi', 1, 'Objection raised'),
    ('kod', 'İyi', 1, 'Good'),
    ('kod', 'İyi yanıt', 1, 'Good response'),
    ('kod', 'İyileşerek Çıkış/Taburcu', 1, 'Discharged recovered'),
    ('kod', 'İç ekran', 1, 'Internal screen'),
    ('kod', 'İç hekim', 1, 'Internal physician'),
    ('kod', 'İç iş (demirbaş)', 1, 'Internal job (asset)'),
    ('kod', 'İş Adresi', 1, 'Work address'),
    ('kod', 'İş Kazası', 1, 'Occupational accident'),
    ('kod', 'İş değişikliği', 1, 'Job change'),
    ('kod', 'İş göremezlik', 1, 'Incapacity'),
    ('kod', 'İş kazası', 1, 'Occupational accident'),
    ('kod', 'İşe dönüş', 1, 'Return to work'),
    ('kod', 'İşlem kaynağı', 1, 'Transaction source'),
    ('kod', 'İşlem seti', 1, 'Procedure set'),
    ('kod', 'İşleme göre aç gelmeniz istenebilir; randevu sırasında verilen talimata uyun. Gebelik ihtimalinizi bildirin.', 1, 'Depending on the procedure you may be asked to fast; follow the instructions given when booking. Tell us if you might be pregnant.'),
    ('kod', 'İşlendi', 1, 'Processed'),
    ('kod', 'İşletme Hesabı Esası', 1, 'Cash basis accounting'),
    ('kod', 'İşten çıkış', 1, 'Left employment'),
    ('kod', 'İşyeri Normal Muayene', 1, 'Workplace routine examination'),
    ('kod', 'İşyeri İse Giriş Ya Da Periyodik Muayene', 1, 'Workplace pre-employment or periodic examination'),
    ('kod', 'İşçi', 1, 'Worker'),
    ('kod', 'İşçilik + yol', 1, 'Labour + travel'),
    ('kod', 'Şam (UTC+3)', 1, 'Damascus (UTC+3)'),
    ('kod', 'Şartlı uygun', 1, 'Conditionally acceptable'),
    ('kod', 'Şaşılık', 1, 'Strabismus'),
    ('kod', 'Şiddetli', 1, 'Severe'),
    ('kod', 'Şifa', 1, 'Recovery'),
    ('kod', 'Şikayet (görev)', 1, 'Complaint (task)'),
    ('kod', 'Şu koşulla çalışır', 1, 'Fit for work under this condition'),
    ('kod', 'Şube nakli', 1, 'Branch transfer'),
    ('kod', 'Şube/Depo', 1, 'Branch/warehouse'),
    ('kod', 'Şüpheli', 1, 'Suspicious'),
    ('kod', '؋ AFN · Afgan Afganisi', 1, '؋ AFN · Afghan afghani'),
    ('kod', '€ EUR · Euro', 1, '€ EUR · euro'),
    ('kod', '₺ TRY · Türk Lirası', 1, '₺ TRY · Turkish lira'),
    ('kod', '₼ AZN · Manat', 1, '₼ AZN · manat'),
    ('kod', '₽ RUB · Ruble', 1, '₽ RUB · rouble'),
    ('kod', '≤ (en çok)', 1, '≤ (at most)'),
    ('kod', '≥ (en az)', 1, '≥ (at least)'),
    ('kod', 'İşe giriş', 1, 'Hired'),
    ('kod', 'Diğer', 1, 'Other')
on conflict (kapsam, anahtar, dil) do update set metin = excluded.metin,
    degistirme_tarihi = now();

do $$
declare v_en integer; v_kod integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    select count(*) into v_kod from public.ceviri where dil = 1 and kapsam = 'kod';
    raise notice '852 tamam: ingilizce sozluk % satir (% kod degeri).', v_en, v_kod;
end $$;
