-- ============================================================================
--  Gentegre AI — ROL / DEPARTMAN / GÖREV ADLARI İNGİLİZCE (853)
--  853_ingilizce_sozluk_rol_departman_gorev.sql
--
--  Kullanıcı: *"rol, departman ve görev adlarını da çevir"*.
--
--  ============ BUNLAR VERİ, METİN DEĞİL ==============================
--  Rol/departman/görev adları `rol`, `departman`, `personel_gorev`
--  tablolarında durur ve kurum bunları DEĞİŞTİREBİLİR. Bu yüzden tabloya
--  dil kolonu eklenmedi: kurum adı değiştirdiğinde eşleşme sessizce
--  kopardı ve iki yerde iki ad olurdu.
--
--  Çözüm: kurulumla gelen STANDART adlar sözlüğe yazılır (anahtar = adın
--  kendisi). Kurum adı değiştirirse çeviri uygulanmaz, Türkçesi görünür -
--  yanlış çeviri göstermekten iyidir.
--
--  VERİDEKİ YAZIM HATALARI DA ÇEVRİLDİ: "Gastroentereolji", "Çocuk
--  Romotolojisi", "Ağız, Dış ve Çene Cerrahisi" (Diş yerine Dış) gibi
--  kayıtlar SKRS aktarımından geldiği gibi duruyor; anahtar metnin kendisi
--  olduğu için onlar da ayrı satır olarak karşılandı, yoksa o bölümler
--  İngilizce ekranda Türkçe kalırdı. Veri düzeltmesi ayrı iştir.
--
--  Idempotent (`on conflict do update`).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin) values
    ('kod', 'Acil Cerrahi Yoğun Bakım', 1, 'Emergency Surgical Intensive Care'),
    ('kod', 'Acil Dahili Yoğun Bakım', 1, 'Emergency Medical Intensive Care'),
    ('kod', 'Acil Dahiliye Yoğun Bakım', 1, 'Emergency Internal Medicine Intensive Care'),
    ('kod', 'Acil Hekimi', 1, 'Emergency Physician'),
    ('kod', 'Acil Tıp', 1, 'Emergency Medicine'),
    ('kod', 'Acil Tıp Teknisyeni (ATT)', 1, 'Emergency Medical Technician (EMT)'),
    ('kod', 'Acil Yoğun Bakım', 1, 'Emergency Intensive Care'),
    ('kod', 'Adli Tıp', 1, 'Forensic Medicine'),
    ('kod', 'Ağız Yüz ve Çene Cerrahisi', 1, 'Oral and Maxillofacial Surgery'),
    ('kod', 'Ağız, Dış ve Çene Cerrahisi', 1, 'Oral, Dental and Maxillofacial Surgery'),
    ('kod', 'Ağız, Dış ve Çene Radyolojisi', 1, 'Oral, Dental and Maxillofacial Radiology'),
    ('kod', 'Ağız, Yüz ve Çene Cerrahisi', 1, 'Oral and Maxillofacial Surgery'),
    ('kod', 'Aile Hekimliği', 1, 'Family Medicine'),
    ('kod', 'Algoloji', 1, 'Algology (Pain Medicine)'),
    ('kod', 'AMATEM (Alkol ve Madde Bağımlılığı)', 1, 'AMATEM (Alcohol and Substance Addiction)'),
    ('kod', 'Ambar Görevlisi', 1, 'Warehouse Clerk'),
    ('kod', 'Ameliyathane Hemşiresi', 1, 'Operating Theatre Nurse'),
    ('kod', 'Ameliyathane Yoğun Bakım', 1, 'Operating Theatre Intensive Care'),
    ('kod', 'Anatomi', 1, 'Anatomy'),
    ('kod', 'Anestezi Teknisyeni', 1, 'Anaesthesia Technician'),
    ('kod', 'Anestezi ve Reanimasyon Yoğun Bakım', 1, 'Anaesthesia and Reanimation Intensive Care'),
    ('kod', 'Anesteziyoloji ve Reanimasyon', 1, 'Anaesthesiology and Reanimation'),
    ('kod', 'Arşiv Görevlisi', 1, 'Archive Clerk'),
    ('kod', 'Arşiv Sorumlusu', 1, 'Archive Supervisor'),
    ('kod', 'Asistan Hekim', 1, 'Resident Physician'),
    ('kod', 'Askeri Psikiyatri', 1, 'Military Psychiatry'),
    ('kod', 'Askeri Sağlık Hizmetleri', 1, 'Military Health Services'),
    ('kod', 'Aşçı', 1, 'Cook'),
    ('kod', 'Bağımlılık Polikliniği', 1, 'Addiction Clinic'),
    ('kod', 'Başhekim', 1, 'Chief Physician'),
    ('kod', 'Başhekim Yardımcısı', 1, 'Deputy Chief Physician'),
    ('kod', 'Başhekimlik', 1, 'Chief Physician''s Office'),
    ('kod', 'Başhemşire', 1, 'Head Nurse'),
    ('kod', 'Beyin Cerrahi Yoğun Bakım', 1, 'Neurosurgical Intensive Care'),
    ('kod', 'Beyin ve Sinir Cerrahisi', 1, 'Neurosurgery'),
    ('kod', 'Bilgi İşlem', 1, 'IT'),
    ('kod', 'Bilgi İşlem Müdürü', 1, 'IT Manager'),
    ('kod', 'Bilgi İşlem Personeli', 1, 'IT Staff'),
    ('kod', 'Bilgi İşlem Sorumlusu', 1, 'IT Supervisor'),
    ('kod', 'Birim Âmiri / Departman Sorumlusu', 1, 'Unit Manager / Department Supervisor'),
    ('kod', 'Biyomedikal Teknikeri', 1, 'Biomedical Technician'),
    ('kod', 'Biyomedikal Teknisyeni', 1, 'Biomedical Technician'),
    ('kod', 'Bordro Sorumlusu', 1, 'Payroll Supervisor'),
    ('kod', 'Böbrek Nakli', 1, 'Kidney Transplantation'),
    ('kod', 'Cerrahi Bilimler', 1, 'Surgical Sciences'),
    ('kod', 'Cerrahi Onkoloji', 1, 'Surgical Oncology'),
    ('kod', 'Cerrahi Yoğun Bakım', 1, 'Surgical Intensive Care'),
    ('kod', 'COVID-19 Aşı Uygulama  (Sinovac)', 1, 'COVID-19 Vaccination (Sinovac)'),
    ('kod', 'COVID-19 Aşı Uygulama (Biontech)', 1, 'COVID-19 Vaccination (BioNTech)'),
    ('kod', 'COVID-19 Aşı Uygulama (Turkovac)', 1, 'COVID-19 Vaccination (Turkovac)'),
    ('kod', 'Çağrı Merkezi / Randevu', 1, 'Call Centre / Appointments'),
    ('kod', 'Çağrı Merkezi Ajanı', 1, 'Call Centre Agent'),
    ('kod', 'Çağrı Merkezi Operatörü', 1, 'Call Centre Operator'),
    ('kod', 'Çağrı Merkezi Sorumlusu', 1, 'Call Centre Supervisor'),
    ('kod', 'ÇEMATEM (Çocuk Ergen Madde Bağımlılığı Tedavi Merkezi)', 1, 'ÇEMATEM (Child and Adolescent Substance Addiction Treatment Centre)'),
    ('kod', 'Çevre Sağlığı', 1, 'Environmental Health'),
    ('kod', 'Çocuk Acil', 1, 'Paediatric Emergency'),
    ('kod', 'Çocuk Cerrahi Yoğun Bakım', 1, 'Paediatric Surgical Intensive Care'),
    ('kod', 'Çocuk Cerrahisi', 1, 'Paediatric Surgery'),
    ('kod', 'Çocuk Dış Hekimliği', 1, 'Paediatric Dentistry'),
    ('kod', 'Çocuk Endokrinolojisi', 1, 'Paediatric Endocrinology'),
    ('kod', 'Çocuk Enfeksiyon Hastalıkları', 1, 'Paediatric Infectious Diseases'),
    ('kod', 'Çocuk Enfeksiyon Yoğun Bakım', 1, 'Paediatric Infectious Diseases Intensive Care'),
    ('kod', 'Çocuk Gastroenterolojisi', 1, 'Paediatric Gastroenterology'),
    ('kod', 'Çocuk Genetik Hastalıkları', 1, 'Paediatric Genetic Diseases'),
    ('kod', 'Çocuk Göğüs Hastalıkları', 1, 'Paediatric Pulmonology'),
    ('kod', 'Çocuk Hematolojisi', 1, 'Paediatric Haematology'),
    ('kod', 'Çocuk Hematolojisi ve Onkoloji', 1, 'Paediatric Haematology and Oncology'),
    ('kod', 'Çocuk Hematolojisi ve Onkolojisi', 1, 'Paediatric Haematology and Oncology'),
    ('kod', 'Çocuk İmmunolojisi ve Alerji Hastalıkları', 1, 'Paediatric Immunology and Allergy'),
    ('kod', 'Çocuk Kallp ve Damar Cerrahisi', 1, 'Paediatric Cardiovascular Surgery'),
    ('kod', 'Çocuk Kalp ve Damar Cerrahisi', 1, 'Paediatric Cardiovascular Surgery'),
    ('kod', 'Çocuk Kardiyolojisi', 1, 'Paediatric Cardiology'),
    ('kod', 'Çocuk Kemik İliği', 1, 'Paediatric Bone Marrow Transplantation'),
    ('kod', 'Çocuk Metabolizma Hastalıkları', 1, 'Paediatric Metabolic Diseases'),
    ('kod', 'Çocuk Nefrolojisi', 1, 'Paediatric Nephrology'),
    ('kod', 'Çocuk Nörolojisi', 1, 'Paediatric Neurology'),
    ('kod', 'Çocuk Onkolojisi', 1, 'Paediatric Oncology'),
    ('kod', 'Çocuk Radyolojisi', 1, 'Paediatric Radiology'),
    ('kod', 'Çocuk Romatolojisi', 1, 'Paediatric Rheumatology'),
    ('kod', 'Çocuk Romotolojisi', 1, 'Paediatric Rheumatology'),
    ('kod', 'Çocuk Sağlığı ve Hastalıkları', 1, 'Paediatrics'),
    ('kod', 'Çocuk Ürolojisi', 1, 'Paediatric Urology'),
    ('kod', 'Çocuk ve Ergen Ruh Sağlığı ve Hastalıkları', 1, 'Child and Adolescent Psychiatry'),
    ('kod', 'Çocuk Yoğun Bakım', 1, 'Paediatric Intensive Care'),
    ('kod', 'Çocuk Yoğun Bakımı', 1, 'Paediatric Intensive Care'),
    ('kod', 'Çözgem (Çok Disiplinli Çocuk ve Genç Ruh Sağlığı Merkezi)', 1, 'ÇÖZGEM (Multidisciplinary Child and Youth Mental Health Centre)'),
    ('kod', 'Dahili Bilimler', 1, 'Medical Sciences'),
    ('kod', 'Dahili Yoğun Bakım', 1, 'Medical Intensive Care'),
    ('kod', 'Dahiliye Hemşiresi', 1, 'Internal Medicine Nurse'),
    ('kod', 'Dahiliye Uzmanı', 1, 'Internal Medicine Specialist'),
    ('kod', 'Dahiliye Yoğun Bakım', 1, 'Internal Medicine Intensive Care'),
    ('kod', 'Danışma Görevlisi', 1, 'Information Desk Clerk'),
    ('kod', 'Depo / Ambar', 1, 'Warehouse / Store'),
    ('kod', 'Depo Sorumlusu', 1, 'Warehouse Supervisor'),
    ('kod', 'Deri ve Zührevi Hastalıklar', 1, 'Dermatology'),
    ('kod', 'Deri ve Zührevi Hastalıkları', 1, 'Dermatology'),
    ('kod', 'Dış Doktor (portal)', 1, 'External Physician (portal)'),
    ('kod', 'Dış Hekimliği (Genel Dış)', 1, 'Dentistry (General Dentistry)'),
    ('kod', 'Dış Kurum · Klinik (portal)', 1, 'External Institution · Clinical (portal)'),
    ('kod', 'Dış Kurum · Yönetici (portal)', 1, 'External Institution · Manager (portal)'),
    ('kod', 'Diğer Bölümler', 1, 'Other Departments'),
    ('kod', 'Diğer Görevler', 1, 'Other Positions'),
    ('kod', 'Diş Asistanı', 1, 'Dental Assistant'),
    ('kod', 'Diş Hekimi', 1, 'Dentist'),
    ('kod', 'Diş Hekimliği Nöbet Kliniği', 1, 'Dental On-Call Clinic'),
    ('kod', 'Diyetisyen', 1, 'Dietitian'),
    ('kod', 'Doktor Sekreteri', 1, 'Physician''s Secretary'),
    ('kod', 'Ebe', 1, 'Midwife'),
    ('kod', 'Ebe Polikliniği', 1, 'Midwifery Clinic'),
    ('kod', 'Eczane / Depo', 1, 'Pharmacy / Store'),
    ('kod', 'Eczane Teknisyeni', 1, 'Pharmacy Technician'),
    ('kod', 'Eğitim Birimi', 1, 'Training Unit'),
    ('kod', 'Eğitim Sorumlusu', 1, 'Training Supervisor'),
    ('kod', 'El cerrahisi', 1, 'Hand Surgery'),
    ('kod', 'Endokrin ve Metabolizma Hastalıkları', 1, 'Endocrinology and Metabolic Diseases'),
    ('kod', 'Endokrinoloji ve Metabolizma Hastalıkları', 1, 'Endocrinology and Metabolic Diseases'),
    ('kod', 'Endokrinoloji Yoğun Bakım', 1, 'Endocrinology Intensive Care'),
    ('kod', 'Endokrinoloji Yoğun Bakım Ünitesi', 1, 'Endocrinology Intensive Care Unit'),
    ('kod', 'Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji', 1, 'Infectious Diseases and Clinical Microbiology'),
    ('kod', 'Enfeksiyon Kontrol Hemşiresi', 1, 'Infection Control Nurse'),
    ('kod', 'Enfeksiyon Yoğun Bakım', 1, 'Infectious Diseases Intensive Care'),
    ('kod', 'Enfeksiyon Yoğun Bakım Ünitesi', 1, 'Infectious Diseases Intensive Care Unit'),
    ('kod', 'Epidemiyoloji', 1, 'Epidemiology'),
    ('kod', 'Erişkin Kemik İliği', 1, 'Adult Bone Marrow Transplantation'),
    ('kod', 'Evde Mobil COVID-19 Aşı Uygulaması', 1, 'Mobile Home COVID-19 Vaccination'),
    ('kod', 'Evde Sağlık Birimi', 1, 'Home Healthcare Unit'),
    ('kod', 'Farmakoloji', 1, 'Pharmacology'),
    ('kod', 'Faturalama Görevlisi', 1, 'Billing Clerk'),
    ('kod', 'Faturalama Sorumlusu', 1, 'Billing Supervisor'),
    ('kod', 'Faturalama ve Provizyon', 1, 'Billing and Authorisation'),
    ('kod', 'Finans Sorumlusu', 1, 'Finance Supervisor'),
    ('kod', 'Firma Yetkilisi (portal)', 1, 'Company Representative (portal)'),
    ('kod', 'Fiziksel Tıp ve Rehabilitasyon', 1, 'Physical Medicine and Rehabilitation'),
    ('kod', 'Fiziksel tıp ve Rehabiltasyon', 1, 'Physical Medicine and Rehabilitation'),
    ('kod', 'Fizyoloji', 1, 'Physiology'),
    ('kod', 'Gastroentereolji', 1, 'Gastroenterology'),
    ('kod', 'Gastroentereolji Cerrahisi', 1, 'Gastroenterological Surgery'),
    ('kod', 'Gastroenteroloji', 1, 'Gastroenterology'),
    ('kod', 'Gastroenteroloji Cerrahisi', 1, 'Gastroenterological Surgery'),
    ('kod', 'Gastroenteroloji Yoğun Bakım', 1, 'Gastroenterology Intensive Care'),
    ('kod', 'Gastroenterolojik Cerrahi Yoğun Bakım', 1, 'Gastroenterological Surgery Intensive Care'),
    ('kod', 'Gastroentroloji  Yoğun Bakım', 1, 'Gastroenterology Intensive Care'),
    ('kod', 'Gastroentroloji Cerrahi Yoğun Bakım', 1, 'Gastroenterological Surgery Intensive Care'),
    ('kod', 'Geleneksel Tamamlayıcı Tıp Ünitesi', 1, 'Traditional and Complementary Medicine Unit'),
    ('kod', 'Gelişimsel Pediatri', 1, 'Developmental Paediatrics'),
    ('kod', 'Genel Cerrahi Yoğun Bakım', 1, 'General Surgery Intensive Care'),
    ('kod', 'Genel Yoğun Bakım', 1, 'General Intensive Care'),
    ('kod', 'Geriatri', 1, 'Geriatrics'),
    ('kod', 'Göğüs Cerrahi  Yoğun Bakım', 1, 'Thoracic Surgery Intensive Care'),
    ('kod', 'Göğüs Cerrahi Yoğun Bakım', 1, 'Thoracic Surgery Intensive Care'),
    ('kod', 'Göğüs Cerrahisi', 1, 'Thoracic Surgery'),
    ('kod', 'Göğüs Hastalıkları', 1, 'Pulmonology'),
    ('kod', 'Göğüs Hastalıkları Yoğun Bakım', 1, 'Pulmonology Intensive Care'),
    ('kod', 'Göğüs Yoğun Bakım', 1, 'Pulmonology Intensive Care'),
    ('kod', 'Görüntüleme / Nükleer', 1, 'Imaging / Nuclear Medicine'),
    ('kod', 'Göz Doktoru', 1, 'Ophthalmologist'),
    ('kod', 'Göz Hastalıkları', 1, 'Ophthalmology'),
    ('kod', 'Göz Teknisyeni', 1, 'Ophthalmic Technician'),
    ('kod', 'Güvenlik Görevlisi', 1, 'Security Officer'),
    ('kod', 'Halk Sağlığı', 1, 'Public Health'),
    ('kod', 'Halkla İlişkiler / Pazarlama', 1, 'Public Relations / Marketing'),
    ('kod', 'Halkla İlişkiler Sorumlusu', 1, 'Public Relations Supervisor'),
    ('kod', 'Harp Cerrahisi', 1, 'War Surgery'),
    ('kod', 'Hasta (portal)', 1, 'Patient (portal)'),
    ('kod', 'Hasta Hakları', 1, 'Patient Rights'),
    ('kod', 'Hasta Hakları Birimi', 1, 'Patient Rights Unit'),
    ('kod', 'Hasta Hakları Sorumlusu', 1, 'Patient Rights Supervisor'),
    ('kod', 'Hasta Hizmetleri', 1, 'Patient Services'),
    ('kod', 'Hasta İlişkileri Sorumlusu', 1, 'Patient Relations Supervisor'),
    ('kod', 'Hasta Kabul / Danışma', 1, 'Patient Registration / Information'),
    ('kod', 'Hasta Kabul Görevlisi', 1, 'Patient Registration Clerk'),
    ('kod', 'Hasta Kabul Sorumlusu', 1, 'Patient Registration Supervisor'),
    ('kod', 'Hastane Müdür Yardımcısı', 1, 'Deputy Hospital Manager'),
    ('kod', 'Hastane Müdürü', 1, 'Hospital Manager'),
    ('kod', 'Hava ve Uzay Hekimliği', 1, 'Aerospace Medicine'),
    ('kod', 'Hekim Branşları', 1, 'Physician Specialties'),
    ('kod', 'Hematoloji Yoğun Bakım', 1, 'Haematology Intensive Care'),
    ('kod', 'Hemşire', 1, 'Nurse'),
    ('kod', 'Histoloji ve Embriyoloji', 1, 'Histology and Embryology'),
    ('kod', 'İç Hastalıkları', 1, 'Internal Medicine'),
    ('kod', 'İdari Birimler', 1, 'Administrative Units'),
    ('kod', 'İdari Müdür', 1, 'Administrative Manager'),
    ('kod', 'İdari ve Mali İşler Müdürlüğü', 1, 'Administrative and Financial Affairs Directorate'),
    ('kod', 'İK Personeli', 1, 'HR Staff'),
    ('kod', 'İK Sorumlusu', 1, 'HR Supervisor'),
    ('kod', 'İmmunoloji ve Alerji Hastalıkları', 1, 'Immunology and Allergy Diseases'),
    ('kod', 'İnsan Kaynakları', 1, 'Human Resources'),
    ('kod', 'İnsan Kaynakları / Eğitim', 1, 'Human Resources / Training'),
    ('kod', 'İnsan Kaynakları Müdürü', 1, 'Human Resources Manager'),
    ('kod', 'İnsan Kaynakları Uzmanı', 1, 'Human Resources Specialist'),
    ('kod', 'İSG Uzmanı', 1, 'OHS Specialist'),
    ('kod', 'İş ve Meslek Hastalıkları', 1, 'Occupational Medicine'),
    ('kod', 'İş ve Meslek Hastalıları', 1, 'Occupational Medicine'),
    ('kod', 'İşyeri Hekimi', 1, 'Occupational Physician'),
    ('kod', 'Jinekolojik Onkoloji Cerrahisi', 1, 'Gynaecological Oncology Surgery'),
    ('kod', 'Kadın Doğum Yoğun Bakım', 1, 'Obstetric Intensive Care'),
    ('kod', 'Kadın Hastalıkları ve Doğum', 1, 'Obstetrics and Gynaecology'),
    ('kod', 'Kalite / Arşiv', 1, 'Quality / Archive'),
    ('kod', 'Kalite Direktörü', 1, 'Quality Director'),
    ('kod', 'Kalite Görevlisi', 1, 'Quality Officer'),
    ('kod', 'Kalite Sorumlusu', 1, 'Quality Supervisor'),
    ('kod', 'Kalite Yönetimi', 1, 'Quality Management'),
    ('kod', 'Kalp Damar Cerrahisi', 1, 'Cardiovascular Surgery'),
    ('kod', 'Kalp ve Damar Cerrahisi', 1, 'Cardiovascular Surgery'),
    ('kod', 'Karaciğer Nakli', 1, 'Liver Transplantation'),
    ('kod', 'Kardiyoloji', 1, 'Cardiology'),
    ('kod', 'Kayıt Kabul / Banko', 1, 'Registration / Front Desk'),
    ('kod', 'Kayıt Kabul Sorumlusu (Banko Şefi)', 1, 'Registration Supervisor (Front Desk Lead)'),
    ('kod', 'Klinik Nörofizyoloji', 1, 'Clinical Neurophysiology'),
    ('kod', 'Koroner Yoğun Bakım', 1, 'Coronary Intensive Care'),
    ('kod', 'Kulak Burun Boğaz', 1, 'Ear, Nose and Throat'),
    ('kod', 'Kulak Burun Boğaz Hastalıkları', 1, 'Otorhinolaryngology'),
    ('kod', 'Kvc Yoğun Bakım', 1, 'Cardiovascular Surgery Intensive Care'),
    ('kod', 'KVC Yoğun Bakım', 1, 'Cardiovascular Surgery Intensive Care'),
    ('kod', 'Lab Sorumlusu (Protez)', 1, 'Lab Supervisor (Prosthetics)'),
    ('kod', 'Lab Teknisyeni', 1, 'Lab Technician'),
    ('kod', 'Lab Uzmanı', 1, 'Lab Specialist'),
    ('kod', 'Laborant', 1, 'Laboratory Assistant'),
    ('kod', 'Laboratuvar ve Temel Bilimler', 1, 'Laboratory and Basic Sciences'),
    ('kod', 'Mali İşler', 1, 'Financial Affairs'),
    ('kod', 'Mali İşler Müdürü', 1, 'Finance Manager'),
    ('kod', 'Mali İşler Sorumlusu', 1, 'Finance Supervisor'),
    ('kod', 'Medikal Estetik ve Kozmetik Uygulamalar', 1, 'Medical Aesthetics and Cosmetic Procedures'),
    ('kod', 'Medikal Muhasebe Personeli', 1, 'Medical Accounting Staff'),
    ('kod', 'Medula Sorumlusu', 1, 'MEDULA Supervisor'),
    ('kod', 'Mesul Müdür', 1, 'Responsible Manager'),
    ('kod', 'Muhasebe / Finans', 1, 'Accounting / Finance'),
    ('kod', 'Muhasebe Elemanı', 1, 'Accounting Clerk'),
    ('kod', 'Muhasebe Müdürü', 1, 'Accounting Manager'),
    ('kod', 'Muhasebe Sorumlusu', 1, 'Accounting Supervisor'),
    ('kod', 'Muhasebe ve Finans', 1, 'Accounting and Finance'),
    ('kod', 'Mutfak / Yemekhane', 1, 'Kitchen / Canteen'),
    ('kod', 'Müdür', 1, 'Manager'),
    ('kod', 'Nefroloji', 1, 'Nephrology'),
    ('kod', 'Nefroloji Yoğun Bakım', 1, 'Nephrology Intensive Care'),
    ('kod', 'Neonatoloji', 1, 'Neonatology'),
    ('kod', 'Nöbetçi Müdür', 1, 'Duty Manager'),
    ('kod', 'Nöroloji', 1, 'Neurology'),
    ('kod', 'Nöroloji Yoğun Bakım', 1, 'Neurology Intensive Care'),
    ('kod', 'Nöromusküler Hastalıklar Birimi', 1, 'Neuromuscular Diseases Unit'),
    ('kod', 'Nükleer Tıp', 1, 'Nuclear Medicine'),
    ('kod', 'Onkoloji Yoğun Bakım', 1, 'Oncology Intensive Care'),
    ('kod', 'Optometrist / Refraksiyonist', 1, 'Optometrist / Refractionist'),
    ('kod', 'Organ Nakli Yoğun Bakım', 1, 'Transplant Intensive Care'),
    ('kod', 'Ortopedi ve Travmatoloji', 1, 'Orthopaedics and Traumatology'),
    ('kod', 'Ortopedi Yoğun Bakım', 1, 'Orthopaedics Intensive Care'),
    ('kod', 'OSGB Sekreteri', 1, 'OHS Centre Secretary'),
    ('kod', 'Palyatif Bakım Ünitesi', 1, 'Palliative Care Unit'),
    ('kod', 'Palyatif Kritik Bakım', 1, 'Palliative Critical Care'),
    ('kod', 'Pandemi Kliniği (Çocuk)', 1, 'Pandemic Clinic (Paediatric)'),
    ('kod', 'Pandemi Kliniği (Erişkin)', 1, 'Pandemic Clinic (Adult)'),
    ('kod', 'Pandemi Kliniği (Yenidoğan)', 1, 'Pandemic Clinic (Neonatal)'),
    ('kod', 'Pazarlama Sorumlusu', 1, 'Marketing Supervisor'),
    ('kod', 'Pediatri Yoğun Bakım', 1, 'Paediatric Intensive Care'),
    ('kod', 'Periferik Damar Cerrahisi', 1, 'Peripheral Vascular Surgery'),
    ('kod', 'Perinatoloji', 1, 'Perinatology'),
    ('kod', 'Periodontoloji', 1, 'Periodontology'),
    ('kod', 'Plastik, Rekonstrüktif ve Estetik Cerrahi', 1, 'Plastic, Reconstructive and Aesthetic Surgery'),
    ('kod', 'Post-Op Yoğun Bakım', 1, 'Post-Op Intensive Care'),
    ('kod', 'Pratisyen Doktor', 1, 'General Practitioner'),
    ('kod', 'Pratisyen Hekim', 1, 'General Practitioner'),
    ('kod', 'Protetik Dış Tedavisi', 1, 'Prosthodontics'),
    ('kod', 'Provizyon Görevlisi', 1, 'Authorisation Clerk'),
    ('kod', 'Psikolog', 1, 'Psychologist'),
    ('kod', 'Radyasyon Onkolojisi', 1, 'Radiation Oncology'),
    ('kod', 'Radyoloji Teknisyeni', 1, 'Radiology Technologist'),
    ('kod', 'Rapor Yenileme', 1, 'Report Renewal'),
    ('kod', 'Restoratif Dış Tedavisi', 1, 'Restorative Dentistry'),
    ('kod', 'Rol Atanmamış', 1, 'No Role Assigned'),
    ('kod', 'Romatoloji', 1, 'Rheumatology'),
    ('kod', 'Ruh Sağlığı ve Hastalıkları', 1, 'Psychiatry'),
    ('kod', 'Sağlık Kurulu Çözger (Çocuk Özel Gereksinim Raporu)', 1, 'Medical Board ÇÖZGER (Child Special Needs Report)'),
    ('kod', 'Sağlık Kurulu Erişkin', 1, 'Medical Board (Adult)'),
    ('kod', 'Sağlık Memuru', 1, 'Health Officer'),
    ('kod', 'Sağlık Personeli', 1, 'Health Personnel'),
    ('kod', 'Sağlık Turizmi Sorumlusu', 1, 'Health Tourism Supervisor'),
    ('kod', 'Sağlıklı Yaş Alma Merkezi', 1, 'Healthy Ageing Centre'),
    ('kod', 'Santral Görevlisi', 1, 'Switchboard Operator'),
    ('kod', 'Satınalma / Lojistik', 1, 'Purchasing / Logistics'),
    ('kod', 'Satınalma Müdürü', 1, 'Purchasing Manager'),
    ('kod', 'Sekreter', 1, 'Secretary'),
    ('kod', 'Sigarayı Bıraktırma Kliniği', 1, 'Smoking Cessation Clinic'),
    ('kod', 'Sistem Yöneticisi', 1, 'System Administrator'),
    ('kod', 'Sitopatoloji', 1, 'Cytopathology'),
    ('kod', 'Sosyal Hizmet Uzmanı', 1, 'Social Worker'),
    ('kod', 'Spor Hekimliği', 1, 'Sports Medicine'),
    ('kod', 'Sterilizasyon (MSÜ) Sorumlusu', 1, 'Sterilisation (CSSD) Supervisor'),
    ('kod', 'Sterilizasyon Personeli', 1, 'Sterilisation Staff'),
    ('kod', 'Sterilizasyon Ünitesi', 1, 'Sterilisation Unit'),
    ('kod', 'Sualtı Hekimliği ve Hiperbarik Tıp', 1, 'Underwater and Hyperbaric Medicine'),
    ('kod', 'Tahsilat Görevlisi', 1, 'Collections Clerk'),
    ('kod', 'Tanıtım / Satış', 1, 'Promotion / Sales'),
    ('kod', 'Tedavi Danışmanı', 1, 'Treatment Advisor'),
    ('kod', 'Teknik / Destek', 1, 'Technical / Support'),
    ('kod', 'Teknik Servis / Biyomedikal', 1, 'Technical Service / Biomedical'),
    ('kod', 'Teknik Servis Görevlisi', 1, 'Technical Service Officer'),
    ('kod', 'Teknik Servis Sorumlusu', 1, 'Technical Service Supervisor'),
    ('kod', 'Teleradyoloji Doktoru (dış)', 1, 'Teleradiology Physician (external)'),
    ('kod', 'Temel İmmünoloji', 1, 'Basic Immunology'),
    ('kod', 'Temizlik Hizmetleri', 1, 'Cleaning Services'),
    ('kod', 'Temizlik Personeli', 1, 'Cleaning Staff'),
    ('kod', 'Tıbbi Biyokimya', 1, 'Medical Biochemistry'),
    ('kod', 'Tıbbi Ekoloji ve Hidroklimatoloji', 1, 'Medical Ecology and Hydroclimatology'),
    ('kod', 'Tıbbi Farmakoloji', 1, 'Medical Pharmacology'),
    ('kod', 'Tıbbi Genetik', 1, 'Medical Genetics'),
    ('kod', 'Tıbbi Genetik Tanı Merkezi', 1, 'Medical Genetics Diagnostic Centre'),
    ('kod', 'Tıbbi Mikoloji', 1, 'Medical Mycology'),
    ('kod', 'Tıbbi Mikrobiyoloji', 1, 'Medical Microbiology'),
    ('kod', 'Tıbbi Onkoloji', 1, 'Medical Oncology'),
    ('kod', 'Tıbbi Parazitoloji', 1, 'Medical Parasitology'),
    ('kod', 'Tıbbi Patoloji', 1, 'Medical Pathology'),
    ('kod', 'Tıbbi Sekreter', 1, 'Medical Secretary'),
    ('kod', 'Tıbbi Sekreter / Arşiv', 1, 'Medical Secretary / Archive'),
    ('kod', 'Tıbbi Viroloji', 1, 'Medical Virology'),
    ('kod', 'Tüberküloz Birimi', 1, 'Tuberculosis Unit'),
    ('kod', 'Uyku Polikliniği', 1, 'Sleep Clinic'),
    ('kod', 'Uzman Doktor', 1, 'Specialist Physician'),
    ('kod', 'Uzman Dr.', 1, 'Specialist Dr'),
    ('kod', 'Uzman Hekim', 1, 'Specialist Physician'),
    ('kod', 'Üroloji', 1, 'Urology'),
    ('kod', 'Üroloji Yoğun Bakım', 1, 'Urology Intensive Care'),
    ('kod', 'Üst Yönetim (Mesul Müdür / Genel Müdür)', 1, 'Senior Management (Responsible Manager / General Manager)'),
    ('kod', 'Vezne', 1, 'Cashier''s Office'),
    ('kod', 'Vezne Görevlisi', 1, 'Cashier'),
    ('kod', 'Yanık Merkezi', 1, 'Burns Centre'),
    ('kod', 'Yanık Ünitesi', 1, 'Burns Unit'),
    ('kod', 'Yanık Yoğun Bakım', 1, 'Burns Intensive Care'),
    ('kod', 'Yatan Hasta Hemşiresi', 1, 'Inpatient Nurse'),
    ('kod', 'Yatış / Taburcu Ofisi', 1, 'Admissions / Discharge Office'),
    ('kod', 'Yemekhane Görevlisi', 1, 'Canteen Attendant'),
    ('kod', 'Yenidoğan Açık Yatak', 1, 'Neonatal Open Bed'),
    ('kod', 'Yenidoğan Cerrahi Yoğun Bakım', 1, 'Neonatal Surgical Intensive Care'),
    ('kod', 'Yenidoğan Cerrahisi Yoğun Bakım', 1, 'Neonatal Surgical Intensive Care'),
    ('kod', 'Yenidoğan Yoğun Bakım', 1, 'Neonatal Intensive Care'),
    ('kod', 'Yenidoğan Yoğun Bakım Küvöz', 1, 'Neonatal Intensive Care Incubator'),
    ('kod', 'Yoğun Bakım Hemşiresi', 1, 'Intensive Care Nurse'),
    ('kod', 'Yonetici', 1, 'Administrator'),
    ('kod', 'Yönetici Sekreteri', 1, 'Executive Secretary'),
    ('kod', 'Yönetim Görüntüleyici', 1, 'Management Viewer'),
    -- KADRO BOLUMLERI (rol agacinin optgroup basliklari)
    ('kod', 'Yönetim', 1, 'Management'),
    ('kod', 'Tıbbi hizmetler', 1, 'Medical services'),
    ('kod', 'Hemşirelik', 1, 'Nursing'),
    ('kod', 'Yardımcı sağlık ve teknik', 1, 'Allied health and technical'),
    ('kod', 'Hasta hizmetleri', 1, 'Patient services'),
    ('kod', 'Mali işler', 1, 'Finance'),
    ('kod', 'İdari ve destek', 1, 'Administration and support'),
    ('kod', 'Portal (kurum dışı)', 1, 'Portal (external)'),
    ('kod', 'Sistem', 1, 'System'),
    ('kod', 'Diğer', 1, 'Other')
on conflict (kapsam, anahtar, dil) do update set metin = excluded.metin,
    degistirme_tarihi = now();

do $$
declare v_en integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    raise notice '853 tamam: ingilizce sozluk % satir.', v_en;
end $$;
