-- ============================================================================
--  Gentegre AI — HİZMET VE TETKİK ADLARI İNGİLİZCE (854)
--  854_ingilizce_sozluk_hizmet_tetkik.sql
--
--  Kullanıcı: *"hizmet ve tetkik adlarını da çevir"*.
--
--  ============ KAPSAM: MODÜLE BAĞLI HİZMETLER =======================
--  `hizmet` tablosunda 10.123 satır / 7.819 TEKİL ad var - neredeyse
--  tamamı SUT kataloğunun toplu aktarımı. Hepsi bu betikte YOK; burada
--  ekranlarda fiilen görünen küme çevrildi:
--    · diş modülü hizmetleri (`dis_islem = 1`)   : 365
--    · laboratuvar tetkikleri (`lab_tetkik`)     :  64
--    · radyoloji hizmetleri / hizmet grup başlıkları
--    · belgelerde kullanılmış hizmetler
--  Toplam 441 tekil ad.
--
--  KALAN ~7.200 SUT ADI BİLEREK ÇEVRİLMEDİ: bunlar mevzuat kataloğudur;
--  toplu makine çevirisi cerrahi/işlem adlarında anlam kaydırır. Doğru yol
--  Bakanlığın/SGK'nın İngilizce listesi ya da gözden geçirilmiş toplu
--  çeviridir. Karşılığı olmayan ad ekranda TÜRKÇE görünür - yanlış çeviri
--  göstermekten iyidir.
--
--  ============ FATURA VE MEDULA ETKİLENMEZ ==========================
--  Çeviri yalnız GÖSTERİMDİR: sunucu hizmet adını Türkçe tutar, MEDULA'ya
--  ve e-Belge'ye giden ad değişmez. Resmî çıktıda SUT adı Türkçe kalmalı.
--
--  "(*)" öneki SUT'ta özel şart işaretidir, korundu. Veri yazım hataları
--  ("Angle Snıf 3", "Sınıf II - Kontol Muayenesi") anahtar olduğu gibi
--  alındı; yoksa o satırlar İngilizce ekranda Türkçe kalırdı.
--
--  Idempotent (`on conflict do update`).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin) values
    ('kod', '(*) Açık Kapanış Ortodontik Tedavisi', 1, '(*) Orthodontic treatment of open bite'),
    ('kod', '(*) Ağız Dışı Aparey Tatbiki (Chinecap-Çenelik)', 1, '(*) Extraoral appliance (chin cap)'),
    ('kod', '(*) Ağız Dışı Aparey Tatbiki (Headgear-Yüzarkı)', 1, '(*) Extraoral appliance (headgear / face bow)'),
    ('kod', '(*) Angle Sınıf 1.(Class 1) Anomalilerin Ortodontik Tedavisi', 1, '(*) Orthodontic treatment of Angle Class 1 anomalies'),
    ('kod', '(*) Angle Sınıf 2.(Class 2) Anomalilerin Ortodontik Tedavisi', 1, '(*) Orthodontic treatment of Angle Class 2 anomalies'),
    ('kod', '(*) Angle Snıf 3.(Class 3) Anomalilerin Ortodontik Tedavisi', 1, '(*) Orthodontic treatment of Angle Class 3 anomalies'),
    ('kod', '(*) Arkteli Tatbiki Tek Çene, Her Bir Uygulama', 1, '(*) Arch wire placement, single arch, per application'),
    ('kod', '(*) Band (Braket) Tatbiki, Her Bir Diş', 1, '(*) Band (bracket) placement, per tooth'),
    ('kod', '(*) Hızlı Maksiller Expansiyon Apereyi', 1, '(*) Rapid maxillary expansion appliance'),
    ('kod', '(*) İki Çeneyi İlgilendiren Aparey Yapımı (Aktivatör)', 1, '(*) Fabrication of a two-arch appliance (activator)'),
    ('kod', '(*) Kısa Süreli Ortodontik Tedavi', 1, '(*) Short-term orthodontic treatment'),
    ('kod', '(*) Okluzal Cerrahi Splint', 1, '(*) Occlusal surgical splint'),
    ('kod', '(*) Ortodondik Ameliyat Arkı, Tek Çene', 1, '(*) Orthodontic surgical arch, single arch'),
    ('kod', '(*) Ortodontik Model Analizi', 1, '(*) Orthodontic model analysis'),
    ('kod', '(*) Pekiştirme Tedavisi', 1, '(*) Retention treatment'),
    ('kod', '(*) Sefelometrik Cerrahi Planı', 1, '(*) Cephalometric surgical plan'),
    ('kod', '(*) Tek Çeneyi İlgilendiren Aparey Yapımı', 1, '(*) Fabrication of a single-arch appliance'),
    ('kod', 'Açık Apeksli Dişte Kanal Tedavisi, Her Bir Kanal', 1, 'Root canal treatment of an open apex tooth, per canal'),
    ('kod', 'Açık Eklem Cerrahisi (Tek Taraflı)', 1, 'Open joint surgery (unilateral)'),
    ('kod', 'Adeziv Simantasyon (Diş Başı)', 1, 'Adhesive cementation (per tooth)'),
    ('kod', 'Ağız içi Kriyoterapi tedavisi', 1, 'Intraoral cryotherapy'),
    ('kod', 'Akrilik Bölümlü Protez, Tek Çene', 1, 'Acrylic partial denture, single arch'),
    ('kod', 'Akrilik bölümlü protez, tek çene- dişli prova', 1, 'Acrylic partial denture, single arch - tooth try-in'),
    ('kod', 'Akrilik bölümlü protez, tek çene- kapanış', 1, 'Acrylic partial denture, single arch - bite registration'),
    ('kod', 'Akrilik bölümlü protez, tek çene- ölçü', 1, 'Acrylic partial denture, single arch - impression'),
    ('kod', 'Akrilik İmmediat Protez, Tek Çene', 1, 'Acrylic immediate denture, single arch'),
    ('kod', 'Akrilik Protezde Kırık veya Çatlak Tamiri', 1, 'Repair of a fracture or crack in an acrylic denture'),
    ('kod', 'Akrilik Tam Protez, Tek Çene', 1, 'Acrylic complete denture, single arch'),
    ('kod', 'Akrilik tam protez, tek çene- dişli prova', 1, 'Acrylic complete denture, single arch - tooth try-in'),
    ('kod', 'Akrilik tam protez, tek çene- kapanış', 1, 'Acrylic complete denture, single arch - bite registration'),
    ('kod', 'Akrilik tam protez, tek çene- ölçü', 1, 'Acrylic complete denture, single arch - impression'),
    ('kod', 'Alçı Yüz Maskı', 1, 'Plaster face mask'),
    ('kod', 'ALT (SGPT)', 1, 'ALT (SGPT)'),
    ('kod', 'Alveol Düzeltilmesi, Tek Çene', 1, 'Alveoloplasty, single arch'),
    ('kod', 'Alveol Plastiği, Yarım Çene', 1, 'Alveoloplasty, half arch'),
    ('kod', 'Alveoler Distraksiyon İçin Osteotomi', 1, 'Osteotomy for alveolar distraction'),
    ('kod', 'Alveolit Cerrahi Tedavisi', 1, 'Surgical treatment of alveolitis'),
    ('kod', 'Amalgam Dolgu, Bir Yüzlü', 1, 'Amalgam filling, one surface'),
    ('kod', 'Amalgam Dolgu, İki Yüzlü', 1, 'Amalgam filling, two surfaces'),
    ('kod', 'Amalgam Dolgu, Üç Yüzlü', 1, 'Amalgam filling, three surfaces'),
    ('kod', 'Ameliyat ve Girişimler', 1, 'Surgery and interventions'),
    ('kod', 'Amputasyon', 1, 'Amputation'),
    ('kod', 'Antero-Posterior Sefalometrik Film Analizi', 1, 'Anteroposterior cephalometric film analysis'),
    ('kod', 'Antero-Posteriyor Sefalometrik Film, Her Biri', 1, 'Anteroposterior cephalometric film, each'),
    ('kod', 'Aparey Tamiri', 1, 'Appliance repair'),
    ('kod', 'Apse Drenajı, Ekstraoral', 1, 'Abscess drainage, extraoral'),
    ('kod', 'Artrosentez, Tek Taraf', 1, 'Arthrocentesis, unilateral'),
    ('kod', 'AST (SGOT)', 1, 'AST (SGOT)'),
    ('kod', 'Aşırı Kole Hassasiyet Tedavisi, Yarım Çene', 1, 'Treatment of severe cervical sensitivity, half arch'),
    ('kod', 'Aşırı kole hassasiyeti tedavisi,  Tek diş', 1, 'Treatment of severe cervical sensitivity, single tooth'),
    ('kod', 'Aşırı kole hassasiyeti tedavisi, Tam çene', 1, 'Treatment of severe cervical sensitivity, full arch'),
    ('kod', 'Avulse diş tedavisi diş başına', 1, 'Treatment of an avulsed tooth, per tooth'),
    ('kod', 'Bağ Dokusu Grefti, Her Bir Diş', 1, 'Connective tissue graft, per tooth'),
    ('kod', 'Balgam kültürü', 1, 'Sputum culture'),
    ('kod', 'Bant veya Braket çıkarılması', 1, 'Removal of a band or bracket'),
    ('kod', 'Basit Çene Defektlerine Protetik Tedavi', 1, 'Prosthetic treatment of simple jaw defects'),
    ('kod', 'Bazofil (%)', 1, 'Basophils (%)'),
    ('kod', 'Bazofil (mutlak)', 1, 'Basophils (absolute)'),
    ('kod', 'Besleme, Tek Çene', 1, 'Denture reline, single arch'),
    ('kod', 'Beyin BT, kontrastsız', 1, 'Brain CT, without contrast'),
    ('kod', 'Bilgisayar destekli rehber plak (implant cerrahisinde)', 1, 'Computer-guided surgical stent (implant surgery)'),
    ('kod', 'Bilgisayarlı Büyük Tme Fonksiyon Testi', 1, 'Computerised extended TMJ function test'),
    ('kod', 'Bilgisayarlı Kas Tonus Analizi (EMG)', 1, 'Computerised muscle tone analysis (EMG)'),
    ('kod', 'Bilgisayarlı Sefalometrik Film Analizi', 1, 'Computerised cephalometric film analysis'),
    ('kod', 'Bilinçli Sedasyon', 1, 'Conscious sedation'),
    ('kod', 'Bilirubin (strip)', 1, 'Bilirubin (dipstick)'),
    ('kod', 'Bite-Wing Film, Her Biri', 1, 'Bitewing radiograph, each'),
    ('kod', 'Biyomateryal Uygulaması, Her Bir Diş', 1, 'Biomaterial application, per tooth'),
    ('kod', 'Biyopsi', 1, 'Biopsy'),
    ('kod', 'Black 5 (Kole) Dolgusu, Amalgam', 1, 'Class V (cervical) filling, amalgam'),
    ('kod', 'Black 5 (Kole) Dolgusu, Cam İyonomer', 1, 'Class V (cervical) filling, glass ionomer'),
    ('kod', 'Black 5 (Kole) Dolgusu, Kompozit', 1, 'Class V (cervical) filling, composite'),
    ('kod', 'Boğaz kültürü', 1, 'Throat culture'),
    ('kod', 'BRCA1/2 NGS paneli', 1, 'BRCA1/2 NGS panel'),
    ('kod', 'Büküm İçeren Tel Tatbiki (Tek Çene)', 1, 'Placement of a wire with bends (single arch)'),
    ('kod', 'C-Reaktif Protein', 1, 'C-reactive protein'),
    ('kod', 'CAD-CAM Uygulaması', 1, 'CAD-CAM application'),
    ('kod', 'Cam İyonomer Dolgu', 1, 'Glass ionomer filling'),
    ('kod', 'Castillo Moraks Apareyi', 1, 'Castillo Morales appliance'),
    ('kod', 'Cerrahi Nevralji Tedavisi', 1, 'Surgical treatment of neuralgia'),
    ('kod', 'Çene Kırığı (Basit)', 1, 'Jaw fracture (simple)'),
    ('kod', 'Çene Kırığı (Komplike)', 1, 'Jaw fracture (complicated)'),
    ('kod', 'Çene Lüksasyonu, Basit', 1, 'Jaw dislocation, simple'),
    ('kod', 'Çıkan Bantın Tatbiki', 1, 'Re-placement of a debonded band'),
    ('kod', 'Çocuk Protezi  Bölümlü, Akrilik', 1, 'Paediatric partial denture, acrylic'),
    ('kod', 'Çocuk Protezi Tam', 1, 'Paediatric complete denture'),
    ('kod', 'Damak Yarığı Protezi (Over-Denture)', 1, 'Cleft palate prosthesis (overdenture)'),
    ('kod', 'Dansite (Özgül Ağırlık)', 1, 'Specific gravity'),
    ('kod', 'Dental İmplant Çıkarılması (İmplant Başına)', 1, 'Removal of a dental implant (per implant)'),
    ('kod', 'Dental implant Kırık Abutment Çıkarılması', 1, 'Removal of a fractured implant abutment'),
    ('kod', 'Dental Tomografi', 1, 'Dental tomography (CBCT)'),
    ('kod', 'Dentin Pinli Restorasyonu, Her Bir Pin', 1, 'Dentin pin restoration, per pin'),
    ('kod', 'Detertraj (Diş Taşı Temizliği), Alt Sağ Çene', 1, 'Scaling (calculus removal), lower right quadrant'),
    ('kod', 'Detertraj (Diş Taşı Temizliği), Alt Sol Çene', 1, 'Scaling (calculus removal), lower left quadrant'),
    ('kod', 'Detertraj (Diş Taşı Temizliği), Üst Sağ Çene', 1, 'Scaling (calculus removal), upper right quadrant'),
    ('kod', 'Detertraj (Diş Taşı Temizliği), Üst Sol Çene', 1, 'Scaling (calculus removal), upper left quadrant'),
    ('kod', 'Devital Ağartma Diş Başına', 1, 'Non-vital bleaching, per tooth'),
    ('kod', 'Diastema Kapatılması', 1, 'Diastema closure'),
    ('kod', 'Diğer İşlemler', 1, 'Other procedures'),
    ('kod', 'Distraksiyon cerrahi planlaması', 1, 'Distraction surgery planning'),
    ('kod', 'Diş / Odontojenik Kist', 1, 'Dental / odontogenic cyst'),
    ('kod', 'Diş Beyazlatma ( Alt- Üst Çene)', 1, 'Tooth whitening (upper and lower arch)'),
    ('kod', 'Diş Beyazlatma ( Tek diş)', 1, 'Tooth whitening (single tooth)'),
    ('kod', 'Diş Çekimi, İnfiltrasyon Anestezi ile', 1, 'Tooth extraction, with infiltration anaesthesia'),
    ('kod', 'Diş Çekimi, Rejyonel Anestezi ile', 1, 'Tooth extraction, with regional anaesthesia'),
    ('kod', 'Diş Hekimi Muayenesi', 1, 'Dental examination'),
    ('kod', 'Diş İlavesi, Tek Diş', 1, 'Addition of a tooth, single tooth'),
    ('kod', 'Diş İşlemi', 1, 'Dental procedure'),
    ('kod', 'Diş Kökü Çekimi, İnfiltrasyon Anestezi ile', 1, 'Root extraction, with infiltration anaesthesia'),
    ('kod', 'Diş Kron Kırığı Tedavisi', 1, 'Treatment of a crown fracture'),
    ('kod', 'Dolgu (Restorasyon) Tamiri', 1, 'Repair of a filling (restoration)'),
    ('kod', 'Dolgu Sökümü (tek diş)', 1, 'Removal of a filling (single tooth)'),
    ('kod', 'Döküm Post Uygulaması veya Sökümü', 1, 'Placement or removal of a cast post'),
    ('kod', 'Düşmüş Kron-Köprü Simantasyonu, Her Sabit Tutucu İçin', 1, 'Recementation of a dislodged crown/bridge, per retainer'),
    ('kod', 'Düz Ark Teli Tatbiki (Tek Çene NİTİ Telleri)', 1, 'Placement of a straight arch wire (single arch, NiTi)'),
    ('kod', 'Eksternal distraktör ağız içi aygıt', 1, 'External distractor, intraoral device'),
    ('kod', 'Ekstirpasyon, Her Bir Diş', 1, 'Pulp extirpation, per tooth'),
    ('kod', 'Ekstra-Oral Film, Her Biri', 1, 'Extraoral radiograph, each'),
    ('kod', 'El-Bilek Filmi, Her Biri', 1, 'Hand-wrist radiograph, each'),
    ('kod', 'Eozinofil (%)', 1, 'Eosinophils (%)'),
    ('kod', 'Eozinofil (mutlak)', 1, 'Eosinophils (absolute)'),
    ('kod', 'Epitel Hücresi', 1, 'Epithelial cells'),
    ('kod', 'Epulis Operasyonu', 1, 'Epulis excision'),
    ('kod', 'Eritrosit', 1, 'Erythrocytes'),
    ('kod', 'Eritrosit Dağılım Genişliği (CV)', 1, 'Red cell distribution width (CV)'),
    ('kod', 'Eritrosit Dağılım Genişliği (SD)', 1, 'Red cell distribution width (SD)'),
    ('kod', 'Erken Ortodontik Tedavi 1. Kontrol Muayenesi', 1, 'Early orthodontic treatment, 1st review'),
    ('kod', 'Erken Ortodontik Tedavi 2. Kontrol Muayenesi', 1, 'Early orthodontic treatment, 2nd review'),
    ('kod', 'Erken Ortodontik Tedavi 3. Kontrol Muayenesi', 1, 'Early orthodontic treatment, 3rd review'),
    ('kod', 'Erken Ortodontik Tedavi 4. Kontrol Muayenesi', 1, 'Early orthodontic treatment, 4th review'),
    ('kod', 'Erken Ortodontik Tedavi Başlangıç Aşaması', 1, 'Early orthodontic treatment, initial phase'),
    ('kod', 'Erken Ortodontik Tedavi Bitiş Aşaması', 1, 'Early orthodontic treatment, final phase'),
    ('kod', 'Fiber ile Sabit Yer Tutucu Uygulaması', 1, 'Fibre-reinforced fixed space maintainer'),
    ('kod', 'Fiberle Güçlendirilmiş Komposit Restorasyon (Diş Başına)', 1, 'Fibre-reinforced composite restoration (per tooth)'),
    ('kod', 'Fibrom Operasyonu', 1, 'Fibroma excision'),
    ('kod', 'Fissür Örtülmesi (Sealant), Her Bir Diş', 1, 'Fissure sealant, per tooth'),
    ('kod', 'Fizik Tedavi (İnfraruj), Her Bir Seans', 1, 'Physical therapy (infrared), per session'),
    ('kod', 'Flep Operasyonu, Yarım Çene', 1, 'Flap surgery, half arch'),
    ('kod', 'Frenektomi', 1, 'Frenectomy'),
    ('kod', 'Gaita kültürü', 1, 'Stool culture'),
    ('kod', 'Gangren veya Periapikal Lezyon Tedavisi', 1, 'Treatment of gangrene or a periapical lesion'),
    ('kod', 'Gece Plağı (Bruksizm İçin)', 1, 'Night guard (for bruxism)'),
    ('kod', 'Geçici Hareketli Bölümlü Protez Tek Çene', 1, 'Temporary removable partial denture, single arch'),
    ('kod', 'Geçici Hareketli Tam Protez Tek Çene', 1, 'Temporary removable complete denture, single arch'),
    ('kod', 'Geçici Kron, Her Bir Diş', 1, 'Temporary crown, per tooth'),
    ('kod', 'Geçici Opturatör (Cerrahi Plaklar)', 1, 'Temporary obturator (surgical plates)'),
    ('kod', 'Genioplasti', 1, 'Genioplasty'),
    ('kod', 'Gingivektomi, Yarım Çene', 1, 'Gingivectomy, half arch'),
    ('kod', 'Gingivoplasti, Yarım Çene', 1, 'Gingivoplasty, half arch'),
    ('kod', 'Glukoz', 1, 'Glucose'),
    ('kod', 'Glukoz (BOS)', 1, 'Glucose (CSF)'),
    ('kod', 'Glukoz (strip)', 1, 'Glucose (dipstick)'),
    ('kod', 'Gnatoloji, Tme-Kas Muayenesi (Okluzyon Kontrolü)', 1, 'Gnathology, TMJ and muscle examination (occlusal check)'),
    ('kod', 'Gömülü   Diş Çekimi, Kemik Retansiyonlu', 1, 'Extraction of an impacted tooth, bone retained'),
    ('kod', 'Gömülü Diş Çekimi, Mukoza Retansiyonlu', 1, 'Extraction of an impacted tooth, soft tissue retained'),
    ('kod', 'Gömülü dişin sürdürülmesi (tek diş)', 1, 'Exposure and eruption of an impacted tooth (single tooth)'),
    ('kod', 'Gömülü Kanin-Premolar Diş Çekimi', 1, 'Extraction of an impacted canine or premolar'),
    ('kod', 'Hareketli Periodontal Protez, Tek Çene', 1, 'Removable periodontal prosthesis, single arch'),
    ('kod', 'Hassas Tutuculu Kronlar', 1, 'Crowns with precision attachments'),
    ('kod', 'Hassas Tutuculu Protezler (Tek Çene)', 1, 'Dentures with precision attachments (single arch)'),
    ('kod', 'Hematokrit', 1, 'Haematocrit'),
    ('kod', 'Hemiseksiyon (Kök Amputasyonu)', 1, 'Hemisection (root amputation)'),
    ('kod', 'Hemoglobin', 1, 'Haemoglobin'),
    ('kod', 'INR', 1, 'INR'),
    ('kod', 'Işınlı Kompozit Dolgu, Arka Diş, Bir Yüzlü', 1, 'Light-cured composite filling, posterior, one surface'),
    ('kod', 'Işınlı Kompozit Dolgu, Arka Diş, İki Yüzlü', 1, 'Light-cured composite filling, posterior, two surfaces'),
    ('kod', 'Işınlı Kompozit Dolgu, Arka Diş, Üç Yüzlü', 1, 'Light-cured composite filling, posterior, three surfaces'),
    ('kod', 'Işınlı Kompozit Dolgu, Ön Diş', 1, 'Light-cured composite filling, anterior'),
    ('kod', 'İdrar Görünümü', 1, 'Urine appearance'),
    ('kod', 'İdrar kültürü ve antibiyogram', 1, 'Urine culture and antibiogram'),
    ('kod', 'İdrar pH', 1, 'Urine pH'),
    ('kod', 'İdrar Rengi', 1, 'Urine colour'),
    ('kod', 'İmplant Destekli Hareketli Protezler (Tek Çene)', 1, 'Implant-supported removable denture (single arch)'),
    ('kod', 'İmplant diş eti şekillendiricisi uygulaması', 1, 'Placement of an implant gingival former'),
    ('kod', 'İmplant Rehber Stenti', 1, 'Implant surgical stent'),
    ('kod', 'İmplant Üstü Bölümlü Protez', 1, 'Implant-supported partial denture'),
    ('kod', 'İmplant Üstü Kron Köprü, Her Üye İçin', 1, 'Implant-supported crown/bridge, per unit'),
    ('kod', 'İmplant Üstü Tam Protez', 1, 'Implant-supported complete denture'),
    ('kod', 'İmplant Üzeri Organ ve Doku Protezleri', 1, 'Implant-supported organ and tissue prostheses'),
    ('kod', 'İnley Dolgu, İki Yüzlü', 1, 'Inlay, two surfaces'),
    ('kod', 'İnley Dolgu, Oklüzal', 1, 'Inlay, occlusal'),
    ('kod', 'İnley Dolgu, Üç Yüzlü', 1, 'Inlay, three surfaces'),
    ('kod', 'İnterproksimal redüksiyon (diş başına)', 1, 'Interproximal reduction (per tooth)'),
    ('kod', 'İntraoral otojen greft alınımı tek taraflı', 1, 'Harvesting an intraoral autogenous graft, unilateral'),
    ('kod', 'Jaket Kron, Akrilik', 1, 'Jacket crown, acrylic'),
    ('kod', 'Jaket Kron, Tam Seramik (Metal Desteksiz)', 1, 'Jacket crown, all-ceramic (metal free)'),
    ('kod', 'Kalsiyum', 1, 'Calcium'),
    ('kod', 'Kan / Eritrosit (strip)', 1, 'Blood / erythrocytes (dipstick)'),
    ('kod', 'Kan İşlemleri', 1, 'Blood procedures'),
    ('kod', 'Kan kültürü (aerob/anaerob)', 1, 'Blood culture (aerobic/anaerobic)'),
    ('kod', 'Kanal Dolgusu Sökümü (her Kanal İçin)', 1, 'Removal of a root filling (per canal)'),
    ('kod', 'Kanal İçi Post Uygulaması, Her Bir Diş', 1, 'Placement of an intracanal post, per tooth'),
    ('kod', 'Kanal İçi Rezorpsiyon Tedavisi (Kanal Başına)', 1, 'Treatment of internal resorption (per canal)'),
    ('kod', 'Kanal Tedavisi, İki Kanal', 1, 'Root canal treatment, two canals'),
    ('kod', 'Kanal Tedavisi, İlave Her Kanal', 1, 'Root canal treatment, each additional canal'),
    ('kod', 'Kanal Tedavisi, Tek Kanal', 1, 'Root canal treatment, single canal'),
    ('kod', 'Kanal Tedavisi, Üç Kanal', 1, 'Root canal treatment, three canals'),
    ('kod', 'Kanaldan Kırık Alet Çıkartılması', 1, 'Removal of a fractured instrument from a canal'),
    ('kod', 'Kanama Müdahalesi', 1, 'Management of bleeding'),
    ('kod', 'Kapişon İzalesi veya İmplant Üstü Açılması', 1, 'Operculectomy or implant uncovering'),
    ('kod', 'Kardiyomiyopati NGS paneli (germline)', 1, 'Cardiomyopathy NGS panel (germline)'),
    ('kod', 'Kayıp Apareyin Yeniden Yapımı, Tek Çene', 1, 'Remaking a lost appliance, single arch'),
    ('kod', 'Kemik İçi İmplant Uygulaması, Tek Ünite', 1, 'Endosseous implant placement, single unit'),
    ('kod', 'Kemik Yaşı Tayini', 1, 'Bone age assessment'),
    ('kod', 'Keton (strip)', 1, 'Ketones (dipstick)'),
    ('kod', 'Kırılan apareyin yeniden yapımı tek çene', 1, 'Remaking a broken appliance, single arch'),
    ('kod', 'Kırılan ark telinin değişimi', 1, 'Replacement of a broken arch wire'),
    ('kod', 'Kist Operasyonu, Büyük', 1, 'Cyst surgery, large'),
    ('kod', 'Kist Operasyonu, Küçük', 1, 'Cyst surgery, small'),
    ('kod', 'Komplikasyonlu Diş Çekimi, İnfiltrasyon Anestezi ile', 1, 'Complicated tooth extraction, with infiltration anaesthesia'),
    ('kod', 'Komplikasyonlu Diş Çekimi, Rejyonel Anestezi ile', 1, 'Complicated tooth extraction, with regional anaesthesia'),
    ('kod', 'Komplike Çene Defektlerine Protetik Tedavi', 1, 'Prosthetic treatment of complex jaw defects'),
    ('kod', 'Kompomer Dolgu, Her Bir Diş', 1, 'Compomer filling, per tooth'),
    ('kod', 'Kompozit Dolgu, Arka Diş', 1, 'Composite filling, posterior'),
    ('kod', 'Kompozit Dolgu, Ön Diş', 1, 'Composite filling, anterior'),
    ('kod', 'Kompozit Veneer', 1, 'Composite veneer'),
    ('kod', 'Konsultasyon', 1, 'Consultation'),
    ('kod', 'Konsültan Diş Hekimi Muayenesi', 1, 'Consultant dental examination'),
    ('kod', 'Kopan Ortodontik Ataçmanın Yeniden Yapıştırılması (Ataçman Başına)', 1, 'Rebonding a debonded orthodontic attachment (per attachment)'),
    ('kod', 'Koronale Kaydırma veya Sliding Flep, Yarım Çene', 1, 'Coronally advanced or sliding flap, half arch'),
    ('kod', 'Kortikotomi (çene genişletilmesi amaçlı)', 1, 'Corticotomy (for arch expansion)'),
    ('kod', 'Kortikotomi tek diş', 1, 'Corticotomy, single tooth'),
    ('kod', 'Kök Ucu Rezeksiyonu, Tek Diş', 1, 'Apicoectomy, single tooth'),
    ('kod', 'Kreatinin', 1, 'Creatinine'),
    ('kod', 'Kristal', 1, 'Crystals'),
    ('kod', 'Kron Sökümü, Her Ayak Üye İçin', 1, 'Crown removal, per abutment unit'),
    ('kod', 'Kron, Köprü Tamiri, Her Üye İçin', 1, 'Crown or bridge repair, per unit'),
    ('kod', 'Kronlarda Freze Tekniği  Farkı', 1, 'Milling technique surcharge for crowns'),
    ('kod', 'Kroşe İlavesi', 1, 'Addition of a clasp'),
    ('kod', 'Kuafaj', 1, 'Pulp capping'),
    ('kod', 'Laminate Veneer', 1, 'Laminate veneer'),
    ('kod', 'Laminate Veneer Kron (akrilik)', 1, 'Laminate veneer crown (acrylic)'),
    ('kod', 'Laminate Veneer Kron (seramik)', 1, 'Laminate veneer crown (ceramic)'),
    ('kod', 'Lateral/Ekstrüzyon/İntrozyon Tedavisi diş başına', 1, 'Treatment of lateral luxation / extrusion / intrusion, per tooth'),
    ('kod', 'Lazerle Sert Doku Uygulamalaları', 1, 'Laser hard tissue procedures'),
    ('kod', 'Lazerle Yumuşak Doku Uygulamaları', 1, 'Laser soft tissue procedures'),
    ('kod', 'Lenfosit (%)', 1, 'Lymphocytes (%)'),
    ('kod', 'Lenfosit (mutlak)', 1, 'Lymphocytes (absolute)'),
    ('kod', 'Lokal Anestezi, İnfiltrasyon', 1, 'Local anaesthesia, infiltration'),
    ('kod', 'Lokal Anestezi, Rejyonel', 1, 'Local anaesthesia, regional'),
    ('kod', 'Lökosit', 1, 'Leucocytes'),
    ('kod', 'Lökosit Esteraz (strip)', 1, 'Leucocyte esterase (dipstick)'),
    ('kod', 'Lumbo-sakral radyografi, iki yönlü', 1, 'Lumbosacral radiograph, two views'),
    ('kod', 'Marsüpiyalizasyon', 1, 'Marsupialisation'),
    ('kod', 'Maryland (Andheziv) Köprü', 1, 'Maryland (adhesive) bridge'),
    ('kod', 'Membran Uygulaması', 1, 'Membrane placement'),
    ('kod', 'Metal İskelet Tamiri', 1, 'Repair of a metal framework'),
    ('kod', 'Metal Kaideli Bölümlü Protez, Tek Çene', 1, 'Metal-based partial denture, single arch'),
    ('kod', 'Metal kaideli bölümlü protez, tek çene- dişli prova', 1, 'Metal-based partial denture, single arch - tooth try-in'),
    ('kod', 'Metal kaideli bölümlü protez, tek çene- iskelet prova', 1, 'Metal-based partial denture, single arch - framework try-in'),
    ('kod', 'Metal kaideli bölümlü protez, tek çene- kapanış', 1, 'Metal-based partial denture, single arch - bite registration'),
    ('kod', 'Metal kaideli bölümlü protez, tek çene- ölçü', 1, 'Metal-based partial denture, single arch - impression'),
    ('kod', 'Metal Kaideli Tam Protez, Tek Çene', 1, 'Metal-based complete denture, single arch'),
    ('kod', 'Metal kaideli tam protez, tek çene- dişli prova', 1, 'Metal-based complete denture, single arch - tooth try-in'),
    ('kod', 'Metal kaideli tam protez, tek çene- kapanış', 1, 'Metal-based complete denture, single arch - bite registration'),
    ('kod', 'Metal kaideli tam protez, tek çene- ölçü', 1, 'Metal-based complete denture, single arch - impression'),
    ('kod', 'Miniplak vida distraktör sökümü', 1, 'Removal of a miniplate, screw or distractor'),
    ('kod', 'Model Set-Up', 1, 'Model set-up'),
    ('kod', 'Monosit (%)', 1, 'Monocytes (%)'),
    ('kod', 'Monosit (mutlak)', 1, 'Monocytes (absolute)'),
    ('kod', 'Mta Kullanımı (Diş Başına)', 1, 'MTA use (per tooth)'),
    ('kod', 'Muayene İşlemi', 1, 'Examination procedure'),
    ('kod', 'Mukus', 1, 'Mucus'),
    ('kod', 'Nance Aparey', 1, 'Nance appliance'),
    ('kod', 'Nitrit (strip)', 1, 'Nitrite (dipstick)'),
    ('kod', 'Normal Poliklinik Muayenesi', 1, 'Routine outpatient examination'),
    ('kod', 'Nötrofil (%)', 1, 'Neutrophils (%)'),
    ('kod', 'Nötrofil (mutlak)', 1, 'Neutrophils (absolute)'),
    ('kod', 'Obstruktif Uyku Apnesi Apareyi', 1, 'Obstructive sleep apnoea appliance'),
    ('kod', 'Odontojenik Tümör Operasyonu, Büyük', 1, 'Odontogenic tumour surgery, large'),
    ('kod', 'Odontojenik Tümör Operasyonu, Küçük', 1, 'Odontogenic tumour surgery, small'),
    ('kod', 'Oklüzal Aşındırmalar, Tek Çene', 1, 'Occlusal adjustment, single arch'),
    ('kod', 'Oklüzal Film, Her Biri', 1, 'Occlusal radiograph, each'),
    ('kod', 'Onley', 1, 'Onlay'),
    ('kod', 'Oro-Antral Fistül Tedavisi', 1, 'Treatment of an oroantral fistula'),
    ('kod', 'Ortalama Eritrosit Hacmi', 1, 'Mean corpuscular volume (MCV)'),
    ('kod', 'Ortalama Eritrosit Hb Konsantrasyonu', 1, 'Mean corpuscular haemoglobin concentration (MCHC)'),
    ('kod', 'Ortalama Eritrosit Hemoglobini', 1, 'Mean corpuscular haemoglobin (MCH)'),
    ('kod', 'Ortalama Trombosit Hacmi', 1, 'Mean platelet volume (MPV)'),
    ('kod', 'Ortodontik  Fotograf', 1, 'Orthodontic photograph'),
    ('kod', 'Ortodontik Ankraj Amaçlı Plak Yerleştirilmesi', 1, 'Placement of a plate for orthodontic anchorage'),
    ('kod', 'Ortodontik düşük doz lazer uygulaması (tek çene)', 1, 'Orthodontic low-level laser therapy (single arch)'),
    ('kod', 'Ortodontik Fotograf Analizi', 1, 'Orthodontic photograph analysis'),
    ('kod', 'Ortodontik Model Yapımı', 1, 'Fabrication of orthodontic models'),
    ('kod', 'Ortodontik Modellerin Face-Bow İle Artikülatöre Taşınması', 1, 'Face-bow transfer of orthodontic models to an articulator'),
    ('kod', 'Ortodontik Şeffaf Plak Uygulaması (Plak Başına)', 1, 'Clear aligner placement (per aligner)'),
    ('kod', 'Ortodontik Tedavi Amaçlı Gömülü Dişlerin Üzerinin Açılması', 1, 'Surgical exposure of impacted teeth for orthodontic treatment'),
    ('kod', 'Ortognatik Cerrahide Ortodontik tedavi, Başlangıç', 1, 'Orthodontic treatment in orthognathic surgery, initial'),
    ('kod', 'Ortognatik Cerrahide Ortodontik tedavi, Pekiştirme', 1, 'Orthodontic treatment in orthognathic surgery, retention'),
    ('kod', 'Ortognatik Cerrahide Ortodontik tedavi, Tedavi', 1, 'Orthodontic treatment in orthognathic surgery, active treatment'),
    ('kod', 'Ortopantomograf (Panoromik) Film', 1, 'Orthopantomogram (panoramic) radiograph'),
    ('kod', 'Osteomiyelit Operasyonu, Tek Çene', 1, 'Osteomyelitis surgery, single arch'),
    ('kod', 'Osteotomi (Tek Çene)', 1, 'Osteotomy (single arch)'),
    ('kod', 'Ototransplantasyon', 1, 'Autotransplantation'),
    ('kod', 'Önleyici Ortodontik Tedavisi (Dil Paravanası)', 1, 'Preventive orthodontic treatment (tongue crib)'),
    ('kod', 'Palatal crip', 1, 'Palatal crib'),
    ('kod', 'Pansuman Seans Başı', 1, 'Dressing, per session'),
    ('kod', 'Parazit / Trichomonas', 1, 'Parasites / Trichomonas'),
    ('kod', 'Parmak apareyi', 1, 'Thumb-sucking appliance'),
    ('kod', 'Pekiştirme Aygıtı (Havley Pi)', 1, 'Retainer (Hawley plate)'),
    ('kod', 'Pendex Apareyi', 1, 'Pendex appliance'),
    ('kod', 'Peri-İmplantitis Tedavisi (İmplant Başına)', 1, 'Treatment of peri-implantitis (per implant)'),
    ('kod', 'Periapikal Film, Her Biri (Analog/Dijital)', 1, 'Periapical radiograph, each (analogue/digital)'),
    ('kod', 'Periodontal Apse Tedavisi', 1, 'Treatment of a periodontal abscess'),
    ('kod', 'Periodontal Şine (Splint), Devamlı Tek Çene', 1, 'Periodontal splint, permanent, single arch'),
    ('kod', 'Periodontal Şine (Splint), Geçici Tek Çene', 1, 'Periodontal splint, temporary, single arch'),
    ('kod', 'Pinley ve Çeşitleri', 1, 'Pinlay and variants'),
    ('kod', 'Pivo (Çivili Kron) veya Post-Core', 1, 'Post crown or post-core'),
    ('kod', 'Positioner Yapımı', 1, 'Fabrication of a positioner'),
    ('kod', 'Potasyum', 1, 'Potassium'),
    ('kod', 'Prefabrike Kron', 1, 'Prefabricated crown'),
    ('kod', 'Prefabrike zirkonyum kron', 1, 'Prefabricated zirconia crown'),
    ('kod', 'Premedikasyon ve Sedasyon', 1, 'Premedication and sedation'),
    ('kod', 'Protein (strip)', 1, 'Protein (dipstick)'),
    ('kod', 'Proteze Yumuşak Akrilik Uygulaması', 1, 'Soft acrylic liner for a denture'),
    ('kod', 'Proteze yumuşak akrilik uygulaması geçici tek çene', 1, 'Temporary soft acrylic liner for a denture, single arch'),
    ('kod', 'Quad Helix', 1, 'Quad helix'),
    ('kod', 'Rebazaj (Kaide Yenileme), Tek Çene', 1, 'Rebasing, single arch'),
    ('kod', 'Reimplantasyon, Tek Diş', 1, 'Replantation, single tooth'),
    ('kod', 'Retreatment (iki kanal için)', 1, 'Root canal retreatment (two canals)'),
    ('kod', 'Retreatment (Tek kanal için)', 1, 'Root canal retreatment (single canal)'),
    ('kod', 'Retreatment (Üç kanal için)', 1, 'Root canal retreatment (three canals)'),
    ('kod', 'Retrograt Dolgu', 1, 'Retrograde filling'),
    ('kod', 'Reverse Headgear', 1, 'Reverse headgear'),
    ('kod', 'Rezin inflitrasyon uygulamaları', 1, 'Resin infiltration procedures'),
    ('kod', 'Roach Köprü', 1, 'Roach bridge'),
    ('kod', 'Sabit Fonksiyonel Aparey Uygulaması', 1, 'Placement of a fixed functional appliance'),
    ('kod', 'Sabit Pekiştirme Aygıtı (Lingual Ratainer)', 1, 'Fixed retainer (lingual retainer)'),
    ('kod', 'Sabit Periodontal Protez, Her Üye İçin', 1, 'Fixed periodontal prosthesis, per unit'),
    ('kod', 'Sediment Eritrosit', 1, 'Sediment erythrocytes'),
    ('kod', 'Sediment Lökosit', 1, 'Sediment leucocytes'),
    ('kod', 'Sefalometrik Film Analizi', 1, 'Cephalometric film analysis'),
    ('kod', 'Sefalometrik Film, Her Biri', 1, 'Cephalometric radiograph, each'),
    ('kod', 'Segmental Ark veya Tork Arkı Tatbiki', 1, 'Placement of a segmental or torque arch'),
    ('kod', 'Segmental Osteotomi', 1, 'Segmental osteotomy'),
    ('kod', 'Seramik İnley dolgu ( Bir Yüzlü )', 1, 'Ceramic inlay (one surface)'),
    ('kod', 'Seramik İnley dolgu ( İki Yüzlü )', 1, 'Ceramic inlay (two surfaces)'),
    ('kod', 'Seramik İnley dolgu ( Üç Yüzlü )', 1, 'Ceramic inlay (three surfaces)'),
    ('kod', 'Serbest Diş Eti Grefti, Yarım Çene', 1, 'Free gingival graft, half arch'),
    ('kod', 'Sert Doku Greftleme', 1, 'Hard tissue grafting'),
    ('kod', 'Sialografi (İki Taraf)', 1, 'Sialography (bilateral)'),
    ('kod', 'Sialografi, (Tek Taraf)', 1, 'Sialography (unilateral)'),
    ('kod', 'Silendir', 1, 'Casts'),
    ('kod', 'Sinüs Lifting', 1, 'Sinus lift'),
    ('kod', 'Sinüs Plastiği', 1, 'Sinus plasty'),
    ('kod', 'Sodyum', 1, 'Sodium'),
    ('kod', 'Strip Kron', 1, 'Strip crown'),
    ('kod', 'Subgingival Küretaj, Alt Sağ Çene', 1, 'Subgingival curettage, lower right quadrant'),
    ('kod', 'Subgingival Küretaj, Alt Sol Çene', 1, 'Subgingival curettage, lower left quadrant'),
    ('kod', 'Subgingival Küretaj, Üst Sağ Çene', 1, 'Subgingival curettage, upper right quadrant'),
    ('kod', 'Subgingival Küretaj, Üst Sol Çene', 1, 'Subgingival curettage, upper left quadrant'),
    ('kod', 'Subperiostal İmplant, Tek Ünite', 1, 'Subperiosteal implant, single unit'),
    ('kod', 'Supernumere Diş Çekimi, İnfiltrasyon Anestezi ile (Yarım Çene)', 1, 'Extraction of a supernumerary tooth, with infiltration anaesthesia (half arch)'),
    ('kod', 'Sürme Rehberliği', 1, 'Eruption guidance'),
    ('kod', 'T.M.E. Splint Yapımı', 1, 'Fabrication of a TMJ splint'),
    ('kod', 'Tahlil İşlemleri', 1, 'Laboratory procedures'),
    ('kod', 'Tam İdrar Analizi (Strip+mikroskopi)', 1, 'Complete urinalysis (dipstick + microscopy)'),
    ('kod', 'Tam Kan Sayımı (Hemogram)', 1, 'Full blood count'),
    ('kod', 'Tek Parça Döküm Kron', 1, 'One-piece cast crown'),
    ('kod', 'Teleskop Primer Kron, Kopingli', 1, 'Telescopic primary crown with coping'),
    ('kod', 'Temparomandibüler Eklem İçi Enjeksiyon, Tek Taraf', 1, 'Intra-articular TMJ injection, unilateral'),
    ('kod', 'Temparomandibüler Eklem Mekanoterapi', 1, 'TMJ mechanotherapy'),
    ('kod', 'Temporomandibüler Eklem (Tme) Filmi, Her Biri', 1, 'Temporomandibular joint (TMJ) radiograph, each'),
    ('kod', 'Tetkik ve Radyoloji Bilgileri', 1, 'Test and radiology information'),
    ('kod', 'TME Protezi fossa kompenenti uygulması tek taraflı', 1, 'TMJ prosthesis, fossa component, unilateral'),
    ('kod', 'TME Protezi ramus kompenenti uygulaması tek taraflı', 1, 'TMJ prosthesis, ramus component, unilateral'),
    ('kod', 'Torus Operasyonu, Yarım Çene', 1, 'Torus removal, half arch'),
    ('kod', 'Trombofili paneli (RT-PCR)', 1, 'Thrombophilia panel (RT-PCR)'),
    ('kod', 'Trombosit', 1, 'Platelets'),
    ('kod', 'Trombosit Dağılım Genişliği', 1, 'Platelet distribution width'),
    ('kod', 'Trombositkrit', 1, 'Plateletcrit'),
    ('kod', 'TSH', 1, 'TSH'),
    ('kod', 'TTB/HUV İşlemleri (SUT dışı)', 1, 'TTB/HUV procedures (outside SUT)'),
    ('kod', 'Tunnel Operasyonu, Her Bir Diş', 1, 'Tunnel preparation, per tooth'),
    ('kod', 'Tükürük Akış Hızı ve Tamponlama Kapasitesi tayini', 1, 'Salivary flow rate and buffering capacity assessment'),
    ('kod', 'Tükürük Bezi Kanalından Taş Çıkarma', 1, 'Removal of a stone from a salivary duct'),
    ('kod', 'Tükürükte Mikrobiyolojik Analiz', 1, 'Microbiological analysis of saliva'),
    ('kod', 'Üç boyutlu dijital ortodontik analiz', 1, 'Three-dimensional digital orthodontic analysis'),
    ('kod', 'Üç Boyutlu Dijital Ortodontik Model Hazırlanması (Tek Çene)', 1, 'Preparation of a three-dimensional digital orthodontic model (single arch)'),
    ('kod', 'Üç Boyutlu Katı Modelleme (Tek Çene)', 1, 'Three-dimensional solid modelling (single arch)'),
    ('kod', 'Üre', 1, 'Urea'),
    ('kod', 'Ürobilinojen (strip)', 1, 'Urobilinogen (dipstick)'),
    ('kod', 'Velum Uzantılı Konuşma Apereyi', 1, 'Speech appliance with velar extension'),
    ('kod', 'Veneer Kron, Akrilik', 1, 'Veneer crown, acrylic'),
    ('kod', 'Veneer Kron, Seramik', 1, 'Veneer crown, ceramic'),
    ('kod', 'Vestibüloplasti Operasyonu', 1, 'Vestibuloplasty'),
    ('kod', 'Vida Uygulaması (Tek Vida)', 1, 'Screw placement (single screw)'),
    ('kod', 'Vitalite Kontrolü', 1, 'Vitality test'),
    ('kod', 'Wilson Arkı Uygulaması', 1, 'Wilson arch placement'),
    ('kod', 'Yara kültürü', 1, 'Wound culture'),
    ('kod', 'Yarık Dudak -Damak veya Yarık Damak Daimi Dişlenme Dönemi Ortodontik Tedavi', 1, 'Orthodontic treatment of cleft lip/palate in the permanent dentition'),
    ('kod', 'Yarık Dudak -Damak veya Yarık Damak Doğum Sonrası Şekillendirme Tedavisi', 1, 'Post-natal moulding treatment for cleft lip/palate'),
    ('kod', 'Yarık Dudak -Damak veya Yarık Damak Karışık Dişlenme Dönemi Ortodontik Tedavi', 1, 'Orthodontic treatment of cleft lip/palate in the mixed dentition'),
    ('kod', 'Yatak İşlemleri', 1, 'Bed charges'),
    ('kod', 'Yeni Doğanda Preoperatif Aparey', 1, 'Pre-operative appliance in the newborn'),
    ('kod', 'Yer tutucu diş eti altı', 1, 'Subgingival space maintainer'),
    ('kod', 'Yer Tutucu, Hareketli', 1, 'Space maintainer, removable'),
    ('kod', 'Yer Tutucu, Sabit', 1, 'Space maintainer, fixed'),
    ('kod', 'Yerel Flor Uygulaması (Çürük Proflaksisi), Yarım Çene', 1, 'Topical fluoride application (caries prophylaxis), half arch'),
    ('kod', 'Yumuşak Doku Greftleme', 1, 'Soft tissue grafting'),
    ('kod', 'Yüz Protezleri', 1, 'Facial prostheses'),
    ('kod', 'Zirkonyum Kron (Her Bir Üye)', 1, 'Zirconia crown (per unit)'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 1. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 1'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 2. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 2'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 3. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 3'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 4. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 4'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 5. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 5'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 6. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 6'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 7. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 7'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 8. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 8'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 9. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 9'),
    ('kod', 'Ortodontik tedavi, Sınıf I - 10. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class I - review 10'),
    ('kod', 'Ortodontik tedavi, Sınıf I - Başlangıç', 1, 'Orthodontic treatment, Class I - initial'),
    ('kod', 'Ortodontik tedavi, Sınıf I - Pekiştirme', 1, 'Orthodontic treatment, Class I - retention'),
    ('kod', 'Ortodontik tedavi, Sınıf I - Tedavi', 1, 'Orthodontic treatment, Class I - active treatment'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 1. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 1'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 2. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 2'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 3. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 3'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 4. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 4'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 5. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 5'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 6. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 6'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 7. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 7'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 8. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 8'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 9. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 9'),
    ('kod', 'Ortodontik tedavi, Sınıf II - 10. Kontol Muayenesi', 1, 'Orthodontic treatment, Class II - review 10'),
    ('kod', 'Ortodontik tedavi, Sınıf II - Başlangıç', 1, 'Orthodontic treatment, Class II - initial'),
    ('kod', 'Ortodontik tedavi, Sınıf II - Pekiştirme', 1, 'Orthodontic treatment, Class II - retention'),
    ('kod', 'Ortodontik tedavi, Sınıf II - Tedavi', 1, 'Orthodontic treatment, Class II - active treatment'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 1. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 1'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 2. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 2'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 3. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 3'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 4. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 4'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 5. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 5'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 6. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 6'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 7. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 7'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 8. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 8'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 9. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 9'),
    ('kod', 'Ortodontik tedavi, Sınıf III - 10. Kontrol Muayenesi', 1, 'Orthodontic treatment, Class III - review 10'),
    ('kod', 'Ortodontik tedavi, Sınıf III - Başlangıç', 1, 'Orthodontic treatment, Class III - initial'),
    ('kod', 'Ortodontik tedavi, Sınıf III - Pekiştirme', 1, 'Orthodontic treatment, Class III - retention'),
    ('kod', 'Ortodontik tedavi, Sınıf III - Tedavi', 1, 'Orthodontic treatment, Class III - active treatment')
on conflict (kapsam, anahtar, dil) do update set metin = excluded.metin,
    degistirme_tarihi = now();

do $$
declare v_en integer; v_kalan integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    select count(distinct h.ad) into v_kalan
      from public.hizmet h
     where not exists (select 1 from public.ceviri c
                        where c.dil = 1 and c.anahtar = h.ad);
    raise notice '854 tamam: ingilizce sozluk % satir. Cevirisi olmayan hizmet adi: %.',
                 v_en, v_kalan;
end $$;
