-- ============================================================================
--  Gentegre AI — İLAÇ ADLARI İNGİLİZCE (856)
--  856_ingilizce_sozluk_ilac.sql
--
--  Kullanıcı: *"ilaç adlarını da çevir"*.
--
--  ============ İLAÇ ADI NEDEN BÜTÜN OLARAK ÇEVRİLMEDİ =============
--  `ilac` tablosunda 23.002 satır / 22.949 TEKİL ad var ve her ad şu
--  kalıptadır:  <MARKA> <doz> <FARMASÖTİK FORM>, <adet> <birim>
--      "RIPAZOL 15 MG AĞIZDA DAĞILAN TABLET, 28 ADET"
--  Çevrilebilir olan yalnız FORM kısmıdır. MARKA ADI (ÖZEL İSİM) VE DOZ
--  ÇEVRİLMEZ - "RIPAZOL" bir TİTCK ruhsat adıdır, çevrilirse ekranda olmayan
--  bir ilaç görünür. Bu yüzden sözlük TAM ADİ değil, adın içindeki
--  farmasötik form / uygulama yolu / ambalaj sözcüklerini taşır; istemci
--  adı parçalayıp EN UZUN eşleşen ifadeyi çevirir, tanımadığını aynen bırakır.
--      → "RIPAZOL 15 MG ORODISPERSIBLE TABLET, 28 UNITS"
--  Tam ad sözlüğe konsaydı 22.949 satır her istemciye indirilirdi.
--
--  ============ NE ÇEVRİLDİ ===========================================
--    · Farmasötik form / yol / ambalaj sözcükleri (182): "film kaplı tablet"
--      → film-coated tablet, "kullanıma hazır şirınga" → pre-filled syringe.
--      Kelime kelime çevrilince söz dizimi bozulan kalıplar BİLEŞİK anahtar
--      olarak yazıldı ("X içeren flakon" → "vial containing X").
--    · ETKEN MADDE (322): Türkçe yazım → ULUSLARARASI INN adı ("parasetamol"
--      → paracetamol, "sefdinir" → cefdinir). Bu bir çeviri değil, aynı
--      maddenin resmî İngilizce adıdır. Emin olunmayan ve çok bileşenli
--      kayıtlar TURKCE BIRAKILDI - etken madde adında tahmin yürütülmez.
--
--  ============ ANAHTAR BİÇİMİ ==========================================
--  Bu kapsamın anahtarı diğerlerinden FARKLI: küçük harfli ve Türkçe
--  harfleri ASCII'ye katlanmış ("film kapli tablet"). Veri tabanında aynı
--  sözcük FİLM/FILM, ÇÖZELTİ/ÇÖZELTI/COZELTI gibi 3-4 yazımla geçiyor;
--  katlanmış tek anahtar hepsini yakalar. İstemci de arama metnini aynı
--  şekilde katlar (`web/src/dil/ceviri.ts` → `ilacAdi`).
--
--  ============ REÇETE / MEDULA ETKİLENMEZ ==============================
--  Çeviri yalnız EKRAN içindir. e-Reçete, MEDULA ve İTS'ye giden ilaç adı
--  ile barkod sunucuda Türkçe/değişmeden kalır; `recete_satir.ilac_ad`
--  kaydı da Türkçe yazılır.
--
--  Idempotent (`on conflict do update`).
-- ============================================================================
\set ON_ERROR_STOP on

insert into public.ceviri (kapsam, anahtar, dil, metin) values
    ('ilac', 'abirateron asetat', 1, 'abiraterone acetate'),
    ('ilac', 'adalimumab', 1, 'adalimumab'),
    ('ilac', 'adet', 1, 'units'),
    ('ilac', 'adrenalin', 1, 'adrenaline'),
    ('ilac', 'agiz cozeltisi', 1, 'oral solution'),
    ('ilac', 'agiz gargarasi', 1, 'mouthwash'),
    ('ilac', 'agizda cozunen tablet', 1, 'orodispersible tablet'),
    ('ilac', 'agizda dagilan tablet', 1, 'orodispersible tablet'),
    ('ilac', 'akarboz', 1, 'acarbose'),
    ('ilac', 'alfa lipoik asit', 1, 'alpha lipoic acid'),
    ('ilac', 'alfa lipoik asit (tioktik asit)', 1, 'alpha lipoic acid (thioctic acid)'),
    ('ilac', 'amikasin', 1, 'amikacin'),
    ('ilac', 'amikasin sulfat', 1, 'amikacin sulfate'),
    ('ilac', 'amlodipin', 1, 'amlodipine'),
    ('ilac', 'amlodipin besilat', 1, 'amlodipine besilate'),
    ('ilac', 'amoksisilin', 1, 'amoxicillin'),
    ('ilac', 'amoksisilin trihidrat', 1, 'amoxicillin trihydrate'),
    ('ilac', 'amoksisilin ve klavulanik asit', 1, 'amoxicillin and clavulanic acid'),
    ('ilac', 'ampisilin', 1, 'ampicillin'),
    ('ilac', 'ampul', 1, 'ampoule'),
    ('ilac', 'apiksaban', 1, 'apixaban'),
    ('ilac', 'apremilast', 1, 'apremilast'),
    ('ilac', 'aripiprazol', 1, 'aripiprazole'),
    ('ilac', 'aripiprazol monohidrat', 1, 'aripiprazole monohydrate'),
    ('ilac', 'asetilsalisilik asit', 1, 'acetylsalicylic acid'),
    ('ilac', 'asetilsistein', 1, 'acetylcysteine'),
    ('ilac', 'asiklovir', 1, 'aciclovir'),
    ('ilac', 'aspartam', 1, 'aspartame'),
    ('ilac', 'atomoksetin hidroklorur', 1, 'atomoxetine hydrochloride'),
    ('ilac', 'atorvastatin', 1, 'atorvastatin'),
    ('ilac', 'atorvastatin kalsiyum', 1, 'atorvastatin calcium'),
    ('ilac', 'atorvastatin kalsiyum trihidrat', 1, 'atorvastatin calcium trihydrate'),
    ('ilac', 'atropin sulfat', 1, 'atropine sulfate'),
    ('ilac', 'azitromisin dihidrat', 1, 'azithromycin dihydrate'),
    ('ilac', 'baklofen', 1, 'baclofen'),
    ('ilac', 'basincli inhalasyon', 1, 'pressurised inhalation'),
    ('ilac', 'basincli inhalasyon cozelti', 1, 'pressurised inhalation, solution'),
    ('ilac', 'basincli inhalasyon suspansiyon', 1, 'pressurised inhalation, suspension'),
    ('ilac', 'beklometazon dipropiyonat', 1, 'beclometasone dipropionate'),
    ('ilac', 'benzidamin hcl', 1, 'benzydamine hydrochloride'),
    ('ilac', 'betahistin dihidroklorur', 1, 'betahistine dihydrochloride'),
    ('ilac', 'biotin', 1, 'biotin'),
    ('ilac', 'blister', 1, 'blister'),
    ('ilac', 'brimonidin tartarat', 1, 'brimonidine tartrate'),
    ('ilac', 'brivarasetam', 1, 'brivaracetam'),
    ('ilac', 'budesonid', 1, 'budesonide'),
    ('ilac', 'burun damlasi', 1, 'nasal drops'),
    ('ilac', 'burun jeli', 1, 'nasal gel'),
    ('ilac', 'burun spreyi', 1, 'nasal spray'),
    ('ilac', 'butamirat sitrat', 1, 'butamirate citrate'),
    ('ilac', 'cigneme tablet', 1, 'chewable tablet'),
    ('ilac', 'cigneme tableti', 1, 'chewable tablet'),
    ('ilac', 'cinko sulfat', 1, 'zinc sulfate'),
    ('ilac', 'cinko sulfat heptahidrat', 1, 'zinc sulfate heptahydrate'),
    ('ilac', 'cozelti', 1, 'solution'),
    ('ilac', 'cozelti hazirlamak icin granul', 1, 'granules for solution'),
    ('ilac', 'cozelti hazirlamak icin toz', 1, 'powder for solution'),
    ('ilac', 'cozelti iceren ampul', 1, 'ampoule containing solution'),
    ('ilac', 'cozelti iceren flakon', 1, 'vial containing solution'),
    ('ilac', 'cozeltisi', 1, 'solution'),
    ('ilac', 'cozucu', 1, 'solvent'),
    ('ilac', 'damla', 1, 'drops'),
    ('ilac', 'damlasi', 1, 'drops'),
    ('ilac', 'dapagliflozin', 1, 'dapagliflozin'),
    ('ilac', 'dapoksetin hidroklorur', 1, 'dapoxetine hydrochloride'),
    ('ilac', 'daptomisin', 1, 'daptomycin'),
    ('ilac', 'dasatinib', 1, 'dasatinib'),
    ('ilac', 'dasatinib monohidrat', 1, 'dasatinib monohydrate'),
    ('ilac', 'deferasiroks', 1, 'deferasirox'),
    ('ilac', 'degistirilmis salimli tablet', 1, 'modified-release tablet'),
    ('ilac', 'deksametazon', 1, 'dexamethasone'),
    ('ilac', 'deksketoprofen trometamol', 1, 'dexketoprofen trometamol'),
    ('ilac', 'deksketoprofen trometamol/tiyokolsikosid', 1, 'dexketoprofen trometamol/thiocolchicoside'),
    ('ilac', 'dekspantenol', 1, 'dexpanthenol'),
    ('ilac', 'dekstroz', 1, 'dextrose'),
    ('ilac', 'dekstroz anhidr', 1, 'dextrose anhydrous'),
    ('ilac', 'dekstroz anhidrat', 1, 'dextrose anhydrous'),
    ('ilac', 'dekstroz monohidrat', 1, 'dextrose monohydrate'),
    ('ilac', 'demir iii hidroksit polimaltoz kompleksi', 1, 'iron(III) hydroxide polymaltose complex'),
    ('ilac', 'deri spreyi', 1, 'skin spray'),
    ('ilac', 'deri uzerine uygulanan', 1, 'cutaneous'),
    ('ilac', 'desloratadin', 1, 'desloratadine'),
    ('ilac', 'desmopressin', 1, 'desmopressin'),
    ('ilac', 'diazepam', 1, 'diazepam'),
    ('ilac', 'diklofenak potasyum', 1, 'diclofenac potassium'),
    ('ilac', 'diklofenak sodyum', 1, 'diclofenac sodium'),
    ('ilac', 'dilalti tablet', 1, 'sublingual tablet'),
    ('ilac', 'dilalti tableti', 1, 'sublingual tablet'),
    ('ilac', 'diltiazem hcl', 1, 'diltiazem hydrochloride'),
    ('ilac', 'diltiazem hidroklorur', 1, 'diltiazem hydrochloride'),
    ('ilac', 'dimetil fumarat', 1, 'dimethyl fumarate'),
    ('ilac', 'dis macunu', 1, 'toothpaste'),
    ('ilac', 'diyaliz cozeltisi', 1, 'dialysis solution'),
    ('ilac', 'donepezil hcl', 1, 'donepezil hydrochloride'),
    ('ilac', 'donepezil hidroklorur', 1, 'donepezil hydrochloride'),
    ('ilac', 'dosetaksel', 1, 'docetaxel'),
    ('ilac', 'doz', 1, 'doses'),
    ('ilac', 'duloksetin hcl', 1, 'duloxetine hydrochloride'),
    ('ilac', 'duloksetin hidroklorur', 1, 'duloxetine hydrochloride'),
    ('ilac', 'efervesan granul', 1, 'effervescent granules'),
    ('ilac', 'efervesan tablet', 1, 'effervescent tablet'),
    ('ilac', 'eltrombopag olamin', 1, 'eltrombopag olamine'),
    ('ilac', 'empagliflozin', 1, 'empagliflozin'),
    ('ilac', 'emulsiyon', 1, 'emulsion'),
    ('ilac', 'enjeksiyon', 1, 'injection'),
    ('ilac', 'enjeksiyon icin cozelti', 1, 'solution for injection'),
    ('ilac', 'enjeksiyonluk', 1, 'for injection'),
    ('ilac', 'enjeksiyonluk cozelti', 1, 'solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti hazirlamak icin liyofilize toz', 1, 'lyophilised powder for solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti hazirlamak icin toz', 1, 'powder for solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti iceren ampul', 1, 'ampoule containing solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti iceren flakon', 1, 'vial containing solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti iceren kullanima hazir enjektor', 1, 'pre-filled syringe containing solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti iceren kullanima hazir kalem', 1, 'pre-filled pen containing solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti iceren kullanima hazir siringa', 1, 'pre-filled syringe containing solution for injection'),
    ('ilac', 'enjeksiyonluk cozelti icin toz', 1, 'powder for solution for injection'),
    ('ilac', 'enjeksiyonluk emulsiyon', 1, 'emulsion for injection'),
    ('ilac', 'enjeksiyonluk su', 1, 'water for injections'),
    ('ilac', 'enjeksiyonluk suspansiyon', 1, 'suspension for injection'),
    ('ilac', 'enjeksiyonluk toz iceren flakon', 1, 'vial containing powder for injection'),
    ('ilac', 'enjektabl', 1, 'injectable'),
    ('ilac', 'enjektabl cozelti', 1, 'solution for injection'),
    ('ilac', 'enjektabl cozelti iceren ampul', 1, 'ampoule containing solution for injection'),
    ('ilac', 'enjektabl cozelti iceren flakon', 1, 'vial containing solution for injection'),
    ('ilac', 'enjektabl solusyon', 1, 'solution for injection'),
    ('ilac', 'enjektabl solusyon iceren ampul', 1, 'ampoule containing solution for injection'),
    ('ilac', 'enjektabl solusyon iceren flakon', 1, 'vial containing solution for injection'),
    ('ilac', 'enjektabl toz', 1, 'powder for injection'),
    ('ilac', 'enjektabl toz iceren flakon', 1, 'vial containing powder for injection'),
    ('ilac', 'enjektor', 1, 'syringe'),
    ('ilac', 'enoksaparin sodyum', 1, 'enoxaparin sodium'),
    ('ilac', 'entekavir monohidrat', 1, 'entecavir monohydrate'),
    ('ilac', 'enterik kapli kapsul', 1, 'gastro-resistant capsule'),
    ('ilac', 'enterik kapli tablet', 1, 'gastro-resistant tablet'),
    ('ilac', 'epinefrin', 1, 'epinephrine'),
    ('ilac', 'epoetin alfa', 1, 'epoetin alfa'),
    ('ilac', 'epoetin zeta', 1, 'epoetin zeta'),
    ('ilac', 'erdostein', 1, 'erdosteine'),
    ('ilac', 'eritromisin', 1, 'erythromycin'),
    ('ilac', 'erlotinib hidroklorur', 1, 'erlotinib hydrochloride'),
    ('ilac', 'esmolol hidroklorur', 1, 'esmolol hydrochloride'),
    ('ilac', 'esomeprazol magnezyum dihidrat', 1, 'esomeprazole magnesium dihydrate'),
    ('ilac', 'esomeprazol sodyum', 1, 'esomeprazole sodium'),
    ('ilac', 'essitalopram', 1, 'escitalopram'),
    ('ilac', 'essitalopram oksalat', 1, 'escitalopram oxalate'),
    ('ilac', 'etanersept', 1, 'etanercept'),
    ('ilac', 'etodolak', 1, 'etodolac'),
    ('ilac', 'etofenamat', 1, 'etofenamate'),
    ('ilac', 'famotidin', 1, 'famotidine'),
    ('ilac', 'fampiridin', 1, 'fampridine'),
    ('ilac', 'feksofenadin hcl', 1, 'fexofenadine hydrochloride'),
    ('ilac', 'fenofibrat', 1, 'fenofibrate'),
    ('ilac', 'fentanil sitrat', 1, 'fentanyl citrate'),
    ('ilac', 'fentikonazol nitrat', 1, 'fenticonazole nitrate'),
    ('ilac', 'filgrastim', 1, 'filgrastim'),
    ('ilac', 'film kapli tablet', 1, 'film-coated tablet'),
    ('ilac', 'film tablet', 1, 'film-coated tablet'),
    ('ilac', 'fingolimod hidroklorur', 1, 'fingolimod hydrochloride'),
    ('ilac', 'fitil', 1, 'suppository'),
    ('ilac', 'flakon', 1, 'vial'),
    ('ilac', 'flaster', 1, 'patch'),
    ('ilac', 'florodeoksiglukoz', 1, 'fludeoxyglucose'),
    ('ilac', 'flukonazol', 1, 'fluconazole'),
    ('ilac', 'flurbiprofen', 1, 'flurbiprofen'),
    ('ilac', 'flutikazon propiyonat', 1, 'fluticasone propionate'),
    ('ilac', 'formoterol fumarat dihidrat', 1, 'formoterol fumarate dihydrate'),
    ('ilac', 'furosemid', 1, 'furosemide'),
    ('ilac', 'fusidik asit', 1, 'fusidic acid'),
    ('ilac', 'gabapentin', 1, 'gabapentin'),
    ('ilac', 'gadobutrol monohidrat', 1, 'gadobutrol monohydrate'),
    ('ilac', 'gargara', 1, 'mouthwash'),
    ('ilac', 'gemsitabin hidroklorur', 1, 'gemcitabine hydrochloride'),
    ('ilac', 'gentamisin', 1, 'gentamicin'),
    ('ilac', 'gentamisin sulfat', 1, 'gentamicin sulfate'),
    ('ilac', 'gliklazid', 1, 'gliclazide'),
    ('ilac', 'glimepirid', 1, 'glimepiride'),
    ('ilac', 'glimeprid', 1, 'glimepiride'),
    ('ilac', 'goz damlasi', 1, 'eye drops'),
    ('ilac', 'goz jeli', 1, 'eye gel'),
    ('ilac', 'goz merhemi', 1, 'eye ointment'),
    ('ilac', 'goz yikama cozeltisi', 1, 'eye wash solution'),
    ('ilac', 'granisetron', 1, 'granisetron'),
    ('ilac', 'granisetron hcl', 1, 'granisetron hydrochloride'),
    ('ilac', 'granisetron hidroklorur', 1, 'granisetron hydrochloride'),
    ('ilac', 'granul', 1, 'granules'),
    ('ilac', 'guanfasin hidroklorur', 1, 'guanfacine hydrochloride'),
    ('ilac', 'haloperidol', 1, 'haloperidol'),
    ('ilac', 'hazirlamak icin', 1, 'for preparation of'),
    ('ilac', 'hemodiyaliz cozeltisi', 1, 'haemodialysis solution'),
    ('ilac', 'ibandronik asit monosodyum tuzu monohidrat', 1, 'ibandronic acid monosodium salt monohydrate'),
    ('ilac', 'ibuprofen', 1, 'ibuprofen'),
    ('ilac', 'iceren', 1, 'containing'),
    ('ilac', 'iceren flakon', 1, 'vial'),
    ('ilac', 'icin', 1, 'for'),
    ('ilac', 'icinde', 1, 'in'),
    ('ilac', 'iloprost', 1, 'iloprost'),
    ('ilac', 'imatinib mesilat', 1, 'imatinib mesilate'),
    ('ilac', 'implant', 1, 'implant'),
    ('ilac', 'indapamid', 1, 'indapamide'),
    ('ilac', 'infuzyon', 1, 'infusion'),
    ('ilac', 'infuzyon icin cozelti', 1, 'solution for infusion'),
    ('ilac', 'infuzyon icin konsantre cozelti', 1, 'concentrate solution for infusion'),
    ('ilac', 'infuzyonluk', 1, 'for infusion'),
    ('ilac', 'infuzyonluk cozelti', 1, 'solution for infusion'),
    ('ilac', 'infuzyonluk cozelti hazirlamak icin konsantre', 1, 'concentrate for solution for infusion'),
    ('ilac', 'infuzyonluk cozelti hazirlamak icin liyofilize toz', 1, 'lyophilised powder for solution for infusion'),
    ('ilac', 'infuzyonluk cozelti hazirlamak icin toz', 1, 'powder for solution for infusion'),
    ('ilac', 'infuzyonluk cozelti iceren flakon', 1, 'vial containing solution for infusion'),
    ('ilac', 'infuzyonluk cozelti iceren torba', 1, 'bag containing solution for infusion'),
    ('ilac', 'infuzyonluk cozelti icin konsantre', 1, 'concentrate for solution for infusion'),
    ('ilac', 'inhalasyon', 1, 'inhalation'),
    ('ilac', 'inhalasyon icin cozelti', 1, 'solution for inhalation'),
    ('ilac', 'inhalasyon icin suspansiyon', 1, 'suspension for inhalation'),
    ('ilac', 'inhalasyon icin toz', 1, 'inhalation powder'),
    ('ilac', 'inhalasyon tozu', 1, 'inhalation powder'),
    ('ilac', 'insan albumini', 1, 'human albumin'),
    ('ilac', 'insan normal immunoglobulini', 1, 'human normal immunoglobulin'),
    ('ilac', 'insulin glarjin', 1, 'insulin glargine'),
    ('ilac', 'ioheksol', 1, 'iohexol'),
    ('ilac', 'iomeprol', 1, 'iomeprol'),
    ('ilac', 'iopamidol', 1, 'iopamidol'),
    ('ilac', 'iopromid', 1, 'iopromide'),
    ('ilac', 'irbesartan', 1, 'irbesartan'),
    ('ilac', 'irbesartan ve hidroklorotiyazid', 1, 'irbesartan and hydrochlorothiazide'),
    ('ilac', 'itrakonazol', 1, 'itraconazole'),
    ('ilac', 'ivermektin', 1, 'ivermectin'),
    ('ilac', 'iyoheksol', 1, 'iohexol'),
    ('ilac', 'jel', 1, 'gel'),
    ('ilac', 'kalem', 1, 'pen'),
    ('ilac', 'kalsitriol', 1, 'calcitriol'),
    ('ilac', 'kalsiyum asetat', 1, 'calcium acetate'),
    ('ilac', 'kalsiyum dobesilat monohidrat', 1, 'calcium dobesilate monohydrate'),
    ('ilac', 'kalsiyum karbonat', 1, 'calcium carbonate'),
    ('ilac', 'kalsiyum karbonat ve vitamin d3', 1, 'calcium carbonate and vitamin D3'),
    ('ilac', 'kalsiyum klorur dihidrat', 1, 'calcium chloride dihydrate'),
    ('ilac', 'kalsiyum polistiren sulfonat', 1, 'calcium polystyrene sulfonate'),
    ('ilac', 'kandesartan sileksetil', 1, 'candesartan cilexetil'),
    ('ilac', 'kapli tablet', 1, 'coated tablet'),
    ('ilac', 'kapsul', 1, 'capsule'),
    ('ilac', 'karboplatin', 1, 'carboplatin'),
    ('ilac', 'kartus', 1, 'cartridge'),
    ('ilac', 'karvedilol', 1, 'carvedilol'),
    ('ilac', 'kaspofungin asetat', 1, 'caspofungin acetate'),
    ('ilac', 'kavanoz', 1, 'jar'),
    ('ilac', 'ketiapin', 1, 'quetiapine'),
    ('ilac', 'ketiapin fumarat', 1, 'quetiapine fumarate'),
    ('ilac', 'ketiapin hemifumarat', 1, 'quetiapine hemifumarate'),
    ('ilac', 'ketoprofen', 1, 'ketoprofen'),
    ('ilac', 'klaritromisin', 1, 'clarithromycin'),
    ('ilac', 'klobetazol 17-propiyonat', 1, 'clobetasol 17-propionate'),
    ('ilac', 'klopidogrel bisulfat', 1, 'clopidogrel bisulfate'),
    ('ilac', 'kloramfenikol', 1, 'chloramphenicol'),
    ('ilac', 'kolekalsiferol (vitamin d3)', 1, 'colecalciferol (vitamin D3)'),
    ('ilac', 'konsantre', 1, 'concentrate'),
    ('ilac', 'kontrollu salimli tablet', 1, 'controlled-release tablet'),
    ('ilac', 'krem', 1, 'cream'),
    ('ilac', 'kulak damlasi', 1, 'ear drops'),
    ('ilac', 'kullanima hazir', 1, 'ready to use'),
    ('ilac', 'kullanima hazir enjektor', 1, 'pre-filled syringe'),
    ('ilac', 'kullanima hazir kalem', 1, 'pre-filled pen'),
    ('ilac', 'kullanima hazir siringa', 1, 'pre-filled syringe'),
    ('ilac', 'kuru toz', 1, 'dry powder'),
    ('ilac', 'kutanoz cozelti', 1, 'cutaneous solution'),
    ('ilac', 'kutanoz sprey', 1, 'cutaneous spray'),
    ('ilac', 'kutu', 1, 'box'),
    ('ilac', 'lakozamid', 1, 'lacosamide'),
    ('ilac', 'laktuloz', 1, 'lactulose'),
    ('ilac', 'lamotrijin', 1, 'lamotrigine'),
    ('ilac', 'lansoprazol', 1, 'lansoprazole'),
    ('ilac', 'lantanyum karbonat oktahidrat', 1, 'lanthanum carbonate octahydrate'),
    ('ilac', 'lavman', 1, 'enema'),
    ('ilac', 'leflunomid', 1, 'leflunomide'),
    ('ilac', 'lenalidomid', 1, 'lenalidomide'),
    ('ilac', 'levetirasetam', 1, 'levetiracetam'),
    ('ilac', 'levodropropizin', 1, 'levodropropizine'),
    ('ilac', 'levofloksasin hemihidrat', 1, 'levofloxacin hemihydrate'),
    ('ilac', 'levokarnitin', 1, 'levocarnitine'),
    ('ilac', 'levosetirizin dihidroklorur', 1, 'levocetirizine dihydrochloride'),
    ('ilac', 'levotiroksin sodyum', 1, 'levothyroxine sodium'),
    ('ilac', 'lidokain hidroklorur', 1, 'lidocaine hydrochloride'),
    ('ilac', 'linagliptin', 1, 'linagliptin'),
    ('ilac', 'linezolid', 1, 'linezolid'),
    ('ilac', 'liyofilize', 1, 'lyophilised'),
    ('ilac', 'liyofilize toz', 1, 'lyophilised powder'),
    ('ilac', 'liyofilize toz iceren flakon', 1, 'vial containing lyophilised powder'),
    ('ilac', 'lornoksikam', 1, 'lornoxicam'),
    ('ilac', 'losartan potasyum', 1, 'losartan potassium'),
    ('ilac', 'losyon', 1, 'lotion'),
    ('ilac', 'lurasidon hidroklorur', 1, 'lurasidone hydrochloride'),
    ('ilac', 'magnezyum klorur hekzahidrat', 1, 'magnesium chloride hexahydrate'),
    ('ilac', 'mannitol', 1, 'mannitol'),
    ('ilac', 'melatonin', 1, 'melatonin'),
    ('ilac', 'meloksikam', 1, 'meloxicam'),
    ('ilac', 'memantin hcl', 1, 'memantine hydrochloride'),
    ('ilac', 'memantin hidroklorur', 1, 'memantine hydrochloride'),
    ('ilac', 'merhem', 1, 'ointment'),
    ('ilac', 'meropenem trihidrat', 1, 'meropenem trihydrate'),
    ('ilac', 'mesalazin', 1, 'mesalazine'),
    ('ilac', 'metamizol sodyum', 1, 'metamizole sodium'),
    ('ilac', 'metformin hcl', 1, 'metformin hydrochloride'),
    ('ilac', 'metformin hidroklorur', 1, 'metformin hydrochloride'),
    ('ilac', 'metilfenidat hcl', 1, 'methylphenidate hydrochloride'),
    ('ilac', 'metilprednizolon', 1, 'methylprednisolone'),
    ('ilac', 'metoprolol tartarat', 1, 'metoprolol tartrate'),
    ('ilac', 'metotreksat', 1, 'methotrexate'),
    ('ilac', 'metotreksat disodyum', 1, 'methotrexate disodium'),
    ('ilac', 'metronidazol', 1, 'metronidazole'),
    ('ilac', 'midazolam', 1, 'midazolam'),
    ('ilac', 'mide asidine dayanikli tablet', 1, 'gastro-resistant tablet'),
    ('ilac', 'miglitol', 1, 'miglitol'),
    ('ilac', 'mikafungin sodyum', 1, 'micafungin sodium'),
    ('ilac', 'mikropellet kapsul', 1, 'pellet capsule'),
    ('ilac', 'minoksidil', 1, 'minoxidil'),
    ('ilac', 'mirabegron', 1, 'mirabegron'),
    ('ilac', 'mirtazapin', 1, 'mirtazapine'),
    ('ilac', 'modafinil', 1, 'modafinil'),
    ('ilac', 'moksifloksasin hidroklorur', 1, 'moxifloxacin hydrochloride'),
    ('ilac', 'mometazon furoat', 1, 'mometasone furoate'),
    ('ilac', 'montelukast', 1, 'montelukast'),
    ('ilac', 'montelukast sodyum', 1, 'montelukast sodium'),
    ('ilac', 'naftifin hidroklorur', 1, 'naftifine hydrochloride'),
    ('ilac', 'naproksen', 1, 'naproxen'),
    ('ilac', 'naproksen sodyum', 1, 'naproxen sodium'),
    ('ilac', 'nateglinid', 1, 'nateglinide'),
    ('ilac', 'nebivolol hcl', 1, 'nebivolol hydrochloride'),
    ('ilac', 'nebulizasyon icin', 1, 'for nebulisation'),
    ('ilac', 'nebulizasyon icin cozelti', 1, 'solution for nebulisation'),
    ('ilac', 'nebulizator', 1, 'nebuliser'),
    ('ilac', 'nimesulid', 1, 'nimesulide'),
    ('ilac', 'ofloksasin', 1, 'ofloxacin'),
    ('ilac', 'okzaliplatin', 1, 'oxaliplatin'),
    ('ilac', 'olanzapin', 1, 'olanzapine'),
    ('ilac', 'olmesartan medoksomil', 1, 'olmesartan medoxomil'),
    ('ilac', 'olmesartan medoksomil/hidroklorotiyazid', 1, 'olmesartan medoxomil/hydrochlorothiazide'),
    ('ilac', 'omeprazol', 1, 'omeprazole'),
    ('ilac', 'ondansetron', 1, 'ondansetron'),
    ('ilac', 'ondansetron hidroklorur dihidrat', 1, 'ondansetron hydrochloride dihydrate'),
    ('ilac', 'oral', 1, 'oral'),
    ('ilac', 'oral cozelti', 1, 'oral solution'),
    ('ilac', 'oral cozelti hazirlamak icin granul', 1, 'granules for oral solution'),
    ('ilac', 'oral cozelti hazirlamak icin toz', 1, 'powder for oral solution'),
    ('ilac', 'oral damla', 1, 'oral drops'),
    ('ilac', 'oral damla cozelti', 1, 'oral drops, solution'),
    ('ilac', 'oral sprey', 1, 'oral spray'),
    ('ilac', 'oral suspansiyon', 1, 'oral suspension'),
    ('ilac', 'oral suspansiyon hazirlamak icin granul', 1, 'granules for oral suspension'),
    ('ilac', 'oral suspansiyon hazirlamak icin kuru toz', 1, 'dry powder for oral suspension'),
    ('ilac', 'oral suspansiyon hazirlamak icin toz', 1, 'powder for oral suspension'),
    ('ilac', 'oral toz', 1, 'oral powder'),
    ('ilac', 'ornidazol', 1, 'ornidazole'),
    ('ilac', 'oseltamivir fosfat', 1, 'oseltamivir phosphate'),
    ('ilac', 'paklitaksel', 1, 'paclitaxel'),
    ('ilac', 'palbosiklib', 1, 'palbociclib'),
    ('ilac', 'paliperidon palmitat', 1, 'paliperidone palmitate'),
    ('ilac', 'pantoprazol', 1, 'pantoprazole'),
    ('ilac', 'pantoprazol sodyum seskihidrat', 1, 'pantoprazole sodium sesquihydrate'),
    ('ilac', 'papaverin hcl', 1, 'papaverine hydrochloride'),
    ('ilac', 'parasetamol', 1, 'paracetamol'),
    ('ilac', 'parikalsitol', 1, 'paricalcitol'),
    ('ilac', 'paroksetin hidroklorur', 1, 'paroxetine hydrochloride'),
    ('ilac', 'pastil', 1, 'lozenge'),
    ('ilac', 'pediyatrik', 1, 'paediatric'),
    ('ilac', 'pellet', 1, 'pellets'),
    ('ilac', 'periton diyaliz cozeltisi', 1, 'peritoneal dialysis solution'),
    ('ilac', 'periton diyaliz solusyonu', 1, 'peritoneal dialysis solution'),
    ('ilac', 'peritoneal diyaliz solusyonu', 1, 'peritoneal dialysis solution'),
    ('ilac', 'permetrin', 1, 'permethrin'),
    ('ilac', 'pinaveryum bromur', 1, 'pinaverium bromide'),
    ('ilac', 'pioglitazon hcl', 1, 'pioglitazone hydrochloride'),
    ('ilac', 'pioglitazon hidroklorur', 1, 'pioglitazone hydrochloride'),
    ('ilac', 'pirasetam', 1, 'piracetam'),
    ('ilac', 'pitavastatin kalsiyum', 1, 'pitavastatin calcium'),
    ('ilac', 'pomat', 1, 'ointment'),
    ('ilac', 'posakonazol', 1, 'posaconazole'),
    ('ilac', 'potasyum klorur', 1, 'potassium chloride'),
    ('ilac', 'pramipeksol dihidroklorur monohidrat', 1, 'pramipexole dihydrochloride monohydrate'),
    ('ilac', 'pravastatin sodyum', 1, 'pravastatin sodium'),
    ('ilac', 'pregabalin', 1, 'pregabalin'),
    ('ilac', 'progesteron', 1, 'progesterone'),
    ('ilac', 'propofol', 1, 'propofol'),
    ('ilac', 'rabeprazol sodyum', 1, 'rabeprazole sodium'),
    ('ilac', 'ramipril', 1, 'ramipril'),
    ('ilac', 'rasajilin mesilat', 1, 'rasagiline mesilate'),
    ('ilac', 'rektal', 1, 'rectal'),
    ('ilac', 'rektal supozituvar', 1, 'rectal suppository'),
    ('ilac', 'repaglinid', 1, 'repaglinide'),
    ('ilac', 'rifampisin', 1, 'rifampicin'),
    ('ilac', 'riociguat', 1, 'riociguat'),
    ('ilac', 'risedronat sodyum', 1, 'risedronate sodium'),
    ('ilac', 'risperidon', 1, 'risperidone'),
    ('ilac', 'rivaroksaban', 1, 'rivaroxaban'),
    ('ilac', 'rivastigmin hidrojen tartarat', 1, 'rivastigmine hydrogen tartrate'),
    ('ilac', 'rokuronyum bromur', 1, 'rocuronium bromide'),
    ('ilac', 'rosuvastatin', 1, 'rosuvastatin'),
    ('ilac', 'rosuvastatin kalsiyum', 1, 'rosuvastatin calcium'),
    ('ilac', 's-etodolak', 1, 'S-etodolac'),
    ('ilac', 'salbutamol', 1, 'salbutamol'),
    ('ilac', 'salbutamol sulfat', 1, 'salbutamol sulfate'),
    ('ilac', 'salmeterol ksinafoat/flutikazon propiyonat', 1, 'salmeterol xinafoate/fluticasone propionate'),
    ('ilac', 'sampuan', 1, 'shampoo'),
    ('ilac', 'sase', 1, 'sachet'),
    ('ilac', 'sefazolin sodyum', 1, 'cefazolin sodium'),
    ('ilac', 'sefdinir', 1, 'cefdinir'),
    ('ilac', 'sefiksim', 1, 'cefixime'),
    ('ilac', 'sefiksim trihidrat', 1, 'cefixime trihydrate'),
    ('ilac', 'sefotaksim sodyum', 1, 'cefotaxime sodium'),
    ('ilac', 'sefpodoksim proksetil', 1, 'cefpodoxime proxetil'),
    ('ilac', 'sefprozil', 1, 'cefprozil'),
    ('ilac', 'sefprozil monohidrat', 1, 'cefprozil monohydrate'),
    ('ilac', 'seftriakson sodyum', 1, 'ceftriaxone sodium'),
    ('ilac', 'sefuroksim aksetil', 1, 'cefuroxime axetil'),
    ('ilac', 'sefuroksim sodyum', 1, 'cefuroxime sodium'),
    ('ilac', 'seleksipag', 1, 'selexipag'),
    ('ilac', 'semaglutid', 1, 'semaglutide'),
    ('ilac', 'sert kapsul', 1, 'hard capsule'),
    ('ilac', 'setirizin dihidroklorur', 1, 'cetirizine dihydrochloride'),
    ('ilac', 'setli', 1, 'with set'),
    ('ilac', 'setsiz', 1, 'without set'),
    ('ilac', 'siklosporin', 1, 'ciclosporin'),
    ('ilac', 'sildenafil', 1, 'sildenafil'),
    ('ilac', 'sildenafil sitrat', 1, 'sildenafil citrate'),
    ('ilac', 'simetikon', 1, 'simeticone'),
    ('ilac', 'siprofloksasin', 1, 'ciprofloxacin'),
    ('ilac', 'siprofloksasin hidroklorur', 1, 'ciprofloxacin hydrochloride'),
    ('ilac', 'siprofloksasin laktat', 1, 'ciprofloxacin lactate'),
    ('ilac', 'siringa', 1, 'syringe'),
    ('ilac', 'sise', 1, 'bottle'),
    ('ilac', 'sitagliptin hidroklorur monohidrat', 1, 'sitagliptin hydrochloride monohydrate'),
    ('ilac', 'sitarabin', 1, 'cytarabine'),
    ('ilac', 'sodyum bikarbonat', 1, 'sodium bicarbonate'),
    ('ilac', 'sodyum fusidat', 1, 'sodium fusidate'),
    ('ilac', 'sodyum iyodur (131i)', 1, 'sodium iodide (131I)'),
    ('ilac', 'sodyum klorur', 1, 'sodium chloride'),
    ('ilac', 'sodyum laktat', 1, 'sodium lactate'),
    ('ilac', 'sodyum valproat', 1, 'sodium valproate'),
    ('ilac', 'solifenasin suksinat', 1, 'solifenacin succinate'),
    ('ilac', 'solusyon', 1, 'solution'),
    ('ilac', 'somatropin', 1, 'somatropin'),
    ('ilac', 'spiramisin', 1, 'spiramycin'),
    ('ilac', 'steril', 1, 'sterile'),
    ('ilac', 'sudaki', 1, 'in water'),
    ('ilac', 'sudaki cozeltisi', 1, 'solution in water'),
    ('ilac', 'sugammadeks sodyum', 1, 'sugammadex sodium'),
    ('ilac', 'sultamisilin', 1, 'sultamicillin'),
    ('ilac', 'sunitinib malat', 1, 'sunitinib malate'),
    ('ilac', 'supozituvar', 1, 'suppository'),
    ('ilac', 'surup', 1, 'syrup'),
    ('ilac', 'suspansiyon', 1, 'suspension'),
    ('ilac', 'suspansiyon hazirlamak icin granul', 1, 'granules for oral suspension'),
    ('ilac', 'suspansiyon hazirlamak icin kuru toz', 1, 'dry powder for oral suspension'),
    ('ilac', 'suspansiyon hazirlamak icin toz', 1, 'powder for oral suspension'),
    ('ilac', 'tablet', 1, 'tablet'),
    ('ilac', 'tadalafil', 1, 'tadalafil'),
    ('ilac', 'takrolimus monohidrat', 1, 'tacrolimus monohydrate'),
    ('ilac', 'tamsulosin hidroklorur', 1, 'tamsulosin hydrochloride'),
    ('ilac', 'teikoplanin', 1, 'teicoplanin'),
    ('ilac', 'telmisartan', 1, 'telmisartan'),
    ('ilac', 'telmisartan ve hidroklorotiyazid', 1, 'telmisartan and hydrochlorothiazide'),
    ('ilac', 'temozolomid', 1, 'temozolomide'),
    ('ilac', 'tenofovir disoproksil fumarat', 1, 'tenofovir disoproxil fumarate'),
    ('ilac', 'tenoksikam', 1, 'tenoxicam'),
    ('ilac', 'terbinafin hcl', 1, 'terbinafine hydrochloride'),
    ('ilac', 'terbinafin hidroklorur', 1, 'terbinafine hydrochloride'),
    ('ilac', 'tigesiklin', 1, 'tigecycline'),
    ('ilac', 'tikagrelor', 1, 'ticagrelor'),
    ('ilac', 'tirzepatid', 1, 'tirzepatide'),
    ('ilac', 'tiyokolsikosid', 1, 'thiocolchicoside'),
    ('ilac', 'tobramisin', 1, 'tobramycin'),
    ('ilac', 'tolterodin tartarat', 1, 'tolterodine tartrate'),
    ('ilac', 'tolvaptan', 1, 'tolvaptan'),
    ('ilac', 'topiramat', 1, 'topiramate'),
    ('ilac', 'torasemid', 1, 'torasemide'),
    ('ilac', 'torba', 1, 'bag'),
    ('ilac', 'toz', 1, 'powder'),
    ('ilac', 'toz iceren flakon', 1, 'vial containing powder'),
    ('ilac', 'traneksamik asit', 1, 'tranexamic acid'),
    ('ilac', 'transdermal flaster', 1, 'transdermal patch'),
    ('ilac', 'trimebutin maleat', 1, 'trimebutine maleate'),
    ('ilac', 'trimetazidin dihidroklorur', 1, 'trimetazidine dihydrochloride'),
    ('ilac', 'tup', 1, 'tube'),
    ('ilac', 'ure', 1, 'urea'),
    ('ilac', 'ursodeoksikolik asit', 1, 'ursodeoxycholic acid'),
    ('ilac', 'uzatilmis salimli enjeksiyonluk cozelti', 1, 'prolonged-release solution for injection'),
    ('ilac', 'uzatilmis salimli enjeksiyonluk cozelti iceren kullanima hazir siringa', 1, 'pre-filled syringe containing prolonged-release solution for injection'),
    ('ilac', 'uzatilmis salimli enjeksiyonluk suspansiyon', 1, 'prolonged-release suspension for injection'),
    ('ilac', 'uzatilmis salimli kapsul', 1, 'prolonged-release capsule'),
    ('ilac', 'uzatilmis salimli tablet', 1, 'prolonged-release tablet'),
    ('ilac', 'vajinal krem', 1, 'vaginal cream'),
    ('ilac', 'vajinal ovul', 1, 'pessary'),
    ('ilac', 'vajinal suppozituvar', 1, 'pessary'),
    ('ilac', 'vajinal tablet', 1, 'vaginal tablet'),
    ('ilac', 'valsartan', 1, 'valsartan'),
    ('ilac', 'valsartan + hidroklorotiyazid', 1, 'valsartan + hydrochlorothiazide'),
    ('ilac', 'valsartan/hidroklorotiyazid', 1, 'valsartan/hydrochlorothiazide'),
    ('ilac', 'vankomisin hidroklorur', 1, 'vancomycin hydrochloride'),
    ('ilac', 've', 1, 'and'),
    ('ilac', 'venlafaksin hcl', 1, 'venlafaxine hydrochloride'),
    ('ilac', 'vildagliptin', 1, 'vildagliptin'),
    ('ilac', 'vitamin d3', 1, 'vitamin D3'),
    ('ilac', 'vitamin d3 (kolekalsiferol)', 1, 'vitamin D3 (colecalciferol)'),
    ('ilac', 'vorikonazol', 1, 'voriconazole'),
    ('ilac', 'yumusak jelatin kapsul', 1, 'soft gelatin capsule'),
    ('ilac', 'yumusak kapsul', 1, 'soft capsule'),
    ('ilac', 'zoledronik asit monohidrat', 1, 'zoledronic acid monohydrate')
on conflict (kapsam, anahtar, dil) do update set metin = excluded.metin,
    degistirme_tarihi = now();

do $$
declare v_en integer; v_ilac integer; v_etken integer;
begin
    select count(*) into v_en from public.ceviri where dil = 1;
    select count(*) into v_ilac from public.ceviri where dil = 1 and kapsam = 'ilac';
    -- Karşılığı olmayan etken madde ekranda Türkçe kalır.
    select count(*) into v_etken from public.ilac i
     where i.etken_madde <> ''
       and not exists (select 1 from public.ceviri c
                        where c.dil = 1 and c.kapsam = 'ilac'
                          -- 'I' de katlanir: ICU tr-TR'de lower('I') = 'i'
                          --   degil 'i' yerine noktasiz 'i' uretir.
                          and c.anahtar = lower(translate(i.etken_madde,
                              'ıİIşŞçÇöÖüÜğĞ', 'iiissccoouugg')));
    raise notice '856 tamam: ingilizce sozluk % satir (ilac kapsami %). Cevirisi olmayan etken madde satiri: %.',
                 v_en, v_ilac, v_etken;
end $$;
