# ============================================================
# seed_bulk.ps1 — Config/referans tablolarini (<= MaxRows satir) MSSQL'den PG'ye toplu kopyalar
# ------------------------------------------------------------
# Bos tablolari ve MaxRows ustunu ATLAR. ID'ler AYNEN (GENERATED BY DEFAULT). bit->0/1,
# varbinary->bytea(hex), UTF-8 (docker cp + psql -f). Her tablo ayri; hatali tabloyu atlar,
# raporlar. Sonda identity sequence'lari setval eder.
#   powershell -File pg\tools\seed_bulk.ps1 -MaxRows 20000
# ============================================================
param(
  [int]$MaxRows = 20000,
  [string[]]$Exclude = @(),
  [string]$MssqlServer='DESKTOP-HL3J3AS\SQLEXPRESS', [string]$MssqlDb='BILIM',
  [string]$MssqlUser='sa', [string]$MssqlPass='FETAGEN',
  [string]$PgContainer='gentegre-pg', [string]$PgDb='gentegre', [string]$PgSchema='public',
  [string]$PgUser='postgres', [string]$PgPass='FETAGEN'
)
$ErrorActionPreference='Stop'
[Console]::OutputEncoding=[System.Text.Encoding]::UTF8
function LI([string]$s){return $s.ToLowerInvariant()}
function PgLit([object]$v){
  if($null -eq $v -or $v -is [DBNull]){return 'NULL'}
  if($v -is [bool]){if($v){return '1'}else{return '0'}}
  if($v -is [byte[]]){return "decode('"+([System.BitConverter]::ToString($v).Replace('-',''))+"','hex')"}
  if($v -is [datetime]){return "'"+$v.ToString('yyyy-MM-dd HH:mm:ss.fff')+"'"}
  if($v -is [int] -or $v -is [long] -or $v -is [decimal] -or $v -is [double] -or $v -is [single] -or $v -is [byte] -or $v -is [int16]){return ([string]$v).Replace(',','.')}
  if($v -is [Guid]){return "'"+$v.ToString()+"'"}
  return "'"+([string]$v).Replace("'","''")+"'"
}
$cn=New-Object System.Data.SqlClient.SqlConnection("Server=$MssqlServer;Database=$MssqlDb;User Id=$MssqlUser;Password=$MssqlPass;TrustServerCertificate=True;")
$cn.Open();$c=$cn.CreateCommand()
# hedef tablolar: 0 < satir <= MaxRows
$c.CommandText="SELECT t.name, SUM(p.rows) r FROM sys.tables t JOIN sys.partitions p ON p.object_id=t.object_id AND p.index_id IN(0,1) WHERE t.schema_id=SCHEMA_ID('dbo') GROUP BY t.name HAVING SUM(p.rows) BETWEEN 1 AND $MaxRows ORDER BY r"
$rd=$c.ExecuteReader();$tabs=@();while($rd.Read()){$tabs+=[string]$rd[0]};$rd.Close()
$tabs=$tabs|?{$Exclude -notcontains $_}
Write-Host ("Seed edilecek: {0} tablo (<= {1} satir)" -f $tabs.Count,$MaxRows) -ForegroundColor Cyan
$ok=0;$fail=@();$seqTabs=@()
foreach($t in $tabs){
  $tl=LI $t
  # PG hedef kolonlari (kucuk)
  $pgCols=(docker exec -e "PGPASSWORD=$PgPass" $PgContainer psql -U $PgUser -d $PgDb -tAc "SELECT string_agg(column_name,',' ORDER BY ordinal_position) FROM information_schema.columns WHERE table_schema='$PgSchema' AND table_name='$tl'")
  if(-not $pgCols){$fail+="$t (PG'de yok)";continue}
  $pgSet=@{}; ($pgCols.Trim().Split(',')|%{$pgSet[$_.Trim()]=1})
  # MSSQL kolonlar (gercek ad, sirali) + identity var mi
  $c.CommandText="SELECT c.name, c.is_identity FROM sys.columns c WHERE c.object_id=OBJECT_ID('dbo.$t') ORDER BY c.column_id"
  $r2=$c.ExecuteReader();$cols=@();$hasIdent=$false
  while($r2.Read()){ $nm=[string]$r2['name']; if([bool]$r2['is_identity']){$hasIdent=$true}; if($pgSet.ContainsKey((LI $nm))){$cols+=$nm} }
  $r2.Close()
  if(-not $cols){$fail+="$t (kolon yok)";continue}
  $colList=($cols|%{'"'+(LI $_)+'"'}) -join ','
  $sel="SELECT ["+($cols -join '],[')+"] FROM [dbo].[$t]"
  $c.CommandText=$sel;$r3=$c.ExecuteReader()
  $sb=New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("TRUNCATE TABLE $PgSchema.$tl CASCADE;")
  $n=0
  while($r3.Read()){
    $vals=@();for($i=0;$i -lt $cols.Count;$i++){$vals+=PgLit $r3.GetValue($i)}
    [void]$sb.AppendLine("INSERT INTO $PgSchema.$tl ($colList) VALUES ("+($vals -join ',')+");")
    $n++
  }
  $r3.Close()
  $tmp=[System.IO.Path]::GetTempFileName()
  [System.IO.File]::WriteAllText($tmp,$sb.ToString(),(New-Object System.Text.UTF8Encoding($false)))
  docker cp $tmp "${PgContainer}:/tmp/seed_$tl.sql" | Out-Null
  $res=docker exec -e "PGPASSWORD=$PgPass" -e "PGCLIENTENCODING=UTF8" $PgContainer psql -U $PgUser -d $PgDb -v ON_ERROR_STOP=1 -q -f "/tmp/seed_$tl.sql" 2>&1
  Remove-Item $tmp -Force
  if($LASTEXITCODE -eq 0){ $ok++; if($hasIdent){$seqTabs+=$tl}; Write-Host ("  OK  {0} ({1})" -f $t,$n) }
  else { $fail+="$t : "+(($res|Select-Object -First 1)); Write-Host ("  HATA {0}" -f $t) -ForegroundColor Yellow }
}
$cn.Close()
# identity sequence'lari duzelt
foreach($tl in $seqTabs){
  docker exec -e "PGPASSWORD=$PgPass" $PgContainer psql -U $PgUser -d $PgDb -tAc "SELECT setval(pg_get_serial_sequence('$tl','id'), GREATEST((SELECT COALESCE(MAX(id),0) FROM $tl),1)) WHERE pg_get_serial_sequence('$tl','id') IS NOT NULL" 2>&1 | Out-Null
}
Write-Host ("`n=== BITTI: {0} basarili, {1} hata ===" -f $ok,$fail.Count) -ForegroundColor Green
if($fail){Write-Host "HATALAR:" -ForegroundColor Yellow; $fail|Select-Object -First 30|%{Write-Host ("  "+$_)}}
